### ISSUE TITLE
Storage Commitment: How to deal with N-EVENT Report Requests in DicomClient?

### ISSUE THREAD

**Issue by Johannes-sg** [fo-dicom/fo-dicom#1001]
### Expected behavior
I'm currently implementing a Storage Commitment SCU - so far so good. The only thing that I can't really get to work properly is to deal with N-EVENT Report Requests on the same association as the N-Action request/respones.
See Dicom Standard PS3.4  **J.3.3.1.2 Service Class Provider Behavior**:

> Note
> 
> 1.
> The SCP may attempt to issue the N-EVENT-REPORT on the same Association, but this operation may fail because the SCU is free to release at any time the Association on which it sent the N-ACTION-Request. As DICOM defaults the association requestor to the SCU role, the SCP (i.e., the association requester) negotiates an SCP role using the SCU/SCP role negotiation (see PS3.7).

It would be OK for me if the DicomClient sends an AssociationReject, or just closes the association without having an exception.
**Ideally I would like to know if there is a way I can handle this "event".** 
In my workflow I have a separate Storage Commitment listener for receiving N-EVENT Reports at any time.

### Actual behavior
A DicomNetworkException is thrown with message "N-Service SCP not implemented"

### Steps to reproduce the behavior
I was using a DVTK script serving as a Storage Commitment SCP, which expects an N-Action Request, sends an N-Action Response and immediately tries to send the N-EVENT Report afterwards (in the same association).
FO Dicom:
Setup a DicomClient to send an N-Action Request and receive an N-Action Response. 

### fo-dicom version and OS/platform
fo dicom 4.04 / Windows 10

**Comment by Johannes-sg** [comment]
Currently I only see the possibility to check the exception from the DicomClient like 
` if (ex.Message == "N-Service SCP not implemented")
 { // handle }`
Of course the toolkit will still log error messages like "An error occurred while we had an active connection, cleaning that up first", which is not nice since we redirect these logs to our logs.
Is there a more sophisticated way to solve this problem?

**Comment by gofal** [comment]
This will be a great enhancement, but I would do this in next version 5.

Take a look here: https://github.com/rickardraysearch/fo-dicom/tree/dimse_n_client_support
Mr Holmberg already did some work in this direction. If you build the source yourself, you can cherrypick his changes into the current code.
If you then find the code stable enough, it can be merged into fo-dicom 4

**Comment by Johannes-sg** [comment]
Thank you very much! I will have a look at it.
