### ISSUE TITLE
Does not support Jpeg2000 decompression?

### ISSUE THREAD

**Issue by cslee99** [fo-dicom/fo-dicom#1004]
### Expected behavior
Jpeg2000 decompression

### Actual behavior
Error in JPEG 2000 code stream!

   at Dicom.Imaging.Codec.DicomJpeg2000NativeCodec.Decode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters)
   at Dicom.Imaging.Codec.DicomTranscoder.Decode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)
   at Dicom.Imaging.Codec.DicomTranscoder.Transcode(DicomDataset dataset)
   at Dicom.Imaging.Codec.DicomTranscoder.Transcode(DicomFile file)
   at DCMTool.frmMain.searchFolderFiles(Object folderList) in D:\Dev\DICOM_Decompressor\DCMDecompressor\Form1.cs:line 225

### Steps to reproduce the behavior
original file : JPEG 2000 Image Compression (Lossless Only)
source : 
var transcoder = new DicomTranscoder(file.Dataset.InternalTransferSyntax, DicomTransferSyntax.ExplicitVRLittleEndian);
file = transcoder.Transcode(file);
file.Save(saveFilePath);

build environment : Debug x64 or Release x64

### fo-dicom version and OS/platform
windows10, etc windows

**Comment by gofal** [comment]
Are you using fo-dicom.Desktop or fo-dicom.NetCore? 

Are you using the codec shipped with fo-dicom, or are you already using the codecs from Efferent (https://www.nuget.org/packages/Efferent.Native/)

which other viewers are able to open the file (to make sure the file is not corrupt)?

**Comment by cslee99** [comment]
> Are you using fo-dicom.Desktop or fo-dicom.NetCore?
> 
> Are you using the codec shipped with fo-dicom, or are you already using the codecs from Efferent (https://www.nuget.org/packages/Efferent.Native/)
> 
> which other viewers are able to open the file (to make sure the file is not corrupt)?

**Comment by cslee99** [comment]
Yes, I'm using Dicom.Core, Dicom.Native64 with nuget (fo-dicom.Desktop : v4.0.4.0)
Another process is not using the file.
Efferent.Native is not used.
Efferent.Native support decompression?
  :: JPEG 2000 Image Compression (Lossless Only) ==> ExplicitVRLittleEndian

**Comment by gofal** [comment]
> Another process is not using the file.

i did not mean the IO access. This would give you an other error message. i mean, if you are able to take the file and open it in some other viewing application. It may be, that the file is corrupt and contains some invalid jpeg stream.

Of course Efferent supports decompression. This library will be the go-forward code for codec
