### ISSUE TITLE
Convert Avi to Dicom

### ISSUE THREAD

**Issue by alanhmartins** [fo-dicom/fo-dicom#1007]
Is it possible to convert an AVI video to VDicom?

**Comment by gofal** [comment]
DICOM standard only supports MPEG2 Main Profile, MPEG-4 AVC/H.264, and HEVC/H.265.

this library supports you to encapsulate your mpeg-stream into a valid DICOM file (see here: https://github.com/fo-dicom/fo-dicom/issues/689#issuecomment-488559294), but to convert a file from AVI to MPEG you have to use an other library (aforge, ffmpeg, ...)

**Comment by alanhmartins** [comment]
It is converting to DIcom, however when running in a dicom viewer, the video has the correct time, but is blank, does anyone know what it can be? Below code

`public static string ConvertVideoToDIcom(string file)
        {
            try
            {
                DicomDataset dataset = new DicomDataset();                
                int i = 0;
                DateTime DataHoraExame = DateTime.Now;
                dataset.Add(DicomTag.SOPClassUID, DicomUID.MultiFrameTrueColorSecondaryCaptureImageStorage);
                dataset.Add(DicomTag.StudyInstanceUID, GenerateUid());
                dataset.Add(DicomTag.SeriesInstanceUID, GenerateUid());
                dataset.Add(DicomTag.SOPInstanceUID, GenerateUid());
                dataset.Add(DicomTag.PatientName, "TesteVDicom");
                dataset.Add(DicomTag.StudyDate, DataHoraExame);
                dataset.Add(DicomTag.StudyTime, DataHoraExame);
                dataset.Add(DicomTag.PhotometricInterpretation, PhotometricInterpretation.Rgb.Value);
               
                dataset.AddOrUpdate(DicomTag.BitsAllocated, (ushort)(8));
                dataset.AddOrUpdate(DicomTag.TransferSyntaxUID, DicomTransferSyntax.MPEG4AVCH264HighProfileLevel41.UID.UID);
                DicomPixelData pixelData = DicomPixelData.Create(dataset, true);
                List<Bitmap> videoFrames = GetVideoFrames(file);
                
                Bitmap bitmap = new Bitmap(videoFrames[0]);
                bitmap = GetValidImage(bitmap);
                int rows, columns;
                byte[] pixels = GetPixels(bitmap, out rows, out columns);
                dataset.Add(DicomTag.Rows, (ushort)rows);
                dataset.Add(DicomTag.Columns, (ushort)columns);
                dataset.AddOrUpdate(DicomTag.BitsAllocated, (ushort)8);
                foreach (Bitmap item in videoFrames)
                {
                    if (item != null)
                    {
                         bitmap = new Bitmap(item);
                        bitmap = GetValidImage(bitmap);                        
                        pixels = GetPixels(bitmap, out rows, out columns);
                        MemoryByteBuffer buffer = new MemoryByteBuffer(pixels);
                        
                        pixelData.AddFrame(buffer);
                        i++;
                    }
                }

                pixelData.NumberOfFrames = i;
                

                DicomFile dicomfile = new DicomFile(dataset);
                string filedicom = Application.StartupPath + @"\Video.VDICOM";
                dicomfile.Save(filedicom);
                return filedicom;
            }
            catch (Exception ex)
            {

                return "";
            }

        }`

**Comment by gofal** [comment]
You are mixing up two things:
* the first thing are Multiframes
* the other thing is Video

Your code creates a multi frame image. That is a list of independent encoded images. There the Transfersyntax of your DicomDataset should be the Transfersyntax of a single frame. Because you write the full uncompressed bitmap, the transfersyntax should be LittleEndianImplicit.

The downside is that the file gets very large. Then you can create a mpeg video and just copy the binary stream of this video into the pixel data. Then the Transfersyntax should be MPEG4AVCH264HighProfileLevel41.

**Comment by alanhmartins** [comment]
It would be like this?

`
  DicomDataset dataset = new DicomDataset();                
                int nFrames = 0;
                DateTime DataHoraExame = DateTime.Now;
                dataset.Add(DicomTag.SOPClassUID, dataset.Add(DicomTag.SOPClassUID, DicomUID.MultiFrameTrueColorSecondaryCaptureImageStorage);
                dataset.Add(DicomTag.StudyInstanceUID, GenerateUid());
                dataset.Add(DicomTag.SeriesInstanceUID, GenerateUid());
                dataset.Add(DicomTag.SOPInstanceUID, GenerateUid());
                dataset.Add(DicomTag.MediaStorageSOPInstanceUID, GenerateUid());
                dataset.Add(DicomTag.ImageType, "ORIGINAL\\PRIMARY");
                dataset.Add(DicomTag.PatientName, "TesteVDicom");
                dataset.Add(DicomTag.StudyDate, DataHoraExame);
                dataset.Add(DicomTag.StudyTime, DataHoraExame);
                  dataset.AddOrUpdate(DicomTag.BitsAllocated, (ushort)(8));
 List<Bitmap> videoFrames = GetVideoFrames(file);  
                Bitmap bitmap = new Bitmap(videoFrames[0]);
                bitmap = GetValidImage(bitmap);
 foreach (Bitmap item in videoFrames)
                {

                    if (item != null)
                    {
                        //bitmap = new Bitmap(item);
                        //bitmap = GetValidImage(bitmap);
                        //pixels = GetPixels(bitmap, out rows, out columns);
                        //MemoryByteBuffer buffer = new MemoryByteBuffer(pixels);

                        //pixelData.AddFrame(buffer);
                        nFrames++;
                    }
                }
                int rows, columns;
                byte[] pixels = GetPixels(bitmap, out rows, out columns);
dataset.Add(DicomTag.PhotometricInterpretation, PhotometricInterpretation.Rgb.Value);
                dataset.Add(DicomTag.Rows, (ushort)rows);
                dataset.Add(DicomTag.Columns, (ushort)columns);
                dataset.AddOrUpdate(DicomTag.TransferSyntaxUID, DicomTransferSyntax.MPEG4AVCH264HighProfileLevel41.UID.UID);
                DicomPixelData pixelData = DicomPixelData.Create(dataset, true);
                var finfo = new FileInfo(file);
                var buffer = new FileByteBuffer(new Dicom.IO.DesktopFileReference(file), 0, (uint)finfo.Length);
                pixelData.AddFrame(buffer);
                pixelData.NumberOfFrames = nFrames;         
DicomFile dicomfile = new DicomFile(dataset);

                string filedicom = Application.StartupPath + @"\Video.VDICOM";
                dicomfile.Save(filedicom);
                return filedicom;
`

But it looks like this in the DICOM viewer

![image](https://user-images.githubusercontent.com/18291580/77321979-c4a09d80-6cf1-11ea-86da-91b19e7d63d9.png)

**Comment by gofal** [comment]
So you can scroll through the 205 images in the viewer? then fo-dicom seems to do its job.
I would take a look at lines:

        List videoFrames = GetVideoFrames(file);
        Bitmap bitmap = new Bitmap(videoFrames[0]);

try to save the `bitmap` into a temporary file and take a look at this file. I bet, this bitmap already looks the same as your screenshot above.

**Comment by alanhmartins** [comment]
I can see the 205 frames, but not automatically as a video. as shown in the image below, q is an original VDicom, which has 22 frames, but runs directly without having to scroll to see the other frames. Is it possible to do this with fodicom?

Excuse me for my English, I'm Brazilian

![image](https://user-images.githubusercontent.com/18291580/77326980-5cee5080-6cf9-11ea-9bdb-b57d596f62c2.png)

**Comment by gofal** [comment]
The feature you are asking for is "cine" (http://dicom.nema.org/medical/dicom/2016e/output/chtml/part03/sect_C.7.6.5.html)
If you have a multiframe image, then the viewer interprets them as several independent images to scroll throught.
But if there are these cine-attributes like `FrameTime` then the viewer knows how to display the images automatically.

**Comment by alanhmartins** [comment]
I got it, but I put the tags on the cine module and still didn't solve it, is there an example?

**Comment by alanhmartins** [comment]
@gofal I managed, in a dicom viewer, it automatically ran all the frames, but in another one that automatically runs original dicom videos, I couldn't, I imagine that each viewer may have to put different tags for him to identify that it is to run as if it were a video, right?

**Comment by gofal** [comment]
Of course every viewer may behave different.
DICOM standard defines how valid files have to look like, but there are a lot of different cases, options, optional fields etc.
Every software, that handles DICOM, has to write a DICOM conformance statement (http://dicom.nema.org/dicom/2004/04_02PU.PDF). if you google for "DICOM conformance statement" + some vendor or some machine/software then you will find how it looks like. And in this conformance statement, there should be described which DICOM fields are evaluated or required for some features or workflows.

It may be, that the viewer, which do not display the cine, has some option, that it only plays cine if there are the cine attributes AND if it is a Ultrasound or a Radiography. That is a very reasonable assumption. And since you create SecondaryCaptures the cine may not play automatically.... There are so many possibilities :-)

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.

**Comment by SushrutDeo** [comment]
List<Bitmap> videoFrames = GetVideoFrames(file); 
Bitmap bitmap = new Bitmap(videoFrames[0]);
bitmap = GetValidImage(bitmap);

Can somebody provide code for GetVideoFrames(file); and GetValidImage(bitmap);, please? I am trying to convert mp4 video to dicom video. I am really struggling with it. Can someone help, please?
