### ISSUE TITLE
Adding an annotation to a DICOM image

### ISSUE THREAD

**Issue by milkyway007** [fo-dicom/fo-dicom#1011]
I have the following goal:

1. To add markings to a DICOM image (for example, drawings or textual comments).
2. Added markings must not be a part of the image (if necessary the must be an opportunity to show them or hide).

As much as I have understood, [here](https://stackoverflow.com/questions/34591221/annotate-dicom-files/34609540#34609540) is said that this can be accomplished with the help of the [Grayscale Softcopy Presentation State IOD](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_A.33.html#sect_A.33.1). At the moment I am studying the framework fo-dicom in order to make clear if it enables to use this way. However, I have understood that I do not understand how it is working in general.

I have the following questions:

1. First of all, we should create a new DICOM object (with the SOP Class UID matching Grayscale Softcopy Presentation State IOD). How will be this object connected with the DICOM image object? Using what attributes and in which object? The attributes of the Presentation State Relationship module in the Grayscale Softcopy Presentation State IOD?
2. How can I see the annotations done with the help of the Grayscale Softcopy Presentation State IOD using any DICOM Viewer?

**Comment by gofal** [comment]
You already found the definition of Grayscale Softcopy Presentation State in DICOM standard. There you have the Presentation State Relationship module, which is mandatory. In concrete you have to add ReferencedSeriesSequence (0008,1115) and there the SeriesinstanceUid and ReferencedImageSequence(0008,1140) with InstanceUID and FrameNumber

To see you result, you have to use a viewer, that supports presentation states. most, but not all free viewer do. commercial viewer all support presentation states of course. Then it is up to the viewer how to make it display.

**Comment by milkyway007** [comment]
Thanks!

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.
