### ISSUE TITLE
Changing the font size of a Presentation State

### ISSUE THREAD

**Issue by milkyway007** [fo-dicom/fo-dicom#1015]
I am currently trying to create the Grayscale Softcopy Presentation State file that holds some text comment. I am creating text object sequence like this:

```
DicomDataset textObjectSequenceDataset = new DicomDataset();
textObjectSequenceDataset.Add(DicomTag.BoundingBoxAnnotationUnits, "DISPLAY");
textObjectSequenceDataset.Add(DicomTag.UnformattedTextValue, "TERE");
textObjectSequenceDataset.Add(DicomTag.BoundingBoxTopLeftHandCorner, @"0\0");
textObjectSequenceDataset.Add(DicomTag.BoundingBoxBottomRightHandCorner, @"0\0");
textObjectSequenceDataset.Add(DicomTag.BoundingBoxTextHorizontalJustification, @"LEFT");
graphicAnnotationSequenceDataset.Add(DicomTag.TextObjectSequence, textObjectSequenceDataset); 

```
How it is possible to change the font size of a textual comment?

**Comment by gofal** [comment]
First of all you should not set the boundingbox a rectangle with zero width and zero height. BoundingBoxBottomRightHandCorner should have higher values than BoundingBoxTopLefthandCorner.

As I understand the advantage of having textual annotations over drawing overlay-bitmaps is that the viewer has full control of rendering (color, size, font, ...). So setting the font size is not the way. Maybe some viewers try to fit the text into the boundingbox. You could try to set the bounding box bigger than in other annotations. But you should not rely on that. if font size is important, then draw on a bit-plane and create an overlay bitmap.

**Comment by milkyway007** [comment]
Understood, thanks!

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.
