### ISSUE TITLE
DICOM Print with annotation

### ISSUE THREAD

**Issue by yadavvirus** [fo-dicom/fo-dicom#1016]

**Comment by yadavvirus** [comment]
@gofal  Hello Sir DICOM Print is working fine but sir please help me how to print with DICOM tag over image as annotation.
Please sir help me.

**Comment by gofal** [comment]
please be more concrete with your question/issue. Are you DICOM SCU or DICOM SCP? What have you tried so far, which information do you need?

**Comment by yadavvirus** [comment]
SIr DICOM Print SCU just simply send image without having DICOM dataset over image. How i can send image with its DICOM Dataset (Annotations on it)

**Comment by yadavvirus** [comment]
Sir I am attaching image one image is plain image another is having annotation over it. Now Print SCU Is sending imge without Annotations ovet it, But I need to print like another image attached showing patient name and id over it.
![b](https://user-images.githubusercontent.com/7027914/79513711-21c60f80-8062-11ea-8b58-98cf02beb1f7.png)
![a](https://user-images.githubusercontent.com/7027914/79513723-25599680-8062-11ea-861f-b92087e91c89.png)

**Comment by yadavvirus** [comment]
@gofal plz help me

**Comment by yadavvirus** [comment]
@gofal Sir I am waiting for your reply please.

**Comment by gofal** [comment]
Please be patient. Of course I will help you as far as I can. But obviously there is no bug in fo-dicom. And I am a open source developer spending my free time here, not your DICOM consultant who has to answer within x hours. 

But anyway: To understand correctly, you are running a Print SCU and now you do not send annotations any more? 
If you read through the DICOM standard for DICOM Print (you should do that, really), then you will see, that the Print SCP never receives metadata like Patientsname, Birthdate, PatientID or similar. The Print SCU only sends the complete ready rendered pixel data to the Print SCP.

So anywhere in your code you are creating this pixel data. And there you have somewhere the code, where you call RenderImage on the original DicomDataset, where you read some values from this file, and then write the content somewhere on the rendered Bitmap and then add this Bitmap to your pringJob.

I do not know your code, so I do not know how to help you.

**Comment by yadavvirus** [comment]
Sorry sir plz dont get angry. I reaaly dont mean to disturb you or make angry.

**Comment by yadavvirus** [comment]
@gofal  sir i am using your demo print scu only i want you helpb me how i can print by showing DICOM tag values 4 corner.Is it possible with available print scu dem. if possible then please help me. thank you sir

**Comment by gofal** [comment]
> Sorry sir plz dont get angry. I reaaly dont mean to disturb you or make angry.

no problem. But keep it mind, that answers might take some time. And please try to ask about fo-dicom or DICOM as detailled as possible. I do not have the time to teach or explain all about DICOM and programming.

**Comment by gofal** [comment]
> @gofal sir i am using your demo print scu only i want you helpb me how i can print by showing DICOM tag values 4 corner.Is it possible with available print scu dem. if possible then please help me. thank you sir

of course it is.
See here: https://github.com/fo-dicom/fo-dicom-samples/blob/447ee3f56a2fb9a3a84b3b68186737119d62a899/Desktop/Print%20SCU/Program.cs#L34
There the sample renders the Bitmap, which is then added to the printjob. But before you add it to the printjob, you can do with it whatever you want. Like:

     using (var g = Graphics.FromImage(bitmap))
     {
           g.DrawText(0, 0, greyscaleImg.Dataset.GetString(DicomTags.Patientname, Brushes.Yellow);
      }

or similar.
I wrote the code from my mind, so the order or type of the parameters in `DrawText` are propably wrong. But I think you should get the idea: you can extend this bitmap via GDI with as many annotations, lines, drawings, text, watermarks as you want. You can do imagemanipulations like bluring or sharpening, .... do what your application needs to do. This is out of scope of DICOM, but your personal busines logic.

**Comment by yadavvirus** [comment]
@gofal 
Hello Sir thank you sir with your support its done.
![bpjiyadavji123](https://user-images.githubusercontent.com/7027914/80291578-4d38b080-876c-11ea-80f2-2ffc0c77fc71.jpg)
