### ISSUE TITLE
Merge JsonConverter into main project

### ISSUE THREAD

**Issue by gofal** [fo-dicom/fo-dicom#1024]
### Expected behavior
Json conversion is a common task and should be included in mail package instead of installing an extra package

Microsofts System.Text.Json could be used instead of third party Newtonsoft.Json.
https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to

**Comment by amoerie** [comment]
Watch out with the Microsoft JSON serializer / deserializer, the last thing I read about this is that they don't support all the same types that Newtonsoft does (some collection types if I'm not mistaken)

**Comment by gofal** [comment]
Yes, I also read that microsofts implementation is limited compared to newtonsoft.
But DICOM is very strict how the json file has to look like. So we only have to check about these few defined types.

**Comment by amoerie** [comment]
If it works, all the better. I am also in favor of using a leaner, faster implementation. We do quite a bit of JSON converting ourselves.

**Comment by gofal** [comment]
Implemented json conversion into fo-dicom.core assembly. Call it:

      string json = FellowOakDicom.Serialization.DicomJson.ConvertDicomToJson(dataset);
      DicomDataset ds = FellowOakDicom.Serialization.DicomJson.ConvertJsonToDicom(json);

I duplicated all the unittests with json conversion to run with the new converter and all run green. 
Please do some tests with your own json data and report any findings.

**Comment by gofal** [comment]
The result of the benchmark:



|                            Method |       Mean |    Error |    StdDev |    Gen 0 |    Gen 1 |    Gen 2 |  Allocated |
|---------------------------------- |-----------:|---------:|----------:|---------:|---------:|---------:|-----------:|
|   SerializeDicomDirWithNewtonsoft |   590.2 us | 12.59 us |  18.85 us |  39.0625 |   9.7656 |        - |  242.02 KB |
|       SerializeFileWithNewtonsoft | 2,012.8 us | 38.82 us |  43.15 us | 359.3750 | 355.4688 | 355.4688 |  4129.5 KB |
| DeserializeDicomDirWithNewtonsoft | 4,227.0 us | 83.00 us | 107.93 us | 328.1250 | 164.0625 |        - | 2060.75 KB |
|     DeserializeFileWithNewtonsoft | 4,143.0 us | 40.16 us |  35.60 us | 328.1250 | 164.0625 |        - | 2060.75 KB |
|    SerializeDicomDirWithMicrosoft |   489.0 us |  2.58 us |   2.41 us |  37.1094 |   5.8594 |        - |  231.67 KB |
|        SerializeFileWithMicrosoft | 1,021.4 us | 17.92 us |  16.77 us | 160.1563 | 158.2031 | 158.2031 | 1382.83 KB |
|  DeserializeDicomDirWithMicrosoft | 2,791.2 us | 54.84 us |  71.31 us | 164.0625 |  66.4063 |        - | 1015.16 KB |
|      DeserializeFileWithMicrosoft | 2,750.9 us | 29.72 us |  27.80 us | 164.0625 |  66.4063 |        - | 1015.16 KB |

**Comment by gofal** [comment]
I used a DicomDir (many tags with many sequences) and a DicomFile (huge pixel data). Then I searialized it and deserialized it both with Newtonsoft- and Microsoft-based converter.

Microsofts converter allocates less memory and is faster (close to factor 2).

**Comment by amoerie** [comment]
This looks amazing. Double the speed and half of the memory allocated.

If everything really works, then I'm a big fan. 😃

**Comment by shelbypereira** [comment]
any hance of having this in the next release if it is working?  This is of huge value.  In addition to the speed/memory improvments,  the reference to the addition serialization packages is clumsy.  The Json serializers are quite important for working with WADO/QIDO and surely elsewhere.

**Comment by gofal** [comment]
it is included in fo-dicom version 5. I do not plan, to also include it in the version 4, which is currently in status of only bug-fixing and and adding pull requests that come from the community.

version 5 should also fit better when it comes to web-interfaces like WADO/QIDO. It should integrate better with the DI-architecture of asp.net.

did you take a look at version 5 already?

**Comment by shelbypereira** [comment]
I will definitely look at 5.0, thanks for the pointer.

**Comment by gofal** [comment]
when taking a look at version 5: just open the solution "FO-DICOM.Full.sln" instead of the "DICOM.*.sln".
An important thing when releasing version 5 will be the documentation, because there are some breaking changes. So take a look at the file "changeLog5.md", it contains a full list of changes compared to version 4
