### ISSUE TITLE
Enable custom implementations of IDicomClientConnection

### ISSUE THREAD

**Issue by amosonn** [fo-dicom/fo-dicom#1036]
If more fine-grained control of a connection as an SCU is required, sometimes it can be useful to implement `IDicomClientConnection` in a custom way, also inheriting from `DicomService`. This is similar to the standard implementation of `DicomClientConnection`, but replacing the calls to `DicomClient` with custom code. The implementation of `DicomClientConnection`, where it delegates the `StartListener` and all `Send*` methods to `base`, can be almost completely re-used in user code, except for one method: `SendNextMessageAsync` is private.

What I would suggest to enable this use-case is either making `SendNextMessageAsync` public like the others; or, perhaps better, to make a public abstract class which shares `DicomClientConnection`-s inheritance, delegates of `StartListener` and `Send*` methods to `DicomService`, but leaves implementation of the `On*` callbacks free.

If one or the other is deemed appropriate, I can draft a PR.

Thanks!

**Comment by amoerie** [comment]
The DicomClientConnection class is just a gateway instance that represents an active DICOM association. If your "modified version" of DicomClientConnection would fail to properly notify the DicomClient in all scenarios, the DicomClient would break / stall / become unresponsive.

What's your use case exactly? We already have quite a collection of event handlers and other hook points that enable a lot of flexibility.

**Comment by amosonn** [comment]
Well, in my implementation we don't use `DicomClient` at all. The `Send*`-s are hooked up to `DicomService`, but the `On*`-s are using custom handlers.

Perhaps it is possible to use `DicomClient` and its hooks instead; I didn't look into it deeply, but what I mostly noticed missing was a hook for aborted connections. Either way, I don't actually need all the state-management the `DicomClient` offers, so I would prefer to avoid it. Our use case is just forwarding messages from another client, so we rely on their state machine.

If it helps, I'm migrating the code from an older version of fo-dicom and the `IDicomServiceUser` interface, where we did the same thing: use a customized version of the standard implementation of `DicomServiceUser`.

**Comment by amosonn** [comment]
I'm bumping this; is there a case *against* adding this intermediate abstract class and/or changing the visibility of `DicomService.SendNextMessageAsync` (I think protected is enough)?

**Comment by amoerie** [comment]
Sorry, I'm not ignoring you, I'm just quite busy at the moment and I've made a note to investigate this a little more before I provide you with a more elaborate answer. I'll get back to you on this as soon as I can!

**Comment by amoerie** [comment]
I've taken a look at the DicomClientConnection and its usages, and here are my thoughts:

I still consider the existence of "IsSendNextMessageRequired" and "SendNextMessage" a mistake. A DICOM service shouldn't need to be poked by external systems to continue processing its outbox of requests, this should be done automatically as much as possible. Unfortunately, that is not the situation today, as my extensive experiments with DicomClient have shown. A lot of engineering went into the new DicomClient to ensure the processing of the outbox continues in every appropriate scenario, and a lot of tests have been written to verify this. 
For this reason, I consider writing your own, completely custom, IDicomClientConnection a considerable "footgun" that should come with a big disclaimer.

On the other hand, I won't pretend that only I am capable of dealing with this responsibility. I imagine that your custom implementation of IDicomServiceUser has been paid for with blood, sweat and tears too. 😉 

My preferred plan, taking your proposed solution, would be the following:

- Rename the interface IDicomClientConnection to IDicomConnection. I want to make it explicit that this interface will no longer exist solely for its usage by DicomClient
- Add an abstract class DicomConnection that is 99% the same implementation as DicomClientConnection. The constructor parameter "DicomClient" should be replaced with an interface called "IDicomConnectionCallbacks" that contains all of the 'On*' methods
- Make DicomClientConnection inherit from DicomConnection, and make it implement the IDicomConnectionCallbacks interface. We could directly implement this interface in DicomClient itself, but that would make all those On* methods public, and I don't want to pollute the public API of DicomClient if possible.
- Verify that the DicomClient still works as before by running its suite of tests
- Verify that a custom class that inherits from DicomConnection is also able to send and receive DICOM messages (your use case), without needing access to any internal classes from fo-dicom.

If you are able to draft a PR, I can help with any issues you might encounter. I can also make the initial PR, but then your patience will be tested a little longer I'm afraid. 😉

**Comment by amosonn** [comment]
Thanks for the detailed response! I didn't mean to imply you're ignoring, sorry if it came so across. I just assumed this has gone down in the inbox, so I thought I could check again.

I agree about the point in `SendNextAsync`. I think I would expect `SendMessageAsync` to always return only when the message was sent, and exactly a single one: so instead of having a loop and and and `if (_sending) break`, I would have a semaphore and block on it (asynchronously). Perhaps I'm missing something?

Anyway, to the matter at hand: your suggestion looks quite good! Definitely better than an abstract class. Looking at the use-sites, though, I have the feeling that an even cleaner approach should be possible, as these really are two completely separate interfaces: one for the callbacks and one for the sending. The former ones are used only inside `DicomService`, whereas the latter ones are used in all of the `DicomClient*State`-s, and there are no other use-sites. This makes me think, that perhaps it is possible to have `DicomService` receive an optional `IDicomConnectionCallbacks` on construction, and have `DicomClientConnectState` initialize the service with a `DicomClientConnection` which implements it. This only leaves the question of where to put `StartListener` (i.e. where to store the task for `RunAsync`), but this could be moved to `DicomService` itself, perhaps. What do you think about this?

Either way, I think it will take some time for me to get around to actually implementing this, I will write here if I go back to working on this; but I would like to hear your thoughts about the approach above :)

**Comment by amoerie** [comment]
I do agree that it might be beneficial to split things up a little more, and your suggestions sound good.  Moving the listener task to DicomService sounds wrong though, DicomService is already a huge monster class and I don't wish to pollute it further. If anything, that class needs to go on a diet. I would keep the Listener task on the DicomClientConnection if at all possible. 

If you find the time, I would be delighted to help and review. 

My apologies for being a bit slow to respond, I recently became a father and time has become a valuable good. 😅

**Comment by amosonn** [comment]
Congratulations :)

I see your point with `DicomService` holding the task, I think I agree. OTOH I don't like `DicomClientConnection` holding it, because then they are sort-of depending on each other. Perhaps the best place would be the `DicomClient` directly, after all it "owns" the `DicomService`, but I'll see if it can fit there; otherwise I'll leave it in `DicomClientConnection`.

Anyway, in the coming few weeks I don't think I'll have time for this, but maybe afterwards I will. I'll let you know if I come back to this, thanks for you time!

**Comment by amoerie** [comment]
@amosonn Can you read the discussion we had over in https://github.com/fo-dicom/fo-dicom/pull/1050? 

We discussed the possibility of adding a middleware layer to DicomClient / DicomServer that could possibly be of value to you. Of course, I realize that you wish to avoid DicomClient entirely, so I'm not sure this might cover our needs with regards to this issue.

**Comment by amosonn** [comment]
@amoerie Thanks for linking this! As a first reaction, it seems to me that if custom implementations were possible, implementing the current `IDicomClientConnection` would provide the complete middleware functionality (and more). After all, all calls in both directions - both callbacks from the `DicomService`, notifying that a message has arrived, as well as requests to send a message through the `Send*` methods - go through this interface. The standard `DicomClientConnection` just routes those calls onwards to `DicomClient` and `DicomService` respectively, but an alternative implementation could change the messages before passing them onward.

However, I'm not sure this is the best API for this. This is "stronger" than a middleware interface, in that you don't have to forward the call at all, can initiate additional calls, etc.; this means OTOH that you have the responsibility of correctly forwarding the calls in the standard caso. Also, the current implementation is non-symmetric, in that the `DicomService` is inherited by the implementation, whereas the `DicomClient` is a member; this could be perhaps changed without much work, though attention needs to be paid to the inherent asymmetry where the client initiates the creation of the service and has a 1:n relationship with it. Finally, I liked the idea from above of splitting the two halves of this interface, each being a sort of a half-duplex. This also lets you replace the `DicomClient` completely if needed, as in my usecase.

I think the main take here is that if splitting `IDicomClientConnection`, whereas before I thought of removing the half "wrapping" `DicomService` and just have the client call it directly, it might be useful to keep this half around for such middleware usecases. Perhaps some kind of `IDicomService`? Either way, it's interesting to see this other usecase, and I'll think if it can further affect the design of the solution to this problem.

**Comment by amoerie** [comment]
@amosonn If you're still interested in this, I would ask you to review the possibilities with the advanced connection/association API and see if your use cases are covered by those APIs. If not, it would probably be best to open a new issue. I hope you understand I'm closing this issue because it's quite outdated.

**Comment by amosonn** [comment]
Hi, thanks for all your work! I've moved on to other projects in the
meantime, if I find time I'll look at this though :)
