### ISSUE TITLE
Quality not applied to JPEG Transfer sintax

### ISSUE THREAD

**Issue by icolovic** [fo-dicom/fo-dicom#1038]
When cloning DicomDataset changinh the quality parameter for DicomJpegParams is not applied to the frames. I can change quality to 20, 60 or 100. Every time files have exactly the same size. And the resulting files are almost identical. If you compare them (binary) whole PixelData part is exactly the same.

### Steps to reproduce the behavior
Add any number of frames to the dicomDataSet.

dicomDataSet = dicomDataSet.Clone( saveTransferSintax, new DicomJpegParams() { Quality = 20 } );
dicomFile = new DicomFile( dicomDataSet );
dicomFile.Save("DICOM20Q.dcm")

Then change the quality to 60. Compare files by size and content.

### fo-dicom version and OS/platform
fo-dicom 4.0.4
Window 10 1909
.NET Framework 4.8

**Comment by gofal** [comment]
Are you using the codec shipped with fo-dicom or are you using Efferent's codec?

I took a first glance into the code and found, that every quality <=50 for example is mapped to the sampe quantifier table entry. So there will not be any difference for all values lower than 50. But for others I do not see any obvious reason why the parameter is not evaluated.

What exactly is the content of the variable `saveTransferSintax` in your sample?

**Comment by icolovic** [comment]
I am using codec shipped with fo-dicom.

In my tests I was using 60 and 20 as a quality. But then still does not explain no change.

Is there any benefit of using a different codec and if so are there any examples?

Value of saveTransferSintax if set based on some private DICOM tags. There is a configuration option in the application that allow user to select different quality of the saved images. Based on that I am setting Transfer Syntax and Quality (if codec support it).

**Comment by gofal** [comment]
the codec shipped with fo-dicom has only full support on windows/NetFramework and limited support on other OS or platforms. See here:
https://github.com/fo-dicom/fo-dicom/wiki/Supported-Transfer-Syntaxes

fo-dicom has many places where you can plug in your own implementations. This is also true for Codecs. 
The company Efferent did a great work and made the codecs also work on linux and mac. See here: https://github.com/Efferent-Health/fo-dicom.Codecs

What I meant with the content of saveTransferSintax is, which TransferSyntax you are actually using. The quality-option is only supported if you choose transfersyntax "JPEG Baseline (Process 1)4 (1.2.840.10008.1.2.4.50)" or "JPEG Baseline (Processes 2 & 4)5 (1.2.840.10008.1.2.4.51)". These are lossy jpeg codecs. 
If you have choosen an other TransferSyntax then you would need other parameters.

**Comment by icolovic** [comment]
The problem I have is that my data is saved using 16bits and that is why I can not use 1.2.840.10008.1.2.4.50 and  1.2.840.10008.1.2.4.51.

What are the other parameters available for compression on 1.2.840.10008.1.2.4.70 or 1.2.840.10008.1.2.4.57.

**Comment by gofal** [comment]
well, 1.2.840.10008.1.2.4.70 is JPEG Losses, Nonhierarchial, First- Order Prediction (Process 14, selection value 1).
and 1.2.840.10008.1.2.4.57 is JPEG Lossless, Nonhierarchial (Process 14).

those are lossess compressions, there are no quality-parameters or others, I am affraid.
