### ISSUE TITLE
ImplicitVRLittleEndian always added to presentation context by default causes other transfer syntax to not be accepted

### ISSUE THREAD

**Issue by Siyam** [fo-dicom/fo-dicom#1048]
### Expected behavior
Setting an internal transfer syntax ensures that the dicom data set is sent via CStore with that intended transfer syntax only.

### Actual behavior
fo-dicom adds by default ImplicitVRLittleEndian to all presentation contexts from a CStore request.  This then creates an acceptance to use ImplicitVRLittleEndian instead of the specified/intended transfer syntax. 

While convenient it isn't always the intended objective as a CSTORE SCP may offer a presentation context but can still store the dataset with the internal transfer syntax that was requested.  In simulating this same CSTORE operation using dcmtk, one is able to propose a different presentation context: --propose-jpeg8 

Please allow the ability for users to prevent a default transfer ImplicitVRLittleEndian from being added to the request.  For example because of this behavior, what would normally be a 200 KB JPEG Lossy image, gets stored as a decompressed image that is 10mb in size in a PACS system.

### Steps to reproduce the behavior
Sample CSTORE:
```
[DEBUG] Searching C:\...\bin\Debug\Dicom.Native*.dll for Dicom codecs
[DEBUG] Codec: JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression
[DEBUG] Codec: JPEG Extended (Process 2 & 4): Default Transfer Syntax for Lossy JPEG 12 Bit Image Compression (Process 4 only)
[DEBUG] Codec: JPEG Lossless, Non-Hierarchical (Process 14)
[DEBUG] Codec: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression
[DEBUG] Codec: JPEG 2000 Image Compression (Lossless Only)
[DEBUG] Codec: JPEG 2000 Image Compression
[DEBUG] Codec: JPEG-LS Lossless Image Compression
[DEBUG] Codec: JPEG-LS Lossy (Near-Lossless) Image Compression
[DEBUG] Codec: RLE Lossless
[DEBUG] Searching C:\...\bin\Debug\Dicom.Native*.dll for Dicom codecs
[DEBUG] Codec: JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression
[DEBUG] Codec: JPEG Extended (Process 2 & 4): Default Transfer Syntax for Lossy JPEG 12 Bit Image Compression (Process 4 only)
[DEBUG] Codec: JPEG Lossless, Non-Hierarchical (Process 14)
[DEBUG] Codec: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression
[DEBUG] Codec: JPEG 2000 Image Compression (Lossless Only)
[DEBUG] Codec: JPEG 2000 Image Compression
[DEBUG] Codec: JPEG-LS Lossless Image Compression
[DEBUG] Codec: JPEG-LS Lossy (Near-Lossless) Image Compression
[DEBUG] Codec: RLE Lossless
[DEBUG] [IDLE] --> [CONNECTING]
[DEBUG] [CONNECTING] --> [REQUESTING ASSOCIATION]
[INFO] TSTG0APCVIS -> Association request:
Calling AE Title:       ISCV_TEST
Called AE Title:        TSTG0APCVIS
Remote host:            xxx.xx.xx.xxx
Remote port:            xxx
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 4.0.4
Maximum PDU Length:     262144
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Secondary Capture Image Storage
       Transfer Syntax:  JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] TSTG0APCVIS <- Association accept:
Calling AE Title:       ISCV_TEST
Called AE Title:        TSTG0APCVIS
Remote host:            xxx.xxx.xxx
Remote port:            xxx
Implementation Class:   Unknown [1.3.46.670589.58.4.2]
Implementation Version: ISCV 4.2
Maximum PDU Length:     64234
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Secondary Capture Image Storage
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[DEBUG] [REQUESTING ASSOCIATION] Association is accepted
[DEBUG] [REQUESTING ASSOCIATION] --> [SENDING REQUESTS]
[DEBUG] [SENDING REQUESTS] Sending DICOM requests
[INFO] TSTG0APCVIS -> C-Store request [2]
[INFO] TSTG0APCVIS <- C-Store response [2]: Success
Success
```

Area of code in  Dicom.Network.DicomPresentationContextCollection where transfer syntax is changed:
```
 public void AddFromRequest(DicomRequest request)
        {
            if (request is DicomCStoreRequest cstore)
            {
                var pcs = _pc.Values.Where(x => x.AbstractSyntax == request.SOPClassUID);
                if (cstore.TransferSyntax == DicomTransferSyntax.ImplicitVRLittleEndian)
                {
                    pcs = pcs.Where(x => x.GetTransferSyntaxes().Contains(DicomTransferSyntax.ImplicitVRLittleEndian));
                }
                else
                {
                    pcs = pcs.Where(x => x.HasTransferSyntax(cstore.TransferSyntax));
                }

                var pc = pcs.FirstOrDefault();
                if (pc == null)
                {
                    var tx = new List<DicomTransferSyntax>();
                    if (cstore.TransferSyntax != DicomTransferSyntax.ImplicitVRLittleEndian) tx.Add(cstore.TransferSyntax);
                    if (cstore.AdditionalTransferSyntaxes != null) tx.AddRange(cstore.AdditionalTransferSyntaxes);
                    tx.Add(DicomTransferSyntax.ImplicitVRLittleEndian);  // <--- HERE 

                    Add(cstore.SOPClassUID, tx.ToArray());
                }
            }
            else
            {
                if (request.PresentationContext != null)
                {
                    var pc =
                        _pc.Values.FirstOrDefault(
                            x =>
                                x.AbstractSyntax == request.PresentationContext.AbstractSyntax &&
                                request.PresentationContext.GetTransferSyntaxes().All(y => x.GetTransferSyntaxes().Contains(y)));

                    if (pc == null)
                    {
                        var transferSyntaxes = request.PresentationContext.GetTransferSyntaxes().ToArray();
                        if (!transferSyntaxes.Any())
                            transferSyntaxes = new[] { DicomTransferSyntax.ImplicitVRLittleEndian };
                        Add(
                            request.PresentationContext.AbstractSyntax,
                            request.PresentationContext.UserRole,
                            request.PresentationContext.ProviderRole,
                            transferSyntaxes);
                    }
                }
                else
                {
                    foreach (var sopclass in MetaSopClasses.GetMetaSopClass(request.SOPClassUID))
                    {
                        var pc = _pc.Values.FirstOrDefault(x => x.AbstractSyntax == sopclass);
                        if (pc == null)
                        {
                            Add(sopclass, DicomTransferSyntax.ImplicitVRLittleEndian);
                        }
                    }
                }
            }
        }
```

### fo-dicom version and OS/platform
.net core 3.1 , fo-dicom 4.0.5

**Comment by Siyam** [comment]
Found the area of the code that causes the issue I am facing.  Is there an absolute need to set more than one transfer syntax or a default transfer syntax in the presentation context?  I think it is best for interoperability to make this an option that can be turned off.

**Comment by shazha** [comment]
This behavior is required by DICOM standard. #934 provides more details on that.

**Comment by Siyam** [comment]
Thanks for the reference @shazha .  @gofal You mentioned that it is required as part of the standard, however I am curious how a library like DCMTK allows us to propose a transfer syntax that takes care of this particular issue.

**Comment by Siyam** [comment]
I just wanted to quote the documentation here, because I think there is some ambiguity on the requirement.  It does state that there are instances where the requirement can be waived:
> 10.1 DICOM Default Transfer Syntax
> DICOM defines a default Transfer Syntax, the DICOM Implicit VR Little Endian Transfer Syntax (UID = "1.2.840.10008.1.2 "), which shall be supported by every conformant DICOM Implementation. This implies that:
> 
> If an Application Entity issues an A-ASSOCIATE request, it shall offer the DICOM Implicit VR Little Endian Transfer Syntax in at least one of the Presentation Contexts associated with each offered Abstract Syntax.
> 
> Note
> Offering Abstract Syntax (AS1) in two Presentation Contexts with Transfer Syntaxes (TS1) and (TS2) is not valid, but offering AS1-TS1, AS1-TS2 and AS1-TSD is valid because the DICOM Default Little Endian Transfer Syntax (TSD) is present in at least one of the Presentation Contexts that are based on Abstract Syntax (AS1).
> 
> If an Application Entity receives an A-ASSOCIATE indication corresponding to a request that follows the requirements specified in Section 10.1 (a), every Presentation Context related to a given Abstract Syntax cannot be rejected in an A-ASSOCIATE response for the reason that none of the Transfer Syntaxes are supported.
> 
> **Both of these requirements, (a) and (b), are waived when the Application Entity sending the pixel data has only access to the pixel data in lossy compressed form and a Transfer Syntax that uses a pixel data reference is not offered.**
> 
> **Requirement (b) to accept the default Transfer Syntax is waived if a Transfer Syntax that uses a pixel data reference is offered.**

**Comment by Siyam** [comment]
Created a PR for a "before association request send" event.  This will give a developer the ability to make any final changes if desired before the association request is sent.

**Comment by gofal** [comment]
Thanks for the PR: this event handler was just an idea, but it requires deep knowledge of how the assiciation is built up. This would be a kind of "emgergency exit" for experienced DICOM-developers.

I startet digging into it and finally found the following: The scu sends a list of presentationcontextes, that contain the AbstractSyntax to send and a list of offered Transfersyntaxes. Then for each presentationcontext the server returns if the abstractsyntax is supported and which of the offered transfersyntaxes to use.

Until now, fo-dicom had a 1:1 mapping between abstractSyntax and presentationcontext. That means we created 1 presentationcontext for every abstractsyntax to send.
I traced how dcmtk does it. here is the log when I tried so send a Jpeg-compressed SecondaryCapture

```
D:   Context ID:        201 (Proposed)
D:     Abstract Syntax: =SecondaryCaptureImageStorage
D:     Proposed SCP/SCU Role: Default
D:     Proposed Transfer Syntax(es):
D:       =JPEGBaseline
D:   Context ID:        203 (Proposed)
D:     Abstract Syntax: =SecondaryCaptureImageStorage
D:     Proposed SCP/SCU Role: Default
D:     Proposed Transfer Syntax(es):
D:       =LittleEndianExplicit
D:       =BigEndianExplicit
D:       =LittleEndianImplicit
```
They create one presentation context with the abstranc syntax with the transfersyntax that the image originally has, and then they create a presentation context with the "required" transfersyntaxes (thats how dcmtk calls it). if the context 201 is accepted they know that they can send the image as is, otherwise they decode it.

**Comment by gofal** [comment]
should fo-dicom do this by default? But this would change the behaviour of fo-dicom. 

Or should we add an property "PreferredTransfersyntax" to the CStoreRequest. for this transfersyntax the extra presentation state is created. That would be simple to use without changing the default behaviour.

**Comment by Siyam** [comment]
I think preferred or proposed syntax similar to how DCMKT does it makes a lot of sense.  Doing it this way allows the caller to present the best presentation and transfer syntax for the image.

**Comment by gofal** [comment]
I implemented the behavior, that there is a separate PresentationContext for the original TS, in the new version 5. 
Will do it in version 4 also.
