### ISSUE TITLE
DicomValidation for UI when AddFile to DicomDirectory

### ISSUE THREAD

**Issue by JungWooHwang** [fo-dicom/fo-dicom#1053]
Hello all,

I have DICOM files with an invalid DICOM UID element that starts with 0.
When trying to create a DICOM directory containing these files, the following problems occur.

> myDicomDir.AddFile(DicomFile file, string refFileID)

When executing this statement, DicomException occurs with the stack trace below.

> Content "1.2.4.100000.94849.4239.32.00121" does not validate VR UI: components must not have leading zeros 

>    at Dicom.DicomValidation.ValidateUI(String content)
   at System.Collections.Generic.List'1.ForEach(Action'1 action)
   at Dicom.DicomElement.Validate()
   at Dicom.DicomDataset.DoAdd(IEnumerable'1 items, Boolean allowUpdate)
   at Dicom.Media.DicomDirectory.CreateRecordSequenceItem(DicomDirectoryRecordType recordType, DicomDataset dataset)
   at Dicom.Media.DicomDirectory.CreateStudyRecord(DicomDataset dataset, DicomDirectoryRecord patientRecord)
   at Dicom.Media.DicomDirectory.AddNewRecord(DicomFileMetaInformation metaFileInfo, DicomDataset dataset, String referencedFileId)

[DicomValidation for VR UI on reading datasets #859 ](https://github.com/fo-dicom/fo-dicom/issues/859)
With reference to this issue, I tried changing the **AutoValidate** property to **false**, but I got the same exception.

How can I solve this problem? I need your help.

### Expected behavior
**DicomElement.Validate()** should be skipped by set **AutoValidate** property to **false**.

### Actual behavior
**DicomElement.Validate()** generates an exception for an invalid DicomUID.

### Steps to reproduce the behavior
Add DICOM file with invalid SOP Instance UID to **DicomDirectory** instance using **AddFile(DicomFile, string)** method.

### fo-dicom version and OS/platform
Fo-DICOM 4.0.4 on Windows 10 x64 / .NET Framework 4.7

add) I'm not good at English, so I'm not sure if I was able to communicate the problem correctly. If you need more information, please leave the comment. I will review your comment and provide that.

**Comment by gofal** [comment]
I'm afraid there is no workaround for that, because DicomDirectory creates some DicomDatasets internally that you cannot access.
As a workaround until the next release you have to turn off validation globally by calling `DicomValidation.AutoValidation = false`

**Comment by JungWooHwang** [comment]
The problem was temporarily solved by applying the method you suggested. What are the side effects of disabling the DicomValidation.AutoValidate property?

**Comment by gofal** [comment]
well, the side effect is, that there will be no validation at all. So when you create DICOM data from any source you have to check yourself that you do not create invalid data and send it out to the world.
As you see, if there is one single application creating bad data, all other applications around working with this data (like yours) face the issue to weaken their implementation and handle bad data.

**Comment by gofal** [comment]
I created a unittest to reproduce the issue. First it threw an exception, but then with setting the property `AutoValidate` to `false` it worked fine. So updating to latest version 4.0.5 might have solved the issue.

but anyway: the validation should be perfomed on NEW data that you are creating (like valid filename etc..), but should not be done on data that you are only reading and receiving, like such an invalid UID. So I will fix it so that it still works without setting AutoValidate to false.
