### ISSUE TITLE
Exception occurred in Indexer of VOISequenceLUT Class

### ISSUE THREAD

**Issue by JungWooHwang** [fo-dicom/fo-dicom#1062]
Hello all,

[[Download Sample DICOM File]](https://drive.google.com/file/d/1asxx9I-hidvSr13D0tyyvizX7lDjb4YF/view?usp=sharing)

_※ The attached sample file is an anonymized file that is actually being tested._

Please refer to the sample DICOM file I attached as a link. There is no Modality LUT in the DICOM file, only the VOI LUT Sequence.
When I try to make this DICOM file into a Bitmap Image through **`DicomImage.RenderImage()`**, an `IndexOutOfRangeException` occurs.

We used the DICOM Dump Application in Fo-DICOM Solution to check where the problem occurred. It is identified as a problem occurring in the Indexer(**`int this[int index]`**) of **`VOISequenceLUT`** Class.

Based on the attached sample DICOM file, 

According to [DICOM Standard Section C.11.2.1.1](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.11.2.html#sect_C.11.2.1.1), if the number of table entries is 2<sup>16</sup>, the first value of the LUT Descriptor is 0. And at this time, if there is no Modality LUT, the second value of the LUT Descriptor will have the same value as Pixel Representation.

Now, let's take a look at the **`Recalculate()`** Method of `VOISequenceLUT` Class.

>         public void Recalculate()
>         {
>             GetLUTDescriptor();
> 
>             var LUTDataElement = _renderOptions.VOILUTSequence.Items[0].GetDicomItem<DicomElement>(DicomTag.LUTData);
>             switch (LUTDataElement.ValueRepresentation.Code)
>             {
>                 case "OW":
>                 {
>                     var LUTData = LUTDataElement as DicomOtherWord;
>                     _LUTDataArray = ConvertAll(Dicom.IO.ByteConverter.ToArray<ushort>(LUTData.Buffer), x => (int)x);
>                     break;
>                 }
>                 case "US":
>                 {
>                     var LUTData = LUTDataElement as DicomUnsignedShort;
>                     _LUTDataArray = ConvertAll(Dicom.IO.ByteConverter.ToArray<ushort>(LUTData.Buffer), x => (int)x);
>                     break;
>                 }
>                 case "SS":
>                 {
>                     var LUTData = LUTDataElement as DicomSignedShort;
>                     _LUTDataArray = ConvertAll(Dicom.IO.ByteConverter.ToArray<short>(LUTData.Buffer), x => (int)x);
>                     break;
>                 }
>             }
> 
>             // Added
>             // If number of Table Entries is 2^16 and the first value of LUT Descriptor is 0
>             // _nrOfEntries should be corrected
>             if (_LUTDataArray.Length == 65536 && _nrOfEntries == 0)
>             {
>                 _nrOfEntries = _LUTDataArray.Length;
>             }
>         }
> 
>         private void GetLUTDescriptor()
>         {
>             var lutDescriptorElement = _renderOptions.VOILUTSequence.Items[0].GetDicomItem<DicomElement>(DicomTag.LUTDescriptor);
>             if (lutDescriptorElement.ValueRepresentation.Code == "SS")
>             {
>                 var LUTDescriptor = lutDescriptorElement as DicomSignedShort;
>                 _nrOfEntries = Math.Abs(LUTDescriptor.Get<int>(0)); //Sometimes negative number is defined and this makes no sense
>                 _firstInputValue = LUTDescriptor.Get<int>(1);
>                 _nrOfBitsPerEntry = LUTDescriptor.Get<int>(2);
>             }
>             else
>             {
>                 var LUTDescriptor = lutDescriptorElement as DicomUnsignedShort;
>                 _nrOfEntries = LUTDescriptor.Get<int>(0);
>                 _firstInputValue = LUTDescriptor.Get<int>(1);
>                 _nrOfBitsPerEntry = LUTDescriptor.Get<int>(2);
>             }
>         }
> 

`GetLUTDescriptor()` gets the first value of LUT Descriptor and assigns it to the `_nrOfEntries` field. The `_nrOfEntries` field of `VOISequenceLUT` Class indicates the number of table entries, that is, the first value of LUT Descriptor. And when LUT Data is gotten, if the length of `_LUTDataArray` is 2<sup>16</sup> it seems that `IndexOutOfRangeException` occurs because of the number of table entries that became 0 by the above condition.

At the end of the `Recalculate()` Method of the `VOISequenceLUT` Class, the value of the `_nrOfEntries` field is changed to **the actual number of Table Entries**, not the first value of the LUT Descriptor, depending on the conditions as in the code above.

Since it is not known whether this part is actually the intended part of the developer, we register it as an issue to request confirmation.

Please make sure that the code I modified correctly reflects the meaning of DICOM Standard.

If you have any additional needs, please leave a comment. We will try to check the comments and give you more information.

### fo-dicom version and OS/platform
fo-dicom 4.04 / .NET Framework 4.7 / Windows10 / x64

**Comment by gofal** [comment]
Thanks for giving this great detailled bug report.
fo-dicom acutally did not handle the case, that the number of items may be 0 and should then be considered to be 2^16. 

I hope you do not mind, but i changed the code in that way, that when in `GetLutDescriptor` the number of entries is 0, then it is set to 2^16. So pretty exactly as it is described in DICOM standard.

Later then, on the spot, where you added the code, I just check the array size (that was missing so far) and throw a exception in case that does not match. now you will get a meaningful exception whenever the array size mismatches the Descriptor, instead of getting some IndexOutOfRange-exception.

Could you give a try?

**Comment by JungWooHwang** [comment]
I'm glad I helped a little with this project.
I think it's better to create an exception that identifies the problem, as you did, than to make an unintended change like I did and get rid of the exception.

I tested it again with the corrections and it seems to work very well. It seems that the exception for the DICOM file with the wrong LUT Data is also properly generated.

If the exception occurred because the LUT data is wrong, as you have corrected, it seems highly desirable that the application developer does not apply the LUT by handling it.
There is one problem here.
I avoided the problem by removing the VOI LUT Sequence from the Dataset before `RenderImage()`.
But, the Obsolete Attribute Message says that should not access the Dataset Property of the `DicomImage` Class.
If so, I think there is a need for a way to remove LUT data without accessing the Dataset of the `DicomImage` Instance in order to `RenderImage()` a `DicomImage` with invalid LUT Data.

Is there a way to create a bitmap image by ignoring LUT data?
Please let me know if there is a way. If not, wouldn't it be necessary to think about it?

**Comment by gofal** [comment]
To understand you right: you do have other images where the actual number of entries does not match the first value of the LutDescriptor? Because the sample image you provided is rendered correctly.

And of course there is a way to render without the LUT. `DicomImage` has a property `UseVOILUT` what you can set to `false` before calling `RenderImage()`.

**Comment by JungWooHwang** [comment]
This is a problem I stumbled upon while testing DICOM files I also had, so unfortunately I couldn't find any additional sample DICOM files.

In the current version, if an exception occurs in the indexer, `UseVOILUT` property cannot be used. Since we use the fo-dicom library through NuGet Package, we have no choice but to use it with the VOI LUT Sequence removed until the next version is released.
Can you tell me when the next version will be released?

**Comment by gofal** [comment]
I want to fix the issues on github, that are labled with "bug", as many as possible and then there will be the next 4-release. I also plan to do a version 5 release then.
