### ISSUE TITLE
"Malformed DICOM json" exception is thrown by JsonDicomConverter if the dataset item with VR=FL and Value = NaN exists in DicomJson.

### ISSUE THREAD

**Issue by poadhika** [fo-dicom/fo-dicom#1063]
"Malformed DICOM json" exception is thrown by JsonDicomConverter if the dataset item with VR=FL and Value = NaN exists in DicomJson. If such VR values can be serialized successfully then they should be deserialized successfully as well.

Also From the Dicom Spec:
On Section 8 of PS3.5, it states following:

"For Pixel Data values encoded in OF and OD, any value that is permitted by the IEEE 754:1985 may be used, including NaN, +ve Infinity and -ve Infinity."

### Expected behavior
No exception should be thrown

### Actual behavior
"Malformed DICOM json" exception is thrown 

### Steps to reproduce the behavior
1. Perform STOW operation to Serialize and store the following Dicom File.
[DownLoad Sample Dicom File](https://drive.google.com/file/d/1Tfiza3IJgeQlKG_m0N7WIhqpOW5A_Foo/view?usp=sharing)

2. Stow will be successful.
3. Perform WADO-RS to retrieve the metadata of the stored file.
4. "Malformed DICOM json" exception will be thrown by JsonDicomConverter

Exception is being thrown by private static T[] ReadJsonMultiNumberValue<T>(JToken token)
from JsonDicomConverter.cs. 

### fo-dicom version and OS/platform
Version 4.0.5 .NET Framework 4.8 Windows 10 64 bit.

**Comment by amoerie** [comment]
Hey poadhika, I'm no expert on the JSON side of things, but I do see that you create a pull request in your own fork. 
May I suggest that you create a pull request here, in https://github.com/fo-dicom/fo-dicom? You should be able to choose a branch from your own fork when doing so. That'll allow us more easily to see the changes you've made, and to possibly accept it. 

Thanks!

**Comment by poadhika** [comment]
> Hey poadhika, I'm no expert on the JSON side of things, but I do see that you created a pull request in your own fork.
> May I suggest that you create a pull request here, in https://github.com/fo-dicom/fo-dicom? You should be able to choose a branch from your own fork when doing so. That'll allow us more easily to see the changes you've made, and to possibly accept it.
> 
> Thanks!

I have created the PR against fo-dicom. Please take a look.

**Comment by gofal** [comment]
here some more information sent via gitter to explain ths change:

> So we are seeing this behvaior that a Dicom File has a pixel data that has VR Value NaN for Vr type FL. Looks like json serializer is serializing it correctly but deserielaizer throws an exception of "Malformed Dicom"
> 
> Dicom spec says the following for such values
> "
> On Section 8 of P3.5, it states following:
> 
>"For Pixel Data values encoded in OF and OD, any value that is permitted by the IEEE 754:1985 may be used, including NaN, +ve Infinity and -ve Infinity."
> 
> "
> 
> In our case we are seeing this value for VR = FL ( not OF or OD as specified in Spec).

**Comment by gofal** [comment]
perged the pull request.
