### ISSUE TITLE
Print SCU  Sample   Is Error 

### ISSUE THREAD

**Issue by dhanzhang** [fo-dicom/fo-dicom#107]
![20151012165302](https://cloud.githubusercontent.com/assets/457633/10424569/c052d06c-7102-11e5-85c8-0b675309eeeb.png)
Can't   Send  PrintSCU  To Server..

**Comment by dhanzhang** [comment]
..\fo-dicom\DICOM\DicomDatasetWalker.cs  
///---------------------------
    /// <summary>
        /// Perform a dataset walk.
        /// </summary>
        /// <param name="walker">Walker implementation.</param>
        /// <param name="items">Queue of internal items; must be initialized and empty when called from external method.</param>
        private static void DoWalk(IDicomDatasetWalker walker, Queue<DicomItem> items)
        {
#if  !DEBUG
            try
            {

#endif
            walker.OnBeginWalk();

            while (items.Count > 0)
            {
                var item = items.Dequeue();

                if (item is DicomElement)
                {
                    walker.OnElement(item as DicomElement);
                }
                else if (item is DicomFragmentSequence)
                {
                    walker.OnBeginFragment(item as DicomFragmentSequence);
                }
                else if (item is DicomFragmentItem)
                {
                    walker.OnFragmentItem((item as DicomFragmentItem).Buffer);
                }
                else if (item is EndDicomFragment)
                {
                    walker.OnEndFragment();
                }
                else if (item is DicomSequence)
                {
                    walker.OnBeginSequence(item as DicomSequence);
                }
                else if (item is BeginDicomSequenceItem)
                {
                    walker.OnBeginSequenceItem((item as BeginDicomSequenceItem).Dataset);
                }
                else if (item is EndDicomSequenceItem)
                {
                    walker.OnEndSequenceItem();
                }
                else if (item is EndDicomSequence)
                {
                    walker.OnEndSequence();
                }
            }

            walker.OnEndWalk();
#if !DEBUG
            }
            catch (Exception e)
            {
                try
                {
                    walker.OnEndWalk();
                    throw;
                }
                catch
                {
                    throw e;
                }
            }
#endif
        }

        /// <summary>
        /// Perform an asynchronous dataset walk.
        /// </summary>
        /// <param name="walker">Walker implementation.</param>
        /// <param name="items">Queue of internal items; must be initialized and empty when called from external method.</param>
        private static async Task DoWalkAsync(IDicomDatasetWalker walker, Queue<DicomItem> items)
        {
#if  !DEBUG
            try
            {

#endif

            walker.OnBeginWalk();

            while (items.Count > 0)
            {
                var item = items.Dequeue();

                if (item is DicomElement)
                {
                    await walker.OnElementAsync(item as DicomElement).ConfigureAwait(false);
                }
                else if (item is DicomFragmentSequence)
                {
                    walker.OnBeginFragment(item as DicomFragmentSequence);
                }
                else if (item is DicomFragmentItem)
                {
                    await walker.OnFragmentItemAsync((item as DicomFragmentItem).Buffer).ConfigureAwait(false);
                }
                else if (item is EndDicomFragment)
                {
                    walker.OnEndFragment();
                }
                else if (item is DicomSequence)
                {
                    walker.OnBeginSequence(item as DicomSequence);
                }
                else if (item is BeginDicomSequenceItem)
                {
                    walker.OnBeginSequenceItem((item as BeginDicomSequenceItem).Dataset);
                }
                else if (item is EndDicomSequenceItem)
                {
                    walker.OnEndSequenceItem();
                }
                else if (item is EndDicomSequence)
                {
                    walker.OnEndSequence();
                }
            }

            walker.OnEndWalk();
#if  !DEBUG
            }
            catch (Exception e)
            {
                try
                {
                    walker.OnEndWalk();
                    throw;
                }
                catch
                {
                    throw e;
                }
            }
#endif
        }

        #endregion
    }

**Comment by anders9ustafsson** [comment]
@dhanzhang Which *fo-dicom* version are you using? Is port 105 truly accessible? Have you managed to get Print SCU to work, or is it failing all the time?

**Comment by dhanzhang** [comment]
@anders9ustafsson    I  git clone the latest .   And  I try  again . this time  just change  the following code 
1) Dicom.Printing.PrintService.cs
![20151013110529](https://cloud.githubusercontent.com/assets/457633/10444524/5e099db2-719a-11e5-9f3f-a12256f9a2aa.png)
2)  DICOM\DicomDatasetWalker.cs        like above

**Comment by dhanzhang** [comment]
![20151013111604](https://cloud.githubusercontent.com/assets/457633/10444672/d4736720-719b-11e5-8829-8cc4bbfccfad.png)

**Comment by dhanzhang** [comment]
![20151013111652](https://cloud.githubusercontent.com/assets/457633/10444688/f0c91ab4-719b-11e5-9875-a5dcccf0e530.png)

**Comment by dhanzhang** [comment]
![20151013111730](https://cloud.githubusercontent.com/assets/457633/10444722/057b9f18-719c-11e5-91b9-773ea5eef73f.png)

**Comment by dhanzhang** [comment]
@anders9ustafsson     it's failing all the time .

**Comment by anders9ustafsson** [comment]
@dhanzhang Sorry for not getting back sooner. When you state that you are using the latest source code, I assume you mean the code from the *development* branch? During the work on PR #109 I found an issue in the `DicomService` class that could very well be related to the failures you are experiencing. I have fixed the issue in the pull request, but the PR has not been merged yet.

If you are in urgent need of this functionality, I recommend that you switch to the *master* branch and use the *Print SCU* and *Print SCP* applications from this branch. Or even better, you can clone my private fork from [here](https://github.com/anders9ustafsson/fo-dicom), switch to and build the *GH-60* branch to check whether the printing issue is fixed in that branch.

Please report your findings regardless.

**Comment by dhanzhang** [comment]
@anders9ustafsson      thank you very much !   the  1.1 branch is no this issue.

**Comment by anders9ustafsson** [comment]
OK, thanks for verifying @dhanzhang . I hope to soon merge pull request #109 to *development* also. When I do, perhaps you can check again if your problem is solved using those modifications as well.

**Comment by dhanzhang** [comment]
@anders9ustafsson   under debug model,   I think disable  TRY_CATCH  statement may be better to  debug  or test ?

**Comment by dhanzhang** [comment]
@anders9ustafsson    1.1 branch   ,test  pass .
