### ISSUE TITLE
16bit DX Image pixcel getting damaged while changing is transfer syntax to JPEG 2000 Lossy

### ISSUE THREAD

**Issue by yadavvirus** [fo-dicom/fo-dicom#1083]
I was trying to change transfersyntax of 16bit DX but Its getting wrose please see the attached image.
One is oreginal another one is Changed and DICOM Image uploaded too.
[dx.zip](https://github.com/fo-dicom/fo-dicom/files/5056840/dx.zip)

![IMG-0003-00001](https://user-images.githubusercontent.com/7027914/89894850-691b7180-dbf8-11ea-8bec-0a1d09179e6a.jpg)

![IMG-0002-00001](https://user-images.githubusercontent.com/7027914/89894648-0b872500-dbf8-11ea-98b3-8fed1fc2998e.jpg)

Fellow Oak DICOM version: (e.g. 4.0.6)
OS: (e.g. Windows 8.1 x64)
Platform: (e.g. .NET Framework 4.6.2)

**Comment by gofal** [comment]
Which version of fo-dicom and which TranscoderManager did you use?

**Comment by yadavvirus** [comment]
Fo-DICOM V4.0.6.0 Dicom.Native.dll

**Comment by yadavvirus** [comment]
I have also attached .dcm file in zip please check that too.

**Comment by yadavvirus** [comment]
@gofal sir please check this file why transcoder keep on throwing error. Find dicom file in zip.

**Comment by gofal** [comment]
shure I will do as soon as I have the time.
But meanwhile could you give Efferent's codec a try? 
https://github.com/fo-dicom/fo-dicom/wiki/Native-codecs-on-.NET#is-the-transfer-syntax-supported-on-your-platform
https://github.com/Efferent-Health/fo-dicom.Codecs

This codec implementation is better than fo-dicom's dicom.native, because it runs on windows, linux and macos. They cloned fo-dicom's codec and do a lot of maintainment.

**Comment by yadavvirus** [comment]
Sure sir ll try.

**Comment by yadavvirus** [comment]
@gofal sir , sorry but the provided link code generates another name space liabrary. How I can use the transcoder with fo-diocm liabrary(Dicom.core.dll)
from this
https://github.com/Efferent-Health/fo-dicom.Codecs

**Comment by gofal** [comment]
Yes. because in next version 5 fo-dicom will use their codec by default, they were so kindly and changed the name from EfferentHealth.* to fo-dicom.Codec. 
But you can use it with version 4 too. 
Read here: https://github.com/Efferent-Health/fo-dicom.Codecs#with-fo-dicom-40

**Comment by gofal** [comment]
Did the codec from Efferent fix your issue?

**Comment by yadavvirus** [comment]
@gofal Actually I failed to use Efferent library. If possible can you please guide me how we can use that lib with fo-dicom lib.

**Comment by gofal** [comment]
@yadavvirus Plase give more details about the error your transcoder throws.

Here is my sample project, I just created: a new netframework 4.6.2 console application, add nuget-reference to "fo-dicom.Desktop 4.0.7"

the method is:

        using Dicom;
        using Dicom.Imaging;
        using Dicom.Imaging.Codec;
        
        namespace ConsoleApp4
        {
           class Program
           {
              static void Main(string[] args)
              {
        
                 var dataset = Dicom.DicomFile.Open(@"D:\dicom\fo-dicom\gh-1083\dx.dcm");
                 var image = new DicomImage(dataset.Dataset);
        
                 var rendered = image.RenderImage().AsBitmap();
        
                 rendered.Save(@"D:\dicom\fo-dicom\gh-1083\dx.jpeg", System.Drawing.Imaging.ImageFormat.Jpeg);
        
                 var transcodedDataset = dataset.Clone(DicomTransferSyntax.JPEGProcess14);
                 var transcodedImage = new DicomImage(transcodedDataset.Dataset);
        
                 var transcodedRendered = transcodedImage.RenderImage().AsBitmap();
        
                 transcodedRendered.Save(@"D:\dicom\fo-dicom\gh-1083\dxtranscoded.jpeg", System.Drawing.Imaging.ImageFormat.Jpeg);
        
              }
           }
        }

where the input dx.dcm is the file you provided above.
There is no error when transcoding. And the output of this application are these files:

**Comment by gofal** [comment]
![dx](https://user-images.githubusercontent.com/6769246/103178849-f51bf600-4886-11eb-9635-97a86a5ee4e4.jpeg)
![dxtranscoded](https://user-images.githubusercontent.com/6769246/103178853-f6e5b980-4886-11eb-9a18-39f3c709391e.jpeg)

**Comment by yadavvirus** [comment]
@gofal 
Thank you sir for helping me.
Sir i have tried above code is working fine with all possible transfersynatx but when i put
var transcodedDataset = dataset.Clone(DicomTransferSyntax.JPEG2000Lossy, new DicomJpeg2000Params { Rate = 255 });
then show error of readonlymemory and after few attempts application started crashing.
Sorry sir to disturb you.
But please sir if possible try to change image in DicomTransferSyntax.JPEG2000Lossy.
Thank you sir

**Comment by yadavvirus** [comment]
@gofal Hello Sir,
Sorry sir to disturb Please sir take a look in above compression. Thank you sir

**Comment by gofal** [comment]
Closing this issue, because it is about issues in codec. Issues should be opend/discussed in fo-dicom.Codec repository.
