### ISSUE TITLE
RenderImage().Asbitmap()  throw exception 

### ISSUE THREAD

**Issue by ByZhouhang** [fo-dicom/fo-dicom#1087]
**Describe the bug**

Cannot cast to 'Bitmap'; type must be assignable from 'Byte[]'”

    DicomImage image = new DicomImage(filePath);
                    MemoryStream imageBuffer = new MemoryStream();
                    using (var rendered = image.RenderImage())
                    {
                        rendered.AsClonedBitmap().Save(imageBuffer, ImageFormat.Jpeg);
                    }

**Environment**
Fellow Oak DICOM version: (e.g. 4.0.6)
OS: (e.g. Windows 10 x64)
Platform: (e.g. .NET core 3.1)

**Comment by gofal** [comment]
The `AsClonedBitmap()` is a convenience function hat converts your rendered image into a Bitmap. But in order that this works under the hood, you first have to make sure, that you are really using the ImageManager that renders Windows Bitmaps.

Somewhere where you are doing your initializations you have to call

      ImageManager.SetImplementation(WinFormsImageManager.Instance);

See here: https://github.com/fo-dicom/fo-dicom/wiki/Image-rendering

**Comment by ByZhouhang** [comment]
I'm using  asp.net Core 3.1 developing web project   ImageManager.SetImplementation(WinFormsImageManager.Instance); 
 can not find   WinFormsImageManager  ，I try it in  winform    Can find  WinFormsImageManager    
 How can I use it in  asp.net core  web projects

**Comment by ByZhouhang** [comment]
I'm using asp.net Core 3.1 developing web project.   ImageManager.SetImplementation(WinFormsImageManager.Instance);
can not find WinFormsImageManager ，I try it in winform project   it Can find WinFormsImageManager
How can I use it in asp.net core web projects

**Comment by ByZhouhang** [comment]
> **Describe the bug**
> 
> Cannot cast to 'Bitmap'; type must be assignable from 'Byte[]'”
> 
> ```
> DicomImage image = new DicomImage(filePath);
>                 MemoryStream imageBuffer = new MemoryStream();
>                 using (var rendered = image.RenderImage())
>                 {
>                     rendered.AsClonedBitmap().Save(imageBuffer, ImageFormat.Jpeg);
>                 }
> ```
> 
> **Environment**
> Fellow Oak DICOM version: (e.g. 4.0.6)
> OS: (e.g. Windows 10 x64)
> Platform: (e.g. .NET core 3.1)

I'm using asp.net Core 3.1 developing web project. ImageManager.SetImplementation(WinFormsImageManager.Instance);
can not find WinFormsImageManager ，I try it in winform project it Can find WinFormsImageManager
How can I use it in asp.net core web projects

**Comment by ByZhouhang** [comment]
> The `AsClonedBitmap()` is a convenience function hat converts your rendered image into a Bitmap. But in order that this works under the hood, you first have to make sure, that you are really using the ImageManager that renders Windows Bitmaps.
> 
> Somewhere where you are doing your initializations you have to call
> 
> ```
>   ImageManager.SetImplementation(WinFormsImageManager.Instance);
> ```
> 
> See here: https://github.com/fo-dicom/fo-dicom/wiki/Image-rendering

thanks ,    document  write  Windows Forms based imaging is selected by default.   
  ImageManager.SetImplementation(WinFormsImageManager.Instance) also should inicialize in  .net core 3.1 web project

**Comment by gofal** [comment]
the initialization of the ImageManger is done by default as good as possible, but it is not always possible.

fo-dicom is compiled in several platforms: netFramework, netstandard, mono, PCL... 
If you use the netFramework-version (called fo-dicom.desktop), then the WindowsForms image manager is initialized by default.
if running in .net core then visual studio tries to bind the netstandard, where the WinformsImageManager cannot be initialized by default, because on linux or so this would not be available. 

The whole net core thing made the detection of the platforms little tricky, thats why explicit initializations are often necessary.

The next major version 5.0.0 of fo-dicom deals with this and used state of the art techniques like DependencyInjection instead of manager-instances that are initialized via Reflection.

**Comment by gofal** [comment]
So is your issue fixed now?

**Comment by ByZhouhang** [comment]
> So is your issue fixed now?

fixed thanks
