### ISSUE TITLE
DicomTag GetHashCode is grossly inefficient

### ISSUE THREAD

**Issue by edespong** [fo-dicom/fo-dicom#1088]
**Describe the bug**
When parsing a DICOM header, around 50% of all allocations from fo-dicom are stemming from the following lines in `DicomTag`:

```
public override int GetHashCode()
{
            if (_hash == 0) _hash = ToString("X", null).GetHashCode();
            return _hash;
        }
```

This causes a significant performance hit.

**To Reproduce**
Run a memory profiler or a performance benchmark parsing a file, e.g. `DicomFile.Open(content, FileReadOption.Default)` and look at the results

**Expected behavior**
GetHashCode should not allocate anything. Something like: `return unchecked(Group ^ Element)` should be fine, see [Point in System.Drawing reference ](https://referencesource.microsoft.com/#System.Drawing/commonui/System/Drawing/Point.cs) (and does not need caching)

**Environment**
Fellow Oak DICOM version: 4.0.6

**Comment by gofal** [comment]
Thanks for this hint! Will of course be changed.

**Comment by rcd** [comment]
Didn't this used to be `(int)ToUInt32()`? Did that lead to conflicts?

**Comment by rcd** [comment]
Maybe it should be closer to the following if private tags were causing an issue?

```
        public override int GetHashCode()
        {
            if (_hash == 0)
            {
                _hash = (int)ToUInt32();
                if (PrivateCreator != null)
                    _hash ^= PrivateCreator.Creator.GetHashCode();
            }
            return _hash;
        }
```

**Comment by rkm** [comment]
Hi @edespong. Are you able to share what tools/methods you used to run your performance benchmark? Thanks!

**Comment by edespong** [comment]
Hi,

My benchmark is essentially this (BenchmarkDotNet):

    ```[MemoryDiagnoser]
    public class FoDicom : Benchmark {
        public override string Library => nameof(FoDicom);

        [Benchmark]
        public object ParseHeader() {
            return ParseHeader(this.content);
        }

        public static object ParseHeader(Stream content) {
            content.Position = 0;
            var file = DicomFile.Open(content);
            return file;
        }
    }
```


For diagnosing the issues, I used DotMemory. There are quite a lot of other things that will improve things even more, but I will take those in separate issues.

Results before and after (using the unchecked(Group ^ Element), but I expect the @rcd proposal to not differ greatly). As you can see, the CT and MR cases more than doubles in parsing speed.

|      Method |     HeaderName |         Mean |      Error |       StdDev |       Median |     Gen 0 |     Gen 1 | Gen 2 |   Allocated |
|------------ |--------------- |-------------:|-----------:|-------------:|-------------:|----------:|----------:|------:|------------:|
| ParseHeader |         ct.dcm |    172.07 us |   3.465 us |     9.659 us |    172.95 us |         - |         - |     - |       72 KB |
| ParseHeader |         ko.dcm |     73.00 us |   1.559 us |     2.185 us |     72.43 us |   11.8408 |         - |     - |    50.08 KB |
| ParseHeader |         mr.dcm |    203.54 us |   4.710 us |    12.972 us |    205.65 us |         - |         - |     - |       80 KB |
| ParseHeader |        pet.dcm |    229.78 us |   3.244 us |     2.876 us |    229.95 us |   47.3633 |    1.2207 |     - |   200.49 KB |
| ParseHeader |         sr.dcm |  2,566.49 us |  49.157 us |    52.598 us |  2,553.71 us |  226.5625 |  113.2813 |     - |   1391.8 KB |
| ParseHeader |         us.dcm |    148.39 us |   3.042 us |     3.736 us |    147.53 us |   20.9961 |         - |     - |    89.47 KB |
| ParseHeader | wsi-header.dcm | 31,203.57 us | 692.750 us | 1,725.188 us | 30,479.40 us | 2000.0000 | 1000.0000 |     - | 14216.13 KB |


|      Method |     HeaderName |         Mean |      Error |     StdDev |       Median |     Gen 0 |   Gen 1 | Gen 2 |  Allocated |
|------------ |--------------- |-------------:|-----------:|-----------:|-------------:|----------:|--------:|------:|-----------:|
| ParseHeader |         ct.dcm |     69.08 us |   1.166 us |   1.033 us |     68.74 us |    7.6904 |       - |     - |   32.77 KB |
| ParseHeader |         ko.dcm |     52.77 us |   1.054 us |   2.684 us |     51.94 us |    6.4087 |       - |     - |   27.26 KB |
| ParseHeader |         mr.dcm |     87.14 us |   1.599 us |   1.496 us |     86.80 us |    9.1553 |       - |     - |   38.81 KB |
| ParseHeader |        pet.dcm |    167.43 us |   2.807 us |   2.626 us |    167.95 us |   31.4941 |  7.8125 |     - |  133.34 KB |
| ParseHeader |         sr.dcm |  1,755.24 us |  37.243 us |  63.242 us |  1,731.85 us |  125.0000 | 62.5000 |     - |  767.85 KB |
| ParseHeader |         us.dcm |    101.07 us |   1.895 us |   1.861 us |    100.51 us |    9.7656 |       - |     - |   41.64 KB |
| ParseHeader | wsi-header.dcm | 21,291.24 us | 398.329 us | 353.108 us | 21,229.70 us | 1000.0000 |       - |     - | 8536.66 KB |

**Comment by amoerie** [comment]
@edespong I've created a PR that addresses this concern. We already maintain a little suite of benchmarks here: https://github.com/fo-dicom/fo-dicom/tree/development/Tests/FO-DICOM.Benchmark

If your files are properly anonymized, I would be interested to add them to these benchmarks. In the future, we should find a way to run the benchmarks for each pull request so we can detect performance degradations. I believe the .NET guys have already figured this out, so maybe there's a way.

**Comment by amoerie** [comment]
Do we still need to cache the _hash value if we're just using numbers? 

- It's just a number, but it's per DICOM tag, and we have lots of those
- There's no thread safety, so there's absolutely no guarantee that it's not being calculated multiple times anyway
- It's probably blazing fast to calculate now, since we only push a few numbers.

**Comment by gofal** [comment]
I have created some benchmark. This are my results with the original version prior to thich change:

    |        Method |     Mean |   Error |  StdDev |   Gen 0 |   Gen 1 | Gen 2 | Allocated |
    |-------------- |---------:|--------:|--------:|--------:|--------:|------:|----------:|
    |       ParseCT | 567.3 us | 1.09 us | 1.02 us | 45.8984 | 10.7422 |     - |  282.3 KB |
    |       ParseMR | 680.5 us | 5.38 us | 4.77 us | 58.5938 | 14.6484 |     - | 364.66 KB |
    | ParseDicomdir | 877.7 us | 2.75 us | 2.43 us | 60.5469 | 19.5313 |     - |  375.3 KB |`

then the examt same test with the change that is currently pushed in PR

    |        Method |     Mean |    Error |   StdDev |   Gen 0 |   Gen 1 | Gen 2 | Allocated |
    |-------------- |---------:|---------:|---------:|--------:|--------:|------:|----------:|
    |       ParseCT | 480.0 us |  3.80 us |  3.17 us | 40.5273 |  9.7656 |     - | 250.83 KB |
    |       ParseMR | 579.2 us | 11.44 us | 10.71 us | 52.7344 | 12.6953 |     - | 326.85 KB |
    | ParseDicomdir | 679.6 us |  2.83 us |  2.51 us | 49.8047 | 16.6016 |     - | 309.49 KB |

you see the great improvement in memory allocation as well as in cpu time
And then this is, when I remove the _hash field and simplify the GetHashCode by just returning the calulated hash instead of the if-condition to check if _hash is not 0

    |        Method |     Mean |   Error |  StdDev |   Gen 0 |   Gen 1 | Gen 2 | Allocated |
    |-------------- |---------:|--------:|--------:|--------:|--------:|------:|----------:|
    |       ParseCT | 469.8 us | 2.44 us | 2.16 us | 40.0391 |  9.7656 |     - | 250.83 KB |
    |       ParseMR | 564.4 us | 4.09 us | 3.82 us | 52.7344 | 12.6953 |     - | 326.85 KB |
    | ParseDicomdir | 679.2 us | 6.31 us | 5.90 us | 49.8047 | 16.6016 |     - | 309.49 KB |

memory is just the same, so no improvement. But the cpu is litte bit better. i assume because of heavy inlining of the compiler and the fact that dotnet just returns the integer value if you call .GetHashValue on a integer or uint. So all the `if _hash > 0` can be saved.

**Comment by gofal** [comment]
also tried hybrides, where only the hash of the PrivateCreator is cached, but it does not get better.
i will commit the benchmarktest and the change without caching _hash
