### ISSUE TITLE
Excessive memory allocations in DicomService 

### ISSUE THREAD

**Issue by edespong** [fo-dicom/fo-dicom#1091]
**Describe the bug**
The `DicomService `allocates a lot of memory that it does not need.

In two places, `byte[]`s are created where it could easily be removed, increasing performance and reducing memory load.

1:
In `SendNextPDUAsync`, the following code:
```
var ms = new MemoryStream();
pdu.Write().WritePDU(ms);

var buffer = ms.ToArray();
await _network.AsStream().WriteAsync(buffer, 0, (int)ms.Length).ConfigureAwait(false);
```

can be replacable with

```
var ms = new MemoryStream();
pdu.Write().WritePDU(ms);

ms.Seek(0, SeekOrigin.Begin);
await ms.CopyToAsync(_network.AsStream()).ConfigureAwait(false);
```

2:
In `ListenAndProcessPDUAsync`, the following is done:

```
using (var ms = new MemoryStream()) { 
    ms.Write(buffer, 0, buffer.Length);
    ...
    buffer = ms.ToArray();
}      

var raw = new RawPDU(buffer);
```

but we can see in `RawPDU` that the only thing we do with the byte[] is to create another MemoryStream. So with a new constructor on RawPDU which can take ownership of an existing stream, e.g.

```
public RawPDU(MemoryStream ms) {
            ms.Seek(0, SeekOrigin.Begin);
            _ms = ms;
            _br = EndianBinaryReader.Create(_ms, Endian.Big);
            _type = _br.ReadByte();
            _ms.Seek(6, SeekOrigin.Begin);
}
```

we can instead do:

```
var ms = new MemoryStream();
ms.Write(buffer, 0, buffer.Length); 
....
var raw = new RawPDU(ms);
```

Making these two changes will reduce the number of total allocations with 15% and the total memory allocated with 20% in my test scenario where I have a simple sender and receiver.

**Environment**
Fellow Oak DICOM version: 4.0.6
OS: Windows 10
Platform: Independent

**Comment by amoerie** [comment]
Thanks for making an issue about this! I actually had a few similar thoughts about this, but for example the part where it writes to an intermediate buffer instead of directly to the network stream is something curious. The simplest implementation is writing to the network stream directly, so why create a buffer at all? It seems to be done with a deliberate reason.

Anyhow, if you are up to it, you are more than welcome to create a PR, otherwise it will end up on the TODO list of me or @gofal, but then your patience will be tested a bit. 🙂

**Comment by gofal** [comment]
I am not for 100% sure, but I also did quite some byte-array-allocation optimizations in version 5.0.0, but only within the classes that implement IByteBuffer.
When it comes with Enidaness issues (littleEndian, bigendian) then the processor of the stream does change the bytes in the array. So there may have been issues where the data has been changed and therefore on every call a new byte array is passed through.

Then testing the pull request, please make sure that you send many data with LittleEndian transfer syntax (which is not hard) and also with BigEndian transfer syntax.

**Comment by amoerie** [comment]
> Then testing the pull request, please make sure that you send many data with LittleEndian transfer syntax (which is not hard) and also with BigEndian transfer syntax.

Sounds like we should have a unit test for this, no?

**Comment by edespong** [comment]
> 
> When it comes with Enidaness issues (littleEndian, bigendian) then the processor of the stream does change the bytes in the array. So there may have been issues where the data has been changed and therefore on every call a new byte array is passed through.

But if we are only dealing with the creation and copying of PDUs, which is the case here (although not super obvious from the code above) we would always have Big Endian, right?

**Comment by gofal** [comment]
> But if we are only dealing with the creation and copying of PDUs, which is the case here (although not super obvious from the code above) we would always have Big Endian, right?

yes, you are right. The byte buffers should already be corrected at this moment.

**Comment by gofal** [comment]
The class RawPDU holds a memory stream and has the instance of EndianBinaryWriter. The different PDU implementations create an instance of RawPDU and use its write-method, which passes the data through the EndianBinaryWriter. So Endianess is done.

This code in DicomService.SendNextPDUAsync:

                    var ms = new MemoryStream();
                    pdu.Write().WritePDU(ms);

                    ms.Seek(0, SeekOrigin.Begin);
                    await ms.CopyToAsync(_network.AsStream()).ConfigureAwait(false);

creates a new memorystream, then the RawPDU instance writes one header and its internal MemoryStream into the new memorystream and then this new memorystream is copied into the networkstream.

Do you think, we could also get rid of this temporary MemoryStream?

If you add this method to RawPDU (it is only an async version of RawPDU.WritePDU)

        public async Task WritePDUAsync(Stream s)
        {
            var buffer = new byte[6];

            unchecked
            {
                buffer[0] = _type;

                var length = (uint)_ms.Length;
                buffer[2] = (byte)((length & 0xff000000U) >> 24);
                buffer[3] = (byte)((length & 0x00ff0000U) >> 16);
                buffer[4] = (byte)((length & 0x0000ff00U) >> 8);
                buffer[5] = (byte)(length & 0x000000ffU);
            }

            await s.WriteAsync(buffer, 0, 6).ConfigureAwait(false);
            await _ms.CopyToAsync(s).ConfigureAwait(false);
        }

Then the above code in DicomService.SendNextPDUAsync could look like that:

                    await pdu.Write().WritePDUAsync(_network.AsStream()).ConfigureAwait(false);

This would reduce one more MemoryStream.
Can you give it a try and do your evaluation with this code?

**Comment by edespong** [comment]
Good suggestions, I will try them out when I can carve out some time and update here.

**Comment by edespong** [comment]
It turns out that this might not be as clear-cut as initially thought. I am running a 'clean' send benchmark where I load 1000 images into memory, creating `CStoreRequest`s of them and then measure the allocations of doing:

```
await client.AddRequestsAsync(requests).ConfigureAwait(false);
await client.SendAsync().ConfigureAwait(false);
```

Running with the initial changes plus @gofal's addition, there is a reduction in total bytes allocated from `2.71 Gb` -> `1.76 Gb` compared to fo-dicom 4.0.6. 

However, the total number of allocated objects acutally increase from `458k` to `750k`. This seems related to the fact that we are now doing very frequent calls to small async methods, which internally allocates compiler generated classes containing the state machine of the async call. The main offenders are:

`DicomService+PDataTFStream+<WriteAsync>d__30` with 192k allocations 
`DicomWriter+<WriteBufferAsync>d_23` with 48k allocations
`DicomWriter+<OnElementAsync>d_11` with 48k allocations

So it is not obvious that this change (1) will actually improve things.

**Comment by gofal** [comment]
I see. Many thaks for this great analysis.
So the issue is this async state machine. Every method with the "async" keyword generates such one, so the better method would be:

    public /* async */ Task WritePDUAsync(Stream s)
    {
        var buffer = new byte[6];

        unchecked
        {
            buffer[0] = _type;

            var length = (uint)_ms.Length;
            buffer[2] = (byte)((length & 0xff000000U) >> 24);
            buffer[3] = (byte)((length & 0x00ff0000U) >> 16);
            buffer[4] = (byte)((length & 0x0000ff00U) >> 8);
            buffer[5] = (byte)(length & 0x000000ffU);
        }

        // write this 6 bytes synchronously. this is only small data.
        s.Write(buffer, 0, 6);
        return /* await */ _ms.CopyToAsync(s) /* .ConfigureAwait(false) */;
    }
