### ISSUE TITLE
DicomServer Create CStore : NullReferenceException

### ISSUE THREAD

**Issue by sylvainb31** [fo-dicom/fo-dicom#1093]
**Describe the bug**

I have been using this code to implement the CStoreSCP : [https://github.com/fo-dicom/fo-dicom/issues/1039#issuecomment-636769708](https://github.com/fo-dicom/fo-dicom/issues/1039#issuecomment-636769708)

Everything works fine, except in my output in visual studio 2019 I have the following once all the images have been stored :

```
Exception levée : 'System.NullReferenceException' dans PortailWorker.dll
Exception levée : 'System.NullReferenceException' dans Dicom.Core.dll
Exception levée : 'System.NullReferenceException' dans System.Private.CoreLib.dll
Exception levée : 'System.NullReferenceException' dans PortailWorker.dll
Exception levée : 'System.NullReferenceException' dans Dicom.Core.dll
Exception levée : 'System.NullReferenceException' dans System.Private.CoreLib.dll
```

**To Reproduce**
Sending a C-Move to a local server which then send the C-Store back.

I use the code provided on the following comment for the C-Store SCP : [https://github.com/fo-dicom/fo-dicom/issues/1039#issuecomment-636769708](https://github.com/fo-dicom/fo-dicom/issues/1039#issuecomment-636769708)

**Expected behavior**
Well I expect it to works without any exceptions thrown. Is there a way to activate more debug informations ?

**Environment**
Fellow Oak DICOM version: 4.0.6
OS: Windows 10 Pro x64
Platform: netcoreapp3.1

**Comment by gofal** [comment]
And in visual studio there is the Exception-settings-window (Strg+Alt+E). There you can tell visual studio to halt on every System.NullReferenceException, even if it is catched by an ExceptionHandler. This will guide you to the root cause of the exceptions
