### ISSUE TITLE
Few Images are in Magenta colour when rendered

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#110]
*Reported via NuGet by user pooja13:*

For our Application we are using FO-Dicom version-1.0.37. 
I have seen an issue when rendering an image. Issue: Few Images are in Magenta colour when rendered. 
We are using RenderImage() API for rendering an image.
For investigation, I have updated the FO-Dicom to version 1.1.0 still I am observing the same issue. Again I have used the FO-Dicom version 1.0.36 then I did not the see images in Magenta colour. On further investigation, I observed that images which has overlays those type of images are coming in Magenta colour. 
With FO-Dicom version-1.0.37, I have disabled overlays before rendering the image. With this change I did not see the images are coming in Magenta colour. Here, Colour is removed but overlays are disabled. 
Could you guys please check why for images having overlays are coming in Magenta colour and give a fix for it. 
If you need any snapshot of the problem. Please let me know.

**Comment by anders9ustafsson** [comment]
Do I understand correctly that you are questioning why the overlays are displayed with magenta color? *fo-dicom* is pre-configured to display all overlays with magenta, where the overlay pixel value is non-zero. This pre-configuration has been around for a while, but of course the overlay handling can be improved. How would you like overlays to be displayed?

**Comment by kbpooja13** [comment]
![1](https://cloud.githubusercontent.com/assets/15139138/10509694/2f201e64-734c-11e5-865e-c6fcd011aec5.png)

I have attached the image how it is seen when rendered. 
Image is distorted and image is covered with Magenta colour. 
For us, overlay should be displayed but image should not be distorted as attached image.

**Comment by anders9ustafsson** [comment]
OK, I assume that you want to see the overlay in original grayscale, but with transparency so that you are able to view the underlying image as well. Is that correct?

To facilitate further investigation, could you please upload an anonymized copy of the DICOM file you used to obtain the image above?

**Comment by kbpooja13** [comment]
![7 01 13 1 711771191917816719918284741902111102192272547829](https://cloud.githubusercontent.com/assets/15139138/10533997/69c82712-73ee-11e5-92ef-0c593b39f633.png)

I have the dicom file and changed the extension to png. Change the file to dcm and use the image. 

Why is that image distorted?
we want to see the image as well as overlay(original colour which is used for overlay)

**Comment by anders9ustafsson** [comment]
@kbpooja13 Many thanks for providing the image, it will be very helpful for development.

As I explained above, this is not a distortion but intended behavior (implemented before my time on the *fo-dicom* team, though :-) ). For overlays, *fo-dicom* applies magenta color to all non-zero pixels in the overlay. 

This was probably implemented as a "quick-and-dirty" solution, just to get the basic overlay functionality in place, in particular for adding texts or lines to the image. Since the initial implementation, very little has been made to extend the functionality.

However, here you obviously have a use case that implies the need for further development of the overlay functionality in *fo-dicom*. We will definitely consider to extend *fo-dicom* overlay functionality to meet your requirements.

If you are able to view the overlay image in another viewer with desired overlay handling for this case, it would be good if you could also publish this image as a benchmark for this development.

**Comment by anders9ustafsson** [comment]
In *microDicom* and *RadiANT* viewers, the overlay is not displayed at all. With *PixelMed*, the image looks like this:

![overlay-in-pixelmed](https://cloud.githubusercontent.com/assets/6515030/10536439/4a36d91e-73eb-11e5-98b9-6ca497d32973.png)

In relation to this, the *fo-dicom* display seems pretty acceptable :-)

@kbpooja13 If you have a better looking screen dump from a viewer that properly displays the overlays, that would be great.

**Comment by anders9ustafsson** [comment]
And when I run the DCMTK application *dcm2pnm* to generate an image file, I get the following warning message four times,

> W: invalid value for 'OverlayBitPosition' (0), refers to bit position within stored pixel value

and no overlays are included in the resulting image file. Maybe the overlays are not correctly specified in the file either?

**Comment by kbpooja13** [comment]
![afterrendering](https://cloud.githubusercontent.com/assets/15139138/10539408/ff742378-741c-11e5-8e03-e6663121e78c.png)
![2](https://cloud.githubusercontent.com/assets/15139138/10539406/ff123cd0-741c-11e5-8b00-b7cd8bcff21e.png)

I have attached another sample dicom file where same i have observed. Change the file 2.png to .dcm file and check it. 

In the viewer which you used PixelMed , image shown properly but using FO-Dicom rendering as shown in the attached.

**Comment by kbpooja13** [comment]
Could you able to check the above issue

**Comment by anders9ustafsson** [comment]
@kbpooja13 Please publish your screen dump of the *PixelMed* plot, so that we get a benchmark for how you want the overlay to be displayed.

As I have previously explained, the current implementation of overlay display in *fo-dicom* is primarily adapted to displaying text and line or polygon-based overlays, so it is a very basic approach. We can of course improve on this implementation, and it **has** been placed on our backlog for a fix in a medium distant future. 

If you are in a hurry, I suggest that you try and solve the problem yourself by forking *fo-dicom* and implement your own fix. If you do fork and manage to come up with a solution, we of course appreciate it very much if you contribute back your work in the form of a pull request.

Regards,
Anders @ Cureos

**Comment by kbpooja13** [comment]
![11](https://cloud.githubusercontent.com/assets/15139138/10599328/a3f8420e-771e-11e5-8d53-f2f253a41dcc.png)

I have attached the snapshot of the image how it looks in pixelMed.

**Comment by anders9ustafsson** [comment]
As far as I can tell from this image, it does not show any overlays at all? 

If I am not mistaken, *PixelMed* adds the displayed text by default, based on data in the DICOM file. *fo-dicom* does not add this text automatically, but that is something you have to compose as part of your application.

What you would rather see in this case is thus an option to disable overlay output, since the overlay data definitely distorts the image? An overlay disabling function should be somewhat easier to add and might be doable in a nearer future.

**Comment by anders9ustafsson** [comment]
When dealing with #138 , I noticed what was causing the problems in this case also; *Overlay Bit Position* was specified to 0, although it was an embedded overlay. I have implemented a "forgiving" fallback handling for this issue in PR #140, so this issue should now be possible to consider resolved.

(There was also a problem with switched overlay rows and columns, which caused the magenta overlay to be plotted in only half of the second image. This issue has also been resolved in #140.)

**Comment by anders9ustafsson** [comment]
After further consultations in #140, I have decided to silently ignore the embedded overlay if the *Overlay Bit Position* is less than or equal to the main image *High Bit*. This will happen for the above images for example, since *Overlay Bit Position* is set to 0.
