### ISSUE TITLE
Create DCM file from JPG images using JPEG.BaseLine transfer syntax

### ISSUE THREAD

**Issue by Shivansh1291** [fo-dicom/fo-dicom#1102]
### Expected behavior

Using below code to create dicom with JPEG.Baseline transfer syntax. DCM file is created but it is corrupt and no dicom viewer is able to the file
public static void ImportImage1(string file)
        {
            Bitmap bitmap = new Bitmap(file);
            //bitmap = GetValidImage(bitmap);

            byte[] pixels = GetPixels(bitmap);
            MemoryByteBuffer buffer = new MemoryByteBuffer(pixels);
            DicomDataset dataset = new DicomDataset(DicomTransferSyntax.JPEGProcess1);
            //FillDataset(dataset);
            dataset.Add(DicomTag.PhotometricInterpretation, PhotometricInterpretation.Rgb.Value);
            dataset.Add(DicomTag.Rows, (ushort)bitmap.Height);
            dataset.Add(DicomTag.Columns, (ushort)bitmap.Width);
            dataset.Add(DicomTag.BitsAllocated, (ushort)8);
            dataset.Add(DicomTag.LossyImageCompressionMethod, "ISO_10918_1");
            dataset.Add(DicomTag.LossyImageCompression, "01");
            dataset.Add(DicomTag.SOPClassUID, "1.2.840.10008.5.1.4.1.1.2");
            dataset.Add(DicomTag.SOPInstanceUID, "1.2.840.10008.5.1.4.1.1.2.20181120090837121314");
            DicomPixelData pixelData = DicomPixelData.Create(dataset, true);
            pixelData.BitsStored = 8;
            //pixelData.BitsAllocated = 8;
            pixelData.SamplesPerPixel = 3;
            pixelData.HighBit = 7;
            pixelData.PixelRepresentation = 0;
            pixelData.PlanarConfiguration = 0;
            pixelData.AddFrame(buffer);

            DicomFile dicomfile = new DicomFile(dataset);
            dicomfile.Save(@"C:\Dicoms\Imagedicomfile.dcm");

            // SaveDicomFile2(pixels, bitmap.Height, bitmap.Width);
        }
 public static byte[] GetPixels(Bitmap bitmap)
        {
            byte[] bytes = new byte[bitmap.Width * bitmap.Height * 3];
            int wide = bitmap.Width;
            int i = 0;
            int height = bitmap.Height;
            for (int y = 0; y < height; y++)
            {
                for (int x = 0; x < wide; x++)
                {
                    var srcColor = bitmap.GetPixel(x, y);
                    //bytes[i] = (byte)(srcColor.R * .299 + srcColor.G * .587 + srcColor.B * .114);
                    bytes[i] = srcColor.R;
                    i++;
                    bytes[i] = srcColor.G;
                    i++;
                    bytes[i] = srcColor.B;
                    i++;
                }
            }
            return bytes;
        }

How can we use the transfer syntax 

1.2.840.10008.1.2.4.50 | JPEG Baseline (Process 1):

?

**Comment by kira-96** [comment]
You can change the transfer syntax after creating the dateset:

``` csharp
public static void ImportImage1(string file)
        {
            Bitmap bitmap = new Bitmap(file);
            //bitmap = GetValidImage(bitmap);

            byte[] pixels = GetPixels(bitmap);
            MemoryByteBuffer buffer = new MemoryByteBuffer(pixels);
            DicomDataset dataset = new DicomDataset(DicomTransferSyntax.ExplicitVRLittleEndian);
            //FillDataset(dataset);
            dataset.Add(DicomTag.PhotometricInterpretation, PhotometricInterpretation.Rgb.Value);
            dataset.Add(DicomTag.Rows, (ushort)bitmap.Height);
            dataset.Add(DicomTag.Columns, (ushort)bitmap.Width);
            dataset.Add(DicomTag.BitsAllocated, (ushort)8);
            //dataset.Add(DicomTag.LossyImageCompressionMethod, "ISO_10918_1");
            //dataset.Add(DicomTag.LossyImageCompression, "01");
            dataset.Add(DicomTag.SOPClassUID, "1.2.840.10008.5.1.4.1.1.2");
            dataset.Add(DicomTag.SOPInstanceUID, "1.2.840.10008.5.1.4.1.1.2.20181120090837121314");
            DicomPixelData pixelData = DicomPixelData.Create(dataset, true);
            pixelData.BitsStored = 8;
            //pixelData.BitsAllocated = 8;
            pixelData.SamplesPerPixel = 3;
            pixelData.HighBit = 7;
            pixelData.PixelRepresentation = 0;
            pixelData.PlanarConfiguration = 0;
            pixelData.AddFrame(buffer);

            DicomFile dicomfile = new DicomFile(dataset.Clone(DicomTransferSyntax.JPEGProcess1));
            dicomfile.Save(@"C:\Dicoms\Imagedicomfile.dcm");

            // SaveDicomFile2(pixels, bitmap.Height, bitmap.Width);
        }
```

**Comment by Shivansh1291** [comment]
Thanks @kira-96  it workd. Saved me a lot of trouble. Do you have any idea how it compresses the images. I had a 273kb JPG image which got converted to a 399 KB DCM files when the TR is set as JPEGProcess1. I am not sure how the DCM files is more in size than the original image.I would expect the size of the DICOM image to be size of the header (around 876 bytes) plus the size of the encapsulated DICOM image.

**Comment by kira-96** [comment]
@Shivansh1291 Maybe you can try some other compression methods, such as `JPEG2000Lossy`.

**Comment by Shivansh1291** [comment]
@kira-96 I was just asking if you know how fo-dicom is dong the conversion. I need JPEGBaseline only

**Comment by kira-96** [comment]
Sorry, I don't know how it works.

**Comment by CountJung** [comment]
read all bytes but not to use getpixels
just read all bytes raw source file. 
example

 pixels=File.ReadAllBytes(filename); 
 dataset= new DicomDataSet(DicomTransferSyntax.JPEGProcess1);  
 MemoryByteBuffer buffer = new MemoryByteBuffer(pixels);  
 pixelData.AddFrame(new CompositeByteBuffer(buffer));

**Comment by mia-san** [comment]
it depends on dataset's transfer syntax.

dataset can be
- 'compressed'(transfer syntax is JPEGBaseline, JPEGLossless, JPEG2000 or such) or
- 'uncompressed'(transfer syntax is Little Endian Explicit VR, Little Endian Implicit VR or such).

if dataset is 'compressed', PixelData should contain 'compressed' presentation, use ReadAllBytes.

otherwise, if dataset is 'uncompressed', PixelData should contain raw pixel data only, use GetPixels.
