### ISSUE TITLE
Fellow Oak DICOM crashes when association requests are received from Osirix

### ISSUE THREAD

**Issue by amoerie** [fo-dicom/fo-dicom#1103]
**Describe the bug**
When receiving an association request from the latest version of Osirix, Fellow Oak DICOM crashes. 

**To Reproduce**
Try to send a C-Store request to Fellow Oak DICOM using the latest Osirix PACS software

**Expected behavior**
The file is processed normally

**Environment**
Fellow Oak DICOM version: 4.0.6
OS: Windows 10
Platform: .NET Framework 4.8

**Comment by amoerie** [comment]
I've done a little digging, and this is what I found:

Osirix sends association requests that are encoded with ASCII. Fellow Oak DICOM will then decode this association request using UTF8. In most scenarios, this isn't a problem, since the only text in assocation request is Presentation Context UIDs, Abstract Syntax UIDs, etc, where a UID can only consist of numbers and dots. Since UTF8 is a superset of ASCII where each character under byte value 7F is the same, this doesn't cause issues when all characters are just dots or numbers.

But what if someone does send a character with a byte value higher than 7F? (Hint: this is what Osirix is doing).
According to the UTF8 rules, any character higher than 7F should use 2 bytes instead of one. 

So, when we are parsing the Abstract Syntax UID, the following code is executed:

https://github.com/fo-dicom/fo-dicom/blob/19a7cdd8d5ce6b4be45ebd34b7d8f817e3279722/DICOM/Network/PDU.cs#L651-L654

First, we read how long the UID will be, and put that in a variable called `asul`. Then, on line 654, we tell the the RawPdu to read a string with length `asul`. Let's go there and see what happens:

https://github.com/fo-dicom/fo-dicom/blob/52abdf7b1640d100c2f96db75ca721a73b83a834/FO-DICOM.Core/Network/PDU.cs#L200-L205

The _br field is initialized with a BinaryReader, which takes an "Encoding" parameter. So we are telling the BinaryReader here to read x number of characters from the stream.
This is the bug: depending on the type of encoding and the value of the bytes, BinaryReader.ReadChars can read more bytes than the provided "count" parameter.
According to the DICOM specification, the "asul" variable is how many BYTES should be read.
According to what we pass to the `BinaryReader`, the "asul" variable is how many CHARACTERS should be read. 
Luckily, when using ASCII encoding OR when using UTF8 encoding and every character is <= 7F, this works because 1 character is always 1 byte.
But, when you use UTF8 and there is a character > 7F, then an extra byte is read!

This causes the position of the memory stream to become incorrect, and somewhere down the line the whole process crashes, usually because it tries to read an Item-Length that is suddenly a very large value, and this crashes inside the CheckOffset method.

**Comment by gofal** [comment]
Great.

Just for sake of curiosity: what's that character > 7F that osirix is sending? In in which context?

**Comment by gofal** [comment]
That's definitively an issue on the osirix workstation. They do have some textfile for configurations and they copied/pasted the values there. Because this Zero-Width-Space is inserted in Editors (often after Dots) to mark that there could be a line break if the line width is too low. So this character is only used by editors for layouting reasons.

I am pretty sure other pacs system would fail reading this request, too. 

Is fo-dicom fixing this wrong value? If fo-dicom just take it and help spreading this invalid data, then I think this is not a good idea. If fo-dicom implicitly fixes it, then it is ok even if I do not like it very much.

The Osirix-guys have to fix this and they should not create invalid data.

**Comment by amoerie** [comment]
Some more details:

- we have confirmed that DCMTK can handle this request. Other pacs systems might too.

- it is true that they send invalid data. But it is only a problem in Fellow Oak Dicom because we apply the standard wrongly: an Item-Length says how many BYTES should be ready, not how many CHARACTERS. In ASCII, and in UTF-8 for characters <= 127, one character is indeed one byte. When parsing the raw PDU, we accidentally read too many bytes, which causes the memory stream position to be incorrect for further parsing.

- Osirix actually sets the Item-Length correctly, so when we apply the standard correctly, there is no issue. They just send invalid characters, and we can complain about that, but fo-dicom should not crash.

- At the moment, this pull request just makes sure that this invalid data does not cause issues. In fact, we are now correctly implementing the spec instead of making an invalid assumption.

- We could review the spec and see if we can remove any invalid characters (everything except dots and numbers) but I'm not 100% that other PACS systems will be happy if we mess around with the syntax UIDs that they sent. (The strings will not be equal)

**Comment by gofal** [comment]
You persuaded me. Specially that without this fix fo-dicom crashes. So this is a big stability improvement.
Thanks!
