### ISSUE TITLE
Date field dose not support date range

### ISSUE THREAD

**Issue by icolovic** [fo-dicom/fo-dicom#1105]
When adding date range (<dateFrom>-<dateTo>) to a date field I am getting an exception that field value is not valid for the Date VR.

In any DicomDataset add ScheduledProcedureStepStartDate tag with the value 20190101-20200101.

Field value should be accepted as valid as this is supported by the standard (http://dicom.nema.org/medical/dicom/current/output/html/part04.html#table_K.6-1) and it is used when quering Modality Worklist Servers (DicomCFindRequest). The same is true for Time fields.

Fellow Oak DICOM version: 4.0.5
OS: Windows 10 x64
Platform: .NET Framework 4.8

**Comment by ge-bus** [comment]
Hi,

Can you try by adding: `new DicomDateRange(new DateTime(2019, 1, 1), new DateTime(2020, 1, 1))` instead of the value?

**Comment by gladiatus55** [comment]
Hi, I would like to contribute to this project by implementing DA and DT validators with adequate unit tests as my first issue. Would it be okay if I start working on this issue?

**Comment by gofal** [comment]
@gladiatus55 Sure! 👍 
Just to make this visible to others, you can assign this issue to yourself.
