### ISSUE TITLE
Could we have a working video export example?

### ISSUE THREAD

**Issue by remyGrandry** [fo-dicom/fo-dicom#1108]
### Expected behavior

Hello, 

I followed the steps to export video as described here : https://github.com/fo-dicom/fo-dicom/issues/689
It actually creates a Dicom file, with a video inside.
The video format I want to insert is MPEG4 (DicomTransferSyntax.MPEG4AVCH264HighProfileLevel41)
I'm trying to see the result with Radiant Dicom Viewer.

### Actual behavior

The file is created but the video shuts immediately when I click on it

### Steps to reproduce the behavior

Using the code described in the other issue, try to open the dicom and see if the video plays or not.

### fo-dicom version and OS/platform

fo-dicom latest version (fo-dicom.Desktop 4.0.6 currently), Window 10 x64 Build 1903, .Net framework 4.7.2

**Comment by Sindhumol-S** [comment]
Hi,

In the last two days I was also in the same situation. Now it is solved!!! Working with Radiant Viewer and Microdicom

Please try this overloaded constructor  
   DicomDataset dataset = new DicomDataset(DicomTransferSyntax.MPEG4AVCH264HighProfileLevel41);

and set
dataset.AddOrUpdate(DicomTag.TransferSyntaxUID, DicomTransferSyntax.MPEG4AVCH264HighProfileLevel41.UID);
.
.
.
dicomfile.FileMetaInfo.TransferSyntax = DicomTransferSyntax.Lookup(DicomUID.MPEG4AVCH264HighProfileLevel41);

**Comment by remyGrandry** [comment]
Thanks a lot for your reply !! This is perfectly functional thanks to you.
It's a little bit weird that we have to set the same information multiple time though. 

But thanks a lot to have shared this.
