### ISSUE TITLE
Way to specify the local port to used in DicomClient?

### ISSUE THREAD

**Issue by VitMosin** [fo-dicom/fo-dicom#1109]
There is possibility for TcpClient to assign local port. As described here https://stackoverflow.com/questions/2869840/is-there-a-way-to-specify-the-local-port-to-used-in-tcpclient.

Do you have the same functionality for DicomClient?

The need is due to the fact that the server is waiting for a connection from a specific client port.

Thank you.

**Comment by amoerie** [comment]
This is currently not supported. You can work around this limitation by implementing your own NetworkManager, and taking heavy inspiration from the existing DesktopNetworkManager and DesktopNetworkStream. In DesktopNetworkStream, the TcpClient is created. That is the place where you would need to make your own custom changes.

**Comment by Amit-Joshi-Git** [comment]
Related StackOverflow post: https://stackoverflow.com/q/63992606/5779732

**Comment by Amit-Joshi-Git** [comment]
@amoerie : Can you please explain how this is newly implemented? Is there any source code available? Which class should I refer to see the changes?

**Comment by MiniGammaRay** [comment]
> @amoerie : Can you please explain how this is newly implemented? Is there any source code available? Which class should I refer to see the changes?

Did you ever get a response to this?  I cannot see how it has been fixed.
