### ISSUE TITLE
D.3.3.7 User Identity Negotiation Support

### ISSUE THREAD

**Issue by samnaction** [fo-dicom/fo-dicom#1110]
D.3.3.7 of dicom standard talks about the User Identity Negotiation. This is an optional mechanism to send/receive user credentials, a Kerberos ticket or a SAML assertion during DICOM association negotiation. This is a useful feature which provides association negotiation to perform authorization controls.

**Comment by gofal** [comment]
http://dicom.nema.org/Medical/dicom/current/output/chtml/part07/sect_D.3.3.7.html

**Comment by SyarifFakhri** [comment]
Is this still in the works? This would be a great feature to have :)
