### ISSUE TITLE
It's very slow to open deflated dicom file

### ISSUE THREAD

**Issue by pengchen0692** [fo-dicom/fo-dicom#1115]
**Describe the bug**
It takes about 5 min to open a 40MB deflated DICOM file .

The root cause is [code](https://github.com/fo-dicom/fo-dicom/blob/15258dbe7177a09c18b70be4757d25b444bcedc2/DICOM/IO/Reader/DicomReader.cs#L302) - it read whole file byte by byte.

**To Reproduce**
*   Open a 40MB deflated DICOM file

**Expected behavior**
* It should take a few seconds to complete 

**Actual behavior**
* It takes about 5 min

**Screenshots or test DICOM files**
[Deflated.zip](https://github.com/fo-dicom/fo-dicom/files/5308563/Deflated.zip)
Note: it's not a good idea to upload a 40MB file, so I attached a 4MB file as example. It takes 6 seconds to open, while after my fix, it takes only 0.3 second.

**Environment**
DICOM version: (4.0.6)
OS: ( Windows 10 x64)
Platform: (.NET Core)
CPU:  I7-8665U
MEM: 48GB

**Comment by gofal** [comment]
added the sample file into benchmark project. great improvement!
