### ISSUE TITLE
[question]FrameGeometry class, ImageToPatientSpace transformation matrix and Pixel Spacing

### ISSUE THREAD

**Issue by blazhevich** [fo-dicom/fo-dicom#1121]
Hi, my first time applying a question, sorry if doing it wrong. My question is regarding the code in the class constructor, that builds the matrix in question:

**`PixelSpacingX = pixelSpacing[0]; // this is important`**
**`PixelSpacingY = pixelSpacing[1]; // this is important`**
`...`
`ImageToPatientSpace.Column(0,`
`DirectionRow.X * PixelSpacingX, DirectionRow.Y * PixelSpacingX, DirectionRow.Z * PixelSpacingX, 0);`
`ImageToPatientSpace.Column(1,`
`DirectionColumn.X * PixelSpacingY, DirectionColumn.Y * PixelSpacingY, DirectionColumn.Z * PixelSpacingY, 0);`

[From the DICOM documentation regarding the pixel spacing](https://dicom.innolitics.com/ciods/ct-image/image-plane/00280030):
_The first value is the row spacing in mm, that is the spacing between the centers of adjacent rows, or vertical spacing._
_The second value is the column spacing in mm, that is the spacing between the centers of adjacent columns, or horizontal spacing._
![image](https://user-images.githubusercontent.com/15904125/95915235-895ddd00-0daf-11eb-9698-896ef399b9d0.png)

Shouldn't the `PixelSpacingX` and `PixelSpacingY` be switched in the two rows above according to the DICOM definition for the Pixel Spacing? And if so, I would even rename them to `PixelSpacingRow` and `PixelSpacingColumn` respectively.

Thank you!

**Comment by gofal** [comment]
Yes, you are absolutely right! Thanks for reporting this bug.
