### ISSUE TITLE
No DICOM charset found for requested encoding.

### ISSUE THREAD

**Issue by kira-96** [fo-dicom/fo-dicom#1125]
**Describe the bug**
DicomEncoding.GetCharset throw an exception when input encoding is `GB18030`. GB18030 should be a supported encoding, but not recognized in .NET Core.

**To Reproduce**
``` csharp
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
Encoding encoding = Encoding.GetEncoding("GB18030");
string charset = DicomEncoding.GetCharset(encoding);  // System.ArgumentException:“No DICOM charset found for requested encoding. ”
```

**Expected behavior**
`GetCharset` should return `"GB18030"`, but an error occurred.

**Screenshots or test DICOM files**

![图片](https://user-images.githubusercontent.com/22876709/96095984-e8cc0200-0f01-11eb-9c0a-235c4cebc8c8.png)
![图片](https://user-images.githubusercontent.com/22876709/96096181-2466cc00-0f02-11eb-86ce-0c771e41d8c7.png)

Encoding WebName is `"gb18030"` in .NET Core.

**Environment**
Fellow Oak DICOM version: 4.0.6
OS: Windows 10 x64
Platform: .NET Core 3.1

**Comment by mia-san** [comment]
it seems to me that WebName returns "GB18030" on .NET Framework, returns "gb18030" on .NET Core.
here's my test code:
```static void Main(string[] args)
{
    var encoding = Encoding.GetEncoding("GB18030");
    Console.WriteLine(encoding.WebName);
}
```

so following test fails on .NET Core.
https://github.com/fo-dicom/fo-dicom/blob/275cc8a9f2d4896c95efc26605def4c24f4033ed/DICOM/DicomEncoding.cs#L158

one easy solution would be just add
`case "gb18030": `
right next to above line.

**Comment by kira-96** [comment]
You are right. There is no problem on .Net Framework. I only modified the code of .NET Core.

**Comment by kira-96** [comment]
@gofal I have upgraded fo-dicom to 4.0.7, but the problem still remains. I realized that I had only modified the code for 5.x, should I submit a new PR for 4.x?

**Comment by gofal** [comment]
I see. I thought you had changed it only in version 5 because you are using version5. But sure, please create an other PR for version 4.
