### ISSUE TITLE
Don't always add ImplicitVRLittleEndian to DicomCStoreRequest

### ISSUE THREAD

**Issue by fr-soe** [fo-dicom/fo-dicom#1127]
**What is, according to you, missing from fo-dicom? Please describe.**
fo-dicom always add ImplicitVRLittleEndian as a transfer syntax to a DicomCStoreRequest (lines 130-133 in FO-DICOM.Core/Network/DicomPresentationContextCollection.cs). This is problematic for us.

Say we want to send an image with transfer syntax JPEG Baseline to a receiving storage SCP. fo-dicom will propose a single presentation context containing two transfer syntaxes: JPEG Baseline (the image's transfer syntax) and ImplicitVRLittleEndian (always added).

The receiving SCP (not a fo-dicom SCP) has a prioritized list of acceptable transfer syntaxes, where ImplicitVRLittleEndian is at the top. This means it will accept ImplicitVRLittleEndian before it accepts JPEG Baseline, and so the transfer will be in ImplicitVRLittleEndian, unnecessarily!

But if we disable the "always-add-little-endian" lines, fo-dicom will instead propose _two_ presentation contexts, each with a single transfer syntax: JPEG Baseline in the first presentation context, and ImplicitVRLittleEndian in the second.

This is exactly what we want!

The receiving SCP will accept both presentation contexts, and fo-dicom will then select the first presentation context (with JPEG Baseline). So the transfer will be in JPEG Baseline!

(Should the receiving SCP for any reason _not_ accept the transfer syntax in the first presentation context it will fall back to the second and ImplicitVRLittleEndian, just as expected.)

**Describe the solution you'd like**
Make it **optional** to always include ImplicitVRLittleEndian. Relegating it to a separate presentation context works much better.

**Describe possible alternatives or existing workarounds you've considered**
Our current workaround is to comment out the four lines of code described above and re-build the NuGet package.

**Comment by mia-san** [comment]
possible duplicate of #1048?

**Comment by fr-soe** [comment]
Possibly... They sound very similar indeed but looking at the commit from #1048 it contains the very lines we remove:
![image](https://user-images.githubusercontent.com/72932199/96264772-d961bd00-0fc4-11eb-87ad-033239881534.png)

**Comment by mia-san** [comment]
ah, you're right, #1048 is slightly different.
for time being, must remove 4 lines as you said, I'm afraid.
//

**Comment by gofal** [comment]
I'm affraid, issue 1048 is exactly what you want to. See here the current code:
https://github.com/fo-dicom/fo-dicom/blob/275cc8a9f2d4896c95efc26605def4c24f4033ed/FO-DICOM.Core/Network/DicomPresentationContextCollection.cs#L117-L138
In line 118 there is always a separate PresentationContext-Entry for the original transfersyntax that the file has.
And then from line 123 on there is another PresentationContext for all the additional supported Transfersyntaxes as well as the **mandatory** ImplicitLittleEndian, that every valid DICOM association must offer.

Could it be that the file you want to send is localy stored as ImplicitLittleEndian and you want to force sending in some compressed way? That would require some code change. Or you first compress the file on your harddisk, and then add the compressed file as a CStoreRequest into your DicomClients Request collection.

**Comment by fr-soe** [comment]
@gofal you are absolutely right! I must have run my tests on an earlier version of fo-dicom thinking it was the latest. 4.0.6 works out of the box and my "fix" is not neccessary. Thanks for clarifying, closing this issue.
