### ISSUE TITLE
Group 0034 tags retired spuriously

### ISSUE THREAD

**Issue by skrinakron** [fo-dicom/fo-dicom#1131]
### Expected behavior
FO-DICOM's [attribute dictionary XML](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Dictionaries/DICOM%20Dictionary.xml) has the attribute `version="2020b"`. As the [the 2020b data element registry entries for group 0034](http://dicom.nema.org/medical/dicom/2020b/output/chtml/part06/chapter_6.html#para_c0921abb-a8d2-4c1b-86bf-904b6083c464) – and the corresponding [Innolitics JSON attribute objects](innolitics/dicom-standard/blob/master/standard/attributes.json) parsed from them – are not marked retired, these attributes should not be retired in FO-DICOM.

### Actual behavior
The `tag` elements in the dictionary XML with `group="0034"` all have `retired="true"`. The DicomTag member identifiers for these tags are also appended with `RETIRED` (which seems counterproductive in general, but there's probably a good reason).

### Steps to reproduce the behavior
Attempt to use e.g. `Dicom.DicomTag.FlowIdentifier` in a program. This will fail with a compiler error because the actual identifier is `Dicom.DicomTag.FlowIdentifierRETIRED`.

### fo-dicom version and OS/platform
Version of the source currently accessible on GitHub.

**Comment by malaterre** [comment]
See note:


> The group number (0006H) of the Sequence containing the Attributes of the Current Frame Functional Groups Module is used to contain Attributes that are specific to real-time transfer. If this information needs to be kept in a persistent object, its contents have to be copied into an Attribute that has a group number of 0008H or higher.

**Comment by skrinakron** [comment]
@malaterre: I assume your comment was intended for #1132. Also, as I'm very new to DICOM in general, I'm not really able to intuit what that note means for the 0006H group's inclusion in fo-dicom. Could you perhaps elaborate on that?
