### ISSUE TITLE
Multiframe Image Receiving support

### ISSUE THREAD

**Issue by arunjoshtech** [fo-dicom/fo-dicom#1134]
Dear Team, 
Multiframe MRI images  are not received from modality. So Used conquest server. And also in general MRI image receiving need any speciall implementation??? Kindly advise how to receive multiframe images to go DICOM(as SCP)

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior (code snippet or clear description)

**Expected behavior**

**Screenshots or test DICOM files**
If applicable, add screenshots or test DICOM files to help explain your problem.

**Environment**
Fellow Oak DICOM version: (e.g. 4.0.6)
OS: (e.g. Windows 8.1 x64)
Platform: (e.g. .NET Framework 4.6.2)

**Comment by gofal** [comment]
You have to give more information about your code.
Generally spoken: every Dicom Dataset ist just a collection of DicomTags, which is just a number (group, element) and some binary stream as value. The StoreSCP receives all data and stores it. The StoreSCP does not interpret something and therefore does not make any difference between MR or EnhancedMR (the multiframe MR file). 
The difference is only when it comes to rendering or reading some metadata from the dataset.

From your minimal description I have two issues:
- when association request is done in  OnReceiveAssociationRequestAsync you have to iterate all presentation contexts and accept or reject. Maybe you are rejecting the abstranctsyntax EnhancedMR?
- These multiframe MR images are of course bigger than a mr image with only one slice. Did you check your application if it has enough memory to handle this?

For more help, please send a DICOM-log

**Comment by gofal** [comment]
I will close this due to inactivity. If the issue still occurs please don't hesitate to reopen this issue and give more information.
