### ISSUE TITLE
Need a Class Like FrameGeometry For 2D Data(CR,MG) to Calculate Distance between two points

### ISSUE THREAD

**Issue by rmrudro** [fo-dicom/fo-dicom#1138]
Dear Team,
As I discussed in gitter.im  @gofal  suggested to create an issue . The problem is in FrameGeometry  class. we can calculate two points using this class . But that only for 3D object like CT, MR etc . Other Dicom file Image like CR,MG etc 2D data  if we want to calculate distance we get exception "var geometry = new FrameGeometry(DicomDataSet);" Dicom.DicomDataException:Tag(0020,0052) not found in Dataset at Dicom.DicomDataset.ValidateDicomTag." 

Here was my code actually @gofal helped me to create this I'm very grateful to him.

Here is the code 

                System.Windows.Point px1 = e.GetPosition((System.Windows.Controls.Image)sender);
                _firstPoint = px1;
                System.Windows.Point px2 = e.GetPosition((System.Windows.Controls.Image)sender);
                _secondPoint = px2;
                var geometry = new FrameGeometry(DicomDataSet);
                var patientCoord1 = geometry.TransformImagePointToPatient(new Point2(Convert.ToInt32(_firstPoint.X), 
                Convert.ToInt32(_firstPoint.Y)));
                var patientCoord2 = geometry.TransformImagePointToPatient(new Point2(Convert.ToInt32(_secondPoint.X), 
                Convert.ToInt32(_secondPoint.Y)));
                double distanceInMM = patientCoord1.Distance(patientCoord2);

Here The FrameGeometry class I got the exception . @gofal  also told me "So this class may lack of CR or MG support" . So I think if you guys fix this and if you implement another class that support 2D data it will be helpful for me . That will be very kind of you

Environment :
wpf .NETFramework  Version 4.8

**Describe possible alternatives or existing workarounds you've considered**
A clear and concise description of any alternative solutions or existing workarounds you've considered.
``

**Comment by kira-96** [comment]
Hi!  
It seems that `FrameOfReferenceUid` is only used here.  
https://github.com/fo-dicom/fo-dicom/blob/499b409e9bbc6bf0d5b19e31dbc0aada5cd96011/DICOM/Imaging/FrameGeometry.cs#L164-L166
It ensures that both frames use the same `FrameOfReferenceUid` when calculating the localizer.  
In my opinion, it is not a very **required** property in `FrameGeometry`.
https://github.com/fo-dicom/fo-dicom/blob/499b409e9bbc6bf0d5b19e31dbc0aada5cd96011/DICOM/Imaging/FrameGeometry.cs#L53-L54
So, can we change its constructor like this?
``` csharp
public FrameGeometry(DicomDataset image)
    : this(image.GetSingleValueOrDefault(DicomTag.FrameOfReferenceUID, string.Empty),
```

**Comment by rmrudro** [comment]
@gofal  I hope it works now what do you say

**Comment by gofal** [comment]
that is an important step, but not enough. 
for example CR images do not have PatientPosition or PatientImageOrientation values. And pixel spacing may be in different tags, like (0018,1050) Spatial Resolution or others.
I am working on this now.

**Comment by gofal** [comment]
Previously the constructor of FrameGeometry only worked fine if all the necessary geometry data was given in DicomDataset. Now that meassuring should also work in other images, I had to change this.

FrameGeometry now accepts every DicomDataset and reads information that is available. Now you have to check yourself if geometry data was available. There are 2 new properties `GeometryType` which is either "None" (there is no geometry data at all), "Plane" (pixel spacing is given, so distance measuring is available, but no other volume data) or "Volume" (all 3d data is present, so localizer-calculation could be done). And the other `HasGeometryData` returns if GeometryType is Plane or Volume.

 In case of GeometryType Plane (a CR image) all the z-values are 0 all the time.
