### ISSUE TITLE
Parallel image creation

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#114]
*Excerpt from Google Groups question, reported by Yonatan Yaakovian, October 20, 2015:*

I've tried to create multiple DicomDataset using Microsoft's parallel class in order to accelerate export but I got this exception:
"System.ArgumentException: An item with the same key has already been added."   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at DicomFellowOak.DicomDictionary.GetPrivateCreator(String creator).
after some research with a college we decided to add a lock on the code block that adds private keys so only one thread will be allowed to add private keys at a given time in order to eliminate possible racing conditions in GetPrivateCreator.
this worked for the last two months but now I get these same exceptions again.

**Comment by anders9ustafsson** [comment]
Thanks for reporting, Yonatan. Could you please provide a code snippet showing the failing code. Please also specify which *fo-dicom* version you are running.

**Comment by IanYates** [comment]
Refer to https://msdn.microsoft.com/en-us/library/xfhwa508.aspx#Anchor_10

We can improve quite a few things in DicomDictionary.cs in this regard.  Using Lazy<T> to handle the initialisation of the static dictionaries for one, and perhaps using either concurrent dictionaries or at least a lock around the reading and writing of dictionaries will go a long way towards tightening this up.

I'm pretty sure PCLs support Lazy and ConcurrentDictionary.  I'll put together a PR.

**Comment by anders9ustafsson** [comment]
@IanYates Many thanks for looking into this. If I am not mistaken, `ConcurrentDictionary` is an available alternative in the PCL profile (111) we are using, if you want to take that route.

Just to make you aware, I am currently preparing a PR related to #107. In the end, it has become a complete overhaul of the `DicomService` class to make it run more sequentially. The PR primarily contains file modifications (only two file deletions if I remember correctly), so it should not interfere to much with other PR mergers. I hope to finish my PR later today.

**Comment by IanYates** [comment]
I just made the PR - it just touches the one file and only in a few areas.  The most time was actually just spent reasoning about the various pathways and interplay between the dictionaries to make sure we didn't need to have a broader lock covering access across the private collections rather than treating each one separately.
