### ISSUE TITLE
Validation of VR type DS doesn't allow for leading and trailing spaces.

### ISSUE THREAD

**Issue by EthicsGradient** [fo-dicom/fo-dicom#1141]
**Describe the bug**
Dicom tags with VR type DS fail to validate if they contain leading or trailing spaces. This is against the standard. http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html

**To Reproduce**
Place value " -1024" in a Dicom tag of type DS Decimal String

**Expected behavior**
It should validate correctly, if the value without leading or trailing space is valid.

**Screenshots or test DICOM files**
Unable to supply due to data protection.

**Environment**
Fellow Oak DICOM version: fo-dicom.NetCore 4.07
OS: CentOS7
Platform: .Net Core Version:   2.2.300  Commit:    73efd5bd87

**Comment by gofal** [comment]
fixed in pullrequest #1142
