### ISSUE TITLE
How to  implementation dicomClient pool

### ISSUE THREAD

**Issue by cocosip** [fo-dicom/fo-dicom#1143]
When we not use `HttpClient` not as a singleton,  it will caught TCP socket port exhaustion.
Will `DicomClient`  meet the same problem?Should we create a client pool to reuse the tcp connection?
When i try to write a pool 
```c#
var pool=new DicomClientPool();
var dicomClient= pool.Rent();
...
pool.Return(dicomClient);
```
but, i found i can‘t get some connection state in `DicomClient`, How do I create a client connection pool?
Thank you!

**Comment by gofal** [comment]
No, I do not see any reason for having a DicomClient pool. The only reason for having a HttpClient pool is, because HttpClient is implemented in a very special way. For optimization reasons it does not completely disponse on disposing, but keeps some resources open and is a shared object under the hood.
DicomClient has no such internal shared object. A TcpClient instance is used internally and disposed as soon as DicomClient is disposed.

What was the reason for your question? Did you observe some issue with open ports or open connections? Maybe you found a bug that under certain circumstances fo-dicom does not dispose correctly?

**Comment by cocosip** [comment]
> No, I do not see any reason for having a DicomClient pool. The only reason for having a HttpClient pool is, because HttpClient is implemented in a very special way. For optimization reasons it does not completely disponse on disposing, but keeps some resources open and is a shared object under the hood.
> DicomClient has no such internal shared object. A TcpClient instance is used internally and disposed as soon as DicomClient is disposed.
> 
> What was the reason for your question? Did you observe some issue with open ports or open connections? Maybe you found a bug that under certain circumstances fo-dicom does not dispose correctly?

In our business, qr scu was run on  a http server side.
When client send a http request (input studyUid , seriesUid, sopInstanceUid), we try to qr dicom with image level.
So , if we don‘t  have a connection pool ,the TCP connection port will running out.

**Comment by amoerie** [comment]
@cocosip I'm late to the party, but better late than never. We have a proprietary DicomClient pooling setup like you described, I can give you a quick rundown on how it works:

- Create a pool per type of request (C-FIND, C-STORE, ...)
- Create n DicomClients per pool and add all possible transfer syntax UIDs (via AdditionalPresentationContexts)

Now you have an idle pool. When sending a request, do the following:

- Take a DicomClient from the correct pool. You don't need to "extract and return it", DicomClient itself is threadsafe
- Add your request to this DicomClient. If this is the first request, you will need to call SendAsync. If this DicomClient is already actively sending, it will automatically be enqueued for sending on the current association. The "associationLingerTimeout" parameter is very handy in this scenario.
- Code would look something like this: `if(DicomClient.IsSendRequired) DicomClient.SendAsync()`

Each DicomClient.SendAsync takes a cancellation token. You will be expected to keep these tokens around so you can properly stop & shutdown your DicomClient pool

**Comment by amoerie** [comment]
Closing this since the issue is inactive and the question is answered.
