### ISSUE TITLE
IOException when writing DICOM encapsulated transfer syntax with file size > 2GB

### ISSUE THREAD

**Issue by Andreas-Kl** [fo-dicom/fo-dicom#1148]
### Expected behavior
DICOM encapsulated transfersyntax MPEG4AVCH264HighProfileLevel41 can be stored with encapsulated Video file size of up to
~4GB (maximum fragment size)

### Actual behavior

Gives the following exception during DICOM Write operation with given video size > 2GB:

   at Dicom.DicomDatasetWalker.DoWalk(IDicomDatasetWalker walker, Queue`1 items)
   at Dicom.DicomDatasetWalker.Walk(IDicomDatasetWalker walker)
   at Dicom.IO.Writer.DicomFileWriter.WalkDataset(IByteTarget target, DicomTransferSyntax syntax, DicomDataset dataset, DicomWriteOptions options)
   at Dicom.IO.Writer.DicomFileWriter.WriteDataset(IByteTarget target, DicomTransferSyntax syntax, DicomDataset dataset, DicomWriteOptions options)
   at Dicom.IO.Writer.DicomFileWriter.Write(IByteTarget target, DicomFileMetaInformation fileMetaInfo, DicomDataset dataset)
   at Dicom.DicomFile.Save(String fileName, DicomWriteOptions options)

Exception: An attempt was made to move the file pointer before the beginning of the file.

### Steps to reproduce the behavior

Following code was used:

            string mp4 = "vid.mp4";
            string dcmOut = "out.dcm";

            int numFrames = 1234;
            int rows = 1024;
            int columns = 720;

            DicomDataset dataset = new DicomDataset(DicomTransferSyntax.MPEG4AVCH264HighProfileLevel41);
            dataset.AddOrUpdate(DicomTag.TransferSyntaxUID, DicomTransferSyntax.MPEG4AVCH264HighProfileLevel41);

            dataset.Add(DicomTag.PhotometricInterpretation, PhotometricInterpretation.Rgb.Value);
            dataset.Add(DicomTag.BitsAllocated, (ushort) 8);
            dataset.Add(DicomTag.BitsStored, (ushort) 8);
            dataset.Add(DicomTag.HighBit, (ushort) 7);

            dataset.Add(DicomTag.Rows, (ushort) rows);
            dataset.Add(DicomTag.Columns, (ushort) columns);
            dataset.Add(DicomTag.SOPClassUID, DicomUID.VideoEndoscopicImageStorage);
            dataset.Add(DicomTag.SOPInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID());

            DicomPixelData pixelData = DicomPixelData.Create(dataset, true);
            var finfo = new FileInfo(mp4);       
            var buffer = new FileByteBuffer(new Dicom.IO.DesktopFileReference(mp4), 0, (uint)finfo.Length);

            pixelData.AddFrame(buffer);
            DicomFile dicomfile = new DicomFile(dataset);

            dicomfile.FileMetaInfo.TransferSyntax = DicomTransferSyntax.Lookup(DicomUID.MPEG4AVCH264HighProfileLevel41);
            dicomfile.Save(dcmOut);

### fo-dicom version and OS/platform

Windows, .NET Core, 4.0.7

**Comment by Andreas-Kl** [comment]
Looks like there is at least an integer overflow issue in DicomWriter:

        private static void WriteBuffer(IByteTarget target, IByteBuffer buffer, uint largeObjectSize)
        {
            var offset = 0;
            var remainingSize = buffer.Size;

            while (remainingSize > largeObjectSize)
            {
                var range = buffer.GetByteRange(offset, (int)largeObjectSize);
                target.Write(range, 0, largeObjectSize);

                offset += (int)largeObjectSize;
                remainingSize -= largeObjectSize;
            }

            target.Write(buffer.GetByteRange(offset, (int)remainingSize), 0, (uint)remainingSize);
        }

using uint for offset 'seems' to fix the issue

**Comment by gofal** [comment]
I already did some rework to use `long` instead if `int` whereever possible when it comes to writing with buffers. Using `uing` instead of `int` also may give some more size. 
You have to be careful in version 4 because the same code has to build for several platforms like netframework, netcore, mono, unite etc. Some of them require `int`. I will take a look at it.

But if you try using version 5, which is only built in netstandard2.0, then there are more possiblilities today.

**Comment by Andreas-Kl** [comment]
Thanks for the reply, I have already thought that this is possibly only half the solution, but still wanted to share.
Thanks for working on this, FO-DICOM has really become a great library !

**Comment by gofal** [comment]
just for curiosity: would upgrading to version 5 be an option for you? It's still in beta not because the code is instable or so. There are no known bugs. But we are evaluating if we should change the API of DicomClient and therefore I am awaiting this. 
This are the changes when upgrading: https://github.com/fo-dicom/fo-dicom/wiki/Upgrade-from-version-4-to-version-5
 It would be much more easy if I would only fix this int/uint in version 5.

**Comment by Andreas-Kl** [comment]
Hello Reinhard, sorry for the late reply we have found a temporary solution and have thereby gained some time, version 5 will be totally fine. Thanks for picking up on this !

**Comment by CountJung** [comment]
please Fix offset to long in Method WriteBuffer

private static void WriteBuffer(IByteTarget target, IByteBuffer buffer, uint largeObjectSize)
    {
        **long** offset = 0;
        var remainingSize = buffer.Size;

        while (remainingSize > largeObjectSize)
        {
            var range = buffer.GetByteRange(offset, (int)largeObjectSize);
            target.Write(range, 0, largeObjectSize);

            offset += (int)largeObjectSize;
            remainingSize -= largeObjectSize;
        }

        target.Write(buffer.GetByteRange(offset, (int)remainingSize), 0, (uint)remainingSize);
    }

When I trying to Save Higher then 2GB, offset will be Overflowed because offset is treated as int 
fix offset variable type to long is OK
