### ISSUE TITLE
RawImage class should be available on all platform

### ISSUE THREAD

**Issue by nguyenvuduc** [fo-dicom/fo-dicom#1149]
**Describe the bug**
Exception JNI DETECTED ERROR IN APPLICATION: JNI NewString called with pending exception android.runtime.JavaProxyThrowable: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeLoadException: Could not resolve type with token 0100003b from typeref (expected class 'Dicom.Imaging.RawImage' in assembly 'Dicom.Core, Version=4.0.2.0, Culture=neutral, PublicKeyToken=3a13f649e28eb09a')

when uses RawImage class in a Shared library of Xamarin project.

**To Reproduce**
Create a Xamarin project that have Shared library uses RawImage class. Then run the Android Xamarin project.

**Expected behavior**
This exception shouldn't be occurred. It seems the RawImage and RawImageManager class don't exist in fo-dicom.Android nuget package

**Environment**
Fellow Oak DICOM version: 4.0.2
OS: Android
Platform: Android

**Comment by gofal** [comment]
Yes. `IImage` is an interfac in dicom.core and then there are different implementations in the different builds. In android library there is `AndroidImage` and so on. netcore does not have a imaging class on its own (you can introduce system.drawing that depends on gdi and windows, but thats a workaround?) and so there is `RawImage` where you only have pixel data.

So it was kind of desired that RawImage is not part of the core dll.

I would suggest 2 solutions: 
- if it's possible, then try upgrading to version 5. There are some breaking changes (https://github.com/fo-dicom/fo-dicom/wiki/Upgrade-from-version-4-to-version-5) but there you have RawImage included in core library.
- or you copy the `RawImage` class from github into your project and call `ImageManager.SetImplementation(new MyRawImageManager())` to use RawImage in your project.

**Comment by gofal** [comment]
did one of the suggestions work for you?

**Comment by nguyenvuduc** [comment]
Yes, it works. I copied the RawImage class to my cross platform project and call ImageManager.SetImplement. Thank @gofal.
