### ISSUE TITLE
The color of the converted image is not displayed correctly

### ISSUE THREAD

**Issue by wjm23714** [fo-dicom/fo-dicom#1150]
view：
![image](https://user-images.githubusercontent.com/39718496/106249034-c52c8d80-624c-11eb-8bac-8eddc4ee3065.png)
expect view:
![image](https://user-images.githubusercontent.com/39718496/106249359-3e2be500-624d-11eb-8141-38aececeaf03.png)

**Comment by gofal** [comment]
I'm affraid I need more help. So I assume this are not images in pixel data because not only color, but also content is different. You are using some Overlay annotations? Can you give some code that you are using, or can you upload a anonymized sample dicom file?

**Comment by wjm23714** [comment]
> I'm affraid I need more help. So I assume this are not images in pixel data because not only color, but also content is different. You are using some Overlay annotations? Can you give some code that you are using, or can you upload a anonymized sample dicom file?

yes i am using some Overlay annotations。How to change the color？

**Comment by gofal** [comment]
The `DicomImage` instance has a property `OverlayColor` of type int. Change this value before calling `.RenderImage()`.
Default is FFFF00FF, which is magenta. You can set it to an other color easly by setting the int-value or by setting via System.Drawing.Color.XXX.ToArgb()
