### ISSUE TITLE
Delimeter (fffe,e0dd) instead of delimeter (fffe,e00d)

### ISSUE THREAD

**Issue by timetogo2** [fo-dicom/fo-dicom#1157]
**Describe the bug**
We encounter some ultrasound dicom clips that incorrectly terminate a sequence.  I think the last item in the sequence is missing the end of item marker and instead has the end of sequence marker.  Matlab and most dicom viewers seem to handle this condition.  Here is the traceback I get from FO on the open:
2/18/2021 3:17:44 PM Failed file D:\DataStore\TEE\JHM\DIRW0000.dcm: Dicom.DicomFileException: Input string was not in a correct format. ---> System.FormatException: Input string was not in a correct format.
   at System.Text.StringBuilder.FormatError()
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Dicom.DicomFile.Open(String fileName, Encoding fallbackEncoding, Func`2 stop, FileReadOption readOption) in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\DicomFile.cs:line 243
   --- End of inner exception stack trace ---
   at Dicom.DicomFile.Open(String fileName, Encoding fallbackEncoding, Func`2 stop, FileReadOption readOption) in C:\dev\GitHub\fo-dicom\fo-dicom\DICOM\DicomFile.cs:line 260
   at FODicom.FODicom.ProcessFolderForDicomFiles(String folder) in C:\Users\elarson\source\repos\FODicom\FODicom.cs:line 50

This does seem similar to another issue posted previously, but I feel this one can be handled with confidence that the data will be read as intended and that the provider simply encoded the "end of item / end of sequence" improperly.  Maybe an option to select less strict adherence would allow the caller to decide if they want to allow small known non-conformances?  Strict conformance would be the default to make those that require it to be happy.  Just thinking out loud here...

**To Reproduce**
This is the output using dcmdump:
dcmdump.exe D:\DataStore\VALIDATION-SET\ACUSON-SEQUOIA-9.51\DIRW0007
E: DcmItem: Parse error in sequence item, found (fffe,e0dd) instead of item delimiter (fffe,e00d)
E: dcmdump: Item Delimitation Item missing: reading file: D:\DataStore\VALIDATION-SET\ACUSON-SEQUOIA-9.51\DIRW0007

**Expected behavior**
I think handling the exception and retrying with the end of sequence marker is a viable option and is likely what others have done.

**Screenshots or test DICOM files**

[DIRW0007.zip](https://github.com/fo-dicom/fo-dicom/files/6010451/DIRW0007.zip)

**Environment**
Fellow Oak DICOM version: FO-Desktop 4.0.7
OS: Windows 10
Platform: .Net 4.7.2

**Comment by timetogo2** [comment]
It is being opened with FileReadOption.ReadLargeOnDemand if that matters.

**Comment by gofal** [comment]
Fo-dicom already handles to implicitly end an Item when a SequenceDelimiter appears without a explicit ItemDelimiter.

I've debugged the file. It is not that the SequenceDelimiterItem is in the wrong order. The pixeldata tag is with undefined Length FFFFFFFF and therefore requires the SequenceDelimterItem at the end to mark the end of the pixeldata. This SequenceDelimiterItem then finally appears close to the end of the file. But then there is a second SequenceDelimiterItem, which is just wrong. The parser there expects a DicomTag. A change has to be done very carefully. because sometimes two SequenceDelimiterItems are correct if you have nested sequences of undefined length. I will think about how to handle this file savely without breaking the parser process.

**Comment by timetogo2** [comment]
Thank you so much for considering a possible fix.  As you have already figured out, I was kind of winging it with my description of the problem.  The part about others handling this case is true though:-)  Again, thank you.

**Comment by gofal** [comment]
some research surprised me. none of my validation tools complained about the last extra SequenceDelimiterItem. Seems like it some relict of prior versions in DICOM. a dataset may be finally closed with a last SequenceDelimiterItem.
