### ISSUE TITLE
There are two DICOM images generated jpg images are black

### ISSUE THREAD

**Issue by JiangWeian** [fo-dicom/fo-dicom#1158]
The DICOM images are:
[DICOM.zip](https://github.com/fo-dicom/fo-dicom/files/6033562/DICOM.zip)

Display in viewer is normal:
![TIM图片20210223180747](https://user-images.githubusercontent.com/56569509/108951894-bc8c7300-76a3-11eb-812e-e66c5ae85793.png)

In the code I call is :
public static bool WriteTo(fo.DicomDataset dicomObject, int frame, string fileName)
{
var frameIndex = frame - 1;
var dicomImage = new DicomImage(dicomObject, frameIndex);

            string directory = Path.GetDirectoryName(fileName);
            if(!Directory.Exists(directory))
            {
                Directory.CreateDirectory(directory);
            }

            using (var bitmap = dicomImage.RenderImage(frameIndex).AsBitmap())
            using (FileStream stream = File.Open(fileName, FileMode.CreateNew))
            {
                bitmap.Save(stream, System.Drawing.Imaging.ImageFormat.Jpeg);
                //   stream.Position = 0;
                stream.Flush();
                stream.Close();
            }

        return success;
    }

Environment
foDICOM version: 3.0.2.1
OS: Windows 7 64bit
Platform: .Net 4.5.2

**Comment by gofal** [comment]
I tried to render the files with latest version fo-dicom 4.0.7 as well as with new fo-dicom 5.0.0-alpha. on both the rendered image look fine like that:

![image](https://user-images.githubusercontent.com/6769246/108963290-327be480-767a-11eb-82e1-b8aa75b8e5bd.png)

There seems to be a bug vin version 3.0.2 that is already fixed in latest version. Please update fo-dicom and retry.

**Comment by JiangWeian** [comment]
@gofal , I tested it, too. There is no such problem of fo-dicom 4.0.7.
But some code cannot downward compatible:
![TIM图片20210224163411](https://user-images.githubusercontent.com/56569509/108972320-244fb780-76be-11eb-9b43-178abdc4b257.png)

The invocation of these two methods produces ambiguity:
        public DicomDataset Add<T>(DicomTag tag, params T[] values);
        public DicomDataset Add<T>(DicomTag tag, Encoding encoding, params T[] values);

How to solve it?

**Comment by gofal** [comment]
If I want to add Tags with empty values, I usually call `dataset.Add(DicomTag.XXX, string.empty);`. Because an empty string will be converted to a empty value, depending on the Value Representation of the Dicom Tag.

**Comment by gofal** [comment]
otherwise `studyDs.Add(fo.DicomTag.XX, (object)null)` should do the same als previous?

**Comment by JiangWeian** [comment]
@gofal , OK, thank you!
