### ISSUE TITLE
JSON Deserialization fails if VR = IS and the JSON has the tag encoded as a string instead of a number

### ISSUE THREAD

**Issue by BobSter3000** [fo-dicom/fo-dicom#1161]
### Expected behavior
Change in DICOM Standard
PS3.18 F.2.3.1
http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_F.2.3.html
now has the following VR's listed as either number or string, where previously they were just number
DS, IS, SV, UV

I did actually encounter this in a qido-rs response.

### Actual behavior
Malformed DICOM json exception in v4.07
Malformed DICOM json, number expected exception in v5.0  

### Steps to reproduce the behavior

var json = @"[{ ""00201206"":{""vr"":""IS"",""Value"":[""311""]}}]";

// v4
var ds = JsonConvert.DeserializeObject<DicomDataset[]>(json, new JsonDicomConverter());
 
// v5
 var datatset = DicomJson.ConvertJsonToDicomArray(json);

### fo-dicom version and OS/platform
v 4.07 Desktop and v5.0

**Comment by gofal** [comment]
handling strings as value is implemented in version 5. Unittests work fine. Can you give it a try in real-world?

**Comment by BobSter3000** [comment]
@gofal Sorry it took so long to reply.  Yes, I verified this is fixed in version 5,  with the same device that was failing before.  Thank you very much.
