### ISSUE TITLE
Error showing image 

### ISSUE THREAD

**Issue by maikel87** [fo-dicom/fo-dicom#1166]
[filedcm.zip](https://github.com/fo-dicom/fo-dicom/files/6222731/filedcm.zip)

### Actual behavior
If you load a dicom image that have a Element VOI LUT Sequence (0028,3010), but this field it is empty, when you try Render Image fo-dicom throw an exception

### Steps to reproduce the behavior
1- Load a dicom file, that have a VOI LUT Sequence empty.
2- Call the method RenderImage of DicomImage or change the property UseVOILUT to false

### fo-dicom version and OS/platform
fo-dicom version 4.0.7

**Comment by gofal** [comment]
It seems, the file is corrupt. I tried several free and comercial viewers. None of them rendered this image.
It is fine that fo-dicom throws an exception when trying to render an corrupt dicom image file.
