### ISSUE TITLE
fo-dicom.Android v4.0.7 is not available

### ISSUE THREAD

**Issue by nguyenvuduc** [fo-dicom/fo-dicom#1167]
**Describe the bug**
I can't add fo-dicom reference in to my Xamarin's Android project. Nuget said:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1102	Unable to find package fo-dicom.Android with version (>= 4.0.7)
  - Found 16 version(s) in nuget.org [ Nearest version: 4.0.2 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Package
```

**To Reproduce**
Create a Xamarin Forms project. Add fo-dicom reference to the Android project

**Environment**
Fellow Oak DICOM version: 4.0.7
Visual Studio 2019
OS: Windows
Platform: Xamarin Android

**Comment by gofal** [comment]
Please consider using version 5. This is completely built in netstandard and therefore does not require platform specific packages like fo-dicom.android, fo-dicom.ios or so any more. See here for details about upgrading your code from version 4 to version 5: https://github.com/fo-dicom/fo-dicom/wiki/Upgrade-from-version-4-to-version-5

**Comment by nguyenvuduc** [comment]
Thank @gofal, it is awesome. I will close this issue.
