### ISSUE TITLE
Adding private tags behaves differently for different transfer syntax

### ISSUE THREAD

**Issue by erlaxmikantha** [fo-dicom/fo-dicom#1170]
**Describe the bug**
Adding a private tag with LT or UT as VR type is getting added UN if the dataset is having transfer syntax Implicit VR Little Endian 

**To Reproduce**
Following snippet behaves differently for Implicit VR Little Endian and Explicit VR Little Endian
```
private static DicomFile AddSnapshotPrivateTag1(DicomFile dicomFile)
{
        string snapshotData = "test snapshotData ";
        dicomFile.Dataset.Add<string>(DicomVR.LT, new DicomTag(0x0031, 0x01, "My Creator"), snapshotData);
        return dicomFile;
}
```
For Implicit VR Little Endian dataset, it added as binary value with VR as UN.
For Explicit VR Little Endian dataset, it added as string and VR as LT.

**Expected behavior**
Irrespective of the transfer syntax of the dataset, it should add private tag as string because VR type mentioned while adding tag is LT.

**Screenshots or test DICOM files**
For Explicit VR Little Endian dataset,

![image](https://user-images.githubusercontent.com/28131649/114847815-be4cfa00-9dfb-11eb-82f4-eed9ed538d8a.png)

For Implicit VR Little Endian dataset

![image](https://user-images.githubusercontent.com/28131649/114847971-e177a980-9dfb-11eb-8389-28dfbe99d268.png)

**Environment**
Fellow Oak DICOM version: 4.0.7
OS: Windows 10 Version 1909
Platform: .NET Framework 4.7.2

**Comment by kira-96** [comment]
> The Data Elements contained in the Data Set structure shall be encoded with Implicit VR (without a VR Field) as specified in Section 7.1.3.

See http://dicom.nema.org/medical/dicom/current/output/chtml/part05/chapter_A.html
Since VR type is not explicitly specified, the VR type of private tag is converted to UN.

**Comment by gofal** [comment]
to be niggling: the VR is not "converted" to UN. When writing the dataset, fo-dicom serializes the content into the 18 bytes of data. In case of Explicit transfer syntax, it also adds the VR.
Then when some application reads the dataset, the 18 bytes content are read. In case of explicit transfer syntax the reader also knows that the VR is a text and converts the bytes into a string. In case of implicit transfer syntax the reader does not know how to interpret this and writes "UNknown".
