### ISSUE TITLE
RetrieveURL

### ISSUE THREAD

**Issue by mradosovic** [fo-dicom/fo-dicom#1177]
I have a problem reading DicomTag.RetrieveUrl on a client.
I'm using Weasis to search local DICOM server and it works fine, but to be able to do WADO import after search is done, Weasis probably needs RetrieveURL to exist in the DataSet.
Although the value is added to a DataSet, when I check it with WireShark, it's value is unknown.
I have tried to force VR type like this:
resultDataSet.AddOrUpdate(DicomVR.UT, DicomTag.RetrieveURL, $"http://cite.com/api/studies/{study.StudyInstanceUID}");

Can anyone help with a suggestion or similar experience?

**Comment by gofal** [comment]
I have no experience with Weasis, but I try to understand your issue:
- You have built a DICOM server and run a classic QueryRetrieve Server
- the weasis client does a query and you add the retireveURL to every item in your result
- you checked with WireShark and the retrieveUrl value is added to the dataset correctly
- but for any reason Weasis does not go further and does not query the images via WADO.
Did I get you right?

**Comment by mradosovic** [comment]
Thank you very much for a reply! 
You got everything right except the third, when I check with WireShark the value of RetrieveUrl is 'unknown'.

**Comment by gofal** [comment]
ok, that is weird. I would recommend to activate full dicom logging (your DicomServer has a property `Options` of type `DicomServiceOptions`, there you set the bool property  `LogDimseDatasets` to `true`). This will write all your DICOM data into the log before serializing into the network. So you will see if the retrieveurl gets lost within your Query-handler in logic (then this log already shows an empty/unknown retrieveurl) or if the value gets lost when sending via network (then the retrieveurl has the right value).

One thing I notice now, is that you add it with VR UT (Unlimited Text), but the DicomTag retrieveUrl is defined as VR UR (Universal Resource identifier or locator). Please also try to fix that.

**Comment by mradosovic** [comment]
Actually, I've was doing it with just a simple way as for any other tag like: AddOrUpdate(DicomTag.RetrieveURI, "someUrl");
VR UT was just to mimic a solution I've found for some other DCOM package.
I'm gonna try with the full logging as you suggested.

**Comment by mradosovic** [comment]
Sorry, there is no issue with RetrieveUrl. What i've found now is that everything works fine, Weasis is getting RetrieveUrl value.
The problem that confused me was that Weasis was showing me an old study, not the one I downloaded at the moment. For some reason, until I manually remove the study, restart Weasis and then do C-Get again, it's showing me an old study. 
Thank you very much for the help!
