### ISSUE TITLE
Saving bool type in a tag

### ISSUE THREAD

**Issue by icolovic** [fo-dicom/fo-dicom#1178]
Sometimes it is required that an on/off flag is saved in the DICOM file as a tag. The best type for this is bool (boolean). Searching for the solution online, I concluded that the best VR for this is Code String (CS). Currently, I am getting an exception (System.InvalidOperationException: Unable to create DICOM element of type CS with values of type System.Boolean) when trying to save a tag with boolean as a value.

I have looked into the code and found that this is correctly handled for the enums. But it is not handled for the bool.
It would be nice if fo-dicom did this automatically. 

There is a solution, to convert the bool to string when adding a tag.

**Comment by icolovic** [comment]
I am using exactly what you have suggested, Code String with TRUE and FALSE. 
Why I suggested is that I have looked into the code and found that enums are handled in the same way,
And enums can be saved as numbers and as strings, the same way as a bool.

**Comment by mrbean-bremen** [comment]
DICOM has the concept of enumerated values (a list of values allowed for a tag in a specific SOP class), but no explicit concept of Booleans. At least for me, the current behavior is what I would expect, while an implicit Boolean conversion would be ambiguous in DICOM (could be represented by TRUE/FALSE, YES/NO or some other enumerated values).
