### ISSUE TITLE
Problem sending siemens resonance prints stopping printing on the equipment.

### ISSUE THREAD

**Issue by andersoncav** [fo-dicom/fo-dicom#1179]
Good morning, I am using the version fo-dicom print scp 4.04 and when I send impressions of the siemens resonance this is showing the error below and stopping the printing on the equipment.
Please, has anyone had this problem and can help me?

[INFO] MSTZ400D <- Association request:
Calling AE Title:          MSTZ400D
Called AE Title:           Magic
Remote host:               10.200.3.2
Remote port:               59716
Implementation Class:      Implementation Class UID [1.3.12.2.1107.5.2]
Implementation Version:    MR_VD14A
Maximum PDU Length:        262144
Async Ops Invoked:         1
Async Ops Performed:       1
Presentation Contexts:     4
  Presentation Context:     1 [Proposed]
       Abstract Syntax:     Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:     Explicit VR Little Endian
       Transfer Syntax:     Implicit VR Little Endian: Default Transfer Syntax for DICOM
       Transfer Syntax:     Explicit VR Big Endian (Retired)
  Presentation Context:     3 [Proposed]
       Abstract Syntax:     Print Job SOP Class
       Transfer Syntax:     Explicit VR Little Endian
       Transfer Syntax:     Implicit VR Little Endian: Default Transfer Syntax for DICOM
       Transfer Syntax:     Explicit VR Big Endian (Retired)
  Presentation Context:     5 [Proposed]
       Abstract Syntax:     Basic Color Print Management Meta SOP Class
       Transfer Syntax:     Explicit VR Little Endian
       Transfer Syntax:     Implicit VR Little Endian: Default Transfer Syntax for DICOM
       Transfer Syntax:     Explicit VR Big Endian (Retired)
  Presentation Context:     7 [Proposed]
       Abstract Syntax:     Presentation LUT SOP Class
       Transfer Syntax:     Explicit VR Little Endian
       Transfer Syntax:     Implicit VR Little Endian: Default Transfer Syntax for DICOM
       Transfer Syntax:     Explicit VR Big Endian (Retired)
[INFO] Received association request from AE: MSTZ400D with IP: 127.0.0.1

**[WARNING] Requested abstract syntax Presentation LUT SOP Class [1.2.840.10008.5.1.1.23] from MSTZ400D not supported**

[INFO] Accepted association request from MSTZ400D
[INFO] MSTZ400D -> Association accept:
Calling AE Title:          MSTZ400D
Called AE Title:           Magic
Remote host:               10.200.3.2
Remote port:               59716
Implementation Class:      Implementation Class UID [1.3.12.2.1107.5.2]
Implementation Version:    MR_VD14A
Maximum PDU Length:        262144
Async Ops Invoked:         1
Async Ops Performed:       1
Presentation Contexts:     4
  Presentation Context:     1 [Accept]
       Abstract Syntax:     Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:     Explicit VR Little Endian
  Presentation Context:     3 [Accept]
       Abstract Syntax:     Print Job SOP Class
       Transfer Syntax:     Explicit VR Little Endian
  Presentation Context:     5 [Accept]
       Abstract Syntax:     Basic Color Print Management Meta SOP Class
       Transfer Syntax:     Explicit VR Little Endian
  Presentation Context:     7 [RejectAbstractSyntaxNotSupported]
       Abstract Syntax:     Presentation LUT SOP Class
       Transfer Syntax:     Explicit VR Little Endian
[INFO] MSTZ400D <- N-Get request [310]
[INFO] N-Get request [310]
--------------------------------------------------------------------------------
 DIMSE Command:
--------------------------------------------------------------------------------
(0000,0000) UL 90                                               #     4, CommandGroupLength
(0000,0003) UI [1.2.840.10008.5.1.1.16]                         #    22, RequestedSOPClassUID
(0000,0100) US 272                                              #     2, CommandField
(0000,0110) US 310                                              #     2, MessageID
(0000,0800) US 257                                              #     2, CommandDataSetType
(0000,1001) UI [1.2.840.10008.5.1.1.17]                         #    22, RequestedSOPInstanceUID

--------------------------------------------------------------------------------

[INFO] N-Get response [310]: Success
--------------------------------------------------------------------------------
 DIMSE Command:
--------------------------------------------------------------------------------
(0000,0002) UI [1.2.840.10008.5.1.1.16]                         #    22, AffectedSOPClassUID
(0000,0100) US 33040                                            #     2, CommandField
(0000,0120) US 310                                              #     2, MessageIDBeingRespondedTo
(0000,0800) US 514                                              #     2, CommandDataSetType
(0000,0900) US 0                                                #     2, Status
(0000,1000) UI [1.2.840.10008.5.1.1.17]                         #    22, AffectedSOPInstanceUID

--------------------------------------------------------------------------------
 DIMSE Dataset:
--------------------------------------------------------------------------------
(0008,0070) LO [MedicalSoft]                                    #    12, Manufacturer
(0008,1090) LO [PaXtreme Printer]                               #    16, ManufacturerModelName
(0018,1000) LO (no value available)                             #     0, DeviceSerialNumber
(0018,1020) LO (no value available)                             #     0, SoftwareVersions
(0018,1200) DA [20210514]                                       #     8, DateOfLastCalibration
(0018,1201) TM [093028]                                         #     6, TimeOfLastCalibration
(2110,0010) CS [NORMAL]                                         #     6, PrinterStatus
(2110,0020) CS (no value available)                             #     0, PrinterStatusInfo
(2110,0030) LO (no value available)                             #     0, PrinterName

--------------------------------------------------------------------------------

[INFO] MSTZ400D -> N-Get response [310]: Success
[INFO] MSTZ400D <- N-Create request [311]
[INFO] Create new film session 2.25.149707090954240265009923977725984920630
[INFO] MSTZ400D -> N-Create response [311]: Success
[INFO] MSTZ400D <- N-Create request [312]
[INFO] Applying display format STANDARD\1,1 for film box Local UID [2.25.22267873071965234101984762411298653628]
[INFO] Created new film box 2.25.22267873071965234101984762411298653628
[INFO] MSTZ400D -> N-Create response [312]: Success
[INFO] MSTZ400D <- N-Set request [313]
[INFO] Set image box 2.25.22267873071965234101984762411298653628.1
[INFO] MSTZ400D -> N-Set response [313]: Success
[INFO] MSTZ400D <- N-Action request [314]
                Action Type:    0001
[INFO] Creating new print job for film box 2.25.22267873071965234101984762411298653628
[INFO] Print Job 220469928368039779416717633843808894716 Status Pending: QUEUED
[INFO] MSTZ400D -> N-EventReport request [1]
                Event Type:     0001
[INFO] MSTZ400D <- N-EventReport response [1]: Success
[INFO] Print Job 220469928368039779416717633843808894716 Status Printing: QUEUED
[INFO] MSTZ400D -> N-Action response [314]: Success
                Action Type:    0001
[INFO] MSTZ400D -> N-EventReport request [2]
                Event Type:     0002
[INFO] MSTZ400D <- N-Delete request [315]
[INFO] MSTZ400D <- N-EventReport response [2]: Success
[INFO] MSTZ400D -> N-Delete response [315]: Success
[INFO] Print Job 220469928368039779416717633843808894716 Status Printing: NORMAL
[INFO] MSTZ400D -> N-EventReport request [3]
                Event Type:     0002
[INFO] MSTZ400D <- N-EventReport response [3]: Success
[INFO] Print Job 220469928368039779416717633843808894716 Status Done: NORMAL
[INFO] MSTZ400D -> N-EventReport request [4]
                Event Type:     0003
[INFO] MSTZ400D <- N-Delete request [316]
[INFO] MSTZ400D <- N-EventReport response [4]: Success
[INFO] MSTZ400D -> N-Delete response [316]: Success
[INFO] MSTZ400D <- Association release request
[INFO] MSTZ400D -> Association release response
[INFO] Connection closed

**Comment by gofal** [comment]
Sorry, I cannot see any error. This seems to be the log of a pretty normal printing. the association request was done with a normal handshare, then the print SCU created a film session, then created a film box and set an image into the film box. Then the scu called the n-action to print the image and cleaned up everything again.

**Comment by andersoncav** [comment]
the impression is pausano in the siemens resonance. Could it be due to this error message that is in the log?
[WARNING] Requested abstract syntax Presentation LUT SOP Class [1.2.840.10008.5.1.1.23] from MSTZ400D not supported

**Comment by gofal** [comment]
this is not an error, its just an warning. 
In DICOM handshake the scu sends all the abstract syntaxes that the client wants to use, then the server responds which of them are supported. and then it's up to the client to quit the association or to use only those abstractsyntaxes that are supported.

For example, it's common that the user requests "BasicGrayscalePrintManagement" and "BasicColorPrintManagement" when having color images. then the server accepts BasicGrayscalePrintManagemet and rejects BasicColorPrintManagement because there is only a black/white printer. so the client converts the color images into grayscale and sends the images as grayscale....

Rejecting some of the requested abstract syntaxes is not an error at all.

If the client does an association request, the server rejects some abstract syntaxes and then the client ends the association without any further action, then you can assume that the rejected abstract syntax was essential to the client. But in this case the client continued printing. The client only knew not to use LUT (lookup tables) when sending the images to print.

I am affraid, you have to contact some technican of the siemens machine to take a look at the logs of the siemens machine.....
