### ISSUE TITLE
Add support for Universal Windows Platform

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#118]
Add a platform target for the *Universal Windows Platform* (Windows 10 on desktops, tablets, phones and, potentially, IoT).

Library should support imaging and native codec handling.

**Comment by anders9ustafsson** [comment]
A baseline for this functionality has been provided by PR #124 , but as pointed out in the PR issues remain to be solved. These include:

* Networking implementation not functioning satisfactory.
* Overly restrictive file I/O due to re-using the `DesktopFileManager` implementation. For example, UI event handlers does not accept direct calls to synchronous methods such as `File.Delete`; requires embedding the method invoking this `File` method inside a `Task`.
* Image rendering not fully validated; there are indications that some image types cannot be rendered correctly (due to 3-component rather than 4-component representation?)

Before this issue can be closed the above items need to be sufficiently addressed.

**Comment by IanYates** [comment]
For things like 
```
Overly restrictive file I/O due to re-using the DesktopFileManager implementation. 
For example, UI event handlers does not accept direct calls to synchronous methods such as 
File.Delete; requires embedding the method invoking this File method inside a Task.
```

should we just do async all the way down, taking the breaking change for v2?

**Comment by anders9ustafsson** [comment]
Many thanks, Ian!

Yes, that sounds like a plausible way forward! I'll look into this in more detail soon, and please don't hesitate to let me know if you have any specific recommendations on how to proceed.
