### ISSUE TITLE
Socket error while reading PDU: ConnectionAborted [10053]

### ISSUE THREAD

**Issue by jdbogdan** [fo-dicom/fo-dicom#1180]
[INFO] DVTK_MW_SCU <- Association request:
Calling AE Title: DVTK_MW_SCU
Called AE Title: Zhy
Remote host: 10.8.109.38
Remote port: 64748
Implementation Class: Implementation Class UID [1.2.276.0.7230010.3.0.3.6.4]
Implementation Version: OFFIS_DCMTK_364
Maximum PDU Length: 16384
Async Ops Invoked: 1
Async Ops Performed: 1
Presentation Contexts: 1
Presentation Context: 1 [Proposed]
Abstract Syntax: Modality Worklist Information Model - FIND
Transfer Syntax: Explicit VR Little Endian
Transfer Syntax: Explicit VR Big Endian (Retired)
Transfer Syntax: Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] Received association request from AE: DVTK_MW_SCU with IP: 10.8.109.38
[INFO] Accepted association request from DVTK_MW_SCU
[INFO] DVTK_MW_SCU -> Association accept:
Calling AE Title: DVTK_MW_SCU
Called AE Title: Zhy
Remote host: 10.8.109.38
Remote port: 64748
Implementation Class: Implementation Class UID [1.2.276.0.7230010.3.0.3.6.4]
Implementation Version: OFFIS_DCMTK_364
Maximum PDU Length: 16384
Async Ops Invoked: 1
Async Ops Performed: 1
Presentation Contexts: 1
Presentation Context: 1 [Accept]
Abstract Syntax: Modality Worklist Information Model - FIND
Transfer Syntax: Explicit VR Little Endian
[INFO] Socket error while writing PDU: ConnectionAborted [10053]
[INFO] Connection closed
[INFO] Socket error while reading PDU: ConnectionAborted [10053]

IOException in FellowOakDicom.Network.DicomService

Is this a client-side problem or a server-side problem

**Comment by gofal** [comment]
hard to say.
All I can read from log is: there seem to be an association request from client and the server accepted the request. 
next step would be that the client sends the the action c-find message containing the query-filters and then the server returns the results, and then the client sends an association-release-request and the association will be released.
But here the connection seems to be broken after association request.

this can be client-side, so the client now would read some query-information and fails.
or it can be server-side, so the server now blocks the thread for some reason and so after some timeout the client aborts the connection. 
Maybe at least timestamps in log would be helpful. And some of your code, to find out if your server could cause the issue.
