### ISSUE TITLE
Breaking change around FloatPixelData between 4.0.1 and 4.0.2

### ISSUE THREAD

**Issue by pierrekhouryb** [fo-dicom/fo-dicom#1186]
**Describe the bug**
The following sample code that adds FloatPixelData to a DicomDataset works fine with 4.0.1, but throws an exception with 4.0.2. 
```           
DicomDataset dicomDataset = new DicomDataset
{
    { DicomTag.Rows, (ushort)1 },
    { DicomTag.Columns, (ushort)2 },
};

dicomDataset.AddOrUpdate(new DicomDataset { { DicomTag.FloatPixelData, new float[] { 1.0f, 2.0f } } });
```

Exception thrown:
> 'Content "(7fe0,0008) OF Float Pixel Data" does not validate VR OF: Number of items 2 does not match ValueMultiplicity 1'

**To Reproduce**
Run the above snippet using fo-dicom 4.0.1. 
Verify no exceptions are thrown.
Update fo-dicom from 4.0.1 to 4.0.2.
Verify an exception is thrown.

**Expected behavior**
No exceptions and the DicomDataset is properly create with FloatPixelData.

**What I tried**
I tried disabling auto-validate but it didn't have any effects:
`dicomDataset.AutoValidate = false;`

**Environment**
Fellow Oak DICOM version: 4.0.1 and above
OS: Windows 10 x64
Platform: .NET Core 5.0

**Comment by gofal** [comment]
I am bit of confused right now. DICOM defines the Value Multiplicity of the DicomTag 7FE0,0008 FloatPixelData to be 1 (https://dicom.innolitics.com/ciods/parametric-map/floating-point-image-pixel/7fe00008). This is why the array fails validation. Validation was introduced in 4.0.2.
On the other hand the description of this tags says "a data stream of the pixel samples that comprise the image", so an array of values seems to be expected.

**Comment by mrbean-bremen** [comment]
OF behaves the same way as OB and OW, e.g. the content is a contiguous array that comprises only one value, meaning that Value Multiplicity is always 1 independent of the actual data length. The VM check does not make sense for any Ox VR as far as I understand.

**Comment by pierrekhouryb** [comment]
Thanks @mrbean-bremen for fixing this! @gofal would you have any estimate on a 4.0.8 release that includes this fix by any chance?

**Comment by gofal** [comment]
@pierrekhouryb it was released yesterday.
