### ISSUE TITLE
Discrepancies found in anonymization profiles

### ISSUE THREAD

**Issue by fordanic** [fo-dicom/fo-dicom#1189]
**Describe the bug**
Discrepancies have been found in the SecurityProfile class and DefaultProfile as compared with profile listed in the DICOM standard at http://dicom.nema.org/medical/dicom/current/output/html/part15.html#table_E.1-1 version DICOM PS3.15 2021b.

The discrepancies are the following:

- fo-dicom are missing the following tags: '400,0551', '400,0552', '0018,11BB', '18,9937', 
- fo-dicom use other operators/action codes for the following tags in the basic profile: '3006,0009', '300A,00B2'

**To Reproduce**
Review the SecurityProfile class and DefaultProfile and compare with profile listed in the DICOM standard at http://dicom.nema.org/medical/dicom/current/output/html/part15.html#table_E.1-1 version DICOM PS3.15 2021b.

**Expected behavior**
No discrepancies

**Environment**
Code review based upon commit f44260ad66049e24cb32466440b1ed477b85908e

**Comment by gofal** [comment]
Agree. fo-dicom periodically regenerates its dictionaries like DicomTags, constants, anonymization profies etc.
Last update was on 3rd Februar 2021 with commit 7aa56f5d to DICOM Standard 2021a. an update to version 2021b will solve your issue.
