### ISSUE TITLE
Too many presentation contexts configured for this association! On cGetRequest

### ISSUE THREAD

**Issue by uttamdashtech** [fo-dicom/fo-dicom#1195]
**Describe the bug**
When I loop through serisUId i am getting "Too many presentation contexts configured for this association!" 
I have total 6 seriesUId. The code is working find for 1st 2 series but when it goes to 3rd seriesUId in it is throwing the error "Too many presentation contexts configured for this association!" 

I have found the same issue was opened with #590. It says the "Problem was due to an incomplete update when refactoring the DicomPresentationContext.AcceptedTransferSyntax". I have used fo-dicom nuget-package manager. Please help how can i update my code.

Here's a snippet of code that's causing the issue. 

client = new DicomClient(dicomRemoteHost, dicomRemoteHostPort, false, ourDotNetTestClientDicomAeTitle, remoteDicomHostAeTitle);
foreach (var serisUId in serieUids)
{
var cGetRequest = CreateCGetBySeriesUID(studyUID, serisUId);
client.OnCStoreRequest += (DicomCStoreRequest req) =>
{
Console.WriteLine(DateTime.Now.ToString() + "DCM files recived");
SaveImage(req.Dataset);
return Task.FromResult(new DicomCStoreResponse(req, DicomStatus.Success));
};
// the client has to accept storage of the images. We know that the requested images are of SOP class Secondary capture,
// so we add the Secondary capture to the additional presentation context
// a more general approach would be to mace a cfind-request on image level and to read a list of distinct SOP classes of all
// the images. these SOP classes shall be added here.
var pcs = DicomPresentationContext.GetScpRolePresentationContextsFromStorageUids(
DicomStorageCategory.Image,
DicomTransferSyntax.ExplicitVRLittleEndian,
DicomTransferSyntax.ImplicitVRLittleEndian,
DicomTransferSyntax.ImplicitVRBigEndian);
client.AdditionalPresentationContexts.AddRange(pcs);
await client.AddRequestAsync(cGetRequest);
await client.SendAsync();

**Comment by gofal** [comment]
Well, it's just as the error message says: too many presentation contexts. 
Your code iterates each serie and does the following:
 - create the cget request
 - add a event-handler to client.oncstorerequest
 - add additional presentation contexts for all (!) available image uids, that are 65 different
 - enqueue the request
 - sent the request
so the first one works fine, but with the second series you do all again! this means you do have two event handlers. Do you notice that with 2 series you will receive the double number of console logs? and with the second series you add additional 65 presentation contexts. And then with the third series it will be way tooo much.

change your code the following way

    // create a client and initialize
    client = new DicomClient(dicomRemoteHost, dicomRemoteHostPort, false, ourDotNetTestClientDicomAeTitle, remoteDicomHostAeTitle);

    client.OnCStoreRequest += (DicomCStoreRequest req) =>
    {
        Console.WriteLine(DateTime.Now.ToString() + "DCM files recived");
        SaveImage(req.Dataset);
        return Task.FromResult(new DicomCStoreResponse(req, DicomStatus.Success));
    };

    var pcs = DicomPresentationContext.GetScpRolePresentationContextsFromStorageUids(
        DicomStorageCategory.Image,
        DicomTransferSyntax.ExplicitVRLittleEndian,
        DicomTransferSyntax.ImplicitVRLittleEndian,
        DicomTransferSyntax.ImplicitVRBigEndian);
    client.AdditionalPresentationContexts.AddRange(pcs);

    // then create all the requests and enqueue them
    foreach (var serisUId in serieUids)
    {
        var cGetRequest = CreateCGetBySeriesUID(studyUID, serisUId);
        await client.AddRequestAsync(cGetRequest);
    }

    // now that everything is done, wo start the actual network-action
    await client.SendAsync();

**Comment by uttamdashtech** [comment]
> Well, it's just as the error message says: too many presentation contexts.
> Your code iterates each serie and does the following:
> 
> * create the cget request
> * add a event-handler to client.oncstorerequest
> * add additional presentation contexts for all (!) available image uids, that are 65 different
> * enqueue the request
> * sent the request
>   so the first one works fine, but with the second series you do all again! this means you do have two event handlers. Do you notice that with 2 series you will receive the double number of console logs? and with the second series you add additional 65 presentation contexts. And then with the third series it will be way tooo much.
> 
> change your code the following way
> 
> ```
> // create a client and initialize
> client = new DicomClient(dicomRemoteHost, dicomRemoteHostPort, false, ourDotNetTestClientDicomAeTitle, remoteDicomHostAeTitle);
> 
> client.OnCStoreRequest += (DicomCStoreRequest req) =>
> {
>     Console.WriteLine(DateTime.Now.ToString() + "DCM files recived");
>     SaveImage(req.Dataset);
>     return Task.FromResult(new DicomCStoreResponse(req, DicomStatus.Success));
> };
> 
> var pcs = DicomPresentationContext.GetScpRolePresentationContextsFromStorageUids(
>     DicomStorageCategory.Image,
>     DicomTransferSyntax.ExplicitVRLittleEndian,
>     DicomTransferSyntax.ImplicitVRLittleEndian,
>     DicomTransferSyntax.ImplicitVRBigEndian);
> client.AdditionalPresentationContexts.AddRange(pcs);
> 
> // then create all the requests and enqueue them
> foreach (var serisUId in serieUids)
> {
>     var cGetRequest = CreateCGetBySeriesUID(studyUID, serisUId);
>     await client.AddRequestAsync(cGetRequest);
> }
> 
> // now that everything is done, wo start the actual network-action
> await client.SendAsync();
> ```

@gofal Thanks for quick response.

I have used the code you mentioned but it says "Association Abort [source: Unknown; reason: NotSpecified".

**Comment by gofal** [comment]
so for some reason the server aborted the association, but usually it's something internal of the server. because there are a lot of errormessages if the request does not match, then the server returns this message. Or if the request is invalid, then there is usually an AssociationReject and not an abort.

**Comment by uttamdashtech** [comment]
> so for some reason the server aborted the association, but usually it's something internal of the server. because there are a lot of errormessages if the request does not match, then the server returns this message. Or if the request is invalid, then there is usually an AssociationReject and not an abort.

Hello @gofal 

Adding await client.SendAsync(); in foreach worked for me.

foreach (var serisUId in serieUids)
  {
      var cGetRequest = CreateCGetBySeriesUID(studyUID, serisUId);
      await client.AddRequestAsync(cGetRequest);
      await client.SendAsync();
  }

**Comment by gofal** [comment]
ok, thanks for the hint. I will keep in mind that the pacs behaves like that. but I cannot explain. must be some timing-thing that the pacs doesnt like it when the next request comes too early when the sending of the data is not completed internally or something like that. because under the hood it's actually the same if you enqueue the requests and then call sendasync once or if you call SendAsync after each enqueued request. The first version usually works faster because you do not have to do all the association handshake etc but you open one connection and then send all the request one after the other.

**Comment by uttamdashtech** [comment]
Yeah Thanks @gofal for your help. :) I am closing this issue now.
