### ISSUE TITLE
Is there a way to know through which association a DicomMessage was received?

### ISSUE THREAD

**Issue by andreassoderstrom79** [fo-dicom/fo-dicom#1201]
Hi!

I've been dabbling a bit with using FO-DICOM to implement a C-STORE proxy. I'm using the storage SCP example from https://github.com/fo-dicom/fo-dicom-samples to implement a storage SCP (DicomServer) that uses a storage SCU (DicomClient) that forwards messages to a configurable destination.

In this context I'd like to know through which (of possibly many) active associations to the SCP a DicomMessage is received. In the OnCStoreRequest method I have the DicomMessage and from that I can get the PresentationContext and AcceptedTransferSyntax but I don't see any obvious way of knowing the association through which the message was received. Is there a way to identify this "parent" association?

**Comment by andreassoderstrom79** [comment]
Ah! I didn't understand that there was one service instance created per association - that makes total sense! That solves my problem. Thanks for the clarification!
A really nice library this - good work guys!

**Comment by gofal** [comment]
You're welcome!
