### ISSUE TITLE
DicomFile.Open() with stop function does not preserve parsed tags from groups beyond group 8.

### ISSUE THREAD

**Issue by per-bohlin** [fo-dicom/fo-dicom#1204]
**Describe the bug**
DicomFile.Open() can pass "stop" `Func<ParseState,bool>` which stops the parsing when returning true.

We want to stop the parsing once we have found the Series Instance UID of a file, due to performance reasons (parsing thousands of files). But we need the value of the tag.

However, triggering the stop mechanism cause some **some** of the already parsed tags not to be preserved during the internal abort/cleanup procedure.

I've stepping through the code but have not been able to pinpoint exactly what goes wrong but I can tell that the "observer" pops the latest datasets in way that cause some of the already parsed tags to not be included in the final result.

**To Reproduce**

Running "FO-DICOM.Full.sln"

```c#
       // Add to DicomFileTest.cs and run
       // Based on Open_StopAfterOperatorsNameTag_OperatorsNameIncluded()
        [Fact]
        public void Open_StopAfterGroup20Tag_TagIncluded()
        {
            static bool criterion(ParseState state) => state.Tag.CompareTo(DicomTag.SeriesInstanceUID) > 0;

            var file = DicomFile.Open(TestData.Resolve("GH064.dcm"), DicomEncoding.Default, criterion);
            Assert.True(file.Dataset.Contains(DicomTag.SeriesInstanceUID));
        }
```

**Expected behavior**
I expected the Series Instance UID tag to be present in the dataset.

**Environment**
Fellow Oak DICOM version: 4.0.7
OS: Windows 10
Platform: ? Using FO_DICOM.Full.sln in Visual Studio 2019, from git tag 4.0.7

**Comment by mrbean-bremen** [comment]
I had a quick look at this, and it seems that the problem is with tags in a sequence item. The criterion is applied to sequence items recursively, and if any tag in a sequence item matches the stop criterion, the reading is stopped at that sequence tag.
This is probably a feature, and you easily avoid it by checking for the sequence depth:
```cs
        [Fact]
        public void Open_StopAfterGroup20Tag_TagIncluded()
        {
            static bool criterion(ParseState state) =>
                state.SequenceDepth == 0 && state.Tag.CompareTo(DicomTag.SeriesInstanceUID) > 0;

            var file = DicomFile.Open(TestData.Resolve("GH064.dcm"), DicomEncoding.Default, criterion);
            Assert.True(file.Dataset.Contains(DicomTag.SeriesInstanceUID));
        }
```
which passes.

**Comment by per-bohlin** [comment]
You are absolutely correct. Thank you for the quick response. Closing the issue.
