### ISSUE TITLE
The Doc of Api 'GrayscalePixelDataS16.Components' has wrong describe 

### ISSUE THREAD

**Issue by 1009058470** [fo-dicom/fo-dicom#1207]
**Describe the bug**
The doc for api Dicom.Imaging.Render GrayscalePixelDataS16 class Components has a wrong describe 
**_'Gets number of pixel components (normally 1 for grayscale, 1 for palette, and 3 for RGB and YBR).'_**

**Comment by gofal** [comment]
So you are requesting that this description is wrong. What would you expect instead? What would be a correct description?

**Comment by mrbean-bremen** [comment]
Actually I think we can close this - the description is correct, and I don't see the need to specifically add the actual returned number of channels for each sub class. 
@1009058470 - Feel free to reopen this if you disagree, and can provide a better description. Or better yet, make a PR with the changes you want to have.
