### ISSUE TITLE
Getting error "DICOM dataset is missing pixel data element."

### ISSUE THREAD

**Issue by pravinbakare1** [fo-dicom/fo-dicom#1217]
### Expected behavior
There should not be error 

### Actual behavior
Image should be there 

### Steps to reproduce the behavior
When i am getting OnCStoreRequest doing the following step to convert DCM file to JPG file .
  
var images = new DicomImage(request.Dataset);

### fo-dicom version and OS/platform
Fellow Oak DICOM version: 4.0.4
OS: Windows 10 x64

**Comment by mrbean-bremen** [comment]
Does that happen to every image? Have you checked that the images actually contain pixel data?

**Comment by pravinbakare1** [comment]
It happens to Every image , mage don have the pixel data

**Comment by pravinbakare1** [comment]
My DCM files dont have pixel data

**Comment by mrbean-bremen** [comment]
So, if your DICOM data does not have pixel data, what do expect a `DicomImage` to contain? `DicomImage` is for handling image data, so it doesn't make sense for DICOM data without an image, but maybe I don't understand your use case.

**Comment by pravinbakare1** [comment]
> 
> 
> So, if your DICOM data does not have pixel data, what do expect a `DicomImage` to .contain? `DicomImage` is for handling image data, so it doesn't make sense for DICOM data without an image, but maybe I don't understand your use case.

[1I00001.zip](https://github.com/fo-dicom/fo-dicom/files/7201498/1I00001.zip)
i have this file at my  end and i want to show the file in dicom viewer format

**Comment by mrbean-bremen** [comment]
This is an SR file, it cannot be viewd in a DICOM viewer format - DICOM viewers are about image data.

**Comment by pravinbakare1** [comment]
> 
> 
> This is an SR file, it cannot be viewed in a DICOM viewer format - DICOM viewers are about image data.

Have You extracted the file format is .dcm and i am able to view in micro dicom viewer  like below .
![image](https://user-images.githubusercontent.com/66236945/134136271-72104fa5-e3ae-4868-9a9d-f11904463978.png)

**Comment by mrbean-bremen** [comment]
Well, yes, it is possible to show the content in a viewer in some tree-like format, but not in an image viewer, as it is not an image. To handle SRs in fo-dicom, you can use `DicomStructuredReport` instead of `DicomImage`. You can then iterate over the contained data and so something with it, for example print out the contents in some structured way, as micro dicom viewer seems to do it.

**Comment by pravinbakare1** [comment]
> `DicomStructuredReport`

How can we show report data in structured way when we have SR file.

**Comment by mrbean-bremen** [comment]
Here is some sample code for traversing and printing the content with some basic indentation:
```cs
        private int indent = 0;        

        private void TraverseItem(DicomContentItem item)
        {
            indent += 1;
            Console.WriteLine(string.Concat(Enumerable.Repeat("  ", indent)) + item);
            foreach (var childItem in item.Children())
            {
                TraverseItem(childItem);
            }
            indent -= 1;
        }

        public void TraverseStructuredReport(DicomStructuredReport sr)
        {
            Console.WriteLine(sr.ToString());
            foreach (var item in sr.Children())
            {
                TraverseItem(item);
            }
        }
```
For your dataset this outputs something like:
```
(125200,DCM,"Adult Echocardiography Procedure Report") CONTAINER
  CONTAINS (121118,DCM,"Patient Characteristics") CONTAINER
    CONTAINS (8277-6,LN,"Body Surface Area") NUM [2,13 m2]
    CONTAINS (121032,DCM,"Subject Sex") CODE [(F,DCM,"Female")]
    CONTAINS (121033,DCM,"Subject Age") NUM [57 a]
    CONTAINS (8302-2,LN,"Patient Height") NUM [1,59 m]
    CONTAINS (29463-7,LN,"Patient Weight") NUM [115 kg]
  CONTAINS (121070,DCM,"Findings") CONTAINER
    HAS CONCEPT MOD (G-C0E3,SRT,"Finding Site") CODE [(T-32600,SRT,"Left Ventricle")]
    CONTAINS (125007,DCM,"Measurement Group") CONTAINER
      HAS CONCEPT MOD (G-0373,SRT,"Image Mode") CODE [(G-03A2,SRT,"2D mode")]
      CONTAINS (18051-3,LN,"Left Ventricular Fractional Shortening") NUM [36,280276861093 %]
        HAS CONCEPT MOD (121401,DCM,"Derivation") CODE [(R-00317,SRT,"Mean")]
        HAS PROPERTIES (121404,DCM,"Selection Status") CODE [(121412,DCM,"Mean value chosen")]
        HAS ACQ CONTEXT (G-0373,SRT,"Image Mode") CODE [(G-03A2,SRT,"2D mode")]
      CONTAINS (18051-3,LN,"Left Ventricular Fractional Shortening") NUM [36,280276861093 %]
        HAS ACQ CONTEXT (G-0373,SRT,"Image Mode") CODE [(G-03A2,SRT,"2D mode")]
      CONTAINS (18054-7,LN,"Interventricular Septum % Thickening") NUM [-38,110183533665 %]
...
```

**Comment by mrbean-bremen** [comment]
@pravinbakare1 - did this answer your question? Can we close the issue?

**Comment by pravinbakare1** [comment]
> 
> 
> @pravinbakare1 - did this answer your question? Can we close the issue?

yes we can close the issue thank you for help.
