### ISSUE TITLE
Create one dicom file from multi jpeg file in c#. 

### ISSUE THREAD

**Issue by Dash-Uttam** [fo-dicom/fo-dicom#1224]
Hello All,

I need to create one single dicom file from multiple jpeg files in c#. If can anyone has done please provide guidance or reference code ?

Thanks in Advance.

**Comment by mia-san** [comment]
hoping this helps.
https://gist.github.com/mia-san/7d5b4a333b36d854901c2b180f1e8950

you might need some changes if you're using version 5.
//
