### ISSUE TITLE
Cannot generate JPEG from Dicom

### ISSUE THREAD

**Issue by GeovaneW96** [fo-dicom/fo-dicom#1249]
**Describe the bug**
While using ImageRender.As Bitmap I get a runtime exception:

Cannot cast to 'Bitmap'; type must be assignable from 'Byte[]'

**To Reproduce**

`DicomImage image = new DicomImage(currentFile);
Bitmap bmp = image.RenderImage().As<Bitmap>();`

**Expected behavior**
Successfully generate JPEG images

**Environment**
Fellow Oak DICOM version: 5.0.0
fo-dicom.Codecs: 5.0.2
OS: macOS 10.12.6
Platform: .NET Framework 4.6.2

**Comment by Todilo** [comment]
@GeovaneW96 can you provide the solution for this? Trying to set it up for .net 6 and I don't seem to manage to.

**Comment by GeovaneW96** [comment]
> @GeovaneW96 can you provide the solution for this? Trying to set it up for .net 6 and I don't seem to manage to.

I used ImageSharp
```
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
......
dicomFile = DicomFile.Open(currentFile);
DicomImage image = new DicomImage(dicomFile.Dataset);
Image<Bgra32> renderedImage = image.RenderImage().AsSharpImage();
renderedImage.SaveAsJpeg(tmpFile);
```
