### ISSUE TITLE
DicomJsonConverter Reads Too Many Characters

### ISSUE THREAD

**Issue by wsugarman** [fo-dicom/fo-dicom#1251]
**Describe the Bug**
The `DicomJsonConverter` for `System.Text.Json` currently reads the `JsonTokenType.EndObject` JSON token when it should leave it as the current position at the end of parsing. While this is fine when parsing a JSON object alone, in the context of a JSON array it leaves the reader in the incorrect position such that it throws an error:

> **System.Text.Json.JsonException**: 'The converter 'FellowOakDicom.Serialization.DicomJsonConverter' read too much or not enough.

For example, in the .NET documentation their sample [PersonConverterWithTypeDiscriminator](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-converters-how-to?pivots=dotnet-5-0#support-polymorphic-deserialization)  returns the object as soon as the `JsonTokenType.EndObject` is encountered.

By making this fix, I think the existing `DicomArrayJsonConverter` would become `Obsolete` as the `DicomJsonConverter` can accomplish the same behavior.

**To Reproduce**
```csharp
public static void Main(string[] args)
{
    const string json = @"
[
    {
        ""00080016"":{
            ""vr"":""UI"",
            ""Value"":[
                ""2.25.329448490451502656335668647653471331740""
            ]
        },
        ""00080018"":{
            ""vr"":""UI"",
            ""Value"":[
                ""2.25.67929634425127559715685870388203755507""
            ]
        }
    },
    {
        ""00080020"":{
            ""vr"":""DA"",
            ""Value"":[
                ""20080701""
            ]
        },
        ""00080060"":{
            ""vr"":""CS"",
            ""Value"":[
                ""XRAY""
            ]
        }
    }
]
";
    var options = new JsonSerializerOptions();
    options.Converters.Add(new DicomJsonConverter());
    var datsets = JsonSerializer.Deserialize<List<DicomDataset>>(json, options);
}
```

**Expected Behavior**
The above example should be able to deserialize successfully.

**Screenshots or test DICOM files**
N/A

**Environment**
Fellow Oak DICOM version: 5.0.0
OS: Windows 10 x64
Platform: .NET 5.0

**Comment by wsugarman** [comment]
This may be related to #1220

**Comment by wsugarman** [comment]
Thanks for checking this in @mrbean-bremen! Is there an estimate on when we'll see 5.0.1 release? We cannot really use the new serializers until this change is out.

**Comment by mrbean-bremen** [comment]
This is a probably a question for @gofal.

**Comment by gofal** [comment]
I will estimate a release within the next week.

**Comment by wsugarman** [comment]
That'd be great! Thank you!
