### ISSUE TITLE
Saving a DICOM file loads the full DICOM file into memory

### ISSUE THREAD

**Issue by amoerie** [fo-dicom/fo-dicom#1256]
DicomFile.Save is quite inefficient, it loads the full DICOM file in memory even if we just copy the DICOM file to a new location.

The main culprit behind this is how DicomWriter is implemented. It uses IByteBuffer.GetByteRange in chunks of largeObjectSize (1kb), and this keeps allocating new 1kb arrays.

I have a pending solution already:

1. Invert the responsibility: add methods `IByteBuffer.WriteTo(IByteTarget target)` and `IByteBuffer.WriteToAsync(IByteTarget target, CancellationToken cancellationToken)`
2. Inside the implementation, make use of System.Buffers.ArrayPool to optimize memory usage

**Comment by amoerie** [comment]
Benchmarks after making the aforementioned modifications, this is the performance of opening a 3GB DICOM file and saving it to a new location:

![image](https://user-images.githubusercontent.com/2063584/140728698-6ad2d1d1-c804-45a2-b8b8-4d5615812782.png)

**Comment by amoerie** [comment]
I will make a pull request ASAP

**Comment by gofal** [comment]
Great! So the difference is, when you open a file with FileReadOption .ReadLargeOnDemand? If the data is already in memory, then it is written from there?

**Comment by amoerie** [comment]
FileReadOption makes no difference. The issue is that DicomFile.Save calls into DicomFileWriter, which internally FileByteBuffer.GetByteRange, which always allocates a new byte array to give you the results, and if you are saving a DICOM file, it walks through the full byte range, i.e. the entire file.

So essentially you are making a copy in memory of the entire file.

**Comment by gofal** [comment]
Ah, I see.
That will be an important enhancement.

**Comment by amoerie** [comment]
@gofal You already fixed this! I found this while using fo-dicom 4.x but it looks like you already implemented your own solution for this in the 5.x release line. You added ApplyToStream and ApplyToStreamAsync to IByteTarget

**Comment by gofal** [comment]
Did I? This was unintentionally. This change was one of the first reworks in version 5. in version 4 there is a lot of code with byte arrays because of PCL build, but in version 5 I utilized streams and async more. I was not aware that this saves so much memory.

**Comment by amoerie** [comment]
I'll do a little cleanup, we never actually need the offset and length parameters. Also, I will introduce System.Buffers.ArrayPool to further reduce the memory footprint of these operations. 
But the main root cause has already been fixed then. :-)

**Comment by amoerie** [comment]
Update: I think the issues might actually still be there. IFileByteBuffer.CopyToStream calls File.GetByteRange(Position + offset, count) which makes a new byte array again. 🤐

I'll see if I can benchmark to prove it.

**Comment by amoerie** [comment]
So, bad news, the issue still exists. Will post benchmark results soon.

**Comment by amoerie** [comment]
Benchmark results are in: (copied from pull request comment)

Saving an 11MB DICOM file 
------------------------------

1. Before this pull request

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.22000
Intel Core i7-8700K CPU 3.70GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.402
  [Host]     : .NET Core 3.1.20 (CoreCLR 4.700.21.47003, CoreFX 4.700.21.47101), X64 RyuJIT
  DefaultJob : .NET Core 3.1.20 (CoreCLR 4.700.21.47003, CoreFX 4.700.21.47101), X64 RyuJIT


```
|    Method |     Mean |     Error |    StdDev |     Gen 0 |     Gen 1 |     Gen 2 | Allocated |
|---------- |---------:|----------:|----------:|----------:|----------:|----------:|----------:|
|      Save | 7.381 ms | 0.0743 ms | 0.0659 ms | 1460.9375 | 1453.1250 | 1453.1250 |   11.2 MB |
| SaveAsync | 8.591 ms | 0.1488 ms | 0.1392 ms | 1593.7500 | 1562.5000 | 1562.5000 |  11.29 MB |

2. After this pull request

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.22000
Intel Core i7-8700K CPU 3.70GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.402
  [Host]     : .NET Core 3.1.20 (CoreCLR 4.700.21.47003, CoreFX 4.700.21.47101), X64 RyuJIT
  DefaultJob : .NET Core 3.1.20 (CoreCLR 4.700.21.47003, CoreFX 4.700.21.47101), X64 RyuJIT


```
|    Method |     Mean |     Error |    StdDev |   Gen 0 | Gen 1 | Gen 2 | Allocated |
|---------- |---------:|----------:|----------:|--------:|------:|------:|----------:|
|      Save | 4.884 ms | 0.0955 ms | 0.1514 ms |       - |     - |     - |  28.13 KB |
| SaveAsync | 8.583 ms | 0.4430 ms | 1.3063 ms | 15.6250 |     - |     - | 126.41 KB |

**Comment by IqbalAST** [comment]
@amoerie  Can you please share the code how you save DICOM file locally. I've a PACS server, I can connect to it and query patient's information but I can't get any images (X-RAY, MRI etc).

My only purpose is to download .dcm file from PACS server to backup in a local drive.
Thanks..

**Comment by amoerie** [comment]
> @amoerie  Can you please share the code how you save DICOM file locally. I've a PACS server, I can connect to it and query patient's information but I can't get any images (X-RAY, MRI etc).
> 
> My only purpose is to download .dcm file from PACS server to backup in a local drive.
> Thanks..
> [Edit: This is the first time I'm using it.]

Please open a separate issue with your question, this is not the place.
