### ISSUE TITLE
Memory usage improvements

### ISSUE THREAD

**Issue by amoerie** [fo-dicom/fo-dicom#1262]
Now that we have System.Buffers, I thought I'd peek around and see if I can make some more memory usage improvements. 
I think we might have some great opportunities in DicomService, especially with regards to reading and writing PDV chunks. 

I'm creating this issue to present any findings - if any - and to invite discussion. I might make a pull request if I can make some worthwhile improvements.

**Comment by amoerie** [comment]
Initial results are promising. It looks like we copied all incoming PDU data in (small chunks of) byte arrays, essentially making a full copy of all data that comes in.

By reusing a buffer from the shared array pool there, I have been able to improve sending a C-STORE request to an in-memory DICOM server.

Before my changes:

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.19043
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.402
  [Host]     : .NET Core 3.1.20 (CoreCLR 4.700.21.47003, CoreFX 4.700.21.47101), X64 RyuJIT
  Job-OGURGR : .NET Core 3.1.20 (CoreCLR 4.700.21.47003, CoreFX 4.700.21.47101), X64 RyuJIT

MaxIterationCount=25  

```
|            Method |     Mean |     Error |    StdDev |    Gen 0 |    Gen 1 |    Gen 2 |  Allocated |
|------------------ |---------:|----------:|----------:|---------:|---------:|---------:|-----------:|
|  SendEchoToServer | 2.031 ms | 0.0837 ms | 0.1117 ms |  39.0625 |        - |        - |  102.33 KB |
| SendStoreToServer | 7.156 ms | 0.1536 ms | 0.1578 ms | 515.6250 | 296.8750 | 250.0000 | 5266.09 KB |

After my changes:

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.19043
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.402
  [Host]     : .NET Core 3.1.20 (CoreCLR 4.700.21.47003, CoreFX 4.700.21.47101), X64 RyuJIT
  Job-IDJFPP : .NET Core 3.1.20 (CoreCLR 4.700.21.47003, CoreFX 4.700.21.47101), X64 RyuJIT

MaxIterationCount=25  

```
|            Method |     Mean |     Error |    StdDev |    Gen 0 |    Gen 1 |    Gen 2 |  Allocated |
|------------------ |---------:|----------:|----------:|---------:|---------:|---------:|-----------:|
|  SendEchoToServer | 2.002 ms | 0.0692 ms | 0.0924 ms |  35.1563 |        - |        - |   92.44 KB |
| SendStoreToServer | 6.668 ms | 0.1475 ms | 0.1969 ms | 343.7500 | 281.2500 | 257.8125 | 4741.46 KB |

**Comment by amoerie** [comment]
Related issue I might revisit: #1091

**Comment by amoerie** [comment]
I think we could avoid making a full in-memory copy of each PDU (so PDU -> NetworkStream instead of PDU -> RawPDU -> NetworkStream) if only we could avoid the need for MarkLength16 and WriteLength16 in PDU.cs. These methods require a seekable Stream, which NetworkStream isn't.
The reason these methods exist is to write the infamous Item-Length fields.
I actually believe we could calculate all of these lengths beforehand, I might have a go at it.

**Comment by gofal** [comment]
Ah yes, I can remeber this issue with the RawPDU-stream. I did then the commit https://github.com/fo-dicom/fo-dicom/commit/19f3bfd4d596d911a3aa4324a5d7749bdeb27826 where I introduced the MergedStream.  The above comments suggested some other solution, to first write the premble into the networkstream and then writing the acutal data. But that caused some weird side effects, some requests failed for any reason. When I then did it with this mergedstream it worked.

My assumption was that when you write directly into network stream, then you first write some part of the pdu then you write the next part and so on. This results that onn networkstream then there might be some delays or similar between those parts. And so the PDU might not be sent as one chunk over the network. the parser on the other side then may fail, at least it did when i was testing then. So collecting the data of the PDU into this RawPDU and then sending the whole RawPDU in one flush is some mechanism of stability.

**Comment by amoerie** [comment]
Good to know, thanks for providing that info. I think we can avoid the first problem (the preamble being sent separately) by simply using a BufferedStream around the NetworkStream ( https://docs.microsoft.com/en-us/dotnet/api/system.io.bufferedstream?view=net-5.0 ) because otherwise we would be doing a lot of miniscule writes to the underlying NetworkStream. 

In any case, if I manage to find a way to make this work, I'll test with some real world setup to make sure requests still work. Of course, it's impossible to test with every PACS and every situation..

**Comment by amoerie** [comment]
I have made some additional adjustments to PDU.cs and DicomService.cs:

- When writing PDUs, use rented byte arrays to buffer the content. In the case of P-DATA-TF, we write directly to the (buffered) network stream. But in the case of association handshake PDUs, we write to a MemoryStream (with a rented byte array as internal buffer). Since these handshake messages are very small (max 65 536 bytes for A-ASSOCIATE-RQ and A-ASSOCIATE-AC), it is safe to rent these
- For incoming communication in DicomService, use a rented byte array to buffer the PDU if the total length (which we know thanks to the PDU preamble) is smaller than 1MB. 1MB because this is the internal cap set by the shared array pool. 
- For PDUs larger than 1MB, immediately allocate a byte array with the correct size and pass that in as the buffer of the MemoryStream. This improves the old implementation which used the default MemoryStream constructor, and that one behaves like a List: it uses an internal buffer that doubles in capacity on demand, which incurs a new allocation (and GC later on) + a Buffer.BlockCopy. By immediately creating a buffer with the correct size, we avoid this "automatic doubling of the internal buffer of MemoryStream" entirely.

Latest benchmarks including these changes:

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.19043
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.402
  [Host]     : .NET Core 3.1.20 (CoreCLR 4.700.21.47003, CoreFX 4.700.21.47101), X64 RyuJIT
  Job-NMZFKW : .NET Core 3.1.20 (CoreCLR 4.700.21.47003, CoreFX 4.700.21.47101), X64 RyuJIT

MaxIterationCount=25  

```
|            Method |     Mean |     Error |    StdDev |    Gen 0 |    Gen 1 |    Gen 2 |  Allocated |
|------------------ |---------:|----------:|----------:|---------:|---------:|---------:|-----------:|
|  SendEchoToServer | 2.212 ms | 0.1121 ms | 0.1417 ms |  35.1563 |        - |        - |   96.91 KB |
| SendStoreToServer | 6.901 ms | 0.1353 ms | 0.1558 ms | 164.0625 | 109.3750 | 109.3750 | 2198.19 KB |

**Comment by amoerie** [comment]
I am still seeing more opportunities for optimization:

- PDataTFStream is creating and resizing arrays left and right, for reasons that I have not deciphered yet. I might dig into this next.
- C-STORE requests with files larger than 1MB still allocate memory to contain the entire file. We could avoid this by using chunked rented byte arrays (much like RecyclableMemoryStream) but that is an undertaking I'm shying away from for now.
- When parsing a PDV, each PDU.ReadBytes() call allocates a new byte[] copy which is ridiculous, because we already have a fully buffered in memory copy of all the contents of the incoming DICOM message. 
- The above might be a limitation because of the API of BinaryReader, and I'm uncertain if I can get rid of BinaryReader without having to rewrite most of the low level PDU reading and writing, which I'm honestly a little scared of. It looks like we could replace BinaryWriter / BinaryReader with Memory<byte> from the System.Memory nuget package. This blog post details the benefits: https://stebet.net/real-world-example-of-reducing-allocations-using-span-t-and-memory-t/

**Comment by amoerie** [comment]
Late Sunday night update! Going to bed after this, but this problem has been tickling my brain in all the right places.

So, it turns out that BinaryReader does support a `Read` call that accepts a buffer, which is exactly what we needed! This allows us to assign a rented byte array as buffer for each incoming PDV that is parsed from a raw PDU. This also allows us to use rented byte buffers when reading a string (which requires an intermediate byte array before we pass it to `Encoding.GetBytes`)

These are the latest numbers:

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.19043
Intel Core i7-7700HQ CPU 2.80GHz (Kaby Lake), 1 CPU, 8 logical and 4 physical cores
.NET Core SDK=5.0.402
  [Host]     : .NET Core 3.1.20 (CoreCLR 4.700.21.47003, CoreFX 4.700.21.47101), X64 RyuJIT
  Job-VXIHCB : .NET Core 3.1.20 (CoreCLR 4.700.21.47003, CoreFX 4.700.21.47101), X64 RyuJIT

MaxIterationCount=25  

```
|            Method |     Mean |     Error |    StdDev |    Gen 0 |   Gen 1 |   Gen 2 |  Allocated |
|------------------ |---------:|----------:|----------:|---------:|--------:|--------:|-----------:|
|  SendEchoToServer | 1.961 ms | 0.0636 ms | 0.0849 ms |  35.1563 |       - |       - |   96.31 KB |
| SendStoreToServer | 6.157 ms | 0.1158 ms | 0.0967 ms | 117.1875 | 62.5000 | 62.5000 | 1684.51 KB |

**Comment by amoerie** [comment]
Mental note: check if TcpNoDelay on the socket still makes sense now that we're using a BufferedStream for writing.

**Comment by amoerie** [comment]
After refactoring PDataTFStream to also use rented byte arrays for its PDVs, memory has improved again!
Sending an ECHO or a C-STORE is now so fast, that BenchmarkDotnet drastically increased the number of executions per iteration, which actually caused socket port exhaustion on my computer. I had to manually reduce the the number of iterations again via a few BenchmarkDotNet attributes to get it working again, and now I'm getting these numbers:

``` ini

BenchmarkDotNet=v0.12.0, OS=Windows 10.0.22000
Intel Core i7-8700K CPU 3.70GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
.NET Core SDK=5.0.402
  [Host]     : .NET Core 3.1.20 (CoreCLR 4.700.21.47003, CoreFX 4.700.21.47101), X64 RyuJIT
  Job-CZJKXN : .NET Core 3.1.20 (CoreCLR 4.700.21.47003, CoreFX 4.700.21.47101), X64 RyuJIT

InvocationCount=128  MaxIterationCount=25  MaxWarmupIterationCount=10  
UnrollFactor=16  

```
|            Method |     Mean |     Error |    StdDev |   Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------ |---------:|----------:|----------:|--------:|------:|------:|----------:|
|  SendEchoToServer | 1.392 ms | 0.0439 ms | 0.0570 ms | 15.6250 |     - |     - |  98.86 KB |
| SendStoreToServer | 3.687 ms | 0.1201 ms | 0.1474 ms | 23.4375 |     - |     - | 144.81 KB |

**Comment by amoerie** [comment]
For those of you following along here, this work is a bit too much for one PR and requires some refactoring, so I'm pushing the work again, chopped in smaller PRs. This should make the changes more stable and make the lives of the reviewers easier.

The first PR is here https://github.com/fo-dicom/fo-dicom/pull/1267, it contains a bunch of improvements related to sending.

The most impactful changes (in DicomService and PDataTFStream specifically) are also the most risky ones, so these will definitely require separate PRs and extra unit tests.

**Comment by amoerie** [comment]
Second PR here: #1273

**Comment by amoerie** [comment]
Third PR here: #1291

**Comment by amoerie** [comment]
After my third PR, I think I'll take a break from performance optimizations for now. 

These are the final results (when PR #3 is merged).

Before (excluding PR 1, 2 and 3)
---------
|            Method |     Mean |     Error |    StdDev |    Gen 0 |    Gen 1 |    Gen 2 |  Allocated |
|------------------ |---------:|----------:|----------:|---------:|---------:|---------:|-----------:|
|  SendEchoToServer | 2.031 ms | 0.0837 ms | 0.1117 ms |  39.0625 |        - |        - |  102.33 KB |
| SendStoreToServer | 7.156 ms | 0.1536 ms | 0.1578 ms | 515.6250 | 296.8750 | 250.0000 | 5266.09 KB |

After (including PR 1, 2 and 3)
------
|            Method |     Mean |     Error |    StdDev |   Gen 0 | Gen 1 | Gen 2 | Allocated |
|------------------ |---------:|----------:|----------:|--------:|------:|------:|----------:|
|  SendEchoToServer | 1.035 ms | 0.0321 ms | 0.0428 ms | 15.6250 |     - |     - | 100.23 KB |
| SendStoreToServer | 2.921 ms | 0.1014 ms | 0.1246 ms | 23.4375 |     - |     - | 151.25 KB |

Don't look at the timings too much, since these benchmarks were taken at different times and so they're hard to compare. I do expect both C-ECHO and (especially) C-STORE to be faster, but that would require a more elaborate benchmarking setup.

However, the most important part is definitely the drastically reduced memory usage. Even for very large files, we never load the entire file anymore, instead using a buffered send and buffered receive mechanism with all buffers rented from array pools (by default).

This should drastically reduce the memory usage and corresponding garbage collection pressure in a service that sends and receives a lot of DICOM files.
