### ISSUE TITLE
Add support for web services (WADO, QIDO, STOW)

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#127]
Just putting this suggestion here to get people's opinions on the subject. Please comment!

**Comment by HelderMPinhal** [comment]
It's definitely a plus.
I have been reading a few things on WADO and was considering on doing that myself.
I will try to find some time to post some implementation guidelines to check your feedback.

**Comment by 0xLigety** [comment]
WADO would be a great feature for fo-dicom. 
Useful and needed for state of the art pacs / workstation and mobile clients.

**Comment by jaime-olivares** [comment]
Implementing the whole WADO-RS protocol will take some time. But for those implementing it by their selves, it will be helpful to get the metadata in XML or JSON formats straight from the Dataset class. I think there won't be a big technical challenge to implement that.

Sample XML: http://dicomweb.hcintegrations.ca/#/xml

Sample JSON: http://dicomweb.hcintegrations.ca/#/json

**Comment by anders9ustafsson** [comment]
Thanks, @jaime-olivares ! You'll be happy to hear that JSON support is already implemented: #182 #186. Will be included in next minor release.

**Comment by jaime-olivares** [comment]
Hi Anders, that sounds good. Is there any workitem for the xml version?
The full standard requires to serve both formats
BR,
Jaime.

From:  Anders Gustafsson
Reply-To:  fo-dicom/fo-dicom
Date:  Tuesday, March 29, 2016 at 09:12
To:  fo-dicom/fo-dicom
Cc:  Jaime Olivares
Subject:  Re: [fo-dicom/fo-dicom] Add support for web services (WADO, QIDO, STOW) (#127)


Thanks, @jaime-olivares ! You'll be happy to hear that JSON support is already implemented: #182 #186. Will be included in next minor release.

**Comment by jaime-olivares** [comment]
Also please make a distinction between WADO-URI, WADO-WS and WADO-RS (DicomWeb). They have different schemas. Same for QIDO and STOW.

**Comment by anders9ustafsson** [comment]
> Hi Anders, that sounds good. Is there any workitem for the xml version?
The full standard requires to serve both formats.

@jaime-olivares Not yet, but please feel free to post a [new issue](https://github.com/fo-dicom/fo-dicom/issues/new).

**Comment by anders9ustafsson** [comment]
> Also please make a distinction between WADO-URI, WADO-WS and WADO-RS (DicomWeb). They have different schemas. Same for QIDO and STOW.

@jaime-olivares Thanks, will keep this in mind.

**Comment by Zaid-Safadi** [comment]
Hi all, seems I'm a little late to find this project. I started implementing DICOMweb/WADO last year using ClearCanvas and have an almost full working implementation (including database and storage)
I'm in the process of open sourcing the .NET projects: https://github.com/Zaid-Safadi/DICOMcloud

If anyone is interested please let me know. My thoughts now is to replace ClearCanvas with another library as I am already having troubles with encoding/decoding images.

**Comment by anders9ustafsson** [comment]
@Zaid-Safadi I had a quick look at your project, and it seems to be exactly what we want! Splendid work! It would be fabulous if *DICOMCloud* could be adapted to *fo-dicom*.

We have recently implemented JSON serialization, but XML serialization is still missing. I noticed you also had some support for this. Also a welcome addition, of course.

Without having delved too deep in your code, I assume it is not PCL ready, or? Ideally we would like to be able to target PCL profile 111 as much as possible, which practically means .NET Framework 4.5, Windows Universal Platform, Windows 8, Windows Phone 8.1 (non-Silverlight), Xamarin iOS and Xamarin Android. We have solved platform dependencies through an abstraction layer of "managers" for file I/O, imaging, networking etc. Not sure how much work it would mean to adapt *DICOMCloud* to these prerequisites?

If PCL adoption is too much work, it would still be great to see one or more .NET-only web service libraries relying on the *fo-dicom* Core and Desktop Platform.

Let's stay in touch to see how we can help each other with this!

Best regards,
Anders @ Cureos

**Comment by Zaid-Safadi** [comment]
@anders9ustafsson, thank you for the great words, just the right encouragement and enthusiasm that I needed :)

I am looking right now at fo-dicom and it does have great features, very nice design and clearly a lot of energy. I also like to see what does it take to compile DICOMcloud with PCL profile and understand the prerequisites to adapt it to fo-dicom, at the very minimum and as a first step I should get ClearCanvas replaced by fo-dicom and support providing all different image formats/transfer syntax available.

We can also include the XML serialization that I have into fo-dicom, which I believe should belong to the “DICOM” library anyway from a design standpoint, this might be a nice exercise for me to get familiar with fo-dicom. 

I’ll start by adding these ideas to the repository issues and we can collaborate and help each other.

Great work!
Zaid Safadi

**Comment by anders9ustafsson** [comment]
Since [DICOMcloud](https://github.com/Zaid-Safadi/DICOMcloud) is built upon *fo-dicom* and provides a substantial part of the requested DICOM web services functionality, we should not "re-invent the wheel" but rather recommend *DICOMcloud* for these requirements.

**Comment by Zaid-Safadi** [comment]
Thank you @anders9ustafsson for recommending the [DICOMcloud](https://github.com/Zaid-Safadi/DICOMcloud)

I'm really interested to hear what others like to see in the library to improve usability, any improvements, features or feedback are welcome.

**Comment by robertvanommen** [comment]
where has DICOMcloud gone?

**Comment by anders9ustafsson** [comment]
@robertvanommen Maybe @Zaid-Safadi can shed some light on this?

**Comment by Zaid-Safadi** [comment]
The **DICOMcloud** has been moved to a new account [here](https://github.com/DICOMcloud/DICOMcloud)

**Comment by jaime-olivares** [comment]
As there is support for DICOMweb in a separate project, this issue should be completed.
