### ISSUE TITLE
fo-dicom 5.0 - DicomJson to convert List of DicomDataset to string json

### ISSUE THREAD

**Issue by sylvainb31** [fo-dicom/fo-dicom#1271]
I'm trying to convert a List of DicomDataset to a json string, but I can't find the right method to do so in fo-dicom 5.0

When I was using fo-dicom 4.7, i was using the following : 

`JsonConvert.SerializeObject(studiesListDataSet, new Dicom.Serialization.JsonDicomConverter());`

### Expected behavior

To have a method in FellowOakDicom.Serialization.DicomJson to convert a List of DicomDataset to a string json.

Method that should exist : ConvertDicomArrayToJson

Does it already exist and I haven't installed the correct package ?

### Actual behavior

Actual methods are : ConvertDicomToJson, ConvertJsonToDicom and ConvertJsonToDicomArray

### fo-dicom version and OS/platform

fo-dicom 5.0

**Comment by gofal** [comment]
You are right, that one overload is missing. It will be included in next release. If you cannot wait so long, you can do meanwhile the following: 
The code of ConvertDicomToJson is:

        public static string ConvertDicomToJson(DicomDataset dataset, bool writeTagsAsKeywords = false, bool formatIndented = false)
        {
            var options = new JsonSerializerOptions();
            options.Converters.Add(new DicomJsonConverter(writeTagsAsKeywords: writeTagsAsKeywords));
            options.WriteIndented = formatIndented;
            var conv = JsonSerializer.Serialize(dataset, options);
            return conv;
        }

as you can see here: https://github.com/fo-dicom/fo-dicom/blob/fd190f60a7c9a4ff284a5b1abc90856dff153f07/FO-DICOM.Core/Serialization/DicomJson.cs#L13

Those are all public classes, no private or internal code, so you can copy this method into your project and replace the `DicomDataset` parameter to a `DicomDataset[]` array parameter, or a `IEnumerable<DicomDataset>`. The rest still works the same.

**Comment by sylvainb31** [comment]
Thanks a lot for your answer ! :)
