### ISSUE TITLE
Add codec support for Android, iOS and Mono platforms

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#128]
Currently, RLE, JPEG, JPEG-LS and JPEG2000 codecs are not supported on the Mono-based platforms (Xamarin Android, Xamarin iOS and Mono), whereas they are fully supported on .NET and UWP.

For completeness, these compressed image codecs should be supported on all platforms that *fo-dicom* targets.

From an implementation point of view, a *P/Invoke* based solution should probably be considered.

**Comment by anders9ustafsson** [comment]
It is probably better to base this implementation on the native codec implementation for the *Universal Windows Platform* (PR #124) since the UWP implementation has been made independent of the *Dicom.Core* assembly.

**Comment by jaime-olivares** [comment]
It is crucial to have a complete test suite for validating encoding, and then compare the native Windows and *X implementations. I have found only DicomTranscoderTest.cs, which seems to be insufficient.

**Comment by anders9ustafsson** [comment]
@jaime-olivares Yes, we could do with a lot more unit tests. Community contributions are more than welcome. Do you have something to contribute?

**Comment by tolstenko** [comment]
I need a build to work with Unity3D. It is a mono based game engine. I will be glad to help. But first I need to understand better what I need to do. I fixed most of code problems involving Task Threading, but I need to understand what is really needed and what isnt. I am dropping support to many features to improve compatibility to unity and I thinking I am doing it wrong.

**Comment by anders9ustafsson** [comment]
@tolstenko Please see my response [here](https://gitter.im/fo-dicom/fo-dicom?at=57060343b17e698d5ef18ed1).

**Comment by hdesouky** [comment]
Since Xamarin is now available fore free with no restriction, it is now more appealing to support codec libraries for both iOS and Android.

I am not that big Xamarin expert, but i rolled out a research project to find out how far can i go.

**Comment by tolstenko** [comment]
Sure! Smartphones nowadays have lots of ram enabling them to open a full dicom exams without problems. It will be awesome! Please support Unity3D users too.
