### ISSUE TITLE
Unable to go from DICOM to JPEG image format

### ISSUE THREAD

**Issue by AJohnson2ACR** [fo-dicom/fo-dicom#1280]
**Describe the bug**
Using the documentation and links provided on the Fo-Dicom ReadMe, I am unable to produce an image from a DICOM file that works in both Linux and Windows. Every method attempts throws an except in Linux, or both Windows and Linux (Ubuntu hosted in docker container).

**To Reproduce**
**Method 1:**

When attempting to use the Bitmap and NativeTranscoderManager method, I get an exception of:

"Cannot cast to 'Bitmap'; type must be assignable from 'Byte[]'".

In startup.cs:
```
new DicomSetupBuilder()
       .RegisterServices(s => 
            s.AddFellowOakDicom().AddTranscoderManager<FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager>())
       .SkipValidation()
       .Build();
```
usage:

```
var image = new DicomImage(filePath);
var bitmap = image.RenderImage().As<Bitmap>();
```
The exception is thrown on the image.RenderImage().<Bitmap>() method. This is on Windows.

**Method 2:**

When using ImageSharp example:

startup.cs
```
new DicomSetupBuilder()
              .RegisterServices(s => s.AddFellowOakDicom().AddImageManager<ImageSharpImageManager>())
              .SkipValidation()
              .Build();
```
 usage:

```
var image = new DicomImage(filePath);
var sharpimage = image.RenderImage().AsSharpImage();
using var stream = new MemoryStream();
sharpimage.Save(stream, new JpegEncoder());
```
This method works on Windows. When running this same code in the Ubuntu container, I get the following exception:
"Decoding dataset with transfer syntax: JPEG 2000 Image Compression (Lossless Only) is not supported."

**Expected behavior**
Method will work both on Windows and Ubuntu.

**Screenshots or test DICOM files**
Not applicable.

**Environment**
NugetPackages:
fo-dicom 5.0.0
fo-dicom.Drawing 4.0.8
fo-dicom.Codecs 5.0.2
fo-dicom.Imaging.ImageSharp 5.0.0
fo-dicom.NetCore 4.0.8
SixLabors.ImageSharp 1.0.4

OS: Windows 10 and Ubuntu 18.04 LTS (Docker Container)
Platform: .NET Core 3.1

**Comment by gofal** [comment]
So this is an documentation issue.
The solution is simple: to have both, the imaging and the decoding, just add both services to the DI container:

    new DicomSetupBuilder()
           .RegisterServices(s =>   
                s.AddFellowOakDicom()
                  .AddTranscoderManager<FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager>()
                  .AddImageManager<ImageSharpImageManager>())
           .SkipValidation()
           .Build();

Fo-dicom is using a dependency injection container to retrieve services. It is kind of nature of DI containers to have multiple different services registered in parallel. Of course i would like to make the readme better understandable for beginners, but still the focus has to be on fo-dicom and not on dependency injection in general.

Do you have a suggestion? What would a better read.me look like?

**Comment by AJohnson2ACR** [comment]
> Do you have a suggestion? What would a better read.me look like?

This is a really good question. I will give your suggestion an try and see if I can come up with some ideas. Please give me a couple of days.

**Comment by AJohnson2ACR** [comment]
Apologies for the late response, things have been really busy. But your suggestions worked.

**Comment by mrodc** [comment]
Hello @gofal, your code made my day and week. 
[gofal](https://github.com/gofal) commented [on Dec 9, 2021](https://github.com/fo-dicom/fo-dicom/issues/1280#issuecomment-989574363)

**Comment by dash-bhavinbhesaniya** [comment]
@gofal Thank you so so much for your solutiuon. Its works for me in .Net 6.0 for extract image from DICOM(DCM). after adding  both services to the DI container it works fine.

**Comment by IMRAN-5740** [comment]
new DicomSetupBuilder()
       .RegisterServices(s =>   
            s.AddFellowOakDicom()
              .AddTranscoderManager<FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager>()
              .AddImageManager<ImageSharpImageManager>())
       .SkipValidation()
       .Build();
The type or namespace name 'NativeCodec' does not exist in the namespace 'FellowOakDicom.Imaging' (are you missing an assembly reference?)
Please resolve.

**Comment by gofal** [comment]
> new DicomSetupBuilder() .RegisterServices(s => s.AddFellowOakDicom() .AddTranscoderManager<FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager>() .AddImageManager()) .SkipValidation() .Build(); The type or namespace name 'NativeCodec' does not exist in the namespace 'FellowOakDicom.Imaging' (are you missing an assembly reference?) Please resolve.

The compiler already gave you the right hint: "are you missing an assembly reference?"
See here on the start page: https://github.com/fo-dicom/fo-dicom?tab=readme-ov-file#nuget-packages
these are the packages, hat you might need, depending on what you want do develop. You are missing the fo-dicom.Codec package, when you want to add a TranscoderManager.

**Comment by IMRAN-5740** [comment]
is it need to install into npm
 fo-dicom.Codec package?

**Comment by IMRAN-5740** [comment]
[HttpGet("DICOMtoJPEG")]
public IActionResult ConvertDicomAccurate([FromQuery] string format =
"jpeg")
{
    string dicomPath =
Path.Combine(@"H:\data\12933\1.2.410.200018.109.1.10.3025.3334.20250528211845000_0002_000001_17484462260014.dcm");
    if (!System.IO.File.Exists(dicomPath))
        return NotFound("DICOM file not found.");

    try
    {
        var dicomFile = DicomFile.Open(dicomPath);
        var dataset = dicomFile.Dataset;

        var pixelData = DicomPixelData.Create(dataset);
        var pixels = pixelData.GetFrame(0).Data;

        double slope =
dataset.GetValueOrDefault<double>(DicomTag.RescaleSlope, 0, 1.0);
        double intercept =
dataset.GetValueOrDefault<double>(DicomTag.RescaleIntercept, 0, 0.0);
        double windowCenter =
dataset.GetValueOrDefault<double>(DicomTag.WindowCenter, 0, 40.0);
        double windowWidth =
dataset.GetValueOrDefault<double>(DicomTag.WindowWidth, 0, 400.0);

        int width = pixelData.Width;
        int height = pixelData.Height;
        byte[] outputPixels = new byte[width * height];

        double minValue = double.MaxValue;
        double maxValue = double.MinValue;

        if (windowWidth <= 0)
        {
            // Auto min/max
            for (int i = 0; i < pixels.Length; i += 2)
            {
                ushort val = BitConverter.ToUInt16(pixels, i);
                double scaled = val * slope + intercept;
                minValue = Math.Min(minValue, scaled);
                maxValue = Math.Max(maxValue, scaled);
            }

            // Prevent zero division
            if (Math.Abs(maxValue - minValue) < 1e-6)
            {
                maxValue = minValue + 1;
            }
        }

        for (int i = 0; i < pixels.Length; i += 2)
        {
            ushort pixelValue = BitConverter.ToUInt16(pixels, i);
            double rescaled = pixelValue * slope + intercept;

            byte processedValue;
            if (windowWidth <= 0)
            {
                processedValue = (byte)((rescaled - minValue) * 255 /
(maxValue - minValue));
            }
            else
            {
                double lower = windowCenter - windowWidth / 2;
                double upper = windowCenter + windowWidth / 2;
                processedValue = (byte)(255 * Math.Max(0, Math.Min(1,
(rescaled - lower) / windowWidth)));
            }

            outputPixels[i / 2] = processedValue;
        }

        using var image =
SixLabors.ImageSharp.Image.LoadPixelData<L8>(outputPixels, width, height);
        using var ms = new MemoryStream();

        if (format.Equals("png", StringComparison.OrdinalIgnoreCase))
        {
            image.SaveAsPng(ms);
            return File(ms.ToArray(), "image/png");
        }
        else
        {
            image.SaveAsJpeg(ms);
            return File(ms.ToArray(), "image/jpeg");
        }
    }
    catch (Exception ex)
    {
        return StatusCode(500, $"Error: {ex.Message}");
    }
}[image: 1d48ea63-657f-4672-a5b3-fce9c091e111.jpeg]
What is the issues actually
my code was working previously but now this condition why ? iam very
frustrated.
using FellowOakDicom;
using FellowOakDicom.Imaging;
using Microsoft.AspNetCore.Mvc;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using System.Drawing.Imaging;
my project reference

**Comment by IMRAN-5740** [comment]
please reply dear

**Comment by IMRAN-5740** [comment]
thank you so much dear its working now after use of Native
