### ISSUE TITLE
Can dicom create dcm file from .mov extension ?

### ISSUE THREAD

**Issue by Dash-Uttam** [fo-dicom/fo-dicom#1293]
Hello @all,

I am creating a Dicom file from the video. I am using webm extension video file and I am able to create Dicom files from it successfully. Now I have a requirement to create a Dicom file from the MOV video extension but it is not playing in the Orthanc server, So please help me with that.

Thanks.

**Comment by Dash-Uttam** [comment]
> 

@gofal Please If you can help me with this?

**Comment by gofal** [comment]
What have you tried so far? If you searched in this github project for video-to-dicom coversion, then you might have found this issue: #1007. There was a very similar question, and the answer is the same: DICOM only supports multiframe (having a full bitmap for each video-frame as stack of bitmaps) or some very specific sort of mp4-compression.
Converting between video-formats is out of scope of fo-dicom

**Comment by Dash-Uttam** [comment]
> What have you tried so far? If you searched in this github project for video-to-dicom coversion, then you might have found this issue: #1007. There was a very similar question, and the answer is the same: DICOM only supports multiframe (having a full bitmap for each video-frame as stack of bitmaps) or some very specific sort of mp4-compression. Converting between video-formats is out of scope of fo-dicom

Okay, I am sending my code here, If you can find a better idea.                    

                    var inputFile = dicomModel.UploadMediaModel.Files[0].FileName;
                    DicomDataset ds = new DicomDataset(DicomTransferSyntax.MPEG4AVCH264HighProfileLevel41);
                    ds.AddOrUpdate(DicomTag.BitsAllocated, (ushort)8);

                    if (StudyID.Any() && !string.IsNullOrEmpty(StudyID[0]))
                    {
                        ds.Add(DicomTag.StudyInstanceUID, StudyID[0]);
                        ds.Add(DicomTag.SeriesInstanceUID, DicomUID.Generate());
                        ds.Add(DicomTag.PatientID, PID[0]);
                        ds.Add(DicomTag.AccessionNumber, AcnNumber[0]);
                    }
                    else
                    {
                        ds.Add(DicomTag.StudyInstanceUID, DicomUID.Generate());
                        ds.Add(DicomTag.SeriesInstanceUID, DicomUID.Generate());
                        ds.Add(DicomTag.PatientID, patientDetailsModel.PatientId);
                        ds.Add(DicomTag.AccessionNumber, patientDetailsModel.AccessionNumber);
                    }

                    switch (DicomSOPClass)
                    {
                        case "VideoEndoscopicImageStorage":
                            ds.Add(DicomTag.SOPInstanceUID, DicomUID.VLEndoscopicImageStorage);
                            ds.Add(DicomTag.SOPClassUID, DicomUID.VLEndoscopicImageStorage);
                            break;
                        case "VideoMicroscopicImageStorage":
                            ds.Add(DicomTag.SOPInstanceUID, DicomUID.VideoMicroscopicImageStorage);
                            ds.Add(DicomTag.SOPClassUID, DicomUID.VideoMicroscopicImageStorage);
                            break;
                        case "VideoPhotographicImageStorage":
                            ds.Add(DicomTag.SOPInstanceUID, DicomUID.VideoPhotographicImageStorage);
                            ds.Add(DicomTag.SOPClassUID, DicomUID.VideoPhotographicImageStorage);
                            break;
                        case "MultiFrameSingleBitSecondaryCaptureImageStorage":
                            ds.Add(DicomTag.SOPInstanceUID, DicomUID.MultiFrameSingleBitSecondaryCaptureImageStorage);
                            ds.Add(DicomTag.SOPClassUID, DicomUID.MultiFrameSingleBitSecondaryCaptureImageStorage);
                            break;
                        case "MultiFrameGrayscaleByteSecondaryCaptureImageStorage":
                            ds.Add(DicomTag.SOPInstanceUID, DicomUID.MultiFrameGrayscaleByteSecondaryCaptureImageStorage);
                            ds.Add(DicomTag.SOPClassUID, DicomUID.MultiFrameGrayscaleByteSecondaryCaptureImageStorage);
                            break;
                        case "MultiFrameGrayscaleWordSecondaryCaptureImageStorage":
                            ds.Add(DicomTag.SOPInstanceUID, DicomUID.MultiFrameGrayscaleWordSecondaryCaptureImageStorage);
                            ds.Add(DicomTag.SOPClassUID, DicomUID.MultiFrameGrayscaleWordSecondaryCaptureImageStorage);
                            break;
                        case "MultiFrameTrueColorSecondaryCaptureImageStorage":
                            ds.Add(DicomTag.SOPInstanceUID, DicomUID.MultiFrameTrueColorSecondaryCaptureImageStorage);
                            ds.Add(DicomTag.SOPClassUID, DicomUID.MultiFrameTrueColorSecondaryCaptureImageStorage);
                            break;
                    }

                    ds.Add(DicomTag.PatientName, patientDetailsModel.PatientName);
                    ds.Add(DicomTag.PatientSex, patientDetailsModel.Gender);
                    ds.Add(DicomTag.PatientBirthDate, patientDetailsModel.PatientBirthDate);
                    ds.Add(DicomTag.StudyDate, DateTime.Now);
                    ds.Add(DicomTag.StudyTime, DateTime.Now);
                    DicomPixelData pixelData = DicomPixelData.Create(ds, true);

                    FilterGraph graphFilter = new FilterGraph();
                    IGraphBuilder graphBuilder;
                    IMediaSeeking mediaSeek;
                    IVideoWindow mediaWindow;
                    long duration = 0;
                    var height = 0;
                    var width = 0;
                    graphBuilder = (IGraphBuilder)graphFilter;
                    graphBuilder.RenderFile(inputFile, null);
                    mediaSeek = (IMediaSeeking)graphBuilder;
                    mediaWindow = (IVideoWindow)graphBuilder;
                    mediaSeek.GetDuration(out duration);
                    mediaWindow.get_Height(out height);
                    mediaWindow.get_Width(out width);
                    var time = TimeSpan.FromMilliseconds(duration).TotalMilliseconds / 1000;

                    if (Path.GetExtension(inputFile).Equals(".mp4"))
                    {
                        ShellFile shellFile = ShellFile.FromFilePath(inputFile);
                        var mp4Fps = shellFile.Properties.System.Video.FrameRate.Value / 1000;
                        pixelData.NumberOfFrames = Convert.ToInt32(mp4Fps) * Convert.ToInt32(time) / 10000;
                    }
                    else
                    {
                        pixelData.NumberOfFrames = 25 * Convert.ToInt32(time) / 10000;
                    }
                    pixelData.Width = (ushort)width;
                    pixelData.Height = (ushort)height;
                    pixelData.BitsStored = 8;
                    pixelData.SamplesPerPixel = 3;
                    pixelData.HighBit = 7;
                    pixelData.PixelRepresentation = 0;
                    pixelData.PlanarConfiguration = 0;
                    pixelData.PhotometricInterpretation = PhotometricInterpretation.YbrPartial420;
                    ds.AddOrUpdate(DicomTag.NumberOfFrames, pixelData.NumberOfFrames);
                    ds.AddOrUpdate(DicomTag.Columns, pixelData.Width);
                    ds.AddOrUpdate(DicomTag.Rows, pixelData.Height);
                    ds.Add(DicomTag.LossyImageCompression, "01");
                    ds.Add(DicomTag.SpecificCharacterSet, "ISO_IR 100");
                    ds.Add(DicomTag.ConversionType, "SI");
                    ds.Add(DicomTag.Manufacturer, "OmniSuite");
                    ds.AddOrUpdate(DicomTag.BitsAllocated, (ushort)8);
                    ds.AddOrUpdate(DicomTag.InstanceNumber, "1");
                    DicomDataset sqContent = new DicomDataset
                    {
                        { DicomTag.Modality, "OT" },
                        { DicomTag.ScheduledProcedureStepStartDate, DateTime.Now.Date }
                    }; //Content of the sequence

                    DicomSequence sq = new DicomSequence(DicomTag.ScheduledProcedureStepSequence, sqContent); // Create sequence, add content
                    ds.AddOrUpdate(sq);
                    byte[] videoBytes = File.ReadAllBytes(dicomModel.UploadMediaModel.Files[0].FileName);
                    MemoryByteBuffer buffer = new MemoryByteBuffer(videoBytes);
                    pixelData.AddFrame(buffer);
                    DicomFile dicomfile = new DicomFile(ds);
                    dicomfile.FileMetaInfo.TransferSyntax = DicomTransferSyntax.Lookup(DicomUID.MPEG4HP41);
                    dicomfile.Save(fileName);

                    await client.AddRequestAsync(new DicomCStoreRequest(dicomfile));
                    await client.SendAsync();

**Comment by Dash-Uttam** [comment]
@gofal Right now we are recording MOV files using NewTek NDI SDK, We are able to create Dicom files successfully from it. but it is not playing in the Orthanc server.
So is there any CODEC or any other thing that we need to pass?

**Comment by gofal** [comment]
it's just as you can find in the other issue that I referenced.
DICOM defines very very exactly the codecs you can use. You created a DicomDataset with TransferSyntax DicomTransferSyntax.MPEG4AVCH264HighProfileLevel41. The Dataset looks fine to me, but the data that you add in pixeldata has to be really exactly mpeg4 h.264 codec high profile level 4.1 correspoinding to the ITU-T H.264 standard's profile and level specification (https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_10.10.html).
I assume, orthanc uses some kind of deault mp4-renderer to display the video, so if your video uses some slightly other profile then your DICOM-video is invalid, but orthanc would sill render it. At least you must have some mpeg4 h.264 video.

But take a look here https://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_8.7.3.html. DICOM has also definitions for videos in MPEG2 or mpeg4 h.265, maybe you can convert the MOV to one of those better than to a mpeg4 h.264

**Comment by gofal** [comment]
maybe one more sentence to make it more clear: fo-dicom is about handling DICOM Datasets and DICOM communication. Converting beteween various image formats is a very common task in DICOM, but luckily a company Efferent-Health is maintaining some codec project as a plugin to fo-dicom, so that you can easily convert between uncompressed, jpeg-baseline, jpeg-extended, jpeg2k lossy, jpeg2k lossless, jpeg-ls lossy, jpeg-ls lossless, jpeg-lossless image formats.
As you can see here, there is not just only one "jpeg" compression, but DICOM really exactly defines the codec to use and has various different transfersyntaxes defined for each of them.

but when it comes to video-codecs, then this is completely out of scope in fo-dicom. So you have to convert your MOV video into one of the allowed formats first, and then you can start using fo-dicom to create a DICOM file wrapping this converted video. In the line where you read all the videodata `byte[] videoBytes = File.ReadAllBytes(dicomModel.UploadMediaModel.Files[0].FileName);` there you have to read the bytes of the ready converted video file.

**Comment by jaime-olivares** [comment]
Agree with the last comment. DICOM doesn't support .mov, as it will not support many exotic still image formats. 
Thus, this request is out of the scope of fo-dicom or fo-dicom.Codecs.
I think it's best to close this issue.

**Comment by mrbean-bremen** [comment]
Closing as proposed.
