### ISSUE TITLE
Mono support

### ISSUE THREAD

**Issue by jaime-olivares** [fo-dicom/fo-dicom#13]
We should have clear support for Mono, and hence for either Linux and OS X. Do we have already something like that?
I am to start a big project and I need to put some components in Linux-server and OS X-client, besides Windows. I would love to use fo-dicom across all them.
In Linux environments, I see very fuzzy descriptions about how to compile native libraries, but probably we may only provide a single way to compile, let's say, for an intel-64 CPU with a specific compiler. I think that will cover a big percentage of use-cases.

**Comment by anders9ustafsson** [comment]
Thanks Jaime, for posting this request.

I think that Mono support for the C# library should be fairly straightforward, especially if we separate out *NLog* dependency in a separate assembly as discussed in issue #8 .

But I assume you are also interested in full codec support (JPEG etc.), which is included in the _DICOM.Native.*_ libraries?

**Comment by jaime-olivares** [comment]
Hi Anders,
Yes, I am talking indeed about both native and managed source codes.

**Comment by jaime-olivares** [comment]
By the way, MonoDevelop seems to be very suitable to fully support fo-dicom, as it can compile both C++ and C#. And as it supports Nuget as well, you can have a compiled distributions for OS X and Linux.

**Comment by anders9ustafsson** [comment]
Thanks for the additional info, Jaime. If you are able to set up a *MonoDevelop* / *Xamarin Studio* solution for building *fo-dicom* on Linux and/or OSX, we appreciate very much if you make a pull request out of it.

**Comment by jaime-olivares** [comment]
I may have time to research on this around August. Will keep you informed.

**Comment by michaelp** [comment]
Checking the status of things. I will keep you posted

**Comment by michaelp** [comment]
Ok, I have some updates on the Linux build status: 
1) The 'Dicom' project has references and actively uses types from PresentationCore which is not part of the mono distribution. Rendering pipeline must be externalized 
2) native `vcproj` projects are not supported by xbuild / monodevelop

My conclusions and recommendations:
1) to provide support for more active/concurrent development project must be split into orthogonal sub components
2) I would recommend to use cmake as a build system for the native parts of the project

---------------
to illustrate the errors that i have please look at the following build log



michael@ubuntu:~/projects/fo-dicom$ xbuild DICOM.sln
XBuild Engine Version 12.0
Mono, Version 3.2.8.0
Copyright (C) 2005-2013 Various Mono authors

Build started 9/26/2015 9:12:52 PM.
__________________________________________________
/home/michael/projects/fo-dicom/DICOM.sln:  warning : Ignoring vcproj 'libijg8.x86'.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : Ignoring vcproj 'libijg12.x86'.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : Ignoring vcproj 'libijg16.x86'.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : Ignoring vcproj 'libijg8.x64'.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : Ignoring vcproj 'libijg12.x64'.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : Ignoring vcproj 'libijg16.x64'.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : Ignoring vcproj 'DICOM [Native64]'.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : Ignoring vcproj 'DICOM [Native]'.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : /home/michael/projects/fo-dicom/ConsoleTest/ConsoleTest.csproj: ProjectReference '..\DICOM [Native]\x64\DICOM [Native64].vcxproj' is of an unsupported type. Ignoring.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : /home/michael/projects/fo-dicom/ConsoleTest/ConsoleTest.csproj: ProjectReference '..\DICOM [Native]\x86\DICOM [Native].vcxproj' is of an unsupported type. Ignoring.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : /home/michael/projects/fo-dicom/DICOM [Unit Tests]/DICOM [Unit Tests].csproj: ProjectReference '..\DICOM [Native]\x64\DICOM [Native64].vcxproj' is of an unsupported type. Ignoring.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : /home/michael/projects/fo-dicom/DICOM [Unit Tests]/DICOM [Unit Tests].csproj: ProjectReference '..\DICOM [Native]\x86\DICOM [Native].vcxproj' is of an unsupported type. Ignoring.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : /home/michael/projects/fo-dicom/Tools/DICOM Dump/DICOM Dump.csproj: ProjectReference '..\..\DICOM [Native]\x64\DICOM [Native64].vcxproj' is of an unsupported type. Ignoring.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : /home/michael/projects/fo-dicom/Tools/DICOM Dump/DICOM Dump.csproj: ProjectReference '..\..\DICOM [Native]\x86\DICOM [Native].vcxproj' is of an unsupported type. Ignoring.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : /home/michael/projects/fo-dicom/Examples/DICOM Media/DICOM Media.csproj: ProjectReference '..\..\DICOM [Native]\x64\DICOM [Native64].vcxproj' is of an unsupported type. Ignoring.
/home/michael/projects/fo-dicom/DICOM.sln:  warning : /home/michael/projects/fo-dicom/Examples/DICOM Media/DICOM Media.csproj: ProjectReference '..\..\DICOM [Native]\x86\DICOM [Native].vcxproj' is of an unsupported type. Ignoring.

---------------------------

Performing main compilation ...
Compilation failed: 10 error(s), 0 warnings

/home/michael/projects/fo-dicom/DICOM/Imaging/Render/ImageGraphic.cs(10,28): error CS0234: The type or namespace name `Imaging' does not exist in the namespace `System.Windows.Media'. Are you missing an assembly reference?
/home/michael/projects/fo-dicom/DICOM/Imaging/DicomImage.cs(9,28): error CS0234: The type or namespace name `Imaging' does not exist in the namespace `System.Windows.Media'. Are you missing an assembly reference?
/home/michael/projects/fo-dicom/DICOM/Imaging/Render/CompositeGraphic.cs(8,28): error CS0234: The type or namespace name `Imaging' does not exist in the namespace `System.Windows.Media'. Are you missing an assembly reference?
/home/michael/projects/fo-dicom/DICOM/Imaging/Render/IGraphic.cs(6,28): error CS0234: The type or namespace name `Imaging' does not exist in the namespace `System.Windows.Media'. Are you missing an assembly reference?
/home/michael/projects/fo-dicom/DICOM/Imaging/Render/IGraphic.cs(108,3): error CS0246: The type or namespace name `BitmapSource' could not be found. Are you missing an assembly reference?
/home/michael/projects/fo-dicom/DICOM/Imaging/Render/ImageGraphic.cs(34,19): error CS0246: The type or namespace name `BitmapSource' could not be found. Are you missing an assembly reference?
/home/michael/projects/fo-dicom/DICOM/Imaging/Render/ImageGraphic.cs(290,16): error CS0246: The type or namespace name `BitmapSource' could not be found. Are you missing an assembly reference?
/home/michael/projects/fo-dicom/DICOM/Imaging/Render/ImageGraphic.cs(325,24): error CS0246: The type or namespace name `BitmapSource' could not be found. Are you missing an assembly reference?
/home/michael/projects/fo-dicom/DICOM/Imaging/DicomImage.cs(184,10): error CS0246: The type or namespace name `ImageSource' could not be found. Are you missing an assembly reference?
/home/michael/projects/fo-dicom/DICOM/Imaging/Render/CompositeGraphic.cs(152,10): error CS0246: The type or namespace name `BitmapSource' could not be found. Are you missing an assembly reference?

**Comment by anders9ustafsson** [comment]
Many thanks @michaelp for this extensive input. Regarding *Presentation Core*, I wrote the following on [Gitter](https://gitter.im/fo-dicom/fo-dicom?at=560796e32652445532ce6101):

>@michaelp Many thanks for taking a closer look at the *Mono* question. 
>> Ok, I have some updates on the Linux build status:  The 'Dicom' project has references and actively uses types from PresentationCore

>Yes, I am aware of this, and one goal that I have with the ongoing refactoring (although not yet explicitly expressed anywhere) is to add an abstraction layer for the image rendering to facilitate the full adaptation of *fo-dicom* onto various platforms, including *Mono* but also *iOS*, *OS X*, *Android* and the *Universal Windows Platform*, UWP. A first step in this direction was taken in issue #83 / PR #85 , but more work of course remains to be done. I'll file an issue post to keep track of the request.

A new issue has now been posted on this subject, #92 .

When it comes to *CMake*, this also sounds like a very good idea. I am not very experienced with *CMake*, though, does it also support building *.lib*s and *.dll*s for *iOS*, *Android* etc.? Anyway, if you have the time and willingness, please feel free to contribute a *CMake* builiding PR, that would be a welcome addition to the project.

**Comment by anders9ustafsson** [comment]
A separate Mono solution is now provided, with a few example applications, as a result of PR #109. Still missing is transcoding support for compressed image formats.
