### ISSUE TITLE
GetFrame() with width 187 and height 157 shifts to the right on successive frames

### ISSUE THREAD

**Issue by timetogo2** [fo-dicom/fo-dicom#1300]
**Describe the bug**
The DICOM file has transfer syntax JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression, photometric interpretation MONOCHROME2

The frames are 187x157 bytes

I use "DicomDataset imageDataset = DicomCodecExtensions.Clone(dicomDataset, DicomTransferSyntax.ImplicitVRLittleEndian);" to decode the frames

I get the pixel data using "DicomPixelData dicomPixelData = DicomPixelData.Create(imageDataset);"

I use "byte[] frameData = dicomPixelData.GetFrame(frame).Data;" to get the frames in a loop.

The images shift by what appears to be 1 pixel for each frame (0..3599 frames)

Other DICOM viewers read and display the data correctly (Sante, MicroDicom, Synedra).

**To Reproduce**
Read and display images with the supplied DICOM file.

**Expected behavior**
Images should not shift to the right.

**Screenshots or test DICOM files**
DICOM file:
https://drive.google.com/drive/folders/15apc8MyngMUpVvRDCd_ftlLZ92ylY4bv?usp=sharing

**Environment**
Fellow Oak DICOM version: (4.0.7)
OS: (Windows 10 x64)
Platform: (.NET Framework 4.7.1)

**Comment by timetogo2** [comment]
My guess would be that there is a discrepancy between the storage of the frames during conversion to DicomTransferSyntax.ImplicitVRLittleEndian and the fetching of the frames.  The odd sizes I am quite sure has something to do with why.  The frame length is 187 * 157 = 29359 which is also odd.

**Comment by mrbean-bremen** [comment]
Yes, the problem seems to be the conversion to `ImplicitVRLittleEndian`. I just tried it, and the frame size after the conversion is too large by 3600 bytes, meaning that probably a padding byte is inserted after each frame. This explains the shift by one pixel. 
As far as I can see, this happens on decoding using the decoder. As the decoder is provided by `fo-dicom.Codecs`, maybe we should file an issue on their side.

**Comment by mrbean-bremen** [comment]
If I understand this correctly, the padding byte is added in [this line](https://github.com/Efferent-Health/fo-dicom.Codecs/blob/582fb8d5de3167b601c9ad7a85a4b39da86196e0/Codec/DicomJpegCodec.cs#L2352) - which is correct for single frames, but not for multi-frame images, where it seems to be done for each frame.
@gofal - if you agree, we could move this issue to `fo-dicom.Codecs`.

**Comment by timetogo2** [comment]
If you are asking me, then that is fine with me.  Are you going to move the issue?

**Comment by timetogo2** [comment]
As an aside, is what I am doing the recommended method for getting at the actual pixel data?  Is there a more space efficient, such as frame at a time conversion, that I can take advantage of?

**Comment by mrbean-bremen** [comment]
> Is there a more space efficient, such as frame at a time conversion, that I can take advantage of?

Not that I'm aware of, but I'm not familiar enough with the code yet. Maybe @amoerie or @gofal can answer this.

**Comment by mrbean-bremen** [comment]
Transferring an issue to another organization seems not to be possible, I will just write a new one and leave this one for tracking.

**Comment by amoerie** [comment]
> > Is there a more space efficient, such as frame at a time conversion, that I can take advantage of?
> 
> Not that I'm aware of, but I'm not familiar enough with the code yet. Maybe @amoerie or @gofal can answer this.

We mostly use the various implementations of DicomImage.Render for this, where we assume this is the most optimal path.

**Comment by gofal** [comment]
Depending on many various dicomtags the data stored in the file has to be processed first. For example depending on the transfersyntax the data has to be decompressed maybe. Or depending on PhotometricInterpretation the pixels have to be inverted (0 = white) or not (0 = black). Or depending on Rescale Slope and Rescale Interseption there has to be a linear transformation applied on each pixel. Or depending on some LUTs the data can not be interpreted as color value, but has to be interpreted as index of a colortable. etc etc.
if you call the Render method, then fo-dicom takes care about all those things. 
if you for any reason do not care about that, then you can directly access the DicomItem of DicomTag.PixelData and read the content of the buffer.

**Comment by mrbean-bremen** [comment]
Has been [fixed](https://github.com/Efferent-Health/fo-dicom.Codecs/commit/2df33d13a4566bacc5add55608f0115e693440cd) upstream, and is integrated into the [latest relase](https://www.nuget.org/packages/fo-dicom.Codecs/5.1.0). 
@gofal: As far as I can see, we reference `fo-dicom.Codecs` only in `FO-DICOM.Tests` and `FO-DICOM.Dump`, which we can update at some time.
@timetogo2: Please check with  fo-dicom.Codecs 5.1.0, shall be fixed now.

**Comment by mrbean-bremen** [comment]
Closing this as fixed in `fo-dicom.Codecs`, I had verified it locally. Please reopen if you still have issues.
