### ISSUE TITLE
C-Store request dataset read incorrect

### ISSUE THREAD

**Issue by cocosip** [fo-dicom/fo-dicom#1301]
**Describe the bug**
Get values from c-store request return incorrect values.
The correct value is [196,208]
```c#
var dataset = request.Dataset.Clone();
dataset.NotValidated();
var sexBuffer = dataset.GetValues<byte>(DicomTag.PatientSex);
```

**To Reproduce**

Open dicom from local file, the sexBuffer is correct.
```c#
var dicomFile = await DicomFile.OpenAsync("D:\\dicom1.dcm");
var dataset = dicomFile.Dataset.Clone().NotValidated();
var sexBuffer = dataset.GetValues<byte>(DicomTag.PatientSex);
```
Try to read from request file's path (temp path) is correct 
```c#
var dicomFile = await DicomFile.OpenAsync(request.File.File.Name);
var dataset = dicomFile.Dataset.Clone();
dataset.NotValidated();
var sexBuffer = dataset.GetValues<byte>(DicomTag.PatientSex);
```

**Screenshots or DICOM files**
***Read from request dataset, incorrect***
![err](https://user-images.githubusercontent.com/9337837/148332086-0d0ba594-f881-41f9-9c02-061f0acbadbd.png) 

***Read from request.File, incorrect***
![err2](https://user-images.githubusercontent.com/9337837/148332495-6c5b316f-26f1-4962-9bb6-e19f72fd134f.png)

***Read from request temp file is correct***
![11](https://user-images.githubusercontent.com/9337837/148332747-58fe91d3-2353-4fdb-8af0-51c540d092b6.png)

**Environment**
Fellow Oak DICOM version: 5.0.0
OS: Win11
Platform: .net6.0

**Comment by mrbean-bremen** [comment]
Without knowing what the actual concrete problem in the code is: this is an invalid value for `PatientSex`. `PatientSex` has the VR _CS_ and allows only a few ASCII values (M, F and O, I think), while in your case you have 男, meaning male, in Chinese encoding (as Google Translate tells me). As CS values are handled as ASCII and the encoding shall not get applied to these values, this gets probably converted at some stage improperly.

**Comment by cocosip** [comment]
> Without knowing what the actual concrete problem in the code is: this is an invalid value for `PatientSex`. `PatientSex` has the VR _CS_ and allows only a few ASCII values (M, F and O, I think), while in your case you have 男, meaning male, in Chinese encoding (as Google Translate tells me). As CS values are handled as ASCII and the encoding shall not get applied to these values, this gets probably converted at some stage improperly.

The dicom file is not very standard, the `PatientSex` tag store a chinese value `男`.  
Fo-Dicom when receive c-strore request, it will [save](https://github.com/fo-dicom/fo-dicom/blob/development/FO-DICOM.Core/Network/DicomService.cs#L664) dataset to temp , then read dataset from temp file by method [GetCStoreDicomFile](https://github.com/fo-dicom/fo-dicom/blob/development/FO-DICOM.Core/Network/DicomService.cs#L284)

I wonder why request.Dataset , read from request file is different?

**Comment by mrbean-bremen** [comment]
Hm, is there an easy possibility to reproduce this? I can create a test dataset with the offending tag, but I'm not sure how to create the C-STORE request for testing (I tried, but couldn't reproduce the issue, so I obviously did something wrong).

**Comment by cocosip** [comment]
> Hm, is there an easy possibility to reproduce this? I can create a test dataset with the offending tag, but I'm not sure how to create the C-STORE request for testing (I tried, but couldn't reproduce the issue, so I obviously did something wrong).

I found add this line code, the bug will reproduce. I guess WriteToString() method changed the dataset.
```c#
   Logger.Debug("Received N-Delete:{0}.", request.Dataset?.WriteToString());
```

**Comment by mrbean-bremen** [comment]
Thanks, I can confirm this. To reproduce:
```cs
        var dataset = DicomFile.Open("filepath").Dataset;
        var sexBuffer = dataset.GetValues<byte>(DicomTag.PatientSex);
        // buffer is 196, 208
        dataset.WriteToString();
        // buffer is 63, 63
```
In `WriteToString`, the target encoding for the string values is set (in this case `GB18030`). As for CS values, the encoding is originally set to `ASCII`, the code is trying to re-encode the value, assuming that it is encoded in ASCII.
Notwithstanding the fact that this would not happen with valid DICOM data, maybe the code can be changed to handle this case better.
