### ISSUE TITLE
Exception: 'FellowOakDicom.Imaging.DicomImagingException' em fo-dicom.core.dll

### ISSUE THREAD

**Issue by megarockss** [fo-dicom/fo-dicom#1317]
Please i need help with this error.

Starting print SCP server with AET: PRINTSCP on port 8000
Press any key to stop the service
[INFO] WEASIS_AE <- Association request:
Calling AE Title:       WEASIS_AE
Called AE Title:        PRINTSCP
Remote host:            192.168.88.169
Remote port:            55104
Implementation Class:   Implementation Class UID [1.2.40.0.13.1.3]
Implementation Version: dcm4che-5.24.2
Maximum PDU Length:     16378
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] Received association request from AE: WEASIS_AE with IP: 192.168.88.169
[INFO] Accepted association request from WEASIS_AE
[INFO] WEASIS_AE -> Association accept:
Calling AE Title:       WEASIS_AE
Called AE Title:        PRINTSCP
Remote host:            192.168.88.169
Remote port:            55104
Implementation Class:   Implementation Class UID [1.2.40.0.13.1.3]
Implementation Version: dcm4che-5.24.2
Maximum PDU Length:     16378
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] WEASIS_AE <- N-Create request [1]
[INFO] Create new film session 2.25.43369002965375377547447458353885123418
[INFO] WEASIS_AE -> N-Create response [1]: Success
[INFO] WEASIS_AE <- N-Create request [2]
[INFO] Applying display format STANDARD\1,1 for film box Unknown [2.25.193497880471278022723684129141826792891]
[INFO] Created new film box 2.25.193497880471278022723684129141826792891
[INFO] WEASIS_AE -> N-Create response [2]: Success
[INFO] WEASIS_AE <- N-Set request [3]
[INFO] Set image box 2.25.193497880471278022723684129141826792891.1
[INFO] WEASIS_AE -> N-Set response [3]: Success
[INFO] WEASIS_AE <- N-Action request [4]
                Action Type:    0001
[INFO] Creating new print job for film box 2.25.193497880471278022723684129141826792891
[INFO] Print Job 147962443662677333917205416075102238014 Status Pending: QUEUED
[INFO] WEASIS_AE -> N-Action response [4]: Success
                Action Type:    0001
[INFO] Print Job 147962443662677333917205416075102238014 Status Printing: QUEUED
[INFO] WEASIS_AE <- N-Delete request [5]
[INFO] WEASIS_AE -> N-Delete response [5]: Success
[INFO] WEASIS_AE <- N-Delete request [6]
[INFO] WEASIS_AE -> N-Delete response [6]: Success
[INFO] WEASIS_AE <- Association release request
[INFO] WEASIS_AE -> Association release response
[INFO] Connection closed
[INFO] Print Job 147962443662677333917205416075102238014 Status Printing: NORMAL
Error:FellowOakDicom.Imaging.DicomImagingException: Cannot cast to 'Image'; type must be assignable from 'Byte[]'
   em FellowOakDicom.Imaging.ImageBase`1.As[T]()
   em FellowOakDicom.Printing.ImageBoxExtensions.Print(ImageBox imageBox, Graphics graphics, RectF box, Int32 imageResolution)
   em FellowOakDicom.Printing.FilmBoxExtensions.Print(FilmBox filmBox, Graphics graphics, Rectangle marginBounds, Int32 imageResolution)
   em FellowOakDicom.Samples.Printing.PrintJob.OnPrintPage(Object sender, PrintPageEventArgs e) na D:\Leandro\fo-dicom-samples-master\Desktop\Print SCP\PrintJob.cs:linha 315
   em System.Drawing.Printing.PrintDocument.OnPrintPage(PrintPageEventArgs e)
   em System.Drawing.Printing.PrintDocument._OnPrintPage(PrintPageEventArgs e)
   em System.Drawing.Printing.PrintController.PrintLoop(PrintDocument document)
   em System.Drawing.Printing.PrintController.Print(PrintDocument document)
   em System.Drawing.Printing.PrintDocument.Print()
   em FellowOakDicom.Samples.Printing.PrintJob.DoPrint() na D:\Leandro\fo-dicom-samples-master\Desktop\Print SCP\PrintJob.cs:linha 280
[ERROR] Print Job 147962443662677333917205416075102238014 Status Failure: UNKNOWN
Stopping print service

****************************
I need to print the document on a laser printer as soon as the service listens for the dicom print

**Comment by megarockss** [comment]
I tried to change it to bmp but the error persists, I must be changing the wrong place in the code.

`
// Copyright (c) 2012-2022 fo-dicom contributors.
// Licensed under the Microsoft Public License (MS-PL).

using FellowOakDicom.Log;
using FellowOakDicom.Printing;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Printing;
using System.IO;
using System.Linq;
using System.Threading;

namespace FellowOakDicom.Samples.Printing
{
public class StatusUpdateEventArgs : EventArgs
{
public ushort EventTypeId { get; private set; }
public string ExecutionStatusInfo { get; private set; }
public string FilmSessionLabel { get; private set; }
public string PrinterName { get; private set; }

    public StatusUpdateEventArgs(
        ushort eventTypeId,
        string executionStatusInfo,
        string filmSessionLabel,
        string printerName)
    {
        EventTypeId = eventTypeId;
        ExecutionStatusInfo = executionStatusInfo;
        FilmSessionLabel = filmSessionLabel;
        PrinterName = printerName;
    }
}

public enum PrintJobStatus : ushort
{
    Pending = 1,

    Printing = 2,

    Done = 3,

    Failure = 4
}


public class PrintJob : DicomDataset
{
    #region Properties and Attributes

    public bool SendNEventReport { get; set; }

    public Guid PrintJobGuid { get; private set; }

    public IList<string> FilmBoxFolderList { get; private set; }

    public Printer Printer { get; private set; }

    public PrintJobStatus Status { get; private set; }

    public string PrintJobFolder { get; private set; }

    public string FullPrintJobFolder { get; private set; }

    public Exception Error { get; private set; }

    public string FilmSessionLabel { get; private set; }

    private int _currentPage;

    private FilmBox _currentFilmBox;

    /// <summary>
    /// Print job SOP class UID
    /// </summary>
    public readonly DicomUID SOPClassUID = DicomUID.PrintJob;

    /// <summary>
    /// Print job SOP instance UID
    /// </summary>
    public DicomUID SOPInstanceUID { get; private set; }

    /// <summary>
    /// Execution status of print job.
    /// </summary>
    /// <remarks>
    /// Enumerated Values:
    /// <list type="bullet">
    /// <item><description>PENDING</description></item>
    /// <item><description>PRINTING</description></item>
    /// <item><description>DONE</description></item>
    /// <item><description>FAILURE</description></item>
    /// </list>
    /// </remarks> 
    public string ExecutionStatus
    {
        get => GetSingleValueOrDefault(DicomTag.ExecutionStatus, string.Empty);
        set => AddOrUpdate(DicomTag.ExecutionStatus, value.ToUpperInvariant());
    }

    /// <summary>
    /// Additional information about Execution Status (2100,0020).
    /// </summary>
    public string ExecutionStatusInfo
    {
        get => GetSingleValueOrDefault(DicomTag.ExecutionStatusInfo, string.Empty);
        set => AddOrUpdate(DicomTag.ExecutionStatusInfo, value.ToUpperInvariant());
    }

    /// <summary>
    /// Specifies the priority of the print job.
    /// </summary>
    /// <remarks>
    /// Enumerated values:
    /// <list type="bullet">
    ///     <item><description>HIGH</description></item>
    ///     <item><description>MED</description></item>
    ///     <item><description>LOW</description></item>
    /// </list>
    /// </remarks>
    public string PrintPriority
    {
        get => GetSingleValueOrDefault(DicomTag.PrintPriority, "MED");
        set => AddOrUpdate(DicomTag.PrintPriority, value);
    }

    /// <summary>
    /// Date/Time of print job creation.
    /// </summary>
    public DateTime CreationDateTime
    {
        get => this.GetDateTime(DicomTag.CreationDate, DicomTag.CreationTime);
        set
        {
            AddOrUpdate(DicomTag.CreationDate, value);
            AddOrUpdate(DicomTag.CreationTime, value);
        }
    }

    /// <summary>
    /// User defined name identifying the printer.
    /// </summary>
    public string PrinterName
    {
        get => GetSingleValueOrDefault(DicomTag.PrinterName, string.Empty);
        set => AddOrUpdate(DicomTag.PrinterName, value);
    }

    /// <summary>
    /// DICOM Application Entity Title that issued the print operation.
    /// </summary>
    public string Originator
    {
        get => GetSingleValueOrDefault(DicomTag.Originator, string.Empty);
        set => AddOrUpdate(DicomTag.Originator, value);
    }

    public ILogger Log { get; private set; }


    public event EventHandler<StatusUpdateEventArgs> StatusUpdate;

    #endregion

    #region Constructors

    /// <summary>
    /// Construct new print job using specified SOP instance UID. If passed SOP instance UID is missing, new UID will
    /// be generated
    /// </summary>
    /// <param name="sopInstance">New print job SOP instance uID</param>
    public PrintJob(DicomUID sopInstance, Printer printer, string originator, ILogger log)
        : base()
    {
        Log = log;

        SOPInstanceUID = string.IsNullOrEmpty(sopInstance?.UID) ? DicomUID.Generate() : sopInstance;

        Add(DicomTag.SOPClassUID, SOPClassUID);
        Add(DicomTag.SOPInstanceUID, SOPInstanceUID);

        Printer = printer ?? throw new ArgumentNullException(nameof(printer));

        Status = PrintJobStatus.Pending;

        PrinterName = Printer.PrinterAet;

        Originator = originator;

        if (CreationDateTime == DateTime.MinValue)
        {
            CreationDateTime = DateTime.Now;
        }

        PrintJobFolder = SOPInstanceUID.UID;

        var receivingFolder = Path.Combine(Environment.CurrentDirectory, "PrintJobs");

        FullPrintJobFolder = Path.Combine(receivingFolder, PrintJobFolder);

        FilmBoxFolderList = new List<string>();
    }

    #endregion

    #region Printing Methods

    public void Print(IList<FilmBox> filmBoxList)
    {
        try
        {
            Status = PrintJobStatus.Pending;

            OnStatusUpdate("QUEUED");

            var printJobDir = new DirectoryInfo(FullPrintJobFolder);
            if (!printJobDir.Exists)
            {
                printJobDir.Create();
            }

            DicomFile file;
            int filmsCount = FilmBoxFolderList.Count;
            for (int i = 0; i < filmBoxList.Count; i++)
            {
                var filmBox = filmBoxList[i];
                var filmBoxDir = printJobDir.CreateSubdirectory(string.Format("F{0:000000}", i + 1 + filmsCount));

                file = new DicomFile(filmBox.FilmSession);
                file.Save(Path.Combine(filmBoxDir.FullName, "FilmSession.dcm"));

                FilmBoxFolderList.Add(filmBoxDir.Name);
                filmBox.Save(filmBoxDir.FullName);
            }

            FilmSessionLabel = filmBoxList.First().FilmSession.FilmSessionLabel;

            var thread = new Thread(new ThreadStart(DoPrint))
            {
                Name = $"PrintJob {SOPInstanceUID.UID}",
                IsBackground = true
            };
            thread.Start();
        }
        catch (Exception ex)
        {
            Error = ex;
            Status = PrintJobStatus.Failure;
            OnStatusUpdate("UNKNOWN"); // The exception may be analyzed and a more proper code as defined in "Table C.13.9.1-1. Defined Terms for Printer and Execution Status Info" may be used
            DeletePrintFolder();
        }
    }

    private void DoPrint()
    {
        PrintDocument printDocument = null;
        try
        {
            Status = PrintJobStatus.Printing;
            OnStatusUpdate("QUEUED");

            var printerSettings = new PrinterSettings
            {
                PrinterName = "HP2734C8",
                //PrintToFile = true,
                //PrintFileName = Path.Combine(FullPrintJobFolder, SOPInstanceUID.UID + ".xps")
            };

            printDocument = new PrintDocument
            {
                PrinterSettings = printerSettings,
                DocumentName = Thread.CurrentThread.Name,
                PrintController = new StandardPrintController()
            };

            printDocument.QueryPageSettings += OnQueryPageSettings;
            printDocument.PrintPage += OnPrintPage;

            printDocument.Print();

            Status = PrintJobStatus.Done;

            OnStatusUpdate("NORMAL");
        }
        catch (Exception e)
        {
            Console.WriteLine("Error:"+e );
            Status = PrintJobStatus.Failure;
            OnStatusUpdate("UNKNOWN"); // The exception may be analyzed and a more proper code as defined in "Table C.13.9.1-1. Defined Terms for Printer and Execution Status Info" may be used
        }
        finally
        {
            if (printDocument != null)
            {
                //dispose the print document and unregister events handlers to avoid memory leaks
                printDocument.QueryPageSettings -= OnQueryPageSettings;
                printDocument.PrintPage -= OnPrintPage;
                printDocument.Dispose();
            }
        }
    }

    private void OnPrintPage(object sender, PrintPageEventArgs e)
    {
        /* _currentFilmBox.Print(e.Graphics, e.MarginBounds, 100);

         _currentFilmBox = null;
         _currentPage++;

         e.HasMorePages = _currentPage < FilmBoxFolderList.Count;*/
        var bmp = new Bitmap(e.PageBounds.Width, e.PageBounds.Height);
        using (var bmpGraphics = Graphics.FromImage(bmp))
        {
            _currentFilmBox.Print(bmpGraphics, e.MarginBounds, 100);
            Console.WriteLine("teste");
        }

        // then here you do your manipulations on bmp

        // now draw your adjusted bitmap on the printer
        e.Graphics.DrawImage(bmp, 0, 0);

        _currentFilmBox = null;
        _currentPage++;

        e.HasMorePages = _currentPage < FilmBoxFolderList.Count;
    }

    private void OnQueryPageSettings(object sender, QueryPageSettingsEventArgs e)
    {
        OnStatusUpdate($"NORMAL");
        var filmBoxFolder = Path.Combine(FullPrintJobFolder, FilmBoxFolderList[_currentPage]);
        var filmSession = FilmSession.Load(Path.Combine(filmBoxFolder, "FilmSession.dcm"));
        _currentFilmBox = FilmBox.Load(filmSession, filmBoxFolder);

        e.PageSettings.Margins.Left = 25;
        e.PageSettings.Margins.Right = 25;
        e.PageSettings.Margins.Top = 25;
        e.PageSettings.Margins.Bottom = 25;

        e.PageSettings.Landscape = _currentFilmBox.FilmOrientation == "LANDSCAPE";
    }

    private void DeletePrintFolder()
    {
        var folderInfo = new DirectoryInfo(FullPrintJobFolder);
        if (folderInfo.Exists)
        {
            folderInfo.Delete(true);
        }
    }

    #endregion

    #region Notification Methods

    protected virtual void OnStatusUpdate(string info)
    {
        ExecutionStatus = Status.ToString();
        ExecutionStatusInfo = info;

        if (Status != PrintJobStatus.Failure)
        {
            Log.Info("Print Job {0} Status {1}: {2}", SOPInstanceUID.UID.Split('.').Last(), Status, info);
        }
        else
        {
            Log.Error("Print Job {0} Status {1}: {2}", SOPInstanceUID.UID.Split('.').Last(), Status, info);
        }
        StatusUpdate?.Invoke(this, new StatusUpdateEventArgs((ushort)Status, info, FilmSessionLabel, PrinterName));
    }

    #endregion

}
}

`

**Comment by gofal** [comment]
This error comes, when the PrintJob wants to render the image and convert it into a System.Drawing.Image. But therefore the WinformsImageManager has to be registered.
Just like described here: https://github.com/fo-dicom/fo-dicom#image-rendering-configuration
Please initialize your FellowOakDicom Setup when starting the application.

**Comment by megarockss** [comment]
I love you Brow, It worked. Sorry me, i am only brazilian student ^^.
I'm studying programming in the area of ​​medical software. I hope I can count on you for any doubts that may arise regarding Dicom.
Thank you friend.
