### ISSUE TITLE
DicomServer stuck in infinite loop in C-move when forced close of client connection

### ISSUE THREAD

**Issue by p33215** [fo-dicom/fo-dicom#1319]
When doing a CMOVE and forcibly killing the client, the DicomServer get stuck in an infinite loop and logs warnings, (got about 500/s, killing the diskspace...) until you restart the server process. It happened every attempt so far (i.e. reproducable locally).

**Versions:**
Fellow Oak DICOM version 5.0.2
OS: Windows 10

The code issue seems to be empty 'runningDicomServiceTasks' causing exception and infinite while loop in:
```cs
private async Task RemoveUnusedServicesAsync(){
 while (!_cancellationToken.IsCancellationRequested){
......
            await Task.WhenAny(runningDicomServiceTasks).ConfigureAwait(false);
......
               catch (Exception e)
                {
                    Logger.Warn("Exception removing disconnected clients, {@error}", e);
                }
......
 }
}
```
**From the log trace:**
```
"@timestamp": "2022-02-01T14:04:53.5028649Z", "Level": "Info", "Message": "DIMSETester -> C-Move response [1]: Pending\n\t\tCompleted:\t1\n\t\tRemaining:\t939\n\t\tFailures:\t7", "Host": "SE-00197-WKS", "Logger": "FellowOakDicom.Network", "Thread": "20" }

{ "@timestamp": "2022-02-01T14:04:53.5028649Z", "Level": "Info", "Message": "Socket error while writing PDU: ConnectionReset [10054]", "Host": "SE-00197-WKS", "Logger": "FellowOakDicom.Network", "Thread": "20" }

{ "@timestamp": "2022-02-01T14:04:53.5028649Z", "Level": "Info", "Message": "Connection closed", "Host": "SE-00197-WKS", "Logger": "FellowOakDicom.Network", "Thread": "20" }

{ "@timestamp": "2022-02-01T14:04:53.6218665Z", "Level": "Info", "Message": "Socket error while reading PDU: ConnectionReset [10054]", "Host": "SE-00197-WKS", "Logger": "FellowOakDicom.Network", "Thread": "20" }

{ "@timestamp": "2022-02-01T14:04:53.6418551Z", "Level": "Warn", "Message": "Exception removing disconnected clients, System.ArgumentException: The tasks argument contains no tasks.\r\nParameter name: tasks\r\n   at System.Threading.Tasks.Task.WhenAny(IEnumerable`1 tasks)\r\n   at FellowOakDicom.Network.DicomServer`1.<RemoveUnusedServicesAsync>d__57.MoveNext()", "Host": "SE-00197-WKS", "Logger": "FellowOakDicom.Network", "Thread": "20", "Exception": "System.ArgumentException: The tasks argument contains no tasks.\r\nParameter name: tasks\r\n   at System.Threading.Tasks.Task.WhenAny(IEnumerable`1 tasks)\r\n   at FellowOakDicom.Network.DicomServer`1.<RemoveUnusedServicesAsync>d__57.MoveNext()    at System.Threading.Tasks.Task.WhenAny(IEnumerable`1 tasks)\r\n   at FellowOakDicom.Network.DicomServer`1.<RemoveUnusedServicesAsync>d__57.MoveNext()" }

[last entry repeated]
```

**Comment by p33215** [comment]
What is actually happening is that the service.Dispose(); in RemoveUnusedServicesAsync() first throws an exception due to failure to dispose (and flush) the stream deeper down:

{ "@timestamp": "2022-02-08T08:14:36.9937182Z", "Level": "Warn", "Message": "Exception removing disconnected clients, System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host\r\n   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)\r\n   --- End of inner exception stack trace ---\r\n   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)\r\n   at System.IO.BufferedStream.Flush()\r\n   at System.IO.BufferedStream.Dispose(Boolean disposing)\r\n   at System.IO.Stream.Close()\r\n   at FellowOakDicom.Network.DicomService.Dispose(Boolean disposing) in 

Because of the exception the flags _hasServicesFlag and _hasNonMaxServicesFlag are not set and the loop repeats until the 
await Task.WhenAny(runningDicomServiceTasks).ConfigureAwait(false);  with empty runningDicomServiceTasks throwing a new exception etc.

This can be fixed by either try-catching the service.Dispose(); or putting a "if not empty" around the await "Task.WhenAny..".

Dispose-methods "should not" throw exceptions according to general MS design rules but I'm not sure how/if possible to avoid this (and the MS code actually does a try-finally at the exception origin).

In any case this issue is a bug and I think the straightforward solution is to use a try-catch around the service.Dispose() operation. But that try-catch has to be put in DicomService.Dispose to not skip the other disposing operations.

**Comment by amoerie** [comment]
Thanks for reporting this! I agree with your fix, and I've also added an extra safeguard in the DicomServer where it checks if there is at least one running DICOM server so Task.WhenAny cannot crash.
