### ISSUE TITLE
DicomClient sends invalid association requests (AE-title too long)

### ISSUE THREAD

**Issue by Nezrahm** [fo-dicom/fo-dicom#1323]
**Describe the bug**
The new (v5) DicomClient creates invalid association request if you provide the DicomClientFactory.Create method with a calling AE-title that's longer than the standard allows.

**To Reproduce**
Use the DicomClientFactory.Create method with a calling AE-title that's longer than the standard allows.
For example try using STORAGECOMMITTEST.

**Expected behavior**
The old (v4) client silently truncated the AE-title to maximum allowed length. I don't really agree with this behaviour either even though it's better.
What I expect from the client is that it throws an exception when trying to make a call with invalid parameters.

**Screenshots or test DICOM files**
![image](https://user-images.githubusercontent.com/8653358/153172258-6e0c1388-2e3a-4233-86ec-f3c65d24df62.png)

**Environment**
Fellow Oak DICOM version: 5.0.2 vs 4.0.7
OS: Windows 10 x64
Platform: .NET Framework 4.8

**Comment by Nezrahm** [comment]
Note that the above request also seems to crash the server (fo-dicom) when it tries to handle the request.

**Comment by gofal** [comment]
In my opinion, the behavior now is better, than it was in version 4. Because if there is an invalid input, then it should fail somehow so that the input gets fixed.

What do you actually get when you run the application? An simple association rejected? or do you get an exception, that gives you some hint about the malformed AETitle?

**Comment by Nezrahm** [comment]
The current behaviour is really bad.

The server throws an exception: FellowOakDicom.Network.DicomNetworkException: Pdu[type=01, length=200] (offset=199, bytes=3, field="Reserved") Requested offset out of range!
   at FellowOakDicom.Network.RawPDU.CheckOffset(Int32 bytes, String name)
   at FellowOakDicom.Network.RawPDU.SkipBytes(String name, Int32 count)
   at FellowOakDicom.Network.AAssociateRQ.Read(RawPDU raw)
   at FellowOakDicom.Network.DicomService.<ListenAndProcessPDUAsync>d__71.MoveNext()

And the client seemingly goes into an infinite loop trying to make requests.
![image](https://user-images.githubusercontent.com/8653358/153199656-563dd24b-9311-4a7f-8fff-d9d7108f48e9.png).

I don't agree that the client should depend on the server to give us a proper error message when the request is clearly invalid/against specification.

**Comment by mrbean-bremen** [comment]
I think it should already be handled in the client, by refusing to send an invalid message (or sanitizing it as was done before). The server may also handle it, but it should handle it just by rejecting the association, not by crashing.

I would say this is a regression compared to the previous behavior.

**Comment by Nezrahm** [comment]
Here is a simple LinqPad script to reproduce this scenario.

If you change the variable to doFail = true then will it use an AE title that's too long. And the result is just a repeating bunch of these:

![image](https://user-images.githubusercontent.com/8653358/154438410-e48f8f6b-c409-4e71-a530-b5ea85c7219c.png)


	<Query Kind="Program">
	  <NuGetReference>fo-dicom</NuGetReference>
	  <Namespace>FellowOakDicom.Network</Namespace>
	  <Namespace>System.Threading.Tasks</Namespace>
	  <Namespace>FellowOakDicom.Log</Namespace>
	  <Namespace>FellowOakDicom.Imaging.Codec</Namespace>
	  <Namespace>FellowOakDicom.Network.Client</Namespace>
	  <Namespace>FellowOakDicom</Namespace>
	</Query>

	async Task Main()
	{
	  var doFail = true;
	  var callingAe = doFail ? "STORAGECOMMITTEST" : "MyClient";
	  const int port = 10107;
	  
	  new DicomSetupBuilder().Build();
	  
	  using var server = DicomServerFactory.Create<Server>(port);
	  
	  var request = new DicomCEchoRequest();
	  request.OnResponseReceived = (rq, rp) => {
		new { rq, rp }.Dump("DicomCEchoResponse");
	  };
	  
	  var client = DicomClientFactory.Create("localhost", port, false, callingAe, "MyServer");
	  await client.AddRequestAsync(request);
	  await client.SendAsync();
	  
	  "Done".Dump();
	}

	public class Server : DicomService, IDicomServiceProvider, IDicomCEchoProvider
	{
	  public Server(
		INetworkStream stream,
		Encoding fallbackEncoding,
		ILogger log,
		ILogManager logManager,
		INetworkManager networkManager,
		ITranscoderManager transcoderManager) :
		base(stream, fallbackEncoding, log, logManager, networkManager, transcoderManager)
	  {
	  }

	  public void OnConnectionClosed(Exception exception)
	  {
		exception.Dump("OnConnectionClosed");
	  }

	  public void OnReceiveAbort(DicomAbortSource source, DicomAbortReason reason)
	  {
		new { source, reason }.Dump("OnReceiveAbort");
	  }

	  public async Task OnReceiveAssociationReleaseRequestAsync()
	  {
		".".Dump("OnReceiveAssociationReleaseRequestAsync");
		await SendAssociationReleaseResponseAsync().ConfigureAwait(false);
	  }

	  public async Task OnReceiveAssociationRequestAsync(DicomAssociation association)
	  {
		new { association }.Dump("OnReceiveAssociationRequestAsync");
		
		foreach (var pc in association.PresentationContexts) {
		  pc.AcceptTransferSyntaxes(pc.GetTransferSyntaxes().First());
		}
		
		await SendAssociationAcceptAsync(association).ConfigureAwait(false);
	  }

	  public Task<DicomCEchoResponse> OnCEchoRequestAsync(DicomCEchoRequest request)
	  {
		return Task.FromResult(new DicomCEchoResponse(request, DicomStatus.Success));
	  }
	}

**Comment by amoerie** [comment]
I think this should be stopped at the earliest possible time, i.e. in DicomClientFactory.
It could be a simple ArgumentException that takes into account the max length of the relevant VR.

**Comment by gofal** [comment]
If we do this strict validation when creating an DicomClient, then take in to Account, that ValueRepresentation AE also only allows uppercase letters. 
Throw an exception when passing AETitles with lowercase letters?

In my experience this is part of "be as tollerant as possible when processing data". if the two participants choosed too long AETitles or AETitles with lower characters then why prohibit that?
If the client took a too long AETitle, while the server does not accept that, then the client has to reconfigure his AETitle anyway. But if the server accepted that too log AET, then why now prohibit that?

If we merge this, then my experience tells me, that we will soon get some issue, to allow longer AETitles. At least that's what I learned when I introduced the validation feature in DicomDataset. Then i had to do a lot of issues where the user can turn this validation off.

Having this very general exception is not so nice, so at least a better exception would be great. But I am unsure to be that strict. If I am the only one with that opinion, then you vote me down. But be aware of that.

**Comment by amoerie** [comment]
Ehm Github doesn't have upvotes or downvotes! 😁

But I think your arguments are reasonable. What would the ideal solution look like then?
We could, at the very least, log a warning if a DicomClient is made with an invalid calling or called AE (lowercase or too long).

Isn't there also a global flag to disable validation? We could throw an exception by default if global validation is enabled, and only log a warning if global validation is disabled, for example.

Also, can you give an example what you mean exactly by "a better exception"?

**Comment by gofal** [comment]
There are two different spots. If the client passed a too long AETitle (thats where in the PR the argument validation is done) then fo-dicom still works without problems. But fo-dicoms DicomServer throws this "Requested offset out of length" exception if there is a too long value. i meant, that our dicomserver could throw a nicer excpetion, like "value does not validate AE size limit" or so.

**Comment by mrbean-bremen** [comment]
Upvote 👍 
Downvote 👎 
😁 

I think there is a difference between incorrect characters in a tag (we should certainly be able to handle this, and the most that we should do here is to issue a warning), and an incorrect tag length. The latter may have a potential security impact, if the receiver does expect a certain maximum length (consider very large tags), so I would consider the previous behavior in this case. At the very least I would only allow a maximum length that is a bit longer than the allowed length, though this is debatable. 

For the server probably the same should be true. 

> We could throw an exception by default if global validation is enabled, and only log a warning if global validation is disabled, for example.

Agreed, this is actually what I would expect. This is what pydicom does, by the way.

**Comment by Nezrahm** [comment]
There are some problems here. 

1. First of I think that the length is a much bigger issue than casing because the DICOM protocol has fixed length for these fields so there is no easy way for a server to parse that?
2. The server (as per the example above) does receive a call to `OnConnectionClosed(Exception exception)` when this happens but the connection to the client is simply dropped and the client is not informed. The fo-dicom client then (endlessly?) repeats the connection attempt. This is not a good situation.

**Comment by gofal** [comment]
1) well, agree.
So the most secure would be to throw an exception in DicomClientFactory (as done in the PR) AND revert the commit [956d1bf77c30460e014b76cc2cd8bbe1dbd29e68](https://github.com/fo-dicom/fo-dicom/commit/956d1bf77c30460e014b76cc2cd8bbe1dbd29e68) which introduced this regression, in case someone creates a dicomclient directly withou the factory,

**Comment by Nezrahm** [comment]
That is arguably enough.

Is there a rational behind not informing the client about the error? I'm guessing that it could be argued that it's a protection against some form of DOS attack, not sure though if that's the case or if it's even a good argument.

**Comment by gofal** [comment]
I guess there is no rational behind that. But I have to dig into the server-code first, to see how to inform the client. Do you have an idea? some Pull Request :-) ?
