### ISSUE TITLE
JPEG BAsline codec not registered on some WIn 10 pcs

### ISSUE THREAD

**Issue by EdwardMarcus** [fo-dicom/fo-dicom#1326]
**Describe the bug**
Jpeg transfer syntax images wont render on some win 10 pcs.

**To Reproduce**
exception  "No codec registered fro transfer syntax JPEG baseline" raised on call to 'transcoder.decodepixeldata'

**Expected behavior**
Expecting standard jpeg decoding result seen on other pcs. Error occurs for all jpeg baseline tx files

**Environment**
Fo dicom 3.02 compiled in Net framework 4.5.2  for x86 cpu.
Problematic OS is win 10 (assuming it is 64 bit)

**Comment by amoerie** [comment]
> Fo dicom 3.02 compiled in Net framework 4.5.2 for x86 cpu.

Dude. That's a release from 21 Apr 2017. This is an open source library supported by maintainers with their free time.

Please update your application to the latest 4.x release (this is still .NET Framework compatible) and try again.

**Comment by EdwardMarcus** [comment]
Thank you Alexander and all fodicom contributors. I will try your valuable suggestion to implement the update. Please let me know in what way I might be able to support your important contributions to the toolkits community.

Sincerely,
Edward Marcus
Principal Research Software Engineer
Boston Children's Hospital
________________________________________

**Comment by amoerie** [comment]
Hi Edward. I first wanted to apologize for my somewhat abrupt and rude reply. Your politeness stands in contrast to my lack of it. I recognize you're just trying to do your job, and came here to get help. So I will try to be of help.

While updating is definitely the way to go, I can imagine this won't be a painless endeavor if you're 5 years behind. I would advise you to perform this update in small steps (don't jump from 3.0.2 to 4.0.8) and use the release notes to help you with breaking changes.

Until then, maybe we can try to fix your codec problem without having to upgrade. 

Please check that you are not building in AnyCPU and that the host process is running in the correct bitness (32 bit or 64 bit)

See https://github.com/fo-dicom/fo-dicom/issues/874#issuecomment-592128848 for more info

**Comment by EdwardMarcus** [comment]
Alexander,


I am always grateful for your expertise. I will try your suggestion for the upgraded version and let you know what I find.

Regards,

Ed

**Comment by EdwardMarcus** [comment]
Hello Alexander

I tried the 4.08 toolkit- it renders jpeg on my pc, but the other pc still encounters jpeg rendering errors.

If I remain stuck I may need to go with the WPF jpeg decoders.

Thank you,

Ed

**Comment by amoerie** [comment]
Can you enable logging? Specifically, I would wish to see the "Dicom.Imaging.Codec.txt" file that is produced on startup if logging is enabled. (If you are using NLog)

It should look like this:

```
2022-01-10 13:21:10.0843: thread:1 - Debug Searching C:\YOUR_APPLICATION\Dicom.Native*.dll for Dicom codecs
2022-01-10 13:21:10.1023: thread:1 - Debug Codec: JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression
2022-01-10 13:21:10.1023: thread:1 - Debug Codec: JPEG Extended (Process 2 & 4): Default Transfer Syntax for Lossy JPEG 12 Bit Image Compression (Process 4 only)
2022-01-10 13:21:10.1023: thread:1 - Debug Codec: JPEG Lossless, Non-Hierarchical (Process 14)
2022-01-10 13:21:10.1023: thread:1 - Debug Codec: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression
2022-01-10 13:21:10.1023: thread:1 - Debug Codec: JPEG 2000 Image Compression (Lossless Only)
2022-01-10 13:21:10.1023: thread:1 - Debug Codec: JPEG 2000 Image Compression
2022-01-10 13:21:10.1023: thread:1 - Debug Codec: JPEG-LS Lossless Image Compression
2022-01-10 13:21:10.1023: thread:1 - Debug Codec: JPEG-LS Lossy (Near-Lossless) Image Compression
2022-01-10 13:21:10.1023: thread:1 - Debug Codec: RLE Lossless
```

If it says something along the lines of "No codecs found", then that means it cannot load the necessary native DLLs.
The first I would try is to install the latest Visual C++ redistributable binaries.

You can find the installer for that here: https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
Choose x86 if your application is built with 32 bit, or x64 otherwise.
Also verify that when you run the application, it is running in the same bitness.

**Comment by EdwardMarcus** [comment]
I configured v 4.08 with N log and will investigate the method needed to activate the logging.

Your were correct – the jump from 3.02 to 4.08 was painless – only a few enumerations were different. Thanks for that useful hint!

BTW From my exception handling so far I can confirm the JPEG decoder is not registering as expected on the problematic pcs. I will try to confirm this with N log as well.

Since I have some users awaiting results I might also  implement wpf decoding to get things rolling. If that functionality is needed for the toolkit I can share the method.

Thank you again

**Comment by EdwardMarcus** [comment]
Alexander,

On the problematic PC with V 4.08 I have confirmed


1)      No standard JPEG transfer syntaxes are indicted to be registered by the transcoder manager

2)      The WPF JPEG decoder works

When I implement Nlog I will send those results also.

Would it also be suggested to try explicit loading of dlls from the transcoder manager?

Thank you,

Ed

**Comment by amoerie** [comment]
@EdwardMarcus 

You can try to get a .NET stack trace, but at this point it's quite obvious the codecs are not being loaded.

Can you verify

- whether the C++ redistributables are installed
- whether the app is running in the same bitness

**Comment by EdwardMarcus** [comment]
Hi Alexander,

Thanks for responding.


Can you verify

  *   whether the C++ redistributables are installed – yes the redistributables are installed
  *   whether the app is running in the same bitness – The OS is 64 bit. Both the 32 bit and 64 compiles failed to load the codecs.
I also verified all standard jpeg codecs are not loading.

Ed

**Comment by amoerie** [comment]
In that case something more mysterious is going on.

You could try using http://www.dependencywalker.com/ to see why the DLLs cannot be loaded.

**Comment by EdwardMarcus** [comment]
Thank you

Do you which dll to check - Dicom.core or Dicom.native?

**Comment by amoerie** [comment]
Dicom.Native(64) is the one your project should reference directly and is the one that references the codec DLLs.

**Comment by EdwardMarcus** [comment]
Thank you

I will take a look.

Best Regards

Ed

**Comment by EdwardMarcus** [comment]
Thanks for your inputs so far. I decided to update to the latest version 5.10 . 

I downloaded these NUGET references.
DICOM.NativeCodecs.dll
Fo-Dicom.core.dll
FO dicom imaging desktop.dll

I also include dependency injection tools from microsoft, and registered the Set up Builder.

        Dim dsb As New DicomSetupBuilder()
        dsb.Build()

I am currently still unable to transcode JPEG baseline. 

I'd be most appreciative if there some additional step you can see that I might have missed, and that might be  needed to get the codecs working.

**Comment by EdwardMarcus** [comment]
I succeeded to load the v5 codecs. Here is the method. I am seeing 9 supported codecs. I will now try the decoding.
     
 Dim dsb As New DicomSetupBuilder()
        dsb.RegisterServices(AddressOf RegisterServices)
        dsb.SkipValidation
        dsb.Build()

   Private Sub RegisterServices(s As IServiceCollection)
        s.AddFellowOakDicom.AddTranscoderManager(Of FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager)
    End Sub

**Comment by EdwardMarcus** [comment]
Got the jpeg working in v5.  Thank you!

**Comment by amoerie** [comment]
That's excellent! Thanks for letting us know.
Glad to hear v5 is working for you.
