### ISSUE TITLE
Consider multi-targeting instead of .NET Standard 2.0

### ISSUE THREAD

**Issue by amoerie** [fo-dicom/fo-dicom#1335]
.NET Standard 2.0 was originally created by Microsoft to provide a smooth path for library authors to support .NET Framework and .NET Core simultaneously. That sounds like us, right? 
However, .NET Standard 2.1 dropped support for .NET Framework (which we won't drop for another while) and releases since .NET 5 don't even mention .NET Standard anymore.
It looks like Microsoft is abandoning .NET Standard, and I'm thinking that maybe we should do the same.

The alternative to .NET Standard 2.0 is called multi-targeting, and looks like this:

Replace 

`    
<TargetFramework>netstandard2.0</TargetFramework>
`
with

`    
<TargetFrameworks>net461;netnet5.0</TargetFrameworks>
`

Notice how it says TargetFramework**s** instead of TargetFramework!
Now, why would we do this? Everything works, no?
Well, no, not everything works. See https://andrewlock.net/stop-lying-about-netstandard-2-support/ 
In a nutshell: Microsoft is already dropping support in System.Runtime.CompilerServices.Unsafe for .NET Core versions older than 3.1 because these versions are out of support. 
Even if we decided to keep working with an older version of System.Runtime.CompilerServices.Unsafe, this dependency is also used by ImageSharp, so that means we could also not update that dependency. 
I imagine this problem will get worse in the future, so I believe it would be better for fo-dicom to follow the "supported .NET versions" as  advertised by Microsoft, but including .NET Framework of course.

An extra benefit of this approach is that we could make use of new .NET APIs in .NET 5 and up. Now, with .NET Standard 2.0 we are constrained to what .NET Framework implements, which excludes Span, Memory, etc. We could import a compatibility nuget package that gives us these types, but you would still be missing all of the existing APIs that have been updated to use Span / Memory.
Multi-targeting would allow us to write optimized code for .NET Core and non-optimized code for .NET Framework. Of course, as a downside, this would mean a higher chance of logical differences / bugs between .NET Framework and .NET Core, but perhaps this risk is worth the benefits we would get in .NET Core.

Today (February 24th 2020), that means we would multi-target like this:

`    
<TargetFrameworks>net461;netcoreapp3.1;net5.0;net6.0</TargetFrameworks>
`

In November 2022, .NET 7 will be released, and on December 3d, 2022 support for .NET Core 3.1 will be dropped. (source: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core)
That means we would update our target frameworks to this:

`    
<TargetFrameworks>net461;net5.0;net6.0;net7.0</TargetFrameworks>
`

One thing that I have no experience with is Xamarin / Universal Windows Platform / Unity / ..., so we'd have to check which target frameworks these platforms need to function correctly.

**Comment by aerik** [comment]
From the situation you describe, it kinda sounds like going to multi-targeting is inevitable...?

Regarding

> Multi-targeting would allow us to write optimized code for .NET Core and non-optimized code for .NET Framework. Of course, as a downside, this would mean a higher chance of logical differences / bugs between .NET Framework and .NET Core, but perhaps this risk is worth the benefits we would get in .NET Core.

IMHO, the "higher chance of logical differences / bugs " is NOT worth it - my vote is firmly in the camp that says keeping code simple is a virtue, and I think the only times that it might be worthwhile is in computational intensive operations such as image processing.  Just my 2 cents.

**Comment by amoerie** [comment]
> From the situation you describe, it kinda sounds like going to multi-targeting is inevitable...?

We are not monsters. If Unity requires .NET Standard 2.0 then we simply stay with .NET Standard 2.0 and will have to explicitly document somewhere that we don't (really) support versions older than .NET Core 3.1, even though it was not necessarily our decision to actually drop support for those versions. This decision is being forced on us tbh.

> IMHO, the "higher chance of logical differences / bugs " is NOT worth it - my vote is firmly in the camp that says keeping code simple is a virtue, and I think the only times that it might be worthwhile is in computational intensive operations such as image processing. Just my 2 cents.

This is up to us (which includes you!) to evaluate on a case by case basis. Of course we don't want to riddle the code base with #if NET_5_OR_GREATER statements, but like you say we might do it in some cases where there is a big win for .NET Core.
We do all of the fo-dicom development here in the open on Github, and our process is quite democratic with regards to which changes are actually merged, so feel free to comment on pull requests.

Of course, the end goal eventually is to drop support for .NET Framework entirely which avoids this problem altogether, but you can rest assured that this will not happen this year or even next year.

**Comment by mrbean-bremen** [comment]
Looks like there is no alternative to multi-targeting in the short term, as inconvenient this is, though I think `netstandard2.0` shall still be added as a target for the time being. This will make the transition easier.

**Comment by gofal** [comment]
My opinion is, that support for netstandard2.0 is important for longer time. I see from the article it could be better for dependencies, if there is multitargeting like `<TargetFrameworks>netstandard2.0;netnet5.0</TargetFrameworks>` just so that the compiler can choose the bindings better. 
Adding this multitargeting solves such binding issues, so it is fine. But just because we have multitargeting, that does not mean that we should start introducing #if statements. 

fo-dicom already had this, with a shared project and then several projects per platform. and it was horrible. We did a lot of work to bring this all back together into one project and one codebase. i really want to avoid letting it drift apart again.

introducing things like Span is something that is very basic. so there would be many different places where Spans have to be used. and that means a lot of #if statements in code.

the usage of other higher level features should be solved not by adding conditional compilation in code, but rather via inversion of denpencies (DI). Just like it is with the System.Drawing. To support Bitmaps, we did not use the #if statements, but instead used some internal interface, and in a separate project/nuget-package then implemented this interface.
So I am not sure, which features you are planning to use, but instead of thinking about different codebases, try to consider different nugetpackages.

**Comment by amoerie** [comment]
> fo-dicom already had this, with a shared project and then several projects per platform. and it was horrible. We did a lot of work to bring this all back together into one project and one codebase. i really want to avoid letting it drift apart again.

I completely agree. We should strive to keep everything as simple as possible in one project.

> introducing things like Span is something that is very basic. so there would be many different places where Spans have to be used. and that means a lot of #if statements in code.

For low level APIs that use Span / Memory / ..., for example when reading from or writing to a Stream, I imagine some sort of StreamHelper class that exposes a single API that can be used across fo-dicom, and which contains the necessary "#if" statements internally. That way, these "#if" statements are contained to a single scenario in a single place.

For other APIs, e.g. IAsyncEnumerable, I think we'll have to evaluate on a case by case basis. For example, IAsyncEnumerable was fixable by simply adding a dependency to the Bcl.AsyncInterfaces nuget package.

I do agree that the default answer should be: no "#if" statements unless the benefits are overwhelmingly better than the downsides

> So I am not sure, which features you are planning to use, but instead of thinking about different codebases, try to consider different nugetpackages.

I created this issue not only to be able to use the "latest and greatest" APIs in newer .NET Core versions, but also to try and make it more explicit which platforms we support and test.

.NET Standard 2.0 covers the already obsolete .NET Core 2.1 version, but we don't/shouldn't support this anymore.
As hinted by the blog post of Andrew Lock, I believe more problems will appear because we target .NET Standard 2.0, so we should consider multi targeting instead, even if we don't need a single "#if" statement.

**Comment by amoerie** [comment]
Closing the issue to keep things simple for now..
