### ISSUE TITLE
"Slow" rendering encapsulated frames

### ISSUE THREAD

**Issue by wy2ch** [fo-dicom/fo-dicom#1340]
### Expected behavior
probably down to <100ms for single frame rendering

### Actual behavior
about 300ms for single frame rendering

### Steps to reproduce the behavior
i use below code snippet in my Wpf application :

```csharp
        var dcm = DicomFile.Open(dcmFilePathTbl.Text);
        var dicomImage = new DicomImage(dcm.Dataset);
        Log($"start generating {dicomImage.NumberOfFrames} images");
        Stopwatch sw = new Stopwatch();
        sw.Start();
        //Parallel.For(0, dicomImage.NumberOfFrames, GenerateImage);
        for (int i = 0; i < dicomImage.NumberOfFrames; i++)
        {
               GenerateImage(i);
         }
        sw.Stop();
        Log($"images generating cost {sw.ElapsedMilliseconds} ");

        private void GenerateImage(int frame=0)
        {
            try
            {
                Log($"start generate frame {frame}");
                Stopwatch sw = new Stopwatch();
                sw.Start();
                var image = dicomImage.RenderImage(frame);
                sw.Stop();
                var bmp = image.AsWriteableBitmap();
                
                //var filePath = System.IO.Path.Combine(imageFolder, frame.ToString() + ".jpeg");

                //bmp.Save(filePath, System.Drawing.Imaging.ImageFormat.Jpeg);

                Log($"end generate frame {frame}, cost {sw.ElapsedMilliseconds}");
                //images.Add(filePath);
            }
            catch(Exception ex)
            {
                Log($"error occured generating image for frame {frame}: {ex.Message}");
            }
        }
```
I observed 300ms foreach frame rendering from this line:
```csharp
var image = dicomImage.RenderImage(frame);
```
Also tried with:
 - without encapsulated a single frame rendering cost <100ms
 - use SharedBitmap or ClonedBitmap via WinformImage has same result(encapsulated 300ms, without <100ms)
 
So i want to know is this 300ms still impovable? or I use the wrong way to generating the images?
[rendering slow.zip](https://github.com/fo-dicom/fo-dicom/files/8158522/rendering.slow.zip)

### fo-dicom version and OS/platform
4.0.8 and Win10

**Comment by aerik** [comment]
I am pretty sure DicomImage transcodes frames as needed.  That being the case, rendering an encapsulated frame will always take longer.

FWIW, considering you are rendering multiple frames and transcoding them one at a time, I think the total time to render all frames will be faster if you just transcode the entire dataset at once.

**Comment by EdwardMarcus** [comment]
I am able to render at about 60 frames per second with this method to return the pixels of a specified  frame


 Private Function GetDecodedPixels() As Imaging.Render.IPixelData


        If DS.InternalTransferSyntax.IsEncapsulated Then

          

            Select Case DS.InternalTransferSyntax

                Case DicomTransferSyntax.JPEGProcess1

                    If PreferredToolkitDecoder = JPEGDecoder.FODicom Then
                        Return Transcoder.DecodePixelData(DS, CurrentFrame) 'one line decoder
                    End If


A slow multi-frame render result may also be from a bitmap creation of each individual decoded frame. To speed the render, you can try to create a writable bitmap only for the render of the first frame, and then copy pixels into the writable bitmap on the subsequent frames.

**Comment by wy2ch** [comment]
I do not have sufficient knowledge about low level technical details like the pixel data, jpeg compression, etc.
My final solution is to use NativeTranscoderManager and ImageSharpImageManager, which i guess a specific image type "ImageSharpImage" is used instead of WpfImage or WinformImage.
``` csharp
            new DicomSetupBuilder().RegisterServices(s => s
                .AddTranscoderManager<NativeTranscoderManager>()
                .AddImageManager<ImageSharpImageManager>()).Build();
```
it took about 10ms for single frame rendering, that's absolutely acceptable.
BTW, seems previously the most time consuming operation is happen on a lock statement.
