### ISSUE TITLE
DicomStringElement StringValue property differences between version 4 and 5

### ISSUE THREAD

**Issue by mrsuau627** [fo-dicom/fo-dicom#1341]
**Describe the bug**
We have an application that we are in the process of updating from fo-dicom version 4.0.7 to 5.0.2. In running through tests after the upgrade, we realized a difference in the output of DicomDataset.GetSingleValueOrDefault for a DICOM tag that has a null string value. In 4.0, GetSingleValueOrDefault would return an empty string. In 5.0, it returns null. We downloaded the 5.0 code and ran our project with it and traced it down to FO-DICOM.Core/DicomElement.cs line 137. 
It currently has this check in 5.0:
`if (_value == null && Buffer != null && (Buffer != EmptyBuffer.Value))`

In 4.0 it looks more like this:
`if (_value == null && Buffer != null)`

As a result 5.0 never gets to this code on line 139:
```
                    _value = Buffer == EmptyBuffer.Value
                        ? string.Empty
                        : DicomEncoding.DecodeBytes(Buffer, _bufferEncodings, ValueRepresentation == DicomVR.PN)
                                .TrimEnd((char)ValueRepresentation.PaddingValue);
```
**As you can see in this code, the ternary can never be true anymore so it will never return string.Empty. Was this change intentional to return null instead of string.Empty moving forward?**

**Expected behavior**
When it's an empty buffer, it will return an empty string

**Screenshots or test DICOM files**
If you need a DICOM file for this I can provide one, although it doesn't seem necessary.

**Environment**
Fellow Oak DICOM version: 5.0.2
OS: Windows 10 x64
Platform: .NET Framework 4.7.2

**Comment by amoerie** [comment]
Looks like @gofal encountered this issue and tried to fix it, but it does look like the surrounding if prevents the fix from working indeed. See https://github.com/fo-dicom/fo-dicom/commit/fc6347e30586feacf6152f4a38109906c93839f1

@gofal do you know more about this issue?

**Comment by mrsuau627** [comment]
@gofal do you know if this change was intentional? If it was, we will make a change on our end (an extension method or otherwise) to change the functionality back to how it was. If it was not, would you mind if I submit a pull request to change it?

**Comment by gofal** [comment]
It was not. @mrsuau627, you are welcome to do a pull request - including some unittests to prevent this change of behavior in future :-)

**Comment by amoerie** [comment]
Running into this issue as well now. See the pull request for the fix @mrsuau627
