### ISSUE TITLE
DicomCGetRequest (C-Get) 'NetworkErrorToo many presentation contexts configured for this association!'

### ISSUE THREAD

**Issue by mikhail-rozum** [fo-dicom/fo-dicom#1350]
### Discussed in https://github.com/fo-dicom/fo-dicom/discussions/1349

<div type='discussions-op-text'>

<sup>Originally posted by **mikhail-rozum** March  6, 2022</sup>
Hello!
I try to get dicom studies from PACS server (Orthanc) using fo-dicom package. I managed to get studies from the server. But I faced a problem getting a dicom study which consists of 361 images. 
When I try to send C-Get request to a server, I get an exception at DicomClient.SendAsync() call  FellowOakDicom.Network.DicomNetworkException: 'Too many presentation contexts configured for this association!'
Here it is the code I use to get studies from the server:

```
    public class DicomNetworkProvider
    {
       ........
        public async Task<string> GetStudy(string studyInstanceId)
        {
            var tempDirectory = Path.Combine(Path.GetRandomFileName());
            Directory.CreateDirectory(tempDirectory);

            await this.GetStudy(
                studyInstanceId,
                (dataSet, sopInstanceUid) =>
                {
                    new DicomFile(dataSet).Save(Path.Combine(tempDirectory, sopInstanceUid));
                });

            return tempDirectory;
        }

        private static DicomCFindRequest CreateSeriesRequestByStudyUid(string studyInstanceId)
        {
            var request = new DicomCFindRequest(DicomQueryRetrieveLevel.Series);
            request.Dataset.AddOrUpdate(DicomTag.SeriesInstanceUID, string.Empty);
            request.Dataset.AddOrUpdate(DicomTag.StudyInstanceUID, studyInstanceId);

            return request;
        }

        private static DicomCGetRequest CreateGetStudyRequest(string studyInstanceId, string seriesInstanceId)
        {
            var request = new DicomCGetRequest(studyInstanceId, seriesInstanceId);

            return request;
        }

        private static async Task SendRequest(Func<Task> action)
        {
            try
            {
                await action();
            }
            catch (AggregateException ex)
            {
                var innerMessage = string.Join('\n', ex.InnerExceptions.Select(x => x.Message));
                var message = string.Format(CultureInfo.InvariantCulture, "NetworkError" + innerMessage);
                throw new Exception(message, ex);
            }
            catch (Exception ex)
            {
                throw new Exception(string.Format(CultureInfo.InvariantCulture, "NetworkError" + ex.Message));
            }
        }

        private IDicomClient GetClient()
        {
            var client = DicomClientFactory.Create(this.connectionConfiguration.Host, this.connectionConfiguration.Port, false, this.connectionConfiguration.Modality, "SCP-AE");
            client.NegotiateAsyncOps();
            return client;
        }

        private async Task GetStudy(string studyInstanceId, Action<DicomDataset, string> action)
        {
            var client = this.GetClient();
            var findSeriesRequest = CreateSeriesRequestByStudyUid(studyInstanceId);

            var seriesInstanceId = string.Empty;
            findSeriesRequest.OnResponseReceived = (_, response) =>
            {
                if (response.HasDataset)
                {
                    seriesInstanceId = response.Dataset?.GetSingleValue<string>(DicomTag.SeriesInstanceUID);
                }
            };

            await client.AddRequestAsync(findSeriesRequest);

            await SendRequest(() => client.SendAsync());

            if (string.IsNullOrEmpty(seriesInstanceId))
            {
                throw new Exception("StudyNotFound");
            }

            var getStudyRequest = CreateGetStudyRequest(studyInstanceId, seriesInstanceId);
            client.OnCStoreRequest += (request) =>
            {
                var dataSet = request.Dataset;
                var instUid = dataSet.GetSingleValue<string>(DicomTag.SOPInstanceUID).Trim();

                action(dataSet, instUid);

                return Task.FromResult(new DicomCStoreResponse(request, DicomStatus.Success));
            };

            var pcs = DicomPresentationContext.GetScpRolePresentationContextsFromStorageUids(
            DicomStorageCategory.None,
            DicomTransferSyntax.JPEG2000Lossless,
            DicomTransferSyntax.ExplicitVRLittleEndian,
            DicomTransferSyntax.ImplicitVRLittleEndian,
            DicomTransferSyntax.ExplicitVRBigEndian,
            DicomTransferSyntax.ImplicitVRBigEndian);
            client.AdditionalPresentationContexts.AddRange(pcs);
            await client.AddRequestAsync(getStudyRequest);

           // It throws here
            await SendRequest(() => client.SendAsync());
        }
    }
```

await SendRequest(() => client.SendAsync()); - throws exception

What I do wrong?
Thanks
</div>

**Comment by robertvanommen** [comment]
see: https://groups.google.com/g/comp.protocols.dicom/c/5DrUUA18sEg
i think it might work if you propose less DicomTransferSyntaxes, for example remove the:
DicomTransferSyntax.ExplicitVRBigEndian
DicomTransferSyntax.ImplicitVRBigEndian

**Comment by mikhail-rozum** [comment]
> var pcs = DicomPresentationContext.GetScpRolePresentationContextsFromStorageUids(
>             DicomStorageCategory.None,
>             DicomTransferSyntax.JPEG2000Lossless,
>             DicomTransferSyntax.ExplicitVRLittleEndian,
>             DicomTransferSyntax.ImplicitVRLittleEndian,
>             DicomTransferSyntax.ExplicitVRBigEndian,
>             DicomTransferSyntax.ImplicitVRBigEndian);

I tried to remove all extra Transfer syntaxes, excluding JPEG2000Lossless(which is used in the study I try to get), but exception still throws

**Comment by aerik** [comment]
Mmm... I'm not even sure that GetScpRolePresentationContextsFromStorageUids is necessary, but even so, why are you using DicomStorageCategory.None?  Pretty sure that will generate a zillion presentation contexts for all kinds of non-storage UIDs

**Comment by mikhail-rozum** [comment]
> Mmm... I'm not even sure that GetScpRolePresentationContextsFromStorageUids is necessary, but even so, why are you using DicomStorageCategory.None? Pretty sure that will generate a zillion presentation contexts for all kinds of non-storage UIDs

Yes, you're right. I changed it to DicomStorageCategory.Image, and the exceptions disapeared. But there is another problem: I can't get a study with jpeg compression. I see the following in the log:
```
[DEBUG] [REQUESTING ASSOCIATION] Association is accepted
[DEBUG] [REQUESTING ASSOCIATION] --> [SENDING REQUESTS]
[DEBUG] [SENDING REQUESTS] Sending DICOM requests
[INFO] SCP-AE -> C-Get request [2]
[INFO] SCP-AE <- C-Get response [2]: Cannot understand
                Failures:       1
[DEBUG] [SENDING REQUESTS] All requests are done, going to linger association now...
[DEBUG] [SENDING REQUESTS] --> [LINGERING ASSOCIATION]
[DEBUG] [LINGERING ASSOCIATION] Linger timed out after 50ms, releasing association
[DEBUG] [LINGERING ASSOCIATION] --> [RELEASING ASSOCIATION]
[INFO] SCP-AE -> Association release request
[INFO] SCP-AE <- Association release response
[INFO] Connection closed
[DEBUG] [RELEASING ASSOCIATION] Association release response received, disconnecting...
[DEBUG] [RELEASING ASSOCIATION] --> [COMPLETED]
[DEBUG] [COMPLETED] DICOM client completed without errors
[DEBUG] [COMPLETED] Cleaning up
[DEBUG] [COMPLETED] --> [IDLE]
[DEBUG] [IDLE] No requests to send, staying idle
```
My code works for other raw-data studies, but it says "Cannot understand" for the study with Jpeg compression

**Comment by gofal** [comment]
the "cannot understand" is some general error, that the server delivers. 
Which version of fo-dicom are you using? I made some enhancement some time ago, to make more errorcodes visible in logs and therefore reduce the propability of "cannot understand".

Anyway: even if the server has the images stored in some jpeg compression. if you are sending some presentation contexts and offer only uncompressed transfersyntaxes, then the server has to decompress and send you the decompressed file.

i would consider this as some issue on the server side.

**Comment by mikhail-rozum** [comment]
> the "cannot understand" is some general error, that the server delivers. Which version of fo-dicom are you using? I made some enhancement some time ago, to make more errorcodes visible in logs and therefore reduce the propability of "cannot understand".
> 
> Anyway: even if the server has the images stored in some jpeg compression. if you are sending some presentation contexts and offer only uncompressed transfersyntaxes, then the server has to decompress and send you the decompressed file.
> 
> i would consider this as some issue on the server side.

I tried to remove all DicomTransferSyntax'es excluding DicomTransferSyntax.JPEG2000Lossy which coincides with the original images in the study and it **works fine**. It seems you're right, and Orthanc tries to convert images into one of the TransferSyntaxes, but can't for some reason(probably it's not supported).
Thank you
