### ISSUE TITLE
StopTag not working as expected in DicomReader.Read

### ISSUE THREAD

**Issue by Ed55** [fo-dicom/fo-dicom#136]
If the DicomTag given in the parameter "stop"  of DicomReader.Read() is contained already in a sequence the Reader will stop within this sequence.
This is not (at least my :-)) expected result. Assume a DicomTag.PixelData is already contained in a (private) Tag group 0019 ..
Test: 
use the image uploaded in issue #64 (because I worked on that already)  and try stop tag = DicomTag.InstanceNumber (0020,0013) . Result: you will get no PatientID  (group 0010).
This is not expected as you wanted to stop at a tag in group 0020.

My proposal:
In DicomReader create a private field like int sequenceDepth and initiate it in the constructor with 0.
In ParseValue change (this.stop != null && this._tag.CompareTo(this.stop) >= 0) to 
(this.stop != null && this.sequenceDepth == 0 && this._tag.CompareTo(this.stop) >= 0)
In ParseItemSequenceValue change this.ParseDataset(source); to
     this.sequenceDepth++;
     this.ParseDataset(source);
     this.sequenceDepth--;

I am new to V.2.0.0 135 since 3 hours but familiar with a much more ealder code base.
But I think you got the point and might put it to the right place ...
Thanks for your work.

**Comment by anders9ustafsson** [comment]
Many thanks for bringing up this issue, @Ed55.

I agree that the stop function is rudimentary and could be extended substantially. 

How do other frameworks behave in a case like this? Here you have limited the stop level to sequence depth 0, would it make sense to optionally specify stop depth non-zero in the argument list?

All in all, your suggestion seems like a good improvement and I think it is worthwhile including in 2.0. Are there other opinions in the community?

**Comment by IanYates** [comment]
So the proposal is to have Stop only stop on "root" tags.  I haven't had the need to stop myself so don't know enough of the use-cases unfortunately.  What has it been used on the past?  Is it to handle huge sequences where a chunk of it can be discarded as unimportant?

**Comment by Ed55** [comment]
Sometimes I need to parse hundreds of millions of instances to check consistencies.
Of course you do not want to parse all of it when you just need some major infos, e.g. including group 0020.
I know this is special, but this is my use-case for this functionality.

**Comment by IanYates** [comment]
Fair enough.  I can certainly see the value in being able to short-circuit the parsing process.

We could generalise this a bit and accept a `Func<DicomTag, {some other state}, bool>` into the method.  That Func is called after each tag.  If it returns false then parsing the current sequence is aborted.  The {some other state} could be data such as the parse depth and perhaps other information relevant to the decision to stop.

**Comment by Ed55** [comment]
Thanks, seems to be feasible. My proposal was focused on my use-case only ...

**Comment by anders9ustafsson** [comment]
@Ed55 Just for my understanding: are you currently calling `DicomReader.Read(...)` directly? 

Would it make sense to add the stop tag (and potentially the stop tag predicate suggested by @IanYates) as an optional argument in one or some of the `DicomFile.Open(Async)` overloads?

**Comment by Ed55** [comment]
@anders9ustafsson You are absolutely right, I implemented it (in my modifications of the old code base)  down from DicomFile.Open(Filename / stream ,DicomTag StopTag = null) and implemented a StopTag in the DicomFileReader as well.
Sorry for missing this in my description above, the implementation in the Reader only would not make much sense (for my use-case) if it this option is not available when opening a file.
My starting point was the unexpected stop within sequences.
