### ISSUE TITLE
JPEG Baseline not rendering on win 10 64 bit OS

### ISSUE THREAD

**Issue by EdwardMarcus** [fo-dicom/fo-dicom#1360]
**Describe the bug**
V 5 codecs are initialized with Direct Injection and render JPEG baseline on the development pc. 

**To Reproduce**
The build .exe of the renderer works on the development machine, but not on a deployment pc (win 10 64 bit)

**Expected behavior**
Expect JPEG to render on any win 10 platform

**Screenshots or test DICOM files**
Here is the nlog trace of the render
2022-03-23 10:11:27.1155|INFO|Image_Renderer_QA.LoggerModule|Logger initialized.
2022-03-23 10:11:27.5538|INFO|Image_Renderer_QA.LoggerModule|Initialization : File Read Completed
2022-03-23 10:11:27.6129|INFO|Image_Renderer_QA.LoggerModule|Initialization : Pseudo RGB Windowing Ready
2022-03-23 10:11:27.6129|INFO|Image_Renderer_QA.LoggerModule|Initialization : Transcoder Ready 
2022-03-23 10:11:27.6129|INFO|Image_Renderer_QA.LoggerModule|Initialization :   Pixel Data Pipeline Ready 
2022-03-23 10:11:27.6309|INFO|Image_Renderer_QA.LoggerModule|Initialization Display Rate Ready  
2022-03-23 10:11:27.6309|FATAL|Image_Renderer_QA.LoggerModule|Rendering : Pixel Decoding Error Decoding dataset with transfer syntax: JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression is not supported. See here to get help resolving the reason: https://github.com/fo-dicom/fo-dicom/wiki/Native-codecs-on-.NET

I checked the compile option is set to x64

**Environment**
Fellow Oak DICOM version: (e.g. 5.10)
OS: (e.g. Windows 10 x64)
Platform: (e.g. .NET Framework 4.6.2)
Thank you
Ed

**Comment by EdwardMarcus** [comment]
Have discovered some configuration errors on my part- and will investigate.

**Comment by EdwardMarcus** [comment]
Hello

In my transition to V5 , I am encountering some challenges with Dependency Injections of the setup builder.

Here is the setup code to inject  NativeTranscoderManager, NLogManager, and WPFImageManager into the services collection

	Dim dsb As New DicomSetupBuilder()
        dsb.RegisterServices(AddressOf RegisterServices)
        dsb.SkipValidation
        dsb.Build()


	Private Sub RegisterServices(s As IServiceCollection)
        s.AddFellowOakDicom.AddTranscoderManager(Of FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager)
        s.AddFellowOakDicom.AddLogManager(Of FellowOakDicom.Log.NLogManager)
        s.AddFellowOakDicom.AddImageManager(Of Imaging.WPFImageManager)
	End Sub

Following the build, When I check the services collection only the WPFIMAGEMANAGER seems to be successfully injected. 
Instead of the intended NATIVETRANSCODERMANAGER, the DEFAULTRANSCODERMANAGER resides in the services collection.
Instead of the intended NLOGMANAGER, the CONSOLELOGMANAGER resides in the services collection.  

Would it be possible to indicate if this unexpected result is the result of some coding error on my part?

My rendering technique also relies on access to the transcodermanager, but the services collection appears to be private, so I am wondering how do I access the ITranscodermanager item in the collection?

Thank you,

Ed

**Comment by gofal** [comment]
You should not call the "AddFellowOakDicom()" several times, because this method fills in the default implementations.
so after you called "AddTranscoderManager" and then again "AddFellowOakDicom" then the second call replaces your desired TranscoderManager with the DefaultTranscoderManager. The same is true then for the LoggerManager

you have to call 

    s.AddFellowOakDicom.AddTranscoderManager(of NativeTranscoderManager).AddLogManager(of NLogManager).AddImageManager(of WPFImageManager).

**Comment by EdwardMarcus** [comment]
Thank you!

That worked.

How do I access the ServicesCollection - as it appears to be private?

**Comment by gofal** [comment]
Usually you do not access the service collection later. fo-dicom uses the DI-container that ships with .net core. You can read about how to use it on msdn. 
You are using the service collection at startup to tell fo-dicom which services to use internally. then on Build() fo-dicom generates a service provider from that service collection. 
Currently it is not designed to make that service provider accessible from outside. Where would you require to access the service provider? What is the use case? Maybe I can help you to find an other solution. Else we should think about a way how to make the service provoder accessible from outside.

**Comment by EdwardMarcus** [comment]
For low level access, it would be great to make the services collection public.

For now, with this workaround I am able to access the services from the registration process action sub.

Dim Services As ServiceCollection

Private Sub RegisterServices(s As IServiceCollection)

        s.AddTranscoderManager(Of FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager)
        s.AddLogManager(Of FellowOakDicom.Log.NLogManager)
        s.AddImageManager(Of Imaging.WPFImageManager)

        Services = s

End Sub

I then retrieve the services


        Dim serviceProvider As ServiceProvider = Services.BuildServiceProvider()
        TranscoderManager = serviceProvider.GetRequiredService(Of Imaging.Codec.ITranscoderManager)
        ImageManager = serviceProvider.GetRequiredService(Of Imaging.IImageManager)
        LogManager = serviceProvider.GetRequiredService(Of Log.ILogManager)





So with this technique I just go my first successful jpeg render, and I am encouraged (with more testing to come!)

BTW, in the process, I discovered the DICOM.Native-win-64.dll is not automatically set as a reference from the codecs nugget install package, so I had to find and then manually add the DICOM.Native-win-64.dll to the project references.

I have also published a new paper and referenced fo-dicom contributors. Is there some place I can forward the citation when it is published?

Thanks for everything!

Ed

**Comment by EdwardMarcus** [comment]
One need to access the transcodermanager is to show the  supported codecs.

Public Sub ShowSupportedCodecs()

        Dim syntaxes As New List(Of FellowOakDicom.DicomTransferSyntax)
        syntaxes.Add(FellowOakDicom.DicomTransferSyntax.JPEGProcess1)
        syntaxes.Add(FellowOakDicom.DicomTransferSyntax.JPEGProcess2_4)
        syntaxes.Add(FellowOakDicom.DicomTransferSyntax.JPEGProcess14)
        syntaxes.Add(FellowOakDicom.DicomTransferSyntax.JPEGProcess14SV1)
        syntaxes.Add(FellowOakDicom.DicomTransferSyntax.JPEGLSLossless)
        syntaxes.Add(FellowOakDicom.DicomTransferSyntax.JPEGLSNearLossless)
        syntaxes.Add(FellowOakDicom.DicomTransferSyntax.JPEG2000Lossless)
        syntaxes.Add(FellowOakDicom.DicomTransferSyntax.JPEG2000Lossy)
        syntaxes.Add(FellowOakDicom.DicomTransferSyntax.RLELossless)

        Dim supported As String

        For i = 0 To syntaxes.Count - 1


            If TranscoderManager.HasCodec(syntaxes(i)) Then
                supported = "Yes"
            Else
                supported = "No"
            End If
        Next


    End Sub

**Comment by EdwardMarcus** [comment]
I succeeded with the rendering ion the problematic pc. Many thanks for your assistance. I also figured out to get manager instances. 


For the transcoder this worked.

 Dim transcodermanager As New Imaging.NativeCodec.NativeTranscoderManager

        For i = 0 To syntaxes.Count - 1

            If TranscoderManager.HasCodec(syntaxes(i)) Then
                supported = "Yes"
            Else
                supported = "No"
            End If

        Next

for the logmanager this worked
       Dim NLogManager As Log.ILogManager = Log.NLogManager.Instance
        Dim logger As Log.ILogger = NLogManager.GetLogger("")
