### ISSUE TITLE
New transcoder JPEG Results

### ISSUE THREAD

**Issue by EdwardMarcus** [fo-dicom/fo-dicom#1366]
### Expected behavior
image rendered by a v 5 jpeg baseline codec and image rendered by a wpf jpeg decoder are expected to have very similar results 

### Actual behavior

Checked image is 800 x 600 
With a difference threshold of 2 gray levels out of 255 , only 18 pixels (out of 480000) are different between the  wpf and  fo codec renders.

With a threshold of 5 out of 255 , there are no  differences between  wpf and  fo codec renders.
  
Conclusion : The new fo-jpeg decoding appears to be in agreement with wpf.

**Comment by mrbean-bremen** [comment]
Thanks - so this is not an issue, but an observation? Maybe move it to discussions?

**Comment by EdwardMarcus** [comment]
Yes – an observation. I had seen differences with the previous codecs. Not this time though.

I  was not aware of the discussion section and will move it there.
