### ISSUE TITLE
Add Public Callback for Association OnReceiveAssociationAccept

### ISSUE THREAD

**Issue by 0xLigety** [fo-dicom/fo-dicom#137]
Currently its not possible to get association results if no request is added at the client class.
OnAssociationAccepted Callback is hidden in the DicomUser class. 
PresentationContext results are only in DIMSE service callbacks readable.

My proposal:
1.Quick fix
Add AssociationResult property {get; internal set;} to Client class 
Add at OnReceiveAssociationAccept / Reject -> this.client.AssociationResult = association;
2.
Add Delegate and Callback to  Association  class
Add setAssociation Method to Client class
use callback like

           var assoc = new DicomAssociation(...);

            assoc.OnResponseReceived = (Association asr) 
            {

              foreach(DicomPresentationContext ctx in asr.PresentationContexts)
                {

                    Console.WriteLine(ctx.Result.ToString());

                } 

            };
 
     client.setAssociation(assoc);

I need this feature, therefore I will add the quick fix to my project until their is a decision.

Regards 
0xLigety

**Comment by anders9ustafsson** [comment]
Thanks for reporting, @0xLigety , and for providing these solution suggestions. We'll review the issue as soon as possible.
