### ISSUE TITLE
Saved DICOM file is turqouise and pink

### ISSUE THREAD

**Issue by mrsuau627** [fo-dicom/fo-dicom#1379]
**Describe the bug**
We have an application that anonymizes DICOM data built with fo-dicom 4.0.8. Our main app was recently upgraded to fo-dicom 5.0.2. We noticed that anonymized files coming from the 4.0.8 app appear to render with a turqouise and pink tint in the 5.0.2 app. Other DICOM viewers that we have tried render the files correctly and our app used to render them correctly before upgrading to 5.0.2. Just looking for some insight on whether we are missing something when we are generating these files? Maybe 5.0.2 is stricter on specific settings whereas other viewers don't seem to care? Any guidance is appreciated.

**To Reproduce**
Here is an example file that reproduces the issue. I had to zip it so that github would accept it:
[Turquoise and Pink Tint US Image.zip](https://github.com/fo-dicom/fo-dicom/files/8635776/Turquoise.and.Pink.Tint.US.Image.zip)

Here is some sample code that I whipped up to generate the error:
```
                string dicomPath = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "Turquoise and Pink Tint US Image.dcm");
                var dicomFile = DicomFile.Open(dicomPath);
                var dicomBitmap = new DicomImage(dicomFile.Dataset).RenderImage().AsWriteableBitmap();
                string path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "test.png");
                using (FileStream stream = new FileStream(path, FileMode.Create))
                {
                    PngBitmapEncoder encoder = new PngBitmapEncoder();
                    encoder.Frames.Add(BitmapFrame.Create(dicomBitmap));
                    encoder.Save(stream);
                }
```
Here is what we're seeing instead of the standard black & white image:
![test](https://user-images.githubusercontent.com/12435079/167017592-93d980a9-5d28-4934-8bce-9861ba5975b7.png)

**Environment**
Fellow Oak DICOM version: 4.0.8 and 5.0.2 (see description)
OS: Windows 10 x64
Platform: .NET Framework 4.7.2

**Comment by CeeJayCee** [comment]
**Update: Our issue was caused by the encoding of the JPEG being YBR_FULL_422 but the PhotometricEncoding tag stating it was RGB. Presumably FO-DICOM v5 is now using the PhotometricEncoding tag, whereas in v4 it was using the JPEG header?**

Hello. We are seeing a similar issue.

With a standard CT image, rendering is correct.
With a Secondary Capture using Transfer Syntax 1.2.840.10008.1.2.4.50 | JPEG Baseline (Process 1):Default Transfer Syntax for Lossy JPEG 8-bit Image Compression we get the same weird colouring as above.

We are using .net 6.0 and the ImageSharp image manager.

**Comment by gofal** [comment]
there is a new codec-library handling the decompression in version 5. this may use the PhotometricEncoding.

But to get it right: the values of PhotometricEncoding in the image were wrong (were RGB while sould be YBR_FULL_422). 
So this is not a bug, but it could be an enhancement to ignore PhotometricEncoding and instead always assume YBR_FULL_422 on Transfersyntax JPEG Baseline?

**Comment by mrsuau627** [comment]
Thank you @gofal . I'm guessing that some of the DICOM viewers and maybe even fo-dicom 4.0.8 ignore PhotometricEncoding with this transfer syntax like you said. Sounds like maybe the new codec-library is stricter in this case. 

Thank you for confirming that it's not a bug. In this case, we can update our program that is generating these anonymized DICOM files to YBR_FULL_422 and we should be good. Thanks again
