### ISSUE TITLE
Question:  Can TLS be enabled on the server but not on the client?

### ISSUE THREAD

**Issue by aerik** [fo-dicom/fo-dicom#1389]
So I am tinkering with enabling TLS on the server, and I've got it working if the client also supports TLS, but if the client does not, then ssl.AuthenticateAsServer throws an exception and the communication fails.

Question:  Is it possible to enable TLS on the server, but not require it?  So that a TLS enabled client will use it, but a client without will still work?

**Comment by BobSter3000** [comment]
Hi @aerik, I did this a while back and I used two different Dicom Server instances on two different ports, one secured and the other not.  If I recall, it worked correctly.
