### ISSUE TITLE
Lossless JPEG decoding very slow

### ISSUE THREAD

**Issue by endeavour** [fo-dicom/fo-dicom#1391]
**Describe the bug**
Decoding lossless jpegs is very slow, especially on virtual machines. Takes ~ 12 seconds for a 200mb dicom file in a VM.

**To Reproduce**
Try decoding a decent sized dicom file in a VM.

**Expected behavior**
Should be fast.

**Comment by gofal** [comment]
The time depends on many different factors: speed of IO, cpu available, memory available (if the system has to swap memory) etc.
the absolute time of 12 seconds does not give any hint. Please also use some other software (some free viewer, or similar) and measure the time there.

**Comment by gofal** [comment]
closing the issue due to inactivity. If there is still an issue with latest version of fo-dicom, please reopen this issue and provide actual information.
