### ISSUE TITLE
Null Reference Caused when element is empty

### ISSUE THREAD

**Issue by paulchitsonultromics** [fo-dicom/fo-dicom#1392]
When converting to XML, Get<string> can return a null which causes a Null reference exception to be thrown

 https://github.com/fo-dicom/fo-dicom/blob/4562544b8742c78b7b6dd49f1e47bc7952690ee5/FO-DICOM.Core/Serialization/DicomXML.cs#L129

**Comment by gofal** [comment]
Thanks for posting this issue. Do you have an anonymized sample file for that or some sample code to reproduce?

**Comment by paulchitsonultromics** [comment]
[GH064-Amended.zip](https://github.com/fo-dicom/fo-dicom/files/9654978/GH064-Amended.zip)
Sample file generated from one of the test data files in the FO-DICOM repository.   It was created using the dcmtk toolkit using the following command:

            dcmodify -i "(0010,4000)" -nb GH064.dcm

This modification inserts and empty "null" Patient Comments tag.  Have seen this as an artifact of transcoding and anonymisation.

Will throw an exception when running DicomXML.ConvertDicomToXML on the line above.   

Altering EscapeXML to the below fixes the issue for this and other causes:


        private static string EscapeXml(string text)
        {
            if (text == null)
                return String.Empty;
            else
                return text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;").Replace("\"", "&quot;").Replace("'", "&apos;");
        }

**Comment by gofal** [comment]
Great, thank you for giving that example and providing a solution!

Would you mind to create a pull request containint your solution and some unittest?
