### ISSUE TITLE
Certificate support for DicomClient

### ISSUE THREAD

**Issue by pdgmdm** [fo-dicom/fo-dicom#1402]
Is it possible to setup a dicomclient connection using TLS with a client certificate ? 
I was looking at `DesktopNetworkStream(NetworkStreamCreationOptions options)` where the sllstream is created

`var authenticationSucceeded = Task.Run(async () => await ssl.AuthenticateAsClientAsync(options.Host).ConfigureAwait(false)).Wait(_sslHandshakeTimeout);`

Could it be possible to extend the `NetworkStreamCreationOptions ` to include a client certificate and 

`var authenticationSucceeded = Task.Run(async () => await ssl.AuthenticateAsClientAsync(options.Host, option.clientCertificateCollection, false).ConfigureAwait(false)).Wait(_sslHandshakeTimeout);`

Is there a workaround available where the existing functionality could be overriden to add this client certificate ? I did look at the `FellowOakDicom.Network.Client.Advanced.Connection` but could not find anything.

**Comment by mrbean-bremen** [comment]
This also came up as an requirement in our environment - I have no idea about the effort needed to implement this, as I'm not really knowledgable in that area. 
@gofal, @amoerie : can you give some estimation / idea for the effort needed to implement this?

**Comment by mrbean-bremen** [comment]
Also related to #688.

**Comment by amoerie** [comment]
Today this only feasible by providing your own NetworkManager implementation.

We have a custom build with certificate support on our private fork, but it's just never been a priority for me to port that code here...

**Comment by mrbean-bremen** [comment]
@amoerie - we can probably implement this and add as a PR at some time in the not-so-distant future, your help would be appreciated of course.

**Comment by amoerie** [comment]
I took a first stab at implementing client certificate support over in #1418
I'll need some time to polish & test.
