### ISSUE TITLE
I can't check a PersonName for validity anymore in V 5.03

### ISSUE THREAD

**Issue by saschke** [fo-dicom/fo-dicom#1405]
**Describe the bug**
A GE US device sends the ReferringPhysician sequence even if that entry doesn't exist. In V4 I was able to check

if (((DicomPersonName)item)?.First == null) ...

In V 5 this throws an exception of type

((FellowOakDicom.DicomPersonName)item)).First threw an exception of type 'System.NullReferenceException'. 

What I did now is 

 if (item.Tag == DicomTag.ReferringPhysicianName)
            {
                try
                {
                    _header.ReferringPhysicianName.FirstName = ((DicomPersonName)item)?.First ?? "";
                    _header.ReferringPhysicianName.LastName = ((DicomPersonName)item)?.Last ?? "";
                    _header.ReferringPhysicianName.MiddleName = ((DicomPersonName)item)?.Middle ?? "";
                    _header.ReferringPhysicianName.Prefix = ((DicomPersonName)item)?.Prefix ?? "";
                    _header.ReferringPhysicianName.Suffix = ((DicomPersonName)item)?.Suffix ?? "";
                }
                catch 
                { // ignore
                }
                return;
            }

But that is ugly. How can I check without throwing an exception

**To Reproduce**
I guess its difficult to reproduce if you don't have a device sending empty PersonNames

**Expected behavior**
I should be able to check for null without throwing an exception

**Screenshots**
![image](https://user-images.githubusercontent.com/8451973/174735879-18a74e97-8205-40ae-bd31-c37ce370b74b.png)

**Environment**
Fellow Oak DICOM version: 5.03
OS: (x64)
Platform: (e.g. .NET Framework 4.7.2)

**Comment by mrbean-bremen** [comment]
Just to clarify: by "sends the ReferringPhysician sequence even if that entry doesn't exist" do you mean it sends an empty `ReferringPhysiciaName` tag? Or is there a sequence involved, which shall contain the tag in an item?
Also, your screenshot is way too small to show anything - it is always better to just show the snippet of code as text that causes the issue.

**Comment by saschke** [comment]
This is a dump of the beginning of the SR. No referring physician was entered on the US device. No idea why it sends an empty PN

-Dicom-File-Format

-Dicom-Meta-Information-Header
-Used TransferSyntax: Little Endian Explicit
(0002,0000) UL 196                                      #   4, 1 FileMetaInformationGroupLength
(0002,0001) OB 00\01                                    #   2, 1 FileMetaInformationVersion
(0002,0002) UI =ComprehensiveSRStorage                  #  30, 1 MediaStorageSOPClassUID
(0002,0003) UI [1.2.840.113619.2.390.394137.1655458727.0.3] #  42, 1 MediaStorageSOPInstanceUID
(0002,0010) UI =LittleEndianImplicit                    #  18, 1 TransferSyntaxUID
(0002,0012) UI [1.3.6.1.4.1.30071.8]                    #  20, 1 ImplementationClassUID
(0002,0013) SH [fo-dicom 5.0.3]                         #  14, 1 ImplementationVersionName
(0002,0016) AE [HERAREPORT]                             #  10, 1 SourceApplicationEntityTitle

- Dicom-Data-Set
- Used TransferSyntax: Little Endian Implicit
(0008,0005) CS [ISO_IR 6]                               #   8, 1 SpecificCharacterSet
(0008,0016) UI =ComprehensiveSRStorage                  #  30, 1 SOPClassUID
(0008,0018) UI [1.2.840.113619.2.390.394137.1655458727.0.3] #  42, 1 SOPInstanceUID
(0008,0020) DA [20220617]                               #   8, 1 StudyDate
(0008,0021) DA [20220617]                               #   8, 1 SeriesDate
(0008,0023) DA [20220617]                               #   8, 1 ContentDate
(0008,0030) TM [090818]                                 #   6, 1 StudyTime
(0008,0031) TM [093846]                                 #   6, 1 SeriesTime
(0008,0033) TM [093846]                                 #   6, 1 ContentTime
(0008,0050) SH [6379104712547777]                       #  16, 1 AccessionNumber
(0008,0060) CS [SR]                                     #   2, 1 Modality
(0008,0070) LO [GE Vingmed Ultrasound]                  #  22, 1 Manufacturer
(0008,0080) LO [thats me]       #  32, 1 InstitutionName
**(0008,0090) PN (no value available)                     #   0, 0 ReferringPhysicianName**
(0008,1010) SH [AURORA-060399]                          #  14, 1 StationName
(0008,1030) LO [Adult Echocardiography]                 #  22, 1 StudyDescription
(0008,1090) LO [Vivid E90]                              #  10, 1 ManufacturerModelName

Does that help?

**Comment by mrbean-bremen** [comment]
Reading an empty tag should be easy, e.g. this passes:
```cs
        [Fact]
        public void Read_EmptyTag()
        {
            var dataset = new DicomDataset
            {
                { DicomTag.SOPClassUID, DicomUID.SecondaryCaptureImageStorage },
                { DicomTag.SOPInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID() },
                { DicomTag.ReferringPhysicianName, ""}
            };

            var tag = dataset.GetDicomItem<DicomPersonName>(DicomTag.ReferringPhysicianName);
            Assert.Equal("", tag.First);
        }
```
So it would really help if you would show the code which gets the item.

**Comment by saschke** [comment]
here the code I use to walk through the headers items. simple stuff. 

  foreach (DicomItem item in dicomFile.Dataset)
            {
                    if (item.ValueRepresentation != DicomVR.SQ)
                    {
                        if (!item.Tag.IsPrivate && item.ValueRepresentation != DicomVR.UN) // toshiba sends private stuff with VR UN = unknown
                        {
                            AddHeaderInfo(item);
                        }
                    }
     }

      private void AddHeaderInfo(DicomItem item)
        {
          // checking for all the items I care about ... 

            if (item.Tag == DicomTag.ReferringPhysicianName)
            {
                try
                {
                    _header.ReferringPhysicianName.FirstName = ((DicomPersonName)item)?.First ?? "";
                    _header.ReferringPhysicianName.LastName = ((DicomPersonName)item)?.Last ?? "";
                    _header.ReferringPhysicianName.MiddleName = ((DicomPersonName)item)?.Middle ?? "";
                    _header.ReferringPhysicianName.Prefix = ((DicomPersonName)item)?.Prefix ?? "";
                    _header.ReferringPhysicianName.Suffix = ((DicomPersonName)item)?.Suffix ?? "";
                }
                catch 
                { // ignore
                }
                return;
            }
        }
    }

**Comment by mrbean-bremen** [comment]
Thank you - I think I can see the problem now. My test wasn't actually correct, I should have assigned `null` to the item. 
I think this is something that can be fixed in fo-dicom, but for the time being, I would add a check for the number of values in the item:
```cs
  foreach (var item in dataset)
  {
    if (item.Tag == DicomTag.ReferringPhysicianName && ((DicomElement)item).Count > 0)
    {
      _header.ReferringPhysicianName.FirstName = ((DicomPersonName)item).First;
      _header.ReferringPhysicianName.LastName = ((DicomPersonName)item).Last;
      ...
     }
  }
```
Note that you also don't need the additional checks for null here.

**Comment by saschke** [comment]
Great, thank you!
That will work for me.
-Schlomo
