### ISSUE TITLE
Message Command Field Priority invalid for C-ECHO and all DIMSE-N Requests

### ISSUE THREAD

**Issue by Ed55** [fo-dicom/fo-dicom#141]
Sorry to bother you guys again, but I am currently going through all tweaks I applied to the old code base and check them against 2.0.0 beta ...

My notes are unfortunately not complete,but I failed with a StorageCommit prototype implementation against one of the global players PACS system. A test against DCMTK revealed the issue.

Based on my understanding of the DICOM standard the Command Message Field "Priority" is legal just for DIMSE-C Requests except C-ECHO and not for DIMSE-N Requests.
[DIMSE-N Services] (http://dicom.nema.org/dicom/2013/output/chtml/part07/chapter_10.html)
[DIMSE-C Services] (http://dicom.nema.org/dicom/2013/output/chtml/part07/chapter_9.html)

The solution is of course simple: 
* Delete the public property Priority from DicomRequest
* Create a new abstract class like DicomPriorityRequest derived from DicomRequest and add the implementation of the former public property Priority to this class.
* Change the implementation of DicomCFind-, DicomCMove- and DicomCStoreRequest to derive from DicomPriorityRequest.

**Comment by anders9ustafsson** [comment]
Thanks once more, @Ed55 , for your thorough investigations. I need to read up on this to understand it in more detail, and will get back as soon as I have.

**Comment by anders9ustafsson** [comment]
OK, have read and understood :-) @Ed55 your suggested solution seems like the obvious way to go. I'll deal with it shortly.
