### ISSUE TITLE
Specific JPEG Lossless DICOM file produces gibberish pixel data

### ISSUE THREAD

**Issue by amoerie** [fo-dicom/fo-dicom#1422]
**Describe the bug**
This specific file produces strange output when rendering

**To Reproduce**
Open the attached file with Fellow Oak DICOM
The issue occurs both with the Efferent codecs and the codecs from fo-dicom v4.

MicroDicom:
![image](https://user-images.githubusercontent.com/2063584/180790392-d8b81ab2-72f4-41e4-b6e5-9eea86a84539.png)

DICOM Dump using Efferent codecs:
![jpeg-lossless](https://user-images.githubusercontent.com/2063584/180791869-e172c4b3-4796-46dc-b27e-4cdbdca36b19.png)

**Expected behavior**
Deep Unity PACS viewer can parse it apparently, it produces this
![image](https://user-images.githubusercontent.com/2063584/180790701-a008967c-1674-428f-bb55-42f81972bf2d.png)

**Notes**
MicroDicom produces the same output.
dcmdjpeg.exe from DCMTK produces the following output:

```
dcmdjpeg '.\jpeg-lossless.dcm' jpeg-lossless-decoded.dcm
W: Corrupt JPEG data: bad Huffman code
W: Corrupt JPEG data: premature end of data segment
```

**Environment**
Fellow Oak DICOM version: 5.0.3
OS: Windows 10 64 bit
Platform: .NET Core 6.0
[jpeg-lossless.zip](https://github.com/fo-dicom/fo-dicom/files/9181604/jpeg-lossless.zip)

I'm not sure whether this is a corrupt file (that the Deep Unity PACS can magically fix) or whether this is a rare JPEG Lossless file that makes use of some exotic parameter that is almost never supported. If someone with more knowledge about JPEG Lossless could tell me what is going on, then we can make a better informed decision..

**Comment by ge-bus** [comment]
Alexander,

If you look at the first byte of the pixel data, you'll see that the codec used is MITRA_CORNELL. 
(In case the source PACS is Impax and you make use of Q/R, Impax will use MITRA_DICOM_STANDARD as codec, correcting this issue.)
Some viewers indeed present this objects correctly, others will fail. This isn't a fo-dicom/Efferent issue, but related to issues in the Cornell codec.
In DCMTK, dcmdjpeg has the following option:
```
+wc   --workaround-cornell
          enable workaround for 16-bit JPEG lossless
          Cornell images with Huffman table overflow
```
If you use this option, DCMTK will be able to successfully convert this object.
Some extra background:
https://support.dcmtk.org/redmine/attachments/51/dcmjpeg_buggy_cornell_encoder.patch?type=sbs
https://github.com/DCMTK/dcmtk/blob/master/docs/CHANGES.364
This can also be implemented in the codecs used by fo-dicom.

Hope this helps!

**Comment by amoerie** [comment]
That's wonderful Geert, thanks for a conclusive summary! Perhaps we can include the same workaround in fo-dicom someway then.. but I guess that would be a modification in the Efferent codecs then.

**Comment by ge-bus** [comment]
Indeed, in the Efferent codecs, making it optional as DCMTK does.

**Comment by jaime-olivares** [comment]
That sounds like something very specific. We will review it and have an answer soon.

**Comment by jaime-olivares** [comment]
> Indeed, in the Efferent codecs, making it optional as DCMTK does.

Just to clarify. DCMTK doesn't make it an optional functionality.
It is rather a conditional compilation with/without Cornell support.
Not sure how this modification may affect other use-cases

**Comment by jaime-olivares** [comment]
This issue is actively being resolved (and possibly already done) here: https://github.com/Efferent-Health/fo-dicom.Codecs/issues/26

You can safely close this issue.
