### ISSUE TITLE
Issue faced while migrating to 5.0.3

### ISSUE THREAD

**Issue by gajendra2001** [fo-dicom/fo-dicom#1425]
**Describe the bug**
After adapting to the breaking changes(https://github.com/fo-dicom/fo-dicom/blob/development/ChangeLog5.md) An error occurred while sending DICOM requests: 

- FellowOakDicom.Network.DicomNetworkException: Connection was lost before an association could be established
- Socket error while reading PDU: ConnectionReset
- Read 0 bytes from network stream while reading PDU header, connection will be marked as closed

**Expected behavior**
It supposed to established the association

**Environment**
Fellow Oak DICOM version: 5.0.3

**Comment by amoerie** [comment]
Are you saying that the exact same code works under 5.0.2 and is now broken?

Could you provide a minimal code reproduction of the issue?

**Comment by gajendra2001** [comment]
Thanks for your reply, It is resolved now. we were missing one of the dll which is newly added as dependency(microsoft.toolkit.performance) of fo-dicom. The problem we faced is that it is never giving error that dll is missing and closing the connection with above mentioned errors.

**Comment by amoerie** [comment]
@gofal could it be that our nuget package dependencies need to be updated?
