### ISSUE TITLE
PACS C-Store

### ISSUE THREAD

**Issue by khaledyasser95** [fo-dicom/fo-dicom#1427]
### Expected behavior
When I use C-Store to receive certain Dicom files I receive the all Dicom files not the selected ones.
Example: Sending PACS file from a CT Machine. I select multiple images lets say 10/100. The issue is I receive 100 not 10

### Actual behavior
I am assuming there is a Dicom Tag I need to use to get the 10 selected images from the 100.

Please let me know if I am doing something wrong or I need to add a check.

In Dicom Tag there is any boolean for printing or saving?

Maybe it’s wrong configuration in the CT Machine?

**Comment by mrbean-bremen** [comment]
Can you elaborate on your use case? By C-Store you mean a C-STORE SCP implementation? Is this the part you have implemented using fo-dicom? And what do you mean by "selecting images"? 
We need a bit more specific information to understand the question.

**Comment by khaledyasser95** [comment]
Yes Sir. I created C-Store SCP using Foo Dicom. It is working fine and I receive Dicom files. The CT guy said he selected 10 Dicom Files and send it to me but I receive 100 Different Dicom files for the same patient.
What I should receive is 10 Dicom files for this patient not the whole Volume.

please let me know if you need more information. I have been searching online for an answer but I did not.

**Comment by mrbean-bremen** [comment]
Hm, that's strange - are these different files? If yes, they must have been sent by the PACS. Maybe he had selected 10 series with 10 images each or something? 

As it looks, it has nothing to do the with StoreSCP, as it can only accept what it is sent.

**Comment by khaledyasser95** [comment]
They are sent through PACS. I have 0 knowledge about the Machine configurations I just gave them AE Title,IP,Port. 
The files should be for the same patient but different images inside the Dicom files. When I receive the 100 Dicom files the 100 is different files for the same patient but all he said that he only sent 10 so am confused. 

I told him I receive what ever you send to me the app cant invent images.

**Comment by mrbean-bremen** [comment]
Well, you are right - this has nothing to do with fo-dicom. Try to check what they are sending from the PACS, maybe they can show you. Clearly a problem on the sender side... I don't think there is anything we help you with this.

**Comment by khaledyasser95** [comment]
Thank you so much, Sir. 
I really appreciate all your help!

**Comment by mrbean-bremen** [comment]
Nothing to here, closing.
