### ISSUE TITLE
There is already a DICOM server registered on port

### ISSUE THREAD

**Issue by AndersPeng** [fo-dicom/fo-dicom#1431]
There is already a DICOM server registered on port: 105

when i need restart the DICOM server,our code like this:

DicomServer.GetInstance(105).Stop()

DicomServer.Create<CStoreSCP>(GlobalData.DicomStoreSCP.SCPIP, 105);

but it has a exception “There is already a DICOM server registered on port: 105”

please help me,thanks!

**Comment by sudheeshps** [comment]
@AndersPeng can you try unregistering the service? As you stop the service the resources will be ideally disposed. But if you have reference it will not cleanup. I was able to reproduce your issue without unregistering
`DicomServerRegistry.Unregister(dicomServer.Registration);`
The following code works.
 ```
var dicomServer = DicomServerFactory.Create<DicomCEchoProvider>(105);
 Thread.Sleep(50 * 100);
 dicomServer.Stop();
 DicomServerRegistry.Unregister(dicomServer.Registration);
 DicomServerFactory.Create<DicomCEchoProvider>(105);
```

**Comment by gofal** [comment]
I also know this issue very well! Even if you unregister the service just before you try to restart, you can get this error from time to time. I figured out, that the operation system (Windows) needs some time, to mark the port as free. So after unregistering, I added some Thread.Sleep of 10 seconds before starting the server again. With that it was fine.

**Comment by gofal** [comment]
Have you been able to fix the issue with one of the two hints? I will close this issue now, but please feel free to reopen it if you still face an issue.
