### ISSUE TITLE
Cannot cast to 'Image'; type must be assignable from 'Byte[]

### ISSUE THREAD

**Issue by yadavvirus** [fo-dicom/fo-dicom#1436]
While PRINT SCP I am getting error.
Cannot cast to 'Image'; type must be assignable from 'Byte[]

here 
_currentFilmBox.Print(e.Graphics, e.MarginBounds, 100);

Image is attached.
![Untitled](https://user-images.githubusercontent.com/7027914/186661098-039ffde0-496c-41ea-b46b-aef1edb81012.png)

I am using fo-dicom.core version 5.0.3.0

**Comment by yadavvirus** [comment]
@gofal sir please take a look into this problem.

**Comment by gofal** [comment]
See here: https://github.com/fo-dicom/fo-dicom#image-rendering-configuration
fo-dicom is a platform independent library and therefore has no reference to system.drawing out of the box. Rendering is done into a byte array.
But if you reference the package fo-dicom.imaging.destop, then you introduce all dependencies to System.Drawing and, if you then register this package into fo-dicom's internal DI container by calling 
```
new DicomSetupBuilder()
    .RegisterServices(s => s.AddFellowOakDicom().AddImageManager<WinFormsImageManager>())
.Build();
```
then the rendered image will be convertable to System.Drawing.Image

**Comment by gofal** [comment]
Have you been able to solve the issue with that hint?
I will close this issue for now, but please feel free to reopen it if there is still an issue.
