### ISSUE TITLE
XA/XRF images should not have their modality LUT sequence applied

### ISSUE THREAD

**Issue by amoerie** [fo-dicom/fo-dicom#1442]
**Describe the bug**
When an XA or XRF image has a modality LUT sequence, that should not be applied when rendering.

**To Reproduce**
Render a XA or XRF image with a modality lut sequence. You will see the pixel data is much too dark. Since the transformation is not linear, this cannot be fixed by window leveling manually.

**Expected behavior**
The modality LUT sequence should not be applied. 

**Screenshots or test DICOM files**

**Environment**
Fellow Oak DICOM version: 5.0.3
OS: (e.g. Windows 8.1 x64)
Platform: (e.g. .NET Framework 4.6.2)

**Comment by amoerie** [comment]
DCMTK renders this correctly. This snippet of source code is taken from the DCMTK source code:

(Found at https://github.com/DCMTK/dcmtk/blob/master/dcmimgle/libsrc/dimomod.cc#L62 )

```
if ((strcmp(sopClassUID, UID_XRayAngiographicImageStorage) == 0) ||
    (strcmp(sopClassUID, UID_XRayRadiofluoroscopicImageStorage) == 0) ||
    (strcmp(sopClassUID, UID_RETIRED_XRayAngiographicBiPlaneImageStorage) == 0))
{
    /* David Clunie in comp.protocols.dicom (2000-12-13):
        "Modality LUTs in XA and XRF objects are totally screwy and
         do not follow the normal rules. [...] A Modality LUT may be
         included with the image to allow it to be scaled back to its
         proportional value to X-Ray beam intensity. In other words,
         for the objects that use this module (XA and XRF), the
         Modality LUT is used BACKWARDS. It is used to convert stored
         pixels to X-Ray beam intensity space, but it is NOT APPLIED
         to stored pixels for the purpose of display (or more
         specifically prior to application of the VOI LUT Module
         attributes to the stored pixel data)."
    */
    DCMIMGLE_INFO("processing XA or XRF image ... ignoring possible modality transform");
}
```

**Comment by amoerie** [comment]
Link to the original comment by David Clunie: https://groups.google.com/g/comp.protocols.dicom/c/UBxhOZ2anJ0/m/D0R_QP8V2wIJ

**Comment by amoerie** [comment]
The PR includes a unit test with a sample DICOM file (anonymized) that demonstrates the issue.
In the unit test, I don't actually render the image, but just construct the GrayScaleRenderOptions and verify the modality LUT is null (which means it will not be usable by the render pipeline)

**Comment by khalid80** [comment]
Do we have a dcm file for negative test case for other SOP with MLUT sequence?
