### ISSUE TITLE
How to get venous phase?

### ISSUE THREAD

**Issue by potaninmt** [fo-dicom/fo-dicom#1443]
How to get venous phase, arterial phase and other? I mean bitmap

**Comment by mrbean-bremen** [comment]
Can you elaborate what kind of DICOM images you are speaking about, and where fo-dicom comes into it?

**Comment by potaninmt** [comment]
I mean medical dicom images (Magnetic resonance imaging)

**Comment by mrbean-bremen** [comment]
So you are speaking about contrast enhanced MR images with different phases. I'm still not sure what you are asking. Is your question about how to differentiate between the phases? This would be specific to the protocol used (probably found in the Series Description), and has nothing to do with fo-dicom. Or are you generally asking how to display images in fo-dicom?

**Comment by potaninmt** [comment]
Yes I mean how to differentiate between the phases and get venous bitmaps

**Comment by potaninmt** [comment]
WIth using your fo-dicom

**Comment by potaninmt** [comment]
I need bitmap of  venous phase from your library!!!

**Comment by zaharPonimash** [comment]
How to recognize the phases, we know, the issue is that when viewing an image, there is one image showing fo-dicom, while in other programs we see several phases. I would like to know how to switch between phases.

**Comment by mrbean-bremen** [comment]
This depends on your application logic, and how you recognize and load the phases. If you know which image shows which phase, you can just load these as you need to show them. It is your application that does this, fo-dicom is just the used library. Or maybe I still don't understand your question...
