### ISSUE TITLE
Missing Implementation Class UID in association

### ISSUE THREAD

**Issue by edautov** [fo-dicom/fo-dicom#1447]
### Expected behavior
Check for no Implementation Class UID and generate a service class to go with the association.
Acceptance of DICOM transfer. 

### Actual behavior
I tested with example C-Store SCP
The client (i don't control the client) sends without an Implementation Class UID and an error is generated. The error is in attachment.

### fo-dicom version and OS/platform
Fellow Oak DICOM version: 5.0.3
[log_fo-dicom_503_20220915.txt](https://github.com/fo-dicom/fo-dicom/files/9581740/log_fo-dicom_503_20220915.txt)

**Comment by gofal** [comment]
This tag is required. So in the first place you have to inform the client (or who does control the client) that they should add the Implementation Class UID.
But agree, the server could be tollerant here. Fo-dicom already contains a fallback in association handling. if no Implementaiton Class UID is present then internally the UID 1.3.6.1.4.1.30071.8 is used. (https://github.com/fo-dicom/fo-dicom/blob/64b3f3e55b63a2184c9cd4a04476dd9bd7677607/FO-DICOM.Core/Network/DicomAssociation.cs#L111). So this client was able to do echo, c-find or similar.
But this fallback could also be implemented in C-Store here: https://github.com/fo-dicom/fo-dicom/blob/64b3f3e55b63a2184c9cd4a04476dd9bd7677607/FO-DICOM.Core/Network/DicomService.cs#L755

Would you like to make a pull request containing that change?

**Comment by edautov** [comment]
Hi, 
Thank you for help. 
I have notified client developer. 
But I want to make a pull request containing that change.
