### ISSUE TITLE
Which tag I should use to pass the file name to Dicom?

### ISSUE THREAD

**Issue by dash-ravikhoda** [fo-dicom/fo-dicom#1455]
I am uploading images to the Dicom but i am not able to view the actual file name on the Dicom in Orthnac server. 

From google, I found that I should pass the ReferenceFileId tag, but I am not sure if that is the correct tag.

**Comment by mrbean-bremen** [comment]
There is no such thing as a filename in the DICOM file itself - the dataset is send as a stream, not as a named file, so I'm not sure what exactly you are asking here.
Also, can you please explain where fo-dicom fits into the picture?

**Comment by gofal** [comment]
I will close this issue due to inactivity. Please reopen this issue, if you still face the issue or can provide more information.
