### ISSUE TITLE
Photometric Interpretation Question potential issue

### ISSUE THREAD

**Issue by BobSter3000** [fo-dicom/fo-dicom#1456]
**Describe the bug??**
When fo-dicom converts a color image from JPEG Lossless (.70) to JPEG Baseline(.50) the Photometric Interpretation changes from RGB to YBR_FULL.  Looking at the standard PS3.5 Table 8.2.1-1 it shows YBR_FULL_422 to be valid for JPEG Baseline.  Shouldn't fo-dicom be using YBR_FULL_422? 

**To Reproduce**
Take RGB Color image JPEG Lossless and save the file with the transfer syntax of JPEG Baseline.  The photometric interpretation changes from RGB to YBR_FULL.  

**Expected behavior**
This is the question.

**Screenshots or test DICOM files**
N/A.

**Environment**
Fellow Oak DICOM version: 5.0.3
OS: Windows 10 64bit
Platform: .NET6

**Comment by gofal** [comment]
Here is the link to that table: https://dicom.nema.org/medical/dicom/current/output/html/part05.html#table_8.2.1-1
I see, YBR_FULL_422 should be used for Jpeg Baseline instead of YBR_FULL.
The update of the photometric interpretation is done in codec library. I will duplicate this issue there.

**Comment by jaime-olivares** [comment]
Closed at Efferent's side

**Comment by BobSter3000** [comment]
Tested new codec.  This is fixed, closing issue.
