### ISSUE TITLE
AggregateException thrown during SendAsync, instead of SocketException 

### ISSUE THREAD

**Issue by bjorn-malmo** [fo-dicom/fo-dicom#1471]
**Describe the bug**
An AggregateException is thrown by DicomClient.SendAsync() when a socket exception occurs during Connect.

**To Reproduce**

            using (CreateServer<MockCEchoProvider>(port))
            {
                var client = CreateClient("127.0.0.1", 65000, false, "SCU", "INVALID");
                await client.AddRequestAsync(new DicomCEchoRequest()).ConfigureAwait(false);
                await client.SendAsync();
            }

**Expected behavior**
A SocketException should be thrown (the AggregateException should be expanded) when calling using async pattern

**Environment**
Fellow Oak DICOM version: 5.0.3
OS: Windows 10
Platform: .NET Framework 4.6.2

**Comment by gofal** [comment]
This is a breaking change. it is very common in async programming that AggregateExceptions are thrown. So many people will have built applications that catch AggregateExceptions and handle them. If now an other type of exception is thrown then this has to be documentated well.

Could you describe in more detail, why you want to avoid having an AggregateException in this very special case?

**Comment by bjorn-malmo** [comment]
The only reason for the change is that I don't expect an AggregateException to be thrown when calling an async method with the await keyword. 

I only found 2 places in the fo-dicom library where an async task is called synchronously using Wait(), and in the other instance, the AggregateException is unwrapped.

The SendAsync() method represents a single task (with no parallel stuff going on), making it more sensible to throw the actual exception that occurred, than having implementors iterate over the InnerException.

**Comment by gofal** [comment]
ok, thanks. That sounds reasonable

**Comment by amoerie** [comment]
Also adding my comment here: the changes proposed here are already covered by #1418, where the need to unwrap is avoided by simply properly awaiting the operation in DesktopNetworkStreamFactory.

**Comment by gofal** [comment]
Then this issue can be closed now.
