### ISSUE TITLE
Upgrade Nuget package to use CommunityToolkit instead of Microsoft toolkit as it is depreciated. 

### ISSUE THREAD

**Issue by dash-ravikhoda** [fo-dicom/fo-dicom#1473]
**What is, according to you, missing from fo-dicom? Please describe.**
Currently, Fo-Dicom is using Microsoft.Toolkit.highperformance nuget package which is depreciated and it's alternate is Communitytoolkit.Highperformance. 

**Describe the solution you'd like**
Change Nuget package to Communitytoolkit.Highperformance from Microsoft.Toolkit.highperformance

**Describe possible alternatives or existing workarounds you've considered**
A clear and concise description of any alternative solutions or existing workarounds you've considered.

**Comment by mrbean-bremen** [comment]
@Dash-Ravi - do you want to create a PR for this?

**Comment by dash-ravikhoda** [comment]
@mrbean-bremen sorry for the delayed reply. I will try for this and will submit the PR when I am done.

**Comment by amoerie** [comment]
Thanks for notifying us 👍
