### ISSUE TITLE
Render image from Icon Image Sequence with encapsulated images

### ISSUE THREAD

**Issue by bjorn-malmo** [fo-dicom/fo-dicom#1483]
**What is, according to you, missing from fo-dicom? Please describe.**
When an encapsulated SOP instance contains an Icon Image Sequence stored in native format, the DicomImage cannot render the icon, since it will try to extract any pixel data using the parent transfer syntax.
If the parent transfer syntax is an encapsulated video file, the only viable icon option is to use PALETTE COLOR and native format. This can't be rendered with the current implementation.

**Describe the solution you'd like**
I've created a new class; DicomIconImage (based on the implementation of DicomImage) that will extract the icon sequence's first item, and check if it is in native format (although the parent encoding is encapsulated).

**Describe possible alternatives or existing workarounds you've considered**
The current implementation of DicomImage could be changed to address this is in some way or the other, but I think that all features of overlays and windowing etc would make it hard to handle.

**Comment by gofal** [comment]
A great solution, thanks.
Would this also allow reading Icons from DICOMDIR files? Please find a anonymized DICOMDIR file, that contains Icons. Could you verify that? 
[DICOMDIRwithIcons.zip](https://github.com/fo-dicom/fo-dicom/files/10185098/DICOMDIRwithIcons.zip)

**Comment by gofal** [comment]
Duplicate to #1428?

**Comment by gofal** [comment]
I can confirm that rendering icons from Dicomdir file also works fine.
