### ISSUE TITLE
when packages will be migrated to .NET 7

### ISSUE THREAD

**Issue by arunjoshtech** [fo-dicom/fo-dicom#1488]
Dear sir,
As you aware .NET Core 7 is released with more performance , when Fo Dicom may migrated to latest version.

**Comment by gofal** [comment]
I ran our benchmark project in several constellations. Having 
- the core library in netstandard and the benchmark in net6
- the core library in net6 and the benchmark in net6
- the core library in net7 and the benchmark in net7
- the core library in netcore31 and the bencharm in netcore3.1

There are certain values, like opening file, parsing dataset or the server echo, where the netcor31 is clearly worse than the net6 or net7. but the values of net6 and net7 are pretty much the same.

So with the change from netcore3 to net6 there have been some performance improvements. but not so much from net6 to net7.
Of course, the .net7 is better in many areas, like asp.net or maui and so on. But the little part of the whole net framework, that fo-dicom is using, has not changed much.

Have you done some testing? Did you get other results? Did you observe some performance improvement when building fo-dicom with net7? Of course your own appliation, that is using fo-dicom, will benefit from updating to net7.

**Comment by arunjoshtech** [comment]
Dear Gofal,
we will try with .net7 in our SCP Functions and definitely share our results here. Thanks for your detailed answers on my Query.
