### ISSUE TITLE
Can't decode Transfer syntax MPEG2 MainProfile / Main Level

### ISSUE THREAD

**Issue by udiatcimd** [fo-dicom/fo-dicom#1495]
Hi!

I'm trying to decode a file with transferSyntax MPEG2MainProfile@MainLevel YBR_PARTIAL_420 using DicomFile.Clone(DicomTransferSyntax.MPEG2) but I always get the same error:

**"FellowOakDicom.Imaging.Codec.DicomCodecException: 'Decoding dataset with transfer syntax: MPEG2 Main Profile / Main Level is not supported.'"**

I already loaded the NativeTranscoderManager (that solved a lot of other problems I had) using a solution I found around here.
I've tried other DicomTransferSyntax to no avail

[I'm attaching a sample file that's giving me the error:](https://drive.google.com/file/d/1frc8zhi4SVNhQpJR7cSGrBJuPOLZtwIt/view?usp=share_link)

Is this not supported o am I missing something?

I'm using:
fo-dicom 5.0.3 & fo-dicom.codecs 5.1.0 nuget packages

(sorry if this was supposed to be a bug, new user and I'm not sure if this is a bug, a new feature, or just that I'm doing something wrong)

Thank you.

**Comment by mrbean-bremen** [comment]
You are doing nothing wrong, the codec is indeed not supported.
We rely on codecs from [Efferent Health](https://github.com/Efferent-Health/fo-dicom.Codecs), so it is probably better to create an issue in their repo. I don't know if they plan to add support for video codecs.

**Comment by udiatcimd** [comment]
Thank you for your answer, I will open an issue there!

**Comment by mrbean-bremen** [comment]
Closing this one, as it is duplicated in `fo-dicom.Codecs`.

**Comment by jaime-olivares** [comment]
At fo-dicom.Codecs, we don't encode or decode video formats, not even MPEG4.
