### ISSUE TITLE
Photometric Interpretation after decoding not updated

### ISSUE THREAD

**Issue by gofal** [fo-dicom/fo-dicom#1497]
**Describe the bug**
Rendering a color image under certain conditions results in a picture with wrong colors. The background should be white, but instead is pink.

**To Reproduce**
There is a sample image from mediaire Gmbh (an AI report). The image is Secondary Capture, compressed with JpegLossess process 14, it'a a color image and the Photometric Interpretation is YBR_FULL (because of the Jpeg-compression).
When calling RenderImage, the pixelData is decompressed. The Codec then takes the YBR_FULL into account and returns a PixelData object with correkt values and the PhotometricInterpretation of the resulted PixelData is changed to RGB.
But fo-dicom only thakes the Data of the returned PixelData and continues rendering with the original Dataset. So the renderer assumes YBR als color scheme and transforms the pixel data in a wrong way.

**Expected behavior**
After the codec was called and the Frames was decoded, fo-dicom should not only take the pixel data, but also some metadata from the codec, like PhotometricInterpretation

** Screenshot **
This is how it looks like:
![image](https://user-images.githubusercontent.com/6769246/212536455-ba28736c-2e25-45e2-898c-05ff612fd4c8.png)
this is how it should look like:
![image](https://user-images.githubusercontent.com/6769246/212536495-1c69e070-3eda-4fe0-89cc-bd388142276e.png)

**Environment**
Fellow Oak DICOM version: 5.0.3
OS: windows 10
Platform: .net core 6

**Comment by gofal** [comment]
This issue has an easy workaround. Instead of directly opening the compressed file als DicomImage and calling RenderImage, you can open the file, clone it to transfersyntax ExplicitLittleEndian, and then from that decompressed dataset create the DicomImage and then render the image. 
But still, the bug will be fixed.

**Comment by BobSter3000** [comment]
@gofal is this related to #1456?

**Comment by amoerie** [comment]
What a fabulous bug 🌈 😁

**Comment by gofal** [comment]
This bug will be fixed within the branch https://github.com/fo-dicom/fo-dicom/tree/GH917-RenderingOfEnhanced
Similar problems araised with enhanced images. The renderimage tests went well within that branch. but the performance and caching of rendering suffered with the improvement. I will try to restore performance and then do a PR
