### ISSUE TITLE
No Dicom codecs were found after searching Dicom.Native*.dll

### ISSUE THREAD

**Issue by BluerGost** [fo-dicom/fo-dicom#1499]
**Describe the bug**
I have built a viewer using fo-dicom. Which have different builds for 32bit and 64bit. If a computer is 32bit it will download the 32bit version of the software from the FTP server and in the case of 64bit, it will download the 64bit version.

It runs all right on all the computers except one. That computer is running a 64-bit OS. So, It downloads the 64-bit version but when it renders It searches for the Native DLL in the correct folder and the DLL does exists in that folder. But it is unable to find the DLL.
This same version of the software can find the DLL and render the image properly on any other 64-bit pc. 

The closest to this problem I have found is this one [#886](https://github.com/fo-dicom/fo-dicom/issues/866). But the solution that worked for him is unblocking the DLL. 
In my case, no checkbox shows up.
Since the computer has only one drive I was unable to transfer it to a different drive.

But I gave full access to the DLL and all the other folders.
I also tried the unblock command from Powershell. 

Finally, I should mention that since I don't have the Log enabled in my original Software. I have created a demo console application to see the Fo-Dicom logs. I have created 32-bit and 64-bit. When I run the 32-bit on that PC it is able to find the DLL but when I run the 64-bit it is unable to find the DLL.

I have tried all that I could think of but I am out of ideas of what could be the reason. 
Also, this is my first time posting an issue in Git Hub. So, If I made any mistakes let me know. 
Thank you.

**Expected behavior**
image.RenderImage() method renders the image.

**Screenshots or test DICOM files**
![Screenshot 2023-01-23 092314](https://user-images.githubusercontent.com/17919750/213948841-377d4dc0-63e6-46ca-8b7a-08c25bdcae3f.png)

**Environment**
Windows 10 (x64)
Fo-Dicom (4.0.8)
.NET Framework 4.8

**Comment by mrbean-bremen** [comment]
Are you sure it's not a problem with the dataset itself? Does the same dataset get loaded on other PCs?

**Comment by BluerGost** [comment]
> Are you sure it's not a problem with the dataset itself? Does the same dataset get loaded on other PCs?

Yes, the same Dataset/Dicom file loads on other PC. Actually, most of the images fail to load on that PC. But those same images load perfectly on the other PCs

**Comment by mrbean-bremen** [comment]
Strange... so what is different for that PC? I noticed that the backslash is shown in Japanese encoding, is the language different from the other ones (not that it would explain that...)? Do you have another virus scanner on that PC? Something clearly must be different...

**Comment by BluerGost** [comment]
> Strange... so what is different for that PC? I noticed that the backslash is shown in Japanese encoding, is the language different from the other ones (not that it would explain that...)? Do you have another virus scanner on that PC? Something clearly must be different...

Since I am developing in Japan. All the PC are in Japanese setting. So, that's not special for this particular PC.
I also think something must be different. But Still, I could not figure out what that is. Also, it's hard to check everything without knowing what could cause the problem. I do not know the codebase of Fo-Dicom but how do Fo-Dicom searches for the Native DLL? It seems to search for the DLL every time the RenderImage function is called. 

The things that I checked so far:
1) Window Version and Bit
2) Is the build version (64/32) correctly defined?
3) Is C++ ReDistribution installed. But After reading the wiki I found that FoDicom uses both 2013 and 2015. So, I have to make sure they both exist or not. Especially 2015.

Is there anything that could cause a problem for the DLL to load?

**Comment by mrbean-bremen** [comment]
I really have no good idea, but my guess is that this has not directly to do with fo-dicom itself, but with something that messes up the DLL loading. I can only list a few unlikely scenarios, but just in case:
- there is another DLL of the same name somewhere in the path that is found instead of the needed one - maybe there is another version of fo-dicom installed, that is in the path
- there is another process (like a virus scanner) that blocks the DLL
- the PC is infected with a virus that has the file corrupted (as I wrote, unlikely...)

**Comment by BluerGost** [comment]
> I really have no good idea, but my guess is that this has not directly to do with fo-dicom itself, but with something that messes up the DLL loading. I can only list a few unlikely scenarios, but just in case:
> 
> * there is another DLL of the same name somewhere in the path that is found instead of the needed one - maybe there is another version of fo-dicom installed, that is in the path
> * there is another process (like a virus scanner) that blocks the DLL
> * the PC is infected with a virus that has the file corrupted (as I wrote, unlikely...)

Funny because I was hoping that 64-bit could work with 32-bit DLL. So, I put both the 32 and 64-bit DLL in the 64-bit application. But didn't work. I don't think path overlapping is the issue. 
I also tried unblocking the DLL from Windows Defender. But didn't work. Could be that some other process is also blocking it. But why only the 64bit. 

I will try checking your suggested options. But it does seem like a bothersome problem.

**Comment by BluerGost** [comment]
> I really have no good idea, but my guess is that this has not directly to do with fo-dicom itself, but with something that messes up the DLL loading. I can only list a few unlikely scenarios, but just in case:
> 
> * there is another DLL of the same name somewhere in the path that is found instead of the needed one - maybe there is another version of fo-dicom installed, that is in the path
> * there is another process (like a virus scanner) that blocks the DLL
> * the PC is infected with a virus that has the file corrupted (as I wrote, unlikely...)

I found the problem.
That PC did not have C++ Redistributable (x64). After installing the software started to run smoothly. 
For anyone having a similar problem. Read this [Wiki](https://github.com/fo-dicom/fo-dicom/wiki/Prerequisites). Good luck. 
Thank you mrbean-bremen for your help.
