### ISSUE TITLE
C-Get for RTSTRUCT

### ISSUE THREAD

**Issue by mikhail-rozum** [fo-dicom/fo-dicom#1504]
### Discussed in https://github.com/fo-dicom/fo-dicom/discussions/1500

<div type='discussions-op-text'>

<sup>Originally posted by **mikhail-rozum** January 23, 2023</sup>
Hello!
I have a DICOM Server (Orthanc) and I need to download structure set dicom file from there(RTSTRUCT modality). I use this code

```
var request = new DicomCGetRequest(studyInstanceId, seriesInstanceId);

client.OnCStoreRequest += request =>
{
    result.Add(request.Dataset);
    return Task.FromResult(new DicomCStoreResponse(request, DicomStatus.Success));
};
await client.AddRequestAsync(request);
await client.SendAsync();

```
But I get an error:
![image](https://user-images.githubusercontent.com/13016376/213984253-26fed354-ea42-430e-9794-325d2912cc6e.png)
How can I get RTSTRUCT dicom file from dicom server?</div>

**Comment by gofal** [comment]
the server responded with an error. so the first thing would be to ask at the server side what the issue was.
My first guess would be, the server is not configured well. most PACS systems are configured the way, that a clients by default may not query a server (for security reasons). did you have configured your client well? did you configure it as C-Move or as C-Get client?

https://book.orthanc-server.com/dicom-guide.html#c-get-retrieve-with-one-single-scp

**Comment by mikhail-rozum** [comment]
Finally I could get RTSTRUCT file from Orthanc PACS. I tried to check Orthanc's logs and found an error
**"Error in the network protocol: C-GET SCP: storeSCU: No presentation context for: (RS) 1.2.840.10008.5.1.4.1.1.481.3"**
So, the thing I had to do was to add presentation contexts to the request.

I hope this code will help others.

Thank you @gofal 

```
var request = new DicomCGetRequest(studyInstanceId, seriesInstanceId);

client.OnCStoreRequest += request =>
{
    result.Add(request.Dataset);
    return Task.FromResult(new DicomCStoreResponse(request, DicomStatus.Success));
};

var pcs = DicomPresentationContext.GetScpRolePresentationContextsFromStorageUids(
	DicomStorageCategory.Other,
	DicomTransferSyntax.ExplicitVRLittleEndian,
	DicomTransferSyntax.ImplicitVRLittleEndian,
	DicomTransferSyntax.ExplicitVRBigEndian,
	DicomTransferSyntax.ImplicitVRBigEndian);
client.AdditionalPresentationContexts.AddRange(pcs);

await client.AddRequestAsync(request);
await client.SendAsync()
```
