### ISSUE TITLE
DicomDatasetDumper logging is truncating UID's

### ISSUE THREAD

**Issue by BobSter3000** [fo-dicom/fo-dicom#1505]
**Describe the bug**
When the DicomService LogDataPDUs or LogDimseDatasets are enabled a 64 byte UID is truncated in the logging.

**To Reproduce**
Create a Dicom Client and enable LogDataPDUs and LogDimseDatasets in the client.ServiceOptions.
Send a c-store request that has a UID = 64 bytes.

I can get a pull request together for this.

**Expected behavior**
Logging does not truncate UID's.

**Screenshots or test DICOM files**
![image](https://user-images.githubusercontent.com/9662532/215618639-077f214c-b548-4b94-ac65-fe4d55da00fe.png)

Fixed
![image](https://user-images.githubusercontent.com/9662532/215618730-8abfa4c3-72ec-4ddf-b998-43339ecf9e79.png)

**Environment**
Fellow Oak DICOM version: 5.0.3
OS: Windows 10 64bit
Platform: .NET 6

**Comment by mrbean-bremen** [comment]
Thanks! Generally, it makes sense to truncate the value output, as it may get arbitarily long for some VRs, but in the case of UIDs I agree that a truncated one is not helpful. So from my POV a PR would be fine (provided that it does not remove output truncation at all).
