### ISSUE TITLE
PHILIPS Allura Xper FD10 printing loop

### ISSUE THREAD

**Issue by murilo-kendjy** [fo-dicom/fo-dicom#1526]
Not sure how to describe it with more info, but I'm trying to use it in a PHILIPS Allura Xper FD10 and the problem is: It works, but it keeps printing in loop.

fo-dicom.Desktop v4.0.0 / .NET 4.5.2

**Comment by gofal** [comment]
first of all, please use the latest version fo-dicom 5. there hvae been a lot of enhancements since version 4.

did you search in (closed) issues here. There have been a lot of issues and discussions about how to deal with printing. There you might find some helpful hints.

**Comment by murilo-kendjy** [comment]
Sorry the late response, upgrading for the latest v4 version seems to be fixed, thanks.

**Comment by gofal** [comment]
Great to hear that.
