### ISSUE TITLE
Consider implementing DicomDataset.Clone() as "DeepClone"

### ISSUE THREAD

**Issue by Ed55** [fo-dicom/fo-dicom#153]
I came along this issue writing an MWL test SCP by taking the request dataset, clone it multiple times and call a kind of randomizer TransformRule to create response datasets.
Simplified example simulating this kind of TransformRule:

                DicomDataset ds = new DicomDataset();
                ds.Add(DicomTag.PatientID, "1");
                DicomDataset sps = new DicomDataset();
                sps.Add(DicomTag.ScheduledStationName, "1");
                ds.Add(new DicomSequence(DicomTag.ScheduledProcedureStepSequence, sps));

                DicomDataset ds2 = ds.Clone();

                ds2.Add(DicomTag.PatientID, "2");
                ds2.Get<DicomSequence>(DicomTag.ScheduledProcedureStepSequence).Items[0].Add(DicomTag.ScheduledStationName, "2");

This code will end up with the first dataset's (ds) ScheduledStationName value of "2" as well.

One may create another DicomDataset Extension method "DeepClone()" which recursively iterates  sequences to call DeepClone() again on its items, but personally I would prefer that Clone() handels this already.

Consider to change the constructors of DicomDataset taking items as parameter accordingly as well.

**Comment by anders9ustafsson** [comment]
Agreed, deep cloning would be the preferred choice here.
