### ISSUE TITLE
Use ImplementationClassUID from dataset

### ISSUE THREAD

**Issue by ryan-rozario** [fo-dicom/fo-dicom#1544]
**What is, according to you, missing from fo-dicom? Please describe.**

Currently to add ImplementationClassUID and ImplementationVersionName to a dicom file we have to override the OnSave() function of DicomFile and create our own class.  #798 
If we Add these tags to our dataset then the program generates two duplicate tags, which contains the custom value and another which contains fo-dicom version.

These tags should instead be taken from the dataset, if the tag is present.

**Describe the solution you'd like**
While creating DicomFileMetaInformation during saving we can check if the tag exists already in the dataset and use that  value instead

```      
        public DicomFileMetaInformation(DicomDataset dataset)
        {
            ValidateItems = dataset.ValidateItems;
            Version = new byte[] { 0x00, 0x01 };

            MediaStorageSOPClassUID = dataset.GetSingleValue<DicomUID>(DicomTag.SOPClassUID);
            MediaStorageSOPInstanceUID = dataset.GetSingleValue<DicomUID>(DicomTag.SOPInstanceUID);
            TransferSyntax = dataset.InternalTransferSyntax;

            ImplementationClassUID = DicomImplementation.ClassUID; //use tag from dataset if exists
            ImplementationVersionName = DicomImplementation.Version; // use tag from dataset if exists

            dataset.TryGetString(DicomTag.SourceApplicationEntityTitle, out var aet);
            if (aet != null)
            {
                SourceApplicationEntityTitle = aet;
            }

            if (dataset.TryGetSingleValue(DicomTag.SendingApplicationEntityTitle, out string sendingAETVal))
            {
                SendingApplicationEntityTitle = sendingAETVal;
            }
            if (dataset.TryGetSingleValue(DicomTag.ReceivingApplicationEntityTitle, out string receivingAETVal))
            {
                ReceivingApplicationEntityTitle = receivingAETVal;
            }
            if (dataset.TryGetSingleValue(DicomTag.PrivateInformationCreatorUID, out DicomUID privInfoCreator))
            {
                PrivateInformationCreatorUID = privInfoCreator;
            }
            if (dataset.TryGetValues(DicomTag.PrivateInformation, out byte[] privInfo))
            {
                PrivateInformation = privInfo;
            }
        }
```

**Describe possible alternatives or existing workarounds you've considered**
Another solution would be to allow the user to set the FileMetaInfo property of DicomFile.

**Comment by gofal** [comment]
This information ImplementationClass and ImplementationVersion are used to identify the software that generated or last touched the data. 
so if there is some information in a file and a software based on fo-dicom is then opening this file, propably doing some manipulation and then saving the file, the the ImplementationClass and ImplementationVersion has to change. You should not use the one that has been in the data when loading.

So maybe an other spot would fit better. On all spots where fo-dicom has to update the data, it uses the static properties `DicomImplementation.ClassUID` and `DicomImplementation.Version`. So if you want to have your own Applications UID and versioning, then all you have to do, is to set those static properties on application Startup.

Would that fit your needs and solve this issue?

**Comment by ryan-rozario** [comment]
Oh ok. I did not know that there was a static property that I could set. Based on issue #798  , I assumed overriding Save method was the only way to set our own ClassUID and Version. I saw FileMetaInfo only had a getter and for some reason did not look futher.

For anyone else who is looking to set these tags I will provide a code snippet below:
There is DicomImplementation static class which contain static properties ClassUID and Version which can be set by the user.

If you want to have your own ImplementationClassUID and ImplementationVersionName. You can do it by using the following code.

```csharp

Dicom.DicomImplementation.ClassUID = new DicomUID(
"1.3.6.1.4.1.3782671.32893",    //custom uid
 "Custom UID Name",        
DicomUidType.Unknown);

Dicom.DicomImplementation.Version = "CustomImplementationVersionName"
```
