### ISSUE TITLE
fo-dicom changes the resolution of my Windows Form App

### ISSUE THREAD

**Issue by clairestrebva** [fo-dicom/fo-dicom#1595]
**Describe the bug**
My Windows form app looks like attached image **normal.PNG**

**To Reproduce**
When I browse to a DICOM file and click the Inspect FO button, it calls var file = DicomFile.Open(dicomFilePath); and then changes my application's resolution to look squished as shown in attached image **FO-DICOMchangedResolution.PNG** 

**Expected behavior**
The resolution should not be changed.

**Screenshots or test DICOM files**
See attached.

**Environment**
4.0.8
Windows Server 2016
.NET Framework 4.8

<img width="587" alt="normal" src="https://github.com/fo-dicom/fo-dicom/assets/96157389/88f4d10c-9e59-4ef3-a45b-8a8ecdcc0c6b">
<img width="391" alt="FO-DICOMchangedResolution" src="https://github.com/fo-dicom/fo-dicom/assets/96157389/8bcb7952-5dda-4fea-a027-a063b865f2a2">

**Comment by mrbean-bremen** [comment]
`DicomFile.Open` has nothing to do with the GUI, so I would guess that this is an artifact of how you has programmed your GUI - maybe you have given your view a "fit to content" property, or something like that.
I would say that it is very unlikely that this has anything to do with the `fo-dicom` library.

**Comment by clairestrebva** [comment]
Oops, I reported the wrong source code. This is the culprit: List<string> info = DicomTools.FoDicomInspect(InputFilePath);

**Comment by mrbean-bremen** [comment]
`DicomTools.FoDicomInspect` is also not part of `fo-dicom`. I guess that you use some `DicomTools` package that also uses `fo-dicom`, but there are many tools of this name out there, so I don't know which one you are using.

**Comment by clairestrebva** [comment]
Found the problem. It is indeed in FO-DICOM, but only happens when debugging in Visual Studio. If I run the EXE from File Explorer, the problem does not occur.
[Explanation on stackoverflow](https://stackoverflow.com/questions/49688458/when-i-use-fo-dicom-to-update-a-dicom-tag-the-c-sharp-form-changes-size)

**Comment by mrbean-bremen** [comment]
Ok, interesting... problems with the DPI scaling are unfortunally common in GUI frameworks (like WPF, Qt or others), I also have encountered them multiple times. Still not a fo-dicom issue in my book 😀
