### ISSUE TITLE
Unit test framework?

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#16]
I personally find the *MSTest* framework, that *fo-dicom* uses for its unit tests, rather limited. Furthermore, there are no real signs that the *MSTest* framework is actively being developed and extended, either.

Therefore, I am thinking it would be productive to switch to another unit test framework. 

The one that comes immediately to mind for me is [NUnit](http://nunit.org/) which I have a large experience with myself. 

Another one is [xUnit](http://xunit.github.io/) which has the additional benefit that it also supports a large number of non-.NET platforms such as Windows 8 (tablet/desktop), Windows Phone, Xamarin Android and Xamarin iOS. (In my [cureos](https://github.com/cureos/fo-dicom) fork of *fo-dicom* I am actually using *xUnit* myself, thanks to a very much appreciated contribution from @rickardraysearch.)

There are very few unit tests in *fo-dicom* right now, so now is a good time to switch unit test framework if we want to. Do we? Everyone, please share your thoughts.

**Comment by IanYates** [comment]
I'm an xUnit fan.   Are you using v1 or v2 at the moment?  I tried using v2 too early and a few test runners weren't ready for it but I think that's a long-solved problem now.

**Comment by anders9ustafsson** [comment]
@IanYates v2. Test runners seem to be working fine now, but I will double check.

**Comment by rickardraysearch** [comment]
The xUnit team's list of why they built xUnit is rather informative: https://github.com/xunit/xunit/wiki/Why-did-we-build-xUnit.net . Obviously, I vote for moving to xUnit, but both MSTest and NUnit are probably okay as well. Test runners work fine for me, both in Visual Studio and MSBuild.

**Comment by hiscodeness** [comment]
+1 for xUnit v2. I'm using it exclusively in my projects and haven't had issues with test runners in Visual Studio or on the CI server.

**Comment by anders9ustafsson** [comment]
Consensus seems to be that a switch of framework is recommended, and *xUnit* is the preferred framework to switch to. I am preparing a  pull request to resolve this issue.
