### ISSUE TITLE
checking for valid Window Center and Window Width values before using in GrayscaleRenderOptions

### ISSUE THREAD

**Issue by kb1234** [fo-dicom/fo-dicom#161]
GrayscaleRenderOptions.FromDataset looks at a Dataset to get an initial window/level value.  It first tries to get it from WindowWidth (0028,1051) and WindowCenter (0028,1050).  Prior to using the values in the header it confirms WindowWidth has a value and that it is !=0.

I suggest that we change the check for a valid WindowWidth to be (>=1), as specified in the standard.  I also suggest that we confirm WindowCenter has a value set before using it.

Changes would most likely be made around Ln 104 of GrayscaleRenderOptions.

**Comment by kb1234** [comment]
Also, I recommend that we adjust the checks that occur when using the smallest image pixel value (0028,0106) and largest image pixel value (0028,0107) to get the window.

Currently we perform the follwoing checks:
1) Both tags are present in the dataset.  This happens in GrayscaleRenderOptions.FromDataset.
2) That they are both not equal to zero in GrayscaleRenderOptions.FromImagePixelValueTags.  I don't think this check is what we really want.

I recommend that the checks be:
1) Both tags are present in the dataset.
2) That LargestImagePixelValue > SmallestImagePixel value.

**Comment by anders9ustafsson** [comment]
Thanks, @kb1234 . Will look into this soon.

**Comment by kb1234** [comment]
@anders9ustafsson I recommend changing line 112 & 113 to:
```
                && dataset.Get<int>(DicomTag.SmallestImagePixelValue)
                < dataset.Get<int>(DicomTag.LargestImagePixelValue))
```
If you permit them to be equal you will have a window of zero width, which probably should not be allowed.

And for consistency then line 163 should be:
```
            if (smallValue >= largeValue)
            {
                throw new DicomImagingException(
                    string.Format("Smallest Image Pixel Value ({0}) >= Largest Value ({1})", smallValue, largeValue));
            }
```

Sorry about not just making the changes myself.  I have only been using the nuget binaries and setting up a fo-dicom development environment is on my todo list.

**Comment by anders9ustafsson** [comment]
@kb1234 You are right, I will administer the change. Thanks for pointing this out.

**Comment by kb1234** [comment]
@anders9ustafsson  Thanks.
