### ISSUE TITLE
Dependency injection is not working as expected

### ISSUE THREAD

**Issue by amoerie** [fo-dicom/fo-dicom#1613]
**Describe the bug**
When you use Fellow Oak DICOM with a dependency injection container, simply calling .AddFellowOakDicom() is not sufficient. 
So, at the very least, I think our documentation is lacking in this area. 
I also believe that we should do better and that DicomSetupBuilder should not be necessary for the most common scenario.

**To Reproduce**
Given the following Program.cs (.NET 7 worker template)

```csharp
using FellowOakDicom;
using FellowOakDicom.Imaging;
using FellowOakDicom.Imaging.NativeCodec;

var host = Host.CreateDefaultBuilder(args)
    .ConfigureLogging(logging =>
    {
        logging.ClearProviders();
        logging.AddConsole();
    })
    .ConfigureServices(services =>
    {
        services.AddFellowOakDicom();
        services.AddImageManager<ImageSharpImageManager>();
        services.AddTranscoderManager<NativeTranscoderManager>();
        services.AddHostedService<Worker>();
    })
    .Build();

host.Run();

public class Worker : IHostedService
{
    private readonly ILogger<Worker> _logger;

    public Worker(ILogger<Worker> logger)
    {
        _logger = logger;
    }

    public async Task StartAsync(CancellationToken cancellationToken)
    {
        var dicomFile = await DicomFile.OpenAsync("testfile.dcm");
        var dicomImage = new DicomImage(dicomFile.Dataset);

        using var image = dicomImage.RenderImage();

        if (image is ImageSharpImage)
        {
            _logger.LogInformation("Success!");
        }
        else
        {
            _logger.LogError("Image is of type {ImageType}", image.GetType());
        }
    }

    public Task StopAsync(CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }
}
```

This produces the following log entries:

```log
fail: Worker[0]
      Image is of type FellowOakDicom.Imaging.RawImage
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
```

This fails because DicomImage.RenderImage statically retrieves the ImageManager, which is taken from DicomSetupBuilder.
However, DicomSetupBuilder is never configured automatically.

The workaround is this:

```csharp
var host = Host.CreateDefaultBuilder(args)
    .ConfigureLogging(logging =>
    {
        logging.ClearProviders();
        logging.AddConsole();
    })
    .ConfigureServices(services =>
    {
        services.AddFellowOakDicom();
        services.AddImageManager<ImageSharpImageManager>();
        services.AddTranscoderManager<NativeTranscoderManager>();
        services.AddHostedService<Worker>();
    })
    .Build();

/* This line must be added to get the expected behavior. I can't think of any other library that requires this. */
DicomSetupBuilder.UseServiceProvider(host.Services);

host.Run();
```

**Expected behavior**
I would expect that calling services.AddFellowOakDicom is sufficient.

**Screenshots or test DICOM files**
See example 

**Environment**
This is my .csproj file:

```xml
<Project Sdk="Microsoft.NET.Sdk.Worker">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="fo-dicom" Version="5.1.1" />
      <PackageReference Include="fo-dicom.Codecs" Version="5.10.6" />
      <PackageReference Include="fo-dicom.Imaging.ImageSharp" Version="5.1.0" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.1" />
    </ItemGroup>

    <ItemGroup>
      <None Update="testfile.dcm">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
```

**Comment by gofal** [comment]
I already was working on that and therefore created the project fo-dicom.AspNetCore.
fo-dicom.core gives you the basic functionality with the own DI containers so that it works in any simple console application. but in order to better integrate with the aspnetcore stack, this package should add more helper classes.

I have not found an obvious way, how to get the provider only be registering in ServiceCollection. 
Many libraries I saw required two calls in Startup class. One in ConfigureServices, where the services are added, and then one in Configure with an extensionmethod of IApplicationBuilder go get the IApplicationBuilder.ApplicationServices.

When searching for a way to avoid the two calls, I found a neat trick. AspNetCore has a special handling for services, that implement the interface IHostedService. After the serviceconfiguration is done, each registered service that implements this interface is created. So you can rely that the factory-method or the constructor of this hosted service is executed as soon as possible.
So I also register some empty IHostedService and within the factorymethod I set the serviceprovider.

See here: https://github.com/fo-dicom/fo-dicom/blob/development/Platform/FO-DICOM.AspNetCore/ServiceCollectionExtensions.cs

This project also has the applicationbuilder extention that I mentioned before, in case you are fine with the two calls in Startup class: https://github.com/fo-dicom/fo-dicom/blob/development/Platform/FO-DICOM.AspNetCore/ApplicationBuilderExtensions.cs

**Comment by amoerie** [comment]
Ah I failed to look at the AspNetCore project, I didn't expect such a solution to be present there! Thank you for pointing that out, this is already a big step in the right direction indeed. 
Is this already released and production ready? Because it's not listed in the nuget packages in the README. Speaking of which, do we need a new section in the README that explains how to configure Fellow Oak DICOM in ASP.NET Core applications? 

Additionally, I still feel that there are too many calls to Setup.ServiceProvider everywhere inside fo-dicom because the code base was written before DI was mainstream. 
If I look at the public API of Fellow Oak DICOM, there are not so many "entry points" for consumers of this library:
- DicomFile.Open(Async)
- DicomDirectory.Open(Async)
- DicomImage.ctor(DicomDataset)
- DicomServerFactory.Create
- DicomClientFactory.Create
(There are more who are more low level but still public, e.g. DicomTranscoder.ctor())

The last two already are injectable via DI, but also provide static APIs for applications that do not use DI, or simply for backwards compatibility.
Perhaps we should do the same thing for DicomFile and DicomDirectory? 
Ideally, there are no calls to Setup.ServiceProvider anywhere "deep" in the library, but only at the "top".

We already had some trouble in the unit tests to have different service providers, which you then cleverly solved with a service provider resolution mechanism based on the callstack and the test category attribute. Still, if we didn't do static resolution of the service provider anywhere in our tests, this trick would not have been needed.

In my company's test suite, we are running into a similar problem now. We make the "DicomSetupBuilder.UseServiceProvider" call when our application host is built, but since our (thousands of) tests run in parallel, it is now completely unpredictable which static ServiceProvider will be present according to Fellow Oak DICOM when, resulting in flaky tests. 
Essentially, we will have to disable parallelization (ouch) or implement the same call-stack based fix that is present in fo-dicom to avoid this problem, until fo-dicom itself makes it possible to use it without needing any underlying Setup.ServiceProvider calls.

So, I am seriously consider looking into a DicomFileFactory and DicomDirectoryFactory and see how much problems that would solve already.

**Comment by gofal** [comment]
No, the dicom.aspnetcore package is rather in a prove of concept state. But I have to omit, that this is the way how our company is integrating fo-dicom into the aspnetcore application. 

DI is only mainstream if you are working in aspnet in webapplication or hosted services. if working with destop applications or console tools or in library, then DI is not a big topic at all.
It's desired that fo-dicom is plugable into the asp.net DI environment, but it has to be clear, that it is also has to be easily usable without DI. 
Passing everything down from the top will propably not work - as you maybe remember from the logging, because there are many places down there in the networklayers where then a class or a parser just nueeds a logger instance and has to connection to the parent context. if you add references everywhere then the cleanup and potential memoryleaks will be harder.  And everywhere a fileaccess has to be done, just like simply in checking if a DicomFile is valid, the method DicomFile.HasValidHeader requires a FileReferenceFactory etc. 
It would be a lot of restructuring, potentially intruducing many issues, in my opinion currently not worth it.

With unittests, you can categorize them similar as we do in fo-dicom. Testrunners can be categorized to filter and not to run all tests. it's easy, just to run all tests with the same ServiceProvider in parallel and then all thests with the other service configuration in parallel, etc. So this problem is absolutely solvable.

**Comment by amoerie** [comment]
> DI is only mainstream if you are working in aspnet in webapplication or hosted services. if working with destop applications or console tools or in library, then DI is not a big topic at all.

I'm not sure I would agree with this assessment. We are using the generic host builder in all of our windows services, console applications, etc. as well, because you get a lot of nice stuff for free: 
- logging
- tracing
- metrics
- background services (in the shape of IHostedService)
- dependency injection (which is used by a lot of common logic, e.g. for database access)

Furthermore, by using dependency injection, we can integration test these console applications by hotswapping certain interfaces with test implementations. Unless you use parameter passing or some form of poor man's DI, I fail to see how you could achieve the same. 

But I digress, you're of course free to make your console applications any way you see fit.

> It's desired that fo-dicom is plugable into the asp.net DI environment, but it has to be clear, that it is also has to be easily usable without DI.

That goes without saying. It still needs work in .NET Framework, where DI is rarely used.
That is why I had something like the following in mind:

**DicomFile.cs**

```csharp
/// <summary>
/// Asynchronously read a DICOM file from stream.
/// </summary>
/// <param name="stream">Stream to read.</param>
/// <param name="fallbackEncoding">Encoding to use if encoding cannot be obtained from DICOM file.</param>
/// <param name="stop">Stop criterion in dataset.</param>
/// <param name="readOption">The option how to deal with large DICOM tags like pixel data.</param>
/// <param name="largeObjectSize">Custom limit of what are large values and what are not. If 0 is passend, then the default of 64k is used.</param>
/// <returns>Awaitable <see cref="DicomFile"/> instance.</returns>
public static Task<DicomFile> OpenAsync(Stream stream, Encoding fallbackEncoding,
    Func<ParseState, bool> stop = null, FileReadOption readOption = FileReadOption.Default,
    int largeObjectSize = 0)
    => OpenAsync(Setup.ServiceProvider.GetRequiredService<IMemoryProvider>(), stream, fallbackEncoding, stop,
        readOption, largeObjectSize);

internal static async Task<DicomFile> OpenAsync(IMemoryProvider memoryProvider, Stream stream, Encoding fallbackEncoding, Func<ParseState, bool> stop = null, FileReadOption readOption = FileReadOption.Default, int largeObjectSize = 0)
{
    if (fallbackEncoding == null)
    {
        throw new ArgumentNullException(nameof(fallbackEncoding));
    }
    var df = new DicomFile(memoryProvider);

    // ... rest of the code omitted for brevity
}
```

Then, there would be a new file 

**DicomFileFactory.cs**

```csharp
public interface IDicomFileFactory
{
    /// <summary>
    /// Asynchronously read a DICOM file from stream.
    /// </summary>
    /// <param name="stream">Stream to read.</param>
    /// <param name="fallbackEncoding">Encoding to use if encoding cannot be obtained from DICOM file.</param>
    /// <param name="stop">Stop criterion in dataset.</param>
    /// <param name="readOption">The option how to deal with large DICOM tags like pixel data.</param>
    /// <param name="largeObjectSize">Custom limit of what are large values and what are not. If 0 is passend, then the default of 64k is used.</param>
    /// <returns>Awaitable <see cref="DicomFile"/> instance.</returns>
    Task<DicomFile> OpenAsync(Stream stream, Encoding fallbackEncoding, Func<ParseState, bool> stop = null,
        FileReadOption readOption = FileReadOption.Default, int largeObjectSize = 0);

    // ..other Open methods omitted for brevity
}

public class DicomFileFactory : IDicomFileFactory
{
    private readonly IFileReferenceFactory _fileReferenceFactory;
    private readonly IMemoryProvider _memoryProvider;

    public DicomFileFactory(IFileReferenceFactory fileReferenceFactory, IMemoryProvider memoryProvider)
    {
        _fileReferenceFactory = fileReferenceFactory ?? throw new ArgumentNullException(nameof(fileReferenceFactory));
        _memoryProvider = memoryProvider;
    }

    public Task<DicomFile> OpenAsync(Stream stream, Encoding fallbackEncoding, Func<ParseState, bool> stop = null,
        FileReadOption readOption = FileReadOption.Default, int largeObjectSize = 0)
        => DicomFile.OpenAsync(_memoryProvider, stream, fallbackEncoding, stop, readOption, largeObjectSize);

    // ..other Open methods omitted for brevity
}
``` 

_pros_:

- No breaking changes. All existing APIs still work.
- Implementations stay 99% in the same place, we just need one extra call in the call stack
- No more `Setup.ServiceProvider` needed after this. References to `MemoryProvider`, `FileReferenceFactory` are passed down where needed.
- People who inject and use `IDicomFileFactory` will not even have any calls to Setup.ServiceProvider at all.
- We could remove our call stack based ServiceProviderHost in the unit tests

_cons_:

- More factories. To do this properly, we will probably need a DicomFileFactory, DicomDirectoryFactory and DicomImageFactory at the least. Perhaps better names could be found too, like DicomFileOpener instead of DicomFileFactory.
- Especially `MemoryProvider` goes quite deep, so like you said, this change would touch code in a lot of places. However, I think the risk of breaking things could be lower than you think at first sight.

> So this problem is absolutely solvable.

Sure! Although I would prefer to call it a "workaround" rather than a "solution". :-) 
I still believe that having the service locator pattern scattered throughout our code base is not so great.

**Comment by amoerie** [comment]
"shower thought": it might make more sense to move the actual logic of opening a DicomFile to this new DicomFileFactory. That would make the code better maintainable in the future when new dependencies are needed.

On the other hand, I will run into scoping issues. For example, the various implementations of DicomPixelData are private, so these would need to move along with the factory method.

**Comment by amoerie** [comment]
Closing this for now because it would be a large breaking change, mostly for our internal tests really. I'm still in favour of making the change, so I might revisit later. 

So, to anyone reading this, DicomSetupBuilder.UseServiceProvider is still what you need.
