### ISSUE TITLE
How to show a Dicom image on Avalonia/WPF?

### ISSUE THREAD

**Issue by helderc** [fo-dicom/fo-dicom#1614]
Hi all. I'm trying to show a Dicom image using Avalonia UI without success.

I've read many threads already and the code I put together (copied from many sources) is as follows:

```CSharp
# to allow conversion to SharpImage
new DicomSetupBuilder()
    .RegisterServices(s => 
        s.AddFellowOakDicom()
            .AddImageManager<ImageSharpImageManager>())
    .Build();
```
and them
```CSharp
DicomFile dicomFile = DicomFile.Open("img.dcm");
DicomImage dicomImage = new DicomImage(dicomFile.Dataset);

// Convert the DICOM image to a Bitmap for display
var local_img = dicomImage.RenderImage().AsSharpImage();
```

The problem is after the line above. How can I go from that `SharpImage` to `Bitmap`?
I really appreciate any help you can provide.

**Comment by s004183** [comment]
Hello,

I am developing a process to get frames from DICOMFILE, change size and re-encapsulate to DICOM in OT SopClass. 
This is part of the method I use to extract from a Dicom.Dataset the frame in jpg format.

new DicomSetupBuilder().RegisterServices(s => s.AddFellowOakDicom().AddImageManager<WinFormsImageManager>()).Build();

DicomFile dicomFile = DicomFile.Open("img.dcm");
DicomImage dicomImage = new DicomImage(dicomObject, frame); <- this process for each frame...
var image = dicomImage.RenderImage(frame).As<Image>();
          
//at this point, you can return as Bitmat, as Bitmap in filestream in memory stream... etc.
//for my process, I write to file the frame...    
image.Save(imageFile, ImageFormat.Jpeg);
        }

**Comment by helderc** [comment]
Thanks for your reply.

In this line:
`new DicomSetupBuilder().RegisterServices(s => s.AddFellowOakDicom().AddImageManager()).Build();`
What do you use in the `AddImageManager()`? I guess it should be something like `AddImageManager<SOMETHING>()`.
`Bitmap` doesn't work there.

**Comment by s004183** [comment]
Yes, you are correct! 

new DicomSetupBuilder().RegisterServices(s => s.AddFellowOakDicom().AddImageManager`<`WinFormsImageManager`>`())             .Build();

var dicomImage = new DicomImage(dicomObject, frame);

var image = dicomImage.RenderImage(frame).As`<`Image`>`();

And, to get FrameCount I use this method:

        public int DicomFileFrameCount(DicomDataset ds)
        {
            var pixelDataItem = ds.GetDicomItem`<`DicomItem`>`(DicomTag.PixelData);

            if (pixelDataItem == null) return -1;

            if (ds.Contains(DicomTag.NumberOfFrames))
            {
                return ds.GetSingleValue`<`int`>`(DicomTag.NumberOfFrames);
            }
            return 1;
        }

Previously check that DICOMFILE not contains encapsulated object like PDF, DoseReport in XML format, etc.

**Comment by helderc** [comment]
Thanks again for the reply.

I'm just wondering, does this `<WinFormsImageManager>` works on WPF for you? 
To me, it doesn't. I believe its for Windows Forms based projects only.

**Comment by s004183** [comment]
Yes, it's only for windows projects. Using NuGet fo-dicom.imaging.Desktop
I am using it inside a webapi project. 
Sorry.

**Comment by helderc** [comment]
> Yes, it's only for windows projects. Using NuGet fo-dicom.imaging.Desktop I am using it inside a webapi project. Sorry.

Ok, no problem.

**Comment by DavidVCSousa** [comment]
Hello , not sure if you solved your problems to show DICOM images , so I'll explain an short step by step on WPF , just to be fair and clear with you never used it on Avalonia or other multiplatform project , and the usage on it might be a bit different, but I sure it Works with .NET Framework and hope it will help you.

First when using the newer versions of fo-dicom (e.g.  versions >= 5.0.0.0)  we need to register the services we gonna use such as 

```c#
new DicomSetupBuilder().RegisterServices(s => s.AddFellowOakDicom().AddImageManager<FellowOakDicom.Imaging.WPFImageManager>().AddTranscoderManager<NativeTranscoderManager>()).Build();
```  
Note as show in code above we use `.AddImageManager<FellowOakDicom.Imaging.WPFImageManager>` instead to `.AddImageManager<FellowOakDicom.Imaging.WinFormsImageManager>` for getting proper WPF native image sources such as `BitmapSource` or `ImageSource`  , and we added `.AddTranscoderManager<NativeTranscoderManager>()` which can be acquired with fo-dicom.Codecs [https://github.com/Efferent-Health/fo-dicom.Codecs](url), to support more DICOM codecs and be able to render them.

So to get the image for rendering on an `System.Windows.Controls.Image`  for example ,all we gonna need is an instance of `DicomImage` which can be done by using an `DicomDataset` or with the file path

```c#
string fileName = $@"D:\Exams\CT\3d745496833af936550c7c445cd4990f\series-000001\image-000001.dcm";

DicomImage dicomImage = new DicomImage(fileName);
ImageSource src = dicomImage.RenderImage().As<ImageSource>();

```

**Comment by helderc** [comment]
Thanks @DavidVCSousa .

I gave up on Avalonia/WPF in favour of WinForms.

To help other people that may find this thread, you have to install not only the `fo-dicom.Codecs` but also the `fo-dicom.Imaging.Desktop`.

I still couldn't solve the import needed for `ImageSource`.

**Comment by gofal** [comment]
In order to display images in WPF, you need any instance deriving from ImageSource. This is not platform independent and only works in WindowsDesktop, this is why you have to add the nuget package `dicom.Imaging.Desktop`.
Then on initialization you have to register the `WpfImageManager`. There is a code snipped that is shipped here in this github repository with the litte DicomDump-tool

```
     public MainWindow()
        {
            InitializeComponent();

            new DicomSetupBuilder()
                .RegisterServices(s => s
                    .AddFellowOakDicom()
                    .AddTranscoderManager<NativeTranscoderManager>()
                    .AddImageManager<WPFImageManager>())
                .Build();
        }
```
This package also has an extension Method `FellowOakDicom.Imaging.WPFImageExtensions.AsWriteableBitmap(this IImage image)` which converts an `IImage` generated by fo-dicom to a `WriteableBitmap`, a WPF class implementing ImageSource.

```
      // _image is of type DicomImage and ImageView is a WPF-control of type System.Windows.Controls.Image
            var img = _image.RenderImage(_frameNumber);
            var wpfImage = img.AsWriteableBitmap();

            ImageView.Source = wpfImage;
```
