### ISSUE TITLE
Specific character set doesn't not comply with standards

### ISSUE THREAD

**Issue by deksan** [fo-dicom/fo-dicom#1624]
**Describe the bug**
DicomEncoding.GetCharset returns ISO IR 192 for utf-8 and should instead return ISO_IR 192. 

**To Reproduce**
I send a dataset after setting the DicomTag.SpecificCharset :
```c#
var ds = new DicomDataset();
var encoding = Encoding.GetEncoding(CustomEncoding);
var charset = DicomEncoding.GetCharset(encoding);
ds.AddOrUpdate(DicomTag.SpecificCharacterSet, charset);
``` 

The resulting encoding is ISO IR 192 instead of ISO_IR 192 in the dataset.

**Expected behavior**
We should have ISO_IR 192 isntead

**Environment**
Fellow Oak DICOM version: 5.1.1
OS: Windows 11 x64
Platform:  .NET Framework 4.6.2

**Comment by mrbean-bremen** [comment]
Thank you - that is indeed a bug in `GetCharset` that I may have introduced some time ago.
