### ISSUE TITLE
Documentation: Usage of AdvancedDicomClient correct?

### ISSUE THREAD

**Issue by ayedo** [fo-dicom/fo-dicom#1641]
In the README the following usgage of the AdvancedDicomClient is shown: 

![image](https://github.com/fo-dicom/fo-dicom/assets/4739734/c46f53bf-1d5d-47a0-a1b4-45fe7cbaa03d)

Why is there a using on the Association but also in the finally block `ReleaseAsync` is called? Why not release all resources already in the dispose call?

Thanks and best,

Alon

**Comment by gofal** [comment]
This is, because the "ReleaseAsync" is not an internal cleanup of objects, as the disposing is, but the "ReleaseAsync" is a DICOM-action where an AssociationReleaseRequest is sent via network and then a AssociationReleaseResponse is expected. This is rather a very certain SendReqeustAsync.
