### ISSUE TITLE
Setting FallbackEncoding on AdvancedDicomClientConnectionRequest has no effect on C-Find requests

### ISSUE THREAD

**Issue by ayedo** [fo-dicom/fo-dicom#1642]
Hello everybody.

First of all, thank you very much for your work on fo-dicom! I think we might have found a bug regarding the application of the fallback encodings.

**Describe the bug**
We are retrieving modality worklist items from a PACS that does not send a Specific Character Set Attribute. We would like to allow the user to configure what the expected character set might be. We tried setting FallbackEncoding, but it has no effect. 

**To Reproduce**

Send a modality work list c-find request with the FallbackEncoding set to something that is not Encoding.Default to a PACS or test server that does not return the Specific Character Set Attribute, and look at the result, it will always be decoded with Encoding.Default.

If you want you can use the public IHE order manager as a test system that does not return the attribute. I'm not sure if you can access it? I think it uses dcmtk underneath. 

I looked at the code, and I think the issue here might be related [to this one]( https://github.com/fo-dicom/fo-dicom/issues/1159), but I lack the deep understanding of the library to be sure, and even to create a test case.

**Expected behavior**
I expect the fallback encoding to be applied.

**Environment**
Fellow Oak DICOM version: 5.1.1
OS: macOS 12.6.7
Platform: net6.0

**Comment by gofal** [comment]
great someone found a soluntion, but saddly immediatelly closed the issue without doing a PR, so the bug stayed in the library.
