### ISSUE TITLE
'IImage' does not contain a definition for 'AsTexture2D'

### ISSUE THREAD

**Issue by Xbathy** [fo-dicom/fo-dicom#1643]
**Describe the bug**
I want to use fo-dicom in Unity, and want to cast IImage to Texture2d.
i miss some library?
https://github.com/fo-dicom/fo-dicom/wiki/Image-rendering
```
 DicomImage di = new DicomImage("example");
 IImage image = di.RenderImage().AsTexture2D();
```
**To Reproduce**
unity 2021.3.14
![image](https://github.com/fo-dicom/fo-dicom/assets/63304916/4ab794ff-06ed-4d3c-ae6c-73ca688e2e92)
and these .

**Expected behavior**
no exception.

**Screenshots or test DICOM files**
If applicable, add screenshots or test DICOM files to help explain your problem.

**Environment**
Fellow Oak DICOM version:5.1
OS:  Windows 10 x64
Platform: Unity

**Comment by Xbathy** [comment]
https://github.com/fo-dicom/fo-dicom/discussions/1248   solved.

**Comment by gofal** [comment]
so you are doing Unity with the latest version? 
Sadly I have no experience in Unity, but there are several questions from time to time about using the current version in Unity. So if you update the unity-library to the current version or do any other fix, a PR would be very welcome. Thanks!

**Comment by Xbathy** [comment]
[Unity Renderer Imp.zip](https://github.com/fo-dicom/fo-dicom/files/12393017/Unity.Renderer.Imp.zip)
There is the implementation of [IImage Rendering](https://github.com/fo-dicom/fo-dicom/wiki/Image-rendering). Use fo-dicom 5.1.1 and Unity 2021.3.14 . also run on Hololens2 succeed! Because the implementation dependent on Unity's namespace, so I upload the plugin here, platform specific .
 And  
`new DicomSetupBuilder()
            .RegisterServices(s => s.AddFellowOakDicom().AddImageManager<UnityImageManager>())
            .Build();` first.
Thanks to the authors for such good project and @anders9ustafsson provide the original implementation !
