### ISSUE TITLE
Being able to compare datasets

### ISSUE THREAD

**Issue by JoakimRaySearch** [fo-dicom/fo-dicom#1658]
**What is, according to you, missing from fo-dicom? Please describe.**
A simple and intuitive way of comparing datasets.

**Describe the solution you'd like**
Overload == etc and implement IEquatable<DicomDataset> for DicomDataset. Can use the existing DicomDatasetComparer.

**Describe possible alternatives or existing workarounds you've considered**
Not really. I don't see any good reasons for why this shouldn't be?

**Comment by ViktoriaSalociova** [comment]
@gofal Hello, I'd like to work on this as part of the Hacktoberfest :) Can I assign myself to this task? Thanks!

**Comment by gofal** [comment]
Great, thank you! A good story to do for Hacktoberfest.

**Comment by gofal** [comment]
If I can leave some wishes, would be great to have some options in the IComparer or to have different IComparers to set the degree of equality. Eg is one dataset is missing private tags but all others are equal, are the datasets then equal or not? Or if there are the same values, but the datasets are in different transfersyntax or different Encodings (ansi or utf8), are they then already different? Or should (for performance reasons) the pixeldata also be compared or does the comparer only check the "Header-Tags".

**Comment by ViktoriaSalociova** [comment]
Thanks, I will make some suggestions including your mentioned wishes and get in touch with you. Do you still use gitter for communication?

**Comment by gofal** [comment]
no, gitter became too messy and there was no chance to organize the threads.

**Comment by ViktoriaSalociova** [comment]
Okay, providing update: Still working on the issue, as my first issue it takes longer, but will make PR till end of october 🤞 :)

**Comment by ViktoriaSalociova** [comment]
@gofal Hello, can you please run the pipeline and check the PR? 👀 Your input would be a valuable contribution for me to earn Hacktoberfest points for my university project. Thank you! :)

**Comment by gofal** [comment]
merged in #1668
