### ISSUE TITLE
System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=6.0.0.0

### ISSUE THREAD

**Issue by rakip24** [fo-dicom/fo-dicom#1659]
Upgraded from version 4 to 5 and trying to create a dicom client in order to send a dicom file to a server but running into an issue with 'Microsoft.Extensions.DependencyInjection'
Getting the below error message when trying to call FellowOakDicom.Network.Client.IDicomClient client = FellowOakDicom.Network.Client.DicomClientFactory.Create(remoteHost, remoteHostPort, tlsInitiator, localAeTitle, remoteAeTitle);

System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.'

**Environment**
Fellow Oak DICOM version: (e.g. 5.1.1)
OS: (e.g. Windows 8.1 x64)
Platform: (e.g. .NET Framework 4.6.2)

**Comment by gofal** [comment]
fo-dicom is a .net standard library. and depends on the following packages:
https://www.nuget.org/packages/fo-dicom#dependencies-body-tab

While .net core seems to behave better and load all these dependencies automatically, i also observed, that I had to add those nuget packages to the netframework manually.

So you have to open the nuget packet manager and add those packages manually, if your IDE doesn't do that for you automatically.

**Comment by gofal** [comment]
if someone has a tip, how to improve this behavior so that these packages are added automatically also on netframework projects, then I'd be happy to add this to the project.

**Comment by rakip24** [comment]
Thanks for the response @gofal. Appreciate it.
