### ISSUE TITLE
Unsupported Transfer Syntax Error for Lossy JPEG 8 Bit Image Compression in fo-dicom on .NET 7.0

### ISSUE THREAD

**Issue by jamesnet214** [fo-dicom/fo-dicom#1667]
Certainly! Here's a more detailed bug report:

---

**Describe the bug**
When trying to convert a DICOM image to bitmap using the fo-dicom library, I encounter an error stating "Decoding dataset with transfer syntax: JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression is not supported." This issue does not appear when using the externally provided dicom.Core.dll for .NET Framework 4.81.

**To Reproduce**
1. Clone the repository: [https://github.com/jamesnet214/issue](https://github.com/jamesnet214/issue)
2. Navigate to the `DicomTestViewer` project.
3. Run the application and try to load the DICOM file from the specified location.
4. Observe the error on line 108 in `Class1.cs` when calling the `image.AsSharpImage();` method.

**Expected behavior**
The DICOM image should be successfully converted to a bitmap without any codec errors.

**Screenshots or test DICOM files**
The error screenshot can be viewed here:
![image](https://github.com/fo-dicom/fo-dicom/assets/52397976/79d58a96-c0b6-430e-9588-6f3b11ec06a3)

Code for reference:
[https://github.com/jamesnet214/issue/blob/main/dotnet/dicom/DicomTestViewer/JamesCoreViewer/Class1.cs](https://github.com/jamesnet214/issue/blob/main/dotnet/dicom/DicomTestViewer/JamesCoreViewer/Class1.cs)

Test DICOM file:
[https://github.com/jamesnet214/issue/blob/main/dotnet/dicom/DicomTestViewer/JamesCoreViewer/Data/studylist/A2C/1.dcm](https://github.com/jamesnet214/issue/blob/main/dotnet/dicom/DicomTestViewer/JamesCoreViewer/Data/studylist/A2C/1.dcm)

**Additional context**
The functionality works as expected when using `dicom.Core.dll` for .NET Framework 4.81, suggesting there might be a compatibility or implementation issue with the `fo-dicom` library in .NET 7.0. 

**Environment**
- Fellow Oak DICOM version: 5.1.1
- OS: Windows 11
- Platform: .NET 7.0

---

I hope this expanded description helps. If there's anything else you'd like to add or if you have further questions, please let me know!

**Comment by cocosip** [comment]
You are missing the injection of NativeTranscoderManager

```c#
... 
services
    .AddFellowOakDicom()
    .AddTranscoderManager<NativeTranscoderManager>()
    .AddImageManager<ImageSharpImageManager>();

```

**Comment by amoerie** [comment]
Looks like ChatGPT didn't realize those were needed. 🙃
