### ISSUE TITLE
Send(Async)_MultipleTimes_AllRecognized unit tests pass locally but fail on CI server

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#167]

**Comment by IanYates** [comment]
So I guess this still isn't quite right based on the comments in #169.

I'll see if I can get the unit tests, or even a simple console app, running to the point where it causes this problem without needing the CI server.

Have you had any chance reproducing it locally, even sporadically?

**Comment by anders9ustafsson** [comment]
@IanYates The commits you see referenced here are some attempts I have made to solve the problem. Unit tests pass locally, but I have still  not made them to pass on the CI server. The tested commits have all been rolled back, so none of them appears in the main repository right now.

I have not been able to reproduce it locally yet. What I have done is to set up a CI server for my personal *fo-dicom* fork, so that I can test on the CI server without interfering with the main repository. 

In summary, my impression is that the failure is due to the combination of the fact that `AddRequest` calls `SendRequest` if the service is existing and connected ([here](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Network/DicomClient.cs#L112)) and also that a new service object is set up every time `Send(Async)` is called ([here](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Network/DicomClient.cs#L304)). It should also be taken into account that the service performs asynchronously without control of the consuming code.

**Comment by anders9ustafsson** [comment]
Just tested the `Send_...` unit test with 200 iterations on version 1.1, running on the CI server, and the test still fails (although the number of succeeded requests is 77 whereas it has normally been 1 with the 2.0 implementation...). Also interesting to note that the test time is substantially longer with 1.1 (52 seconds) compared to 2.0 (0.5 seconds). If we can just get the tests to succeed on 2.0 it seems like we have been able to implement a substantial performance boost :-)

**Comment by Thunderstriker** [comment]
For each request the SetComplete inside DicomServiceUser is triggered 3 times. after the first time the main thread will resume and trigger the 2nd Send but the this one will go straight into the FinalizeSend as by now the SetComplete from the first request is triggered again.
if i remove the SetComplete from 2 of the 3 places (OnReceiveAssociationReleaseResponse, OnConnectionClosed, WaitForDisconnect) it works fine even at 1000 iterations.
I know SetComplete is required in all 3 place so this is not the solution

**Comment by anders9ustafsson** [comment]
@Thunderstriker Sorry for the late response, holidays have been the main focus for a couple of days :-) Many thanks for checking this out. I have a few ideas of what I need to do, and your observations are very valuable for the continued work. I'll keep you posted about my progress.
