### ISSUE TITLE
Static dicom dictionary initialisation - race condition remains

### ISSUE THREAD

**Issue by IanYates** [fo-dicom/fo-dicom#168]
As per https://groups.google.com/forum/#!topic/fo-dicom/36xK6qUHt3Y

The issue is that our double-check lock has the _default value set too early.  There's a chance a reader could be given _default and begin using it before the thread that won the initialisation race has actually finished initialising it.

**Comment by IanYates** [comment]
I'll fix it by moving the setting of `_default` to the end of the initialisation.

What I'd like to discuss in a separate issue is whether or not it even makes sense to allow the default `DicomDictionary` to be initialised twice.  If not then we can simply make it a private `Lazy<DicomDictionary>`.  If it does make sense then we can still use `Lazy<>` behind the scenes.

@anders9ustafsson - I don't have any Xamarin stuff installed but I assume `Lazy<>` is present there, correct?

**Comment by anders9ustafsson** [comment]
@IanYates `Lazy<>` is included in Xamarin as well, so no problems with that. It sounds like a good change to use `Lazy<>` for this purpose. I was (too?) quick with accepting your pull request #169, but if you want to switch to lazy initialization now maybe you can post another pull request.

**Comment by IanYates** [comment]
Hi @anders9ustafsson  - no problem.  I think it's good to get that PR in anyway and then think about `Lazy<>`.

From a real-world point of view, should we even allow a setter on the DICOM dictionary?  Or if we do, is it something that people would want to set more than once?  
Basically, can we treat it like the platform support libraries where there's a sensible default in place and if you want to override it (eg WPF instead of Winforms) then you do that up-front in your app.  If that's the case then we can do away with the setter entirely and have a custom init method that end-users can call and we make the default initialisation routine private.

It's not "broken" at the moment but I genuinely curious as to the real-world need to be able to swap out the dictionary at any time.

**Comment by Reproduktor** [comment]
Hi folks,
I think [this] (https://github.com/cureos/fo-dicom/commit/ea1a36a8aad280f6fb21b59583e1222dea7e7f0d) was solving the same issue. But the obvious disadvantage is that lock on property's get...

**Comment by IanYates** [comment]
Hey @Reproduktor - that's certainly a fine solution too since the `LoadInternalDictionaries` method is private and it's only called through the getter.  Therefore there's no race within that method.

It's interesting that it is a private method there...  Perhaps we can make it private in mainstream fo-dicom too after all?

**Comment by anders9ustafsson** [comment]
@IanYates As part of an enhancement @rcd recently made to prevent the private dictionary from being loaded (PR #84) the method was declared `public`. That is also the reason why it is now called in *DICOM Dump*.

**Comment by IanYates** [comment]
Ahh - thanks for the history lesson :)

We'll keep it that way then.  Except that I still am not so sure we need to permit it being called more than once, or the setter being accessed more than once...  Do you think we could still tighten it a bit that way?

**Comment by anders9ustafsson** [comment]
@IanYates Which means that the user needs to set `Default` before getting it, alternatively call `EnsureDefaultDictionariesLoaded` before getting `Default` the first time? And the `Default` setter should throw if `_default` is already defined?

At this stage this seems like a reasonable compromise to me. Can you take care of this update?

**Comment by IanYates** [comment]
Happy to :)  

For 99% of users it'll make no difference, which is what we want.  For those who want to customise it, the'll do it first thing and get an error if they fiddle with the dictionary afterwards (which is better than mysterious changing behaviour)

**Comment by IanYates** [comment]
PR on its way for this...
