### ISSUE TITLE
Dependency Injection error prevents me from passing an object to CStoreSCP

### ISSUE THREAD

**Issue by saschke** [fo-dicom/fo-dicom#1682]
**Describe the bug**
Whe creating an Instance of a CStoreSCP using this code

 var storageConfiguration = new StorageConfiguration(StoragePath, FileNameExtension, AeTitle);

 _server = DicomServerFactory.Create<CStoreSCP>(
     IpAddress, Port, 
     userState: storageConfiguration);

using the sample code of FO-Dicom only adding the userState - parameter it seems to work and the _server is listening  but when I echo the _server I get an exception:

[ERROR] Exception listening for DICOM services, System.InvalidOperationException: Unable to resolve service for type 'System.Object' while attempting to activate 'DicomCommunication.DicomStorageScpNonStatic.DicomStorageScp+CStoreSCP'.
   bei Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   bei lambda_method(Closure , IServiceProvider , Object[] )
   bei FellowOakDicom.Network.DicomServer`1.CreateScp(INetworkStream stream)
   bei FellowOakDicom.Network.DicomServer`1.<ListenForConnectionsAsync>d__56.MoveNext()

**To Reproduce**
Use the code above, if I leave 'userState: storageConfiguration' away it works but I should be able to pass information to the StorageSCP instance.

**Expected behavior**
I would expect this to work as I use the proper parameters.

for this version of access

 public static IDicomServer Create<T>(
   string ipAddress,
   int port,
   string certificateName = null,
   Encoding fallbackEncoding = null,
   Logger logger = null,
   object userState = null)
   where T : DicomService, IDicomServiceProvider
 {
   return Setup.ServiceProvider.GetRequiredService<IDicomServerFactory>().Create<T>(ipAddress, port, certificateName, fallbackEncoding, logger, userState);
 }

Can you tell me what I am missing? 

**Environment**
Fellow Oak DICOM version: (e.g. 5.0.3.0 but I also get the same error in the newest version)
OS: (e.g. Windows 11)
Platform: (e.g. .NET Framework 4.7.2 but also .NET 7)

**Comment by amoerie** [comment]
Can you please review the diagnostic questions here: https://github.com/fo-dicom/fo-dicom/issues/1611 
You're probably running into one of these root causes.

**Comment by amoerie** [comment]
See https://github.com/fo-dicom/fo-dicom/pull/1812

If a scenario is not working for you, please open a separate issue. Custom dependencies are supported.
