### ISSUE TITLE
HTJ2K Support

### ISSUE THREAD

**Issue by jaime-olivares** [fo-dicom/fo-dicom#1687]
HTJ2K is the new encoding format for DICOM. Refer to this discussion: https://github.com/Efferent-Health/fo-dicom.Codecs/issues/54

fo-dicom should support this new format, now that it has the transfer syntax UID's assigned. Read page 7 of https://dicom.nema.org/medical/dicom/Final/sup235_ft_HTJ2K.pdf 

The list of new UID's are:

Mime type|UID|Description
-|-|-
|image/jphc|1.2.840.10008.1.2.4.201|High-Throughput JPEG 2000 Image Compression (Lossless Only)
||1.2.840.10008.1.2.4.202|High-Throughput JPEG 2000 with RPCL Options Image Compression (Lossless Only)
||1.2.840.10008.1.2.4.203|High-Throughput JPEG 2000 Image Compression

Short list of actions:
- Introduce the new UID's in fo-dicom (a.s.a.p)
- Get samples for each transfer syntax
- Introduce the corresponding codecs into do-dicom.Codecs

**Comment by gofal** [comment]
With the current release fo-dicom was updated to DICOM Standard 2023e, so the new UIDs are now included in fo-dicom. So first action is done.

**Comment by jaime-olivares** [comment]
We started the analysis to implement in fo-dicom.Codecs

**Comment by gofal** [comment]
> We started the analysis to implement in fo-dicom.Codecs

Many, many thanks!

**Comment by jaime-olivares** [comment]
This is in beta phase already. Have deployed to nuget the codecs, along with a forked version of fo-dicom for recognizing the transfer syntax.

**Comment by jaime-olivares** [comment]
HTJ2K is now supported with fo-dicom 5.1.3 and fo-dicom.Codecs 5.14.0
