### ISSUE TITLE
Could not decode string '????' with given encoding, using replacement characters.

### ISSUE THREAD

**Issue by topstop3416** [fo-dicom/fo-dicom#1705]
**Describe the bug**
Could not decode "PatientName"
dcmtk dcmdump is ok

**Environment**
Fellow Oak DICOM version: 5.1.1
OS: Windows 10 x64
Platform: .NET 8

![QQ截图20231222194749](https://github.com/fo-dicom/fo-dicom/assets/37021873/e44741af-abf8-4b68-8125-cbb13f9a98d6)

![QQ截图20231222194639](https://github.com/fo-dicom/fo-dicom/assets/37021873/953afdf4-3932-4bfd-82b4-0ba100004cf9)

**Comment by mrbean-bremen** [comment]
It looks like `Specific Character Set` is not defined in your DICOM data. In this case, ASCII is assumed according to the DICOM standard, and `fo-dicom` is basically correct here.
The fact that `dcmdump` shows it correctly may be to to some heuristic in the code that guesses the encoding, or it uses some local encoding. Try to set `SpecificCharacterSet` to GBK (or whatever the actual encoding is) in your dataset and check again.

**Comment by gofal** [comment]
When opening a file with `DicomFile.Open(string filename, Encoding fallbackEncoding)` you can specify the encoding to use in case the DicomFile is missing the Special Character Set.

**Comment by topstop3416** [comment]
> When opening a file with you can specify the encoding to use in case the DicomFile is missing the Special Character Set.`DicomFile.Open(string filename, Encoding fallbackEncoding)`

very good,but how to do in OnCStoreRequestAsync
```c#
public async Task<DicomCStoreResponse> OnCStoreRequestAsync(DicomCStoreRequest request)
{
    request.Dataset.AddOrUpdate(DicomTag.SpecificCharacterSet, "GB18030");// invalid
    request.Dataset.GetSingleValueOrDefault(DicomTag.PatientName, "")
}
```

**Comment by mrbean-bremen** [comment]
BTW, there is still #1654 open that applies the fallback encoding to a response and may help here. That PR has been forgotten somehow, I think...

**Comment by topstop3416** [comment]
> BTW, there is still #1654 open that applies the fallback encoding to a response and may help here. That PR has been forgotten somehow, I think...

I am a beginner and I use translation software. This problem seems to be unsolvable at the moment.

**Comment by mrbean-bremen** [comment]
What I mean is that there is already a fix to the problem that has not been merged that. If it will be merged, the fix will be in the next release.

**Comment by gofal** [comment]
The PR is already merged
