### ISSUE TITLE
Trying to understand GetPrivateTag function of DicomDataset

### ISSUE THREAD

**Issue by aerik** [fo-dicom/fo-dicom#1716]
So I don't think I can say this is a bug, I just may be misunderstanding the code.  I read the standard https://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_7.8.html

and this section in particular (7.8.1.b) :

> Private Creator Data Element (gggg,0010) is required in order to identify Data Elements (gggg,1000-10FF) if present, Private Creator Data Element (gggg,0011) is required in order to identify Data Elements (gggg,1100-11FF) if present, through Private Creator Data Element (gggg,00FF), which identifies Data Elements (gggg,FF00-FFFF) if present.

So that says you need a creator element for each chunk of data elements of up to FF size, and that the creator element has to match the first two hex components of all it's corresponding data elements... right?

Okay, so then I go look at the code.  The method "GetPrivateTag" is all over DicomDataset

```
/// <summary>
/// Converts a dictionary tag to a valid private tag.
/// </summary>
/// <param name="tag">Dictionary DICOM tag</param>
/// <param name="createTag">Whether the PrivateCreator tag should be created if needed.</param>
/// <returns>Private DICOM tag, or null if all groups are already used or createTag is false and the
/// PrivateCreator is not already in the dataset. </returns>
internal DicomTag GetPrivateTag(DicomTag tag, bool createTag)
  {
      // not a private tag
      if (!tag.IsPrivate) return tag;
      // group length
      if (tag.Element == 0x0000) return tag;
      // private creator?
      if (tag.PrivateCreator == null) return tag;
      // already a valid private tag
      if (tag.Element > 0xff) return tag;
      ushort group = 0x0010;
      for (; group <= 0x00ff; group++)
      {
          var creator = new DicomTag(tag.Group, group);
          if (!Contains(creator))
          {
              if (!createTag) continue;
              Add(new DicomLongString(creator, tag.PrivateCreator.Creator));
              return new DicomTag(tag.Group, (ushort)((group << 8) + (tag.Element & 0xff)), tag.PrivateCreator);
          }
          var value = TryGetSingleValue(creator, out string tmpValue) ? tmpValue : string.Empty;
          if (tag.PrivateCreator.Creator == value) return new DicomTag(tag.Group, (ushort)((group << 8) + (tag.Element & 0xff)), tag.PrivateCreator);
      }
      return null;
  }
```

But try as I might, I can't understand the proper functioning of this method.  It looks like if I call "DicomDataset.Add(somePrivateTag)" it will potentially change the element that I've passed as a parameter.... right?

Question number two (or three):  I cannot find out how I should add a creator tag to the dataset explicitly... it looks like the only way to add a creator tag is via the GetPrivateTag method, and then only inside the loop that is incrementing the group number at the line that says

`Add(new DicomLongString(creator, tag.PrivateCreator.Creator));`

Is that correct? (that is the only way to add a creator tag?)

The reason I'm asking is that I'm added some private tags in code and this is sort of giving me fits...

**Comment by mrbean-bremen** [comment]
>  It looks like if I call "DicomDataset.Add(somePrivateTag)" it will potentially change the element that I've passed as a parameter.... right?

Not really. Admittedly, the name `GetPrivateTag` may be a bit misleading with the `createTag` parameter set to `true`, because in this case it also creates the tag if it does not exist. But it does not change the private tag as is, because a private tag is defined by the private creator, the group and the tag offset (which is the lower byte of the tag value). The higher byte of the tag (the part what maybe changed here) is not part of the tag definition itself, it just shows which private creator block it belongs to (e.g. this is meta information about the location in the dataset).

>  I cannot find out how I should add a creator tag to the dataset explicitly

You shouldn't need to. A private creator without a private tag does not make sense, adding a private tag (using `DicomDataset.Add`) will create it if it does not exist yet.
