### ISSUE TITLE
JsonDicomConverter is throwing an ArgumentException for Infinity values FL and FD VRs

### ISSUE THREAD

**Issue by arunmk-ms** [fo-dicom/fo-dicom#1725]
**Describe the bug**
JsonDicomConverter is throwing an ArgumentException while serializing a dicom dataset that contains Infinity values for FL and FD VRs. 

**To Reproduce**
Dicom file attached has a tag (0074, 102A) that has a value '-Infinity' and serializer failed to parse the file.

**Expected behavior**
No exception should be thrown

**Screenshots or test DICOM files**
If applicable, add screenshots or test DICOM files to help explain your problem.
[Test_FD.zip](https://github.com/fo-dicom/fo-dicom/files/14316598/Test_FD.zip)

**Environment**
Fellow Oak DICOM version: 5.1.2
OS: Linux
Platform: .Net 8.0

**Comment by gofal** [comment]
The PR, that fixes this issue, is already mergedn.
