### ISSUE TITLE
Exposing network infos (ip and port) in association

### ISSUE THREAD

**Issue by do0om** [fo-dicom/fo-dicom#173]
Hi,
I am porting an application from Clear Canvas to fo-dicom and I need to have access to the calling AE ip address. Clear Canvas exposes it in [their association parameters](https://github.com/ClearCanvas/ClearCanvas/blob/master/Dicom/Network/AssociationParameters.cs#L377) but I didn't find any equivalent in fo-dicom.
For information, we use it to distinguish between two entities with the same AE title (I know this is bad!) in a badly configured network. But I can imagine that it is useful for other scenarios.

Is it possible to have it exposed?

**Comment by HelderMPinhal** [comment]
Hi,
I've been having exactly the same need.
Thumbs up!

**Comment by IanYates** [comment]
Sounds reasonable.  I'll check it out and see what we can do.  Since we haven't released a final v2 yet we can sneak in these API changes since backwards compatibility isn't expected anyway.

**Comment by anders9ustafsson** [comment]
`IPEndPoint` is not part of the Portable Class Library API, so it is not straightforward (but of course possible) to expose this information.

I definitely see the point in exposing this info, but I would prefer it if we could put the request on hold until after 2.0 is released. Everyone OK with this?

**Comment by do0om** [comment]
I'm Ok

**Comment by anders9ustafsson** [comment]
@do0om @HelderMPinhal and others, when and how would you expect to have access to this IP address and port information? It would be very helpful if you could illustrate it with an example.
