### ISSUE TITLE
ImageSharp is not free software - Disclaimer?

### ISSUE THREAD

**Issue by edespong** [fo-dicom/fo-dicom#1754]
**Describe the "bug"**
Since some time back, ImageSharp has a proprietary license, see https://sixlabors.com/pricing/license

At the moment, there is no mention for this in fo-dicom, and it could be easy to make a mistake by assuming that consuming anything   (though in the end, it is entirely the consumers responsibility).

Three reflections/questions:

1. I think it would be good to have a disclaimer that using the ImageSharp parts of fo-dicom will require you to buy a license if you are to use it for production.

2. I am no legal expert, but I wonder if it is kosher for fo-dicom to have a MS-PL license for the fo-dicom.Imaging.ImageSharp which requires a non-opensource library to work. I guess it could fall under the dynamic vs. static linking argument.

3. Is there any alternatives that are open source that are cross-platform for the functionality that ImageSharp provides?

**Comment by amoerie** [comment]
Hi @edespong 

I've confirmed with the author of ImageSharp that usage of ImageSharp falls under the Apache 2.0 license (the open source license) because ImageSharp is a transitive dependency of fo-dicom. 

However, if you take a direct dependency on ImageSharp (i.e. use it directly in your application), then this no longer applies.

See https://github.com/SixLabors/ImageSharp/blob/main/LICENSE 

This is the line: 

>    - You are consuming the Work as a Transitive Package Dependency.


![image](https://github.com/fo-dicom/fo-dicom/assets/2063584/e5a58cf4-d3a4-4a67-9717-992107bbad7a)

**Comment by edespong** [comment]
Thanks. Good to get confirmation. Then I do not think there is a need for any changes.

But also weird? Because all I have to do in order to circumvent the license it to have a friend create an open source package that takes ImageSharp as a dependency, and then use the open source package in my application. Or I could take fo-dicom as a dependency, and then rely on the fact that fo-dicom is "installing it" and then just grab the assembly from memory and use it. But I guess that is a question for the ImageSharp authors and not for you.

**Comment by amoerie** [comment]
> But also weird? Because all I have to do in order to circumvent the license it to have a friend create an open source package that takes ImageSharp as a dependency, and then use the open source package in my application. Or I could take fo-dicom as a dependency, and then rely on the fact that fo-dicom is "installing it" and then just grab the assembly from memory and use it. But I guess that is a question for the ImageSharp authors and not for you.

Sometimes, illegal things are very easy to do technically. That doesn't make them any less illegal. ;-)

**Comment by edespong** [comment]
My point was that I think that it would not be illegal to do what I suggested

**Comment by amoerie** [comment]
Hmm I guess this debate would result in a "spirit of the law" vs "letter of the law" argument, and this conversation has already exited my zone of expertise. Your initial conclusion of "I guess that is a question for the ImageSharp authors and not for you." is probably correct. :-)
