### ISSUE TITLE
How to monitor the time for a SCU client to transfer multiple files at a time on the SCP Server side

### ISSUE THREAD

**Issue by ByZhouhang** [fo-dicom/fo-dicom#1762]
**Describe the bug**

public Task OnReceiveAssociationRequestAsync(DicomAssociation association)
 {
      // we can  know which client it is  by use  association
 }

 public Task OnReceiveAssociationReleaseRequestAsync()
 {
       // but when  it relaease  ，can not  know which client it is
     return SendAssociationReleaseResponseAsync();
 }
 
Now if there is a client that transfers 100 files to the server, and I want to monitor the total time spent transferring those 100 files, can this be done? Which method should I use?

**Comment by amoerie** [comment]
Inside your DicomService, you can always look at this.Association

**Comment by gofal** [comment]
When you build up a DicomServer, then you create a class inheriting from `DicomService`. This class is then passed to your DicomServer as a generic Type-Parameter.
What you should know is, that the DicomServer creates a new instance of your DicomService class for every association. If there are several associations in parallel, then the DicomServer as a collection of your DicomService instances.
That said, you can add some private fields to your class, like `timestampStart` or `instancesCount`. 

```
public class MyDicomService : DicomService, IDicomServiceProvider, IDicomCStoreProvider
{
   private DateTime _associationStarted;
   private int _instancesCount = 0;

   public Task OnReceiveAssociationRequestAsync(DicomAssociation association)
   {
      // we can know which client it is by use association
   _associationStarted = DateTime.Now;
   }

   public Task OnCStoreRequestAsync(DicomCStoreRequest request)
   {
      // you could check the client/association connected to this instance by accessing the Association-property
      var client = Association.CallingAE;
      _instancesCount ++;
   }

   public Task OnReceiveAssociationReleaseRequestAsync()
   {
      // here on release you can access all fields and the Association property
      Logger.Log($"client {Association.CallingAE} sent {_instancesCount} instances and took {(DateTime.Now - _associationStarted).TotalSeconds} seconds");
      return SendAssociationReleaseResponseAsync();
   }
}
```

**Comment by ByZhouhang** [comment]
> When you build up a DicomServer, then you create a class inheriting from `DicomService`. This class is then passed to your DicomServer as a generic Type-Parameter. What you should know is, that the DicomServer creates a new instance of your DicomService class for every association. If there are several associations in parallel, then the DicomServer as a collection of your DicomService instances. That said, you can add some private fields to your class, like `timestampStart` or `instancesCount`.
> 
> ```
> public class MyDicomService : DicomService, IDicomServiceProvider, IDicomCStoreProvider
> {
>    private DateTime _associationStarted;
>    private int _instancesCount = 0;
> 
>    public Task OnReceiveAssociationRequestAsync(DicomAssociation association)
>    {
>       // we can know which client it is by use association
>    _associationStarted = DateTime.Now;
>    }
> 
>    public Task OnCStoreRequestAsync(DicomCStoreRequest request)
>    {
>       // you could check the client/association connected to this instance by accessing the Association-property
>       var client = Association.CallingAE;
>       _instancesCount ++;
>    }
> 
>    public Task OnReceiveAssociationReleaseRequestAsync()
>    {
>       // here on release you can access all fields and the Association property
>       Logger.Log($"client {Association.CallingAE} sent {_instancesCount} instances and took {(DateTime.Now - _associationStarted).TotalSeconds} seconds");
>       return SendAssociationReleaseResponseAsync();
>    }
> }
> ```

Thank you very much for your detailed reply, it helped me a lot
