### ISSUE TITLE
HTJ2K Throwing exception

### ISSUE THREAD

**Issue by yadavvirus** [fo-dicom/fo-dicom#1768]
@gofal 
.NET 7.0
fo-dicom.Codecs (5.11.0)

I am getting this error while changing its transfer sysntax to HTj2K.

var transcodedDataset = dataset.Clone(DicomTransferSyntax.HTJ2KLossless);

FellowOakDicom.Imaging.Codec.DicomCodecException: 'Encoding dataset to transfer syntax High-Throughput JPEG 2000 Image Compression (Lossless Only) is not supported.'

**Comment by gofal** [comment]
This is because Efferent is currently developing this codec and have not deployed it yet.
Fo-dicom itself does not support Codecs, but it had to add all UIDs, so that Efferent is able to implement. 
Please watch the fo-dicom.codec repository.

**Comment by yadavvirus** [comment]
Oh ok thank you sir for reply.
