### ISSUE TITLE
DICOM CP-246 not handled correctly in DicomReader

### ISSUE THREAD

**Issue by Ed55** [fo-dicom/fo-dicom#177]
A DICOM "edge case" described in ftp://medical.nema.org/medical/dicom/final/cp246_ft.pdf  is not handled correctly.
Unfortunately this "edge case" is quite common.
Short Story: values with VR UN shall be interpretated as ILE, regardless of the datasets transfer syntax.

The issue can be reproduced using the following datasets out of http://sourceforge.net/projects/gdcm/files/gdcmConformanceTests/gdcmConformanceTests/   
D_CLUNIE_CT1_IVRLE_BigEndian.dcm
D_CLUNIE_CT1_IVRLE_BigEndian_ELE.dcm
Enhanced_MR_Image_Storage_Illegal_CP246.dcm
Enhanced_MR_Image_Storage_Illegal_CP246_corrected.dcm
(Thanks to Mathieu Malaterre)

I prepared a fix, but I am not quite happy with it because it needs to differentiate between private tags and standard tags. It seems because parts of this (and related) issues are handled amongst others in e.g. *IsPrivateSequenceBad*.
At least my fix is working (a revision of the reader may wait for the next planned release ;-)).
I created two additional test files to test for *standard UN sequence tag,undefined length*, ELE and EBE: 
![undefined_length](https://cloud.githubusercontent.com/assets/15705674/12211051/cacdfb7e-b65e-11e5-9281-1f6d99bb3def.png) (rename to zip and unzip)

Quick Fix proposal:
In DicomReader *ParseLength*, branch *isExplicitVR*:

    if (!source.Require(6))
    {
       this.result = DicomReaderResult.Suspended;
       return false;
     }
    
    source.Skip(2);
    this.length = source.GetUInt32();
    //added
    //CP-246 handling
    // assume that Undefined Length in explicit datasets with VR UN are sequences 
    //According to cp-246 the sequence shall be handled as ILE, but this will be handled later...
    //in the current code this needs to be restricted to privates 
    if (this.length == UndefinedLength && this._vr == DicomVR.UN && this._tag.IsPrivate )
    {
         this._vr = DicomVR.SQ;
     }
    //end added
    
In *ParseValue* and *ParseValueAsync*, branch DicomVR.SQ just before // Aeric Sylvan ...:

    //changed CP-246 handling
    bool needtoChangeEndian = false;
    if (parsedVR == DicomVR.UN && !_tag.IsPrivate)
    {
    	this._implicit = true;
    	needtoChangeEndian = source.Endian == Endian.Big;
    }
    if (needtoChangeEndian)
    {
    	source.Endian = Endian.Little;
    }
    
    this.ParseItemSequence(source);
    
    if (needtoChangeEndian)
    {
    	source.Endian = Endian.Big;
    	needtoChangeEndian = false;
    }
    //end
    
    //original
    //this.ParseItemSequence(source);
    //end changed
    
This fix works as well for another two real world examples I have in my "funny DICOM" collection, but I am unable to anonymize them without fixing the issue.

Not tested: EBE TS instances having UN issues in private attributes.

**Comment by anders9ustafsson** [comment]
@Ed55 As usual, great work! Many thanks for reporting this and the other two issues, #178 and #179. We will go through them more thoroughly in a short while.

**Comment by anders9ustafsson** [comment]
@Ed55 Since it feels insecure to make changes in these fundamental parts of the code so close to the imminent release, I would like to postpone the fix of this issue as well as #178 and #179 until after the release of 2.0.0. Is this acceptable to you?

**Comment by Ed55** [comment]
@anders9ustafsson Yes, indeed fundamental, but as it seems I am the only one who is facing such kind of instances I accept.
I need to to apply my patches (at least this one and #178) for my (non production) test/analysis applications and report if I have issues.

**Comment by Ed55** [comment]
@anders9ustafsson I have to revise my acceptance:
#178 should still be fixed. Even if you just disable your fix for #64.
Its a pitty that the parser keeps looping (hangs), but the sample in #64 is invalid DICOM , rare
(I haven't seen this in several 100 millions instances from (nearly) all over the world) and can be fixed by not using the private dictionary.

Your fix for this breaks valid DICOM. 
Sorry for being undiplomatic strict, but I have had too many annoying discussions today ;-).

**Comment by anders9ustafsson** [comment]
@Ed55 Diplomacy is overrated :-)

OK, message taken. I released 2.0.0 yesterday, so it is too late for that, but I'll schedule 2.0.1 to be released ASAP with fixes for #177, #178 and #179 in it.

Again, many thanks for these invaluable contributions, both sample-wise and implementation-wise. I (and I think I speak for the rest of the *fo-dicom* team too) am extremely grateful for your work.
