### ISSUE TITLE
Korean Hangul characters incorrectly read from dicom file

### ISSUE THREAD

**Issue by dmgroppe** [fo-dicom/fo-dicom#1772]
**Describe the bug**
The attached dicom file (which is from http://www.dclunie.com/images/charset/index.html) contains a patient name in Korean Hangul characters. When I try to read the name with fo-dicom, the characters are incorrect. 

**To Reproduce**
   var tempDcm = DicomFile.Open("korean_agfa_infinitt_2008-3.dcm");
   var pName=tempDcm.Dataset.GetString(DicomTag.PatientName);

The result is:
pName="$)C??????(B"

**Expected behavior**
pName should equal 김희중

**Environment**
Fellow Oak DICOM version:  fo-dicom.Desktop 4.0.8
OS: Windows 10 (10.0.19045 Build 19045) x64
Platform: .NET Framework 4.7.2
[KoreanHangulDcm.zip](https://github.com/fo-dicom/fo-dicom/files/15040972/KoreanHangulDcm.zip)

**Comment by mrbean-bremen** [comment]
This should work in fo-dicom 5. Are you able to test a current fo-dicom version?

**Comment by dmgroppe** [comment]
Thanks for the speedy reply @mrbean-bremen!
You are correct. fo-dicom 5.1.2 reads the characters perfectly.
