### ISSUE TITLE
fo-dicom v5 Dependency Injection Documentation

### ISSUE THREAD

**Issue by aarondglover** [fo-dicom/fo-dicom#1773]
To make Fellow Oak DICOM use Microsoft.Extensions.Logging, you need to use dependency injection.

If you are using the host builder from ASP.NET Core, you can do this:

```csharp
var host = Host.CreateDefaultBuilder(args)
    .ConfigureLogging(logging =>
    {
        logging.ClearProviders();
        logging.AddConsole();
        logging.SetMinimumLevel(LogLevel.Information);
    })
    .ConfigureServices(services =>
    {
        services.AddFellowOakDicom();
        services.AddHostedService<Worker>();
        // This will be injected into the DICOM service
        services.AddSingleton<CustomDependency>();
    })
    .Build();

// This is still necessary for now, but we want to get rid of this in the long term
DicomSetupBuilder.UseServiceProvider(host.Services);

host.Run();
```

If you are not using the host builder, you'll need to make your own service collection:

```csharp
var services = new ServiceCollection();
services.AddLogging(logging =>
{
    logging.ClearProviders();
    logging.AddConsole();
    logging.SetMinimumLevel(LogLevel.Information);
});
services.AddFellowOakDicom();
var serviceProvider = services.BuildServiceProvider();
DicomSetupBuilder.UseServiceProvider(serviceProvider);
```

_Originally posted by @amoerie in https://github.com/fo-dicom/fo-dicom/discussions/1627#discussioncomment-6439203_

The above post is gold - and is the first time I've seen a clear example of using DI with fo-dicom v5. Dependency injection documentation, samples would be very useful

**Comment by aarondglover** [comment]
Seems I am still having trouble with Dependency injection of additional objects into my DICOMService

Further discussion at [https://github.com/fo-dicom/fo-dicom/discussions/1774#discussion-6549386](https://github.com/fo-dicom/fo-dicom/discussions/1774#discussion-6549386)

**Comment by amoerie** [comment]
I suspect you are running into this issue: https://github.com/fo-dicom/fo-dicom/issues/1611#issuecomment-1593594190 

Can you check? 

Edit: replied to wrong thread, I'll add the same reply over at #1774

**Comment by aarondglover** [comment]
@amoerie as you suspected - it was exactly the issue you thought... the first x number of parameters MUST match exactly on type Thanks for your prompt assistance

**Comment by amoerie** [comment]
@aarondglover I've created a pull request that tries to clarify how DI works in fo-dicom today. Feedback welcome!
