### ISSUE TITLE
Fix for #64 breaks parsing of valid datasets

### ISSUE THREAD

**Issue by Ed55** [fo-dicom/fo-dicom#178]
In the case of nested sequences with undefined length having a known length sequence item in the end (thus reaching a milestone),  the parsed Sequence Delimination Item might not be invalid as in the #64 example ...

 An example demonstrating the issue here 
![_64fixissueanomwopixel](https://cloud.githubusercontent.com/assets/15705674/12221053/d4f1a550-b78b-11e5-93bd-2b5de146a109.png)
I have removed the pixel data because of burned in annotations ...

I think it could work if the fix would just be applied if there is a difference between the amount of milestones and the calculated sequenceDepth.

	// #64, in case explicit length has been specified despite occurrence of Sequence Delimitation Item
	if (source.HasReachedMilestone() && source.MilestonesCount > this.sequenceDepth)
	{
		this.ResetState();
		return true;
	}

But therefore one has to change the IByteSource interface to be able to get hold of the current amount of milestones ...
I created a quick hack to check the idea: all my parser tests succeeded ( with and without the use of the private dictionary).

I could not check the file related to                         // Aeric Sylvan - https://github.com/rcd/fo-dicom/issues/62#issuecomment-46248073 as the link is not active.

@anders9ustafsson Do you can get hold the this old 62 issue and upload the file again (if any)

Any other ideas to solve #64 / #135 ?

**Comment by anders9ustafsson** [comment]
@Ed55 Maybe we could pass the question on to @Aerik directly: Aerik, do you still have access to the file that Ed is talking about, that initiated your fix [here](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/IO/Reader/DicomReader.cs#L519)?

**Comment by aerik** [comment]
@Ed55 @anders9ustafsson I haven't been able to figure out which specific files cause that problem for me, but I did dig up this description of the problem, from my perspective:

"I had a similar problem when the library tries to be smart about DicomVR.UN - the problem I saw was that the library changed the VR to the default dictionary VR for that tag, but *after* setting the length.  I moved that block of code to before the length was determined, and that fixed my issues."

I also sort of remember that the files I had that problem with seem to have been changed by Efilm - the problem manifested when I tried to open some files that I got from Efilm, but (I think, it was a long time ago) the same file from a source upstream of Efilm were ok.  I also think Colby fixed it slightly differently than I did.  Let me poke around / think some more and come back in a bit.

**Comment by aerik** [comment]
I'm still not sure exactly what file(s) gave me the problem, but I could run a CSTORE using 2.0, test all the files I have in Efilm by sending them, then use @Ed55 's code and do it again, and see if there are any problems...

**Comment by Ed55** [comment]
@aerik Just a remark: 
I did not run a C-STORE, I was using DicomFile.Open and inspect the returned dataset for completeness (see #179) and correctness of the value(s) of the 'critical' attributes.
I did this with and without the use of the supplied 'private dictionary' because this is influencing the parsers handling of private tags.

**Comment by anders9ustafsson** [comment]
@Ed55 #64 breaks if I use "greater than", but this works: `source.MilestonesCount >= this.sequenceDepth`. Any thoughts?

**Comment by anders9ustafsson** [comment]
@Ed55 Glad if you can take a look at PR #190, which uses your solution except for the ">=" replacement.

**Comment by Ed55** [comment]
@anders9ustafsson please see my comments in #190
