### ISSUE TITLE
Invalid VR in explicit dataset leads to 'silent' stop

### ISSUE THREAD

**Issue by Ed55** [fo-dicom/fo-dicom#179]
This is the last issue I found going through my "funny DICOM" collection.
(I apologize for not going through it earlier, but I have had nearly no spare time.)

The syntetic test file (based on a real world instance!) here:
![invalidvrinexplicitdataset](https://cloud.githubusercontent.com/assets/15705674/12222706/45cfd106-b7c4-11e5-9b7e-5b38d27bdb1d.png) (rename to .dcm)
The tag 0028,0120 Pixel Padding Value (which should not be present anyway) has two space chars as VR. 
You need to disable #64 fix or apply my patch mentioned here: #178 

If you just use DicomFile.Open(..) you will not detect any error, no exception is thrown.

Currently I could not make up my mind where it would be best to fix it.
Silently ignore and fix it, or throw, or let it parse until and make DicomReaderResult availabe in DicomFile, or ... ?

**Comment by anders9ustafsson** [comment]
@Ed55 Looking more closely into the binaries of the DICOM file you uploaded, there seem to be more problems than just the "blank space" VR. The *Pixel Padding Value* tag is also repeated, containing again the "blank space" VR, but no value length or value:

![untitled](https://cloud.githubusercontent.com/assets/6515030/12475048/5674b1de-c020-11e5-9c2b-d196208e2e2e.png)

Is this intended?

My plan is to silently allow the white space VR, but the *Pixel Padding Value* duplication messes up the unit test verification. Would it make sense in this case to simply remove the invalid second *Pixel Padding Value* occurrence?

**Comment by Ed55** [comment]
@anders9ustafsson Uuups, sorry, it modified the instance manually to anonymize ...
My point is just one tag in an explicit dataset, the duplicate was not intended and probably my error.

My concern is that there might be other strange DICOM violations which may lead to a 'silent' return of the DicomReader without a throw and without setting DicomReaderResult.Error.

In DicomReader ParseDataset

                    if (!this.ParseTag(source)) return;
                    if (!this.ParseVR(source)) return;
                    if (!this.ParseLength(source)) return;
                    if (!this.ParseValue(source)) return;

The above mentioned case should just demonstrate this: force a return without setting the DicomReaderResult.Error.

Later, in DicomFile.Open

                    if (reader.Read(
                        source,
                        new DicomDatasetReaderObserver(df.FileMetaInfo),
                        new DicomDatasetReaderObserver(df.Dataset, fallbackEncoding),
                        stop) == DicomReaderResult.Error)
                    {
                        return null;
                    }

So you do not notice that something was going wrong ...
May this should be changed to  != DicomReaderResult.Success ??

Just an idea ...

**Comment by anders9ustafsson** [comment]
@Ed55 I see your point. I am about to add a PR with the white-space VR acceptance fix, but I'll probably add another commit to the PR afterwards to account for your comments here. Stay tuned :-)

**Comment by Ed55** [comment]
@anders9ustafsson need to do some other work now ... will switch off the 'tuner' until tonight ;-)

**Comment by anders9ustafsson** [comment]
@Ed55 When your tuner is switched on again :-) please have a look at the latest commit in #196. Its building on your suggestion in the above comment. However, I would prefer to turn the "silent stop" into a "semi-silent stop" by introducing a new property `IsPartial` to indicate if the parsing ended prematurely. Thoughts on that?

**Comment by Ed55** [comment]
@anders9ustafsson haven't had a look into the code, but that's a good idea; and seems to be sufficient.
I have thought about a 'strict/lax' DicomReader property ...
But that's of course more to implement.
