### ISSUE TITLE
ISO 2022 IR 58 Encoded Strings Cannot Be Decoded Correctly

### ISSUE THREAD

**Issue by chen-wu** [fo-dicom/fo-dicom#1805]
**Describe the bug**
Decoding DICOM with "\\ISO 2022 IR 58" may include invalid characters.

**To Reproduce**
``` csharp
        var raw = new byte[] {
            0x5A, 0x68, 0x61, 0x6E, 0x67, 0x5E, 0x58, 0x69, 0x61, 0x6F, 0x44, 0x6F, 0x6E, 0x67, 0x3D, 0x1B, 0x24, 0x29,
            0x41,
            0xD5, 0xC5, 0x5E, 0x1B, 0x24, 0x29, 0x41, 0xD0, 0xA1, 0xB6, 0xAB, 0x3D, 0x20
        }; // Zhang^XiaoDong=张^小东=

        var ds = new DicomDataset {
            { DicomTag.SOPClassUID, DicomUID.SecondaryCaptureImageStorage },
            { DicomTag.SOPInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID() }
        };
        ds.Add(DicomTag.SpecificCharacterSet, "\\ISO 2022 IR 58");

        var sd = new DicomLongString(DicomTag.StudyDescription,
            DicomEncoding.GetEncodings(ds.GetValues<string>(DicomTag.SpecificCharacterSet)),
            new MemoryByteBuffer(raw));
        ds.Add(sd);
        
        var dicomFile = new DicomFile(ds);
        var stream = new MemoryStream();
        dicomFile.Save(stream);
        stream.Seek(0, SeekOrigin.Begin);
        var inFile = DicomFile.Open(stream);
        var nsd = inFile.Dataset.GetString(DicomTag.StudyDescription); //Zhang^XiaoDong=$)A张^$)A小东=
```

The escape codes are not removed.
It looks like that the "gb2312" encoding in .NET cannot handle the escape codes internally. So, it might be better to remove it from the _codePagesForHandledEncodings.

https://github.com/fo-dicom/fo-dicom/blob/f2f4fb0b8998b03f23e3b0b53991d0feac89bfd2/FO-DICOM.Core/DicomEncoding.cs#L299-L303

I'm not sure how dotnet handle these encodings. Another code page "x-cp50227" is descript as "ISO 2022 Simplified Chinese; Chinese Simplified (ISO 2022)", and it seems also cannot remove these escape codes.

**Comment by mrbean-bremen** [comment]
Hm, interesting. I thought I had tested this.

**Comment by mrbean-bremen** [comment]
You are right - this is not handled by the encoding, and just removing the character set from the handled encodings fixes it. Thank you for the report, I had completely forgotten to test this (probably because it only exists as an extended encoding, which is different from all other encodings).

**Comment by chen-wu** [comment]
Thank you for fixing this, then we can close the issue.
