### ISSUE TITLE
Performance impact in DicomDataset comparing

### ISSUE THREAD

**Issue by gofal** [fo-dicom/fo-dicom#1807]
**Describe the bug**
See discussion #1787 
With version 5.1.2 a dicomdataset comparison was introduced that compares the content of two DicomDatasets instead of only the reference equality.
But this lead to huge impact in performance.

**Expected behavior**
Either optimize the performance of comparison or allow to turn it off again

**Environment**
Fellow Oak DICOM version: 5.1.2
OS: (e.g. Windows 8.1 x64)
Platform: (e.g. .NET Framework 4.6.2)

**Comment by gofal** [comment]
Calculating the Hashvalue of a DicomDataset is quite fast, but actually comparing 2 DicomDatasets iterates all items, gets the string representation of the tags and compares that. This means a lot of string allocations, specially for huge tags like pixeldata.

This is a benchmark of the code in 5.1.2. where
- "CompareXX" loads two DicomDatasets from the same file and compares them (the comparision returns true)
- "HaxhXX" calculates a hash-value for a DicomDataset
- "CompareCloneXX" loads a DicomDataset, clones it and compares it. While the DicomDataset is a different instance, all the items contained in these DicomDatasets are the same instance and therefore should be compared faster.

| Method         | Mean          | Error        | StdDev       | Median        | Gen0       | Gen1       | Gen2      | Allocated   |
|--------------- |--------------:|-------------:|-------------:|--------------:|-----------:|-----------:|----------:|------------:|
| CompareCt      |  35,469.52 us | 1,365.651 us | 3,874.124 us |  34,232.50 us |  2000.0000 |  2000.0000 |         - |  27993512 B |
| CompareMR      |   5,868.68 us |   248.676 us |   717.488 us |   5,623.15 us |          - |          - |         - |   5884472 B |
| CompareMg      | 488,450.17 us | 8,451.172 us | 9,732.382 us | 491,507.05 us | 24000.0000 | 15000.0000 | 4000.0000 | 331383656 B |
| HashCt         |      12.54 us |     0.806 us |     2.206 us |      12.20 us |          - |          - |         - |       904 B |
| HashMr         |      15.06 us |     0.825 us |     2.368 us |      14.90 us |          - |          - |         - |       904 B |
| HashMg         |      11.43 us |     0.981 us |     2.767 us |      10.70 us |          - |          - |         - |       904 B |
| CompareCloneCt |  33,087.80 us |   643.157 us | 1,803.482 us |  32,499.95 us |  2000.0000 |  2000.0000 |         - |  27992456 B |
| CompareCloneMR |   5,580.19 us |   107.472 us |   281.236 us |   5,511.85 us |          - |          - |         - |   5875736 B |
| CompareCloneMg | 481,308.94 us | 9,496.661 us | 9,326.991 us | 480,479.00 us | 24000.0000 | 15000.0000 | 4000.0000 | 331366840 B |

the comparison allocates a lot of memory and comparing the cloned DicomDataset with the original is just the same performance as comparing two different DicomDatasets

**Comment by gofal** [comment]
After changing the DicomDatasetComparer, not to render the items as string before comparing them, but creating a virtual DicomElement.Compare(DicomElement other), the performance significantly became better:

| Method         | Mean        | Error      | StdDev     | Median      | Allocated  |
|--------------- |------------:|-----------:|-----------:|------------:|-----------:|
| CompareCt      |   646.57 us |  25.985 us |  73.291 us |   625.25 us |  1085336 B |
| CompareMR      |   388.35 us |  29.405 us |  85.311 us |   359.20 us |   313656 B |
| CompareMg      | 8,761.65 us | 207.461 us | 605.175 us | 8,726.85 us | 23384608 B |
| HashCt         |    13.19 us |   0.812 us |   2.224 us |    12.80 us |      904 B |
| HashMr         |    13.89 us |   0.454 us |   1.234 us |    13.85 us |      904 B |
| HashMg         |    10.23 us |   0.505 us |   1.456 us |    10.00 us |      904 B |
| CompareCloneCt |    88.89 us |   7.155 us |  19.825 us |    80.50 us |    18304 B |
| CompareCloneMR |    94.81 us |   3.839 us |  10.045 us |    93.55 us |    18304 B |
| CompareCloneMg |   101.20 us |  12.461 us |  36.742 us |    91.60 us |    19768 B |

**Comment by gofal** [comment]
And finally, I skipped, that DicomOtherByte and DicomOtherWord read all bytes and compare them, because for pixeldata or encapsulateddata this means that byte-arrays have to be allocated and data is copied from the streams etc.
With that, the performance is quite ok in my opinion:

| Method         | Mean      | Error    | StdDev    | Median     | Allocated |
|--------------- |----------:|---------:|----------:|-----------:|----------:|
| CompareCt      | 112.50 us | 7.527 us | 21.352 us | 109.800 us |   36248 B |
| CompareMR      | 138.57 us | 9.690 us | 28.114 us | 129.900 us |   51000 B |
| CompareMg      | 124.47 us | 8.530 us | 25.152 us | 122.850 us |   65696 B |
| HashCt         |  12.71 us | 0.785 us |  2.265 us |  12.650 us |     904 B |
| HashMr         |  14.90 us | 0.779 us |  2.221 us |  14.400 us |     904 B |
| HashMg         |  10.05 us | 0.647 us |  1.845 us |   9.650 us |     904 B |
| CompareCloneCt |  79.15 us | 2.008 us |  5.598 us |  78.750 us |   18304 B |
| CompareCloneMR |  96.40 us | 4.139 us | 11.047 us |  92.100 us |   18304 B |
| CompareCloneMg |  80.63 us | 6.708 us | 18.698 us |  75.950 us |   19768 B |

Edit: I now noticed, that the cloning of the dataset is done within the benchmark method. Moved the clone to IterationSetup, then the benchmark is even better:

| Method         | Mean      | Error    | StdDev    | Median     | Allocated |
|--------------- |----------:|---------:|----------:|-----------:|----------:|
| CompareCloneCt |  45.25 us | 3.749 us | 10.327 us |  42.85 us |    1032 B |
| CompareCloneMR |  53.71 us | 4.511 us | 12.350 us |  50.05 us |    1032 B |
| CompareCloneMg |  39.57 us | 4.573 us | 13.193 us |  37.95 us |    2400 B |

**Comment by gofal** [comment]
The DicomDataset now has a public static property `CompareInstancesByContent` that is `true` by default. If this is set to `false`, then the behavior of pre 5.1.2 is restored, then two DicomDatasets are only equal if they are the exact instance. Now the performance is:

**But when this option is set to false, then the behavior changes, the Compare methods in the benchmark now return `false`.**

| Method         | Mean      | Error     | StdDev    | Median    | Allocated |
|--------------- |----------:|----------:|----------:|----------:|----------:|
| CompareCt      |  2.385 us | 0.2480 us | 0.7234 us |  2.200 us |     864 B |
| CompareMR      |  2.039 us | 0.2312 us | 0.6634 us |  2.000 us |     864 B |
| CompareMg      |  2.286 us | 0.1989 us | 0.5772 us |  2.300 us |     864 B |
| HashCt         | 11.936 us | 0.5996 us | 1.6513 us | 11.750 us |     904 B |
| HashMr         | 14.410 us | 0.5974 us | 1.6750 us | 14.500 us |     904 B |
| HashMg         | 11.327 us | 0.8898 us | 2.6096 us | 10.550 us |     616 B |
| CompareCloneCt |  2.053 us | 0.2248 us | 0.6414 us |  1.850 us |     864 B |
| CompareCloneMR |  1.977 us | 0.2593 us | 0.7522 us |  1.800 us |     864 B |
| CompareCloneMg |  2.076 us | 0.2433 us | 0.7134 us |  1.900 us |     864 B |

**Comment by amoerie** [comment]
Thanks for digging into this. I think our use cases to compare DicomDatasets by their contents are **very** limited indeed and we'll want to keep using referential equality.

**Comment by gofal** [comment]
Agree, generally comaring DicomDatasets is a not so commom usecase in archive pacs.
But if you implement a PrintSCP with all the NActions NSet and so on commands, where the printserver has to hold the current state per client im memory across asociations, there comparing DicomDatasets by their content is relevant.
Or also when you have a Dicom Worklist client, where you periodically receive DicomDatases from the server where you then want to check if the worklistentries are the same by content.

So there are some usecases, where comparing by content is relevant. But I do not know usecases where reference equality is relevant.

**Comment by amoerie** [comment]
> But I do not know usecases where reference equality is relevant.

Yeah don't get me wrong, I think in our applications we *never* compare entire DicomDatasets (only individual tags).
But it seems safer to me to default to referential equality to avoid possible performance pitfalls if there are hidden equality checks being performed, for example if you put a DicomDataset inside a Dictionary, HashSet or List...

But it's okay though, it doesn't matter what the default is for fo-dicom, I can change it for our applications. :-) 
I was just sharing my thoughts.
