### ISSUE TITLE
What is the plan for supporting .NET 8?

### ISSUE THREAD

**Issue by macdonaldr93** [fo-dicom/fo-dicom#1809]
**What is, according to you, missing from fo-dicom?**

I'm curious what the plan is for supporting .NET 8. I'm starting a new project and I'd like to start from the latest version of .NET, but I'm unsure the impact that will have on this library.

- What is the plan for supporting .NET 8?
- Is the work already in progress?
- What are the major blockers or issues?

**Describe the solution you'd like**

Support for the latest version of .NET.

**Describe possible alternatives or existing workarounds you've considered**

I can certainly start the project from .NET 7. Given the benefits and improvements in .NET 8, I'd much rather start from there.

Thank you!!

**Comment by mrbean-bremen** [comment]
The project is build against NetStandard 2.0, so it will work with any version of .NET that supports this. Only the tests are running against specific framework versions.
Are you thinking of some .NET 8-specific optimizations?

**Comment by macdonaldr93** [comment]
Oh amazing, that makes sense. I saw the explicit the line about .NET 6 and 7 under "Supported Runtimes" so I wasn't sure if .NET 8 introduced a breaking change that wasn't backwards compatible.

**Comment by mrbean-bremen** [comment]
Closing as answered.

**Comment by jaime-olivares** [comment]
NET 8.0 should be supported explicitly, as it is the latest LTS version, officially released few weeks ago.

Although NET Standard 2.0 may be sufficient to cover all their successor frameworks, we have verified in other projects that NET 8.0 is way superior in terms of optimization: array management, garbage collection, etc.

Moreover, the README is confusing, mentioning only support for NET 6 & 7, where NET 7 is deprecated now (but surprisingly not NET 6).
