### ISSUE TITLE
Implement JSON serialization and deserialization of DICOM objects

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#182]
A valid implementation has already been provided by @rickardraysearch in Cureos' *fo-dicom* fork, see pull requests cureos/fo-dicom#7 and cureos/fo-dicom#12. It should be fairly easy to port the relevant code from these pull requests.

It should be noted though that Rickard's implementation has a NuGet dependency on *Json.NET*. To avoid adding dependencies to *Core*, a preferred solution should be to create a separate Portable Class Library *DICOM.JSON* project and a corresponding new NuGet package for the (de)serializer functionality.

**Comment by rickardraysearch** [comment]
Thanks for the additional information! I got a couple of calm hours now and did the PR, see #186 . Comments are very welcome.

**Comment by anders9ustafsson** [comment]
PR #186 resolved this issue.
