### ISSUE TITLE
Unable to load DLL Dicom.Native.dll with .Net Framework 4.7.2

### ISSUE THREAD

**Issue by Muttleskovic** [fo-dicom/fo-dicom#1823]
Not really sure if I'm doing something wrong or it's actually a bug but I receive error when trying to render image

Error message : Decoding dataset with transfer syntax: JPEG 2000 Image Compression (Lossless Only) is not supported.

StackTrace : "at FellowOakDicom.Imaging.Codec.DicomTranscoder.Decode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)"
			"at FellowOakDicom.Imaging.Codec.DicomTranscoder.DecodePixelData(DicomDataset dataset, Int32 frame)"
			"at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)"
			"at FellowOakDicom.Imaging.DicomImage.RenderImage(Int32 frame)"

Code : 
new DicomSetupBuilder()
    .RegisterServices(s => s.AddFellowOakDicom().AddImageManager<WinFormsImageManager>())
.Build();

var image = new DicomImage("filename.dcm");
var bitmap = image.RenderImage().AsClonedBitmap(); // throws error here

**Environment**
Fellow Oak DICOM version:  5.1.3
Platform: .NET Framework 4.7.2

Sample:
[I0000001.zip](https://github.com/user-attachments/files/16159333/I0000001.zip)

Thank you

**Comment by jaime-olivares** [comment]
For dealing with JPEG 2000 images, you need to install the transcoder, as detailed here:
https://github.com/Efferent-Health/fo-dicom.Codecs?tab=readme-ov-file#usage

**Comment by Muttleskovic** [comment]
I've try to add the trascoder on DicomSetupBuilder as described in the link, but with no result.
Also it says that minimum version is "**(minimum version is .NET 5.0)**" for fo-dicom 5.x and I'm using .NET Framework and probably wont work ... at this moment I'm using both fo-dicom 5.1.3 for the fix of "pixel data is not properly closed with a SequenceDelimitationItem ([#1339](https://github.com/fo-dicom/fo-dicom/issues/1339))" and fo-dicom 4.0.8 for rendering  image which has no coded error

**Comment by jaime-olivares** [comment]
According to nuget, both fo-dicom 5.1.3 and fo-dicom.Codecs 5.14.x would support NET Framework 4.7.2 as they are built with .NET Standard 2.0 (they would not with 2.1).

You should keep trying with them. What does it mean "with no result" ? Any error messge?

**Comment by Muttleskovic** [comment]
Same error, same place :(

my setup builder looks like this :
new DicomSetupBuilder()
  .RegisterServices(s => s.AddFellowOakDicom().AddTranscoderManager<FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager>();
s.AddFellowOakDicom().AddImageManager<FellowOakDicom.Imaging.WinFormsImageManager>();)
  .SkipValidation()
  .Build();

I'm using VB.net , not sure if I write the code correctly
For me is like this : 

 Dim x = New DicomSetupBuilder
        x.RegisterServices(Sub(s)
                               s.AddFellowOakDicom().AddTranscoderManager(Of FellowOakDicom.Imaging.NativeCodec.NativeTranscoderManager)
                               s.AddFellowOakDicom().AddImageManager(Of FellowOakDicom.Imaging.WinFormsImageManager)
                           End Sub)
        x.SkipValidation
        x.Build()

**Comment by jaime-olivares** [comment]
This is a long shot, but in our own applications the transcoder is declared after the image manager, as:

````
Dim dicomSetupBuilder = New DicomSetupBuilder()
dicomSetupBuilder.RegisterServices(Sub(s)
    s.AddFellowOakDicom()
    s.AddImageManager(Of ImageSharpImageManager)()
    s.AddTranscoderManager(Of NativeTranscoderManager)()
End Sub)
dicomSetupBuilder.Build()
````

**Comment by Muttleskovic** [comment]
Well this time I have a new error tho :)
"Unable to load DLL 'Dicom.Native.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

But I have Visual C++ Redistributable v14 installed
![image](https://github.com/fo-dicom/fo-dicom/assets/20122218/9935faf9-3ddf-4fd5-8b97-a01fa2831224)

I'll try repair, and see if there is a difference

**Comment by Muttleskovic** [comment]
I've reinstalled Visual C++ Redistributable, updated fo-dicom.codecs to 5.14.2 but still get the error :
"Unable to load DLL 'Dicom.Native.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)"

**Comment by jaime-olivares** [comment]
Apparently, .NET framework cannot find the required native DLL as .NET Core does.
If you inspect your published folder, you will find that the required native DLL is `./runtimes/win-x64/native/Dicom.Native.dll`
So, in your installer config, be sure to add that nested path in the PATH environment variable.
Otherwise, in your installer directives, copy that file to be placed together with `fo-dicom.Codecs.dll`

**Comment by Muttleskovic** [comment]
I wanted to copy the .dll in run location, but it's already there. I've tried while debugging with Visual Studio and in windows installation application, I've also added in windows PATH variable. Still can't find the file.
I'll try tomorrow to set up a new application on .net 5.0/6.0, and see if works for me in some scenario

Thank you for your support so far

**Comment by jaime-olivares** [comment]
I also suggest you to review previous issues mentioning `Dicom.Native` like this one: https://github.com/fo-dicom/fo-dicom/issues/1680 (just an example)

**Comment by Muttleskovic** [comment]
I've just copied "Dicom.Native.dll" in same directory with application and it's working this way, no error and the image renders as expected.

Thank you again for your help

**Comment by jaime-olivares** [comment]
I suggest to change the title of this closed issue as something like "Unable to load DLL Dicom.Native.dll with .Net Framework 4.7.2" so other users experiencing the same can find it.
