### ISSUE TITLE
During RenderImage "Index was outside the bounds of the array." is thrown

### ISSUE THREAD

**Issue by BluerGost** [fo-dicom/fo-dicom#1833]
**Describe the bug**
Normally RenderImage function is fine. But for one ES modality type study's images the RenderImage is failing. Also, the transcode function is failing. The file successfully opens in MicroDicom and Sycorax viewer.

**To Reproduce**
``
               public static BitmapImage GetBitmapImage(DicomFile dicomFile, double? windowWidth = null, 
               double? windowCenter = null)
               {
              
                   try
                   {
                       var dicomImage = new DicomImage(dicomFile.Dataset);
              
                       if (windowWidth.HasValue) dicomImage.WindowWidth = windowWidth.Value;
                       if (windowCenter.HasValue) dicomImage.WindowCenter = windowCenter.Value;
              
                       var iimage = dicomImage.RenderImage();
              
                       var sharp = iimage.AsSharpImage();
                       using var ms = new MemoryStream();
                       sharp.SaveAsBmp(ms);
                       ms.Seek(0, SeekOrigin.Begin);
              
                       var bitmapImage = new BitmapImage();
                       bitmapImage.BeginInit();
                       bitmapImage.CacheOption = BitmapCacheOption.OnLoad;
                       bitmapImage.CreateOptions = BitmapCreateOptions.None;
                       bitmapImage.StreamSource = ms;
                       bitmapImage.EndInit();
                       bitmapImage.Freeze();
              
                       return bitmapImage;
                   }
                   catch (Exception ex)
                   {
                       Console.WriteLine(ex.Message);
                       return null; 
                   }
                   finally
                   {
                       GC.Collect();
                       GC.WaitForPendingFinalizers();
                   }
               }
``

**Expected behavior**
I expect the image to render like the other images. 

**Screenshots or test DICOM files**
I do not think the screenshot would help for this image. But since the images belongs to the client I can not send the files. Especially since it seems like the patient information is inside the pixel data. But if its not possible to solve the issue without a test data. Then kindly teach me a way by which I can remove the patient information from the pixel data. 

**Environment**
Fellow Oak DICOM version: 5.1.3
OS: Windows 11 Pro
Platform: .NET 6.0

**Comment by gofal** [comment]
Sorry, but it is very hard to help if the method always works, but except for some certain file, without having the file.

Maybe it might help if you could create a dump of the dicom file and then in this textfile you could replace patient information by some other character.
The fo-dicom project here also has a project fo-dicom.dump. It is a desktop application, that displays the dump, you could then send screenshots.
I have only one idea: modality ES means endoscopy. Might it be, that this endoscopy file does not contain images in pixeldata, but that it contains an encapsulated video file? Then it might be, that fo-dicom behaves unexpected. If this assumption might be true, then we could add an check and throw a more meaningful exception.

**Comment by BluerGost** [comment]
> The fo-dicom project here also has a project fo-dicom.dump. It is a desktop application, that displays the dump, you could then send screenshots.

Is screenshot alone enough to find the cause? If that's the only thing you need I think I can just use some kind of image software and just hide the patient information and send the screenshot.

**Comment by gofal** [comment]
No, I do not need as screenshot of the rendered image. In order to help you, I need the content of the Dicom-Tags. So either you have some tool, or your image software is capable to export the content of the Dicom Tags (the so called dicom-dump). Or else you could use the application that is contained in fo-dicom project.
Here is an example:
![image](https://github.com/user-attachments/assets/6eeb3747-f584-4578-94c8-66353028bf28)
a lot of information is in the tags starting with 0008, like the SOP Class UID or the Transfer Syntax
![image](https://github.com/user-attachments/assets/cf1e525e-bb01-4831-bdfa-310bae96aca7)
.. or at the end, if there is a tag Pixel Data, and how many bytes there are contained,
etc etc

**Comment by BluerGost** [comment]
Okay, I understand.
Currently I am a bit busy with a seperate task. So, there might be a bit delay.
But I will look into it and let you know as soon as I can.
Thanks.

**Comment by BluerGost** [comment]
@gofal 
Sorry, for the delay. 

I tried using dicom-dump. 
When I opened the dicom file using the dicom-dump the following error showed. After I press the Ok button the information shows up normally. But dicom-dump does not have an output option where I can output the tags into a text file or something. So, I decided to use MicroDicom.

![image](https://github.com/user-attachments/assets/432229f1-a4a0-4bf5-be3c-c80d296c1675)

I opened the image in MicroDicom then Anonymized it. Then I output the information in a text file. Below is the information I got from the MicroDicom.
[microdicom dicom tags.txt](https://github.com/user-attachments/files/16623011/microdicom.dicom.tags.txt)

I saw that the image information was lacking a bit in the MicroDicom output. So, I took the screenshot from the dicom-dump. Below is the screen shot that I took. 
![dicom dump image part info screenshot](https://github.com/user-attachments/assets/6cf9323d-7134-4725-a729-0d6700852560)

Hope it helps solve the problem. 
Thank you

**Comment by gofal** [comment]
I am so sorry. This is a jpeg2000 compressed file. First the data has to be decompressed, before fo-dicom starts to establish the rendering pipeline. Already transcoding is not working well.
Jpeg-compression is not in the scope of fo-dicom, but Efferent is thankfully implementing jpeg encoding for fo-dicom. You have to open an issue there. But be prepared, in order to help you, they will for sure need a sample file.
Maybe you can manage to get a test-file from the ES-modality that you can share with Efferent (https://github.com/Efferent-Health/fo-dicom.Codecs)

**Comment by jaime-olivares** [comment]
@BluerGost is this still an issue using the last versions of fo-dicom and fo-dicom.Codecs?
If so, please file a new Issue in https://github.com/Efferent-Health/fo-dicom.Codecs

**Comment by BluerGost** [comment]
@jaime-olivares @gofal 
I understand.
I need to reproduce the error in a test image. Since the original image contains patient information in the pixel data I am not able to share it.
If you have any idea how that can be done kindly let me know.
Also since I need to open a new issue in the Efferent-Health, you can close this issue if you want.
