### ISSUE TITLE
Dicom will not open but they are correct.

### ISSUE THREAD

**Issue by nico66** [fo-dicom/fo-dicom#184]
Good morning,
I'm trying fo-DICOM 2.0.0.
I'm making a program that is monitoring a large library and in some cases the method DicomFile.Open goes wrong.
With try catch the exception is: Unhandled VR in DICOM parser observer: NONE
However, the file is checked valid.
I enclose one of these files DICOM.

[14850755.zip](https://github.com/fo-dicom/fo-dicom/files/91957/14850755.zip)

Thanks and good job.

**Comment by anders9ustafsson** [comment]
@nico66 Many thanks for your report. Unfortunately the link to your DICOM file is invalid; Github only supports embedding of image files. What you can do is change the file extension of your DICOM file to .png or .jpg and try to upload it again.

**Comment by nico66** [comment]
Hello,
I downloaded in zip format and it seems to have been accepted.

**Comment by anders9ustafsson** [comment]
OK, I see the error. It seems related to what @Ed55 reported in #178. This issue is scheduled to be fixed in 2.0.1, and we will try to get a release out as soon as possible.

**Comment by Ed55** [comment]
@anders9ustafsson yes, it hits my still present breakpoints #64 / #178
