### ISSUE TITLE
DicomDataset.GetDicomItem should return null when private tag is not found but throws exception

### ISSUE THREAD

**Issue by rbqm** [fo-dicom/fo-dicom#1840]
**Describe the bug**
When passing a regular DICOM tag to DicomDataset.GetDicomItem, the method returns null if the tag is not in the dataset. This is how it should behave according to the documentation of the method.

```
<returns>Item corresponding to <paramref name="tag"/> or <code>null</code> if the <paramref name="tag"/> is not contained in the instance.</returns>
```

When passing a private tag, however, the method throws DicomDataException($"Tag: {tag} not found in dataset") if the tag is not in the dataset.

**To Reproduce**
The current implementation of GetDicomItem looks like this

```
public T GetDicomItem<T>(DicomTag tag) where T : DicomItem
{
    tag = ValidatePrivate(tag);
    return _items.TryGetValue(tag, out DicomItem dummyItem) ? dummyItem as T : null;
}
```

ValidatePrivate throws an exception if tag is private and not in the dataset

**Expected behavior**
GetDicomItem should return null also for unfound private tags. It should be written like this:

```
public T GetDicomItem<T>(DicomTag tag) where T:DicomItem
{
    if (TryValidatePrivate(ref tag) && _items.TryGetValue(tag, out DicomItem dummyItem))
    {
        return dummyItem as T;
    }
    else
    {
        return null;
    }
}
```

There may be other methods in DicomDataset that use ValidatePrivate and suffer from the same problem.

**Screenshots or test DICOM files**
N/A

**Environment**
Found in Fellow Oak DICOM 4.0.7, but still seems to exist in the latest code

**Comment by gofal** [comment]
Thanks for reporting this issue!
And you already analyzed the source. Would you like to fix it and create a PR?

**Comment by rbqm** [comment]
That is a little bit difficult. We are using fo-dicom 4.0.7 and we created a fork of that version to implement the above workaround. I just thought it would be good to report the bug here for the benefit of users of the latest version of fo-dicom.

In addition, the suggested fix may break backward compatibility. You just never know if someone depends on the current behavior. I would rather leave that decision to someone else to decide.

**Comment by gofal** [comment]
I wrote an unittest to reproduce the issue. the behavior was inconsistent. Say you have a DicomDataset without the private Tags.
If you then try to access with explict Group- and Elementnumber

    dataset.GetDicomItem<DicomItem>(new DicomTag(0x0019, 0x100A))

then `null` was returned. But when you access the tag without explicit Elementnumer, but via PrivateCreator, then the method threw an exception

    dataset.GetDicomItem<DicomItem>(new DicomTag(0x0019, 0x0A, "PHILIPS MR/PART");

So I assume this as a bug and there should be a consistent behavior.
