### ISSUE TITLE
DicomTag.AnatomicRegionSequence

### ISSUE THREAD

**Issue by xiongw1987** [fo-dicom/fo-dicom#1850]
how can i do to add DicomTag.AnatomicRegionSequence in dataset?

Dataset.Add(DicomTag.AnatomicRegionSequence,"111111"); //this wrong

**Comment by mrbean-bremen** [comment]
A DICOM sequence consists of a number of sequence items (1 in this case), each of which is itself a DicomDataset, so you have create a sequence containing a data set as a sequence item, e.g. something like:
```cs
dataset.Add(new DicomSequence(DicomTag.AnatomicRegionSequence, 
    new DicomDataset(
        new DicomShortString(DicomCode.CodeValue, "...."),
        new DicomShortString(DicomCode.CodingSchemeDesignator, "...."),
        new DicomShortString(DicomCode.CodingSchemeVersion, "...."),
        ...
    )
);
```
You have to check the DICOM standard for the concrete values you need for your case.

**Comment by xiongw1987** [comment]
thank you very much!!!!

**Comment by mrbean-bremen** [comment]
Closing as answered.
