### ISSUE TITLE
DicomPixelData.Create is broken for signed pixel data with BitsAllocated != BitsStored

### ISSUE THREAD

**Issue by rickardraysearch** [fo-dicom/fo-dicom#187]
See the failing tests added in Dicom.Imaging.Render.PixelDataTest in https://github.com/rickardraysearch/fo-dicom/tree/pr-failing-tests . I have a fix available in https://github.com/rickardraysearch/fo-dicom/tree/pr-fix-pixeldata that switches to use arithmetic shift for sign extension, which I think is more readable and easy to verify.

**Comment by IanYates** [comment]
I agree, your changes do seem easier to understand and reason about.

**Comment by anders9ustafsson** [comment]
@rickardraysearch Looks great, Rickard! Please make a pull request from your fix branch and we can include the fix in 2.0.1.

**Comment by anders9ustafsson** [comment]
Fixed with PR #189.
