### ISSUE TITLE
New implementation in DicomClient. 

### ISSUE THREAD

**Issue by DouglasMachas** [fo-dicom/fo-dicom#1872]
In a certain case, it was necessary to create a fo-dicom Client and define its local TCPClient IP.
We implemented a configuration in the DesktopNetworkStream class to force a local IP when creating the TCPClient:

![image](https://github.com/fo-dicom/fo-dicom/assets/147630415/df779817-283e-4a73-a36d-acc63b2b14a5)

Please, implement this functionality in new versions, so that it is possible to define the local IP of the TCPClient.
There are servers that do not accept more than one IP in the registration for reception, however there are cases where we need to upload more than one client to communicate with a server.

**Comment by gofal** [comment]
fo-dicom tries to take advantage of Dependency Injection as much as possible. For example, internal classes like the `INetworkStream` are resolved from a DI-Container. A global Setup method on startup registers all the default implementations to the DI-container, but you can create your own implementations and register those on Setup.

So if someone requires some very special handling - just as you mention here - then you can inherit from some default implementation, override some methods and implement your own methods, and then register you implementation in DI.

Does that work for you?

**Comment by DouglasMachas** [comment]
Like that, right?

new DicomSetupBuilder()
            .RegisterServices(s =>
            {
                s.AddScoped<INetworkStream, CustomNetworkStream>();
            })
            .Build();

This way works for me.
Thanks.

**Comment by DouglasMachas** [comment]
> fo-dicom tenta tirar vantagem da Injeção de Dependência o máximo possível. Por exemplo, classes internas como a `INetworkStream`são resolvidas de um DI-Container. Um método Setup global na inicialização registra todas as implementações padrão no DI-container, mas você pode criar suas próprias implementações e registrá-las no Setup.
> 
> Então, se alguém precisar de algum tratamento muito especial - como você mencionou aqui - você pode herdar de alguma implementação padrão, substituir alguns métodos e implementar seus próprios métodos e, então, registrar sua implementação no DI.
> 
> Isso funciona para você?

**Comment by jaime-olivares** [comment]
It seems @gofal 's explanation about using DI for customizing solves the problem. 
Can this be closed now?
