### ISSUE TITLE
Fo-dicom 5 unable to read private tags

### ISSUE THREAD

**Issue by bec1442** [fo-dicom/fo-dicom#1874]
**Environment**
Fellow Oak DICOM version: 5.1.3
OS: (e.g. Windows 10 x64)
Platform: (e.g. .NET Framework 4.8)

The following code does not work
```
//define private tag 
DicomTag privateTag = new DicomTag(0x3253, 0x1000);
// Check if private tag exist
if (dicomDataset.Contains(privateTag))
{
    //read tag byte-by-byte
    byte[] privateTagData = dicomDataset.GetValues<byte>(privateTag);
}
else
{
Console.WriteLine($"Private tag {privateTag} not found in the dataset.");
}
```
**output:  Private tag (0x3253, 0x1000) not found in the dataset.**
However, I verified the tag (0x3253, 0x1000) does exists

**Comment by mrbean-bremen** [comment]
fo-dicom checks if this is a valid private tag (e.g. has a valid private creator), otherwise it is ignored. Are you sure your dataset has a valid private creator, e.g. (3253, 0010) in your case?

**Comment by bec1442** [comment]
Yes, it does have the creator tag (3253, 0010).  I can replace the tag (for code above and print value to console)

**Comment by mrbean-bremen** [comment]
Ah, sorry - I missed that you have created the private tag incorrectly. 
A private tag is characterized by the group, the (1-byte) element offset and the Private Creator string, so to create a valid private tag, you need something like:
```cs
var privateTag = new DicomTag(0x3253, 0x00, "YOUR PRIVATE CREATOR");
// Check if private tag exist
if (dicomDataset.Contains(privateTag))
{
...
```
The upper byte (0x10) is not part of the private tag, it just references the private block where it is stored.

**Comment by bec1442** [comment]
No need to be sorry, on the contrary, I am grateful that you are spending your personal time to help others. I thank you for that.
In any case, just to clarify, both creator tag (0x3253, 0x0010) and private tag (0x3253, 0x1000) already exist, I just need to replace/update existing contents of (0x3253, 0x1000) which is type VR=OB

Here is what I m trying so far:

string longString =” <?xml version="1.0"?>
<customers>
   <customer id="55000">
      <name>Charter Group</name>
      <address>
         <street>100 Main</street>
         <city>Framingham</city>
         <state>MA</state>
         <zip>01701</zip>
      </address>
   </customer>
</customers>”; 

// Convert the string to a byte array
 byte[] byteArray = Encoding.UTF8.GetBytes(longString);
var privateTag = new DicomTag(0x3253, 0x1000, privateCreator);
if (dicomDataset.Contains(privateTag))
{
//update the private tag with contents of byteArray 
dicomFile.Dataset.AddOrUpdate<byte[]>(DicomVR.OB, privateTag, byteArray);  //does not work

}

**Comment by mrbean-bremen** [comment]
So I guess reading the tag did work now?
Writing a value with VR OB does not work using `byte[]`, you need an `IByteBuffer` object instead, e.g. something like:
```cs
    string longString = "Charter Group...";
    var bytes = ByteConverter.ToByteBuffer(longString);
    dataset.AddOrUpdate(DicomVR.OB, privateTag, bytes);
```

**Comment by bec1442** [comment]
Many thanks, that worked!!!

**Comment by mrbean-bremen** [comment]
Good to knoe - closing in this case.
