### ISSUE TITLE
Extracting coronal and sagittal cuts

### ISSUE THREAD

**Issue by Charrette** [fo-dicom/fo-dicom#188]
Hi,

I need to be able to have a 3D representation of a DICOM image. I suppose that a good start would be to get the sagittal and coronal cuts.

Right now, it seems like 'DicomImage' is only extracting the axial cut from a DICOM file.

Being able to easily get the coronal and sagittal cuts would be perfect :)

**Comment by IanYates** [comment]
Hi @Charrette  - do you have any sample files you might be able to share?

It's probably unlikely we'll be doing 3D rendering anytime soon but the word "cut" implies these are more 2D planes rather than 3D objects anyway, correct?  If that's the case then we may be able to do something to at least allow the other planes to be extracted.

**Comment by Charrette** [comment]
3D rendering would be my part of the job I guess. What I mean is (and tell me if i'm wrong, i'm new to all of this) :

![dicom sample](https://cloud.githubusercontent.com/assets/5971466/12383299/8d390c00-bdce-11e5-978a-d27d3361a343.jpg)

Here from left to right you have : axial cut, sagittal cut and coronal cut. So this would give 3 planes, like x,y,z, which would allow to "mix" them in a way and have a 3D representation (assuming we could have the coordinates of each points of each planes), no?

**Comment by IanYates** [comment]
DICOM is a huge thing - I myself only use a little bit of it :)

If that's the kind of data you've got then there's not enough for a 3D rendering.  You're more likely to want a single plane (like an X/Y axis) and then a bunch of slices representing steps along the Z axis.

When you get the data for those three cuts are they given via a single file?  If so, can you possibly run the file through an anonymizer and post it here?  (see http://dicom.dvtk.org/modules/wiwimod/index.php?page=DICOM+Anonymizer&cmenu=products for one such tool)

**Comment by Charrette** [comment]
No, my bad, that's not from a single file. I first though that those 3 images where stored in the DICOM file just like that and that's why I wanted to extract them.

But finally it seems like we can get those 2 other planes only from multiple slices of the first plane, right?

So there must be some kind of calculation to make on each slice to be able to get those other planes ?

**Comment by IanYates** [comment]
Maybe...  I'll wait to see if someone else can chime in who knows more about that type of imaging.

I usually let the diagnostic machines give me output and I manipulate it as little as possible so I can't get it wrong (no missed diagnosis on my watch if I can help it!).  Do you have any control over the machine feeding you that data or do you just have to take what you're given?

**Comment by Charrette** [comment]
I'm just taking what i'm given. Well meantime I'll try to figure out what this is about and come back later ;)

**Comment by anders9ustafsson** [comment]
Currently, *fo-dicom* supports that, when you render an image out of `DicomImage`, you pick a single frame (normally in the axial plane) from a multi-frame image, hence the `frame` argument in `DicomImage.RenderImage`. But if you have a multi-frame image, you might just as well slice the image data perpendicular to the frames, i.e. coronal and sagittal cuts. 

Such an enhancement would not be too demanding implementation-wise, but maybe it is also too limiting? 

If, on the other hand the request is to provide general functionality for generating digitally reconstructed radiographs from a set of single-frame images, the amount of work expands considerably.

@Charrette and others, what would be your expectations if we were to implement 2D cuts from 3D pixel data?

**Comment by hdesouky** [comment]
The multi planar reconstruction (MPR) can be done using a 3D reconstruction
tools like VTK (and its .NET wrapper Activiz)

DICOM may have AXIAL, SAGITAL or even CORONAL cuts, it is not about AXIAL
cuts all the time



On Mon, Jan 18, 2016 at 4:13 PM, Anders Gustafsson <notifications@github.com
> wrote:

> Currently, *fo-dicom* supports that, when you render an image out of
> DicomImage, you pick a single frame (normally in the axial plane) from a
> multi-frame image, hence the frame argument in DicomImage.RenderImage.
> But if you have a multi-frame image, you might just as well slice the image
> data perpendicular to the frames, i.e. coronal and sagittal cuts.
>
> Such an enhancement would not be too demanding implementation-wise, but
> maybe it is also too limiting?
>
> If, on the other hand the request is to provide general functionality for
> generating digitally reconstructed radiographs from a set of single-frame
> images, the amount of work expands considerably.
>
> @Charrette <https://github.com/Charrette> and others, what would be your
> expectations if we were to implement 2D cuts from 3D pixel data?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fo-dicom/fo-dicom/issues/188#issuecomment-172536679>.
>



-- 
Hesham Desouky

**Comment by anders9ustafsson** [comment]
@hdesouky Many thanks for the clarification and suggestions.

**Comment by GMZ** [comment]
ClearCanvas's MPR and 3D module uses ITK & VTK, if you get the source code(assuming it has not been pulled) you can have this running in a few hours. then you can build a 3D volume and and re-slice in any plane or angle dynamicly and extract new series.

**Comment by GMZ** [comment]
The other option is if you have  CORONAL, SAGITAL and AXIAL series is to create a space pointer tool, the syncs each series as you Cine in any Plane.

**Comment by anders9ustafsson** [comment]
Deeming this request to be out of-scope for *fo-dicom*. Please rely on full-fledged image processing tools like ITK/VTK for this functionality.
