### ISSUE TITLE
DicomCodecException in .NET 8

### ISSUE THREAD

**Issue by VETWorks** [fo-dicom/fo-dicom#1882]
**Describe the bug**
I'm trying to render a Dicom to an image through either the System.Drawing image renderer or the ImageSharp one. In both cases, I keep getting the following error:

```
FellowOakDicom.Imaging.Codec.DicomCodecException: 'Decoding dataset with transfer syntax: JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression is not supported.'
```

I'm compiling for the x64 platform, I'm not using "Any CPU".

I have the same issue with .NET 6, .NET 9. When creating a .NET 4.8 version, there is no issue. I can open and render the Dicom with no issues.

**To Reproduce**

1. Create a new .NET 8 Console program
2. Add Nuget references to "fo-dicom", "fo-dicom.codecs" and "fo-dicom.imaging.imagesharp" or "fo-docim.imaging.desktop"
3. Open Dicom file and use RenderImage()

**Expected behavior**
I expect to be able to get a Bitmap or SharpImage.Image object

**Screenshots or test DICOM files**
<img width="938" alt="image" src="https://github.com/user-attachments/assets/2d10c93e-d764-4b83-abf0-18b81c1391f5">
<img width="593" alt="image" src="https://github.com/user-attachments/assets/a4ba00e0-ee37-4983-8f51-ba444b8395c6">

Minimal project file including the sample Dicom:
[minimal project.zip](https://github.com/user-attachments/files/17789005/minimal.project.zip)

Sample Dicom file:
[sample.dcm.zip](https://github.com/user-attachments/files/17789017/sample.dcm.zip)

**Environment**
Fellow Oak DICOM version: 5.1.4
OS: Windows 11 ARM64
Platform: .NET 8

**Comment by gofal** [comment]
I assume, the issue is that you are using DI the wrong way. 

The call `AddFellowOakDicom(this IServiceCollection)` adds all the default services. 

So acutally you called

    .AddFellowOakDicom()    // here among others the RawImageManager and the DefaultTranscoderManager are registered.
    .AddTranscoderManager<NativeTrascoderManager>() // here you are adding the NativeTranscoderManager, which replaces the DefaultTranscoderManager
    .AddFellowOakDicom()    // no you add all the default services again replacing others. meanung you add the DefaultTranscoderManger again replacing the NativeTranscoderManager
    .AddImageManager<ImageSharpImageManager>()   // here you add ImageSharpImageManager replacing the RawImageMangager.

What your Initialization instead should look like, is:


    new DicomSetupBuilder()
        .RegisterServices(s => s
            .AddFellowOakDicom()
            .AddTranscoderManager<NativeTranscoderManager>()
            .AddImageManager<ImageSharpImageManager>()
        )
        .SkipValidation() // for whatever reason you add this. please try to build your application in a way, that this skipping is not necessary, as this means, that you are knowingly creating and distributing _invalid DICOM data_
        .Build();

**Comment by VETWorks** [comment]
You are right. Thanks for pointing out and taking the time to explain.

Now it's working again, and we're getting the error "Unsupported OS Platform". This is OK as we're running on ARM64 and the fo-dicom.codecs doesn't yet support the platform. Hopefully they will in the future.

**Comment by sutirthpatel** [comment]
I am getting similar error while "stowrs" in DicomCloudWeb .net core. 

Decoding dataset with transfer syntax: MPEG-4 AVC/H.264 BD-compatible High Profile / Level 4.1 is not supported.

![Image](https://github.com/user-attachments/assets/93d93fb4-c987-41d0-9448-5ccd94b86bad)

**Comment by gofal** [comment]
> I am getting similar error while "stowrs" in DicomCloudWeb .net core.

> Decoding dataset with transfer syntax: MPEG-4 AVC/H.264 BD-compatible High Profile / Level 4.1 is not supported.

two things I noticed: when building up your DI services, you are calling '.AddFellowOakDicom' two times, the second time after calling `.AddTranscoderManger`. With that, you are overwriting the NativeTranscoderManager by calling AddFellowOakDicom which then registers the RawTranscoderManager.

the other thing is, that the errormessage is valid: https://github.com/efferent-Health/fo-dicom.Codecs?tab=readme-ov-file#supported-codecs
NativeTranscoderManager support all common image-codes to that you can open a Dicom-image and render the Images. But Mpeg4 is a video. there you have to extract the pixeldata and pass it over to some other application that is able to play videos.

**Comment by mcullifer** [comment]
I have this issue in a .NET 9 API project. Registered with the DI container
```csharp
services.AddFellowOakDicom()
	.AddTranscoderManager<NativeTranscoderManager>()
	.AddImageManager<ImageSharpImageManager>();
```
Fails when `.RenderImage()` is called with
`FellowOakDicom.Imaging.Codec.DicomCodecException: Decoding dataset with transfer syntax: JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression is not supported.`
You can't get any more simple than that setup.

I've attempted upgrading my API project from fo-dicom 4x to 5x multiple times but I always encounter this issue. This was across multiple .NET versions between 6 and 9 and this issue never goes away. I've found random comments saying changing build target from AnyCPU to x64 or x86 fixes this. It does not fix it. The only way it works is reverting back to fo-dicom 4x with fo-dicom.NetCore and using the [deprecated Efferent.Native package](https://www.nuget.org/packages/Efferent.Native). I've been trying to make this transition for a few years now and this is always the road block. What is the issue? I see so many people having this problem and the issues end up closed, but every "fix" for them doesn't actually work.

**Comment by jaime-olivares** [comment]
Just passing by, I notice the environment is: OS Windows 11 ARM64
fo-dicom.Codecs didn't support win-arm64 until now.
If you intend to use fo-dicom on that environment, use codec version [5.16.1](https://www.nuget.org/packages/fo-dicom.Codecs/5.16.1) or higher.
