### ISSUE TITLE
Green background image can not change the window

### ISSUE THREAD

**Issue by BluerGost** [fo-dicom/fo-dicom#1902]
**Describe the bug**
I have a study which when opened shows Green background. 
![image](https://github.com/user-attachments/assets/0b989ea4-403f-4264-becd-eabb5d0d10f2)

There is no WindowWidth and WindowCenter tag available for any of the image of that Study. 
But when I use DicomImage class the WindowWidth is 255 and WindowCenter is 127. 
So, I took those values and assigned to the dataset of the dicom using AddOrUpdate. 

Normally the following code is able to update the window values of the image. But in this case it does not seem to be changing the WindowWidth and WindowCenter.
I am wondering if it is due to the fact that it is might not be a grayscale image.

```
 var dicomImage = new DicomImage(dicomFile.Dataset);
 if (windowWidth.HasValue) dicomImage.WindowWidth = windowWidth.Value;
 if (windowCenter.HasValue) dicomImage.WindowCenter = windowCenter.Value;
 var iimage = dicomImage.RenderImage();

```
**Environment**
Fellow Oak DICOM version: (e.g. 5.1.1)
OS: (e.g. Windows 10 x64)
Platform: .NET 6.0

**Comment by mrbean-bremen** [comment]
Can you show some information about the image? E.g. at least the transfer syntax, and the image related tags (group 28)?

**Comment by mrbean-bremen** [comment]
An anonymized version of the image would be even better, of course...

**Comment by BluerGost** [comment]
@mrbean-bremen ,
Is this enough?
![image](https://github.com/user-attachments/assets/94858878-9f96-4752-aac8-fb3a0419389a)

**Comment by mrbean-bremen** [comment]
Hm, nothing interesting here... What transfer syntax has it used? And how does the image look in another renderer like MicroDicom or Weasis?

**Comment by jaime-olivares** [comment]
This won't be easy to diagnose without the entire DICOM file (anonymized is ok).
Also, if possible, try to get a screenshot of the same image opened by another viewer.

**Comment by BluerGost** [comment]
> Hm, nothing interesting here... What transfer syntax has it used? And how does the image look in another renderer like MicroDicom or Weasis?

MicroDicom also shows the image as green background. But it is able to change the window size of the image.


My Viewer
![image](https://github.com/user-attachments/assets/29849539-4277-4908-ba79-eb02ab9ee196)

MicroDicom
![image](https://github.com/user-attachments/assets/75e75a4c-c2dc-48f9-a01f-cb24e8b7b207)

**Comment by mrbean-bremen** [comment]
Ok, sorry - I  misunderstood the issue, I thought the image was incorrect from the start (greenish images often happen if something goes wrong with the decoding).
 
Yes, it may be that windowing RGB images is not supported, though I'm not sure - @gofal can probably answer this right away.

**Comment by BluerGost** [comment]
It's all good.
Okay, I will wait for his response then.

Also, Maybe this is a bit unrelated to the original question. But is there any function in fo-diocm that can transfer RGB to Grayscale image. I was thinking if Fo-Dicom can not change the window of the RGB then maybe converting it to GrayScale will enable Fo-Dicom to change the window size.

**Comment by jaime-olivares** [comment]
@BluerGost I have seen this issue before. Your image should be a secondary capture coming from a video source and seems to be encoded with YBR color encoding. However, your DICOM says RGB.

Have a look how your image looks if I interpret it as YBR:

<img width="702" alt="image" src="https://github.com/user-attachments/assets/6a8c83b4-c3ce-42fc-8904-674fef4074e4">

You may try to edit your DICOM file to alter tag 0028,0004 (Photometric interpretation) and replace RGB with one of the following values:
- YBR_FULL
- YBR_PARTIAL_420
- YBR_RCT

Then try to open it with a viewer and determine if you can see the image similar to the one I sent.
That will confirm that your DICOM is not well-formed.

**Comment by BluerGost** [comment]
@jaime-olivares 

When I set to YBR_FULL it looks like the image you sent.
By well-formed you mean the image data(pixel data) is not correctly formed?
In such case what can be done?

**Comment by jaime-olivares** [comment]
The pixel data is good. The Photometric interpretation is wrong.

**Comment by BluerGost** [comment]
@mrbean-bremen  
But even when I set it to YBR_FULL the window can not be changed.

**Comment by mrbean-bremen** [comment]
These are separate issues: the incorrect Photometric Interpretation as mentioned by @jaime-olivares (this was the reason that I misunderstood the issue in the first place), which is just a problem with the the dataset, and the (probable) inability to use windowing on RGB images in fo-dicom (which, if true, would be a feature request).

**Comment by BluerGost** [comment]
@mrbean-bremen 
I understand. 

I will further look into it. There seems to be something really weird going on with this study.

**Comment by jaime-olivares** [comment]
@BluerGost One of the claims is solved, as per mentioned in the title (green background related to YBR encoding).
The other one is a duplicated request (window/level over 3-channel images). See https://github.com/fo-dicom/fo-dicom/issues/706 
I think you can close this issue.

**Comment by BluerGost** [comment]
Okay, I will close the issue thank you for your help.
