### ISSUE TITLE
If DicomServer already running, get instance of them

### ISSUE THREAD

**Issue by domitor1927** [fo-dicom/fo-dicom#191]
Hello, after create one Server with DicomServer in one web aplication if i kill server and restart they will try create another DicomServer but like the other are running they will throw one exception and dont work more. It's any way that if are running they will use the instance of the server that are running?

**Comment by IanYates** [comment]
Hi @domitor1927  - what version of fo-dicom are you running?  @anders9ustafsson has just published 2.0 and we made quite a few changes to the implementation of `DicomServer` and its lifetime management for that release.

**Comment by anders9ustafsson** [comment]
@domitor1927 I am adding your second statement from the chat forum, because I think it contains the relevant functionality requests:

> like one public bool DicomServer.AnyRunning() or/and public DicomServer<T> DicomServer.GetActualInstance()

I am not sure if you deliberately omitted it, but to me those proposed methods would ideally be `static` and include a `port` argument. Agreed? 

As I wrote in the chat forum, you should be able to obtain the same functionality relatively easily in your own code, but if there is enough interest in the community we could also consider to include this support in the class library itself.

**Comment by domitor1927** [comment]
@IanYates  yes i have see the 2.0, i am using the 2.0.3 Beta and i will upgrade, but don't have this funcionality that i need.

@anders9ustafsson Yes it's like you say, will be static and have one port argument. i prefer that will be on the class library, because in updates , upgrades, etc, will be more safe if don't are in a little hack in my code.

**Comment by domitor1927** [comment]
@anders9ustafsson i will test. the version are the 2.1.0?

**Comment by anders9ustafsson** [comment]
@domitor1927 Yes. It is not yet available on NuGet, so you have to download and build the latest code from the *development* branch on Github.

**Comment by domitor1927** [comment]
i will test. 5 stars for your work

**Comment by domitor1927** [comment]
Hi @anders9ustafsson,
i just have VS2012. i download the last fo-dicom-development but i cant to build. it's any way to i build one and get the dll to use in my project and test?

**Comment by anders9ustafsson** [comment]
I am sorry, @domitor1927 , but VS 2012 is not an option; there are far too many modern features such as C# 6 etc. in the *fo-dicom* code now for VS 2012 to work.

I strongly recommend that you download VS 2015 Community and work with this instead.

**Comment by domitor1927** [comment]
you can send me the .dll buil files to i test? 
i use the Dicom.Core.dll,

**Comment by anders9ustafsson** [comment]
@domitor1927 It is probably time to make a 2.1 beta release relatively soon. Please check out for it.
