### ISSUE TITLE
DicomImage GrayscaleRenderOptions cannot be set after initialization

### ISSUE THREAD

**Issue by niklr** [fo-dicom/fo-dicom#193]
Is there a reason why the GrayscaleRenderOptions cannot be set after the initialization of a DicomImage? 

I would like to change it to GrayscaleRenderOptions.FromMinMax(Dataset); instead of GrayscaleRenderOptions.FromDataset(Dataset); which is used in the private CreatePipeline method.

**Comment by anders9ustafsson** [comment]
@niklr The `GrayscaleRenderOptions.FromDataset()` that is used in the `DicomImage` initialization is itself an aggregate method that invokes, in order of applicability, `FromWindowLevel`, `FromImagePixelValueTags` or `FromMinMax`.

To override this behavior, you can use the same approach as the *DICOM Dump* application, namely call `GrayscaleRenderOptions.FromMinMax(image.Dataset)` and set the image's `WindowCenter` and `WindowWidth` to the computed values in the render options object, see [here](https://github.com/fo-dicom/fo-dicom/blob/development/Tools/DICOM%20Dump/DisplayForm.cs#L192).

Of course, it might be desirable to control in which order of priority `GrayscaleRenderOptions.FromDataset` selects which underlying `From...` method to call, and also allow this priority order to be set in `DicomImage` initialization? Anyone who thinks that would be a welcome extension, please make your voice heard :-)

**Comment by niklr** [comment]
This was exactly what I was looking for even though I didn't expected that the WindowWidth and WindowCenter influence the "brightness" of the image.

With setting the WindowWidth & WindowCenter

    GrayscaleRenderOptions options = GrayscaleRenderOptions.FromMinMax(image.Dataset);
    image.WindowWidth = options.WindowWidth;
    image.WindowCenter = options.WindowCenter;

<img width="225" alt="fo_dicom_1" src="https://cloud.githubusercontent.com/assets/4712166/12420533/905a3b08-bebd-11e5-8b15-891a1c963866.png">

Without setting the WindowWidth & WindowCenter 

<img width="216" alt="fo_dicom_2" src="https://cloud.githubusercontent.com/assets/4712166/12420540/95248ada-bebd-11e5-8d27-621b92aa9ece.png">
