### ISSUE TITLE
CompositeByteBuffer ArgumentException

### ISSUE THREAD

**Issue by DrainSmith** [fo-dicom/fo-dicom#195]
With the attached image (in zip) an ArgumentException will occur in CompositeByteBuffer.cs at line 78. This is the BlockCopy and appears to be because the 'remain' variable is off by one too high from the length of the 'temp' buffer. 

[C9.zip](https://github.com/fo-dicom/fo-dicom/files/98387/C9.zip)

**Comment by anders9ustafsson** [comment]
@DrainSmith Thanks for reporting, and especially thank you for debugging, it makes the bug fix procedure so much easier.

I think I have found the problem: in the `BlockCopy` calls the number of bytes copied is set to `remain`, but as far as I can see it should be set to `count`. As long as the length of the `Buffers`' data array is equal to `count`, this issue goes unnoticed. However, in your particular case the data array had the size one larger (an even number) than `count` (which was an odd number).

Everyone interested, please look at the code starting [here](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/IO/Buffer/CompositeByteBuffer.cs#L50) to determine if I have come to a correct conclusion.

I will schedule a bug fix for 2.0.1.

**Comment by DrainSmith** [comment]
@anders9ustafsson Thank you very much for working on this. From what I can tell, the real length of the data in the file is the smaller, odd number, according to other imaging programs. I just tested switching out `remain` with `count` and that does load the image properly so I at least have a temporary fix for these problem images. I don't know if that will fix this permanently for all images, especially multi-frame ones. I'm going to see if I can dig up some multi-frame images to test with.
