### ISSUE TITLE
Prefer encoding UTF8 over ASCII for increased portability

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#2]
When porting .NET Framework libraries to Portable Class Libraries, or for that matter Windows 8 (desktop/tablet) and Windows Phone libraries or applications, one often occurring issue is the use of `Encoding.ASCII` or `ASCIIEncoding`. This property and class, respectively, are not supported in PCL and the modern platforms. To work around this issue, I have consistently switched over to *UTF8* encoding, of which *ASCII* is a subset.

I have examined the source code in this repository, and *UTF8* has been used in most places. Right now there is only *one* occurrence that would be a conflict if/when porting to PCL and the modern platforms, and it is [this](https://github.com/fo-dicom/fo-dicom/blob/master/DICOM/Network/PDU.cs#L34) line in *PDU.cs*:

    _encoding = Encoding.ASCII;

If you all approve, I would to change this line to:

    _encoding = Encoding.UTF8;

**Comment by IanYates** [comment]
On the basis that, presumably, only the lower end of ASCII (0-127) would be written through here anyway, switching to UTF8 should be safe  :+1:

**Comment by hdesouky** [comment]
I am not that expert on DICOM PDUs and communication protocol, are you sure this will not introduce any issues with modalities or other PACS vendors?

**Comment by anders9ustafsson** [comment]
You might be right, @hdesouky , I have been a little concerned about this myself when I have given it some extra thought lately. What if the DICOM stream is corrupt and contains bytes that is valid UTF-8 but not valid ASCII?

I will set up a few unit tests, and if they fail I will need to propose a different solution to this issue. I'll re-open this issue to get a placeholder for the unit tests.

**Comment by anders9ustafsson** [comment]
I have now checked the explicit occurrences of *UTF-8* encoding in the *DICOM* assemblies, of which I am historically responsible for all, I think :-)

First of all, I have checked how well it would work to replace `Encoding.ASCII` with the construct `Encoding.GetEncoding("us-ascii")` in a portable class library. The latter construct will compile, but when it is consumed from a *Windows Phone 8.1* application (and, most likely from any Windows Phone application), an `ArgumentException` is thrown stating that encoding *us-ascii* is not supported on the specific platform. From a PCL perspective this workaround is thus unfeasible.

The question then boils down to, is it sufficient to replace `Encoding.ASCII` with `Encoding.UTF8`, given that *UTF-8* covers a substantially larger character set than *ASCII* and thus may interpret characters that *ASCII* encoding would reject?

Here is a summary of *UTF-8* using in the *DICOM* assembly, which should hopefully confirm that replacement is sufficient:

##### `IO\Reader\DicomReader`
Used to convert 2 bytes into a Value Representation (VR) code that is subsequently matched against known VR codes. Since VR codes are ASCII only matching is bound to fail if the 2 bytes are non-ASCII.

##### `IO\Reader\DicomFileReader`
Used to convert an array of bytes into a VR code, a file type recognition code ("ACR NEMA..." strings) or transfer syntax UID, which are respectively matched against a list of known values. Known values are ASCII only, so matching will always fail if the bytes are converted into one or more non-ASCII characters.

##### `IO\ByteConverter`
`ToByteBuffer` methods use `Encoding.UTF8` by default if encoding is not explicitly specified in the method call. Since these are general methods for conversion of strings into byte buffers, it actually seems reasonable to use as generic encoding as possible if consumer does not request otherwise.

##### `Network\PDU`
Encoding for the `RawPDU` class, which is (or should be) used to configure the binary readers and writers. Right now hard coded, should it be configurable? Otherwise it seems reasonable to use as wide-ranging encoding as possible here also, since (I don't think) it is not not known at this location that the encoding may be limited e.g. to the ASCII character repertoire.

Looking at the `RawPDU` constructors [here](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Network/PDU.cs#L27) and [here](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Network/PDU.cs#L41), it also does seem that encoding initialization is happening in the wrong order or not at all; the binary reader/writer creators are invoked without `_encoding` having been initialized, which at first glance appears to be in error. I will investigate this further and if necessary post a new issue report.

##### `DicomEncoding`
Here, `DicomEncoding.Default` is set to `Encoding.UTF8`, which is inconsistent with the DICOM standard where the default character repertoire matches the printable characters of the US ASCII character set, plus the control characters FF, LF, CR, TAB and ESC. (In a strict sense, `Encoding.ASCII` is then also too broad, since it covers a larger set of control characters.)

As far as I can tell, the biggest risk with using `Encoding.UTF8` instead of `Encoding.ASCII` here, is that the *DICOM* assembly accidentally can send non-ASCII characters to a recipient that is incapable of handling a this broader character set.

For most accurate representation of `DicomEncoding.Default`, its definition should thus, for now, be switched back to `Encoding.ASCII`. I will post an issue report for this and make the necessary pull request in a short while.

At the same time, this means that the `DicomEncoding` class will not be fully portable to PCL. The solution for that issue will need to be dealt with at a later stage.
