### ISSUE TITLE
Add VR Other Long (OL)

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#201]
The recently approved Supplement 181 (ftp://medical.nema.org/medical/dicom/final/sup181_ft_TractographyResultsStorage.pdf) introduces a new Value Representation *Other Long* (OL).

The new VR type should be included in *fo-dicom*.

**Comment by Ed55** [comment]
@anders9ustafsson 
I am very sure they will come over shortly with the new Value Representation *Other Other* (OO).
:-D
But this will keep us busy.

**Comment by anders9ustafsson** [comment]
@Ed55 :-)
