### ISSUE TITLE
DicomDecimalString constructor fails with decimals if CurrentCulture has decimal commas

### ISSUE THREAD

**Issue by rickardraysearch** [fo-dicom/fo-dicom#202]
See the failing test in rickardraysearch/fo-dicom@e640ba4453ecf05c04e7dacdd631926b3487f574 .

**Comment by rickardraysearch** [comment]
Fix in rickardraysearch/fo-dicom@dee51ca1381373fadfc2017cdfa5927c07c5e4b6

**Comment by anders9ustafsson** [comment]
Well spotted, @rickardraysearch ! Will adopt your PR soon. Many thanks!

**Comment by IanYates** [comment]
:+1:
