### ISSUE TITLE
DicomReader reads past end of file if empty private sequence is last attribute in dataset

### ISSUE THREAD

**Issue by Ed55** [fo-dicom/fo-dicom#220]
Today I was facing a crash in the parser trying to parse a private SOP Class.
The last attribute happens to be a private empty sequence.
The `IsPrivateSequence(source)` crashes because it tries to read data from the stream, but its already EOF.
A short (synthetic) sample here: ![privatesopmod](https://cloud.githubusercontent.com/assets/15705674/12991690/9c55692c-d110-11e5-8fac-c742de45818e.png) (rename png to dcm).
This should be a valid dataset because its a private SOPClass.

As I mentioned in #177 I am no fan of this two IsPrivateSequence... methods, but I am in a hurry.

For now I fixed it in the two `ParseValue(IByteSource source)` branches by replacing `while (this._vr == DicomVR.SQ && this._tag.IsPrivate)` with `while (this._vr == DicomVR.SQ && this._tag.IsPrivate && this.length > 0 )`
This fix passes all of my paser test case created for #177, #178, #179.

**Comment by anders9ustafsson** [comment]
@Ed55 Thank you again for your invaluable bug reporting and fix suggestions. I will look this over as soon as possible.

And I agree, `DicomReader` would certainly benefit from a major refactoring. When time permits :-)
