### ISSUE TITLE
Deflate Transfersyntax

### ISSUE THREAD

**Issue by cfackroth** [fo-dicom/fo-dicom#227]
Hi,

it seems to be that "Deflated Explicit VR Little Endian" is not supported yet. It would be nice if this can be added in one of the next releases.

Thanks

**Comment by anders9ustafsson** [comment]
@cfackroth It is included in the list of known transfer syntaxes, see [here](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/DicomTransferSyntax.cs). Could you be a little bit more specific about what you are missing?

**Comment by cfackroth** [comment]
Sure but the property IsDeflate is evaluated nowhere. To change the transfer syntax I use DicomCodecExtensions.ChangeTransferSyntax which create a new DICOM but it is not deflated. The resulted DICOM is not really smaller (I understand deflated is something like GZIP) and also not readable for example by dcm4che.

Von: Anders Gustafsson [mailto:notifications@github.com]
Gesendet: Freitag, 19. Februar 2016 08:49
An: fo-dicom/fo-dicom <fo-dicom@noreply.github.com>
Cc: Christian Fackroth <Christian.Fackroth@marabu-edv.de>
Betreff: Re: [fo-dicom] Deflate Transfersyntax (#227)


@cfackroth<https://github.com/cfackroth> It is included in the list of known transfer syntaxes, see here<https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/DicomTransferSyntax.cs>. Could you be a little bit more specific about what you are missing?

**Comment by anders9ustafsson** [comment]
@cfackroth OK, thanks for reporting and for the clarification. I am even tempted to label it as a bug since change transfer syntax does not work correctly for a known transfer syntax type.
