### ISSUE TITLE
Compile DICOM.Windows error

### ISSUE THREAD

**Issue by zhangfh** [fo-dicom/fo-dicom#230]
I use DICOM.Full to compile program for uwp, and DICOM.Windows cannot be compiled success, it prompt:
The type or namespace name 'IJpegNativeCodec' could not be found. 
I know IJpegNativeCodec is defined in DICOM.Native.windows, and it had been compiled, so how to solve this problem? 
Thanks

**Comment by zhangfh** [comment]
maybe development branch has this problem

**Comment by anders9ustafsson** [comment]
You need VS 2015. Have you performed "nuget restore" before trying to build?
