### ISSUE TITLE
Consider adding overloads of async methods that accept CancellationToken

### ISSUE THREAD

**Issue by IanYates** [fo-dicom/fo-dicom#236]
Whilst playing with the async DicomClient tests it occurred to me that we should consider having certain (all?) async methods accept `CancellationToken`s.
If we want to maintain backwards compatibility then we could create overloads

So `SendAsync(int x)` gets an overload `SendAsync(int x, CancellationToken ct)` and the former just calls the latter with `CancellationToken.None`.

It's not a super simple change though since, like async, we need the ability to meaningfully cancel to flow through the inner workings of the code.  I think it might be worth considering after other bits of the codebase settle for a few weeks.

**Comment by anders9ustafsson** [comment]
Very good idea, Ian! And implementing overloads makes perfect sense, I think.

**Comment by Ed55** [comment]
I fully agree.
As you mentioned Ian, it should be "meaningful". C-Move operations should call C-Move-Cancel, C-Find should call C-Find-Cancel ...
I agree as well to wait a bit with 2.1 ...

**Comment by IanYates** [comment]
That's taking the meaningful further than I had thought, but is a great idea! :)    :+1: 
My meaningful was to ensure we actually closed out of threads, etc properly since there's some hairy code around that at the moment.

Let's use this issue as a brain storming area to spec it out and then we can start on a PR.

**Comment by Ed55** [comment]
Yes, sorry :-D.
I have had a brief look into the code (after the idea).. quite some work.
There is just a `DicomCommandField.CCancelRequest` definition but just one reference to it: the local `ToString(...)` overload ...

But I think it is more worth to implement this than a C-GET as asked for in another thread.
(I am already using this issue thread for brain storming.)

But of course your "meaningful" scope is important first.

**Comment by Ed55** [comment]
just brain storming:
I miss an opportunity to set a time out for responses. (I implemented this in my 1.x derivate).
I experienced quite a lot of real world SCP implementations being able to not respond but hold the line.

An assoc response time out (`WaitForAssociation`) is present.
An assoc release reponse time out (`ReleaseAsync`) is present, but how to get into it when calling Client.SendAsync()   (may I miss something?).

As time outs are a kind of "cancellation" I add my thoughts here ...

**Comment by IanYates** [comment]
Thanks @Ed55 - it's these sorts of things we need to think about early in the piece so we can do one update - maybe a v2.5 or a v3 if it's breaking back-compat - rather than evolve it slowly and make it hard for people to upgrade to each new release.

I'm hoping to look at this later tonight once I knock over some work stuff.

**Comment by Ed55** [comment]
I agree. 
I thought of a new abstaction layer introducing a CFindClient, CStoreClient etc to try not to break things.
Those clients could make it more easy and readable to e.g. react differently to a CancellationToken ...
But may this is not neccessary.

I have some more needs and thoughts. Just taking the chance to place it somewhere for further discussions without opening an issue.

**Comment by Ed55** [comment]
@IanYates , @anders9ustafsson 
FYI: I am currently working on this issue and my timeout requirements as well.
Seems it will not break anything.
Some design constaints and details:

- Added time out properties to `DicomServiceOptions`, they are filled with defaults in the constructor.
- The `CancellationToken` is handover down to  `DicomService`. The constructor uses an overload, passing a `CancellationToken.None` as @IanYates suggested to the new constructor to not break things.
- I was struggling with the "time out pattern" as used by the current `WaitForAssociation` implementation to make the time out "retriggerable"; this needs to be done e.g. on each pending response to create a new DicomRequestResponseTimeout. So this (cancellation and timeout) is handled in a ServiceUserTimeoutCancelHandler class using a traditional timer. This implementation might be changed by somebody with more detailed TPL knowledge.
- As described in several high quality discussions there is no way to use a CancellationToken in networkStream.ReadAsync except to shut down the stream. But one would like to send a CancelRequest or an Abort ... So this is currently implemented as an additional timer checking the token for IsCancelRequested to take actions.

Comments?

**Comment by anders9ustafsson** [comment]
@Ed55 To me, this sounds terrific. @IanYates What do you think?

**Comment by IanYates** [comment]
Sorry for the radio silence this past week!  Big presentation in a couple of days :calendar: 

The ideas seem pretty sound to me.  Unfortunately anything we do is going to feel like an ugly hack, because sometimes that's just what's required - fo-dicom can at least hide the hack bits from the consumers of the library.

The key thing is that we ensure we clean up after ourselves regarding timers, etc

**Comment by Ed55** [comment]
@IanYates  thanks for your short note and good luck for your presentation. 
I am very sure nothing will be integrated without your review ...

I am with your feelings, but so far at least it is looking quite clean.
Except the way to cancel the `stream.ReadAsync()` as mentioned above.

Current status: The client part is ready, implementing the server (provider) part ...

**Comment by IanYates** [comment]
@Ed55 - glad to hear it.  I suspect my "review" will be like a walk in the park :D  Looking forward to what you come up with.

**Comment by Ed55** [comment]
@IanYates, @anders9ustafsson,
Taking this thread as discussion forum:
My primary motivation is to get my specs to work using the library, but I try to implement missing functionallity into the library if it can be done without breaking changes:

While creating test projects using the upcoming cancel / timeout implementation (expected to be ready within the next two weeks) I stumbled over two other issues:

1. The `DicomService` starts `ReadAndProcessPDUs()` in the constructor. My derived (provider) class is not even ready with its initialization while the base class already handles requests ...
2. A client is somehow worse, a `DicomServiceUser` implementation is captured as private in a client class. I would like a client to be a  `DicomServiceUser` and not to use a `DicomServiceUser` ...
BTW: this class starts communication in the constructor as well ...

Any arguments to not open that door?

**Comment by Ed55** [comment]
@IanYates, @anders9ustafsson ,
due to heavy (unexpected) work overload I could not finalize this part yet, please be patient for another week ...

**Comment by IanYates** [comment]
@Ed55 - don't worry.  I'm very much in the same boat.

**Comment by amoerie** [comment]
The new DicomClient fully supports CancellationToken with two different cancellation modes, but this logic has not been propagated to DicomService (yet).

Timeouts is also a different matter entirely, as you need to
- keep track of timestamps for each request
- be able to time out a request that is being sent by detecting if PDU packets are still being sent. You don't want one generic timeout for the entire request, C-Store Requests for files larger than 1 GB can take some time.
- be able to time out a request that is sent but hasn't seen any (pending) responses for a while. But when we do receive a pending response, we probably want to postpone the timeout.
