### ISSUE TITLE
Dicom.Platform.rd.xml file should be included as Embedded Resource

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#237]
According to [this](http://www.bartlannoeye.com/blog/creating-nuget-packages-for-your-windows-10-uwp-libraries) blog post, the *Dicom.Platform.rd.xml* file in the *Dicom.Windows* project should be included as an *Embedded Resource* rather than *Content*.

This change will also have an impact on the *NuGet* package creation for *Dicom.Platform* on the *Universal Windows Platform*, UWP.

**Comment by IanYates** [comment]
:+1: - good find!
I haven't done any Win 10 UWP development - was this an issue you ran into?

**Comment by anders9ustafsson** [comment]
@IanYates Yes, I had considerable problems configuring the NuGet package to ensure that the .rd.xml file was available for all architectures. The proposed solution should make UWP package management easier, at least in this respect.
