### ISSUE TITLE
Handle leak when doing DicomClient.Send of CStoreRequests

### ISSUE THREAD

**Issue by aerik** [fo-dicom/fo-dicom#238]
In both (my hacked up and hybrid version of)1.1 and pure 2.0.2 I have run the following code: 

```
class Program
    {
        static void Main(string[] args)
        {
            string folder = @"C:\temp\Dicom\";
            string host = "mypacsserver";
            int port = 104;
            string calledAE = "mypacsae";
            string senderAE = "TESTCLIENT";
            int i = 0;
            for (int j = 0; j < 100; j++)
            {
                foreach (string file in Directory.EnumerateFiles(folder, "*.dcm", SearchOption.AllDirectories))
                {
                    Console.WriteLine("File " + i.ToString() + " " + file);
                    DoSyncCStore(host, port, calledAE, senderAE, file);
                    i++;
                }
            }
            Console.WriteLine("DONE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
            Console.ReadKey();
        }

        private static void DoSyncCStore(string host, int port, string calledAE, string senderAE, string file)
        {
            DicomClient client = new DicomClient();
            DicomCStoreRequest request = new DicomCStoreRequest(file);
            client.AddRequest(request);
            client.Send(host, port, false, senderAE, calledAE);
        }
    }
```

And I see the number of handles in Task Manager creep up steadily.  The memory goes up and down, so the garbage collector is kicking in.  The increase in handles is not 1:1 with the number of files sent, it is smaller, so that's no help.  I let it run all weekend in my hybrid 1.1 version and got  40,000+ handles.  I'm sorry I didn't keep track of how many CStore operations that was, but I am currently running the 2.0.2 (straight out of NuGet) version and it has 1700 handles for 7500 CStore operations.

I can open the files using DicomFile.Open and read the MediaStorageSOPInstance without the handle leak, so I know it's not just opening the files in a loop.  If I only send CEchoRequests, the number of handles seems to stay pretty steady (5,000 echos results in 315 handles and seems to fluctuate but stay right around that figure), so it looks to be related to doing CStoreRequests.

Looking at the process with WinDbg, it looks like they are Thread handles.

Type           	Count
None           	4
Event          	119
Section        	12
File           	19
Directory      	3
Mutant         	5
WindowStation  	2
Semaphore      	4
Key            	19
Thread         	1058
Desktop        	1
IoCompletion   	3
Timer          	1
TpWorkerFactory	2
ALPC Port      	4
WaitCompletionPacket	6

But I haven't been able to configure WinDbg to get more information than that (I looked at several articles that talk about loading extensions to dig deeper, but I have not been successful in doing so).

This is built in VS 2012 Ultimate targetting .net 4.5, running on a Win 8.1 machine.

**Comment by aerik** [comment]
Something interesting but inconclusive:  Calling
```
GC.Collect(GC.MaxGeneration, GCCollectionMode.Forced);
GC.WaitForPendingFinalizers();
```

after every iteration cuts the leak  way down (half, maybe better).  Only calling it after every 100th iteration doesn't seem to have much effect.

**Comment by anders9ustafsson** [comment]
@aerik Superb stress testing! Many thanks for identifying and thoroughly reporting this issue. It will serve as a great input for refactoring the networking functionality. Will investigate your findings in more detail as soon as possible and will most probably get back to you with follow-up questions.

**Comment by Ed55** [comment]
I am currently trying to implement "ETW" logging in 2.0.2
As this can include TPL and CLR logs may I can discover something.
Not yet there ...

**Comment by IanYates** [comment]
Brilliant find.  I'll set aside some time to play with this on the weekend

**Comment by Ed55** [comment]
FYI:
I run 10.000 MWL query operations without obvious issues.
(In opposite to CEchoRequests (see @aerik  comments) they do have a Dataset as welll.)

It seems very likely that (as @aerik assumed) this is related to CStoreRequests only.

**Comment by Ed55** [comment]
FYI:
I just run 10.000 C-Store operations without obvious leaks.

I run it with my patch as outlined here #239 (for my understanding the issue could lead to a leak in either reject or abort scenarios),  on a 8.1 machine having .Net 4.6.1 installed.
Always storing the same file as well ...

**Comment by aerik** [comment]
Hmm, When I ran it, I ran it on a lot of pretty random dicom files.  Looking at @Ed55 's input, it seems it may have to do with what file is sent.  Or it could be environmental (my machine).  Has anyone else replicated the bug?  I'll try it on another machine, and also try it with various specific files.  @Ed55 , what kind of file did you use?  Small, big?  what Transfersyntax?

**Comment by Ed55** [comment]
@aerik By accident this was a Multi-frame Grayscale Byte Secondary Capture Image Storage [1.2.840.10008.5.1.4.1.1.7.2], ELE Transfesyntax, 75k.
I compiled the test app as well as the DICOM.Dektop library part against 4.6.1

Note: I have detected a new issue in my OLD (hacked up and hybrid 1.x version ;-) ) SCP having a rare race condition leading to an AssociationReject what brought me up to #239.
If this happens in your server as well you probably wan't notice this in the new client. But this leads to my understanding to unreleased  handles because FinalizeSend() seems not to be called.
Just thoughts ...

Do you perform any Tansfersyntax changes during your tests?

I am currently working on different contexts, but I may crosscheck suspicious stuff ...

**Comment by aerik** [comment]
@Ed55 Try it with a bigger file.  I tried a 100k file and got no appreciable leak.  I ran a 20MB file and the leak is noticeable in only a hundred iterations.

Also, I noticed that merely decoding the transfer syntax (my source file was Jpeg Process 1) results in a leak.  I saved the same file as Explicit VR Little Endian and used that for my new tests (so no transfer syntax change is necessary as part of the CSTORE process) and I still get a noticeable leak in only a hundred iterations.

**Comment by Ed55** [comment]
@aerik I just run 1.000 C-Store operations with a 18.5 MB file without noticeable issues.
I will definately perform a long running "mixed" C-STORE test as well, but probably not within the next two weeks. But short checks I can run.
May @IanYates can find something ...

**Comment by aerik** [comment]
I finally ran it on two other machines and don't see the leak, so it's looking like it's just my laptop, as it's very repeatable there.

Kind of embarrassing /  discouraging to think about.

**Comment by anders9ustafsson** [comment]
@aerik If I interpret the latest comments  correctly, this is not a general issue for *fo-dicom*, right? Unless you have made other findings, maybe you can close this issue for now?

**Comment by anders9ustafsson** [comment]
I'm closing this issue now due to the turn this discussion has taken over the later comments. Please re-open if anyone thinks I closed too soon.

**Comment by vzdesic** [comment]
I am uploading 70 files, each 500KB, periodically from my ASP.NET Core 2.2 API. After each upload there is 40 MB more allocated and visible in the Process Memory graph of the Visual Studio. I assigned null value to all possible objects after I don't use them anymore. Also, If I create Memory Snapshot, I see following memory print for most demanding memory allocation:

MemoryStream    <0x2512742D2E8>
 Dicom.IO.Buffer.StreamByteBuffer    <0x251274336E8>
  Dicom.DicomOtherWord    <0x25127433710>
   SortedSet+Node<KeyValuePair<Dicom.DicomTag, Dicom.DicomItem>>    <0x25127433730>
    SortedSet+Node<KeyValuePair<Dicom.DicomTag, Dicom.DicomItem>>    <0x251274336B0> 
     SortedSet+Node<KeyValuePair<Dicom.DicomTag, Dicom.DicomItem>>    <0x25127433530> 
      SortedSet+Node<KeyValuePair<Dicom.DicomTag, Dicom.DicomItem>>    <0x251274333A0> 
       SortedSet+Node<KeyValuePair<Dicom.DicomTag, Dicom.DicomItem>>    <0x25127433228> 
        SortedSet+Node<KeyValuePair<Dicom.DicomTag, Dicom.DicomItem>>    <0x25127432ED0> 
         SortedSet+Node<KeyValuePair<Dicom.DicomTag, Dicom.DicomItem>>    <0x25127430D20> 
	  SortedSet+Node<KeyValuePair<Dicom.DicomTag, Dicom.DicomItem>>    <0x25127430478> 
	   SortedSet+Node<KeyValuePair<Dicom.DicomTag, Dicom.DicomItem>>    <0x2512742F9F8> 
	    TreeSet<KeyValuePair<Dicom.DicomTag, Dicom.DicomItem>>    <0x2512742D810> 
	     SortedDictionary<Dicom.DicomTag, Dicom.DicomItem>    <0x2512742D7D0> 
	      Dicom.DicomDataset    <0x2512742D428> 
	       Dicom.DicomFile    <0x2512742D330> 
		Dicom.Network.DicomCStoreRequest    <0x251274349E0> 
		 ConcurrentQueue+Segment<Dicom.Network.DicomRequest>    <0x251272B6A88> 
		  ConcurrentQueue<Dicom.Network.DicomRequest>    <0x25127228C88> 
		   Dicom.Network.DicomClient    <0x29F80949F88>  
		    AsyncTaskMethodBuilder+AsyncStateMachineBox<VoidTaskResult, Dicom.Network.DicomClient+<SendQueuedRequestsAsync>d__68>    <0x251274E8818> 
		     Action    <0x251274E88A8> 
		      AsyncMethodBuilderCore+ContinuationWrapper    <0x251274E88E8> 
			Action    <0x251274E8910> 
			 Task<Object>    <0x2512749A498> 
			  Dictionary<Int32, Task>    <0x251268EFED8> [Static variable Task.s_currentActiveTasks]
			  TaskCompletionSource<Object>    <0x2512749A480> 
			   Dicom.Network.AsyncManualResetEvent    <0x25127228CC8> 
			    Dicom.Network.DicomClient    <0x29F80949F88> [Cycle Detected]
			  AsyncMethodBuilderCore+ContinuationWrapper    <0x251274E88E8> [Cycle Detected]
			  AsyncTaskMethodBuilder+AsyncStateMachineBox<VoidTaskResult, Dicom.Network.DicomClient+<SendQueuedRequestsAsync>d__68>    <0x251274E8818> [Cycle Detected]
			AsyncTaskMethodBuilder+AsyncStateMachineBox<VoidTaskResult, Dicom.Network.DicomClient+<SendQueuedRequestsAsync>d__68>    <0x251274E8818> [Cycle Detected]
	      SortedDictionary+ValueCollection<Dicom.DicomTag, Dicom.DicomItem>    <0x2512742D860> 
	       SortedDictionary<Dicom.DicomTag, Dicom.DicomItem>    <0x2512742D7D0> [Cycle Detected]

You can see that for few of this location was detected memory cycle. All mentioned class are actually Dicom classes. Any idea? It seems that this issue is maybe similar to the problem mentioned originally in this post.
