### ISSUE TITLE
DicomClient.Send DicomAssociationRejectedException not working

### ISSUE THREAD

**Issue by Ed55** [fo-dicom/fo-dicom#239]
Sorry, did not found a nice title ...

Running the code

            DicomClient client = new DicomClient();
            DicomCEchoRequest echoRequest = new DicomCEchoRequest();
            client.AddRequest(echoRequest);
            try
            {
                client.Send("127.0.0.1", 3000, false, "Me", "You");
            }
            catch (Exception ex)
            {
                Logger ...
            }
does not hit the Logger when the association is rejected, I expected a `DicomAssociationRejectedException`.

I am no expert in best "awaiting" patterns, but it seems the issue is caused basically by 

            public void OnReceiveAssociationReject(
                DicomRejectResult result,
                DicomRejectSource source,
                DicomRejectReason reason)
            {
                this.SetComplete();
                throw new DicomAssociationRejectedException(result, source, reason);
            }

I see the exception is thrown, but my above code is done already!

I think the SetComplete() should be changed to something like

            private void SetComplete(Exception ex = null)
            {
                if (this.client.completeNotifier != null)
                {
                    if (ex == null)
                    {
                        this.client.completeNotifier.TrySetResult(true);
                    }
                    else
                    {
                        this.client.completeNotifier.TrySetException(ex);
                    }
                }
            }

and the `OnReceiveAssociationReject` should just call `this.SetComplete(new DicomAssociationRejectedException(result, source, reason));`. The `OnReceiveAbort` should act accordingly.
At least now I am receiving an exception in my upper "high level" code, but it is an `AggregateException`. To make the behaviour the same no matter if you are using `client.Send(..)` or `await client.SendAsync(..)`.
I propose to change the synchron `Send(..)` implementations to something like:

            try
            {
                this.InitializeSend(this.networkStream, assoc);
                this.completeNotifier.Task.Wait();
            }
            catch (AggregateException ex)
            {
                throw ex.InnerException;
            }
            finally
            {
                this.FinalizeSend();
            }

But again, I am no expert in TPL.
And I need to investigate in "Forks" and "Pull requests" ...

**Comment by anders9ustafsson** [comment]
@Ed55 Thanks for an extensive report, as always. We'll get into this very soon.

**Comment by IanYates** [comment]
Makes sense.  Similar to the common pattern in async code where you do some init work that's sync and then delegate to another method that's actually async.  It means we can throw a synchronous exception if required, etc.

I'll look at this on the weekend too :)
