### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by IanYates** [fo-dicom/fo-dicom#24]
Are we happy to start putting documentation into the GitHub wiki?  It seems to be the canonical place for it.  Any particular preference for structure or can we just let it grow organically?

I'd like to see a section for "successful integrations" where we can talk about the various bits of equipment with which we've interfaced and any issues that arose.

Another section for fo-DICOM developers to explain the source would be good (as suggested by @anders9ustafsson in #19 around the changes proposed for logging).

Finally, a section for end-users would be good too.  It could include a quick "getting started".  I know for me, getting started with DICOM was initially intimidating but getting some quick wins where I could grab a dicom file from a machine, extract its images and the patient's name made me realise this wasn't too hard after all :)

Any other thoughts before we start fleshing out the wiki?

**Comment by anders9ustafsson** [comment]
Good suggestions, @IanYates. The proposed sections make perfect sense, I think.

**Comment by anders9ustafsson** [comment]
Wiki established [here](https://github.com/fo-dicom/fo-dicom/wiki), issue resolved.
