### ISSUE TITLE
Pass through unsupported user data during PDU parsing.

### ISSUE THREAD

**Issue by zcr01** [fo-dicom/fo-dicom#242]
For example, AAssociateRQ and AAssociateAC currently just skip any unsupported User Data, leaving it inaccessible to implementers of IDicomServiceProvider.  Instead, it would be nice to either pass the raw data through in the DicomAssociation, or to provide a way to register custom parsers for unsupported/unimplemented data, so that developers can get access to it without needing to modify core code.

**Comment by deyung** [comment]
@zcr01 were you thinking about something in the ListenAndProcessPDUAsync method that would write invalid PDUs to a stream that is accessible by the implementers?

**Comment by zcr01** [comment]
@deyung It's been awhile, so bear with me as I try to remember what I was thinking...  If you look at AAssociateRQ.Read() in Dicom/Network/PDU.cs, you can see where when parsing user information (type == 50) it just skips anything where the user-item type is unknown.  The implementer of IDicomServiceProvider then gets in the OnReceiveAssociationRequest() callback a DicomAssociation object where unparseable/unknown user data is missing entirely.  I think what I was suggesting was that  either: 
 1) this DicomAssociation object just contains a collection of unknown user data objects (type + raw bytes) that it can than optionally be handled and parsed in OnReceiveAssociationRequest().  This I think is similar to what you are suggesting, but I'm not sure there's a need for a separate stream.

or 
  2) through either static callback registration or passing in callbacks to the DicomServer, have AAssociateRQ.Read() callback to the implementer to handle parsing in this case instead of just tossing it on the floor.

That being said, this is all probably low hanging fruit...it may be more worthwhile just to implement the remaining user data sub items directly.  (see http://dicom.nema.org/dicom/2013/output/chtml/part08/sect_9.3.html#sect_9.3.2.3 and http://dicom.nema.org/dicom/2013/output/chtml/part07/sect_D.3.html#sect_D.3.3.6.1 - item types 57, 58, 59)

**Comment by anders9ustafsson** [comment]
@zcr01 Could you please review PR #443 and give you opinion as to whether it meets the requirements in this request.
