### ISSUE TITLE
DicomDirectoryRecord reads ReferencedFileID wrong

### ISSUE THREAD

**Issue by Ravenheart** [fo-dicom/fo-dicom#254]
When reading a DICOMDIR file and iterating over the patients.studies/series/images at the last level (image) the DicomDirectoryRecord reads the ReferencedFileID wrong.

```csharp
//ReferencedFileID = "IMAGES\IM0"
DicomDirectoryRecord sampleImageLevel = GetImageLevelFromSampleDICOMDIR();

string fileName = sampleImageLevel.Get<string>(DicomTag.ReferencedFileID);
```
### Expected behavior
```csharp
fileName == "IMAGES\IM0";
```
### Actual behavior
```csharp
fileName == "IMAGES";
```
### Steps to reproduce the behavior
Run the sample project with the attached DICOMDIR.zip (extract the file)
https://github.com/rcd/fo-dicom/tree/master/Examples/DICOM%20Media

[DICOMDIR.zip](https://github.com/fo-dicom/fo-dicom/files/220845/DICOMDIR.zip)

### fo-dicom version and OS/platform
2.0.2.0 Windows 10 Enterprise x64

**Comment by anders9ustafsson** [comment]
This is not a bug. *Referenced File ID* is a multi-value string element, and the values are separated with a backslash (\).

This means that the *Referenced File ID* in this case consists of two values, but you are only accessing the first; the `Get<T>` overload you are using has an optional `index` argument with default value 0, so you are explicitly requesting `DicomDataset.Get<string>(DicomTag.ReferencedFileID, index: 0)` which returns the first value of the element.

You could (should) use `DicomDataset.Get<string[]>(DicomTag.ReferencedFileID)` which gives you the full array of values.

If you then want a resulting file ID, you could join the individual elements e.g. using `Path.Combine(values)` or `string.Join(@"\", values)`.

Using `Get<byte[]>` gives you extra work having to encode the bytes into a string, so I strongly recommend using `Get<string[]>`.
