### ISSUE TITLE
NLog Formatted Logging Failing

### ISSUE THREAD

**Issue by kb1234** [fo-dicom/fo-dicom#258]
I switched from the ConsoleLogManager to the NLogManager.  In doing so the formatted log message appear to not be functioning.  Below is example output from a C-ECHO request that terminated prematurely.

Example output from the ConsoleLogManager:
IO exception while reading PDU: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ...
Connection closed with error: System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ...

Example output from the NLogManager:
2016-04-18 10:06:08.5300|ERROR|Dicom.Network|IO exception while reading PDU: {0}
2016-04-18 10:06:08.5300|ERROR|Dicom.Network|Connection closed with error: {0}

This is occurring in fo-dicom 2.0.2 from nuget.  System is Windows 8.1 running VS 2013 Pro.

**Comment by anders9ustafsson** [comment]
Well spotted, @kb1234 ! Have located the error and will fix it ASAP.
