### ISSUE TITLE
DicomFileMetaInformation overly intrusive?

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#265]
Just want to raise the question for discussion, whether the current `DicomFileMetaInformation` initialization is desired?

Regardless of whether a loaded DICOM file contains meta information or not, `DicomFileMetaInformation` is initialized. 

The [`DicomDataset` constructor](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/DicomFileMetaInformation.cs#L21) is automatically applying *SOP Class UID*, *SOP Instance UID* and *Internal Transfer Syntax* as the *Media Storage* properties of the `DicomFileMetaInformation` object.

The [default constructor](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/DicomFileMetaInformation.cs#L10) (which is also invoked by the `DicomDataset` constructor) sets remaining properties such as *Implementation Version Name* and *Source Application Entity Title*.

This practically means that,

1. regardless of whether meta information is available or not in the DICOM file, meta information is created already at file load, 
2. any data contained in existing meta information is replaced upon `DicomFileMetaInformation` construction, and 
3. The `DicomDataset` constructor does not check whether e.g. *Media Storage SOP Class UID* is set, it only checks for *SOP Class UID* etc.

It makes sense to (add and) update meta information when saving a DICOM file, but should meta information really be modified already at file loading? 

Please discuss!

**Comment by hiscodeness** [comment]
Simply going by the 'principle of least surprise', I'd vote against modifying information loaded from a file. Or at the very least, one should have a warning about this behavior where it may impact the user (in the API methods for loading files?).

**Comment by kb1234** [comment]
My naive vote (I haven't used fo-dicom enough to fully understand the implications) would be to not modify until save.  This way in the off-chance that the Source AE is of relevance it can easily be used.  I'm not sure what situations it would be relevant, perhaps in some routing or clinical trial scenarios.

I would also like to see, and maybe this is already supported, developers able to change the default image class UID and version name.

**Comment by anders9ustafsson** [comment]
[Gitter comment](https://gitter.im/fo-dicom/fo-dicom?at=571e35a7f5b6334a5e70b343) from user @raise:

> my opinion: If reading dicom files from media, it should always be Part 10 compliant and therefore always have correct MetaInformation. So I would not overwrite if file meta Information is available!

**Comment by anders9ustafsson** [comment]
My interpretation of your comments is that the loaded information should be left untouched. Only at save the relevant elements should be updated.

Thus, we need to modify the current behavior; therefore I have labeled this issue a *bug*.
