### ISSUE TITLE
Wrong description for some tags

### ISSUE THREAD

**Issue by werwolfby** [fo-dicom/fo-dicom#266]
### Expected behavior
Tag (0018, 8151) XRayTubeCurrentInuA has wrong description: **X-Ray Tube Current in A**
It lack of **µ** symbol.

### Actual behavior
Tag (0018, 8151) XRayTubeCurrentInuA have to have next description: **X-Ray Tube Current in µA**

### Steps to reproduce the behavior
Try to read tag (0018, 8151) description

### fo-dicom version and OS/platform
Starting from 2.0
All platforms, the issue exist inside **DICOM Dictionary.xml**

**Comment by anders9ustafsson** [comment]
Many thanks for reporting, @werwolfby ! It is a conscientious decision to exclude non-US alphanumeric characters from the description, but I will investigate if it would be possible to sufficiently include e.g. *&mu;* in the description string.

**Comment by werwolfby** [comment]
I've already submit you a pull request thank you.
