### ISSUE TITLE
DumpWalker

### ISSUE THREAD

**Issue by matimont** [fo-dicom/fo-dicom#274]
Something changed in this new version that I can't display tags anymore..

### Expected behavior
    private class DumpWalker : IDicomDatasetWalker
        {
            int _level = 0;

            public DumpWalker(MostrarTags form)
            {
                Form = form;
                Level = 0;
            }

            public MostrarTags Form
            {
                get;
                set;
            }

            public int Level
            {
                get { return _level; }
                set
                {
                    _level = value;
                    Indent = String.Empty;
                    for (int i = 0; i < _level; i++)
                        Indent += "    ";
                }
            }

### Actual behavior
Error	2	'MostrarTags.DumpWalker' does not implement interface member 'Dicom.IDicomDatasetWalker.OnElementAsync(Dicom.DicomElement)'

### fo-dicom version and OS/platform
2.0.2.0

**Comment by anders9ustafsson** [comment]
@matimont If I am not entirely mistaken, you compare with version 1.x, right? In 2.0, the `IDicomDatasetWalker` was extended with an asynchronous equivalent of `OnElement`, namely `OnElementAsync`. 

So you need to implement this new method in your `DumpWalker` class for your code to compile. Unless you plan to take any special measures, you can normally implement this method by invoking `OnElement` like this:

    public Task<bool> OnElementAsync(DicomElement element)
    {
      return Task.FromResult(OnElement(element));
    }

Please also note that `OnFragmentItemAsync` has been added to the interface in the same way. You can apply the same implementation principle for this method.

**Comment by matimont** [comment]
Hi Anders, yes, I was using the 1.x version and downloaded the new one and this functionality is no longer working for me.

The error I get it in this line:
private class DumpWalker : IDicomDatasetWalker

So, where in the code I need to add what you suggested?

**Comment by anders9ustafsson** [comment]
@matimont In your `DumpWalker` class. Right now it doesn't compile because you have not implemented the whole `IDicomDatasetWalker` interface. Implement the missing methods and your code will build.

**Comment by matimont** [comment]
Ok, solved it.. See below:

Question... Can I put the code I had in the OnElement function I had in the async method? I tried but seems not to work, I don't get any tag..

    public bool OnElement(DicomElement element)
            {
                var tag = String.Format("{0}{1}  {2}", Indent, element.Tag.ToString().ToUpper(), element.Tag.DictionaryEntry.Name);

                string value = "<large value not displayed>";
                if (element.Length <= 2048)
                    value = String.Join("\\", element.Get<string[]>());

                if (element.ValueRepresentation == DicomVR.UI && element.Count > 0)
                {
                    var uid = element.Get<DicomUID>(0);
                    var name = uid.Name;
                    if (name != "Unknown")
                        value = String.Format("{0} ({1})", value, name);
                }

                Form.AddItem(tag,
                    element.ValueRepresentation.Code,
                    element.Length.ToString(),
                    value);
                return true;
            }

            public Task<bool> OnElementAsync(DicomElement element)
            {
                return Task.FromResult(OnElement(element));
            }

**Comment by anders9ustafsson** [comment]
@matimont In principle you can copy the code from `OnElement` directly into `OnElementAsync`, but please observe that the return type is `Task<bool>` and not `bool`. 

So instead of

    return true; // as in OnElement

You should return:

    return Task.FromResult(true);
