### ISSUE TITLE
Unable to update to fo-dicom 2.1.0-beta1 from 2.0.2 via NuGet

### ISSUE THREAD

**Issue by BobSter3000** [fo-dicom/fo-dicom#275]
### Expected behavior
Run Update-Package fo-dicom -Pre

### Actual behavior
Should update

### Steps to reproduce the behavior
Update fails.  Message follows.
Attempting to gather dependency information for multiple packages with respect to project 'ImageServer', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for multiple packages.
Resolving actions install multiple packages
Removed package 'fo-dicom 2.0.2' from 'packages.config'
Successfully uninstalled 'fo-dicom 2.0.2' from ImageServer
Removed package 'fo-dicom.Platform 2.0.2' from 'packages.config'
Successfully uninstalled 'fo-dicom.Platform 2.0.2' from ImageServer
Removed package 'fo-dicom.Legacy 2.0.2' from 'packages.config'
Successfully uninstalled 'fo-dicom.Legacy 2.0.2' from ImageServer
Removed package 'fo-dicom.Core 2.0.2' from 'packages.config'
Successfully uninstalled 'fo-dicom.Core 2.0.2' from ImageServer
  GET https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Packages(Id='fo-dicom.Core',Version='2.1.0-beta1')
  OK https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Packages(Id='fo-dicom.Core',Version='2.1.0-beta1') 216ms
Adding package 'fo-dicom.Core.2.1.0-beta1' to folder 'C:\Users\Bob\OneDrive\Documents\VisualStudio2015Projects\ImageServer\packages'
Added package 'fo-dicom.Core.2.1.0-beta1' to folder 'C:\Users\Bob\OneDrive\Documents\VisualStudio2015Projects\ImageServer\packages'
Added package 'fo-dicom.Core.2.1.0-beta1' to 'packages.config'
Successfully installed 'fo-dicom.Core 2.1.0-beta1' to ImageServer
  GET https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Packages(Id='fo-dicom.Android',Version='2.1.0-beta1')
  OK https://www.nuget.org/api/v2/curated-feeds/microsoftdotnet/Packages(Id='fo-dicom.Android',Version='2.1.0-beta1') 310ms
Install failed. Rolling back...
Package 'fo-dicom.Android 2.1.0-beta1' does not exist in project 'ImageServer'
Removed package 'fo-dicom.Core 2.1.0-beta1' from 'packages.config'
Package 'fo-dicom.Core 2.0.2' already exists in folder 'C:\Users\Bob\OneDrive\Documents\VisualStudio2015Projects\ImageServer\packages'
Added package 'fo-dicom.Core 2.0.2' to 'packages.config'
Package 'fo-dicom.Legacy 2.0.2' already exists in folder 'C:\Users\Bob\OneDrive\Documents\VisualStudio2015Projects\ImageServer\packages'
Added package 'fo-dicom.Legacy 2.0.2' to 'packages.config'
Package 'fo-dicom.Platform 2.0.2' already exists in folder 'C:\Users\Bob\OneDrive\Documents\VisualStudio2015Projects\ImageServer\packages'
Added package 'fo-dicom.Platform 2.0.2' to 'packages.config'
Adding package 'fo-dicom 2.0.2', which only has dependencies, to project 'ImageServer'.
Package 'fo-dicom 2.0.2' already exists in folder 'C:\Users\Bob\OneDrive\Documents\VisualStudio2015Projects\ImageServer\packages'
Added package 'fo-dicom 2.0.2' to 'packages.config'
Package 'fo-dicom.Android 2.1.0-beta1' does not exist in folder 'C:\Users\Bob\OneDrive\Documents\VisualStudio2015Projects\ImageServer\packages'
Removing package 'fo-dicom.Core 2.1.0-beta1' from folder 'C:\Users\Bob\OneDrive\Documents\VisualStudio2015Projects\ImageServer\packages'
Removed package 'fo-dicom.Core 2.1.0-beta1' from folder 'C:\Users\Bob\OneDrive\Documents\VisualStudio2015Projects\ImageServer\packages'
Update-Package : Could not install package 'fo-dicom.Android 2.1.0-beta1'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but 
the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Update-Package fo-dicom -Pre
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
 2.1.0

### fo-dicom version and OS/platform
Using Visual Studio2015, Win10 64bit, Target .NET4.5.2 64bit

**Comment by anders9ustafsson** [comment]
OK, confirmed the failure. Will deal with this as soon as possible. For the time being, recommendation is to first uninstall version 2.0.2, and then install 2.1.0-beta1.
