### ISSUE TITLE
2.1.0-beta1, request.Dataset.Get<string>(DicomTag.PatientID) throws exception when value is empty

### ISSUE THREAD

**Issue by BobSter3000** [fo-dicom/fo-dicom#276]
### Expected behavior
Should return String.Empty

### Actual behavior
Exception Thrown
{"Element empty or index: 0 exceeds element count: 0"}

### Steps to reproduce the behavior
Parsing C-Find request dataset.

### fo-dicom version and OS/platform
2.1.0 beta

**Comment by anders9ustafsson** [comment]
@BobSter3000 For improved handling of mandatory and non-mandatory tags we recently modified the behavior of the `DicomDataset.Get<T>` overloads, please see #226.

`DicomDataset.Get<T>(DicomTag)` is actually the same as typing `DicomDataset.Get<T>(DicomTag, index: 0)`, where the array `index` is an optional parameter with default value `0`. This method overload throws if the requested `DicomTag` is not present in the dataset. 

To apply a default value, you explicitly have to specify the default value using the `DicomDataset.Get<T>(DicomTag, T defaultValue)` overload instead.
