### ISSUE TITLE
ChangeTransferSyntax throws an exception (J2k 16-bit --> Jpeg Lossy P 4)

### ISSUE THREAD

**Issue by Zaid-Safadi** [fo-dicom/fo-dicom#277]
### Use case 
Using DICOM Dump to change transfer syntax for Jpeg2000 16-bit allocated/12-bit-stored DICOM image to Jpeg lossy process 4 throws an exception

### Expected behavior
ChangeTransferSyntax method returns a new DicomDataset with image information encoded in jpeg lossy process 4

### Actual behavior
The ChangeTransferSyntax throws the following exception:
System.InvalidCastException: Unable to cast object of type 'Dicom.Imaging.Codec.DicomJpegParams' to type 'Dicom.Imaging.Codec.DicomJpeg2000Params'.
   at Dicom.Imaging.Codec.DicomJpeg2000NativeCodec.Decode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters) in c:\users\user\source\repos\fo-dicom\dicom.native\dicom.imaging.codec.jpeg2000.cpp:line 246

### Steps to reproduce the behavior
Compile and Run "Dicom Dump", 
Open a J2K 16/12 bit image ( attached)
Tools->Change Syntax -> Jpeg Lossy P1 & P4 -> Quality 100
### fo-dicom version and OS/platform
Windows/Desktop

### Troubleshooting
File DicomCodecExtensions.cs: ChangeTransgerSyntax method is passing the output coded parameter to the DicomTranscoder as both the input and output codec parameters:
            var transcoder = new DicomTranscoder(file.FileMetaInfo.TransferSyntax, syntax, **parameters**, **parameters**);

[IM-0001-0001.zip](https://github.com/fo-dicom/fo-dicom/files/249783/IM-0001-0001.zip)

**Comment by anders9ustafsson** [comment]
@Zaid-Safadi Many thanks for detecting this issue and also perform the troubleshooting. From your findings it is obvious that `parameters` should only apply to the output syntax. I will correct accordingly.

**Comment by Zaid-Safadi** [comment]
Thank you!
