### ISSUE TITLE
Support appending new values to elements with VM > 1

### ISSUE THREAD

**Issue by Zaid-Safadi** [fo-dicom/fo-dicom#278]
### Use case

Currently there doesn't seem to be a way to append a new value to an existing Element with value multiplicity > 1
### Expected behavior

Add "DicomElement.Set<T> (T value, int index)" methods similar to the "Get<T>" methods

**Comment by mrbean-bremen** [comment]
Closing as won't fix - see #1238 for a reasoning. Basically, the added convenience is not worth the needed change in the architecture (DicomItems are currently immutable).
