### ISSUE TITLE
Merge core and platform assemblies

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#280]
Currently, the main *fo-dicom* is splitted into a (relatively large) *Core* assembly, which is a Portable Class Library (PCL), and a number of "tiny" platform packages which implements platform-specific I/O, network, image rendering etc.

This split facilitates platform-agnostic development, but can under certain circumstances be inconvenient. For example, the split relies on "lazy assembly loading" which for example the *iOS* platform does not support.

It is therefore suggested that the PCL *Core* should be merged into the different platform assemblies, and by this creating *Core* assemblies for each respective platform instead.

By keeping the PCL *Core* and using the so-called [bait-and-switch PCL trick](http://log.paulbetts.org/the-bait-and-switch-pcl-trick/) it would still be possible to develop against the portable class library (the "bait") and in the end-application replace the PCL *Core* with the platform specific *Core* equivalent (the "switch").

In practice this would mean that instead of providing one PCL *Dicom.Core* assembly and multiple *Dicom.Platform* assemblies, we would provide *Dicom.Core* assemblies for PCL **and** each supported platform.

Comments, suggestions, ideas?

**Comment by IanYates** [comment]
Well if it's necessary for iOS then I suppose we have to do it.  Paul Betts is certainly no dummy (he got me into RX, ReactiveUI, etc years ago).  From what reading I've just done on the topic it seems like this is a lot better in recent Xamarin versions, but if you're still running in to trouble then this seems like a good approach.  
Happy to proceed in this direction :smile:

**Comment by Zaid-Safadi** [comment]
Might be a little off topic but related, any thoughts about supporting .NET core? 
could this replace or simplify the design of current PCL projects?
 
It seems that version 1.0 will be released in the near future (end of June): https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/

I didn't personally work with .NET Core but from what I've read should be the successor to PCL.

**Comment by anders9ustafsson** [comment]
@Zaid-Safadi It's already on the table :-) See #256 .

I have made a few preliminary tests already, but right now I run into compatibility problems with the base class libraries from NuGet. I thought I'd wait a few more weeks so that at least .NET Core RC2 gets properly released before I make another try.

**Comment by Zaid-Safadi** [comment]
Beautiful! My bad didn't see the enhancement request there. 
Definitely makes since to wait until the official release is out, glad you guys are ahead with adopting these technologies
