### ISSUE TITLE
Pixel Data not null-padded to even length

### ISSUE THREAD

**Issue by Jarekw69** [fo-dicom/fo-dicom#284]
Sometimes it happens that I get images having odd pixel data length (not many -  recently some US and now some SC paperwork scans) . When sending such file with foDicom, the remote SCP aborts association at the last PDU fragment with message: **DIMSE Failure (aborting assoc): 0006:020d DIMSE: Odd Fragment Length / Data received too short**. The issue was reproduced with two different SCP vendors. Sending to foDicom-based SCP works ok.
I will attach anonymized example image as soon as I get one different than SC pt document scan.
Tested with foDicom v.2.0.2.0, Windows 10.

**Comment by anders9ustafsson** [comment]
@Jarekw69 Which transfer syntax are you using?

**Comment by Jarekw69** [comment]
[2016-05-10.zip](https://github.com/fo-dicom/fo-dicom/files/262855/2016-05-10.zip)
I am using LEE. I am also attaching log.

**Comment by anders9ustafsson** [comment]
Thanks, @Jarekw69 . OK, according to [this](http://dicom.nema.org/medical/dicom/current/output/chtml/part08/chapter_E.html) annex of the standard, it seems like *fo-dicom* is violating the requirement that every PDV fragment shall consist of an even number of bytes. We'll deal with it expediently.

**Comment by Jarekw69** [comment]
Thank you @anders9ustafsson .
