### ISSUE TITLE
Prepare NuGet specification files for 1.1.0 release

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#29]
In the 1.1.0 release, the *NLog* dependency has been removed from the *DICOM* assembly.

My personal view is that we should release three separate *NuGet* packages:

* fo-dicom
* fo-dicom.NLog
* fo-dicom.SeriLog

where *fo-dicom* has no dependencies, and the two latter packages have dependencies against *fo-dicom*  and their respective logging framework.

In the 1.0.x releases of *fo-dicom* the *Dump* and *Compare* applications have also been included. In the 1.1.0 release I would like to omit these applications, so that the *NuGet* package only contains the *DICOM.dll* and the native codec assemblies.

What are your views on this?

**Comment by IanYates** [comment]
Makes sense to me.
(following on from your Gitter comments) - before release we should fix the issues you pointed out in my earlier logging PR.  I won't be able to get back to that for a couple of days I'm afraid.

**Comment by anders9ustafsson** [comment]
@IanYates Just for my recollection, the remaining logging issue for this release appears to be:

* Removal of `Init` classes from logging assemblies

Anything else?

**Comment by IanYates** [comment]
Yeah that's pretty much it.  I was also going to cache the logging strings to avoid the repeated parsing of similar string templates since it will be a pretty finite cache (there are only so many log string templates in fo-dicom after all).  Neither are a big deal.

**Comment by anders9ustafsson** [comment]
I am still reluctant to the caching of logging strings, I think it adds (unnecessary) complexity to the library which will only perform more efficiently in some specific scenarios (e.g. logging inside large loops). But that's only my opinion, @hdesouky @GMZ , what do you think?

In the future, perhaps we could consider to implement the logging format strings as string resources in a separate resource assembly, where *Dicom.Serilog* invokes keyword-based format strings and *Dicom.NLog* and the console logger invokes index-based format strings? I don't think this is relevant for the 1.1.0 release, but maybe something to consider going forward. Or maybe such an approach is also overly complex?

**Comment by anders9ustafsson** [comment]
@IanYates I realized one more thing that needs to be addressed in the logging assemblies:

* Logging assemblies should use attributes from the *SharedAssemblyInfo.cs* file

in order to have a common labeling and version numbering of the assemblies. If you want me to I might be able to fix this and the `Init` removal issue.
