### ISSUE TITLE
Please discuss: should DicomService.SendNextMessage throw?

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#312]
I would like to have the community's opinion on the following issue.

In `DicomService.SendNextMessage`, there are two lines where, if conditions are met, the method does not send the next message but simply returns. A common side-effect of this is that the receiving end is waiting indefinitely (or at least until the timeout), and there is no notification of what is going wrong.

The two lines are as of now [839](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Network/DicomService.cs#L839) and [841](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Network/DicomService.cs#L841)

    if (_sending) return;

    if (Association.MaxAsyncOpsInvoked > 0 && _pending.Count >= Association.MaxAsyncOpsInvoked) return;

Should we continue silently returning under these conditions, or should we implement some kind of mitigation to aid the user and/or message receiver? If yes, what? Throw an exception? Wait until conditions are no longer met (is that even plausible)? 

Please share your thoughts on this one!

**Comment by Zaid-Safadi** [comment]
@anders9ustafsson I looked briefly at the code and it seems to be called async with nothing waiting for it to complete, not sure if a user can actually catch and handle the exception, what d do you think?

There might be two other options:
1. fire a callback with the reason of ignoring the message (e.g. sending, maxAsync...) and add logging, derived classes are at least informed
2. update the Implementation to always ensure messages are being processed and we are not returning silently  (e.g. consumer/producer pattern -AutoResetEvent, safe multi-threading with dedicated thread for processing the messages...)

**Comment by anders9ustafsson** [comment]
Thanks, @Zaid-Safadi ! Yes, there are a few `async void`:s in the code. When I refactored the networking code to use `async`/`await` instead of `Begin...`/`End...` constructs, I took a few shortcuts. It is of course highest priority to fix these first, and it should then be easier to sufficiently handle these invalid states.

**Comment by IanYates** [comment]
To avoid surprises, and assist with tracking down these sorts of things in production, we could include a warning log message at east?

**Comment by anders9ustafsson** [comment]
@IanYates Yes, I think that is the way to go right now. I am currently working to remove `async void` constructs, and will account for the issues listed above as part of this refactoring.
