### ISSUE TITLE
Appears Dicom.Desktop Beta3 Client Does Not send any verification PCID in Assoction Negotiation

### ISSUE THREAD

**Issue by BobSter3000** [fo-dicom/fo-dicom#316]
### Expected behavior Beta 2 Console Logging
DICOMSCP -> Association request:
Calling AE Title:       EchoCheck
Called AE Title:        DICOMSCP
Remote host:            192.168.2.124
Remote port:            104
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 2.9.9
Maximum PDU Length:     16384
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Explicit VR Little Endian
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
DICOMSCP <- Association accept:
Calling AE Title:       EchoCheck
Called AE Title:        DICOMSCP
Remote host:            192.168.2.124
Remote port:            104
Implementation Class:   Unknown [1.2.840.113845.1.1]
Implementation Version: Syn4,4,1,11
Maximum PDU Length:     65000
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Explicit VR Little Endian
DICOMSCP -> C-Echo request [1]
DICOMSCP <- C-Echo response [1]: Success
DICOMSCP -> Association release request
DICOMSCP <- Association release response

### Actual behavior  Beta 3 Console Logging.
DICOMSCP -> Association request:
Calling AE Title:       EchoCheck
Called AE Title:        DICOMSCP
Remote host:            192.168.2.124
Remote port:            104
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 2.9.9
Maximum PDU Length:     16384
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  0
Connection closed

### Steps to reproduce the behavior  Code Snippet.
            DicomClient client = new DicomClient();
            DicomCEchoRequest req = new DicomCEchoRequest();
            req.OnResponseReceived = (DicomCEchoRequest rq, DicomCEchoResponse rsp) => {
                if (rsp.Status == DicomStatus.Success) {
                    result = true;
                }
            };
            client.AddRequest(req);
            try {
                client.Send(IP, Port, false, LocalAE, RemoteAE);
            }
            catch (Exception ex) {
                result = false;
                Console.WriteLine(ex);
            }

**Comment by anders9ustafsson** [comment]
@BobSter3000 Thanks for reporting. I have been able to reproduce the error. Funnily enough, the exact same code works when running it as a .NET Core console application...

I will investigate the root cause and come back as soon as possible with a solution.

**Comment by BobSter3000** [comment]
@anders9ustafsson Thank you very much.  This is an outstanding product and I appreciate all the work you do for it.
