### ISSUE TITLE
DicomDataset.Contains(DicomTag tag) matches on object, will not find private tags

### ISSUE THREAD

**Issue by aerik** [fo-dicom/fo-dicom#319]
### Expected behavior
Creating a tag with the same group and element numbers (and optionally private creator) should be found in DicomDataset.Contains if the dataset contains a tag having the same group, element (and optionally private creator)

### Actual behavior

It's not found

### Steps to reproduce the behavior

```
            DicomFile dfile = DicomFile.Open(file);            
            dfile.Dataset.Add(new DicomTag(0x0021, 0x0010, "TEST"), "TEST");
            bool found = dfile.Dataset.Contains(new DicomTag(0x0021, 0x0010, "TEST"));
            Console.WriteLine("Found tag: " + found.ToString());
            Console.ReadKey();
```

### fo-dicom version and OS/platform

1.1 customized, Windows 8.1

**Comment by anders9ustafsson** [comment]
@aerik Thanks for reporting. Could you please verify that the behavior is the same with 2.0.2 or higher?

**Comment by aerik** [comment]
Same result on 2.0.2
