### ISSUE TITLE
Check if a dicom tag in the dataset has a value

### ISSUE THREAD

**Issue by WilliamDoman** [fo-dicom/fo-dicom#320]
It would be very nice to have a way to check if a particular tag exists in the response dataset.  

Working with numerous PACs systems, they all have slightly different return tags and it would greatly simplify the effort to have the ability to check if the value exists vs wrapping every check in a try with empty catch.

Thank you for all your effort, this project is amazing.

**Comment by anders9ustafsson** [comment]
@WilliamDoman You are aware that `DicomDataset` contains a `Contains(DicomTag)` method, right? If this is not sufficient for your needs, what exactly is the functionality you are looking for?

**Comment by WilliamDoman** [comment]
Oh, that's perfect.  Thank you!!!!

**Comment by yogithakur** [comment]
Hi Ander. We need to find the PatientID and we are getting 0010,0020 tag. How to find the Patient ID ?

**Comment by deyung** [comment]
@yogithakur 

var dcmFile = DicomFile.Open(@"test.dcm");
dcmFile.Dataset.Get<string>(DicomTag.PatientID)

**Comment by yogithakur** [comment]
@deyung 
Let me try... 
Thanks for the immediate reply and help. I really appreciate ...:)
