### ISSUE TITLE
Dicom Server listener consumes large amount of memory if http request is sent to listener.

### ISSUE THREAD

**Issue by BobSter3000** [fo-dicom/fo-dicom#327]
I came across this completely by accident and not sure if this would be a real world issue.  However I could see this potentially being a problem.  
### Expected behavior

Close a non Dicom Connection.
### Actual behavior

Connection stays open and memory is consumed.
### Steps to reproduce the behavior

Start a DicomServer listener.  Open a web browser and navigate to http://IP:port of the DicomServer listener.  The listener seems to consume a large amount of memory that is never released.  Even when the web browser or socket is closed.  No errors seem to be logged.

![image](https://cloud.githubusercontent.com/assets/9662532/16416543/c285bcfc-3d10-11e6-9332-27407e6b7a5b.png)
### fo-dicom version and OS/platform

Tested on 2 and Beta 3.

**Comment by anders9ustafsson** [comment]
I feel this is not within my area of expertise. @IanYates @hdesouky do you have any opinion on this?

**Comment by IanYates** [comment]
Hmm - interesting.  I'll dig in to this in at the weekend.  End of financial year here tomorrow so things are pretty busy :)

My guess is that the HTTP open is triggering some code path - or more specifically *not* triggering a code path - where we sit in some busy loop waiting for a sequence of input that's never going to arrive, and in that busy loop maybe we're allocating something extra each time?  
(I reserve the right be completely wrong of course :D )

**Comment by BobSter3000** [comment]
It looks like it has something to do in DicomService.ReadAndProcessPDUAsync().
                    var length = BitConverter.ToInt32(buffer, 2);
                    length = Endian.Swap(length);
                    _readLength = length;
                    Array.Resize(ref buffer, length + 6);
                    **count = await stream.ReadAsync(buffer, 6, length).ConfigureAwait(false);**

+		this	{Dicom.Network.DicomCEchoProvider}	Dicom.Network.DicomService {Dicom.Network.DicomCEchoProvider}
+		stream	{System.Net.Sockets.NetworkStream}	System.IO.Stream {System.Net.Sockets.NetworkStream}
+		buffer	{byte[1411395366]}	byte[]
		count	6	int
		length	1411395360	int
		raw	null	Dicom.Network.RawPDU

**Comment by anders9ustafsson** [comment]
@BobSter3000 Thanks for digging out the details. I guess we need to involve cancellation tokens (#236) for a reliable solution to this problem? @IanYates Any thoughts?

**Comment by IanYates** [comment]
Unfortunately not yet.  I injured my foot Saturday afternoon.  Cleared of a fracture Monday morning finally (I was in a smallish town 3hrs from home so no weekend xrays) but it means I haven't got to 99% of what I planned to do on the weekend unfortunately.

@BobSter3000 is probably on the right path though.  We're just creating an array, trusting what's given.  As for it not being released, I'll bust out JustTrace to track it down but it won't be for a few more days I'm afraid.

That array is 1.3GB in size...  We could allow a maximum incoming size to be set too.  fo-dicom could ship with some sensible default which can be overridden by setting it to 0 or -1 (I've seen both used as sentinel values in things like SignalR and ASP.Net).

**Comment by anders9ustafsson** [comment]
@IanYates Sorry to hear about your foot. Get well soon!

**Comment by anders9ustafsson** [comment]
Scheduling this issue for next major release. Connected with #331.

**Comment by anders9ustafsson** [comment]
@BobSter3000 Is this issue still present in 3.0.0 RC2?

**Comment by BobSter3000** [comment]
@anders9ustafsson I just took a quick look at it again, and yes the condition still exists.

**Comment by anders9ustafsson** [comment]
@BobSter3000 Thanks. Will not delve into it in greater detail right now, but good to know what to pursue after the 3.0 release.
