### ISSUE TITLE
Problem parsing DateTime

### ISSUE THREAD

**Issue by MacL3an** [fo-dicom/fo-dicom#328]
### Expected behavior
It should be able to parse a DicomDateRange with the format "yyyyMMddHHmmss.ffffffzzz"

### Actual behavior
A FormatException is received.

### Steps to reproduce the behavior
      var dt = DateTime.Now.ToString("yyyyMMddHHmmss.ffffffzzz");
      dataset.Add(DicomTag.ScheduledProcedureStepStartDateTime, dt);
      var parsed = dataset.Get<DicomDateRange>(DicomTag.ScheduledProcedureStepStartDateTime);

### fo-dicom version and OS/platform
Win 8.1, VS 2015

**Comment by MacL3an** [comment]
Adding "yyyyMMddHHmmss.ffffffzzz" to PrivateDateFormats in DicomElement works. I suppose making PrivateDateFormats public would be even better.

**Comment by IanYates** [comment]
Can anyone see any downsides in making this part of the default set of date formats?
@MacL3an - did this come from some other system?  I'm a little ignorant about DICOM and dates to be honest - is this part of the spec and we've just not implemented it?

**Comment by MacL3an** [comment]
Yes, it came from another system we're trying to interface with.

"yyyyMMddHHmmss.ffffffzzz" is the expected DT format according to here:
http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html

And according to this page:
http://dicom.nema.org/dicom/2013/output/chtml/part04/sect_C.2.html
it's ok to use the timezone offset in a range, as long as it's positive:
"3.Exclusion of the "-" character for single value matching implies that a Key Attribute with DT Value Representation may not contain a negative offset from Universal Coordinated Time (UTC) if single value matching is intended. Use of the "-" character in date, time or datetime indicates range matching."
