### ISSUE TITLE
Rename methods to clarify intent

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#330]
There are a few methods whose naming regularly seem to lead to confusion, judging from recurring discussions in the fora.

More specifically I am referring to `DicomDataset.Add` and `DicomFile/Dataset.ChangeTransferSyntax`.

The `Add` method is in practice an "add-or-replace" method, and should for clarity be named as such. `ChangeTransferSyntax` does not, as its name implies, change the transfer syntax of the current object, but it generates and returns a new object. A more suitable method signature might possibly be `Clone(DicomTransferSyntax)`? Other suggestions.

Proposal is to change these method names in the upcoming release. For now, the old names could/should be maintained as well, but marked as `[Obsolete]`.

If there are more methods that would benefit from renaming, specify them in comments to this issue.

**Comment by IanYates** [comment]
Good idea.  `[Obsolete]` so we don't hurt anyone.  Clarifying method naming is definitely a good thing.  Add() for dictionaries (something most C# devs would be familiar with) throws if the key is already there.  In an immutable object helper library I use they have `Add()` with traditional meaning and `Set()` for the time where you want AddOrUpdate functionality.
