### ISSUE TITLE
Some Dicom Printer refuse print requests from fo-dicom

### ISSUE THREAD

**Issue by hdesouky** [fo-dicom/fo-dicom#336]
Some Dicom Printers like Kinica Drypro 832 and FujiFilm DryPix are not responding to printing request sent from fo-dicom DicomClient.

The root cause is these printers are supporting Implicit Little Endian transfer syntax only, while the presentation context collection builder create presentation context for requests using the explicit little endian transfer syntax as preferred syntax

As a fix, each created request should have a valid presentation context with implicit little endian transfer syntax.

Doing so will enable the presentation context collection create the valid presentation context for the association.

Note that this issue is related to bad implementation of the DICOM Protocol in the printer itself

As a reference, i attached the conformance statements for DRYPIX and DRYPRO
![image](https://cloud.githubusercontent.com/assets/2395913/16545133/fa0e7b5a-4120-11e6-9b4c-9df3feae1af4.png)

![image](https://cloud.githubusercontent.com/assets/2395913/16545130/ebd53e34-4120-11e6-96e1-52563fcbd1ff.png)

[drypix_4000.pdf](https://github.com/fo-dicom/fo-dicom/files/344988/drypix_4000.pdf)
[DP832_1116YA220B_071126_Fix.pdf](https://github.com/fo-dicom/fo-dicom/files/344989/DP832_1116YA220B_071126_Fix.pdf)

**Comment by anders9ustafsson** [comment]
Fixed by commit 6c957bc.
