### ISSUE TITLE
GE CT520 ModalityWorklist exception

### ISSUE THREAD

**Issue by Ravenheart** [fo-dicom/fo-dicom#337]
Trying to communicate with a GE Optima CT520 computer tomography machine. It looks OK up until association release requests comes then it throws an exception (see the gist).

https://gist.github.com/Ravenheart/35a716240853acb16fa75774e6e2dfeb

Fodicom Desktop 3.0.0.0 beta4

**Comment by anders9ustafsson** [comment]
@Ravenheart Thanks for reporting. Does the exception result in unwanted behavior, or do you achieve what you intended to with the call?

Of course, ideally it should not throw at all, but it would still be good to know if you are able to proceed as desired.

**Comment by Ravenheart** [comment]
Feature wise it works fine, I think the machine just prematurely closes the connection without waiting for a response from the PACS.

**Comment by anders9ustafsson** [comment]
@Ravenheart OK. We'll see if we deal with this now or if we consider it an issue for the general async overhaul of the network functionality in the next release of *fo-dicom*.

**Comment by anders9ustafsson** [comment]
@Ravenheart I think we'll leave this issue without consideration in 3.0.0 after all. `DicomService` is currently sometimes too quick in closing connections, as a precaution in case the opposite side is not responding properly. We could definitely improve on this, but I think we'll postpone the improvement until next major release.

**Comment by anders9ustafsson** [comment]
Connected to #331.

**Comment by anders9ustafsson** [comment]
@Ravenheart Between Beta 4 and RC 3 there have been substantial improvements in the association communication, so potentially the issue you are describing here has been fixed. It would be really great if you could take the time to examine whether RC3 handles the association releases sufficiently in your setup.

**Comment by Ravenheart** [comment]
I won't be able to test this anytime soon as the hospital with said machine is working. I will push for us to upgrade to v3.0.0.0 once its out though.

**Comment by anders9ustafsson** [comment]
@Ravenheart Do you have any updates on whether the exception behavior for modality worklists is still there?

**Comment by gofal** [comment]
Closing this now. @Ravenheart please feel free to reopen it if the issue still exists.
