### ISSUE TITLE
If there is an example of the better OnCFindRequest

### ISSUE THREAD

**Issue by xiongw1987** [fo-dicom/fo-dicom#338]

**Comment by anders9ustafsson** [comment]
@xiongw1987 Is this issue still a concern to you, or did you get the necessary assistance via the Gitter forum?

**Comment by anders9ustafsson** [comment]
@xiongw1987 I interpret your silence as you have been able to solve the problem already. I will close this issue without further action for now. If you still have concerns, please re-open it.
