### ISSUE TITLE
DicomEncoding 

### ISSUE THREAD

**Issue by Muttleskovic** [fo-dicom/fo-dicom#339]
I'm trying to rewrite PatientName and use Romanian diacritics like Ş and Ţ.
I've found a character map that contains all my necessary chars and also found in DICOM/DicomEncoding.cs , but 2 / 5 diacritics are replaced with ?

Char map https://en.wikipedia.org/wiki/ISO/IEC_8859-2
https://github.com/fo-dicom/fo-dicom/pull/22/files

Thank,

### Expected behavior

ăĂâÂșȘțȚîÎ

### Actual behavior

ăĂâÂ????îÎ

### Steps to reproduce the behavior

f = DicomFile.Open(fi.FullName)
di As DicomItem = New DicomShortText(DicomTag.PatientName, DicomEncoding.GetEncoding("ISO 2022 IR 101"), "aăĂâÂsșȘtțȚiîÎ")
f.Dataset.add(di)

### fo-dicom version and OS/platform
.net v2.0.2.0

**Comment by anders9ustafsson** [comment]
@Muttleskovic Could you please try and also apply the encoding as a fallback encoding argument in the `DicomFile.Open` call, i.e.:

    enc as DicomEncoding = DicomEncoding.GetEncoding("ISO 2022 IR 101")
    f = DicomFile.Open(fi.FullName, enc)
    di As DicomItem = New DicomShortText(DicomTag.PatientName, enc, "aăĂâÂsșȘtțȚiîÎ")
    f.Dataset.add(di)

Would this change anything?

**Comment by Muttleskovic** [comment]
Hi Anders and thank for your response, sadly opening the file with specific encoding didn't help :(
Based on this idea, I've try to save the file with encoding, but receive number of arguments error.
f.SaveAsync(filename **, enc**)

![image](https://cloud.githubusercontent.com/assets/20122218/17617820/deb34f24-6084-11e6-9470-ce870b7e0461.png)
![image](https://cloud.githubusercontent.com/assets/20122218/17617868/0fdbef52-6085-11e6-99a5-9c4b0fb9db4c.png)

**Comment by anders9ustafsson** [comment]
@Muttleskovic As you have already found out, no, there is no `SaveAsync` taking a `DicomEncoding` argument. 

Have you tried the 3.0 pre-release to see if results are different in this version?

**Comment by anders9ustafsson** [comment]
@Muttleskovic I have now checked this a little more closely, and my recommendation is that you use UTF-8 (ISO IR 192) encoding instead.

That is, try this:

    di As DicomItem = New DicomShortText(DicomTag.PatientName, DicomEncoding.GetEncoding("ISO IR 192"), "aăĂâÂsșȘtțȚiîÎ")

**Comment by Muttleskovic** [comment]
Hi Andres and thanks for your answer.
I've tried  ISO IR 192 but it's quite OK, many diacritics are't right and even standard chars are a bit wrong (s)
 aăĂâÂsșȘtțȚiîÎ
![image](https://cloud.githubusercontent.com/assets/20122218/18519003/e7ca1d64-7aaa-11e6-8358-b1f314b0bd83.png)

I've also tried Version 3.0.0-beta4, but sadly my old command of retrieving images don't work anymore and I didn't find any info on google 
`Dim timg As Image = image.RenderImage().AsBitmap()`
![image](https://cloud.githubusercontent.com/assets/20122218/18519142/73a49b20-7aab-11e6-805b-a68be82e193c.png)

**Comment by anders9ustafsson** [comment]
@Muttleskovic This is strange, because I am able to reproduce your string completely when using ISO IR 192. What if you also set the *Specific Character Set* (0008,0005) tag to **ISO IR 192**, does that make any difference?

Regarding your problem with `AsBitmap()`, which NuGet package are you using?

**Comment by Muttleskovic** [comment]
Hi Anders, there is a small difference when setting Specific Character Set (0008,0005) tag, but sadly same issues for me 
![image](https://cloud.githubusercontent.com/assets/20122218/18546664/c477f00a-7b47-11e6-8c21-ff47092fe157.png)
I've notice some people use \ISO IR 192, I've tried like this, but the result is the same
Regarding NuGet Package  all are 3.0.0-beta4:
![image](https://cloud.githubusercontent.com/assets/20122218/18546709/0dd890c4-7b48-11e6-8eff-f9528e643389.png)
Can you write your code that you manage to reproduce the string, maybe I'm missing a line or something

Thank you,

**Comment by anders9ustafsson** [comment]
@Muttleskovic First of all, remove *Fellow Oak DICOM Portable Class Library*, it is redundant in this case and may cause the problems you are having with creating images.

I will look into the issue again more closely. Please be prepared that if I publish code it will be in C#. I am not VB fluent :-)

**Comment by anders9ustafsson** [comment]
@Muttleskovic With ISO IR 192 it works flawlessly for me. This is what I have done:

    var expected = "aăĂâÂsșȘtțȚiîÎ";
    var file = DicomFile.Open(@"Test Data\CT-MONO2-16-ankle");
    var dataset = file.Dataset;
    dataset.Add(
                new DicomPersonName(DicomTag.PersonName, DicomEncoding.GetEncoding("ISO IR 192"), expected));
    var actual = dataset.Get<string>(DicomTag.PersonName);
    Assert.Equal(expected, actual);
    Console.WriteLine(actual);

Could it be an encoding problem in the text control you are using, or when writing text on the image?

**Comment by Muttleskovic** [comment]
Hi Anders, I've did the method but the result is the same on newly saved image..
I've tried something different now, after the name change i'm displaying the new tag and indeed is showing to be correct.
![image](https://cloud.githubusercontent.com/assets/20122218/18575878/dad2c4d6-7be4-11e6-963f-aea6ac59f206.png)
`Dim expected = "ăĂîÎșȘțȚâÂ"
                    Dim dataset = f.Dataset
                    dataset.Add(New DicomPersonName(DicomTag.PersonName, DicomEncoding.GetEncoding("ISO IR 192"), expected))
                    Dim actual = dataset.[Get](Of String)(DicomTag.PersonName)
                    MsgBox(actual)`
 I think my problem is in saving the new file or my DICOM-viewers don't interpret the encoding correctly. I will try making a new file from our Computer-Tomograf with diacritics, maybe in this way will find where the problem is.

**Comment by Muttleskovic** [comment]
Hi Anders,
1st of all I want to thank you for your patience and for all your support, I've manage to find where my problem was, and it was the viewer :( 
At the moment I'm also writing the Specific Character Set (0008,0005) : ISO_IR 192 and looks OK
Licensed Viewer :
![image](https://cloud.githubusercontent.com/assets/20122218/18581662/485733fa-7c0a-11e6-8256-7d7f28644c1b.png)
MicroDicomViewer :
![image](https://cloud.githubusercontent.com/assets/20122218/18581695/5d5855f4-7c0a-11e6-8654-c902bbdf38f9.png)
