### ISSUE TITLE
DICOM Parse error - Stack empty 3.0.0 beta 4

### ISSUE THREAD

**Issue by hashitha** [fo-dicom/fo-dicom#342]
I am using 3.0.0 beta 4

and when I try to open this file I get stack empty. I have been processing just over a million dicom files and around 3 of the files get this error.

I have attached the file with the patient name changed

[https://s3-ap-southeast-2.amazonaws.com/sigmalogic.com.au/pacs/dicomfile.zip](https://s3-ap-southeast-2.amazonaws.com/sigmalogic.com.au/pacs/dicomfile.zip)

**Comment by anders9ustafsson** [comment]
@hashitha Thanks for reporting, will examine your file and get back (potentially with questions) soon enough.

**Comment by anders9ustafsson** [comment]
@hashitha The issue might be related with the fact that the private sequence **(01f3, xx11)** contains empty items. My initial guess is that the parser gets out of phase when trying to handle these, but I need to investigate further to confirm that.

DCMTK's application *dcmdump* succeeds in handling these empty items. I am not entirely sure that empty sequence items are supported by DICOM, but **Stacky empty** is not very informative either way.

Investigation will continue.

**Comment by hashitha** [comment]
Thanks @anders9ustafsson for looking at this. I thought so too because that is the only different I can see from the files that work and that doesn't. I also tried with dcmchee Java code, and it works there. It would be great if we can handle this because we have no control over the modalities.
