### ISSUE TITLE
How to change bmp file to dcm?

### ISSUE THREAD

**Issue by wangfeng13** [fo-dicom/fo-dicom#344]
I want to change a bmp file to dcm, but I do not how to add bmp data into dcm. Could you give me some suggestion？

**Comment by anders9ustafsson** [comment]
@wangfeng13 As referenced in the [External Links](https://github.com/fo-dicom/fo-dicom/wiki#external-links) on the wiki page, Mahesh Dubey has provided a simple gist to solve this particular problem. Please take a look at Mahesh's [code](https://gist.github.com/mdubey82/4030263).
