### ISSUE TITLE
CMove and CGet examples

### ISSUE THREAD

**Issue by Ravenheart** [fo-dicom/fo-dicom#345]
I would really benefit if there was a CMove SCP and CGet SCP example available. I've found only one example here [fo-dicom google groups](https://groups.google.com/forum/#!topic/fo-dicom/ic35XVDD1Hc) but that implementation is very slow in sending the images. DicomClient sends one picture, disconnects and then reconnects and sends one picture again, lots of time is lost between association and deassociation.

**Comment by anders9ustafsson** [comment]
@Ravenheart Currently, there are two C-GET SCU examples in the unit tests, see [here](https://github.com/fo-dicom/fo-dicom/blob/development/Tests/Network/DicomCGetRequestTest.cs). Regarding C-MOVE/C-GET SCP examples, I understand your concern. 

We will consider to provide this when time permits. And community contributions on this are of course also more than welcome.

**Comment by anders9ustafsson** [comment]
Moved to fo-dicom/fo-dicom-samples#3.
