### ISSUE TITLE
Add additional state arg to DicomServer constructor to allow passing data to DicomService

### ISSUE THREAD

**Issue by jmiglietta-inc** [fo-dicom/fo-dicom#348]
It would be helpful for configuring the service if a state argument could be passed to the DicomServer / DicomService objects.

e.g
DicomServer(int port, string certificateName = null, DicomServiceOptions options = null, Logger logger = null, object state = null);

ServerParams params = new ServerParams(localPort: 4242, localAET: "storescp", remoteAET: "PHX" );
DicomServer server = DicomServer<CStoreSCP> server = new DicomServer<CStoreSCP>(port: params.LocalIpPort, state: params); 

Then...

public DicomService(Stream stream, Logger log, object state);
public DicomService(Stream stream, Encoding fallbackEncoding, Logger log, object state)

This could allow passing in the AET, storagePath , etc

**Comment by anders9ustafsson** [comment]
@jmiglietta-inc Good thinking. Will take this under thorough consideration for the next major release.

**Comment by jaime-olivares** [comment]
This one seems to be related to #242? isn't it?

**Comment by anders9ustafsson** [comment]
Yes, I believe they are related, but I have not investigated it more thoroughly. If you can confirm that both issues solve the same problem, I would be more than happy to close one of them :-)

**Comment by deyung** [comment]
This would be resolved with this PR https://github.com/fo-dicom/fo-dicom/pull/441
