### ISSUE TITLE
why ? Cannot send messages since pending: {pending} would exceed max async ops invoke

### ISSUE THREAD

**Issue by xydoublez** [fo-dicom/fo-dicom#349]
### Expected behavior
            string[] files = System.IO.Directory.GetFiles(@"E:\dicom_files\CT\210552", "*.dcm");
            var client = new DicomClient();
            client.Linger = 500;
            
            foreach (var item in files)
            {

                
                DicomCStoreRequest req = new DicomCStoreRequest(item);
                req.OnResponseReceived += (r, q) =>
                {
                    Console.WriteLine(q.Status);
                };
                client.AddRequest(req);
                
                
            }
            client.Send("127.0.0.1", 22345, false, "scp", "any_scp");

### Actual behavior

exception:
Cannot send messages since pending: {pending} would exceed max async ops invoke
### fo-dicom version and OS/platform
v.3.0.0 (Beta 4, 7/09/16   dotnet core

**Comment by anders9ustafsson** [comment]
@xydoublez If I am not mistaken, you will need to set the number of pending and invoked asynchronous operations, at least when you are including multiple requests in one send.

Try and add the following line after the initialization of `client` to see if it helps:

    client.NegotiateAsyncOps(files.Length, files.Length);

**Comment by xydoublez** [comment]
thank you
