### ISSUE TITLE
PrintSCP Tag: () not found in dataset

### ISSUE THREAD

**Issue by chicocvenancio** [fo-dicom/fo-dicom#353]
### Expected behavior

PrintSCP generates a printed file.
### Actual behavior

PrintSCP errors on the association with an error of some tags not found in dataset.
With the own PrintSCU sample the tags not found are (2100,0040) and (0000,1008).
With e-film the tags not found are (0000,1000) and  (0000,1001).
### Steps to reproduce the behavior

Open PrintSCP
Send a Print Job
### fo-dicom version and OS/platform

Tried with fo-dicom.Desktop.3.0.0-beta1 and fo-dicom.Desktop.3.0.0-beta4
Windows 8 
.Net 4.5

**Comment by anders9ustafsson** [comment]
@chicocvenancio Although I have not explicitly verified it, I believe that this is because the samples are out of sync with the latest development in *fo-dicom*. Once *fo-dicom* 3.0 stabilizes well enough for a public release, we will ensure that the samples are again in sync.

**Comment by chicocvenancio** [comment]
Is there a know good build commit/target?

**Comment by anders9ustafsson** [comment]
Sample project has now been updated to latest *fo-dicom* pre-release (3.0.0-beta4), and incompatible code has been updated accordingly.

**Comment by adilt** [comment]
@anders9ustafsson 
The issue is still existing with PrintSCP and  fo-dicom.Desktop.3.0.0-RC1.

**Comment by anders9ustafsson** [comment]
@adilt Are you using the Print SCU sample to test this, or are you sending arbitrary images to the Print SCP? I have recently updated *fo-dicom-samples* to reference NuGet packages 3.0.0-beta4. Have you updated your clone to the latest commits on *fo-dicom-samples* before you tested?

**Comment by adilt** [comment]
@anders9ustafsson I updated with the latest commits on fo-dicom-samples and I also updated the fo-dicom (beta4 to rc1).
I use jdicom PrintSCU to send images and PrintSCU sample with fo-dicom.3.0.0-RC1.
And with both threw exception...not found (0000,1001).
And fo-dicom.2.0.2 and PrintSCP and these two Print SCU above (with same images) are working.

**Comment by anders9ustafsson** [comment]
@adilt Yes, there seems to be an issue in the `FilmBox.Initialize` method with an outdated call; the recent change to only allow pure adding for `DicomDataset.Add` seems to be the issue here. Will investigate what the best solution for this particular case is.

Thanks for reporting!

**Comment by anders9ustafsson** [comment]
@adilt Just to know that we are seeing the same issue, please post the exact error message and relevant parts of the stack trace from the Print SCP.

**Comment by adilt** [comment]
# **With N-GET-RQ Printer SOP** 
--------------------------------------------------------------------------------
 DIMSE Command:
--------------------------------------------------------------------------------
(0000,0000) UL 90                                               #     4, CommandGroupLength
(0000,0003) UI [1.2.840.10008.5.1.1.16]                         #    22, RequestedSOPClassUID
(0000,0100) US 272                                              #     2, CommandField
(0000,0110) US 1                                                #     2, MessageID
(0000,0800) US 257                                              #     2, CommandDataSetType
(0000,1001) UI [1.2.840.10008.5.1.1.17]                         #    22, RequestedSOPInstanceUID

--------------------------------------------------------------------------------

Exception processing P-Data-TF PDU: Dicom.DicomDataException: Tag: (0000,1005) not found in dataset
   à Dicom.DicomDataset.Get[T](DicomTag tag, Int32 n, Boolean useDefault, T defaultValue) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\DicomDataset.cs:ligne 420
   à Dicom.Printing.PrintService.GetPrinter(DicomNGetRequest request) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\NGIPS\Console\PrintSCP\PrintService.cs:ligne 451
   à Dicom.Printing.PrintService.OnNGetRequest(DicomNGetRequest request) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\NGIPS\Console\PrintSCP\PrintService.cs:ligne 427
   à Dicom.Network.DicomService.PerformDimse(DicomMessage dimse) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 801
   à Dicom.Network.DicomService.<ProcessPDataTFAsync>d__55.MoveNext() dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 613
Exception processing PDU: Dicom.DicomDataException: Tag: (0000,1005) not found in dataset
   à Dicom.DicomDataset.Get[T](DicomTag tag, Int32 n, Boolean useDefault, T defaultValue) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\DicomDataset.cs:ligne 420
   à Dicom.Printing.PrintService.GetPrinter(DicomNGetRequest request) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\NGIPS\Console\PrintSCP\PrintService.cs:ligne 451
   à Dicom.Printing.PrintService.OnNGetRequest(DicomNGetRequest request) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\NGIPS\Console\PrintSCP\PrintService.cs:ligne 427
   à Dicom.Network.DicomService.PerformDimse(DicomMessage dimse) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 801
   à Dicom.Network.DicomService.<ProcessPDataTFAsync>d__55.MoveNext() dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 682
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à Dicom.Network.DicomService.<ListenAndProcessPDUsAsync>d__54.MoveNext() dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 408
Connection closed with error: Dicom.DicomDataException: Tag: (0000,1005) not found in dataset
   à Dicom.DicomDataset.Get[T](DicomTag tag, Int32 n, Boolean useDefault, T defaultValue) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\DicomDataset.cs:ligne 420
   à Dicom.Printing.PrintService.GetPrinter(DicomNGetRequest request) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\NGIPS\Console\PrintSCP\PrintService.cs:ligne 451
   à Dicom.Printing.PrintService.OnNGetRequest(DicomNGetRequest request) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\NGIPS\Console\PrintSCP\PrintService.cs:ligne 427
   à Dicom.Network.DicomService.PerformDimse(DicomMessage dimse) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 801
   à Dicom.Network.DicomService.<ProcessPDataTFAsync>d__55.MoveNext() dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 682
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à Dicom.Network.DicomService.<ListenAndProcessPDUsAsync>d__54.MoveNext() dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 408

**Comment by adilt** [comment]
**With N-CREATE Basic Film Session**

Starting print SCP server with AET: PRINTSCP on port 8000
Press any key to stop the service
PRINTSCP <- Association request:
Calling AE Title:       PRINTSCP
Called AE Title:        PRINTSCP
Remote host:            127.0.0.1
Remote port:            9157
Implementation Class:   Implementation Class UID [1.2.826.0.1.3680043.2.60.0.1]
Implementation Version: softlink_jdt103
Maximum PDU Length:     32768
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  4
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Proposed]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [Proposed]
       Abstract Syntax:  Basic Color Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  7 [Proposed]
       Abstract Syntax:  Print Job SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
Received association request from AE: PRINTSCP with IP: 127.0.0.1
Accepted association request from PRINTSCP
PRINTSCP -> Association accept:
Calling AE Title:       PRINTSCP
Called AE Title:        PRINTSCP
Remote host:            127.0.0.1
Remote port:            9157
Implementation Class:   Implementation Class UID [1.2.826.0.1.3680043.2.60.0.1]
Implementation Version: softlink_jdt103
Maximum PDU Length:     32768
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  4
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Verification SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  3 [Accept]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  5 [Accept]
       Abstract Syntax:  Basic Color Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
  Presentation Context:  7 [Accept]
       Abstract Syntax:  Print Job SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
PRINTSCP <- N-Create request [1]
Exception processing P-Data-TF PDU: Dicom.DicomDataException: Tag: (0000,1001) not found in dataset
   à Dicom.DicomDataset.Get[T](DicomTag tag, Int32 n, Boolean useDefault, T defaultValue) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\DicomDataset.cs:ligne 420
   à Dicom.Printing.PrintService.CreateFilmSession(DicomNCreateRequest request) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\NGIPS\Console\PrintSCP\PrintService.cs:ligne 207
   à Dicom.Printing.PrintService.OnNCreateRequest(DicomNCreateRequest request) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\NGIPS\Console\PrintSCP\PrintService.cs:ligne 183
   à Dicom.Network.DicomService.PerformDimse(DicomMessage dimse) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 792
   à Dicom.Network.DicomService.<ProcessPDataTFAsync>d__55.MoveNext() dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 673
Exception processing PDU: Dicom.DicomDataException: Tag: (0000,1001) not found in dataset
   à Dicom.DicomDataset.Get[T](DicomTag tag, Int32 n, Boolean useDefault, T defaultValue) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\DicomDataset.cs:ligne 420
   à Dicom.Printing.PrintService.CreateFilmSession(DicomNCreateRequest request) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\NGIPS\Console\PrintSCP\PrintService.cs:ligne 207
   à Dicom.Printing.PrintService.OnNCreateRequest(DicomNCreateRequest request) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\NGIPS\Console\PrintSCP\PrintService.cs:ligne 183
   à Dicom.Network.DicomService.PerformDimse(DicomMessage dimse) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 792
   à Dicom.Network.DicomService.<ProcessPDataTFAsync>d__55.MoveNext() dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 682
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à Dicom.Network.DicomService.<ListenAndProcessPDUsAsync>d__54.MoveNext() dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 408
Connection closed with error: Dicom.DicomDataException: Tag: (0000,1001) not found in dataset
   à Dicom.DicomDataset.Get[T](DicomTag tag, Int32 n, Boolean useDefault, T defaultValue) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\DicomDataset.cs:ligne 420
   à Dicom.Printing.PrintService.CreateFilmSession(DicomNCreateRequest request) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\NGIPS\Console\PrintSCP\PrintService.cs:ligne 207
   à Dicom.Printing.PrintService.OnNCreateRequest(DicomNCreateRequest request) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\NGIPS\Console\PrintSCP\PrintService.cs:ligne 183
   à Dicom.Network.DicomService.PerformDimse(DicomMessage dimse) dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 792
   à Dicom.Network.DicomService.<ProcessPDataTFAsync>d__55.MoveNext() dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 682
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   à Dicom.Network.DicomService.<ListenAndProcessPDUsAsync>d__54.MoveNext() dans C:\Users\dev\Downloads\fo-dicom-3.0.0-rc1\DICOM\Network\DicomService.cs:ligne 408

**Comment by adilt** [comment]
I am sorry to post all log...I don't know what can be relevant to you. 
I will investigate on my side too (not this week) and keep you inform if I will find something.
Thanks.

**Comment by adilt** [comment]
![image](https://cloud.githubusercontent.com/assets/8738098/22468645/6a2492cc-e7c9-11e6-9f3e-04c566f83219.png)

**Comment by adilt** [comment]
![image](https://cloud.githubusercontent.com/assets/8738098/22468671/899538e6-e7c9-11e6-90fe-1d535aafe861.png)
