### ISSUE TITLE
Memory leak in RenderImage() in Unity Asset

### ISSUE THREAD

**Issue by oliver9523** [fo-dicom/fo-dicom#354]
### Expected behavior

Continuously read frames from a dicom file.
### Actual behavior

Frames are read and can be converted to Texture2D however the memory footprint off the application continues to rise. Something in DicomImage.RenderImage() isn't being cleared causing the memory leak.
### Steps to reproduce the behavior

Using a very simple unity script to isolate the source

Example File http://www.insight-journal.org/midas/item/view/2471

void Start() {
  dicomImage = new DicomImage("Broccoli/IM_0001",0);
}

void Update() {
  dicomImage.RenderImage (frame);
  frame++;
  if (frame == dicomImage.NumberOfFrames) {
    frame = 0;
  }
}

**Issue Update:**
The memory leak can also be recreated by just constantly requesting the same frame
void Update() {
  dicomImage.RenderImage (0);
}
### fo-dicom version and OS/platform

Unity Asset Version: 2.9.0b (May 19, 2016)
Unity 5.4.0f3 (64-bit)
Window 10 64bit

**Comment by anders9ustafsson** [comment]
@oliver9523 Sorry for late reply.

I have tried a similar thing with the .NET Framework version of *fo-dicom*, and at first look there does not seem to be a (big) memory leak. Here is the memory usage when rendering the image 10 times per second. Garbage collection seems to step in automatically and clear the memory every now and then.

![untitled](https://cloud.githubusercontent.com/assets/6515030/20300923/98d923ec-ab21-11e6-945f-7546c2dac375.png)

Have you tried to apply a more aggressive garbage collection in your own application? Maybe that will help you sufficiently releasing memory.

**Comment by oliver9523** [comment]
@anders9ustafsson thanks, I'll have a look around Unity docs/forums to see if there's a way to adjust the garbage collection from there.
