### ISSUE TITLE
Cannot override CreateCStoreReceiveStream due to private fields

### ISSUE THREAD

**Issue by aerik** [fo-dicom/fo-dicom#357]
### Expected behavior

Should be able to override CreateCStoreReceiveStream in derived classes
### Actual behavior

 _dimseStreamFile and _dimseStream are both marked private so it is not possible to set them (see https://msdn.microsoft.com/en-us/library/ms173149.aspx#Anchor_3) - therefore overriding the method is useless
### Steps to reproduce the behavior

try to override CreateCStoreReceiveStream
### fo-dicom version and OS/platform

3.0 beta, windows

**Comment by anders9ustafsson** [comment]
@aerik Sorry for the late response.

What, more specifically, would you like to do if you had direct access to `_dimseStreamFile` and `_dimseStream` when overriding the `DicomService` protected methods?

I did not add these protected methods myself, so I cannot say for sure in which context it is intended to work. Would it suffice to call the base method in the overridden method to set `_dimseStreamFile` and `_dimseStream`, i.e.

    protected override void CreateCStoreReceiveStream(DicomFile file)
    {
      base.CreateCStoreReceiveStream(file);
      ...
    }

**Comment by anders9ustafsson** [comment]
@aerik Any thoughts on the questions in my previous comment?

**Comment by aerik** [comment]
Well, I need access to them so I can write my file to the location I want with the filename I want.  Here's my code:

```
protected override void CreateCStoreReceiveStream(DicomFile file)
        {
            try
            {
                string fileFullName = _CalledPartition.SaveFileToIncomingFolder(file, true);
                if (fileFullName == null)
                {
                    _Logger.Warn("Creating temporary file");
                    fileFullName = Dicom.IO.TemporaryFile.Create().Name;
                    file.Save(fileFullName);
                }
                _dimseStreamFile = IOManager.CreateFileReference(fileFullName);
                _dimseStream = File.Open(fileFullName, FileMode.Open, FileAccess.ReadWrite);
                _dimseStream.Seek(0, SeekOrigin.End);
            }
            catch (Exception x)
            {
                _Logger.Error("Error in CreateCStoreReceiveStream: " + x.Message + "\r\n" + x.StackTrace);
            }
        }
```

(I marked the fields as protected instead of private so my DicomSCP which inherits DicomService can access them.)

It would not work to call the base method because I am trying to avoid creating a temporary file.

Thanks for looking at this.
