### ISSUE TITLE
Null characters not trimmed from string values

### ISSUE THREAD

**Issue by aerik** [fo-dicom/fo-dicom#359]
### Expected behavior

strings containing null characters will be cleaned up

An earlier version of FO-DICOM contained this definition of StringValue in DicomElement.cs:

```
        protected string StringValue {
            get {
                if (_value == null && Buffer != null)
                    _value = Encoding.GetString(Buffer.Data, 0, (int)Buffer.Size).TrimEnd((char)ValueRepresentation.PaddingValue);
                //Get rid of null characters
                if (_value.Contains('\0')) _value = _value.Replace("\0", "");
                return _value;
            }
        }
```

But the line that removes nulls is gone now.  I tried using Blame to figure out when it went away, but had no success
### Actual behavior

Null values are left in strings
### fo-dicom version and OS/platform

3.x beta, Windows

**Comment by rickardraysearch** [comment]
Isn't this correct behavior? I can't find anything in part 5 about ignoring trailing nulls. 

If the tag is a Code String, then stripping leading and trailing spaces would be valid, but not zeros. 

To me, adding back the `.Replace("\0","")` looks like handling quirks in other systems at an inappropriate level. Couldn't this be done outside of fo-dicom?

**Comment by aerik** [comment]
I don't know.  In the case I'm dealing with, the nulls were sent by another application.  Removing them is the only way to get FO-Dicom not to crash.

Are null characters ever valid?  The are not part of the default character set (http://dicom.nema.org/Dicom/2013/output/chtml/part05/chapter_E.html) and I'd imagine even if one were using another character set, nulls would still not be valid in a string.

There was a small discussion here 
https://groups.google.com/forum/#!topic/fo-dicom/H8ZNBtg32ug

but even that does not seem to allow for a null being a valid character for anything but padding uids.

Also, yes, one can make the argument (as was done in the google group) that the vendor of the software sending the null should fix it, put for me, as a vendor of software providing DICOM services, I'd like my software to be as compatible as possible.  We get calls from customers already when they have issues with files or network communications, and us telling them, "sorry, go call {big name manufacturer like Toshiba or GE} and have them fix it" is less than ideal, at least if we have a fix available.

**Comment by rickardraysearch** [comment]
So, what about moving the `.Replace("\0", "")` to the Enum.Parse calls? There are three in DicomElement.cs on lines 102, 169 and 391. That looks much nicer to me, since we can reasonably expect enum entries to not contain null bytes... E.g.
```
            if (typeof(T).GetTypeInfo().IsEnum) return (T)Enum.Parse(typeof(T), StringValue.Replace("\0", ""), true);
```

**Comment by hashitha** [comment]
I think this may also be related to the issue I had when testing with RadiAnt Dicom Viewer CFind which was sending an extra space.

OnCFindRequest I had to do this

```
                string level = request.Dataset.Get<string>(DicomTag.QueryRetrieveLevel);

                DicomQueryRetrieveLevel requestLevel = DicomQueryRetrieveLevel.Study;

                if (level.Contains("IMAGE"))
                {
                    requestLevel = DicomQueryRetrieveLevel.Image;
                }

                if (level.Contains("STUDY"))
                {
                    requestLevel = DicomQueryRetrieveLevel.Study;
                }

                if (level.Contains("SERIES"))
                {
                    requestLevel = DicomQueryRetrieveLevel.Series;
                }

               if (requestLevel == DicomQueryRetrieveLevel.Study)
                {
                ...
```

**Comment by anders9ustafsson** [comment]
@hashitha I will implement this according to @rickardraysearch's recommendation. This means that you will still need to account for null characters (like you implicitly do in your example) if you use `Get<string>`. Using `Get<T>` where `T` is an enumerated type on the other hand will after the fix ignore null characters.

**Comment by hashitha** [comment]
@anders9ustafsson yes that is fine
