### ISSUE TITLE
'Dicom.DicomDataException' in Dicom.Core.dll when opening Philips US file

### ISSUE THREAD

**Issue by igorkrav** [fo-dicom/fo-dicom#364]
[Uploading 3_anon.zip…]()
### Expected behavior

Open DICOM file using Dicom.Imaging.DicomImage(string fileName) constructor
### Actual behavior

Dicom.DicomDataException thrown
### Steps to reproduce the behavior

call Dicom.Imaging.DicomImage() with attached file
### fo-dicom version and OS/platform

OS:Windows 7
fo-dicom: 2.0.2

The attached DICOM image (jpegls compression) received from Philips US machine.
The cause of problem is the Ultrasound Regions Sequence encoded without 0018:6011 tag.
The sequence is started with FFFE:E000 tag immediately.
To handle it I've made the following changes in file
fo-dicom-development\DICOM\IO\Reader\DicomReader.cs
Line 570
Updated
                    if (this._vr == DicomVR.SQ)
by
                    if (_vr == DicomVR.SQ || _tag == Dicom.DicomTag.Item)
Added 2 lines after line 574
                        if (_tag == Dicom.DicomTag.Item)
                            source.Rewind();

The actual file can be opened now but I've made very basic regression testing with other DICOM files

**Comment by anders9ustafsson** [comment]
@igorkrav Have you tested the same file with 3.0.0-beta4? We have made several bug fixes in the parsing since 2.0.2.

**Comment by igorkrav** [comment]
Checked it with 3.0.0-beta4
Got the same Dicom.DicomDataException :
{"Unhandled VR in DICOM parser observer: NONE"}
[3_anon.zip](https://github.com/fo-dicom/fo-dicom/files/541551/3_anon.zip)

There is no exception DICOM Store SCP when such a file received but the saved file doesn't contain US regions at all.

BTW
The previous DICOM sample has wrong PIXEL_VALUE tag
The attached file can be used for the testing
Also here is DicomReader.cs I've changed
There is no exceptions when opening but not sure how to restore US regions when DicomTag.SequenceOfUltrasoundRegions tag is missing in dataset
[DicomReader.zip](https://github.com/fo-dicom/fo-dicom/files/541574/DicomReader.zip)

**Comment by anders9ustafsson** [comment]
@igorkrav Sorry for the delay. I read your post more thoroughly now, and I assume this is the key message?

> The cause of problem is the Ultrasound Regions Sequence encoded without 0018:6011 tag.
The sequence is started with FFFE:E000 tag immediately.

If that is the case, how will you ever know where to find the *Ultrasound Regions Sequence*? To me, this sounds like an irrecoverably invalid file. Have you tested to parse it in other viewers/editors? How do they handle the file?

**Comment by igorkrav** [comment]
I think you are definitely right but there is no way to fight with a big guys like Philips.
And explain customers why they are not able to make measurements.
I never tried to open such an images with other viewers.
In my parser I'm ignoring 0018:6011 tag and reading the regions by tags from 0018:6012 to 0018:602e.

Also wondering does it make sense to save the received buffer as is just adding group 2 ?
Without parsing it to the internal structure and reassembly the DICOM file from there ?

**Comment by gofal** [comment]
the DicomDump, that comes with fo-dicom, throws an exception when parsing the Dataset. the last successfully read Tag is 0018,5020. 
Even the tool dcmdump from the dcmtk library (url) has an error:
```
W: DcmMetaInfo: Group Length of Meta Information Header has incorrect value
W: DcmItem: Parse error while parsing element (fffe,e000)
E: dcmdump: Invalid tag: reading file: C:\Users\Reinhard\Downloads\3_anon.dcm
```
In my opinion this file is no valid dicom.
Also here is the question: fo-dicom itself has no error. but should there be a change in fo-dicom to make it be able to deal with such corrupt files?

**Comment by anders9ustafsson** [comment]
@igorkrav I am still reluctant to make this change, since I am concerned that it might have unforeseen side effects in other parsing scenarios. However, I will add the solution you have proposed, in a somewhat modified form, and ask for review from the community. Stay tuned for the upcoming PR.

**Comment by igorkrav** [comment]
According the DICOM spec it's not valid DICOM
Can't find where did I get it
Looks like there is no sense to waist a time for it

**Comment by anders9ustafsson** [comment]
@igorkrav Too late :-) I have included the fix now. Enjoy!
