### ISSUE TITLE
How can i know my exceptions in winform application or wpf application

### ISSUE THREAD

**Issue by ztegod** [fo-dicom/fo-dicom#365]
### Expected behavior

I know that if i add this code: Dicom.Log.LogManager.SetImplementation(ConsoleLogManager.Instance) on version 2.0.2,i can see my exceptions  in logs ,but how can i know my excptions in winform application or wpf application
### fo-dicom version and OS/platform

fo-dicom version :2.0.2

**Comment by anders9ustafsson** [comment]
@ztegod If you want to access the logging output in your application, you can for example use the `NLogManager` and dump the output to a `MemoryTarget`. More on memory target logging with *NLog* [here](https://github.com/nlog/nlog/wiki/Memory-target).

**Comment by ztegod** [comment]
@anders9ustafsson Thanks for your reply,and now i can get my logs by adding these codes:  

`  Dicom.Log.LogManager.SetImplementation(NLogManager.Instance);
            var config = new LoggingConfiguration();
            var target = new MemoryTarget();
            target.Layout = @"${message}";
            config.AddTarget("Console", target);
            config.LoggingRules.Add(new LoggingRule("*", NLog.LogLevel.Info, target));
            NLog.LogManager.Configuration = config;
            foreach (string s in target.Logs)
            {
                Console.Write(s);
            }`
but when i get an error like:IO Exception while reading PDU:{0}.If i can get the specific exception,instead of {0}.Where can i change my code to improve it?
