### ISSUE TITLE
How get Dicom image locally since PAC´s??, or can tell me where start investigate, please.

### ISSUE THREAD

**Issue by Alejandro666** [fo-dicom/fo-dicom#366]

**Comment by anders9ustafsson** [comment]
@Alejandro666 Please be more specific. What are you trying to solve? What have you done so far? Which platform are you working on?

**Comment by Alejandro666** [comment]
thanks @anders9ustafsson, actually work in Windows forms with dicom 2.0.2 and i would like get dicom image since PAC's, my pac´s that used is Orthanc in debian, i can comunicate with pacs, i can send images and i can display information of patients, but i can´t or don´t know how get dicom image since pac's, in the group https://gitter.im/fo-dicom/fo-dicom has mentionedthat i should use Store SCP, but don´t understand used, you can explain how can get image dicom, regards.
