### ISSUE TITLE
Proposal: DicomElement.Get<T>(int item = -1) index should be 0 by default

### ISSUE THREAD

**Issue by werwolfby** [fo-dicom/fo-dicom#369]
It is abstract [method](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/DicomElement.cs#L41):
```
public override T Get<T>(int item = -1)
```
And almost all overrides do this:
```
if (item == -1) item = 0;
```
Except ```DicomMultiStringElement``` which returns raw string value on -1 when ```T``` is ```string``` or ```object```.
This looks not intuitive, and I suggest to replace it with 0 as default. And do not allow -1 at all.
I understand that this is *breaking changes*, but it will make code cleaner with more intuitive API.

When ```T``` is array ```item``` parameter is not used at all. And I can image that -1 can mean that user didn't provide value at all.

What do you think?

**Comment by anders9ustafsson** [comment]
@werwolfby Sorry for not responding earlier.

I agree that the current solution is sub-optimal. I would like to avoid this breaking change right now, but I'll schedule a fix for the next major release.

**Comment by anders9ustafsson** [comment]
Related to #392.

**Comment by anders9ustafsson** [comment]
See also #491. Given the fact that index -1 is e.g. for multistrings used to get the raw string output, I would consider rejecting this issue for the time being, and eventually come up with a generally applicable solution with more intuitivity.
