### ISSUE TITLE
Ultra Sound dicom file become green tinted

### ISSUE THREAD

**Issue by AdamWtt** [fo-dicom/fo-dicom#370]
Dicom file either save as image or send to SCP, the image will become green tinted.  The file original transfer syntax is JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression

### Expected behavior
exported / saved file as same as the original file.

### Actual behavior
image become green tinted whatever transfer syntax we want to change

### Steps to reproduce the behavior

var dicomFile = DicomFile.Open("JpegLossy.dcm");
dicomFile = dicomFile.ChangeTransferSyntax(DicomTransferSyntax.ExplicitVRLittleEndian);
dicomFile.Save("greentinted.dcm");
ds = dicomFile.Dataset;
image = new DicomImage(ds);
image.RenderImage().AsBitmap().Save("greentinted..jpg");

### fo-dicom version and OS/platform
fo-dicom 2.0.2
Windows 10 64bits
![greentinted](https://cloud.githubusercontent.com/assets/23230110/19958617/a6d23ca8-a1db-11e6-865d-e7096a6c9235.jpg)
![original](https://cloud.githubusercontent.com/assets/23230110/19958622/af71efc0-a1db-11e6-9d74-330e8ab21819.jpg)

**Comment by anders9ustafsson** [comment]
@AdamWtt Have you tested version 3.0.0-beta4? There might be fixes in this version that deal with this issue. And, are you able to upload an anonymized copy of the file for our testing purposes?

**Comment by anders9ustafsson** [comment]
@AdamWtt Do you have a file, or link to a file, that we can test?

**Comment by hashitha** [comment]
@anders9ustafsson  I think this could be related to the same issue as #358

**Comment by anders9ustafsson** [comment]
@hashitha Yes, I am thinking so too. Would be good to have the file to test though. I hope @AdamWtt can spare it :-)

**Comment by aerik** [comment]
In fo-dicom 2.0.2 I had the same problem, and I believe it had to do with image data being YBR(whatever) and not being converted to RGB.  I'm sorry I don't remember what I did to fix it, but I think 3.0.x doesn't have this problem.

**Comment by anders9ustafsson** [comment]
Since we currently have no test material, I will close this issue for now. @AdamWtt if you eventually can provide an anonymized test file, please feel free to attach it here and re-open the issue.

**Comment by AdamWtt** [comment]
First of all, sorry for my belated reply as I desperated to source alternative solution.  Also, thanks all the reply and advices here!  Regarding the issue, it is fixed by 3.0.0 without any code changed.  A million thanks for fo-dicom and all contributors.....
