### ISSUE TITLE
unhandled IO exception while reading PDU

### ISSUE THREAD

**Issue by azzurro1971** [fo-dicom/fo-dicom#371]
I do a DicomCStoreRequest to a remote SCP.
Sometimes, when there are network problems, the program stops with a "IO exception while reading PDU".
Although i run the C-Store in a try/catch block, the exception is not handled.
Am i doint something wrong?
How can i handle the IO exception correctly?

### fo-dicom version and OS/platform
v3.0.0-beta1 Universal Windows platform

**Comment by anders9ustafsson** [comment]
@azzurro1971 Are you really using *Beta 1*? Please try *Beta 4* instead. There are recent changes that allows you to access the exception via the [`IDicomServer` API](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Network/IDicomServer.cs).

**Comment by ztegod** [comment]
@azzurro1971 You can try to output the exception instead of catching it.In #365 ,you can follow the codes to output your exception by using NLogManager and memory target to output the exception and change NLog.LogLevel to error message.

**Comment by anders9ustafsson** [comment]
@azzurro1971 Please take a look at [this](https://github.com/fo-dicom/fo-dicom/blob/development/Tests/Network/DicomServerTest.cs#L16) unit test, where the `Exception` property of the `IDicomServer` implementation is consumed. This property was added recently and is available in the 3.0.0 Beta 4 pre-release.

With this information, I will consider this issue resolved. If you fail to make sufficient use of the `Exception` property for these purposes, please add detailed information on what is missing and re-open the issue.
