### ISSUE TITLE
Incorrect message logged when async ops are not avaiable, but requested

### ISSUE THREAD

**Issue by Corvin666** [fo-dicom/fo-dicom#374]
### Expected behavior
Here is the exception:

```
throw new DicomNetworkException(
                            "Cannot send messages since pending: {pending} would exceed max async ops invoked: {invoked}",
                            _pending.Count,
                            Association.MaxAsyncOpsInvoked);
```

### Actual behavior

Here is what gets logged:

Exception processing PDU: System.FormatException: **Input string was not in a correct format**.
at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
at System.String.Format(String format, Object[] args)
at Dicom.Network.DicomService.SendNextMessage() in C:\Users\ander\Documents\Visual Studio 2015\Projects\fo-dicom [fo-dicom]\DICOM\Network\DicomService.cs:line 900
.......

This happens because the string with name formatting and argument list gets passed, through DicomNetworkException constructor to this:

`protected DicomException(string format, params object[] args)
            : this(String.Format(format, args))
        {
        }`

Here, String.Format throws because of malformed format string, masking the original exception.

I think either string should be changed in the original exception or DicomException constructor needs to be changed to use the NameFormatToPositionalFormat method of Logger abstract class, or something like this.

### fo-dicom version and OS/platform
3.0.0-beta4

Windows, desktop

**Comment by anders9ustafsson** [comment]
@Corvin666 Thanks for looking into this. I have seen it before but it is very good that you took the time to investigate and file an issue report. Will try to correct this as soon as possible.
