### ISSUE TITLE
Unity raw pixels data

### ISSUE THREAD

**Issue by mpmartimbianco** [fo-dicom/fo-dicom#376]
Hi, and I'm sorry if I post it in the wrong place.

I'm trying to use the fo-dicom in the unity engine, when I discovered this project and I saw that the project have a unity version I thing that is the best option for my project here, I start compiling the "DICOM.Unity.sln" to use the dll in my unity project, and till here everything works fine. But now trying to implement my code I have some issues and I have some questions if you can help me.

First, I already saw it in the asset store, but it is expensive for me right now. I start trying to use .as<Texture2D> from DicomImage but I received some exceptions about no-codecs and I assume this fo-dicom unity version do not support this. Lokking the DICOM.Unity solution I was supposed that I can script the missing part of the free version to create a texture2D from raw data myself.

One question is about it, can I create my self script to generate a texture2D myself or only with the asset store package allow me it?

I question it because after try to create myself, still can't do it works. I assume that I can set the pixels of texture2D setting the pixel with the pixels from IPixelData like the sample of how to get raw pixel data in this wiki. Just need to convert the short or ushort to 0-255 to create the color. And when I tried to loop through all columns and rows a exception told me that the index is out of range, but I suppose that it is not giving me all values because for example it get about 279053 values in array, but I think that must be more values, because rows and columns are 776*776 in this case.

I don't know why of this, if I need to make it with other way or maybe I'm doing something wrong and I can't see it.

Thanks.

**Comment by anders9ustafsson** [comment]
@mpmartimbianco You should be able to create your own implementation of `IImage` and `IImageManager` for Unity's `Texture2D`. Since implementations are invoked via assembly reflection, you should add your implementations to your own build of Unity *fo-dicom*.

**Comment by mpmartimbianco** [comment]
Hello, thanks for the answer.
Indeed I was trying to convert to Texture2D getting the raw pixel data that I saw in your wiki, like:

`var header = DicomPixelData.Create(dataset);`
`var pixelData = PixelDataFactory.Create(header, idx);`

and using a method I created in the C# inside my unity project itself to convert each pixel and uses `Texture2D.SetPixels()` to populate it.

Trying with the dicom image that I said before, the pixelData returns me 279053 pixels instead of 602176 I supposed to be (776*776).

Testing with another dicom file of 512x512 it returns the right amount of 262144, so it I can handle and create a new Texture2D.
If do I implement inside my Unity fo-dicom soluction it will works properly? Because of this difference values I don't understant exactily what I'm doing wrong.

Thanks for the help.

I added two images to exemplify my problem:
![001](https://cloud.githubusercontent.com/assets/10996602/21183992/8f077576-c1f1-11e6-89a4-b5f4848cf925.png)
![002](https://cloud.githubusercontent.com/assets/10996602/21183993/8f0a159c-c1f1-11e6-9794-ea5c26e7b7d3.png)

**Comment by anders9ustafsson** [comment]
@mpmartimbianco The lesser number of pixels indicates that you might use an encapsulated DICOM image format, for example JPEG. Encapsulated codecs such as JPEG, JPEG-LS and JPEG2000 are currently not supported on Unity, only RLE is supported along with implicit/explicit little/big endian.

**Comment by tolstenko** [comment]
I realy want to help supporting those compressed data from gdcm to fo-dicom, but it is a very difficult task.

We have this task in our to-do list, but no dev wants to do it :-/.

Since our dicom editor only runs on desktops (win, linux and osx), for compressed dicom support, we use the gdcmconv to convert to uncompressed dicom using something similiar to this: 

```
Process process = new Process();
#if UNITY_EDITOR_WIN || UNITY_STANDALONE_WIN
        process.StartInfo.FileName = Path.Combine(StreamingAssetsPath, "gdcmconv.exe");
// #elif ... 
//...
#endif
process.StartInfo.Arguments = " -w -i \"" + path + "\" -o \"" + path + "_\"";
process.StartInfo.ErrorDialog = true;
process.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
process.Start();
process.WaitForExit();
try
{
  if (File.Exists(path))
    File.Delete(path);
  File.Move(path + "_", path);
}
catch (Exception e)
{
  Debug.LogError(e.Message);
 }
```

In the WebGL, iOS and Android, we use uncompressed or pre-processed data.

**Comment by mpmartimbianco** [comment]
@anders9ustafsson  Ah OK, I understood now, I read before that in unity compressed data is not supported, but I thought that with raw data I could convert myself to the Texture2D, I thought that at least with raw data I would have, you now, my mistake, sorry. I suppose the fo-dicom of asset store can't convert it as well.

@tolstenko my application is for desktops only, its a idea, maybe I use a external converter like this if can't convert it myself.

Thank you guys. I'm new in the community/github and dicom-things, thanks for your patience.
