### ISSUE TITLE
Can not catch exceptions while doing c-store if i close my network connection

### ISSUE THREAD

**Issue by ztegod** [fo-dicom/fo-dicom#385]
### Expected behavior
 string path = @"C:\Users\Administrator\Desktop\AGECANONIX\AGECANONIX\Specials 1CoronaryCTA_with_spiral _CTA_pre\CorCTA w-c  1.0  B20f - 6";
            string[] files = System.IO.Directory.GetFiles(path);
            var client = new DicomClient();
            foreach (var s in files)
            {
                DicomCStoreRequest d = new DicomCStoreRequest(s);
                d.OnResponseReceived = (r, q) =>
                {
                    Console.WriteLine("{0},{1}", q.RequestMessageID, q.Status);
                };
                client.AddRequest(d);
            }
            client.Send("193.168.4.32", 11112, false, "CT", "STORESCP");//do try catch
### Actual behavior
I have many images to send,however when i break my network during my sending,i cant catch any exception.Then,it just stop there.I hope you can try it. 

### Steps to reproduce the behavior

I tried both in version 2.0.2 and 3.0 beta4 .

**Comment by anders9ustafsson** [comment]
@ztegod Depending on how the connection is broken/closed, the client service may choose to silently return. In particular, if the connection has been closed by an explicit request, no exception would be propagated. What type of connection break are you experiencing?

**Comment by ztegod** [comment]
@anders9ustafsson What i did is to Unplug my cable while sending images to pacs,so that i can simulate the condition that the network in hospital is broken while sending images to pacs.I am not sure if the silently return is a better way?How can i continue to send my images left?Is there any way to do that?I need your help.

**Comment by ztegod** [comment]
@anders9ustafsson By the way ,I can see the exception in log.However i do want to catch the exception instead of writing in log.What i want to know is that if it is designed to be like this,or somewhere i did wrong?

**Comment by anders9ustafsson** [comment]
@ztegod, can you share the log text?

**Comment by ztegod** [comment]
sure，here is my log：
CREALIFE -> Association request:
Calling AE Title:       SCU
Called AE Title:        CREALIFE
Implementation Class:   Implementation Class UID [1.3.6.1.4.1.30071.8]
Implementation Version: fo-dicom 2.0.2
Maximum PDU Length:     16384
Async Ops Invoked:      100
Async Ops Performed:    100
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  CT Image Storage
       Transfer Syntax:  Explicit VR Little Endian
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for
DICOM
CREALIFE <- Association accept:
Calling AE Title:       SCU
Called AE Title:        CREALIFE
Implementation Class:   Unknown [1.2.19.0.740423.1.0.3.0.1]
Implementation Version: CREALIFEDCM20
Maximum PDU Length:     131072
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Accept]
       Abstract Syntax:  CT Image Storage
       Transfer Syntax:  Explicit VR Little Endian
CREALIFE -> C-Store request [1]
CREALIFE <- C-Store response [1]: Success
Success
CREALIFE -> C-Store request [2]
CREALIFE <- C-Store response [2]: Success
Success
CREALIFE -> C-Store request [3]
CREALIFE <- C-Store response [3]: Success
Success
CREALIFE -> C-Store request [4]
CREALIFE <- C-Store response [4]: Success
Success
CREALIFE -> C-Store request [5]
CREALIFE <- C-Store response [5]: Success
Success
CREALIFE -> C-Store request [6]
CREALIFE <- C-Store response [6]: Success
Success
CREALIFE -> C-Store request [7]
CREALIFE <- C-Store response [7]: Success
Success
CREALIFE -> C-Store request [8]
CREALIFE <- C-Store response [8]: Success
Success
CREALIFE -> C-Store request [9]
CREALIFE <- C-Store response [9]: Success
Success
CREALIFE -> C-Store request [10]
CREALIFE <- C-Store response [10]: Success
Success
CREALIFE -> C-Store request [11]
CREALIFE <- C-Store response [11]: Success
Success
CREALIFE -> C-Store request [12]
CREALIFE <- C-Store response [12]: Success
Success
CREALIFE -> C-Store request [13]
CREALIFE <- C-Store response [13]: Success
Success
CREALIFE -> C-Store request [14]
CREALIFE <- C-Store response [14]: Success
Success
CREALIFE -> C-Store request [15]
CREALIFE <- C-Store response [15]: Success
Success
CREALIFE -> C-Store request [16]
CREALIFE <- C-Store response [16]: Success
Success
CREALIFE -> C-Store request [17]
CREALIFE <- C-Store response [17]: Success
Success
CREALIFE -> C-Store request [18]
CREALIFE <- C-Store response [18]: Success
Success
CREALIFE -> C-Store request [19]
CREALIFE <- C-Store response [19]: Success
Success
CREALIFE -> C-Store request [20]
CREALIFE <- C-Store response [20]: Success
Success
CREALIFE -> C-Store request [21]
CREALIFE <- C-Store response [21]: Success
Success
CREALIFE -> C-Store request [22]
CREALIFE <- C-Store response [22]: Success
Success
CREALIFE -> C-Store request [23]
CREALIFE <- C-Store response [23]: Success
Success
CREALIFE -> C-Store request [24]
CREALIFE <- C-Store response [24]: Success
Success
CREALIFE -> C-Store request [25]
CREALIFE <- C-Store response [25]: Success
Success
CREALIFE -> C-Store request [26]
CREALIFE <- C-Store response [26]: Success
Success
CREALIFE -> C-Store request [27]
CREALIFE <- C-Store response [27]: Success
Success
CREALIFE -> C-Store request [28]
CREALIFE <- C-Store response [28]: Success
Success
CREALIFE -> C-Store request [29]
CREALIFE <- C-Store response [29]: Success
Success
CREALIFE -> C-Store request [30]
CREALIFE <- C-Store response [30]: Success
Success
CREALIFE -> C-Store request [31]
CREALIFE <- C-Store response [31]: Success
Success
CREALIFE -> C-Store request [32]
CREALIFE <- C-Store response [32]: Success
Success
CREALIFE -> C-Store request [33]
CREALIFE <- C-Store response [33]: Success
Success
CREALIFE -> C-Store request [34]
CREALIFE <- C-Store response [34]: Success
Success
CREALIFE -> C-Store request [35]
IO exception while writing PDU: System.IO.IOException: Unable to write data to t
he transport connection: A connection attempt failed because the connected party
 did not properly respond after a period of time, or established connection fail
ed because connected host has failed to respond. ---> System.Net.Sockets.SocketE
xception: A connection attempt failed because the connected party did not proper
ly respond after a period of time, or established connection failed because conn
ected host has failed to respond
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResu
lt asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInst
ance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchr
onization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Dicom.Network.DicomService.<SendNextPDUAsync>d__52.MoveNext() in D:\Users\
Anders\Documents\Visual Studio 2013\Projects\fo-dicom [fo-dicom]\DICOM\Network\D
icomService.cs:line 788
Connection closed with error: System.IO.IOException: Unable to write data to the
 transport connection: A connection attempt failed because the connected party d
id not properly respond after a period of time, or established connection failed
 because connected host has failed to respond. ---> System.Net.Sockets.SocketExc
eption: A connection attempt failed because the connected party did not properly
 respond after a period of time, or established connection failed because connec
ted host has failed to respond
   at System.Net.Sockets.Socket.EndSend(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndWrite(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndWriteAsync>b__53_1(Stream stream, IAsyncResu
lt asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInst
ance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchr
onization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Dicom.Network.DicomService.<SendNextPDUAsync>d__52.MoveNext() in D:\Users\
Anders\Documents\Visual Studio 2013\Projects\fo-dicom [fo-dicom]\DICOM\Network\D
icomService.cs:line 788

**Comment by anders9ustafsson** [comment]
@ztegod Is this from *fo-dicom* 2.0.2? In that case, could you please try the same with 3.0.0 Beta 4, because I am surprised if that exception did not propagate on Beta 4.

**Comment by ztegod** [comment]
The log above is in version 2.0.2.After that i tried it in version 3.0.0 beta4,it just the same like version 2.0.2.
By the way because of the format exception,i add the code in #356 :
  DicomServiceOptions options = new DicomServiceOptions();
            options.IgnoreAsyncOps = true;
            client.Options = options;
so that i can do the cstore with mulltiple sendings.

**Comment by ztegod** [comment]
@anders9ustafsson yes,it's in version2.0.2,and it appears no difference in version 3.0.0 beta4

**Comment by anders9ustafsson** [comment]
@ztegod OK, after looking over the code in `DicomService.CloseConnectionAsync`, I believe that a few exceptions may accidentally go unnoticed. I will add this to the to-do list for 3.0. Thanks for reporting!
