### ISSUE TITLE
Adding additional requests in DicomClient does not send on the existing connection.

### ISSUE THREAD

**Issue by BobSter3000** [fo-dicom/fo-dicom#389]
### Expected behavior
V2.02 you could add a request and it would be sent out on the existing connection if still lingering. 

### Actual behavior
In 3.0 beta4 the additional requests to not get sent out.  Another send must be invoked.

### Steps to reproduce the behavior
V2.0.2 DicomClient AddRequest

        public void AddRequest(DicomRequest request)
        {
            if (this.service != null && this.service.IsConnected)
            {
                this.service.SendRequest(request);
            }
            else this.requests.Add(request);
        }

v3.0 beta4.

        public void AddRequest(DicomRequest request) {
            lock (this.locker) {
                this.requests.Add(request);
            }
        }

### fo-dicom version and OS/platform
This was pretty handy with forwarding or routing type applications.

**Comment by anders9ustafsson** [comment]
@BobSter3000 The same principle should work in 3.0 as well, it is only the send logic that has been moved to the private `DicomService` component of the `DicomClient`. I have however made changes in the lingering procedure, and this might explain why you need to call `Send` a second time. Try to configure the `DicomClient.Linger` property to a larger value to see if the connection is kept open sufficiently long for the client to automatically send requests that were added after the first call to `Send`. 

Please let me know whether changing `Linger` does the trick for you or not.

**Comment by BobSter3000** [comment]
@anders9ustafsson Yes, adding the linger and increasing the value does work, thanks.  I cannot seem to find out if the client connection is still connected(lingering).  Is there a way to find this out?  I do appreciate all the work you put into this.

**Comment by anders9ustafsson** [comment]
@BobSter3000 Currently there is no functionality for checking connection status, but I agree, there is definitely a need for this. If it does not turn out to be too complicated, I will consider adding this feature in the upcoming release. Thanks for the suggestion!

**Comment by BobSter3000** [comment]
@anders9ustafsson Yes, I agree the something like DicomClient.IsSendRequired or DicomClient.IsConnected sounds great, thank you.
