### ISSUE TITLE
Fuji Modality CR Truncate Needed

### ISSUE THREAD

**Issue by mohamedwageh011** [fo-dicom/fo-dicom#393]
[MWMHelper]FcFindDDO::AddRecordImageTable()/Execute:0x80040E57
String or binary data would be truncated.
insert into Image07 
(PhysicianName2, PatientName3, StudyTime, StudyDate, PhysicianName3, PatientName2, StudyInstanceUID, 
AccessionNumber, PhysicianName1, PatientName1, PatientID, PatientBirthDate, PatientSex, SPSStartDate, SPSStartTime, 
StudyID, RPDescription, Modality, SPSDescription, SPSID, ProcUID) values 
(N'', N'', N'155516.000', N'20170103', N'', N'', N'1.2.826.0.1.3680043.2.588.1.10001147', N'10001147', N'', 
N'ahmed Hasan Abd el hameed El Refaay', N'     
P1058', N'1979-01-01 00:00:00 ', N'M', N'2017-01-03 15:54:50 ', N'2017-01-03 15:54:50',
 N'1000034', N'X-RAY on bones of the skull', N'CR', 
N'X-RAY on bones of the skull', N'1', N'1.2.392.200036.9125.2.1402202125774196.64830988516.404877')

## I think that (procuid) column is the root cause of the problem i can't detect where from the modality get this number  '1.2.392.200036.9125.2.1402202125774196.64830988516.404877'

**Comment by anders9ustafsson** [comment]
@mohamedwageh011 From your post, it is not clear what your problem is? Please describe the problem in greater detail. Show the code where the problem occurs, and provide an anonymized copy of the DICOM file(s) that are causing the problem.

**Comment by anders9ustafsson** [comment]
@mohamedwageh011 I fail to see that what you have posted is a *fo-dicom* related issue. I will close this issue for now. If you are able to provide more detailed information on what is going wrong and how this relates to *fo-dicom*, please feel free to add this information and re-open the issue.

**Comment by mohamedwageh011** [comment]
Dear Mr Anders,

Sorry for my late reply.

I will collect all details then I post again.

Thanks for your attention.

On 11 Jan 2017 10:52 a.m., "Anders Gustafsson" <notifications@github.com>
wrote:

@mohamedwageh011 <https://github.com/mohamedwageh011> I fail to see that
what you have posted is a *fo-dicom* related issue. I will close this issue
for now. If you are able to provide more detailed information on what is
going wrong and how this relates to *fo-dicom*, please feel free to add
this information and re-open the issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fo-dicom/fo-dicom/issues/393#issuecomment-271812431>,
or mute the thread
