### ISSUE TITLE
Bad encapsulated pixel data can crash FO-Dicom with and Access Violation Exception when using Dicom.Native dlls

### ISSUE THREAD

**Issue by aerik** [fo-dicom/fo-dicom#394]
### Expected behavior
Bad pixel data should be detected before an un-catchable exception occurs

### Actual behavior
Somewhere buried in the Native dlls an error allows a situation resulting in an uncatchable Access Violation exception which completely crashes FO-DICOM

### Steps to reproduce the behavior
Try to decode a file with bad pixel data (I have such a file but need to anonymize it)

### fo-dicom version and OS/platform
3.x Beta Desktop (Windows 10)

**Comment by aerik** [comment]
It seems to occur inside jpeg_read_header in Dicom.Imaging.Codec.Jpeg.I, and I cannot figure out how to follow (get the debugger to go down inside) the stack after that.

(What happens is it goes inside Dicom.Imaging.Codec.jpeg.cpp in this block:
```
try {
	precision = JpegHelper::ScanJpegForBitDepth(oldPixelData);
}
catch (...) {
	// if the internal scanner chokes on an image, try again using ijg
	Jpeg8Codec^ c = gcnew Jpeg8Codec(JpegMode::Baseline, 0, 0);
	precision = c->ScanHeaderForPrecision(oldPixelData);
}
```
in DicomJpegNativeCodec::Decode - it fails ScanJpegForBitDepth and then goes down into 
c->ScanHeaderForPrecision(oldPixelData);
)

The detail message is "Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt."

Here's an anonymized file that causes this error.
[anony.zip](https://github.com/fo-dicom/fo-dicom/files/702844/anony.zip)

**Comment by anders9ustafsson** [comment]
@aerik At least the file you have provided does not contain any pixel data, which would explain why image transcoding "chokes". Following the pixel data tag and value representation specification, there is an invalid length specifier FFFFFFFF and 16 bytes of delimiters and similar. Please examine the original file to see if it contains real pixel data.

**Comment by aerik** [comment]
Mmm... I think this issue Im really tring to present isnt about these
details.  I do have another file, a 12MB file (that probably has pixel
data) but what Im really trying to say is that I think FO-Dicom should not
crash when it receives invalid data.  I would work on the fix (or perhaps
its an enhancement) myself if I could figure out how to chase it in the
debugger.

Best Regards,
Aerik

**Comment by anders9ustafsson** [comment]
@aerik I get your point, but I am not sure how easy it would be to accomplish a generally fail-safe solution. I can probably track down and fix the root cause for the file you sent, but I don't think that fix could guarantee that your other file(s) don´t choke.

**Comment by aerik** [comment]
I see your point.  All the errors Ive encountered in this area were access
violation exceptions in the native dlls.  My guess is its a pointer going
outside allocated memory while scanning the jpeg headers, but its just a
guess.

If we (you) can make the header scanning code more robust, its certainly a
plus.

Ill upload the other file, just to be thorough.

If youll tell me how to get the debugger to go into that code, Ill be glad
to help.

Aerik


On Jan 16, 2017 12:45 PM, "Anders Gustafsson" <notifications@github.com>
wrote:

@aerik <https://github.com/aerik> I get your point, but I am not sure how
easy it would be to accomplish a generally fail-safe solution. I can
probably track down and fix the root cause for the file you sent, but I
don't think that fix could guarantee that your other file(s) don´t choke.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fo-dicom/fo-dicom/issues/394#issuecomment-272958305>,
or mute the thread

**Comment by anders9ustafsson** [comment]
@aerik I am no expert myself in mixed language debugging, but if I understand correctly you need to set the C/C++ debugging properties to mixed mode. I'll check for it and come back. Any help is of course much appreciated.

**Comment by anders9ustafsson** [comment]
@aerik I have now debugged JPEG decoding (set debug mode to *Mixed* for all C/C++ libraries, enable native debugging in C# projects) for the faulty image that you sent, and I have been able to find out why you encounter an unhandled exception.

The JPEG C code calls an error handler via ERREXITx macros. When correctly implemented the invoked error handler should of course terminate the en/de-coding. However, in the [current](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM.Native/Dicom.Imaging.Codec.Jpeg.i#L14) *fo-dicom* implementation of the error handler this is not the case. This means that after the ERREXITx function has been called, the en/de-coding simply continues, with potentially corrupt data (like in our case).

As I see it, the `ErrorExit` function should for example `throw`, to ensure that the codec error can be sufficiently handled. I need to give it some thought on how to exactly throw from `ErrorExit`. Please feel free to provide suggestions.

**Comment by aerik** [comment]
Awesome - found the debugging flag and flipped it.  Here's my other file - it looks like this one would also quit with ERREXIT if configured to do so.

I think ERREXIT should throw a catchable exception.

[anony2.zip](https://github.com/fo-dicom/fo-dicom/files/712273/anony2.zip)

**Comment by aerik** [comment]
After following it around for awhile in the debugger I did this:

https://github.com/fo-dicom/fo-dicom/commit/4f11196464863ab01b3545fe5944c48b0811b0b5

seems to get exactly what I'm after.

Looking at the original function, it doesn't seem to actually do anything

```
    // error handler, executes longjmp
    void ErrorExit(j_common_ptr cinfo) {
        ErrorStruct *myerr = (ErrorStruct *)cinfo->err;
    }
```

Does it?

**Comment by anders9ustafsson** [comment]
@aerik That's right, as far as I can tell `ErrorExit` does nothing. Right now I don't know if we can use `throw` or if we need to rely on the C function `longjmp` for correct exception handling? Happy for any input I can get in this matter :-)
