### ISSUE TITLE
question: How to support DICONDE?

### ISSUE THREAD

**Issue by CelerityAbbottPC** [fo-dicom/fo-dicom#395]
### Introduction

DICONDE is a variant of DICOM for use in industrial X-ray and Ultrasoubd imaging.  DICONDE "minimally" modifies DICOM, mainly to map certain DICONDE tags to DICOM tags, and add certain DICONDE IODs that are necessary for industrial X-ray and Ultrasound  imaging.  

Here is a very nice introduction ppt:
https://www.astm.org/COMMIT/DICONDE/dicondeOverivew20110512.pdf

I'm looking to make some changes to fo-DICOM to support DICONDE, mainly on Windows platform, and looking for advise and suggestions. 

Thanks in advance.  Looking forward to any replies.

**Comment by anders9ustafsson** [comment]
@CelerityAbbottPC Many thanks for this proposal.

Does DICONDE use DICOM as a "back-bone" and simply add a set of modules and attributes that are specific to nondestructive testing? Or is there more to it?

If DICONDE only adds a number of tags, then you could add the DICONDE specific tags to *fo-dicom's* dictionary using `DicomDictionary.Load(string filename, DicomDictionaryFormat.XML)`. This method will add tags to the dictionary from a file formatted like [*Private Dictionary.XML*](https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Dictionaries/Private%20Dictionary.xml).

Recently we added support for extending the list of known UIDs as well, the `DicomUID.Register(DicomUID)` method. One example of its usage is given in [this](https://github.com/fo-dicom/fo-dicom/blob/development/Tests/Network/DicomServerTest.cs#L220) unit test. The `Register` method is not yet available in any published NuGet package, but it will be included in *fo-dicom* version 3.0 which is due fairly soon.

**Comment by anders9ustafsson** [comment]
@CelerityAbbottPC By the way, do you have an example DICONDE file? Please feel free to upload it here for further examination.

**Comment by anders9ustafsson** [comment]
@CelerityAbbottPC I found some sample DICONDE images [here](https://www.astm.org/COMMIT/DICONDE_Information.htm). I could open them without problems, and as far as I can tell practically all of the tags in the files are identified by *fo-dicom*. Not sure how much there is in DICONDE that is not already covered in DICOM?

**Comment by anders9ustafsson** [comment]
I hope you have received the answers you need, @CelerityAbbottPC. I will close this issue now. If unanswered questions remain, please re-open the issue and comment.

**Comment by CelerityAbbottPC** [comment]
Hi Anders: Thanks for all the replies and for checking the fo-dicom's DICONDE compatibility.  I had been travelling, right after I posted the issue.  I will look into this more, and provide more feedback.
