### ISSUE TITLE
C++/CLI libraries are targeting .NET 4.5 but lib and sample apps are targeting .NET 4.0

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#4]
With the solution upgrade to VS 2013, the platform toolset for the two C++/CLI projects *DICOM [Native]* and *DICOM [Native64]* was automatically updated to *v120*, which corresponds to .NET Framework 4.5.

The C# projects (class library and sample apps) are still targeting .NET Framework 4.0, which leads to  warnings like these when building sample applications:

> C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3274: The primary reference "...\fo-dicom\DICOM [Native]\x64\..\Debug\Dicom.Native64.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.5" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.0,Profile=Client".

For consistency, we should either:

* Downgrade the platform toolset for the C++/CLI projects to *v110* (.NET 4.0) or lower, or
* Upgrade the C# libraries and sample applications to .NET 4.5.

@hdesouky @GMZ @IanYates and other interested parties: what are your recommendations?

**Comment by IanYates** [comment]
This is a bit of a mixed bag.

I've been in the situation recently where I've had to interface with some ophthalmic OCT equipment that is *still* running on Windows XP.  The DICOM output from this just has the machine dropping some *.dcm files to a folder nominated by the user.

I tend to use async/await throughout my code, and whilst this can work in .NET 4.0, there are some issues.  Fortunately I'm able to just pick up the *.dcm files, throw them up to a WebAPI endpoint, and let some server code (using .NET 4.5) deal with them.

:question: 
With the move to possibly making this library more modular and (at least some of it) portable, is there a significant difference in targeting portable libraries and .NET 4.0 versus portable libraries and .NET 4.5?

:+1: 
If this was just my library, I'd be happy for fo-dicom to move to .NET 4.5.  It would allow us to take better advantage of async/await in future and avoid the Begin/End IAsyncResult pattern. :100: 

:-1: 
However there may be others where having the ability to run on Windows XP is still important.  If that's the case then the library ought to stay with .NET 4.0.  If this is the case then we ought to fix the C++ DLLs.  I'd also suggest we start a separate library containing extension methods which can expose the friendly async abstractions.

I'm aware there is an async targeting pack but I've had trouble with this in the past when trying to use an assembly referencing the async pack from other .NET 4.0 and .NET 4.5 assemblies.

The case could also be made that the library, as it stands now, can still be used for those projects requiring legacy Windows compatibility and if you want whatever improvements come in the future then you have to drop XP support.

**Comment by hdesouky** [comment]
i suggest to have 2 sets of Native libraries:
1 set targets .Net 4
1 set targets .Net 4.5

We can also define 2 solutions, one solution for each framework. This will solve the problem for the time being, but if you want my opinion, such a choices will die sooner than later since XP is already a dead platform and sucking supporting such ice ages will hold us back from getting benefits of latest additions to the .Net framework

what do you think

**Comment by GMZ** [comment]
Guys I've been thinking a lot about this this whole .net 4.0 / 4.5 thing. and Ive had a change of heart......
I'm going to do a complete back flip, lets push everything to 4.5.2 as  @rickardraysearch  mentioned on gitter. and my reason is this. there are forks ( my own for example) that can be left for people stuck with XP support issues. 
I don't know about anyone else but I want to work on fresh new cutting edge stuff outside of work.

**Comment by IanYates** [comment]
@GMZ - flips in any direction are most welcome :)
You're right about trying to get the most enjoyment out of having to do stuff in your spare time.

**Comment by anders9ustafsson** [comment]
If I interpret the discussion correctly, the conclusion is then that we should upgrade the C# libraries and sample applications to .NET 4.5. Anyone still against, make your voice heard :-)
