### ISSUE TITLE
Very large file of color frames crashes FO-DICOM due to casting uint to int

### ISSUE THREAD

**Issue by aerik** [fo-dicom/fo-dicom#402]
### Expected behavior
return the byte array for the data

### Actual behavior
throws an error

### Steps to reproduce the behavior
open a an enormous dicom file with a huge amount of frames, then try to get the pixel data for one of the frames far at the end of the file:  PixelDataFactory.Create(newPix, somebignumber);

The problem happens due to casting uints to ints in the buffer Data property in RangeByteBuffer:

        public byte[] Data
        {
            get
            {
                return Internal.GetByteRange((int)Offset, (int)Length);
            }
        }

inside CompositeByteBuffer's GetByteRange(int offset, int count) method, the offset (and maybe count) are now negative numbers.

### fo-dicom version and OS/platform
3.x Windows 10 Desktop

**Comment by anders9ustafsson** [comment]
@aerik Agreed that this is an issue for very large files. A correction will however require substantial refactoring, so I would like to postpone this fix until the next major release.

**Comment by aerik** [comment]
Yeah, I started to chase it and saw there are ints everywhere, including a limit in Buffer.BlockCopy.

However, in the short term I looked at the math inside CompositeByteBuffer and realized how much the value for offset was going to be manipulated, so I put in a short term fix:

https://github.com/aerik/fo-dicom/commit/bfa2c0a772202d9deae3e28bb82a515334996468

which I tested on some 3000 frame, 200MB files, and it works for those.  Probably won't solve everything, but gets me what I need in the short term.

**Comment by BobSter3000** [comment]
I came across this issue now, when I am trying to create a Multiframe object.  It appears adding frames beyond the uint buffers size are ignored.  The number of frames tag is accurate in the file, but not all the pixel data is written to the file.
