### ISSUE TITLE
Question about applying changed pixel data.

### ISSUE THREAD

**Issue by veriturus** [fo-dicom/fo-dicom#404]
Hi to all again,

My backround is from nuclear medicine and in my spare time I try to code (I'm not very good but am trying).

My question is how can I apply pixeldata, that I have changed (e.g. To zero to mask a region) , to the dataset.

I did search here but got lost.

Thanks all
veriturus

p.s. I hope this not a really stupid question!

**Comment by anders9ustafsson** [comment]
@veriturus Do you have any example of what you are trying to do? There is an example of how you can include a bitmap into a new DICOM file [here](https://gist.github.com/mdubey82/4030263), if that is of any help.
