### ISSUE TITLE
Issue with new buffered writing in DicomWriter

### ISSUE THREAD

**Issue by aerik** [fo-dicom/fo-dicom#405]
### Expected behavior
Write a DicomFile without crashing

### Actual behavior
Sometimes fails with error caused by bad value passed to EvenLengthBuffer.GetByteRange (and then into Buffer.BlockCopy)

### Steps to reproduce the behavior
Tough to say - happens to me pretty frequently.

### fo-dicom version and OS/platform
3.x Windows 10

**Comment by aerik** [comment]
More detail:  Inside this block of code

```
       private static void WriteBuffer(IByteTarget target, IByteBuffer buffer, uint largeObjectSize)
        {
            int offset = 0;
            uint remainingSize = buffer.Size;

            while (remainingSize > largeObjectSize)
            {
                var range = buffer.GetByteRange(offset, (int)largeObjectSize);
                target.Write(range, 0, largeObjectSize);

                offset += (int)largeObjectSize;
                remainingSize -= largeObjectSize;
            }
            target.Write(buffer.GetByteRange(offset, (int)remainingSize), 0, remainingSize);
        }
```
the buffer variable may be an EvenLengthBuffer - if it is, it's Size property returns the size of the it's underlying buffer plus 1 (don't know why), so remainingSize can be set to a value larger than what is actually left in the buffer.  When this gets passed into GetByteRange and then into Buffer.BlockCopy, an exceptionp is thrown (because we are trying to copy more bytes than there are in the EvenLengthBuffer's underlying buffer).

I solved it by doing this inside GetByteRange in EvenLengthBuffer

```
        public byte[] GetByteRange(int offset, int count)
        {
            byte[] data = new byte[count];
            count = Math.Min((int)(Buffer.Size - offset), count);
            System.Buffer.BlockCopy(Buffer.Data, offset, data, 0, count);
            return data;
        }
```

Maybe there is a more elegant solution elsewhere, but I don't really understand the purpose and function of EvenLengthBuffer.

**Comment by anders9ustafsson** [comment]
@aerik No, it is not clear to me either why `Size` always returns underlying buffer length + 1, but I will investigate further. Many thanks for reporting and for providing a solution proposal.
