### ISSUE TITLE
Encoding greyscale image to JpegLS with default parameters does not work

### ISSUE THREAD

**Issue by aerik** [fo-dicom/fo-dicom#416]
### Expected behavior
Greyscale image is encoded to JpegLS

### Actual behavior
"ParameterValueNotSupported" exception is thrown

### Steps to reproduce the behavior
try to encode a greyscale image (having no Planarconfiguration specified, which it should not have) using null for the encoding parameters

### fo-dicom version and OS/platform

3.x Windows 10

**Comment by aerik** [comment]
Inside jpegstreamreader.cpp a the function CheckParameterCoherent is called.  When the parameter has one component, it looks for the parameter member "ilv" (which sort of maps to planarconfiguration" to be "InterleaveMode::None" - when it isn't, it returns an error.

The interleave mode gets set to InterleaveMode::Line as a default value at line 66 of JpegLS.cpp in Dicom.Imaging.Codec, so it fails.

I don't really understand why there are three values for InterleaveMode instead of only two, but obviously the current setup doesn't work.

**Comment by anders9ustafsson** [comment]
@aerik Many thanks for detecting this! I did a lot of experimenting with color images in PR #379, but apparently forgot to confirm the validity for greyscale files.

Will fix!
