### ISSUE TITLE
Failure to decompress specific JPEG2000 files

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#42]
*Initially reported to Google Groups by Christoph Ernst on July 12, 2015:*

Hello all,

i use the latest version(1.1.0.0 with NLOG) and ChangeTransferSyntax to decompress DICOM files and send them to a DICOM SCP.
Unfortunately the decompression does not work on some files.

Here is my code:

    df = DicomFile.Open(filename);
    df = df.ChangeTransferSyntax(DicomTransferSyntax.ImplicitVRLittleEndian);

On some files i get the error message "Requested 1599034185 bytes past end of file" when opening the file. I guess there is a problem with broken sequences in the file? I tried several DICOM tools and all of them were able to open the image, but not FO DICOM. How can i work around this problem?

A second problem is when decompressing certain JPEG2000 compressed files. At the point when it comes to the decompression, nothing happens. The program just stops and does nothing anymore. There is no error message in the log, even if i set the level to "trace".
I attached a [sample file](https://groups.google.com/group/fo-dicom/attach/d91d349d6f1410f0/IM-0001-0001.dcm?part=0.1&authuser=0).
Any solution for this two issues?

Thanks,
Christoph

**Comment by azzurro1971** [comment]
Hello Anders,
the image i attached refers to the second issue i described (the issue with the JPEG2000 compressed image and FO DICOM just stopping and doing nothing).
I also have a sample image for the first issue, but since it is real patient data i can't attach it yet, and after i anonymized it with our PACS the problem was gone. I'll anonymize it manually later and attach the sample then...

Regards,
Christoph

**Comment by azzurro1971** [comment]
Hello Anders,
i anonymized the sample image for the first issue now with a hexeditor. I'll attach it to this post.

![b38cdd11](https://cloud.githubusercontent.com/assets/4483000/8653599/817e3daa-2985-11e5-837f-281ff3a03f28.png)

Thanks.


Christoph.

**Comment by anders9ustafsson** [comment]
Great, many thanks for posting. We'll look into this issue thoroughly before 1.1.0 is released.

**Comment by anders9ustafsson** [comment]
The problem with the *Requested 1599034185 bytes past end of file* error message is moved to a separate issue, #47.

**Comment by anders9ustafsson** [comment]
@azzurro1971 I have now attempted to open and view the [JPEG2000 compressed image](https://groups.google.com/group/fo-dicom/attach/d91d349d6f1410f0/IM-0001-0001.dcm?part=0.1&authuser=0) you uploaded in the *DICOM Dump* tool, and the image is successfully decompressed for viewing.

Could you please verify that the uploaded file is causing you problems in *fo-dicom 1.1.0-rc1* and explain in more detail where the problems occur.

**Comment by azzurro1971** [comment]
Hello Anders,
i wrote a little commandline program that tries to decompress the file.
It works fine with the dll from FO DICOM 1.37, but when i compile the same code with the dll from 1.1.0.0 (The Nlog version) i get an exception. Is something wrong with the code?

Here the code and the exception:

Code:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Dicom;
using Dicom.Imaging;
using Dicom.Imaging.Codec;
using Dicom.Imaging.Codec.Jpeg;
using Dicom.IO;
using Dicom.IO.Buffer;
using Dicom.IO.Reader;
using Dicom.IO.Writer;
using Dicom.Log;
using Dicom.Network;

namespace decomp_jp2k_1._0
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Decompressing file " + args[0]);
            var file = DicomFile.Open(args[0]);

            file = file.ChangeTransferSyntax(DicomTransferSyntax.ExplicitVRLittleEndian);

            file.Save(file + ".decomp");

        }
    }
}


Exception:

Ausnahmefehler: System.TypeInitializationException: Der Typeninitialisierer für
"Dicom.Imaging.Codec.DicomTranscoder" hat eine Ausnahme verursacht. ---> System.
Reflection.ReflectionTypeLoadException: Mindestens ein Typ in der Assembly kann
nicht geladen werden. Rufen Sie die LoaderExceptions-Eigenschaft ab, wenn Sie we
itere Informationen benötigen.
   bei System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   bei System.Reflection.RuntimeModule.GetTypes()
   bei System.Reflection.Assembly.GetTypes()
   bei System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalo
g()
   bei System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(Impo
rtDefinition definition)
   bei System.ComponentModel.Composition.Hosting.DirectoryCatalog.<>c__DisplayCl
ass3.<GetExports>b__2(ComposablePartCatalog catalog)
   bei System.Linq.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   bei System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalG
etExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   bei System.ComponentModel.Composition.Hosting.CatalogExportProvider.InnerCata
logExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition
atomicComposition)
   bei System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCor
e(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`
1& exports)
   bei System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExport
sCore(ImportDefinition definition, AtomicComposition atomicComposition)
   bei System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCor
e(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`
1& exports)
   bei System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(Impor
tDefinition definition, AtomicComposition atomicComposition)
   bei System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExpo
rtsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   bei System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCor
e(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`
1& exports)
   bei System.ComponentModel.Composition.Hosting.CompositionContainer.GetExports
Core(ImportDefinition definition, AtomicComposition atomicComposition)
   bei System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCor
e(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`
1& exports)
   bei System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(Impor
tDefinition definition, AtomicComposition atomicComposition)
   bei System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore(T
ype type, Type metadataViewType, String contractName, ImportCardinality cardinal
ity)
   bei System.ComponentModel.Composition.Hosting.ExportProvider.GetExportsCore[T
](String contractName)
   bei Dicom.Imaging.Codec.DicomTranscoder.LoadCodecs(String path, String search
)
   bei Dicom.Imaging.Codec.DicomTranscoder..cctor()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei Dicom.Imaging.Codec.DicomTranscoder..ctor(DicomTransferSyntax input, Dico
mTransferSyntax output)
   bei Dicom.Imaging.Codec.DicomCodecExtensions.ChangeTransferSyntax(DicomFile f
ile, DicomTransferSyntax syntax, DicomCodecParams parameters)
   bei decomp_jp2k_1._0.Program.Main(String[] args)

**Comment by anders9ustafsson** [comment]
This sounds more like a problem where the (native) codec DLLs are not present or could not be properly read? 

Are you using *NuGet*? In that case, what build configuration are you using, *Any CPU*? For the right codec DLL to load, you need to use either *x64* or *x86* build configuration. If you are using NuGet and building for *Any CPU*, you should have received a warning message about this inconsistency in the build log. Correct?

**Comment by azzurro1971** [comment]
Hello Anders,
you were right, the "any CPU" option was the problem. After i corrected that i was able to decompress the JPEG2000 images.

Sorry for that.

**Comment by anders9ustafsson** [comment]
Great to hear that you got it to work.
