### ISSUE TITLE
How to change DicomDataset.InternalTransferSyntax?

### ISSUE THREAD

**Issue by Zaid-Safadi** [fo-dicom/fo-dicom#427]
### Expected behavior

Hi @anders9ustafsson, when building a DicomDataset (DS) and adding the image binary in code, how can I set the InternalTransferSyntax of the DS so when writing to file or transcoding it uses the correct value?

### Actual behavior

Right now, even when setting the TransferSyntax by adding a DICOM tag using ds.AddOrUpdate<string> for example, that doesn't change what the internal TS is which will be "Explicit VR Little Indian" from constructor.

### Steps to reproduce the behavior

```
DicomDataset ds = new DicomDataset ( ) ;
ds.AddOrUpdate<string> ( DicomVR.UI, DicomTag.TransferSyntaxUID, "1.2.840.10008.1.2.4.50" );
var dsF = new DicomFile ( ds) ;
dsF.FileMetaInfo.TransferSyntax = DicomTransferSyntax.Parse( ds.Get ( DicomTag.TransferSyntaxUID, ds.InternalTransferSyntax.ToString ( ) ) ) ;

dsF.Save ( fullPath ) ;
```
### fo-dicom version and OS/platform
V3.0.0-RC2

**Comment by anders9ustafsson** [comment]
@Zaid-Safadi Do you mean when *fo-dicom* does not perform the encoding itself, but the image is already encoded when you attach it to the dataset? 

Currently the `InternalTransferSyntax` setter is declared `internal` and thus not accessible publicly. It would in principle be easy to declare it `public`, although I need to give some thought to what implications such a change would have. 

If you have additional input on the subject, please feel free to comment.

**Comment by Zaid-Safadi** [comment]
@anders9ustafsson you are exactly right in stating the case, this is when the image is encoded outside of fo-dicom then attaching it to the Dataset.

I also share your concerns with having the InternalTransferSyntax declared as public. Maybe we can provide a specific method that clearly describes the effect of this action "SetTransferSyntax" Or update the Dataset method to check when a DicomTag.TransferSyntaxUID element is set then it automatically updates the InternalTransferSyntax with that element value.

**Comment by anders9ustafsson** [comment]
@Zaid-Safadi Would it suffice to add e.g. a method like this one to the `DicomDataset` API?

    AddOrUpdatePixelData(IByteBuffer, DicomVR, DicomTransferSyntax)

Then we could maintain the `internal` declaration of the `InternalTransferSyntax` setter but still be able to update it in a controlled way.

Does this look feasible? Are there some additional methods that should be added a the same time?

**Comment by Zaid-Safadi** [comment]
I think this is a great solution @anders9ustafsson and will suffice.

Internally I assume this method will do both, set the new element data using the AddOrUpdate and change the InternalTransferSyntax property, right?

If this is the case, then feel free to assign me this one and I'll submit a PR with the update.

**Comment by anders9ustafsson** [comment]
>Internally I assume this method will do both, set the new element data using the AddOrUpdate and change the InternalTransferSyntax property, right?

Yes, that was what I had in mind. OK, then I'll gladly assign you to the task :-) Many thanks for taking it on.

**Comment by halsius** [comment]
I would like to request a re-open for this enhancement request. The option to set InternalTransferSyntax in AddOrUpdatePixelData is good enough for a lot of usecases. However, when dealing with multiframe SOPs this method can not be used as the data need to be added in fragment sequences. Is there a chance we could have a direct DicomDataset.UpdateInternalTransferSyntax(DicomTransferSyntax) method on  or release the internal restriction on the property?

To get around this without recompiling the library I currently write the constructed DicomFile to disk and re-read it (as that will set the InternalTS to the the FileMetaInfo TS).

**Comment by anders9ustafsson** [comment]
@halsius Please create a new issue describing your specific request.

**Comment by WernMich** [comment]
`AddOrUpdatePixelData `is marked as deprecated now. How can I exchange the transfer syntax UID in case of changed pixel data in a DICOM video? E.g. a MPEG-2 video is exported and converted to H.264 video and this replaces the "old" pixel data. So I want to do the same which was possbile with `AddOrUpdatePixelData `but is not possible with `DicomPixelData.AddFrame(...)` method, because I could not change the transfer syntax to MPEG-4.
