### ISSUE TITLE
Deploy error for Unity based applications on Hololens

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#431]
### Expected behavior
Should be possible to deploy Unity applications with *fo-dicom* on Microsoft Hololens.

### Actual behavior
Deploy error:

> 3>  Failed to fix references for method System.Boolean Dicom.Network.DesktopNetworkManager::IsSocketExceptionImpl(System.Exception,System.Int32&,System.String&)
3>  Failed to fix references for type Dicom.Network.DesktopNetworkManager
3>  System.Exception: Failed to resolve System.Runtime.InteropServices.ExternalException
3>     at Unity.ModuleContext.Retarget(TypeReference type, GenericContext context)
3>     at Unity.ModuleContext.Retarget(MethodReference method, GenericContext context)
3>     at Unity.FixReferencesStep.Visit(MethodDefinition method, GenericContext context)
3>     at Unity.FixReferencesStep.Visit(TypeDefinition type)
3>     at Unity.TypeDefinitionDispatcher.DispatchType(TypeDefinition type)
3>     at Unity.TypeDefinitionDispatcher..ctor(ModuleDefinition module, ITypeDefinitionVisitor visitor)
3>     at Unity.FixReferencesStep.ProcessModule()
3>     at Unity.ModuleStep.Execute()
3>     at Unity.FixReferencesStep.Execute()
3>     at Unity.Step.Execute(OperationContext operationContext, IStepContext previousStepContext)
3>     at Unity.Operation.Execute()
3>     at Unity.Program.Main(String[] args)

### Steps to reproduce the behavior
Deploy application with Unity *fo-dicom* assembly to Microsoft Hololens.

### fo-dicom version and OS/platform
3.0.0, Unity

**Comment by anders9ustafsson** [comment]
The method in question is never invoked in Unity build and should be possible to exclude without implications.

**Comment by bencinStudios** [comment]
This does not appear to have been fixed, or I am missing something.  Still getting 32 errors similar to OP using Unity 5.5.2f1 Personal 64bit  ...  building for HoloLens gives me the following 1st of 32 errors.  When I open the VS project trying to build gives me the another error... see second code block.

`Reference Rewriter found some errors while running with command --target="Temp\StagingArea\Dicom.Core.dll" --additionalreferences="Temp\StagingArea","Temp\StagingArea\Plugins\ARM","Temp\StagingArea\Plugins\X86","Temp\StagingArea\Plugins\X64","Temp\StagingArea\Plugins\ARM","Temp\StagingArea\Plugins\X64","Temp\StagingArea\Plugins\X86","Temp\StagingArea\Plugins\X64","Temp\StagingArea\Plugins\X86","Temp\StagingArea\Plugins\X86","C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Facade","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Calls.CallsVoipContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.SocialInfo.SocialInfoContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.DevicesLowLevelContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.Printers.PrintersContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.FoundationContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Foundation.UniversalApiContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Graphics.Printing3D.Printing3DContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Networking.Connectivity.WwanContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Services.Store.StoreContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.System.Profile.ProfileHardwareTokenContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.System.Profile.ProfileSharedModeContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.UI.ViewManagement.ViewManagementViewScalingContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Activation.ActivatedEventsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Activation.ActivationCameraSettingsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Activation.ContactActivatedEventsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Activation.WebUISearchActivatedEventsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Background.BackgroundAlarmApplicationContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Calls.Background.CallsBackgroundContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Calls.LockScreenCallContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.FullTrustAppContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Preview.Notes.PreviewNotesContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Resources.Management.ResourceIndexerContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Search.Core.SearchCoreContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Search.SearchContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.StartupTaskContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Wallet.WalletContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.Custom.CustomDeviceContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.Portable.PortableDeviceContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.Printers.Extensions.ExtensionsContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.Scanners.ScannerDeviceContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.Sms.LegacySmsApiContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Gaming.Preview.GamesEnumerationContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Globalization.GlobalizationJapanesePhoneticAnalyzerContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Management.Deployment.Preview.DeploymentPreviewContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Management.Orchestration.OrchestrationContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Management.Workplace.WorkplaceSettingsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Media.Capture.AppCaptureContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Media.Capture.CameraCaptureUIContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Media.Devices.CallControlContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Media.MediaControlContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Media.Playlists.PlaylistsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Media.Protection.ProtectionRenewalContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Networking.NetworkOperators.LegacyNetworkOperatorsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Networking.Sockets.ControlChannelTriggerContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Perception.Automation.Core.PerceptionAutomationCoreContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Security.EnterpriseData.EnterpriseDataContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Security.ExchangeActiveSyncProvisioning.EasContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Services.Maps.GuidanceContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Services.Maps.LocalSearchContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.System.Profile.SystemManufacturers.SystemManufacturersContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.System.Profile.ProfileRetailInfoContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.System.UserProfile.UserProfileContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.System.UserProfile.UserProfileLockScreenContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.UI.ApplicationSettings.ApplicationsSettingsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.UI.Core.AnimationMetrics.AnimationMetricsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.UI.Core.CoreWindowDialogsContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.UI.Xaml.Hosting.HostingContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Web.Http.Diagnostics.HttpDiagnosticsContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.System.SystemManagementContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.Calls.CallsPhoneContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract\2.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Devices.SmartCards.SmartCardEmulatorContract\3.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Embedded.DeviceLockdown.DeviceLockdownContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Networking.NetworkOperators.NetworkOperatorsFdnContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Phone.PhoneContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.Phone.StartScreen.DualSimTileContract\1.0.0.0","C:\Program Files (x86)\Windows Kits\10\References\Windows.UI.WebUI.Core.WebUICommandBarContract\1.0.0.0" --platform="C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Facade\Windows.winmd" --support="Temp\StagingArea\WinRTLegacy.dll" --supportpartialns=Unity.Partial --system=System --dbg=pdb --lock=UWP\project.lock.json --alt=System.Xml.Serialization;System.Collections,System.Collections.NonGeneric;System.Reflection,System.Reflection.TypeExtensions;System.IO,System.IO.FileSystem;System.Net,System.Net.Primitives;System.Net.Sockets,System.Net.Primitives;System.Xml,System.Xml.XmlDocument;<winmd>,Windows.winmd;<winmd>,Windows.ApplicationModel.Calls.CallsVoipContract.winmd;<winmd>,Windows.ApplicationModel.SocialInfo.SocialInfoContract.winmd;<winmd>,Windows.Devices.DevicesLowLevelContract.winmd;<winmd>,Windows.Devices.Printers.PrintersContract.winmd;<winmd>,Windows.Foundation.FoundationContract.winmd;<winmd>,Windows.Foundation.UniversalApiContract.winmd;<winmd>,Windows.Graphics.Printing3D.Printing3DContract.winmd;<winmd>,Windows.Networking.Connectivity.WwanContract.winmd;<winmd>,Windows.Services.Store.StoreContract.winmd;<winmd>,Windows.System.Profile.ProfileHardwareTokenContract.winmd;<winmd>,Windows.System.Profile.ProfileSharedModeContract.winmd;<winmd>,Windows.UI.ViewManagement.ViewManagementViewScalingContract.winmd;<winmd>,Windows.ApplicationModel.Activation.ActivatedEventsContract.winmd;<winmd>,Windows.ApplicationModel.Activation.ActivationCameraSettingsContract.winmd;<winmd>,Windows.ApplicationModel.Activation.ContactActivatedEventsContract.winmd;<winmd>,Windows.ApplicationModel.Activation.WebUISearchActivatedEventsContract.winmd;<winmd>,Windows.ApplicationModel.Background.BackgroundAlarmApplicationContract.winmd;<winmd>,Windows.ApplicationModel.Calls.Background.CallsBackgroundContract.winmd;<winmd>,Windows.ApplicationModel.Calls.LockScreenCallContract.winmd;<winmd>,Windows.ApplicationModel.FullTrustAppContract.winmd;<winmd>,Windows.ApplicationModel.Preview.Notes.PreviewNotesContract.winmd;<winmd>,Windows.ApplicationModel.Resources.Management.ResourceIndexerContract.winmd;<winmd>,Windows.ApplicationModel.Search.Core.SearchCoreContract.winmd;<winmd>,Windows.ApplicationModel.Search.SearchContract.winmd;<winmd>,Windows.ApplicationModel.StartupTaskContract.winmd;<winmd>,Windows.ApplicationModel.Wallet.WalletContract.winmd;<winmd>,Windows.Devices.Custom.CustomDeviceContract.winmd;<winmd>,Windows.Devices.Portable.PortableDeviceContract.winmd;<winmd>,Windows.Devices.Printers.Extensions.ExtensionsContract.winmd;<winmd>,Windows.Devices.Scanners.ScannerDeviceContract.winmd;<winmd>,Windows.Devices.Sms.LegacySmsApiContract.winmd;<winmd>,Windows.Gaming.Preview.GamesEnumerationContract.winmd;<winmd>,Windows.Globalization.GlobalizationJapanesePhoneticAnalyzerContract.winmd;<winmd>,Windows.Management.Deployment.Preview.DeploymentPreviewContract.winmd;<winmd>,Windows.Management.Orchestration.OrchestrationContract.winmd;<winmd>,Windows.Management.Workplace.WorkplaceSettingsContract.winmd;<winmd>,Windows.Media.Capture.AppCaptureContract.winmd;<winmd>,Windows.Media.Capture.CameraCaptureUIContract.winmd;<winmd>,Windows.Media.Devices.CallControlContract.winmd;<winmd>,Windows.Media.MediaControlContract.winmd;<winmd>,Windows.Media.Playlists.PlaylistsContract.winmd;<winmd>,Windows.Media.Protection.ProtectionRenewalContract.winmd;<winmd>,Windows.Networking.NetworkOperators.LegacyNetworkOperatorsContract.winmd;<winmd>,Windows.Networking.Sockets.ControlChannelTriggerContract.winmd;<winmd>,Windows.Perception.Automation.Core.PerceptionAutomationCoreContract.winmd;<winmd>,Windows.Security.EnterpriseData.EnterpriseDataContract.winmd;<winmd>,Windows.Security.ExchangeActiveSyncProvisioning.EasContract.winmd;<winmd>,Windows.Services.Maps.GuidanceContract.winmd;<winmd>,Windows.Services.Maps.LocalSearchContract.winmd;<winmd>,Windows.System.Profile.SystemManufacturers.SystemManufacturersContract.winmd;<winmd>,Windows.System.Profile.ProfileRetailInfoContract.winmd;<winmd>,Windows.System.UserProfile.UserProfileContract.winmd;<winmd>,Windows.System.UserProfile.UserProfileLockScreenContract.winmd;<winmd>,Windows.UI.ApplicationSettings.ApplicationsSettingsContract.winmd;<winmd>,Windows.UI.Core.AnimationMetrics.AnimationMetricsContract.winmd;<winmd>,Windows.UI.Core.CoreWindowDialogsContract.winmd;<winmd>,Windows.UI.Xaml.Hosting.HostingContract.winmd;<winmd>,Windows.Web.Http.Diagnostics.HttpDiagnosticsContract.winmd;<winmd>,Windows.System.SystemManagementContract.winmd;<winmd>,Windows.ApplicationModel.Calls.CallsPhoneContract.winmd;<winmd>,Windows.ApplicationModel.CommunicationBlocking.CommunicationBlockingContract.winmd;<winmd>,Windows.Devices.SmartCards.SmartCardBackgroundTriggerContract.winmd;<winmd>,Windows.Devices.SmartCards.SmartCardEmulatorContract.winmd;<winmd>,Windows.Embedded.DeviceLockdown.DeviceLockdownContract.winmd;<winmd>,Windows.Networking.NetworkOperators.NetworkOperatorsFdnContract.winmd;<winmd>,Windows.Phone.PhoneContract.winmd;<winmd>,Windows.Phone.StartScreen.DualSimTileContract.winmd;<winmd>,Windows.UI.WebUI.Core.WebUICommandBarContract.winmd --ignore=System.IConvertible,mscorlib.
Error: method `System.Reflection.Assembly System.Type::get_Assembly()` doesn't exist in target framework. It is referenced from Dicom.Core.dll at System.String Dicom.DicomImplementation::GetImplementationVersion().
Error: method `System.Reflection.Assembly System.Type::get_Assembly()` doesn't exist in target framework. It is referenced from Dicom.Core.dll at System.Collections.Generic.IEnumerable`1<System.Reflection.Assembly> Dicom.Setup::GetPlatformAssemblies().
Error: method `System.Boolean System.Type::get_IsAbstract()` doesn't exist in target framework. It is referenced from Dicom.Core.dll at System.Boolean Dicom.Setup/<>c__1`1::<GetSinglePlatformInstance>b__1_1(System.Type).
Error: method `System.Boolean System.Type::get_IsAbstract()` doesn't exist in target framework. It is referenced from Dicom.Core.dll at System.Boolean Dicom.Setup/<>c__2`1::<GetDefaultPlatformInstance>b__2_1(System.Type).
Error: method `System.String System.Environment::get_MachineName()` doesn't exist in target framework. It is referenced from Dicom.Core.dll at System.String Dicom.Network.DesktopNetworkManager::get_MachineNameImpl().
Error: method `System.Net.NetworkInformation.NetworkInterface[] System.Net.NetworkInformation.NetworkInterface::GetAllNetworkInterfaces()` doesn't exist in target framework. It is referenced from Dicom.Core.dll at System.Boolean Dicom.Network.DesktopNetworkManager::TryGetNetworkIdentifierImpl(Dicom.DicomUID&).
Error: method `System.Int32 System.Net.NetworkInformation.NetworkInterface::get_LoopbackInterfaceIndex()` doesn't exist in target framework. It is referenced from Dicom.Core.dll at System.Boolean Dicom.Network.DesktopNetworkManager::TryGetNetworkIdentifierImpl(Dicom.DicomUID&).
Error: type `System.Net.NetworkInformation.OperationalStatus` doesn't exist in target framework. It is referenced from Dicom.Core.dll at System.Boolean Dicom.Network.DesktopNetworkManager::TryGetNetworkIdentifierImpl(Dicom.DicomUID&).
Error: method `System.Net.NetworkInformation.OperationalStatus System.Net.NetworkInformation.NetworkInterface::get_OperationalStatus()` doesn't exist in target framework. It is referenced from Dicom.Core.dll at System.Boolean Dicom.Network.DesktopNetworkManager::TryGetNetworkIdentifierImpl(Dicom.DicomUID&).
Error: type `System.Net.NetworkInformation.PhysicalAddress` doesn't exist in target framework. It is referenced from Dicom.Core.dll at System.Boolean Dicom.Network.DesktopNetworkManager::TryGetNetworkIdentifierImpl(Dicom.DicomUID&).
Error: method `System.Net.NetworkInformation.PhysicalAddress`

Trying to build the VS output solution:

`Severity	Code	Description	Project	File	Line	Suppression State
Error		The command ""E:\Projects\VS_Output_DicomMedUnity\V0.0.1\Unity\Tools\AssemblyConverter.exe" -platform=uap -lock="E:\Projects\VS_Output_DicomMedUnity\V0.0.1\DicomMedDataVisualizer\project.lock.json" -bits=32 -configuration=Debug -removeDebuggableAttribute=False -uwpsdk=10.0.14393.0 -path="." -path="E:\Projects\VS_Output_DicomMedUnity\V0.0.1\Players\UAP\dotnet\x86\Debug" "E:\Projects\VS_Output_DicomMedUnity\V0.0.1\DicomMedDataVisualizer\Assembly-CSharp.dll" "E:\Projects\VS_Output_DicomMedUnity\V0.0.1\DicomMedDataVisualizer\UnityEngine.dll" "E:\Projects\VS_Output_DicomMedUnity\V0.0.1\DicomMedDataVisualizer\UnityEngine.UI.dll" "E:\Projects\VS_Output_DicomMedUnity\V0.0.1\DicomMedDataVisualizer\Dicom.Core.dll" "E:\Projects\VS_Output_DicomMedUnity\V0.0.1\DicomMedDataVisualizer\UnityEngine.HoloLens.dll" "E:\JesseMedicalHL\Projects\VS_Output_DicomMedUnity\V0.0.1\DicomMedDataVisualizer\UnityEngine.Networking.dll" "E:\Projects\VS_Output_DicomMedUnity\V0.0.1\DicomMedDataVisualizer\UnityEngine.VR.dll"" exited with code 1.	DicomMedDataVisualizer	E:\Projects\VS_Output_DicomMedUnity\V0.0.1\DicomMedDataVisualizer\DicomMedDataVisualizer.csproj	290	
`

**Comment by anders9ustafsson** [comment]
@bencinStudios Thanks for the additional information. Could you please add the full list of errors (e.g. in a zipped text file) in case there is some more information relevant to this problem.

**Comment by bencinStudios** [comment]
@anders9ustafsson thanks for the quick response!  Attached is the Unity Editor log:
[UnityEditorLogDicomFailures05222017.zip](https://github.com/fo-dicom/fo-dicom/files/1019245/UnityEditorLogDicomFailures05222017.zip)

Wish I could be of more help here, if you need anything to expedite the process please let me know.  Thanks!

**Comment by anders9ustafsson** [comment]
OK, I have to admit I had not read the fine print about Hololens and Unity. [Apparently](https://unity3d.com/partners/microsoft/porting-guides) when you target Windows Store those applications are built against .NET Core rather than Mono/.NET 3.5. I could have guessed it of course :-) but I was not aware of this fact until now.

I need to study this issue in finer detail to come up with a solution that works for Hololens/Windows Store. @bencinStudios Is `Texture2D` still the 2D image rendering solution on this particular platform? It is not using the `WriteableBitmap` from UWP, right?

**Comment by bencinStudios** [comment]
@anders9ustafsson yeah, .NET Core is the target for UWP- HoloLens, another wrench in the Unity dev pipeline.  

Texture2D still renders fine on the HoloLens, or at least Unity has the ability to convert to whatever the HoloLens expects at build time.  Sprites work well too - anything that is already in the graphics pipeline seems to play nice.

**Comment by bencinStudios** [comment]
@anders9ustafsson - any update on this?  Sorry to pester you, I have a client who is waiting on the first build.  If there is anything I can do to help, please point me in the right direction and I will jump all over it.  Thanks!!

**Comment by anders9ustafsson** [comment]
@bencinStudios There is a lot going on with Unity at the moment. In particular, they are about to release support for .NET 4.6, which means that the Unity version will be able to support practically all the functionality of the regular class library.

My intention has been to await the official release of the new Unity platform before I make another build for Unity. You might be able to build a Hololens specific version yourself based on the *fo-dicom.Universal* project. Provided you have purchased the license via the *Asset Store* I can even provide you with the source code for the `Texture2D` renderer.  

Alternatively, I can speed development up specifically for your Hololens requirements. I might be able to fit that into my schedule, but then I would like you to consider either subcontracting me for the work, or at least sponsor *fo-dicom* development via the PayPal buttons on the repository's [README](https://github.com/fo-dicom/fo-dicom) page.

**Comment by bencinStudios** [comment]
@anders9ustafsson please reach out to me via email ben.howard@bencinStudios.com  so we can discuss.  Thanks!
