### ISSUE TITLE
DicomClient sends even when the association is rejected

### ISSUE THREAD

**Issue by aerik** [fo-dicom/fo-dicom#433]
### Expected behavior
Do NOT send if the association is rejected

### Actual behavior
Tries to send and fails when there are no valid presentation contexts

### Steps to reproduce the behavior
Try to send a CSTORE to a valid server but nonexistant AE

### fo-dicom version and OS/platform
3 RC2 Windows 10

**Comment by aerik** [comment]
I changed line 395 to 

`                if (send && associateNotifier.Task.IsCompleted && associateNotifier.Task.Result)`

**Comment by anders9ustafsson** [comment]
Many thanks for reporting, @aerik! I have to look more closely tomorrow, but do you mean that the line change solved the issue for you?

**Comment by aerik** [comment]
yes, changing that line solved it for me (I believe associateNotifier.Task.Result is only true when the association was accepted, yes?)
