### ISSUE TITLE
LUT calculation and Window Center

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#439]
*Copied from Sander Dekker's [post](https://groups.google.com/forum/#!topic/fo-dicom/fJhwzT-bn3w) on Google Groups forum*

### Description

I have a DICOM image that I need to save as bitmap for image analysis. I am using fo DICOM 3.0.0.0 and VB.net 4.5.2. Before, I used to use OFFIS DCMTK dcmj2pnm to convert DICOM to bitmap. When I save bitmaps using dcmj2pnm, the background has pixel value 0 according to ImageJ. When I use RenderImage as bitmap and then analyse the output bmp with ImageJ, the background has pixel value 1. The renderoptions are default: 

RescaleIntercept: 0
RescaleSlope: 1
VOILUTFunction: LINEAR

The colorMap tells me that it is completely linear (0 = 0, 1 = 1, etc). 

Please see the attached DICOM image. This is my code:

    Dim dcmImported As New DicomImage(e.Argument.ToString)
    Dim bmpSlice As Bitmap = dcmImported.RenderImage(0).As(Of Bitmap)()

    bmpSlice.Save("C:\Users\sdekker\Documents\IQ\Samples\fodicom\dcm.bmp")

Why does it produce a bitmap image with a different output than dcmj2pnm?

Thanks for your input!

### fo-dicom version and OS/platform
3.0.0

### Attachments
[EXP0018.zip](https://github.com/fo-dicom/fo-dicom/files/776995/EXP0018.zip)

**Comment by anders9ustafsson** [comment]
I have looked at this image, and the problem is how the LUT is calculated based on the image data. According to the image specifications, the *Window Center* is set to 127 and width 256. The LUT is then calculated 128 components before 127, and 128 components starting at 127, which will effectively mean that the data range [-1,254] is assigned greyscale colors [0,255], i.e. a color shift of 1. If the center is changed to 128 in the DICOM image, colors will be correctly assigned.

I would like some more input from the community whether *fo-dicom* should interpret Window Center differently to ensure that colors are assigned as expected in cases like these.

**Comment by gofal** [comment]
http://dicom.nema.org/Dicom/News/april2014/docs_april2014/cp1316_ft.pdf or ftp://dicom.nema.org/MEDICAL/dicom/2014c/output/chtml/part03/sect_C.11.2.html
there it says the following pseudo code:
```
if (x <= c - 0.5 - (w-1)/2), then y = ymin
else if (x > c - 0.5 + (w-1)/2), then y = ymax,
else y = ((x - (c - 0.5)) / (w-1) + 0.5) * (ymax - ymin)+ ymin
```
you say c= 127 and w = 256 and x has value 0:
if x<= 127 - 0.5 - (256-1)/2 = 127 - 0.5 - 127.5 = -1 then y = ymin. That is not the case
else
y = ((x - (127 - 0.5)) / (256-1)  + 0.5) * (255-0) + 0 = ((x - 126.5)/255 + 0.5) * 255 = (x - 126.5) + 127.5 = x+1

So following exactly what dicom standard says, this image should have this color shift of 1. fo-dicom should not change its implementation since it is correct regarding dicom standard.
I am quite surpriced that OFFIS dcmtk obviously has this little error.

**Comment by anders9ustafsson** [comment]
@gofal Many thanks for this thorough investigation. It then seems like there is no apparent reason to change *fo-dicom* because of this. One thing that could be considered is to make it easier to apply a user-defined LUT to the image rendering, if I remember correctly there is currently no obvious way of doing this right now. I'll keep the issue open while confirming this.

**Comment by sdekker90** [comment]
Thanks so much for both your comments. Since we have been using OFFIS previously, I'll have to set the window center to 128 to make images comparable between OFFIS and of-dicom, even though OFFIS uses a non-conformant method.

**Comment by anders9ustafsson** [comment]
@sdekker90 I have now recapitulated LUT application more thoroughly, and there is indeed some support for applying your own LUT or color map. This was an issue already in 1.x, when some users wanted to apply a color map onto a grayscale image, and the same approach should be applicable in your case as well. For details on how to do it, please see [this](https://github.com/fo-dicom/fo-dicom/wiki/LUT-application) wiki page for two alternative methods.

Given that support is already available, I will close this issue now.
