### ISSUE TITLE
Passing custom object to DicomServer

### ISSUE THREAD

**Issue by deyung** [fo-dicom/fo-dicom#440]
I made some mods to my fork that does something like this.

var scp = DicomServer.Create<ServiceProvider>(port, MyObject);

What this allows me to do is to pass in various objects and get it back on association. For instance, I use it to pass in a list of allowed Called AE titles, and on association read from the object for allowed AEs. Without this, the on association method would make calls to DB or what ever source to get the list of AEs which can be a lot of calls for something that doesn't change much. By using a generic object you can transform it back to anything you want and can also make it an optional parameter.

Is this something you would be interested in?

### fo-dicom version and OS/platform
3.0.0+

**Comment by anders9ustafsson** [comment]
Many thanks for bringing this up, @deyung. Would you say your ideas are in some way related to #348 and #242?

**Comment by deyung** [comment]
It is, if you wouldn't mind, I already have it completed and can submit a PR if that is a route you would like to take.

**Comment by anders9ustafsson** [comment]
Please do. Easier to discuss around it when you see the code also :-)

**Comment by anders9ustafsson** [comment]
Since this issue is strongly related to #348 in particular, I will label it a duplicate and close it for now. Please reference #348 for future discussions around this issue.
