### ISSUE TITLE
question: Does fo-dicom support fluoroscopic sequences?

### ISSUE THREAD

**Issue by CelerityAbbottPC** [fo-dicom/fo-dicom#442]
I'd like to learn about how to support fluoroscopic sequences using fo-dicom.  Could anyone give me some pointers?

### fo-dicom version and OS/platform
Windows 10 64bit OS

**Comment by jaime-olivares** [comment]
Can you provide a sample file?

**Comment by gloeb** [comment]
Would also love help with this! I'm trying to get a live fluoroscopy feed to play in Unity, so any advice is appreciated.

**Comment by CelerityAbbottPC** [comment]
I'm trying to get a few fluoroscopic sequences, and hope get them soon.

Thank you in advance for your help !

**Comment by anders9ustafsson** [comment]
@CelerityAbbottPC No files yet? I'll close this issue for now. If you are able to get hold of some files to share, please re-open the issue.
