### ISSUE TITLE
Clone method arguments missing

### ISSUE THREAD

**Issue by sdekker90** [fo-dicom/fo-dicom#444]
Dear reader,

I would like to save my dicom files in uncompressed format (DicomTransferSyntax.JPEG2000Lossless for example). When using the clone method in fo-dicom 3.0, I am not alowed to pass in arguments at all. All I am doing at this point is opening a DicomFile, cloning it and saving it again.

`Dim dcmFileImported As DicomFile = Dicom.DicomFile.Open(e.Argument.ToString)

Dim dcmUncompressed As DicomFile = dcmFileImported.Clone(DicomTransferSyntax.JPEG2000Lossless)

dcmUncompressed.Save("C:\Uncompr.dcm")` 

### fo-dicom version and OS/platform
fo-dicom 3.0.0.0 from NuGet on Windows 10 with Visual Studio 2013

**Comment by jaime-olivares** [comment]
Any compile-time or runtime exception?

**Comment by sdekker90** [comment]
Thanks for your reply. It doesn't even compile since it doesn't accept any parameters. Visual Studio gives me the generic error: Error	72	Too many arguments to extension method 'Public Function Clone() As Dicom.DicomFile' defined in 'Dicom.DicomFileExtensions'.

**Comment by jaime-olivares** [comment]
Are you using the Dicom.Imaging.Codec namespace? There it is the required extension. 
Have a look at:  https://github.com/fo-dicom/fo-dicom/blob/master/DICOM/Imaging/Codec/DicomCodecExtensions.cs

**Comment by sdekker90** [comment]
Thanks that worked.
