### ISSUE TITLE
If the connection is closed by the host, DicomClient will keep trying to send

### ISSUE THREAD

**Issue by aerik** [fo-dicom/fo-dicom#472]
### Expected behavior
If the connection is closed when trying to send, DicomClient should return (from the Send methods)

### Actual behavior
Hangs up in DicomService because TryCloseConnection just returns false if if (_pduQueue.Count > 0 || _msgQueue.Count > 0 || _pending.Count > 0)

### Steps to reproduce the behavior
Try to send a big study to a server and disconnect your network cable

### fo-dicom version and OS/platform
#3.0rc2 (I think) Windows 10

**Comment by aerik** [comment]
I fixed it by doing this - change TryCloseConnection to

```
private bool TryCloseConnection(Exception exception = null, bool forceClose = false)
        {
            try
            {
                if (!IsConnected) return true;

                lock (_lock)
                {
                    if (_pduQueue.Count > 0 || _msgQueue.Count > 0 || _pending.Count > 0)
                    {
                        Logger.Info(
                            "Queue(s) not empty, PDUs: {pduCount}, messages: {msgCount}, pending requests: {pendingCount}",
                            _pduQueue.Count,
                            _msgQueue.Count,
                            _pending.Count);
                        if (forceClose)
                        {
                            _pduQueue.Clear();
                            _msgQueue.Clear();
                            _pending.Clear();
                        }
                        else
                        {
                            return false;
                        }
                    }
                }...
```

And then call it when there is an IOException in SendNextPDUAsync
```
try
                {
                    await _network.AsStream().WriteAsync(buffer, 0, (int)ms.Length).ConfigureAwait(false);
                }
                catch (IOException e)
                {
                    LogIOException(e, Logger, false);
                    TryCloseConnection(e, true);
                }
```

It's interesting - the TCPClient inside the _network object knows it's disconnected, but this is not exposed anywhere, so I have to rely on the exception to know it's disconnected.

**Comment by anders9ustafsson** [comment]
Thanks, @aerik for identifying the issue and proposing a solution! I will have a closer look at it ASAP. 

Regarding [`TcpClient.Connected`](https://msdn.microsoft.com/en-us/library/system.net.sockets.tcpclient.connected.aspx) I did think about using it recently, but ended up not doing so because it did not really do what I want it to do (it reflects the connection state after the last send/receive attempt rather than the current connection state), and because there was no counterpart for it in UWP. But if it eventually turns out that it is a good fit, I can reconsider.
