### ISSUE TITLE
Tag: (0018,6030) not found in dataset

### ISSUE THREAD

**Issue by sdekker90** [fo-dicom/fo-dicom#475]
### Expected behavior
I am trying to read an ultrasound DICOM file. I need the tag 0018,6030 to get the transducer's frequency.  Since the DICOM file I am using has a value for the 0018,6030 tag, I expect fo-dicom to return an unsigned long such as 6000. Other DICOM readers (dcmtk, Ben DICOM viewer, etc.) are able to read this tag from the same file.

### Actual behavior
fo-dicom reports "Tag: (0018,6030) not found in dataset"

### Steps to reproduce the behavior
[Aloka.zip](https://github.com/fo-dicom/fo-dicom/files/830596/Aloka.zip)
Open the attached file and use this function:
`Dim test = dcm.Dataset.Get(Of ULong)(DicomTag.TransducerFrequency)`

### fo-dicom version and OS/platform
3.0.0 on Windows 10 @ .NET 4.5.2

Thanks for your input!

**Comment by anders9ustafsson** [comment]
*Transducer Frequency* is located in the first item of the *Sequence of Ultrasound Regions*. To access the frequency, you need to traverse down the sequence items tree:

    (in C#)
    var test = dcm.Dataset.Get<DicomSequence>(DicomTag.SequenceOfUltrasoundRegions).Items[0].Get<ulong>(DicomTag.TransducerFrequency);

**Comment by sdekker90** [comment]
Thanks very much for your help!
