### ISSUE TITLE
DicomFile.Open  with file encoded by GB18030 fails in .NET Core

### ISSUE THREAD

**Issue by npnelson** [fo-dicom/fo-dicom#481]
### Expected behavior
Using DicomFile.Open on a file with GB18030 encoding in the .NET core should not fail.

### Actual behavior
Fails with:

'GB18030' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.\nParameter name: name", Source: "Dicom.Core", StackTrace: "   at Dicom.DicomFile.Open(IFileReference file, Encoding fallbackEncoding)\n   at Dicom.Network.DicomService.<ProcessPDataTFAsync>d__55.MoveNext()", TargetSite: "Dicom.DicomFile Open(Dicom.IO.IFileReference, System.Text.Encoding)", _typeTag: "DicomFileException"}

### Steps to reproduce the behavior

Use DicomFile.Open to open a file with GB18030 encoding

### fo-dicom version and OS/platform
3.0.1 Windows 10 x64

### Commentary
When running under .NET Core (for any app, not just fo-dicom), GB18030 encoding is not included by default. This can be demonstrated by a simple .NET Core console app:

```
namespace TestEncoding
{
    class Program
    {
        static void Main(string[] args)
        {
            //Encoding.RegisterProvider(CodePagesEncodingProvider.Instance); //uncomment this line to include GB18030 encoding, make sure you also reference System.Text.CodePages Nuget Package
            var enc= Encoding.GetEncoding("GB18030");
            Console.WriteLine("It worked");
            Console.ReadLine();
        }
    }
}
```
This program runs fine under the full .NET framework but fails under .NET Core.

The fix is to add the System.Text.CodePages package and call 
```Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);```
This will add additional encodings, including GB18030

### Potential Fix

Add System.Text.CodePages NuGet package to the DICOM.NetCore project and add a static constructor for DicomEncoding with a conditional compilation for NETSTANDARD that calls ```Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);``` 

### Current Workaround

Add System.Text.CodePages NuGet package to your program that consumes fo-dicom and call Encoding.RegisterProvider while bootstrapping.

### Further action

I'm happy to create a pull request that registers the provider in a static constructor for DICOMEncoding, but before I did, I wanted to make sure the proposed fix is agreeable. I love unit tests, but not sure if one would add much value here.

**Comment by anders9ustafsson** [comment]
Many thanks for reporting and suggesting a sufficient fix, @npnelson! What you propose sounds reasonable, and a pull request would be much appreciated. Please just make sure that you base the PR on the current latest commit in the development branch, since I have recently restructured the repository quite substantially. Also, I have updated the .NET Core projects to use .csproj, so VS 2017 will be necessary.
