### ISSUE TITLE
Cannot create DICOMDIR after anonymizing images

### ISSUE THREAD

**Issue by saviok04** [fo-dicom/fo-dicom#488]
### Expected behavior
Should be able to create a DICOMDIR using the `DicomDirectory` class after anonymizing images using `DicomAnonymiser`.

### Actual behavior
Throws "Element empty or index: 0 exceeds element count: 0".

### Steps to reproduce the behavior
This is how I create the DICOM directory. `

            var studyDir = new DirectoryInfo(path);
            var dicomDirPath = Path.Combine(path, "DICOMDIR");
            var dicomDir = new DicomDirectory();

            foreach (var file in studyDir.GetFiles("*.*", SearchOption.AllDirectories))
            {
                var dicomFile = DicomFile.Open(file.FullName);

                dicomDir.AddFile(dicomFile, file.Name);
            }

            dicomDir.Save(dicomDirPath);`
The anonymizing is done in the C-Store SCP when the requested Dicom files come in.
`DicomAnonymizer anonymiser = new DicomAnonymizer();
                        anonymiser.AnonymizeInPlace(request.Dataset);`

### fo-dicom version and OS/platform
3.0.1 / Windows 10 / .NET 4.5.2

**Comment by anders9ustafsson** [comment]
@saviok04 Thanks for reporting. Can you please provide the stack trace to indicate exactly where the exception is thrown?

**Comment by saviok04** [comment]
@anders9ustafsson The exception is thrown at `DicomDirectory.AddFile()`.

`at Dicom.DicomDataset.Get[T](DicomTag tag, Int32 n, Boolean useDefault, T defaultValue) in C:\fo-dicom\DICOM\DicomDataset.cs:line 461
   at Dicom.DicomDataset.Get[T](DicomTag tag, Int32 n) in C:\fo-dicom\DICOM\DicomDataset.cs:line 117
   at Dicom.Media.DicomDirectory.CreatePatientRecord(DicomDataset dataset) in C:\fo-dicom\DICOM\Media\DicomDirectory.cs:line 584
   at Dicom.Media.DicomDirectory.AddNewRecord(DicomFileMetaInformation metaFileInfo, DicomDataset dataset, String referencedFileId) in C:\fo-dicom\DICOM\Media\DicomDirectory.cs:line 455
   at Dicom.Media.DicomDirectory.AddFile(DicomFile dicomFile, String referencedFileId) in C:\fo-dicom\DICOM\Media\DicomDirectory.cs:line 450
   `

**Comment by anders9ustafsson** [comment]
Great, thanks! Kind of suspected that, but wanted to get it confirmed :-)
