### ISSUE TITLE
dataset.Get<DicomItem>(DicomTag.Parse("00081070")) return an exception'Dicom.DicomDataException:“Tag: (0008,1070) not found in dataset”'

### ISSUE THREAD

**Issue by pyfdrw** [fo-dicom/fo-dicom#493]
### Expected behavior
Expect to get 'null'

### Actual behavior
Dicom.DicomDataException

### Steps to reproduce the behavior
Try to open a dcm file without "OperatorsName" and find data throngh 
`dataset.Get<DicomItem>(DicomTag.Parse("00081070"))` 
Actually, it works fine with v2.0.2. But, I got an exception with v3.0.1 

### fo-dicom version and OS/platform
v3.0.1

**Comment by anders9ustafsson** [comment]
@pyfdrw This is intended behavior in 3.0, see e.g. #474. If you on the other hand request an array, i.e.

    dataset.Get<DicomItem[]>(DicomTag.Parse("00081070"))

you should get an array with zero elements.

**Comment by pyfdrw** [comment]
I used to consider 'DicomItem' as the base class of other entity, such as the 'object' class.
It was changed in 3.0.
I get it, many thanks.

**Comment by jaime-olivares** [comment]
@anders9ustafsson Maybe it would be good to put a xml-doc comment in the code for notifying the developer that this mechanism is by design.

**Comment by anders9ustafsson** [comment]
@jaime-olivares Yes, you are right. I'll try to do something about it soon.
