### ISSUE TITLE
Should a DICOMDIR created from anonymised images retain their Study-Series structure?

### ISSUE THREAD

**Issue by saviok04** [fo-dicom/fo-dicom#497]
### Expected behavior
A DICOMDIR created from anonymised images should retain their Study-Series structure. The image below shows the structure it should have. There are 3 series from a study with 22 images in each series.

![dicomdir](https://cloud.githubusercontent.com/assets/23030327/24243149/f753435e-0fb1-11e7-9d24-28ff7812434d.png)

### Actual behavior
Each image is considered a different study, resulting in 66 studies.

![anonymised dicomdir](https://cloud.githubusercontent.com/assets/23030327/24243221/3e00e6bc-0fb2-11e7-8204-3c93bb16d2d4.png)

### Steps to reproduce the behavior
As I mentioned in #488 , I cannot create DICOMDIR from anonymised images using fo-dicom. So I created the DICOMDIR using Sante Dicom Viewer. The images above are also from Sante Dicom Viewer.

### fo-dicom version and OS/platform
3.0.1 / Windows 10 / .NET 4.5.2

**Comment by jaime-olivares** [comment]
How did you anonymize the dicom files?

**Comment by saviok04** [comment]
@jaime-olivares 
The anonymizing is done in the C-Store SCP when the requested Dicom files come in.
`DicomAnonymizer anonymiser = new DicomAnonymizer(); anonymiser.AnonymizeInPlace(request.Dataset);`

**Comment by jaime-olivares** [comment]
Are you creating a DicomAnonymizer object one per esch dicom file? Or you are reusing the same instance for anonymizing the whole file set?

**Comment by saviok04** [comment]
@jaime-olivares I am creating a DicomAnonymiser object per file that comes in. 

I just changed it and tried it. It works properly now. Thanks for that :)
