### ISSUE TITLE
Control Association in DicomClient

### ISSUE THREAD

**Issue by raise** [fo-dicom/fo-dicom#508]
### Expected behavior
Have  a  method to control when to close Dicom association. Open an association could stay automatically...

### Actual behavior
DicomClient closes associations automatically

### Steps to reproduce the behavior
Assume dicom datasets arriving in unknown intervals at my application, but I would like to send them on, in the same association, to a new target. 

### fo-dicom version and OS/platform
3.0.1 via nuget

**Comment by anders9ustafsson** [comment]
@raise How does this request differ from #507 ?

**Comment by anders9ustafsson** [comment]
@raise What are you looking for that is not already covered by the `DicomClient.Release[Async]` and `DicomClient.Abort` methods?

**Comment by raise** [comment]
@anders9ustafsson I haven't looked into that methods recently to be honest. Was trying to migrate  my applications to fo-dicom, because I like it, but it is too much effort for me right now, so I have to stick to a different toolkit. You can close #508. thanks and keep up the good work

**Comment by anders9ustafsson** [comment]
@raise OK, thanks. Closing this now since the requested functionality most liekly is already included in the library.
