### ISSUE TITLE
CStore-SCU always adds a PC with LEExplicit and LEImplicit 

### ISSUE THREAD

**Issue by Cregganbane** [fo-dicom/fo-dicom#524]
In the RT-Struct modality (Radiotherapy Structure Set), Contours often serialize into a string >64k in length, this means the only reliable transfer syntax(TS) is LEImplicit (the default DICOM TS), since all others use 16 bits to encode the VR length. Currently fo-dicom always adds a presentation context (PC) with LEImplicit and LEExplicit TSs. See DicomPresentationContextCollection.AddFromRequest. This means the SCP is free to choose LEExplicit even though there maybe no way to encode the embedded contours with this TS. (the SCU tries to transcode into LEExplicit and sends a garbled dataset to the SCP)

### Expected behavior
There is away to programmatically pre-configure PCs before sending any SOP instances.   

### Actual behavior
LEImplicit and LEExplicit TSs are always added for each SOPClass encountered in a send batch. 

### fo-dicom version and OS/platform
v2.0.1 (same code in v.3.0.2 but have not repro'd)

**Comment by aerik** [comment]
fwiw, I agree with this.  Having read the concern on Gitter that this might break some implementations, I think FO-Dicom should follow the standard and beyond that allow maximum flexibility.

**Comment by Cregganbane** [comment]
It looks fairly straight forward to factor out the construction of an Association's PresentationContexts in DicomClient.cs and delegate that to an interface impl passed into the constructor. We can make the default do exactly what it does now but provide the option for the caller to construct PCs based upon the send set through this interface. This maybe a bit specific to my issue, but happy to make a PR if you think this is of general value.

**Comment by deyung** [comment]
I've had to comment out the code that added ELE and ILE in the past to make it work with certain SCPs. I believe it's only a couple lines that needs to be commented out.

**Comment by anders9ustafsson** [comment]
Actually, just like @aerik I am in favor of removing the ExplicitLE assignment for better compliance with the standard. As @deyung points out, it would then only be a few lines that needs to be removed/modified. 

@Cregganbane could you present some sample code of what you suggest? It would make it easier to decide whether it is worthwhile, or if we could suffice with a minor modification.

**Comment by Cregganbane** [comment]
@anders9ustafsson I currently have this:
`   

    /// <summary>
    /// Abstracts construction of proposed presentation contexts for a send job 
    /// </summary>
    public interface IPresentationContextBuilder
    {
        /// <summary>
        /// Define the presentation contexts to use in an Association to send the given set of requests.
        /// </summary>
        /// <param name="assocPCs">The association presentation contexts to update</param>
        /// <param name="sendRequests">The list of send requests for this association</param>
        /// <param name="additionalPCs">Any additional PCs specified in DicomClient</param>
        /// <remarks>It is your responsibility to define a set of presentation contexts that minimally cover the SOP Classes in 
        /// the list of data to send. </remarks>
        /// <returns></returns>
        void BuildPresentationContexts(
            DicomPresentationContextCollection assocPCs,
            List<DicomRequest> sendRequests, 
            List<DicomPresentationContext> additionalPCs);
    }

    /// <summary>
    /// A standard implementation of IPresentationContextBuilder
    /// </summary>
    internal class StandardPresentationContextBuilder : IPresentationContextBuilder
    {
        /// <summary>
        /// Inspect the set of requests and add appropriate default presentation contexts. 
        /// </summary>
        /// <param name="assocPCs"></param>
        /// <param name="sendRequests"></param>
        /// <param name="additionalPCs"></param>
        public void BuildPresentationContexts(
            DicomPresentationContextCollection assocPCs,
            List<DicomRequest> sendRequests,
            List<DicomPresentationContext> additionalPCs
        ) {
            foreach (var request in sendRequests)
            {
                assocPCs.AddFromRequest(request);
            }
            foreach (var context in additionalPCs)
            {
                assocPCs.Add(context.AbstractSyntax, context.GetTransferSyntaxes().ToArray());
            }
        }
    }
`

Then in the constructor of DicomClient:
`       

        /// <summary>
        /// Initializes an instance of <see cref="DicomClient"/> using <see cref="StandardPresentationContextBuilder"/>
        /// </summary>
        public DicomClient() : this( new StandardPresentationContextBuilder() )
        {
        }

        /// <summary>
        /// Initializes an instance of <see cref="DicomClient"/> using a custom implementation of using <see cref="IPresentationContextBuilder"/>.
        /// </summary>
        public DicomClient( IPresentationContextBuilder pcBuilder )
        {
            this.requests = new List<DicomRequest>();
            this.AdditionalPresentationContexts = new List<DicomPresentationContext>();
            this.asyncInvoked = 1;
            this.asyncPerformed = 1;
            this.Linger = 50;
            this.presentationContextBuilder = pcBuilder; 
        }
`

Then in InitializeSend:

`        

        private void InitializeSend(Stream stream, string callingAe, string calledAe)
        {
            ...
            this.presentationContextBuilder.BuildPresentationContexts(assoc.PresentationContexts, this.requests, this.AdditionalPresentationContexts);

            ...
       }
`
I then use a trivial implementation of IPresentationContextBuilder with a fixed set of presentation contexts for my app: 

`    

    public class MyPCBuilder : IPresentationContextBuilder
    {
        /// <summary>
        /// We explicitly construct a fixed set of presentation contexts for MR, CT and RT-Struct SopClasses. 
        /// </summary>
        /// <param name="assocPCs"></param>
        /// <param name="sendRequests"></param>
        /// <param name="additionalPCs"></param>
        public void BuildPresentationContexts(DicomPresentationContextCollection assocPCs, List<DicomRequest> sendRequests, List<DicomPresentationContext> additionalPCs)
        {
            assocPCs.Add(DicomUID.CTImageStorage, new[] {
                DicomTransferSyntax.ImplicitVRLittleEndian,
                DicomTransferSyntax.ExplicitVRLittleEndian,
                DicomTransferSyntax.ExplicitVRBigEndian
            });

            assocPCs.Add(DicomUID.MRImageStorage, new[] {
                DicomTransferSyntax.ImplicitVRLittleEndian,
                DicomTransferSyntax.ExplicitVRLittleEndian,
                DicomTransferSyntax.ExplicitVRBigEndian
            });

            assocPCs.Add(DicomUID.RTStructureSetStorage, new[] {
                DicomTransferSyntax.ImplicitVRLittleEndian
            });
        }
    }
`

Its arguable if AdditionalPresentationContexts is now needed. I have also not checked what happens if there is a SopClasss in the data to send  not covered by a custom presentation context.
