### ISSUE TITLE
Custom fields disappearing on save

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#527]
*Reported by Mike Swaim in Google Groups forum [here](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/fo-dicom/wQvdTM_isFw)*.

As part of our workflow, I'm loading DICOM images, anonymizing them using custom IDs (so we can re-identify the patients later), and then saving them. Some of the saved images are much smaller than the originals. Looking at the originals, I see some HOLOGIC tags and data which aren't in my copy. Is there an easy way to include them when I save my changes?

 I'm using the built in anonymizer, and then substituting in my own IDs. 

            Dicom.DicomAnonymizer anony = new Dicom.DicomAnonymizer();
            anony.AnonymizeInPlace(MyFile);

            MyFile.Dataset.AddOrUpdate(Dicom.DicomTag.PatientName, "Anonymous");
            MyFile.Dataset.AddOrUpdate(Dicom.DicomTag.PatientID, m_patient.PatientID.ToString());
            MyFile.Dataset.AddOrUpdate(Dicom.DicomTag.StudyDescription, Encoding.Encode(conn, this.StudyDescription).ToString());
            MyFile.Dataset.AddOrUpdate(Dicom.DicomTag.SeriesDescription, Encoding.Encode(conn, this.SeriesDescription).ToString());

            MyFile.Save(path);

I've included the result file. The original's 26 meg, and groups seems to choke on it.

[after.zip](https://github.com/fo-dicom/fo-dicom/files/964299/after.zip)

### fo-dicom version and OS/platform
3.0.2

**Comment by jaime-olivares** [comment]
I am not sure if this is directly related to the anonymization source code or related to Dataset functionalities. I will take a look at it anyway.

**Comment by anders9ustafsson** [comment]
The default anonymization profile clears and removes quite a lot of tags, see the [standard](http://dicom.nema.org/medical/dicom/current/output/chtml/part15/chapter_E.html), so the compactification after anonymization is probably correct. 

If the anonymization procedure removes an attribute that shouldn't be removed, please re-open this issue and indicate in detail what is not consistent with the standard.
