### ISSUE TITLE
"Cannot access a closed file"

### ISSUE THREAD

**Issue by kratindev** [fo-dicom/fo-dicom#529]
Hi,
I am trying to run CStoreSCP sample. I am sending a dicom file from another server on fellow oak server.  The association is executing successfully, but the program is somehow unable to write the dcm file.

Exception is thrown : "Cannot access a closed file" in the DicomFileWriter.cs class.

Any inputs please?

**Comment by anders9ustafsson** [comment]
We need more information. Which *fo-dicom* version are you running? Please also provide the server log up to and including the point of the exception.

**Comment by anders9ustafsson** [comment]
@kratindev Any update on this? Did you solve the problem?

**Comment by anders9ustafsson** [comment]
Since I have received no clarifying input I am closing this issue now. If you have additional information, feel free to provide it and re-open the issue.
