### ISSUE TITLE
DicomDictionary.GetEnumerator() is very slow

### ISSUE THREAD

**Issue by rickardraysearch** [fo-dicom/fo-dicom#532]
### Expected behavior
DicomDictionary.GetEnumerator() should return an enumerator of the dictionary elements without much overhead.

### Actual behavior
All dictionary elements in _entries are sorted and added to a temporary list. A lock is taken on the masked tags, and the _masked tags are also sorted (if needed) and added to the temporary list. Finally, an enumerator to the new list is created. This is, unsurprisingly, pretty slow.

### fo-dicom version and OS/platform
3.0.2, Windows 10, Visual Studio 2015

**Comment by anders9ustafsson** [comment]
@rickardraysearch I assume the new PR is related to this issue, right? I am not sure if it is related or adds any information, but you might want to look at issue #168 and PR #169 for a discussion on the usage of `lock` in `DicomDictionary`.

**Comment by rickardraysearch** [comment]
Actually the PR #531 is related, but only tangentially. In JsonDicomConverter, there is a lookup of keyword to DicomTag that is done as `DicomDictionary.Default.FirstOrDefault(entry => entry.Keyword == tagstr)`, which becomes incredibly inefficient when that produces a copy of all dictionary entries for every attribute in a json DICOM dataset. I do not think that the lock is the problem, and the masked tag lock is anyway a different from the Default lock.

So, this is a somewhat separate problem from that in #531, which is not fixed there. I'll create a separate issue for that PR.
