### ISSUE TITLE
fo-dicom build error

### ISSUE THREAD

**Issue by yangyi325** [fo-dicom/fo-dicom#539]
### Expected behavior
Firstly I download fo-dicom source codes via github by clone&download.
Ｉ use VS2013 to open the DICOM.Full.sln and build the whole solution.
however, I got the following error like below.
Error	1	Unexpected character '$'	F:\yle\open_source\medical_software\20170524_fo_dicom\fo-dicom-development\DICOM\Serialization\DicomXML.cs	99	38	DICOM.Desktop

The corresponding code is: xmlOutput.AppendLine($@"<InlineBinary>{binaryString}</InlineBinary>");
do I need remove '$'? or can you please upload one new version of fo-dicom which could be built successfully without any error?
thanks.

**Comment by BobSter3000** [comment]
@yangyi325 For the development branch you will need VS2015.  See https://github.com/fo-dicom/fo-dicom/wiki/Build-notes.  I hope this helps.

**Comment by yangyi325** [comment]
@BobSter3000， thank you for your information. In addition, do you know what the OS platform would be used? e.g. Win 7 or Win10?

**Comment by BobSter3000** [comment]
@yangyi325 I have not used 2015 on Windows 7, I have only used it on Windows 10.  I think Windows 7 would work though.

**Comment by anders9ustafsson** [comment]
To confirm @BobSter3000 's assumption, Yes. Windows 7 should be sufficient.
