### ISSUE TITLE
DicomUIDGenerator.Generate UID Collisions (Non-unique UIDs)

### ISSUE THREAD

**Issue by kponziani** [fo-dicom/fo-dicom#546]
In `DicomUIDGenerator.Generate` (`DICOM/DicomUIDGenerator.cs` Line 64), when run in rapid succession, there's a chance that duplicated UIDs will be generated.

### Expected behavior
`Generate()` is expected to provide a unique DICOM UID. It uses the ticks from DateTime to generate the UID.

### Actual behavior
If the ticks value doesn't change (is equal to lastTicks), the ticks value is incremented. This value is used without checking for collision. 

If three UIDs are generated on the same tick:
 1. The first value will use the original tick
 2. The second value will use (tick +1)
 3. The third value will use the original tick

### Steps to reproduce the behavior
1. Put `DicomUIDGenerator.Generate` inside of a `Parallel.ForEach()` loop.
2. Run on a system (such as a server) with high speed computation capabilities (powerful processor, multiple cores, etc.)

### fo-dicom version and OS/platform
This was discovered in version 2.0.2, in Windows 7.

The line potentially causing the problem is here (Changed in Issue #86) : https://github.com/fo-dicom/fo-dicom/blob/2.0.2/DICOM/DicomUIDGenerator.cs#L72

This generator was not an issue in version 1.1.0. When we revert to this version, there are no duplicate UIDs generated. The line where this can be seen is here:
https://github.com/fo-dicom/fo-dicom/blob/1.1.0/DICOM/DicomUIDGenerator.cs#L56

**Comment by gofal** [comment]
I understand that the while and the Sleep(1) in version 1.1.0 is unnecessary. I would replace the lines

if (ticks == lastTicks) ++ticks;
                lastTicks = ticks;

with 
if (ticks <= lastTicks) ticks = lastTicks +1;
lastTicks = ticks;

the situation above would be solved, right?
