### ISSUE TITLE
Parallel C# DicomJpegLsCodecException: Unknown error

### ISSUE THREAD

**Issue by VitoHanoi** [fo-dicom/fo-dicom#549]
Hello there,
First of all, thank you for your huge work ! it is really good job ! Sometimes i am asking myself how my project could progress without your lib;

Im trying to compress Dicom Images in a folder ; I have a

 "forEach" loop
          open the file 

    try
    {
      var myListOfCompressors = new List<IDicomCompressor>();
      myListOfCompressors.Add(new DicomSubsampler((decimal).355));
      myListOfCompressors.Add(new DicomJpegCompressor(0));
      IDicomCompressor[] myDicomCompressors = myListOfCompressors.ToArray();
      var myDicomCompoundCompressor = new CompoundCompressor(myDicomCompressors);
      myDicomFileAfter = myDicomCompoundCompressor.CompressFile(myDicomFileStart);
    }
    catch (Exception myE)
    {
      Trace.WriteLine($"{myFileName} : " + myE);
    }

It is working perfectly and the result is a fixed number of Images already Compressed
Exception tells me which file is already compressed

Im trying to do a parallel.Foreach loop to be faster but I encounter a problem;

 - I have the list of the Image already Compressed
 - I get some random images that cant be compressed (these images number changes each run)

![errorunknown](https://user-images.githubusercontent.com/16385289/27460287-0d14aff0-5807-11e7-8097-ba0694bca816.png)

If you have an idea o help me out, im keen

### Expected behavior

Just have the compressed image that cant be compress again

### Actual behavior

 compressed image that cant be compress again + random images that fail in processing

### Steps to reproduce the behavior

can't put there all my project but my DicomJpegCompressor has

       public DicomJpegCompressor(int inCompressionLevel)
        {
            compressionLevel = inCompressionLevel;
        }

        /// <summary>
        /// compresses the file
        /// </summary>
        /// <param name="inDicomFile">the DicomFile to compress</param>
        public DicomFile CompressFile(DicomFile inDicomFile)
        {
            DicomFile myReturnableFile;
            if (compressionLevel == 0) // if allowed loss is 0 use the lossless codec
            {
                myReturnableFile = inDicomFile.Clone(DicomTransferSyntax.JPEGLSLossless);
            }
            return myReturnableFile;
        }

### fo-dicom version and OS/platform

Im working with fo-dicom 3.0.2 (last stable version) with windows 10, Visual Studio 2017 preview 2.1 (latest). It is a unit test Framework but also in Application Framework
I saw your problem for unit test... https://github.com/fo-dicom/fo-dicom/issues/82
and i think it is linked but too nooby to solve it

Thank you again !
Guillaume

**Comment by bibble235** [comment]
We now have a working solution to the problem and would be grateful for feedback. We have put a monitor around the encode and decode in Dicom.Imaging.Codec.JpegLS.cpp  i.e

```
System::Object^ obj = gcnew System::Object();
Monitor::Enter(obj);
try
{
}
finally
{
    Monitor::Exit(obj);
}

```
Any chance this could make it to the main branch.

**Comment by bibble235** [comment]
Please can you reopen this as it does not work. If you parallel process 50 clone operations the images are corrupted

**Comment by anders9ustafsson** [comment]
@VitoHanoi @bibble235 The `Clone` method is a convenience call for the following code:

    public static DicomFile Clone(this DicomFile file, DicomTransferSyntax syntax, DicomCodecParams parameters = null)
    {
      var transcoder = new DicomTranscoder(file.FileMetaInfo.TransferSyntax, syntax, null, parameters);
      return transcoder.Transcode(file);
    }

Since you are transcoding a large number of images from and to the same syntax (right?), it would be more efficient to initialize the `transcoder` once and for all, and then call `transcoder.Transcode` once for every file. If you do like that, does it make any difference to the encoding error?

**Comment by bibble235** [comment]
Thanks for the tip, will look into this to improve performance. However this doe not resolve the issue which has been raised. Do you agree? 

Currently, the class is a singleton where we use it so we put a lock around the function as a workaround.

**Comment by anders9ustafsson** [comment]
@bibble235 That's right, my suggestion does nothing to overcome the problem raised in the issue. But I have checked the code and it's not obvious to me yet where shared resources come into play. Placing a lock on the `Decode` and `Encode` methods is a solution, but that will effectively make the de/encoding single-threaded, right?

**Comment by bibble235** [comment]
Yeah, I did look at the C++ code but could not uncover the issue easily. We can manage with the lock but it would be nice to fix the issue.

**Comment by anders9ustafsson** [comment]
@VitoHanoi @bibble235 I have added a unit test for checking whether I can provoke the codec error, see pull request #601. However, regardless of whether I call `Clone` or use `DicomTranscoder.Transcode` directly, I cannot make the JPEG-LS codec to fail for a particular image. I will close this issue for now. Please check the unit test added in #601 to see if there is anything there that you do differently when encountering the codec exception.

**Comment by wangning08115** [comment]
Who solved the problem? I also encountered this Error.

“Dicom.Imaging.Codec.DicomJpegLsCodecException”(in mscorlib.dll 中)
“Dicom.Imaging.Codec.DicomJpegLsCodecException 
 Unknown error
