### ISSUE TITLE
I can't get the StringValue,anyoneplease.

### ISSUE THREAD

**Issue by HiProgramLin** [fo-dicom/fo-dicom#550]
![getdicomdatasetitemsstringvalue](https://user-images.githubusercontent.com/29646717/27464726-7d58bdca-5801-11e7-839d-9ffdb67f02da.jpg)

**Comment by HiProgramLin** [comment]
![itemstringvalue](https://user-images.githubusercontent.com/29646717/27464948-e9a41244-5802-11e7-9f94-5f44b62f254d.jpg)

**Comment by anders9ustafsson** [comment]
@HiProgramLin The abstract class `DicomItem` has a number of implementations, and for several of these implementations (e.g. `DicomSequence`) it does not make sense to access a single string value. 

If you want to traverse the entire data tree you could consider implementing an `IDicomDatasetWalker` (see the *DICOM Dump* implementation [here](https://github.com/fo-dicom/fo-dicom/blob/development/Tools/DICOM%20Dump/MainForm.cs#L155-L290) for an example).

Or, if you want to access single known items, you could use the `DicomDataset.Get<T>` overloads, e.g. `dicomDataset.Get<string>(DicomTag.PatientName)`-
