### ISSUE TITLE
Read Private Tags in Dicom Image

### ISSUE THREAD

**Issue by pankajbhatia** [fo-dicom/fo-dicom#554]
Hi,

I am using fo-dicom 2.0 version and I am struggling to read private tags in my dicom file . i am using 

  var Tag = _TagDataset.Get<string>(_TagDataset.GetPrivateTag(DicomTag.FileMetaInformationGroupLength), "");

or

var  Tag = _TagDataset.Get<string>(DicomTag.FileMetaInformationVersion, "");
           
but this is returning empty value but i had tried with Microdom viewer it has value in these tags.

So can anyone tell me how to read private tags because all other tags i am able to read.

Thanks in Advance

**Comment by anders9ustafsson** [comment]
@pankajbhatia Please note that *File Meta Information Group Length* and File Meta Information Version* are **not** private tags, but they are part of the [Part 10 file header information](http://dicom.nema.org/medical/dicom/current/output/chtml/part10/chapter_7.html).

For file storage, this meta information should normally be included in the file, but it is also fairly common that only the DICOM dataset itself is stored. In your case, it seems likely that the meta information is just not included.

Double-check the results with *fo-dicom* version 3.0, which includes some fine-tuning of the meta information handling, and post an anonymized version of your DICOM file here if you want it further checked. (To successfully upload it to Github, put the file in a zip archive.)

**Comment by anders9ustafsson** [comment]
Assuming issue is solved by now. If not, please re-open and provide more details.
