### ISSUE TITLE
ReceivingApplicationEntityTitle and SendingApplicationEntityTitle omitted during Save

### ISSUE THREAD

**Issue by SrividyaTR** [fo-dicom/fo-dicom#563]
### Expected behavior
If a DicomFile contains the tags ReceivingApplicationEntityTitle  and SendingApplicationEntityTitle, 
when this file is loaded and saved as another file, these tags are omitted in the newly saved file.

### Actual behavior
The newly saved file should contain the ReceivingApplicationEntityTitle  and SendingApplicationEntityTitle tags of the original dicom file

### Steps to reproduce the behavior
1. Load a dicomFile (eg: file1.dcm) containing tags ReceivingApplicationEntityTitle  and SendingApplicationEntityTitle
2. Save this into a new dicomFile (eg: file2.dcm)
3. The new dicomFile (file2.dcm) does not contain these 2 tags any more.

### fo-dicom version and OS/platform
fo-dicom version: 3.0.2  
OS/ platform: .NET application on windows OS

**Comment by anders9ustafsson** [comment]
@SrividyaTR Thanks for reporting!

Yes, you are absolutely right, those tags are, **incorrectly**, not part of the `DicomFileMetaInformation` class. 

I will make sure that the meta information class is sufficiently updated in the next release to contain all tags that are mandatory or optional according to the [DICOM Standard](http://dicom.nema.org/medical/dicom/current/output/chtml/part10/chapter_7.html#sect_7.1).
