### ISSUE TITLE
When parsing a DICOM file fails if a privateBadSequence contains a subsequence

### ISSUE THREAD

**Issue by JoostJM** [fo-dicom/fo-dicom#565]
### Expected behavior
When parsing a DICOM file with a general implicit VR, it can occur that it contains a private sequence with explicit VR. In this case, that sequence is marked `privateBadSequence` in `DicomReader.cs` and parsed using the correct explicit VR. However, that sequence can contain subsequences and upon exit of that subsequence, `privateBadSequence` should *not* be reset (this should only occur upon exit of the true `privateBadSequence`.

### Actual behavior
Upon exit of the subsequence, the code sees that `privateBadSequence` is set to `true` and resets it.
If the sequence then contains additional tags, the parsing fails, as it tries to parse explicit VR using an implicit VR setting.

### Steps to reproduce the behavior
No idea, I got the data with an explicit VR sequence in an implicit VR Dicom file, with subsequence in that explicit VR private sequence (this subsequence is not private, and is explicit VR like it's parent).

### Potential fix
Store the sequnce depth (I store it in `privateBadSequenceDepth`) when marking `privateBadSequence` and only reset it if `sequenceDepth == privateBadSequenceDepth`.

### fo-dicom version and OS/platform
3.0.2, OS .NET/Windows 7

**Comment by anders9ustafsson** [comment]
@JoostJM Thanks for reporting. Could you please upload an anonymized copy of a file where you have encountered this problem?

**Comment by JoostJM** [comment]
@anders9ustafsson, I can try, but usually I anonymize using a script I wrote in fo-dicom, so that'll either be unable to load the original, or save an anonymized versions that corrects the cause of the error (i.e. the private sequence will also be stored in implicit VR)

**Comment by anders9ustafsson** [comment]
@JoostJM Yes, using *fo-dicom* for anonymization in this case is probably not a good idea. Maybe use some other tool?

**Comment by JoostJM** [comment]
@anders9ustafsson, I'll give it a try

**Comment by anders9ustafsson** [comment]
@JoostJM Any progress on providing an anonymized sample file?

**Comment by JoostJM** [comment]
@anders9ustafsson, Sorry for the late reply. I was on a holiday and have not yet been able to create an anonymized DICOM file with the problem I described. I'll try to do this asap.

**Comment by JoostJM** [comment]
@anders9ustafsson [here](https://www.dropbox.com/sh/62cpcciik2zq40x/AABJw6yUa0mazfbWoslCZIMaa?dl=0) is a file which has been stripped down, but can serve to reproduce the error I described.

**Comment by JoostJM** [comment]
@anders9ustafsson, if you want, I can make a PR for the bugfix I implemented for my program.

**Comment by anders9ustafsson** [comment]
@JoostJM Thanks, a PR would be very much appreciated!
