### ISSUE TITLE
Exception in DicomImage Object initialization in UWP

### ISSUE THREAD

**Issue by manuelelucchi** [fo-dicom/fo-dicom#568]
### Expected behavior
Creation of a new DicomImage 

### Actual behavior
System.ObjectDisposedException: "Cannot access a closed Stream"

### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/17146198/28502306-cffe3f86-6fef-11e7-97e3-53a3c3fd8343.png)

### fo-dicom version and OS/platform
fo-dicom.Universal 3.0.2
UWP Project on Windows 10 with Microsoft.NETCore.UniversalWindowsPlatfom v5..3.3

**Comment by anders9ustafsson** [comment]
@manuelelucchi Try to place the `image` definition inside the `using` statement, and also consider to use [`.ConfigureAwait(false)`](https://msdn.microsoft.com/en-us/magazine/jj991977.aspx) on the `DicomFile.OpenAsync` call.

**Comment by manuelelucchi** [comment]
thank you! now it works!
