### ISSUE TITLE
DicomAnonymizer ignores the PatientName and PatientID in the SecurityProfile

### ISSUE THREAD

**Issue by Zaid-Safadi** [fo-dicom/fo-dicom#575]
### Expected behavior
When setting the values of PatientName and PatientID on the DicomAnonymizer SecurityProfile then calling Anonymize, the result Dataset should contain the values being set on the SecurityProfile

### Actual behavior
The PatientName and PatientID are being cleared out from the DICOM Dataset.

### Steps to reproduce the behavior
            _anonymizer = new DicomAnonymizer(DicomAnonymizer.SecurityProfile.LoadProfile(null, DicomAnonymizer.SecurityProfileOptions.BasicProfile |
                                                                                                DicomAnonymizer.SecurityProfileOptions.RetainUIDs |
                                                                                                DicomAnonymizer.SecurityProfileOptions.RetainLongFullDates| 
                                                                                                DicomAnonymizer.SecurityProfileOptions.RetainPatientChars));
            _anonymizer.Profile.PatientName = "zaid";
            _anonymizer.Profile.PatientID   = "IdTest" ;

            var file = _anonymizer.Anonymize(_file);

### fo-dicom version and OS/platform
v3.0.2 Desktop

**Comment by Zaid-Safadi** [comment]
When debugging the code, it seems the values are being set but later cleared out in the "AnonymizeInPlace" method. A possible solution is to restart/continue the loop after setting the value hee:

                if (element.Tag.Equals(DicomTag.PatientName) && Profile.PatientName != null)
                {
                    ReplaceString(dataset, element, Profile.PatientName);
                    continue; // Add this line
                }
                else if (element.Tag.Equals(DicomTag.PatientID) && Profile.PatientID != null)
                {
                    ReplaceString(dataset, element, Profile.PatientID);
                    continue; // Add this line
                }

As a workaround, I am removing these tags from the profile by doing this:

                anonymizer.Profile.PatientName = "Dcloud^Anonymized";
                anonymizer.Profile.PatientID   = "Dcloud.Anonymized";

                RemoveDeIdentifierTag ( anonymizer, DicomTag.PatientName ) ;
                RemoveDeIdentifierTag ( anonymizer, DicomTag.PatientID ) ;

        private static void RemoveDeIdentifierTag ( DicomAnonymizer anonymizer, DicomTag tag )
        {
            var parenthesis = new[] { '(', ')' };
            var tagString = tag.ToString ( ).Trim(parenthesis);
            var action = anonymizer.Profile.FirstOrDefault(pair => pair.Key.IsMatch(tagString));
            anonymizer.Profile.Remove(action.Key);
        }

**Comment by anders9ustafsson** [comment]
@jaime-olivares Can you comment on this one?

**Comment by anders9ustafsson** [comment]
@jaime-olivares Do you have any input on this? Or #576?
