### ISSUE TITLE
DicomAnonymizer blank DicomDate/DicomDateTime to DateTime.MinValue instead of empty value

### ISSUE THREAD

**Issue by Zaid-Safadi** [fo-dicom/fo-dicom#576]
### Expected behavior
After calling Anonymize the date values that should be blanked/zeroed such as Study Date should be set to empty elements.

### Actual behavior
These Date values are being set to DateTime.MinValue which is unexpected 

### Steps to reproduce the behavior
            _anonymizer = new DicomAnonymizer(DicomAnonymizer.SecurityProfile.LoadProfile(null, DicomAnonymizer.SecurityProfileOptions.BasicProfile |
                                                                                                DicomAnonymizer.SecurityProfileOptions.RetainUIDs |
                                                                                                DicomAnonymizer.SecurityProfileOptions.RetainPatientChars));

            var file = _anonymizer.Anonymize(_file);

### fo-dicom version and OS/platform
v3.0.2 Desktop

**Comment by Zaid-Safadi** [comment]
One solution that seems to produce the expected behavior is to replace the DateTime.MinValue with String.Empty in the BlankElement method:

            // Special date/time cases
            if (element is DicomDateTime)
            {
                dataset.AddOrUpdate(new DicomDateTime(element.Tag, DateTime.MinValue));
                return;
            }
            if (element is DicomDate)
            {
                dataset.AddOrUpdate(new DicomDate(element.Tag, DateTime.MinValue));
                return;
            }

should be:

            // Special date/time cases
            if (element is DicomDateTime)
            {
                dataset.AddOrUpdate(new DicomDateTime(element.Tag, string.Empty));
                return;
            }
            if (element is DicomDate)
            {
                dataset.AddOrUpdate(new DicomDate(element.Tag, string.Empty));
                return;
            }

**Comment by anders9ustafsson** [comment]
@jaime-olivares Can you comment on this one?
