### ISSUE TITLE
CT Object Crash

### ISSUE THREAD

**Issue by imanabu** [fo-dicom/fo-dicom#58]
I have a CT Object that causes a crash on fo-dicom but not on dcm4che3, dcmtk/dcmdump and dvtk editor. The crash can be demonstrated with the Dump tool, but also occurs in other DICOM store operations.

Make: Philips Brilliance 64 but has various additional private data in it potentially massaged by Primordial and also has various ELSCINT private data.

It exceptions in parsing an SQ element, but by the time this happens, the tag is all incorrect and with a huge length of 375816198.

I will be performing the initial diagnostics and if able to fix will place a pull request.

If you need to see the object, please email me directly to manabu (at) wingumd.com. Though object is sanitized, I will play it safe as it is an actual acquired object.

**Comment by anders9ustafsson** [comment]
Hello Imanabu,

and many thanks for reporting. It would be really great to have a look at the object, if you could please e-mail it to "anders at cureos dot com", that would be great.

Which *fo-dicom* version have you tested upon? We have solved a possibly related issue in the latest pre-release, please see issue #47 . The pre-release is available on NuGet, see [here](https://www.nuget.org/packages/fo-dicom/1.1.0-rc2).

Best regards,
Anders @ Cureos

**Comment by imanabu** [comment]
Andres, I will send you the object file in email shortly. I pulled/built the master at

https://github.com/fo-dicom/fo-dicom/commit/862fe7d131aaade3c9a539a9b91fc53ca1786672

Before I do anything else, let me pull the latest dev commit and try again.

**Comment by imanabu** [comment]
The latest development branch does fix this issue (awesome!).

**Comment by anders9ustafsson** [comment]
Great, glad to hear that, Manabu!
