### ISSUE TITLE
DicomServer to listen on IPv6 socket

### ISSUE THREAD

**Issue by mia-san** [fo-dicom/fo-dicom#588]
hi.

I'm developing some DICOM server using fo-dicom and noticed that DicomServer listen on IPv4 socket only, at least on fo-dicom.Desktop, as DICOM/Network/DesktopNetworkListener.cs says
```
        internal DesktopNetworkListener(int port)
        {
            this.listener = new TcpListener(IPAddress.Any, port);
        }
```

IPv4 is still preferred over IPv6, but it would be nice if server could listen on IPv6 socket anyway.
e.g.
  1)  always listen on IPAddress.IPv6Any
  2)  add boolean property like EnableIPv6 into DicomServiceOptions to control listening address.
  3)  add property to specify listening address into DicomServiceOptions so that server could bind itself to localhost only etc.

thanks.

**Comment by anders9ustafsson** [comment]
@mia-san Many thanks for the suggestion. I am not sure if I understand item 3, though? Could you please give an example of how this option would be used? Also, if we would be opening up for IPv6, would that have any impact on the client code?

**Comment by mia-san** [comment]
@anders9ustafsson thanks for your comment and sorry to be unclear. 

my idea is that,
1. add property like BindAddress or ListenAddress or such into DicomServiceOptions, which would have IPAddress.Any as default.
2. somehow pass the property as binding address(e.g change DesktopNetworkListener(int port) to DesktopNetworkListener(IPAddress address, int port) etc)
3. client set binding address via the property and start DICOM server.

this way, if client
- doesn't set the property, DICOM server will listen on IPv4 Any socket as default, same as before.
- set IPv6Any to the property, DICOM server will listen on IPv6 Any socket.
- set Loopback to the property, DICOM server will listen on IPv4 loopback address only
- set some particular address to the property, DICOM server will listen on the address only.

> Also, if we would be opening up for IPv6, would that have any impact on the client code?

one obvious 'impact' is length of RemoteHost in DicomAssociation.
as IPv6 address can be longer than IPv4, if client is saving RemoteHost into databases for some reason etc, it may fail.

therefore, we'd listen on IPv4 only as default to be safe.

thanks again.

**Comment by mia-san** [comment]
hi again.

4.  add binding address argument to DicomServer.Create() or DicomServer's constructor.
  this might be easier than 3.

thanks.

**Comment by Cregganbane** [comment]
Nice proposal. Even for IPv4, the ability to configure which NIC fo-dicom listens on would be great.

**Comment by anders9ustafsson** [comment]
@mia-san I have prepared a pull request supporting the extensions I interpret that you asked for. Please have a look at PR #604 and leave a comment if you have questions or concerns.

**Comment by mia-san** [comment]
@anders9ustafsson thanks very much for update and sorry to be late. I've just checked #604 and looks almost good to me.

btw, what if
```
//  for compatibility
public static INetworkListener CreateNetworkListener(int port) {
  return CreateNetworkListener(IPAddress.Any, port);
}

// user have string representation of IP address
// this will throw early if ipAddress is not parsed
public static INetworkListener CreateNetworkListener(string ipAddress, int port)
{
  return CreateNetworkListener(IPAddress.Parse(ipAddress), port);
}

// user already have IP address resolved
public static INetworkListener CreateNetworkListener(IPAddress ipAddress, int port)
{
  //  this way, internal implementation always received IPAddress object.
  //  it doesn't need to worry about if string representation can be parsed or not.
  return _implementation.CreateNetworkListenerImpl(ipAddress, port);
}
```

thanks
//

**Comment by anders9ustafsson** [comment]
@mia-san That might seem like the most straightforward solution, but the problem is that the class `IPAddress` is not available in the Portable Class Library 111 Profile. 

PCL is admittedly being superseded by the .NET Standard, but for the time being PCL is still alive and I would also like to keep it as part of the *fo-dicom* ecosystem at least for the upcoming major release.

So, to enable PCL compatibility, the `ipAddress` argument is required to be a `string`. I agree that it is not optimal, and when PCL is phased out we should probably change it to be of type `IPAddress`, but right now `string` is the only realistic option.

**Comment by mia-san** [comment]
@anders9ustafsson ah, I see. I missed that IPAddress is unavailable in PCL. Let's use string until PCL support dropped.

thanks.
