### ISSUE TITLE
Add logging support for MetroLog

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#59]
[MetroLog](https://github.com/mbrit/MetroLog) is a logging framework with close resemblance to *NLog*. The main advantage with *MetroLog* is that it is available as a *Portable Class Library*, capable of targeting various platforms such as .NET 4.5 and higher, Windows 8.1, Windows Phone 8.1, Windows Universal (Win 10) and even Xamarin.iOS and Xamarin.Android.

It would be a welcome addition to add a separate logging support library for *MetroLog*, similar to *fo-dicom.NLog* and *fo-dicom.Serilog*.

**Comment by IanYates** [comment]
Nice idea :)
