### ISSUE TITLE
Too many presentation contexts configured for this association

### ISSUE THREAD

**Issue by deyung** [fo-dicom/fo-dicom#590]
### Expected behavior
Presentation context should be unique

### Actual behavior
Same presentation contexts are being added to _pc in DicomPresentationContextCollection.cs

### Steps to reproduce the behavior
Perform C-Store with a lot of files of the same presentation context

### fo-dicom version and OS/platform
Latest Development version... something must have changed recently because this wasn't happening before.

**Comment by anders9ustafsson** [comment]
@deyung Strange? Is it any specific presentation context you are adding?

**Comment by deyung** [comment]
I'm just using the samples from here http://www.osirix-viewer.com/resources/dicom-image-library/.

Here's a snippet of code that's causing the issue. It's the same code block I've been using for years with fo-dicom.

`
var client = new DicomClient();
var files = Directory.EnumerateFiles(directory);
foreach (var file in files)
{
	Console.WriteLine("Queuing {0} to be sent", file);
	try
	{
        var req = new DicomCStoreRequest(file)
        {
            OnResponseReceived = delegate (DicomCStoreRequest request, DicomCStoreResponse response)
            {
                if (request == null)
                    throw new ArgumentNullException(nameof(request));
                if (response.Status == DicomStatus.Success)
                {
                    Console.WriteLine("C-Store of {0} was successful", file);
                }
                else
                {
                    Console.WriteLine("C-Store of {0} failed!", file);
                }
            }
        };
        client.AddRequest(req);
	}
	catch (Exception ex)
	{
		Console.WriteLine("Error adding {0}: {1}", file, ex.Message);
	}
}
client.Send(hostName, port, isTLS, callingAE, calledAE);
`

**Comment by deyung** [comment]
I'm sending a single series of a study that has 585 files, all from the same series. I initially saw the issue sending the entire study, then I start narrowing it down to series and still had the same issue.

Series with around 50 files seem to work fine, anything over 100 or so fails with the "Too many presentation contexts configured for this association" exception.

**Comment by anders9ustafsson** [comment]
@deyung OK, I will investigate. Could you please re-format the source code above to separate lines? It would make it easier to grasp.

**Comment by deyung** [comment]
GitHub code formatting seems to not to be working for me, but I got it readable now.

**Comment by anders9ustafsson** [comment]
@deyung To facilitate debugging; which was the last *fo-dicom* version where this worked as intended for you?

**Comment by deyung** [comment]
This is not going to help but that last time I remember attempting to store these studies where probably back in April. I haven't tested it since.

I'm currently looking at it also, would the _pc SortedDictionary in DicomPresentationContextCollection.cs contain the same AbstractSyntax with different IDs?

It seems that the function GetNextPresentationContextID() just increments the ID by 2 and eventually goes over 256.

**Comment by anders9ustafsson** [comment]
I have done quite a few changes in `DicomClient` and `DicomService` that might or might not be related to this. The latest change in `DicomPresentationContextCollection` was to exclude Explicit VR Little Endian from the list of default transfer syntaxes. I don't see that this would have any impact on the issue you are experiencing.

It's not obvious to me right now how the collection should handle same abstract syntax in with different IDs. I need to evaluate this further. But yes, the ID counter will overflow after 128 contexts.

**Comment by anders9ustafsson** [comment]
OK, apparently the `AddFromRequest` method does not properly identify when the abstract syntax/transfer syntax has previously been recorded. Fix should be due during the day (I hope :-) )

**Comment by anders9ustafsson** [comment]
OK, fixed. Problem was due to an incomplete update when refactoring the `DicomPresentationContext.AcceptedTransferSyntax` initialization in #583 (issue #543). Many thanks for making me aware of this flaw, @deyung.

**Comment by deyung** [comment]
thanks, works like a charm!

**Comment by uttamdashtech** [comment]
client = new DicomClient(dicomRemoteHost, dicomRemoteHostPort, false, ourDotNetTestClientDicomAeTitle, remoteDicomHostAeTitle);
                    foreach (var serisUId in serieUids)
                    {
                        var cGetRequest = CreateCGetBySeriesUID(studyUID, serisUId);
                        client.OnCStoreRequest += (DicomCStoreRequest req) =>
                        {
                            Console.WriteLine(DateTime.Now.ToString() + "DCM files recived");
                            SaveImage(req.Dataset);
                            return Task.FromResult(new DicomCStoreResponse(req, DicomStatus.Success));
                        };
                        // the client has to accept storage of the images. We know that the requested images are of SOP class Secondary capture, 
                        // so we add the Secondary capture to the additional presentation context
                        // a more general approach would be to mace a cfind-request on image level and to read a list of distinct SOP classes of all
                        // the images. these SOP classes shall be added here.
                        var pcs = DicomPresentationContext.GetScpRolePresentationContextsFromStorageUids(
                            DicomStorageCategory.Image,
                            DicomTransferSyntax.ExplicitVRLittleEndian,
                            DicomTransferSyntax.ImplicitVRLittleEndian,
                            DicomTransferSyntax.ImplicitVRBigEndian);
                        client.AdditionalPresentationContexts.AddRange(pcs);
                        await client.AddRequestAsync(cGetRequest);
                        await client.SendAsync();


I am facing same error on above code please anyone help me out from this?
