### ISSUE TITLE
DicomDataset Get/AddOrUpdate with byte[]

### ISSUE THREAD

**Issue by mia-san** [fo-dicom/fo-dicom#596]
hi.

Is it possible to provide DicomDataset to Get<byte[]> or AddOrUpdate<byte[]> overload ?

in case (0008,0005) SpecificCharacterSet is '\ISO 2022 IR 87\ISO 2022 IR 13', fo-dicom seems to treats string element to be an IR 6 and PatientName with raw narrow Kana get garbled(appears as '?' character)
we're now doing like following:
```
var e = dataset.Get<DicomStringElement>(tag);
return Encoding.GetEncoding("SHIFT_JIS").GetString(e.Buffer.Data);
```
works OK, but
`return Encoding.GetEncoding("SHIFT_JIS").GetString(dataset.Get<byte[]>(tag, {}));`
could be easier.

regarding to DicomDataset.AddOrUpdate, no overload takes encoding.
therefore, e.g. setting narrow Kana string into PatientName, it gets garbled like above.
now we are creating element object, DicomPersonName or DicomCodeString or such, for each DICOM element, but this is rather boilerplate and prone to error(create element with wrong VR etc)

however, we KNOW how to encode string (e.g. patient name), so
```
byte[] encoded_patient_name_byte_array = this.EncodePatientName(patient_name);
dataset.AddOrUpdate(DicomTag.PatientName, encoded_patient_name_byte_array);
```
would be nice.

thanks.

**Comment by anders9ustafsson** [comment]
@mia-san For `DicomDataset.AddOrUpdate`, you are able to specify encoding in the various DICOM element constructors, so for example this should work:

    dataset.AddOrUpdate(new DicomPersonName(DicomTag.PatientName, *encoding*, patient_name));

When it comes to the `Get` method, I think the main issue is that *fo-dicom* is not handling code extensions in the *Specific Character Set* entirely correctly at the moment, please see issue #43. I think our focus should be to provide sufficient support for code extensions. Hopefully that would solve your encoding issue automatically.

**Comment by mia-san** [comment]
@anders9ustafsson hi, many thanks for your comments.

> For DicomDataset.AddOrUpdate, you are able to specify encoding in the various DICOM element constructors, so for example this should work:
> dataset.AddOrUpdate(new DicomPersonName(DicomTag.PatientName, *encoding*, patient_name));

yes, that's what we're doing for now.

but if we need to modify InstitutionName, PatientID, PatientBirthDate or StudyDescription, we need to create element object for each DICOM element.
it could be CodeString, it could be LongString, it could be LongText etc etc, easily create wrong element I'm afraid(our product may have to be customized for site's needs).

if dataset.AddOrUpdate(tag, byte[]) works, we don't have to worry about which VR should be used.


> When it comes to the Get method, I think the main issue is that fo-dicom is not handling code extensions in the Specific Character Set entirely correctly at the moment, please see issue #43. I think our focus should be to provide sufficient support for code extensions. Hopefully that would solve your encoding issue automatically.

thank you for reference to #43.
yes, that seems to be related and code extension support would be really great !

however, sometimes we need to interact with 'ill-encoded' DICOM tag, which value violates SpecificCharacterSet(e.g. PACS may keep image from older equipments)

therefore, get/set byte[] could be very nice.

**Comment by anders9ustafsson** [comment]
@mia-san I have checked the code and verified via unit tests, and `DicomDataset.Get<byte[]>(DicomTag)` works as you'd like it to already today.

I will take a closer look at `AddOrUpdate`. Stay tuned!

**Comment by anders9ustafsson** [comment]
@mia-san After further examination of the source code, I have come to the conclusion that the most efficient change would be to include `Add` and `AddOrUpdate` overloads that take `Encoding` as a parameter.

This would be a change isolated to the `DicomDataset` class, whereas enabling the ability to add byte arrays would affect a larger part of the code base and could (at least theoretically) lead to inconsistencies in interpretation for multi-valued items; does `byte[]` represent a single composite value or an array of byte values? By instead enabling specification of the string encoding we would avoid these interpretation inconsistencies and hopefully also allow for cleaner code.

**Comment by mia-san** [comment]
@anders9ustafsson thank you for your efforts and sorry to be late.

- regarding Get<byte[]>:
  yes, I also have confirmed that it works as expected.
  I don't know why I thought it's now working...
  sorry about that.

- regarding Add(OrUpdate)<byte[]>:
  As Get<byte[]> returns raw tag value without regarding components nor encoding nor multiplicity, my idea is Add(OrUpdate)<byte[]> to work opposite.
  i.e. it totally replace raw tag value without regarding components nor encoding nor multiplicity.
  or add new function, such as Set<byte[]> or Replace<byte[]>, and leave Add(OrUpdate) intact?

thanks.

**Comment by anders9ustafsson** [comment]
@mia-san Regardless, it is still a quite large undertaking to implement `Add{OrUpdate}<byte[]>`, because the majority of the underlying `DicomElement` derived classes are currently not prepared for setting the value directly from a byte array. On the other hand, the code was well prepared for adding `Add` and `AddOrUpdate` overloads that take `Encoding` as an argument, and as far as I see it that should provide you with the same end result as setting the value via a byte array. 

Please see [this](https://github.com/fo-dicom/fo-dicom/blob/development/Tests/Desktop/DicomDatasetTest.cs#L479-L491) unit test for one example of the new functionality.

**Comment by mia-san** [comment]
@anders9ustafsson ah, OK. unit test seems good enough for our use(as SHIFT_JIS can hold ISO-2022-JP representation).

thanks for your efforts.
fo-dicom is very helpful for us.
//
