### ISSUE TITLE
Illegal VR behaviour

### ISSUE THREAD

**Issue by PimPhilipse** [fo-dicom/fo-dicom#598]
Pre-3.0 versions of DCMTK had a DICOM dictionary where the status of being Retired of an attribute was stored in the VR field. As a consequence, creating a dataset with explicit VR might contain elements with VR=RE.
My expectation is that these elements are either ignored, or (ideally) patched to their actual VR. Since this was also possible with the VR consisting of two spaces, as described in #179, this appears to be feasible.

The actual behavior is that parsing of the dataset terminates immediately.

Steps to reproduce the behavior: using a hex editor, change the VR of a random element in an explicit dataset to RE. Then let DICOM Dump read the prepared dataset. It will only list the elements that come before the modified element.

fo-dicom version 3.0.2, Desktop, Windows 7.

**Comment by anders9ustafsson** [comment]
> Pre-3.0 versions of DCMTK

@PimPhilipse You have me confused now? Do you mean pre-3.0 versions of *fo-dicom*? As far as I can recall *fo-dicom* has had no such thing as a **RE** VR replacement? 

Or do you really mean DCMTK prior to version 3.0? The earliest DCMTK version I can find in their archives is version 3.1.0 from 1996.

Anyway, if an application uses **RE** as explicit value representation, that would be invalid DICOM, so currently I do not think it is worthwhile to provide any workarounds for this scenario. Of course, if this turns out to be a common problem for several users, we could of course rethink. But so far this is the first time I have heard about this issue.

**Comment by PimPhilipse** [comment]
There is still a 2.1 version of DCMTK in the archives, we used that among other things to archive images, and these may still be on file with some of our customers. We always patch our builds of DCMTK to support the RE VR.
Moreover, RE is just as invalid as the two spaces used as VR as described in #179, and in the discussion of that issue the invalidity was not raised as an argument to ignore it.

**Comment by anders9ustafsson** [comment]
@PimPhilipse Well, everything is a matter of priority. As I wrote, this is the first time anyone has brought up the issue, so I doubt that it is a common scenario.

Also, how should this case be viewed from a principal standpoint? Should **RE** be considered a special VR that should be defined in its on right e.g. in the `DicomVR` class? Or should it just be considered as a dummy to be ignored? The Value Representation is also used to determine the number of bytes in the length specification for example, how should that be handled if there is no clear indication which VR is actually intended? At least from this point of view it is easier to just say that an unregistered VR is an invalid VR.

Anyway, if this is an important feature for you, feel free to provide a pull request which we could then consider for inclusion.

**Comment by anders9ustafsson** [comment]
Also, do I understand correctly that not even plain DCMTK contains support to handle **RE**, and that you need to patch DCMTK to support it? If not even the OFFIS people provides built-in support for something they themselves initiated, that is in itself an indicator of how **RE** VR should be handled, I think.

**Comment by gofal** [comment]
I will close this issue because of inactivity. If this issue is still relevant then please feel free to reopen it again and add some updates.
