### ISSUE TITLE
Split fo-dicom into portable core and platform specific assemblies

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#60]
It would be a welcome addition if (parts of)  *fo-dicom* could be available for platforms other than .NET., for example Windows Universal (Windows 10), Xamarin.iOS and Xamarin.Android. 

My vision is that we have a core Portable Class Library (PCL), *DICOM.Core*. This library contains the abstract manager classes and imaging, I/O, networking interfaces. Then, for each target platform, we have a library that reference the core library and contains the implementations of the managers and interfaces. These platform specific libraries can also contain dependencies to the platform specific codec implementations. To begin with, we would have *DICOM.Desktop* for the .NET platform, but then we could expand with *DICOM.Windows* for the *Universal Windows Platform*, *DICOM.Mono* for the Mono platform, and so on.

**Comment by hiscodeness** [comment]
+1 :+1:

**Comment by michaelp** [comment]
It would be nice to have it as one of the first steps. (Personally,i would like to take a closer look into complete decoupling the IO, Rendering, etc. from the  DICOM image class and to understand what is available to support different IODs).  Having this refactored would make merging & validation easier.

**Comment by anders9ustafsson** [comment]
@michaelp Thanks for the input. We are on our way with this, but would still like to make some more portability preparations in the code before actually splitting assemblies. File I/O has already been abstracted (PR #78) for this purpose, and the use of types from the `System.Drawing` namespace has also been reduced (PR #85) for the same reason. Currently I am working on shifting asynchronous functionality to `async`/` await` constructs (issue #65), where *one* gain from a portability point of view is that we can get rid of most `Thread` and `ThreadPool` calls. When these pieces are in place, it will be easier to make the transition to multiple assemblies, I think.
