### ISSUE TITLE
DicomServer constructor marked obsolete

### ISSUE THREAD

**Issue by Cregganbane** [fo-dicom/fo-dicom#602]
The DicomServer constructor is marked obsolete with the suggestion to use the static Create method instead to construct instances. However, it is still necessary in client code to inherit from DicomServer to override the protected virtual CreateScp method. 

What is the intention here? How should clients pass their own parameters to a DicomService instance?

**Comment by anders9ustafsson** [comment]
@Cregganbane I have prepared a pull request facilitating subclassing of `DicomServer<T>` while allowing for server initialization of the derived types via `DicomServer.Create`. Please have a look at PR #604 and leave a comment if you have questions or concerns.
