### ISSUE TITLE
Performance of DicomImage constructor 10x slower in .NET Core for certain transfer syntax

### ISSUE THREAD

**Issue by akaegi** [fo-dicom/fo-dicom#603]
We are using fo-dicom (3.0.2) in a .NET core environment to save images and extract metadata from them.
On an image from a new device (TransferSyntaxUID (0002,0010): 1.2.840.10008.1.2.4.50) we observed the .NET core variant to be 10x slower than the "normal" .NET counterpart.

`Dicom.Imaging.DicomImage(string)` constructor took approx. 20 seconds (.NET core) vs. approx. 2 seconds (.NET).

Observed the behaviour with both versions 3.0.2 and 3.1.0-alpha.

Attached the sample image here: [slow.zip](https://github.com/fo-dicom/fo-dicom/files/1277398/slow.zip)

Any ideas how this could be improved?

**Comment by anders9ustafsson** [comment]
@akaegi .NET Core uses managed C# libraries to handle the codecs, whereas .NET Framework and UWP uses native C/C++ libraries, hence the difference in performance.

Currently it's not in our pipeline to switch to native libraries for .NET Core, but there is a third party attempt to do just that, see [here](https://www.nuget.org/packages/sieempi.DICOM.NETCore.Native). From what I can see this third-party package is applicable to x64 architectures on Windows, Linux and Mac. I have not tested it myself, but please go ahead, try it and share your thoughts.
