### ISSUE TITLE
Re-format C# code to use Visual Studio default tabbing

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#61]
Currently, it can be very cumbersome to edit existing *fo-dicom* source code, since it adheres to tabbing and indentation conventions that are not commonly used with later Visual Studio versions.

To facilitate future development for a group of dedicated developers it is therefore suggested that the source code should be re-formatted to match the following settings in Visual Studio:

> Smart indenting
> Tab size 4
> Indent size 4
> Insert spaces

On the same note, I also suggest that opening angle brackets should be placed on separate lines, i.e.

    if (condition)
    {
      ...

    foreach (var item in items)
    {
      ...

    public double X
    {
      get
      {
        return _x;

    etc.

**Comment by IanYates** [comment]
:+1:

**Comment by hiscodeness** [comment]
:+1:
