### ISSUE TITLE
Changing Media Storage SOP Instance UID fails

### ISSUE THREAD

**Issue by klaheeman** [fo-dicom/fo-dicom#612]
### Expected behavior

I am changing instance UIDs of an image (SOP instance UID, Media Storage SOP Instance UID).
I save the image, and I expect to find the new values I set.

### Actual behavior

What I get is a duplicate Media Storage SOP Instance UID, whereas the SOP Instance is correctly modified.

### Steps to reproduce the behavior

Load an image, set both UIDs and save the same image again. Please note that I also want the pixel data to be saved, and for this I need to keep the stream open in memory (this is also inconvenient).

### fo-dicom version and OS/platform
3.0.2, desktop, .net 4.5.2

**Comment by anders9ustafsson** [comment]
Thanks for reporting, @klaheeman! I will look into your case more closely. Are you working with a Part 10 file, i.e. does it consist of a complete set of file meta information?

Also, this:

> Please note that I also want the pixel data to be saved, and for this I need to keep the stream open in memory (this is also inconvenient).

Is this a separate request? In that case, please post a separate issue and describe in more detail what you are doing and how you would like the library to work.

**Comment by klaheeman** [comment]
I see that I can change the media storage sop instance by changing the file
metadata info. So it's just inconvenient that setting the tag value causes
a duplicate attribute. Maybe it could be treated in a special way.

As per my other request, you're right and I'll submit another Improvement
request.

Thanks

Claudio Landi

Il giorno mer 20 set 2017 alle 10:09 Anders Gustafsson <
notifications@github.com> ha scritto:

**Comment by anders9ustafsson** [comment]
@klaheeman I have now tested this issue, and I am not able to reproduce the error you are describing using the latest commit in the *development* branch. Please post the exact code you are using to update the SOP Instance UIDs.

**Comment by anders9ustafsson** [comment]
@klaheeman Do you have any updates to this? I tested and am not able to reproduce with the current code in the *development* branch. Please re-test your issue using the *development* branch code, and if you are able to reproduce, share the malfunctioning code.

**Comment by klaheeman** [comment]
The following generates a duplicate media storage instance uid:

DicomFile.Dataset.AddOrUpdate<string>(DicomTag.MediaStorageSOPInstanceUID, value);

The following is the working code for setting media storage instance uid:

```
DicomUID existing = null;
                try {
                    existing = DicomFile.FileMetaInfo.MediaStorageSOPInstanceUID;
                } catch (Exception ex) {

                }
                if (existing != null) {
                    DicomFile.FileMetaInfo.MediaStorageSOPInstanceUID = new DicomUID(value, existing.Name, existing.Type);
                }
```

**Comment by anders9ustafsson** [comment]
@klaheeman The reason why you get a duplicate is because you are updating the `Dataset` of the `DicomFile`. `MediaStorageSOPInstanceUID` resides in the `FileMetaInfo` part of `DicomFile`. There is no check that you are adding file meta information to the main dataset and vice versa, and the two parts are completely separated.

Change the duplicate generation line to read like this instead:

    DicomFile.FileMetaInfo.AddOrUpdate(DicomTag.MediaStorageSOPInstanceUID, value);

and you will see that the duplicate is no longer generated.

**Comment by klaheeman** [comment]
Ok, thanks Anders, I can proceed and the issue is solved for my needs.

Just a suggestion, I believe that the AddOrUpdate tag on the dataset should "intercept" the case of tags already handled by the FileMetaDataInfo, so that accidentally adding a duplicate tag is avoided by the library.

Regards,

Claudio

**Comment by anders9ustafsson** [comment]
@klaheeman Thanks for the suggestion. You are probably right in that the `Add`/`AddOrUpdate` methods could be more restrictive for the `FileMetaInfo` part. We'll have that in mind for future updates.
