### ISSUE TITLE
DicomDataSet and Encoding

### ISSUE THREAD

**Issue by Nezrahm** [fo-dicom/fo-dicom#613]
Hi,

I looking at fo-dicom 3 and have trouble understanding how the data sets are supposed to be used in respect with character encodings.

Correct me if I’m wrong but the following seems to be true.
- The sets have no idea about encoding.
- The specific elements in the sets can have encoding on them.
- The elements in the sets can have different encodings on them.
  - But this is not reflected in an export?
- We can manually set a SpecificCharacterSet element that informs how the elements should be interpreted when files are parsed. This doesn’t affect anything though?

If the above is true then I don’t really know what to think. Shouldn’t the SpecificCharacterSet-tag always be set on a data set and control the encoding of its elements?
Is there a way for me to instruct fo-dicom to always use UTF8 as encoding when working with sets?

I want to be able to use: `ds.Add(DicomTag.PatientID, "Hi 人物");`

Not to have to do: `ds.Add(new DicomLongString(DicomTag.PatientID, Encoding.UTF8, "Id 物"));`

**Comment by anders9ustafsson** [comment]
@Nezrahm If I remember correctly, there is currently no way to configure the encoding for an entire `DicomDataset`. With the upcoming release it will be slightly more convenient though; as a complement to writing this:

    ds.Add(new DicomLongString(DicomTag.PatientID, Encoding.UTF8, "Id 物"));

you will also be able to write this:

    ds.Add(DicomTag.PatientID, Encoding.UTF8, "Id 物");

For the time being, there are no immediate plans to implement "global" encoding, but if the interest is large enough (number of :+1: are high :-) ), we can reconsider. Please also note that there is an outstanding issue on code extension, #43, that may have influence on this topic.

**Comment by Nezrahm** [comment]
Ok. There seems to be quite a big risk here though.

This way could one easily create a data set with two elements that have different encodings (say one UTF8 and one iso-8859-1). This all looks well in memory but if you serialize and deserialize it (to trigger the SpecificCharacterSet handling) then will the data be borked.

**Comment by anders9ustafsson** [comment]
Yes, that is correct, currently we are not mitigating that sort of oversights. Good that you point this out.
