### ISSUE TITLE
detail message missing

### ISSUE THREAD

**Issue by erlaxmikantha** [fo-dicom/fo-dicom#616]
### Expected behavior
In DicomCMoveRequest class subscribed to OnResponseReceived. dcmtk tool kit error returned as 0xc502: Error: Failed - Unable to process. Conformance statement of the PACS gives the right information that Failure C502 Move destination unreachable.  status in DicomCMoveResponse should be same as it returned by PACS system.

### Actual behavior
status is coming as Failure [c000: Cannot understand]. 

### Steps to reproduce the behavior
specific to customer environment. Not sure about the reason for it

### fo-dicom version and OS/platform
fo-dicom version 3.0.2

**Comment by anders9ustafsson** [comment]
@erlaxmikantha Please share a code snippet that highlights your problem.

**Comment by erlaxmikantha** [comment]
private void ReceiveCMoveResponse(DicomCMoveRequest request, DicomCMoveResponse response)
{
    if (response.Status == DicomStatus.Success)
    {
        Logger.LogInfoFormat("C-MOVE Success [Series: {0}]: Status:{1}"
        , this.mySeriesInstanceUid
        , response.Status);
        this.myRequestComplete = CMOVE_Status.Success;
    }
    else if (response.Status == DicomStatus.Pending)
    {
        Logger.LogInfoFormat("C-MOVE Pending [Series: {0}]: Current Status:{1}, Completed:{2}, Remaining:{3}, Failures:{4}, Warnings:{5}"
        , this.mySeriesInstanceUid
        , response.Status
        , response.Completed
        , response.Remaining
        , response.Failures
        , response.Warnings);
        if (response.Completed > 0)
            this.myRequestComplete = CMOVE_Status.Partial;

    }
    else if (response.Status != DicomStatus.Success)
    {
        Logger.LogErrorFormat("C-MOVE Failure [Series: {0}]: Status: {1}, Desc:{2}, Code:{3}, ErrorComment: {4}"
        , this.mySeriesInstanceUid
        , response.Status
        , response.Status.Description
        , response.Status.Code
        , response.Status.ErrorComment);

    }

    this.myCMoveErrorComments = response.Status.ErrorComment;
    this.myCMoveStatus = response.Status;
}
in if else block where response.status != DicomStatus.success, I am expecting the actual status that returned by the PACS but it is giving some generic error making it is difficult to analyze with PACS vendor.

**Comment by gofal** [comment]
fo-dicom has internally a list of known status codes. there is also knows the type (success, warning, error) and some description. When a statuscode is returned then the parser tries to map to one of the known status codes to provide at least a generic description. But you are right, the original status code gets lost, which is not good to analyze errors.
