### ISSUE TITLE
Loading and saving pixel data requires source stream to be open

### ISSUE THREAD

**Issue by klaheeman** [fo-dicom/fo-dicom#617]
Disclaimer: I am not sure whether this is an issue, or usability improvement request.

### Expected behavior

I expect to be able to load an image, then save it.

### Actual behavior

I get and ObjectDisposedException upon saving with the following code:

```
static void Main(string[] args)
        {
            DicomFile dcm = null;
            if (File.Exists(args[0])) {
                byte[] buff = File.ReadAllBytes(args[0]);
                using (MemoryStream stream = new MemoryStream(buff)) {
                    dcm = Dicom.DicomFile.Open(stream);
                }
            }

            // this will save the image without pixels and generate an ObjectDisposedException
            dcm.Save(args[1]);
        }
```

### Steps to reproduce the behavior

Run the code above with a dicom image, I am using a simple single frame CT image. If I keep the source stream open, opening and saving works well.

Is there a way to make sure all image is loaded to memory, pixels included, so that the source stream is not needed anymore?
Or alternatively, is there a way to pull in the pixels later, and again make sure the source stream is not needed anymore?

### fo-dicom version and OS/platform

fo-dicom.desktop 3.0.2

**Comment by gofal** [comment]
solved in branch GH-617.
the ObjectDisposedException is now replaced by a DicomIoException with the message "cannot read from stream - maybe closed" to make the error more obvious to the user.
The DicomFile.Open methods now have an optional FileReadOption parameter to define how to deal with the large DICOM tags.
Default - and the behavior as until now - is that fo-dicom only parses small tags and keeps a reference to large tags in the stream. they are acced only on demand, for example when saving the file. But this requires the stream to stay opened as long as the DicomFile lives.
Two other options that allow the stream to be closed immediatelly are FileReadOption.ReadAll (read all the tags, also the large ones) and FileReadOption.SkipLarge (large options are skipped - saves memory and IO if only the header info is needed).
