### ISSUE TITLE
Remove obsolete dictionary, tag and UID code generation

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#62]
Since DICOM dictionary, pre-defined tag and UID generation are now integrated as T4 templates in the *DICOM* project, the code generators in the [Dicom.Generators](https://github.com/fo-dicom/fo-dicom/tree/development/DICOM/Generators) have become obsolete.

Since the classes have likely only been used for internal code generation, it is suggested that these obsolete classes are removed from the *DICOM* project/assembly.

**Comment by IanYates** [comment]
Makes sense to me :+1:
