### ISSUE TITLE
Get Private element Values from JSon File

### ISSUE THREAD

**Issue by VitoHanoi** [fo-dicom/fo-dicom#620]
Hello there,
Thanks for helping me as I have spent 3 days to understand the issue without luck... I don't know if its a bug about private elements or my "get data" technique...

### Expected behavior

I'm failing to get data from Private Elements of a JSon file (which I believe are correctly encoded:
JSon file private elements have different Values (same as dicom file),
When looking at the DicomDataSet variable, different values (same as dicom file),
should be getting these values with code below and Json file below

(0008,0005) : ISO_IR 100
(0045,0010) : GEMS_SENO_02
(0045,1006:GEMS_SENO_02) : 0
(0045,101b:GEMS_SENO_02) : LCC
(0045,1020:GEMS_SENO_02) : 5
(0045,1049:GEMS_SENO_02) : 58

### Actual behavior

It get one (random?) value of the Private Elements Value List and assign it to the other elements.
It is always the same value if same dicomfile (for example : Second value of the list) but varies on a different dicomfile (might be the third Value of the list, still gives the same result each time though)
I have noticed that the value assigned is depending on the number of not private elements in JSON file. (I have deleted one element before the Private Creator Element and the value has changed)

(0008,0005) : ISO_IR 100
(0045,0010) : GEMS_SENO_02
(0045,1006:GEMS_SENO_02) : LCC
(0045,101b:GEMS_SENO_02) : LCC
(0045,1020:GEMS_SENO_02) : LCC
(0045,1049:GEMS_SENO_02) : LCC

### Steps to reproduce the behavior

need to have a JSON file and convert data into a DicomDataset: i know that this part is correctly done as when looking at the DicomDataSet variable (debug mode),  i see the correct values, and after when creating a Dicom File from this Json content, private elements are correct.

myJSonFile part (random values)

 "DicomHeaderInfo": {
    "00080005": {
      "vr": "CS",
      "Value": [
        "ISO_IR 100"
      ]
    },
    "00450010": {
      "vr": "LO",
      "Value": [
        "GEMS_SENO_02"
      ]
    },
    "00451006": {
      "vr": "DS",
      "Value": [
        0
      ]
    },
    "0045101B": {
      "vr": "CS",
      "Value": [
        "LCC"
      ]
    },
    "00451020": {
      "vr": "DS",
      "Value": [
        5
      ]
    },

    "00451049": {
      "vr": "DS",
      "Value": [
        58
      ]
    }
  }

Getting data from the Dataset 

 foreach (DicomItem myDicomAttribute in inDicomDataset)
 {
      DicomTag myDicomTag = myDicomAttribute.Tag;
      string myDicomValue = string.Empty;
      try
      {
           var myDicomValuesJson = inDicomDataset.Get<string[]>(myDicomTag);
           myDicomValue = myDicomValuesJson[0];
      }
      catch
      {
         // ignored
      }
     
    inDicomAttributeList.Add(new KeyValuePair<DicomTag, string>(myDicomTag, myDicomValue));
 }

### fo-dicom version and OS/platform

Wingows 10, fo-dicom and dicomJson 3.0.2, Newtonsoft.Json 10.0.0

**Comment by anders9ustafsson** [comment]
@VitoHanoi There have been fixes to JSON that have not made it into any NuGet package yet. It would be invaluable if you could test the issue against a build from the latest source code in the *development* branch. Do you think you can do that?

**Comment by VitoHanoi** [comment]
@anders9ustafsson sorry for the delay. I have tested (with some difficulties I have to admit as I have never compiled or tested a develpment branch before). But I succeeded ! 

And it is all good! Your new version fixes the issue, now I get the correct values. Wonderful !!!

Do you know when will be the release of this version. As I have tested with the 3.1.0-alpha prerelease (fo dicom and fo-dicom.Json) and it was also failing so I'm looking forward to have the newest version release!

Thanks again for your continuous development and improvement! You can close the issue after reading my comment.

**Comment by anders9ustafsson** [comment]
@VitoHanoi Since there are quite a lot of new stuff which is not yet part of any release, I will probably make a pre-release within the newt few weeks. I have scheduled an official release of 4.0 for November 30, but it might take a little longer since I currently have less time to work with *fo-dicom*.

**Comment by VitoHanoi** [comment]
@anders9ustafsson 
still no release of 4.0 version? 
thanks in advance
