### ISSUE TITLE
C-CANCEL is not processed for C-FIND and C-MOVE operations

### ISSUE THREAD

**Issue by FKupsch** [fo-dicom/fo-dicom#624]
Hello there,

while writing a C-FIND SCP with your nice toolkit, the issue came up that C-FIND-CANCEL-RQ are not processed and a worklist SCU could not cancel the transfer of C-FIND-RSP for the SCP without aborting the association. This issue was adressed in your Google Group several times, but I could not found a related request. The same applies to C-MOVE-CANCEL-RQ. 

## Expected behavior

From DICOM side the expected behavior for the SCP is to stop sending of C-FIND-RSP with status pending (0xFF00) and to send a C-FIND-RSP with status cancelled by client (0xFE00). (see 3.4 K.1.4 Service Definition)

## Actual behavior

The C-FIND-CANCEL-RQ is ignored by the SCP. 

## fo-dicom version and OS/platform

fo-dicom.desktop 3.0.2

**Comment by FKupsch** [comment]
I didnt impelement a client currently, but it will not work either. As you say there is simple no support for this command. On the other side, I already digged into the code of DicomService to figure out how c-cancel can be implemented and I am afraid that a solution for an asynchonous c-cancel cannot be acieved without some major design changes.

**Comment by gofal** [comment]
I see. I also assume a threading problem to implement the cancel-req in the current implementation. The method ListenAndProcessPdu reads from the input stream and then invokes the c-move-method if the DicomService implements the CMoveProvider. then the Handler is processing and working. but while this, the ListenAndProcessPdu is blocked. After the CMove handler is completed the ListenAndProcessPdu continues and reads the next request, the CancelRequest. but at this moment the cmove has already finished.

**Comment by gofal** [comment]
So what to do with this issue? The feature would be great but requires quite some changes in design. does this mean high risk changes regarding the stability? Hope, some more different people give input what they think about this issue.

**Comment by FKupsch** [comment]
The design of the CMoveProvider is defective anyway, because it does not allow an implementation of a MOVE SCP that sends pending responses about the status of the C-STORE sub operations. For this reason it doesnt make sense to implement a C-CANCEL for a MOVE SCP inheritet from IDicomCMoveProvider

**Comment by gofal** [comment]
well, the CMove handler can send pending responses. See my implementation in https://github.com/fo-dicom/fo-dicom-samples/pull/18. there is only a bug with timing of the OnResponseReceived handlers of the DicomCStoreRequests.
