### ISSUE TITLE
Enforce VR restrictions on DicomElement derivations

### ISSUE THREAD

**Issue by FKupsch** [fo-dicom/fo-dicom#627]
I would expect that format, character and length restrictions are enforced for every DICOM VR class. E.g. when passing an invalid string to the constructor of DicomDate, I get an SystemArgument Exception, but when passing a string of more than 16 characters to DicomShortString constructor, no exception is thrown and the attribute is added to the dataset with an invalid value for its VR. 
I wonder why the toolkits provides abstractions for each DICOM VR, but not enforcing their value restrictions?

**Comment by anders9ustafsson** [comment]
@FKupsch Could you please share some code illustrating the issue?

**Comment by FKupsch** [comment]
Hi, 

thank you for your response. What I wanted to address is, how the classes which represent a Dicom Element of a special VR work. E.g. Dicom.DicomShortString. The VR restriction of SH is 16 characters maximum, but I can do something like this without getting a ArgumentException:

`new DicomShortString(DicomTag.AccessionNumber, "12345678901234567890"))`

Adding this to the Dataset will also not trigger any Exception. I am also allowed to create a DicomShortString like this: 

`new DicomShortString(DicomTag.AccessionNumber, "1234567890\\1234567890"))`

 It creates an attribute with VR=2, so maybe this is intended, but it is not what I would expect, when using the interface, since there are more conveniant ways to create an a attribute with VR>1 in your API. E.g. 

`new DicomShortString(DicomTag.AccessionNumber, "1234567890", "1234567890"))`

So I would suggest that at least when using  classes which represent a Dicom Element of a special VR to populate a Dataset, values of these data elements are strictly validated and ArgumentExceptions are thrown, when DICOM length and encoding restrictions for the VR are harmed. In some of those classes I recognized already some validation, e.g. DicomDate. It doesnt allow me to set something like this. 

`new DicomDate(DicomTag.StudyDate, "1234567890")`

Felix

**Comment by mia-san** [comment]
hi.

Regarding AccesionNumber, one of our site runs with AccessionNumber of 18 digits.
Their PACS happily accepts such rather invalid DICOM data.
Sadly, real world is not that ideal, we should be permissive to "invalid" data by default.

so, I would like to suggest something (off top of my head) like
```
class DicomValidator {

    bool Validate( DicomElement element ) {

        string values[] = element.Get<string>().Split(@'\');
        if (element.Count < values.Length) {
            return false;
        }

        for (string value in values) {

            if (element.ValueRepresentation == DicomVR.CS) {
                ...
            } else if (element.ValueRepresentation == DicomVR.DA) {
                ...
            }
        }

        return true;
    }
}
```
return false or throw ArgumentException as you like.

btw, may DicomVR have method to validate string representation of single value, like Validate(string) ?
above for loop could be simplified with the validation method like
  values.All( value => element.ValueRepresentation.Validate( value ) )

just an idea...
//

**Comment by FKupsch** [comment]
Hi, 

in my opinion a system that creates SOP instances should be as strict as pssible in enforcing encoding restrictions, while a system that consumes SOP instances should be as permissive as possible. So a PACS that accepts an 18 chars Accession Number should be the normal case, but this doesnt mean that nobody should care about VR restrictions. Otherwise connectivity problems with less permissive systems will be very likely. Or like the master of DICOM say: 

> no application creating DICOM instances should send values longer than the maximum (or which violate the standard in any way).

[https://groups.google.com/forum/#!msg/comp.protocols.dicom/Jhu--Utkb1w/nuFrLOfoKK8J](url)

For this reason I like your idea of having a validate function. static bool Validate(string value) in every DicomVR class or (may be better) having a validation on/off flag in the constructor. 

`DicomShortString(
	DicomTag tag,
	Encoding encoding,
	params string[] values,
        bool  validate = true
)`

Felix

**Comment by gofal** [comment]
So a possible solution could be:
the DicomElement classes shall have a validate method.
- the public DicomDataset.Add or DicomDataset.AddOrUpdate call this validate method, so that the applications creating new datasets are forced to only used validated tags.
- the internal DicomDatasetReaderObserver or DicomFileExtension.Clone and so on, that parse streams that are received by a DicomServer or read from a DicomFile, do not call the validate function to be permissive on invalid data.

Would that be fine?

**Comment by mia-san** [comment]
Great, as long as I can set value with or without validation.
we might want to set "illegal" value for various reasons...
//

**Comment by Ruairidh** [comment]
Hi all,

I'm encountering a similar issue when I try to use the JsonDicomConverter to serialize a dataset to JSON. I completely agree with @FKupsch's comment about when to be strict/permissive. If this validation mechanism is implemented then the json converter should be updated to use it since it currently fails trying to parse valid IS elements with buffers of more than 12 bytes to int, for example.
