### ISSUE TITLE
print scp PDU error with latest unity 3.5

### ISSUE THREAD

**Issue by rahulmakkar** [fo-dicom/fo-dicom#628]
in order to resolve association request issue #331 #584 i tried use unity 3.5 dicom.core with print scp desktop sample but it produces error at listen and process PDU Async.
Pls Suggest!
![fodicom error](https://user-images.githubusercontent.com/32870437/31933800-d0572292-b8c7-11e7-9b48-e4b2a70e779d.jpg)

**Comment by anders9ustafsson** [comment]
I assume you are using *fo-dicom* on an older version of Unity, i.e. 5.6 or earlier? Networking is only enabled in Unity 2017.1 and later, and you also need to select the .NET 4.6 profile in the Player settings.

**Comment by rahulmakkar** [comment]
hi, thanks for reply!
i compiled dicom.core.dll using unity 3.5 (with .Net 4.6) as i was trying with async ways to solve premature connection close issue on some modalities. i am testing on printscp desktop sample using iqview software. The dicom file from modality has been received and prints fine but the print remains in queue on modality side and shows association failed message.  attaching log info and error at iqview software end. kindly suggest!
[fodicom print scp async way.txt](https://github.com/fo-dicom/fo-dicom/files/1413545/fodicom.print.scp.async.way.txt)
![iqview error](https://user-images.githubusercontent.com/32870437/31984560-a120a0d0-b97f-11e7-83a4-798fce084622.png)

**Comment by gofal** [comment]
quite a lot of enhancements have been made on printing the last year.
Are you still facing this issue with the latest version of fo-dicom?
