### ISSUE TITLE
does fo- dicom support MPEG-4 AVC/H.264 High Profile / Level 4.1

### ISSUE THREAD

**Issue by piokon75** [fo-dicom/fo-dicom#629]
#does fo- dicom support MPEG-4 AVC/H.264 High Profile / Level 4.1 and other video transfer syntaxes

**Comment by anders9ustafsson** [comment]
@piokon75 Depends on what you mean by "support". *fo-dicom* have no problems parsing a DICOM object with videos contained in it and you can insert ready made video contents into the Pixel Data tag, but there is no support for viewing the video, nor for transcoding it into another transfer syntax.

**Comment by FKupsch** [comment]
How can I encapsulate the video buffer in the Pixel Data. 

I tried this;

dataset.AddOrUpdatePixelData(DicomVR.OB, buffer, DicomTransferSyntax.MPEG2);

But after saving the file, the pixel data are not encapsulated.

**Comment by anders9ustafsson** [comment]
@FKupsch When you are using that method, you are supposed to have encapsulated the data in the buffer *before* you add it to the dataset. There is better support for adding encapsulated fragments via the `DicomPixelData` class, although I don't have any good example of this straight away. Anyhow, *fo-dicom* does not include video codecs, so video encoding always needs to be done manually with *fo-dicom*.
