### ISSUE TITLE
Render image as Bitmap .net Core

### ISSUE THREAD

**Issue by bingestam** [fo-dicom/fo-dicom#631]
Hi all.

I'm trying to use fo-dicom to convert dicom files to jpgs.
I had no problems doing it in regular .net Framework 4.5.
But moving to .net core the absence of System.Drawing made it problematic.
Tried two different nuget packages:

https://www.nuget.org/packages/CoreCompat.System.Drawing/
and
https://www.nuget.org/packages/CoreCompat.System.Drawing.v2/5.2.0-preview1-r131

RenderImage throws same Exception with both packages.

Do anyone know a way to convert dicom to jpgs using .net Core only?

### Expected behavior
No runtime Errors

### Actual behavior
Code halts at:
image.RenderImage().As<Bitmap>();
With Exception:
Dicom.Imaging.DicomImagingException: 'Cannot cast to 'Bitmap'; type must be assignable from 'Byte[]''

### Steps to reproduce the behavior
.Net Core 2.0 project
and
https://www.nuget.org/packages/CoreCompat.System.Drawing.v2/5.2.0-preview1-r131

### fo-dicom version and OS/platform
fo-dicom 3.0.1 / Windows 10

**Comment by anders9ustafsson** [comment]
@bingestam You need to use the 3.1.0-alpha version of *fo-dicom.NetCore*, together with the *fo-dicom.Drawing* package. The *Drawing* package will automatically include the *CoreCompat.System.Drawing* package.

For .NET Core, *System.Drawing* rendering is not default, so you also need to manually set the relevant image manager instance: 

    ImageManager.SetImplementation(WinFormsImageManager.Instance);

Then, you can use the `AsBitmap()` extension method to convert the rendered DICOM image into a bitmap, and you can subsequently save it e.g. as a JPEG.

**Comment by bingestam** [comment]
Yey! Thank you for fast reply.

**Comment by anders9ustafsson** [comment]
@Styp Not sure what you mean? The *fo-dicom.NetCore* package is a .NET Standard 1.3 package which should be executable on all .NET Core implementations, including Linux and headless environments. The *Bitmap* implementation is outside of this package, located in *fo-dicom.Drawing*. Currently it is limited to those platforms that support the *CoreCompat.System.Drawing* package (Windows, iOS, Android), but once Microsoft provides a *System.Drawing* official NuGet package I believe that this would be compatible with all .NET Core targets.
