### ISSUE TITLE
Any estimates on availability of 16-bit compression on .Net Core?

### ISSUE THREAD

**Issue by davekiwi** [fo-dicom/fo-dicom#632]
Hi all,

I am looking to implement an application on a Gateway Device running Windows IoT Core. A .NetCore application is the best choice for integration with Azure IoT Edge, but I understand that this implementation in fo-dicom does not have 16-bit support for JPEG-2000 and JPEG-LS compression. Is there any estimate of when and if this might be available? (if it is a way off that I will stick with the UWP approach instead).

Thanks for any guidance!

Dave

**Comment by anders9ustafsson** [comment]
@davekiwi The 3.1.0-alpha pre-release on NuGet should support 16-bit JPEG2000 (decoding and encoding) and JPEG-LS (decoding). It does **not**, however, support *Lossless JPEG*! Please note that JPEG-LS and Lossless JPEG are **different** transfer syntaxes, there is often confusion with regards to this.

**Comment by davekiwi** [comment]
Thanks Anders - I always thought that JPEG-LS with NEAR set to 0 was effectively the same as JPEG-LS Lossless. But in any case we need the encoding part, so that won't be an option for us.

Regarding JPEG2000, is the situation the same, i.e. will JPEG 2000 (...2.4.91) be supported but not JPEG 2000 Lossless only (...2.4.90)? We need a lossless solution for our application. I should have asked this question in the first place, sorry.

Thanks for your help, both of this and you fantastic efforts on the toolkit in general.

Dave

**Comment by anders9ustafsson** [comment]
@davekiwi The JPEG-LS implementation for .NET Core does support both near lossless and true lossless (DICOM transfer syntaxes 1.2.840.10008.1.2.4.80 and 1.2.840.10008.1.2.4.81, see e.g. [this](https://www.dicomlibrary.com/dicom/transfer-syntax/) list). Encoding is included but unfortunately very buggy; it is not in any way reliable. 

JPEG2000, both lossless and lossy is included (transfer syntaxes 1.2.840.10008.1.2.4.90 and 1.2.840.10008.1.2.4.91). 

When I am mentioning Lossless JPEG, I am referring to the transfer syntaxes 1.2.840.10008.1.2.4.57 (Process 14) and 1.2.840.10008.1.2.4.70 (Process 14 SV1), and these syntaxes are not at all supported e.g. on .NET Core. They are *only* supported on .NET Framework and UWP.

**Comment by davekiwi** [comment]
Ok, that's good news. I don't really want to have to support the process 14 stuff, so that's all good. JPEG2000 Lossless will be the best choice for us going forward. Thanks again! Dave

**Comment by zcr01** [comment]
@anders9ustafsson is there any plan to bring Lossless JPEG (Process 14) to .NET Core?  (Is there a reason this is difficult?)

**Comment by buertlh** [comment]
@anders9ustafsson   is there any plan to bring Lossless JPEG (Process 14) to .NET Core? Do you have any suggestions about implementing this function? Thanks
