### ISSUE TITLE
Unable to send CT image from new Siemens CT

### ISSUE THREAD

**Issue by hashitha** [fo-dicom/fo-dicom#635]
I am trying to send a study with 1600+ images from a new CT machine. All images go through except one which causes an exception. I have tested with 3.1.0 Alpha and 3.0.2

```
                var cMoveclient = new DicomClient();
                string dicomFileName = @"C:\\data\test.dcm";
                DicomCStoreRequest req = new DicomCStoreRequest(dicomFileName ); 
                req.OnResponseReceived += (r, q) =>
                {
                    Console.WriteLine(q.Status); 
                };
                cMoveclient.AddRequest(req);


                cMoveclient.Send("192.168.0.25", 4096, false, "PACS1", "OSIRIX");
```

I have attached the DICOM file that causes the error.

[test.zip](https://github.com/fo-dicom/fo-dicom/files/1474523/test.zip)

![image](https://user-images.githubusercontent.com/10569142/32834426-874a2a18-ca3d-11e7-9127-759d976a5429.png)

**Comment by hdesouky** [comment]
It seems that the modality is aborting your request. I understand you are sending images to the modality. To find out why this happen you need to check the conformance statement of the modality to find out the required and mandatory dicom attributes of the images you want to send.
If you have access to the modality log it will give you more hint why the association aborted.

*I just wonder why you want to store images in the modality!*

**Comment by hashitha** [comment]
@hdesouky I am not sending to the modality. The DICOM files received fine from modality to fo-dicom. The issue happens when I am trying to send the images from fo-dicom to another destination such as Osirix. When sending it is only one file that is the problem. I have tried sending different studies and all of them have one or two files that cause this issue.

**Comment by hashitha** [comment]
This could be a similar to #581

**Comment by hdesouky** [comment]
Check Osirix Log, to find out why it is C-Abort your Association

**Comment by hdesouky** [comment]
According to #581 this seems to be a malformed file, try to open it using fo-dicom and render it to an image, i bit it will fail too.

**Comment by hashitha** [comment]
I have checked and the file works on other viewers and editors. This doesn't happen with just this file, this is just one I have attached. Nothing on OsiriX log

**Comment by hdesouky** [comment]
Can you open  the file inside Osirix directly (direct open)

**Comment by hashitha** [comment]
Yes, it opens fine in Osirix, Weasis and MicroDicom. I have attached the file you can see for your self.

**Comment by hdesouky** [comment]
Is it open fine using fo-dicom?

**Comment by Zaid-Safadi** [comment]
I agree with @hdesouky, the logs says you are receiving an "abort" message which is forcing the connection to close. You should check Osirix logs and it hopefully will explain why it is aborting the Store request.

**Comment by hashitha** [comment]
@Zaid-Safadi I have checked the Osirix logs and it doesn't show anything. This file works with all other systems, just not fo-dicom send

**Comment by FKupsch** [comment]
There is something strange in this file. DVT tells me that the tags are not sorted in ascending tag order, which is probably the reason for the abort by osirix, if it is true.

**Comment by hashitha** [comment]
@FKupsch are you sure? because I sent this file directly from the Modality to OsiriX and it worked fine. As a workaround, I have set the CT to send directly to OsiriX which works well for all cases instead of CT > Fo-Dicom > OsiriX which causes problems. Could this be a problem with fo-dicom receiving and saving the file incorrectly?

**Comment by BobSter3000** [comment]
@hashitha Have you tried to compile and use the Development Branch?  This looks like it is the issue reported 581 where the Private tags are out of order.  I do not have Osirix to test, but I have encountered the same issue with other systems.

**Comment by hashitha** [comment]
@BobSter3000 you are right this is indeed fixed in the development branch.
