### ISSUE TITLE
Saving DicomFile containing specific sequence tag corrupts the file, not able to open it again

### ISSUE THREAD

**Issue by SrividyaTR** [fo-dicom/fo-dicom#639]
### Expected behavior
Opening a dicom file and saving it should not alter any tags. Also, it should be possible to open the saved file using fo-dicom

### Actual behavior
On saving this specific dicom file that contains sequence tags, the tag gets modified. Due to this, we cannot open the saved file any longer

### Steps to reproduce the behavior
                DicomFile dicomfile = DicomFile.Open(@"d:\input.dcm");
                dicomfile.Save(@"D:\output.dcm");
                dicomfile = DicomFile.Open(@"D:\output.dcm");
Opening output.dcm results in attached exception.

### fo-dicom version and OS/platform
fo-dicom.Desktop.3.0.2
Windows 7 .NET framework 4.5.2
[Exception.txt](https://github.com/fo-dicom/fo-dicom/files/1481301/Exception.txt)
[input.zip](https://github.com/fo-dicom/fo-dicom/files/1481302/input.zip)

**Comment by FKupsch** [comment]
Hi,

the input file has an invalid encoding. Please have a look on your data element and item lengths. 

http://dicom.nema.org/medical/dicom/current/output/html/part05.html#sect_7.5

**Comment by SrividyaTR** [comment]
Hi,

Thanks for your inputs. This is how the customer is sending data to our application, We were able to temporarily resolve this issue by using the below options 
                DicomWriteOptions options = new DicomWriteOptions();
                options.ExplicitLengthSequenceItems = true;
                sourceFile.Save(newFile, options);

Do you think that this approach would be fine to use in general for saving images?
Or should we follow up with the customer regarding the invalid encoding of their dataset?

**Comment by gofal** [comment]
I think you should not generally use the ExplicitLengthSequenceItems. Only if necessary.
Of course it would be best to contact the customer so that they fix the invalid encoding. The goal should be that they send valid encoding.
Since this is no bug in fo-dicom but on the customers side and there is already a workaround, this is no more an issue for fo-dicom.
