### ISSUE TITLE
Problem to parse a specific Dicom file

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#64]
Originally reported by Gustavo Saita as issue cureos/fo-dicom#6, but applies to desktop *fo-dicom* as well. Here is excerpt from conversation:

*Gustavo, Aug 29, 2014:*
> I'm using it, and I figured out a problem to open a specific Dicom file.
> I'm trying to use DicomFile.Open, but it never returns the DicomFile. :(
> I've tried to find the problem but I didn't have success until now.
> I noted that OnDatasetParseComplete never reaches.

> I'm sharing with you the [file](https://cloud.githubusercontent.com/assets/5712720/4086073/cbead89e-2f2b-11e4-9bc8-a5d8e9ee2fef.jpg).
> Note that I change the extension to jpg just to upload the file here. (Please, rename it to .dcm if you want)

> Any idea what could be the problem? Please, let me know if you have any news!

*Anders, Aug 29, 2014:*
> I will try to have a look at this as soon as possible. For the time being, is this the only file you are having problems with? Which platform are you targeting, Windows 8 or Windows Phone?

*Gustavo, Aug 29, 2014:*
> I've already tested hundreds of series of many patients of many modalities and until now I had no problem at all, except with this specific patient. All images of all series of this kind of patient have the same problem. I thought that was a problem in those files, so I tried to open with some Dicom viewers, but it opened normally.

>Currently I'm working with Windows 8 App.
>Another detail is that neither exception was fired too in any func of DicomFile.cs or DicomReader.cs.

*Anders, Aug 6, 2015*
>I have come so far as to note that parsing goes into an infinite loop when/after parsing tag (2005,143e). The parser recognizes that a milestone has been reached, and thereafter gets trapped in a loop. Testing on other viewers, it appears like these viewers discards the item with this specific tag?

**Comment by dhanzhang** [comment]
@anders9ustafsson    try this !
private void ParseItemSequence(IByteSource source, object state)
        {
            try
            {
                _result = DicomReaderResult.Processing;

                while (!source.IsEOF && !source.HasReachedMilestone())
                {
                    if (_state == ParseState.Tag)
                    {
                        source.Mark();

                        if (!source.Require(8, ParseItemSequence, state))
                        {
                            _result = DicomReaderResult.Suspended;
                            return;
                        }

                        ushort group = source.GetUInt16();
                        ushort element = source.GetUInt16();

                        _tag = new DicomTag(group, element);

                        if (_tag != DicomTag.Item && _tag != DicomTag.SequenceDelimitationItem)
                        {
                            // assume invalid sequence
                            source.Rewind();
                            if (!_implicit)
                            {
                                source.PopMilestone();
                            }
                            _observer.OnEndSequence();
                            if (_badPrivateSequence)
                            {
                                _explicit = !_explicit;
                                _badPrivateSequence = false;
                            }
                            return;
                        }

                        _length = source.GetUInt32();

                        if (_tag == DicomTag.SequenceDelimitationItem)
                        {
                            // end of sequence
                            _observer.OnEndSequence();
                            if (_badPrivateSequence)
                            {
                                _explicit = !_explicit;
                                _badPrivateSequence = false;
                            }
                            ResetState();
                            {
                                //////////////////////////////////////////////////////////////  
                                //////////////////////    this is not a good idea !
                                //////////////////////////////////////////////////////////////
                                if (!source.Require(4, ParseDataset, state))
                                {
                                    return;
                                }
                                source.Mark();
                                var g = source.GetUInt16();
                                if (g != 0xFFFE)
                                {
                                    source.Rewind();
                                    ResetState();
                                    ParseDataset(source, state);
                                    ResetState();
                                }
                               ////////////////////////////////////
                            }
                            return;
                        }

                        _state = ParseState.Value;
                    }

                    if (_state == ParseState.Value)
                    {
                        if (_length != UndefinedLength)
                        {
                            if (!source.Require(_length, ParseItemSequence, state))
                            {
                                _result = DicomReaderResult.Suspended;
                                return;
                            }

                            source.PushMilestone(_length);
                        }

                        _observer.OnBeginSequenceItem(source, _length);

                        ResetState();
                        ParseDataset(source, state);
                        ResetState();

                        _observer.OnEndSequenceItem();
                        continue;
                    }
                }

                // end of explicit length sequence
                if (source.HasReachedMilestone())
                {
                    source.PopMilestone();
                }

                _observer.OnEndSequence();
                if (_badPrivateSequence)
                {
                    _explicit = !_explicit;
                    _badPrivateSequence = false;
                }
            }
            catch (Exception e)
            {
                _exception = e;
                _result = DicomReaderResult.Error;
            }
            finally
            {
                if (_result != DicomReaderResult.Processing && _result != DicomReaderResult.Suspended)
                {
                    _async.Set();
                }
            }
        }

**Comment by anders9ustafsson** [comment]
Many thanks, @dhanzhang , it works! Could you explain in more detail what the added code block does?

**Comment by dhanzhang** [comment]
![20150909144647](https://cloud.githubusercontent.com/assets/457633/9755092/adaa4f50-5701-11e5-8f19-288baf2280f9.png)

**Comment by dhanzhang** [comment]
it  is ugly   .

**Comment by dhanzhang** [comment]
@anders9ustafsson    
 //////////////////////////////////////////////////////////////  
                            //////////////////////    this is not a good idea !
                            //////////////////////////////////////////////////////////////
                            if (!source.Require(4, ParseDataset, state))
                            {
                                return;
                            }
                            source.Mark();
                            var g = source.GetUInt16();
                            source.Rewind();
                            if (g != 0xFFFE)
                            { 
                                ResetState();
                                ParseDataset(source, state);
                                ResetState();
                            }
                           ////////////////////////////////////

**Comment by anders9ustafsson** [comment]
@dhanzhang Yes, thank you, I recognized that this was the added part. It would be good if you can explain what this code block does and how general it is. Is it just working for this problematic file, or can it detect other problems as well? Why are you comparing against `0xFFFE`?

**Comment by dhanzhang** [comment]
http://medical.nema.org/Dicom/2011/11_06pu.pdf   
(FFFE,E000)  Item                                                 Item                                     see note 1
(FFFE,E00D)  Item  Delimitation Item                    ItemDelimitationItem            see note 1
(FFFE,E0DD) Sequence Delimitation Item             SequenceDelimitationItem   see note 1

 I think this bug  raised by  detect  Milestone,  but  there is not enough DCM files to test .  
I'm  to trying other  solutions.

**Comment by anders9ustafsson** [comment]
OK, @dhanzhang , many thanks for looking into this issue. Yes, I also suspect that there is a "milestone" problem with this file. If you are able to come up with a solution that is able to detect the "milestone" error explicitly, that would be fantastic.

**Comment by rcd** [comment]
Does the file load if you disable the private dictionary?

**Comment by anders9ustafsson** [comment]
Unfortunately, disabling the private dictionary does not help up the situation, the loading still freezes. It appears like the DICOM file contains a sequence delimitation item "out of nowhere", i.e. it is malformed. It still would be good if *fo-dicom* parsing could be reliable enough to ignore this local error in the DICOM file.

**Comment by rcd** [comment]
Disabling the private dictionary works for me...

![image](https://cloud.githubusercontent.com/assets/280475/9836877/0526cf1a-59f0-11e5-908f-5b66c5bee24a.png)

**Comment by anders9ustafsson** [comment]
OK, I'll try again. Maybe I didn't press the SHIFT button hard enough :-)

**Comment by anders9ustafsson** [comment]
I stand corrected. Thanks, Colby!
Still, can we use this finding to implement a more fail-safe parsing even if the private dictionary is loaded? Right now it is not completely obvious to me how we can go about to accomplish this.

**Comment by rcd** [comment]
For this file I feel like the default behavior should be to throw an exception straight to Philips engineering. ;-)

It looks like you removed the exceptions from the Require() implementations.  They would have thrown an exception which would have been caught and turned into a DicomFileException which contains the parsable part of the dataset.  The way the implementation is now, the parser gets stuck in a loop for this particular file.

Until the file can automatically be handled (without adding code with the potential of breaking other files), an error message would be the recommended action from my perspective.

I know that isn't ideal, but this is a very oddball file.

**Comment by anders9ustafsson** [comment]
If I remember correctly, for this particular file the `Require()` exceptions did not help, it did the endless loop thing regardless.

I skipped the `throw` in the `Require` method to instead allow for the calling code to handle a `false` return value. This allowed sufficient parsing of some files that were otherwise rejected (#42, #47, #58).

But yes, error message is of course preferred to an endless loop if we can't find a reliable solution for parsing this file completely.

**Comment by rcd** [comment]
I would try to figure out what tag it is actually getting hung up on and make sure that it is correct in the private dictionary.  Maybe it is trying to parse it as something that it isn't?

**Comment by anders9ustafsson** [comment]
The problems start after tag *(2005,143e)*. From the private dictionary:

> &lt;tag group="2005" element="xx3e" vr="SL" vm="1-n"&gt;Unknown&lt;/tag&gt;

As @dhanzhang showed [above](https://github.com/fo-dicom/fo-dicom/issues/64#issuecomment-138806200), value representation is not present for this particular tag. Length is set to 4 bytes. Following the 4 bytes of data is a (misplaced) sequence delimitation item tag *(FFFE, E0DD)*. When this tag is reached, the parser interprets it as a milestone, and (I believe) the milestone stack then becomes unsynchronized. After this, no more tags are identified but the parser enters an infinite loop.

**Comment by Ed55** [comment]
My two cents:
For my understanding there is clearly a DICOM violation in the private sequence 2001,105F if you try (with the knowlegde of a private dictionary) to parse it as SQ.
When you take it as UN, all is fine. When you take it as  SQ the Sequence Delimiter starting at file pos 0x1510 is illegal because its no sequence with undefined length.

Pobably this instance was previously converted from implicit incorrectly as an explicit Achieva instance contains three items ins this sequence without this delimiter. (OK, the instance I could get hold of is dated 2013).

The three items each end with the tag xx3e which might give you the impression of an endless loop.
For my understanding the code steps out taking the Sequence Delimiter as another "popper", in this case ending the ParseProc whithout _async.Set().

I have no solution yet, but I think one could add a handling (in ParseItemSequence) like
if (_tag= DicomTag.Item && _tag != DicomTag.SequenceDelimitationItem) {
	// assume invalid sequence

as
if(_tag == DicomTag.SequenceDelimitationItem && "mySequenceIsNotUndefinedLength") {
	// assume invalid SequenceDelimitationItem 
...

**Comment by anders9ustafsson** [comment]
@Ed55 Splendid, many thanks for this thorough investigation. It really gives us something to work from. If you also manage to verify that your proposal works, do not hesitate to let us know :-) It would be just terrific if this issue could be solved before the release of 2.0.

**Comment by Ed55** [comment]
As I could not find a simple way to achieve  "mySequenceIsNotUndefinedLength" ( see my previous comment) I tried workarround:

In ParseItemSequence I extended the SequenceDelimitationItem handling:

						if (_tag == DicomTag.SequenceDelimitationItem) {
                            //Solve issue #64 with  invalid SequenceDelimitationItems in the end of (private) sequences with known length
                            if (source.HasReachedMilestone()) {
                                //not sure about this
                                if (_badPrivateSequence)
                                {
                                    _explicit = !_explicit;
                                    _badPrivateSequence = false;
                                }
                                ResetState();
                                //just continue and next you will reach the milestone
                                continue;
                            }
							// end of sequence
							_observer.OnEndSequence();
							if (_badPrivateSequence) {
								_explicit = !_explicit;
								_badPrivateSequence = false;
							}
							ResetState();
							return;
						}


(Sorry for the layout)
If you place a breakpoint into the additional stuff you will find a lot more of this issues within this test file ;-).

I performed just a few tests. Some of my "funny DICOM collected during my career" are failing, but this is because I am normally using some more tweaks ( build into a much ealder code base ).
May I popose those later.

Anyway, please give it a try ...

**Comment by anders9ustafsson** [comment]
Many thanks @Ed55 for so observantly identifying the root cause of this issue. I have now posted a pull request #135 with your solution, adapted to the 2.0.0 implementation.

**Comment by Ed55** [comment]
You are wellcome, glad I could help out.
I will try 2.0.0 when I have some more spare time :-|

According to my experience life gots much more easier if you not try to dig into privates because most of the violations happen in this area. Except you want to validate, fix or need to interpretate private tags of course.
As shown here: If you would have taken it as UN (as originally stated) you would not have noticed that there is an issue.
