### ISSUE TITLE
Can/should JsonDicomConverter be modified accept numeric values with no leading zero, e.g. ".03"?

### ISSUE THREAD

**Issue by davekiwi** [fo-dicom/fo-dicom#643]
In the JsonDicomConverter class, the following regular expression is used in the IsValidJsonNumber() method to determine if an attribute value is a valid json number:

return Regex.IsMatch(val, "^-?(0|[1-9][0-9]*)([.][0-9]+)?([eE][-+]?[0-9]+)?$")

Unfortunately, we have found a number of mammography images in the field (manufacturer names will not be mentioned!), where an DS value is encoded as something like ".03" (i.e. has no leading zero).

Would it possible (and appropriate?) to change the regular expression above to accommodate this? I am not an expert on Regex, but I think this would mean adding in the extra ? as the sixth character below:: 

return Regex.IsMatch(val, "^-?(0?|[1-9][0-9]*)([.][0-9]+)?([eE][-+]?[0-9]+)?$")

Right now I have written a DicomDatasetWalker to run over our inputs and fix this issue before they are passed to the JSON conversion, but of course this is a bit clunky.

Thanks, Dave

**Comment by Cregganbane** [comment]
I don't have a strong position on this but an IS value should be a decimal integer string. See http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html 
Your example ".03" - what does the decimal point indicate? There is no scope for this in the official value representation. What DicomTag(s) does this occur on?

**Comment by davekiwi** [comment]
This occurs in the Pixel Spacing attribute of one particular manufacturer of mammography images. I agree that it is not legal DICOM, and as such, I am OK with this change not being made in the toolkit. For now, I have made our own local version of the DICOM JSON converter that accepts this (using the proposed solution), rather than the DatasetWalker which had more implementation risk, since we have no option but to support this scanner. We can continue to use our own custom implementation as long as this machine exists. I don't really like maintaining our own stuff though - it requires us to be vigilant to toolkit changes in that class and merge them in as we move forward.

**Comment by Cregganbane** [comment]
As a DS VR then I think your change is valid and that this encoding is allowed. Clunie "who God himself asks about DICOM" proclaims: https://groups.google.com/forum/#!topic/comp.protocols.dicom/j-z_YVbLtUQ
I'm not a regex expert but this looks like a valid change.

**Comment by davekiwi** [comment]
Nice sleuthing! Yes, I agree that this change should therefore be implemented. And possibly check that "+.03" and "-.03" are accepted also - it looks from the Regex that a leading + may be rejected currently.

**Comment by gofal** [comment]
could this be?
"^**[+-]**?(0?|[1-9][0-9]*)([.][0-9]+)?([eE][-+]?[0-9]+)?$"
only thing is, that now with all the optinal values also a empty string would be a valid DS. either somehow add this test for non-empty into the regex or the c#-code tests for not-null before applying the regex.

**Comment by JoostJM** [comment]
You can also incorporate this in the Regex:
`^[+-]?((0|[1-9][0-9]*)([.][0-9]+)?)|([.][0-9]+)([eE][-+]?[0-9]+)?$`
The first group (`((0|[1-9][0-9]*)([.][0-9]+)?)`) handles all cases of numbers > 1 and fractals with a leading 0, the second group (`([.][0-9]+)`, notice it is not optional here) handles the cases of fractals without a leading 0. The pipe symbol between the 2 groups ensures you either choose the one or the other.
