### ISSUE TITLE
Problem rendering multiframe image

### ISSUE THREAD

**Issue by WernMich** [fo-dicom/fo-dicom#645]
### Expected behavior
Image is rendered correctly (even if there are errors in IOD) as in microDicom or Offis Toolkit.

### Actual behavior
Images are rendered wrong (first frame ok, then the offset seems to become calculated wrong so the output looks strange).

### Steps to reproduce the behavior
Create DicomImage object from attached DCM and create System.Drawing.Bitmap of it and display them or store them in file system.

### fo-dicom version and OS/platform
Win 10 Pro 64-Bit, .NET 4.5.2, fo-dicom v3.1.0-alpha / 3.0.2 (both versions affected)
[PixelDataError.zip](https://github.com/fo-dicom/fo-dicom/files/1535813/PixelDataError.zip)

**Comment by FKupsch** [comment]
Hi Michael,

I checked your image and I suppose the problem is related to an incorrect value of the transfer syntax attribute in your image header. The attribute says that the image is encoded in 1.2.840.10008.1.2 Implicit Little Endian, while the image is obviously encoded in a compressed TS, which is indicated by the value of photometric interpretation and the image size. 

I can see that you use an outdated version of dcm4che to store the image and I remember that this was an issue in dcm4che. You should try to store the image with a different tool. Do you now the original TS of your image? 

Best regards
Felix

**Comment by WernMich** [comment]
Hi Felix,

thank you for your response! 

I do not really know the original TS of the image. microDicom stores it in Explicit Little Endian with a value of "RGB" in photometric interpretation tag and this is correctly processed by fo-dicom then. But maybe microDicom performs an uncompression implicitly. 

Do you know a workaround how I can deal with the image and fo-dicom even if it's picture / compression information is wrong?

Best regards,
Michael

**Comment by FKupsch** [comment]
Hi Michael,

nope guessing the transfer syntax of an image could be an interesting project, but with DICOM conformat tools there should be no need for this. What is the origin of your image? Maybe its DICOM Conformance Statement gives you the required information?

Felix

**Comment by WernMich** [comment]
Hi Felix,

thanks again, I think that's enough information for my PM. Real DICOM conformance is nice but not always given and we have to deal with corrupt images too (maybe). They will say sth. like: microDicom and Offis Toolkit can handle it ...

I do not know the origin, this are old test data which where imported years ago by unknown people ;)

Best regards,
Michael

**Comment by gofal** [comment]
I will close this issue because of inactivity. If this issue is still relevant then please feel free to reopen it again and add some updates.

**Comment by WernMich** [comment]
@FKupsch 30 months later I am struggling with the same issue again.

I noticed that several Dicom Image viewers can display all frames of the image correctly (different platforms and technologies). I am very sure that the origin of the problem is in Fo-Dicom library and not in the Dicom file / dataset. I got the same image stored via "OFFIS_DCMBP_354". If this image is processed with Fo-Dicom the frames look strange too.

And I do not think that the transfer syntax of the dataset is different than "Explizit VR little endian". Please see [Link](https://www.medicalconnections.co.uk/kb/Photometric-Interpretations/) regarding "YBR_FULL_422" photometric interpretation. The size of pixel data is divisible by four. The first frame looks ok, this should not be the case if it is compressed anyway but read uncompressed.

I would very much appreciate to reopen this issue again and to have a deeper look again in this issue.

**Comment by WernMich** [comment]
Here a small snapshot of Offis Toolkit "dcm2pnm" tool, which is exporting all frames correctly (log level trace):
Command line: dcm2pnm.exe -ll trace +on +Fr 1 24 PixelDataError.dcm frame

Log output regarding pixel data:

D: transfer syntax of DICOM dataset: Little Endian Explicit (1.2.840.10008.1.2.1)
T: DcmItem::searchSubFromHere() Element (7fe0,0010) found
T: DcmItem::searchSubFromHere() Element (0028,0004) found
T: DcmItem::searchSubFromHere() Element (0008,0016) found
T: DcmItem::searchSubFromHere() Element (0028,0008) found
T: DcmItem::searchSubFromHere() Element (0028,0010) found
T: DcmItem::searchSubFromHere() Element (0028,0011) found
T: DcmItem::searchSubFromHere() Element (0028,0100) found
T: DcmItem::searchSubFromHere() Element (0028,0101) found
T: DcmItem::searchSubFromHere() Element (0028,0102) found
T: DcmItem::searchSubFromHere() Element (0028,0103) found
T: Pixel Data VR: OW, Uncompressed (LittleEndianExplicit)
T: First frame: 0, Number of frames: 24, Total number of frames: 24
T: Columns: 576, Rows: 456, Samples per Pixel: 2, Photometric Interpretation: YBR_FULL_422
T: Bits Allocated: 8, Bits Stored: 8, High Bit: 7, Unsigned integer
D: reading uncompressed pixel data completely into memory
T: Input length: 12607488 bytes, Pixel count: 12607488 (12607488), In: 16 bits, Out: 8 bits (unsigned)
D: convert input pixel data: case 2a (simple mask)
D: detach pixel data
T: DcmItem::searchSubFromHere() Element (0028,0002) found
T: DcmItem::searchSubFromHere() Element (0028,0006) found
I: writing frame 1 to out.0.png
D: converting color pixel data to output format
I: writing frame 2 to out.1.png
D: converting color pixel data to output format

**Comment by WernMich** [comment]
> I will close this issue because of inactivity. If this issue is still relevant then please feel free to reopen it again and add some updates.

Hi Reinhard, I could not reopen this issue. Can you please reopen it?

**Comment by WernMich** [comment]
Because of the fact, that the first frame is rendered correctly and starting with the second frame, the frames seem to be shifted by 50% I suppose there is an error calculating the offset of the frame(n) where n > 0 (zero-based). It looks like a conversion to RGB is done (which creates 150% data of the source YBR data, see [Avery Lee's JFIF Clarification](http://www.fourcc.org/fccyvrgb.php)) And the offset is taken from RGB data, not from initial, unconverted YBR data.

**Comment by WernMich** [comment]
After further investigation I found the error in Fo-Dicom code. First, see following Dicom definition [YBR_FULL_422 -> Note 2.](https://dicom.innolitics.com/ciods/mr-image/image-pixel/00280004)

Instead of samples per pixel (3 in this case), 2 should be used as factor for pixel data size calculation, because they become downsampled. If pixel data size is calculated wrong, the offset is calculated wrong too.

**Comment by WernMich** [comment]
@gofal I have implemented a solution in DicomPixelData.cs in property `UncompressedFrameSize`. I would like to push my implementation so could you please add me to the contributors?

**Comment by WernMich** [comment]
@gofal Sorry, I never made changes outside of my own repositories on github. I made changes in a new fork called "WernMich": https://github.com/WernMich/fo-dicom/blob/development/DICOM/Imaging/DicomPixelData.cs

Now I do not know how to continue. I wanted to create a pull request (the first ever for me) but it always fails somehow.

My git command: `git request-pull origin/development https://github.com/fo-dicom/fo-dicom development`
Console out is:
warn: No match for commit 5f3eaa75b0c4774694eccdfe400b2becabe9f991 found at https://github.com/fo-dicom/fo-dicom
warn: Are you sure you pushed 'development' there?
The following changes since commit 5f3eaa75b0c4774694eccdfe400b2becabe9f991:

  Fix issue #645: uncompressed YBR_FULL_422 images have to use factor 2 instead of the value of SamplesPerPixel (3) to calculate pixel data length or frame offset (2020-07-27 12:16:48 +0200)

are available in the Git repository at:

  https://github.com/fo-dicom/fo-dicom development

for you to fetch changes up to 5f3eaa75b0c4774694eccdfe400b2becabe9f991:

  Fix issue #645: uncompressed YBR_FULL_422 images have to use factor 2 instead of the value of SamplesPerPixel (3) to calculate pixel data length or frame offset (2020-07-27 12:16:48 +0200)

----------------------------------------------------------------

Could you please help me?
