### ISSUE TITLE
UserState is sometimes null in custom DicomProvider when testing under heavy load

### ISSUE THREAD

**Issue by bartkanis** [fo-dicom/fo-dicom#646]
### Expected behavior
When creating a custom DicomProvider it is possible to add a custom UserState object when creating the DicomServer instance.

`DicomServer.Create<CustomCStoreProvider>(port, custumUserStateObject, ...)`

This UserState object is then available in the CustomCStoreProvider methods. Unfortunately not in the constructor, because it set just after constructing (DicomServer.cs line 220).

### Actual behavior
When sending Dicom objects with a couple of associations at the time it works fine. We found out that sending lots of objects, one per association, in many threads at the same time causes problems with the UserState object. I tested 50 threads sending one object per association for a couple of hundred objects to be processed in a row per thread.  One object per association using DcmTk storecsu to send each object. 
When the UserState object was null it seems that implementations of IDicomCStoreProvider methods were call before even the constructor of the base DicomService and the CustumDicomService was not finished or called. I could not figure out how this is happening.
I fixed the problem by taking out the UserState object from the DicomServer create method, made it static :-( and use it  from by CustomCStoreProvider directly,

 ### Steps to reproduce the behavior
Just send hunderds of Dicom objects (mix of CT, RTPlan, RTStuct and RTDose objects) one per association and about 50 threads in parallel. I used just my PC no other systems were involved. 

### fo-dicom version and OS/platform
fo-dicom.Desktop.3.1.0-alpha
Windows 7 / .NET 4.5.2

**Comment by gofal** [comment]
This issue has bin already been fixed in development branch.
