### ISSUE TITLE
C-Move failure - cannot understand error

### ISSUE THREAD

**Issue by SrividyaTR** [fo-dicom/fo-dicom#648]
### Actual behavior
At times, sporadically, we get C-Move response with 
       Status: Failure [c000: Cannot understand], 
       Description:Cannot understand, 
       Code:49152, 
       ErrorComment: 

How can we find out what exactly leads to such errors?  Why is ErrorComment empty in such cases? And how can we resolve such errors?

### fo-dicom version and OS/platform
fo-dicom.Desktop.3.0.2
Windows 7 .NET framework 4.5.2

**Comment by deyung** [comment]
The error message is from the SCP, it's a pretty standard response message. If you have your C-Move request setup properly with the minimum requirements it should work just fine, in the past, I've seen this message from systems that don't support C-Moves, although it maybe a DICOM listening port, it may not support C-Moves.

I would make sure that your C-Move request has the correct parameters including Study UID and Destination AE, and check with the SCP provider if that is the correct port to send C-Move requests.

**Comment by SrividyaTR** [comment]
We have setup the CMove request correctly and the SCP provider also responds fine most of the time.

But sporadically, we start getting the above mentioned error and after sometime, the problem gets rectified. In this case, it is not clear to us if these intermittent errors is because of some problem on the SCU side or SCP side and why exactly it starts to fail. In this case, how can we figure out the root-cause of such intermittent failures?

**Comment by FKupsch** [comment]
Maybe the Conformance Statement of the PACS can give you more information. It should list potentially send errors and meanings. Other source of information could be the PACS log.

**Comment by Cregganbane** [comment]
Have you tried swapping out the SCP for another e.g. dcmtk? Might help isolating the issue if you have a reproducible test.

**Comment by gofal** [comment]
See issue #616 : fo-dicom internally maps every status code to one of the known status codes. so the PACS did not send C000 but any other Cxxx code. There will be more information when the issue 616 is fixed.

**Comment by gofal** [comment]
Is fixed in pull request #677, will be included in next release
