### ISSUE TITLE
Prepare DicomServer class or factory for dependency injection

### ISSUE THREAD

**Issue by WernMich** [fo-dicom/fo-dicom#649]
### Expected behavior
When a DicomServer object is created it will be possible to inject dependencies during construction time (e.g. AE title, other references to be called within service instance).

### Actual behavior
It is not possible to inject any additional dependencies (created by DicomServer.Create<T>(int port)). Only with ugly workarounds like using statics (which makes it impossible to run more than one DicomServer instance.) or reflection. Using the "UserState" property @ DicomService base class is not possible (without using reflection).

### fo-dicom version and OS/platform
Win 10 Pro 64-bit, FO-DICOM 3.0.2.0

**Comment by FKupsch** [comment]
II think this issue is already solved. In version 3.1.0 you can insert dependecies with UserState at the DicomServer::Create call. If you do so, it will be available in every DicomService instance created by your Server.
