### ISSUE TITLE
Option in DicomClient so perform synchronized sending

### ISSUE THREAD

**Issue by gofal** [fo-dicom/fo-dicom#652]
### Expected behavior
There might be some Requests (like DicomCStoreRequest) where the user wants the sending of the messages and the receiving of the responses to happen in a synchronized order.

### Actual behavior
The sending of the requests added to a DicomClient and the reading of the incomming responses including the invoke of the OnResponseReceived event handlers happen in two separate threads. There is no synchronization mechanism. This means that there is no guarantee that you have the expected Order: send Request1 - invoke Request1.OnResponseReceived - send Request2 - invoke Request2.OnResponseReceived - ...
In applications like QR SCP with a c-move handler you cannot count reliably the number of successfully sent instances because when the OnResposeReceived is invoked you cannot know how many other Requests already have been sent.
Or when implementing a Store SCU and you want to cancel on the first error response there might already have been some other Requests sent causing an unnecessary amout of errors on the Store SCP side.

### Steps to reproduce the behavior
From fo-dicom/fo-dicom-samples start the Store SCP, the QR SCP and the QR SCU. You will see when the QR SCP sends the images to the Store SCP that there are many images already sent before the DicomClient invokes the OnResponseReceived for the first time.

### fo-dicom version and OS/platform
fo-dicom 3.0.2 on windows 10

**Comment by amoerie** [comment]
Actually you can call NegotiateAsyncOps on DicomClient and configure it to only have 1 pending request at a time. That should make it "synchronous", no? Although the .NET calls itself will still be asynchronous, your requests will be executed in order and only when the previous one completed.

**Comment by amoerie** [comment]
I'm closing this issue because I think the requested feature is already implemented. Please reopen if you disagree :-)
