### ISSUE TITLE
How to load Dicom image from server (path contains https://)

### ISSUE THREAD

**Issue by sreeharihp** [fo-dicom/fo-dicom#657]
How to load Dicom image from server (path contains https://) Am using fo-Diocm library.

var image = new DicomImage(filePath);
if filePath is from local directory its working fine. if filePath is from server (like https://example.com/filepath.dcm), its throwing 'Dicom.DicomFileException' saying that specified path value is not correct. What is the right way to load DicomImage from server ??

**Comment by IanYates** [comment]
You'll need to use something like HttpClient or WebRequest to download the file first.  `DicomImage`, which uses `DicomFile` internally, doesn't support fetching from a URL (as far as I can see anyway)

**Comment by sreeharihp** [comment]
Oh ok Thank you IanYates... 
Followed the same way as u suggested
