### ISSUE TITLE
Wrong encoding in DicomCFindResponse

### ISSUE THREAD

**Issue by azzurro1971** [fo-dicom/fo-dicom#659]
Hi,

I am doing a CFind request to a PACS.
In the CFindRequest i'm adding the encoding:

_request.Dataset.AddOrUpdate(new DicomTag(0x8, 0x5), "ISO_IR 100");_

But in the Response i get wrong encoded strings back. The Patient Names and Study Descriptions do not display the german special characters correctly.

_patientname = response.Dataset.Get<String>(DicomTag.PatientName);_

Am i doing something wrong? Or is that a problem on PACS side?
Can i do something to correct the encoding of the response results?

**Comment by gofal** [comment]
As far as I know you cannot influence the encoding of the response with your request. 
The DicomTag 0008,0005 tells, what the encoding of the current DicomDataset is. It is not a request what the encoding of the response shall be.
Take a look at the dicomtag 0008,0005 of the response to see which encoding the PACS uses.
Maybe you could send me some example? the binary data of the dicom tag?

**Comment by azzurro1971** [comment]
Thanks for your answer Reinhard!
The response does not contain the tag 0008,0005 at all, so that seems to be the problem.
I created a capture file with wireshark and the string "Hüfte" is "48-fc-66-74-65" so that seems to be ISO-8859-1 or ANSI...
Is there a chance to force that encoding with fo-dicom or do i have to take the byte array from the response and then convert that to a string with the correct encoding?

**Comment by gofal** [comment]
Then it is a bug in the server. Take a look at the DICOM definition: http://dicom.nema.org/dicom/2013/output/chtml/part03/sect_C.12.html#sect_C.12.1.1.2
The Dicom tag 0008,0005 is required if any special encoding is used within the dataset. If it is missing, then only ISO-646, meaning simple ASCII, shall be used.
I am not sure if fo-dicom has the possibility to enforce encoding. And I am not sure if it is the right way to include an workaround of an other servers problem into this library that is used from so many people.
I will take a closer look into code to see if there is a simple solution. But for now I recommend that you read the binary values and encode it yourself.

**Comment by gofal** [comment]
the issue is with the PACS server, that sends invalid characters without sending the 0008,0005 tag. So nothing to fix in fo-dicom
