### ISSUE TITLE
Try to add StructuredReport to Dicomclient and send it through but cannot find anyway for that. Any help?

### ISSUE THREAD

**Issue by BaharN** [fo-dicom/fo-dicom#660]
Need Help:

Try to add StructuredReport to Dicomclient and send it through but cannot find anyway for that. 
with C#

Any help?

**Comment by gofal** [comment]
So you have already tried the sample that is described on fo-dicom's project main page?

```
var client = new DicomClient();
client.AddRequest(new DicomCStoreRequest(@"test.dcm"));
client.Send("127.0.0.1", 12345, false, "SCU", "ANY-SCP");             // Alt 1
await client.SendAsync("127.0.0.1", 12345, false, "SCU", "ANY-SCP");  // Alt 2

```
The constructor of DicomCStoreRequest can accept either a filename of a DicomDataset that you maybe already have in memory.
Which errors do you get?

**Comment by BaharN** [comment]
I tried to create structuredreport by below line:

var strReport = new DicomStructuredReport(ds) : passing dataset which already includes data

But DicomClient.AddRequest doesn't accept StructuredReport type
Is "Test.dcm" sr name? 

I have all these lines which works perfect for images.

**Comment by gofal** [comment]
the "Test.dcm" is a filename of any dicom dataset stored on the file system.
DicomStructuredReport ist just a wrapper class around DicomDataset. It allows you a more conventient way to access and modify dicom tags that are specific for Structured Reports. The class DicomStructuredReport has a property Dataset that returns you the underlying DicomDataset. 
You have to pass this DicomDataset as parameter into the constructor of DicomCStoreRequest:

```
var strReport = new DicomStructuredReport(ds);
// do some modifications with strReport

var client = new DicomClient();
client.AddRequest(new DicomCStoreRequest(strReport.Dataset));
client.Send("127.0.0.1", 12345, false, "SCU", "ANY-SCP");             // Alt 1
await client.SendAsync("127.0.0.1", 12345, false, "SCU", "ANY-SCP");  // Alt 2
```
If you don't do any modifications with the structured report, then you cann pass the ds directly as parameter into the DicomCStoreRequest constructor.

Please give it a try. If it does not work, I would need a sample dataset of such a structured report to debug it on my machine.

**Comment by BaharN** [comment]
Find the issue with limited time,was my service limit. But current code just create another image, so
I changed my code with below line which gives me error:
dsReport.Add(DicomTag.AffectedSOPClassUID, DicomUID.BasicTextSRStorage);

"No accepted presentation context found for abstract syntax: Basic Text SR Storage"

Any idea?

Thanks

**Comment by gofal** [comment]
Well, the server simply does not accept Basic Text SR Storage. 
In Association Request the client sends the server a list of Abstract Syntaxes (Sop classes) and Transfer Syntaxes (encodings). The server then responses by accepting or rejecting every single Abstract-Transfersyntax-Combination. Then the client sends the data that was accepted.
You have to contact a technican of the server or to read the Dicom Conformance Statement of the server to figure out which abstract syntaxes the server accepts.

**Comment by BaharN** [comment]
Thanks gofal, I could fix it by some changes in my code and Dicom technician guy by setting the same study UID for image and structured report to appear in one level in the other hand.

Thanks again for your help.

**Comment by gofal** [comment]
You're welcome. 
So you have some code with Structured Reports. Is there something you could contribute? Our fo-dicom-samples are still missing a project for creating or reading Structured Reports.

**Comment by BaharN** [comment]
Sorry for delay to get back to you.
Here is a summary of what I 've done with my project:
1- Send image
- Ds is dataset which have image
   ds.Add(DicomTag.SOPClassUID, DicomUID.VLPhotographicImageStorage);
    DicomFile df = new DicomFile(ds);
    DicomFile outDF = df.Clone(DicomTransferSyntax.JPEG2000Lossless);
    DicomClient client = new DicomClient();
     await client.SendAsync(_sendToIp, _sendToPort, _sendSecure, _callingAE, _calledAE);

2- Send SR
- dsReport is for structured report                 
    DicomDataset dsReport = new DicomDataset();
    dsReport.Add(DicomTag.SOPClassUID, DicomUID.BasicTextSRStorage);
    dsReport.Add(DicomTag.StudyInstanceUID, studyId);   -- This Id should be the same as image if you want to display both of them together in other app

  dsReport.Add(DicomTag.Modality, "SR");
  DicomFile df2 = new DicomFile(dsReport);
  DicomFile outDF2 = df2.Clone(DicomTransferSyntax.DeflatedExplicitVRLittleEndian);
   DicomClient client2 = new DicomClient();
   client2.AddRequest(new DicomCStoreRequest(outDF2));
    await client2.SendAsync(_sendToIp, _sendToPort, _sendSecure, _callingAE, _calledAE);

**Comment by unosbaghaie** [comment]
Hello there 
I Have some questions about how to save Structure Reports  as DICOM files. 

There is a study which has some instances (dcm files) . 
Should I save the SR as a new dcm file in the instances of the study ? 
Then do I have to send it to a server or I can save it where all my dcm files are ?

and then when reading: 

How can I recognize a dcm file is SR? and when I read it which tag contains my reported text

**Comment by PalminX** [comment]
@unosbaghaie Your questions are not really related to fo-dicom. If you want to better understand DICOM SR, I would suggest to read David Clunie's excellent book on [DICOM Structured Reporting](http://www.dclunie.com/pixelmed/DICOMSR.book.pdf), as well as the [appropriate chapters of the DICOM standard](http://dicom.nema.org/medical/dicom/current/output/chtml/part21/sect_A.3.html).

> How can I recognize a dcm file is SR? 

You can check its SOP Class UID (0008,0016), to see if it is any of the SR SOP Classes, see http://dicom.nema.org/medical/dicom/current/output/chtml/part04/sect_B.5.html


SOP Class Name | SOP Class UID | IOD Specification (defined in PS3.3)
-- | -- | --
Basic Text SR Storage | 1.2.840.10008.5.1.4.1.1.88.11 | Basic Text SR IOD
Enhanced SR Storage | 1.2.840.10008.5.1.4.1.1.88.22 | Enhanced SR IOD
Comprehensive SR Storage | 1.2.840.10008.5.1.4.1.1.88.33 | Comprehensive SR IOD
Comprehensive 3D SR Storage | 1.2.840.10008.5.1.4.1.1.88.34 | Comprehensive 3D SR IOD
Extensible SR Storage | 1.2.840.10008.5.1.4.1.1.88.35 | Extensible SR IOD

**Comment by unosbaghaie** [comment]
found it. In .net core 2

```


[HttpPost, Route("SaveStructuredReport")]
        public async Task<ActionResult> SaveStructuredReport([FromBody]StructuredReportViewModel model)
        {
            
            var file = DicomFile.Open(inputfilePath, FileReadOption.ReadAll);

            //var modality = file.Dataset.GetValue<string>(DicomTag.Modality, 0);

            file.Dataset.Remove(DicomTag.PixelData);
            file.Dataset.AddOrUpdate(DicomTag.Modality, "SR");
            file.Dataset.AddOrUpdate(DicomTag.SOPInstanceUID, nextId);
            file.Dataset.AddOrUpdate(DicomTag.MediaStorageSOPInstanceUID, nextId);
            file.Dataset.AddOrUpdate(DicomTag.VerificationFlag, "UNVERIFIED");
            file.Dataset.AddOrUpdate(DicomTag.CompletionFlag, model.CompletionFlag);

            var strReport = new DicomStructuredReport(file.Dataset);

            var titleContentItem = new DicomContentItem(
               new DicomCodeItem(model.Title, "companyName", "Title"),
               DicomRelationship.Contains,
               new DicomCodeItem(model.Title, "companyName", "Title"));
            strReport.Add(titleContentItem);

            var requestContentItem = new DicomContentItem(
               new DicomCodeItem(model.Request, "companyName", "Request"),
               DicomRelationship.Contains,
               new DicomCodeItem(model.Request, "companyName", "Request"));
            strReport.Add(requestContentItem);

            if (!string.IsNullOrWhiteSpace(model.ObserverName))
            {
                var observerNameContentItem = new DicomContentItem(
                  new DicomCodeItem(model.ObserverName, "companyName", "Observer Name"),
                  DicomRelationship.Contains,
                  new DicomCodeItem(model.ObserverName, "companyName", "Person Name"));
                strReport.Add(observerNameContentItem);
            }

            var historyContentItem = new DicomContentItem(
               new DicomCodeItem(model.History, "companyName", "History"),
               DicomRelationship.Contains,
               new DicomCodeItem(model.History, "companyName", "History"));
            strReport.Add(historyContentItem);

            var procedureDescriptionContentItem = new DicomContentItem(
               new DicomCodeItem(model.ProcedureDescription, "companyName", "Procedure Description"),
               DicomRelationship.Contains,
               new DicomCodeItem(model.ProcedureDescription, "companyName", "Procedure Description"));
            strReport.Add(procedureDescriptionContentItem);

            var findingContentItem = new DicomContentItem(
             new DicomCodeItem(model.Finding, "companyName", "Finding"),
             DicomRelationship.Contains,
             new DicomCodeItem(model.Finding, "companyName", "Finding"));
            strReport.Add(findingContentItem);

            var recommendationContentItem = new DicomContentItem(
             new DicomCodeItem(model.Recommendation, "companyName", "Recommendation"),
             DicomRelationship.Contains,
             new DicomCodeItem(model.Recommendation, "companyName", "Recommendation"));
            strReport.Add(recommendationContentItem);


            file.Save(outputFilePath);


            var newSerie = new Series();
            newSerie.SeriesInstanceUid = GetNextId(lastSeriesToGenerateRId.SeriesInstanceUid);
            newSerie.FstudyInstanceUid = lastSeriesToGenerateRId.FstudyInstanceUid;
            newSerie.SeriesNumber = lastSeriesToGenerateRId.SeriesNumber;
            newSerie.Modality = "SR";
            newSerie.SeriesDescription = "Report";
            newSerie.NumberOfSeriesRelatedInstances = lastSeriesToGenerateRId.NumberOfSeriesRelatedInstances;

            var newInstance = new Instance();
            newInstance.SopinstanceUid = nextId;
            newInstance.FseriesInstanceUid = newSerie.SeriesInstanceUid;
            newInstance.InstanceNumber = lastNotSRinstance.InstanceNumber;
            newInstance.SopclassUid = lastNotSRinstance.SopclassUid;
            newInstance.InstanceAvailability = lastNotSRinstance.InstanceAvailability;
            newInstance.InstanceCreationDate = DateTime.Now.Date;
            newInstance.Path = $@"{lastSeriesToGenerateRId.FstudyInstanceUid}/{newFileName}";  // .dcm file

            await _seriesService.CreateSerie(newSerie);
            await _instanceService.CreateInstance(newInstance);
            return Ok();
        }




public class StructuredReportViewModel
    {
        public string Title { get; set; }
        public string Request { get; set; }
        public string ObserverName { get; set; }
        public string History { get; set; }
        public string ProcedureDescription { get; set; }
        public string Finding { get; set; }
        public string Recommendation { get; set; }
        public bool IsVerified { get; set; }
    }



```
