### ISSUE TITLE
SendAsync of the DicomClient class is not fully async

### ISSUE THREAD

**Issue by pelnar** [fo-dicom/fo-dicom#663]
### Expected behavior
Should not block the thread

### Actual behavior
Block the  thread while the network connection is being opened. Especially visible when the network connection cannot be established

### Steps to reproduce the behavior
I am calling method public Task SendAsync(string host, int port, bool useTls, string callingAe, string calledAe); of the DicomClient class to call C-ECHO or C-FIND from a WPF application and have called it from the UI thred, which should work with the async. The async behaviour seems to work well when the network connection is established (correctly and quickly). Then the thread is not blocked or probably it is not visible. However when there is a connection issue which eventually times out the async behaviour is not async. It blocks the thread, which is the UI thread in this case. 
I am running this agains my own fo-dicom based DICOM server, which is hosted in ASP.NET app. This means that when the app pool is recycled and before the app is strated (by accessing the web app host), the DICOM server is not running and the network connection will fail.
According to Reinhard Gruber this is probably caused by this code:
 _networkStream = NetworkManager.CreateNetworkStream(host, port, useTls, noDelay, ignoreSslPolicyErrors);

### fo-dicom version and OS/platform
WPF/Desktop 3.0.2

**Comment by gofal** [comment]
This is now implemented in version 4.0.3 with the new `Dicom.Network.Client.DicomClient` class
