### ISSUE TITLE
JsonDicomConverter can't parse null terminated strings

### ISSUE THREAD

**Issue by rkm** [fo-dicom/fo-dicom#665]
Hi all,

I brought this query up in the Gitter chat and was advised to open an issue, so here it is!

I have checked out the development branch and am attempting to test the Json serializer. The tests provided pass fine, but if I try and process a dataset (from a file) which has the tag`Tag: "Patient's Weight" ("10","1030"), VR: "DS", VM: 1, Value: "0\0"` for example, it throws an ArgumentException. I believe the "\0" is padding to give the value an even length.

I know the null terminator doesn't conform to the dicom standard (similar discussion in #359), since it should be padded with a space (32) character. This is something I'm just having to deal with in my data, so I can appreciate it if you don't want to implement a fix for this specific case!

### Expected behavior
The serializer should be able to handle null terminated strings.

### Actual behavior
The serializer tries to parse "0\0" to a decimal string and throws an ArgumentException.

### Steps to reproduce the behavior
```
        [Fact]
        public void TestDecimalStringConversion()
        {
            var ds = new DicomDataset
            {
                new DicomDecimalString(DicomTag.PatientWeight, "0\0")
            };

            VerifyJsonTripleTrip(ds);
        }
```
### fo-dicom version and OS/platform
Latest commit on development branch, VisualStudio 15.6.2 on Windows 10.

**Comment by rkm** [comment]
v4.0.7 fixes this I think

**Comment by gofal** [comment]
at least the unit test you provided runs green in current version.
