### ISSUE TITLE
PrintSCU Association

### ISSUE THREAD

**Issue by caktoy** [fo-dicom/fo-dicom#667]
### Expected behavior
Hi, I want to try PrintSCU project in example, I working with VS2017 Community Editition, and I use PrintSCP application (http://www.charruasoft.com/products/printscp/index.php), but when I run the project from VS, the console produce a message say 'Association Failed!'.
![image](https://user-images.githubusercontent.com/6917446/37759300-c585080a-2de5-11e8-9ccd-b65f19b208d9.png)

### Actual behavior
Association failed with SCP.

### Steps to reproduce the behavior
Just run the PrintSCU project

### fo-dicom version and OS/platform
3.0 Windows 10 64-bit

**Comment by gofal** [comment]
The association fails, because the SprintSCP seems to reject the abstract syntaxes. You send the tree Abstract Syntaxes Basic Film Session, Basic Fim Box and Basic Grayscale ImageBox. And the print SCP reacts on each of them by writing "Waring, not accepted Abstract Syntax: xx" with the UIDs of the tree abstract syntaxes.
So for some reason the print SCP does not accept this. On the homepage of CarruaSoft I could not find something like a Dicom Conformance Statement or similar and the screenshots provided on the homepage do not show some options about dicom communication.

Do you have any additional informations and requirements by CharruaSoft? If not, then you have to guess what this software expects. First of all I would offer more transfer syntaxes.

**Comment by FKupsch** [comment]
The CharruaSoft Print SCP behaves correctly, because the proposed abstract syntax by the SCU is not DICOM conformant. In Print the SCU has to propose the Print Management Meta SOP Classes.  See PS 3.4 H.3 Print Management Conformance.

**Comment by FKupsch** [comment]
A DICOM Conformant association negotiation between Print SCU and SCP would look like this:

A_ASSOCIATE_RQ Message 
Presentation Context Item(s): 
Presentation Context ID:    ID: 1
     > Abstract Syntax: 1.2.840.10008.5.1.1.9
     > Transfer Syntax: 1.2.840.10008.1.2.1
     > Transfer Syntax: 1.2.840.10008.1.2
     > Transfer Syntax: 1.2.840.10008.1.2.2
Presentation Context ID:    ID: 3
     > Abstract Syntax: 1.2.840.10008.5.1.1.18
     > Transfer Syntax: 1.2.840.10008.1.2.1
     > Transfer Syntax: 1.2.840.10008.1.2
     > Transfer Syntax: 1.2.840.10008.1.2.2

A_ASSOCIATE_AC Message 
Presentation Context Item(s): 
Presentation Context ID:    ID: 1
    > Result: 0
     > Abstract Syntax: 1.2.840.10008.5.1.1.9
     > Transfer Syntax: 1.2.840.10008.1.2.1
Presentation Context ID:    ID: 3
    > Result: 3
     > Abstract Syntax: 1.2.840.10008.5.1.1.18
     > Transfer Syntax:

**Comment by GeovaneW96** [comment]
I could successfuly negotiate the presentation context, but it seems like there's still something wrong.

![image](https://user-images.githubusercontent.com/19267390/44667628-aed1d600-a9f1-11e8-839c-c9f66a06ec21.png)

**Comment by FKupsch** [comment]
Did you add the Basic Grayscale Meta SOP class as an additional abstract syntax to the AdditionalPresentationContexts or how did you get the DicomClient to negotiate it? I had a look into the DicomClient of FO DICOM 4.0 and I actually think that print will currently not work with it. So as you see in your screen the SCP has rejected all Abstract Syntaxex except the Meta SOP class. But the DicomClient tries to send the Film Session N-CREATE Rq on the Film Session SOP class, which is not DICOM conformant and is not supported by the SCP. Instead it must send the request on the Meta SOP class, but this logic is not implemented. I wonder who has implemented the DICOM SCU in the samples. I doubt it was ever tested with some real Print SCP.

**Comment by PantelisGeorgiadis** [comment]
Hey @FKupsch, you caught me in the second...!!!
My message was:

Good afternoon!
This is kind of a “bug” in the way DicomClient class is designed. The client is designed to propose a context for each unique SOP class UID it finds within the request collection (plus the additional contexts). Although this might be the case for most of DICOM operations, it is not for printing. I managed to overcome this by disabling the above behavior and making all requests though the “Basic Grayscale Print Management Meta SOP Class” presentation context (if accepted!!!).
I verified that CharruaSoft's PrintSCP works well with the above!

**Comment by GeovaneW96** [comment]
Yes, I added it as an AdditionalPresentationContext.

Maybe it would be necessary to change the DicomClient code to use it as default and then rebuild it? 
I guess I've read all related posts already.

I've found more people having trouble:
https://groups.google.com/forum/#!topic/fo-dicom/L6W3qzDAnLY

But also, there's one saying he has used it with many real SCP printers wihout having any trouble:
https://groups.google.com/forum/#!topic/fo-dicom/DMW1AMgLxUw

**Comment by GeovaneW96** [comment]
@PantelisGeorgiadis How do I disable this behavior?

**Comment by GeovaneW96** [comment]
@PantelisGeorgiadis  I modified the DicomClient (removing the default presentation contexts) and re-tested, but I still couldn't make it work with CharruaSoft.

![image](https://user-images.githubusercontent.com/19267390/44677297-febd9680-aa0b-11e8-879f-c2f4cbf4a669.png)

**Comment by GeovaneW96** [comment]
Yes, I got it :) thanks

**Comment by GeovaneW96** [comment]
I still couldn't make it work with CharruaSoft but atleast I understood why. Maybe @PantelisGeorgiadis  can help with it.

**Comment by PantelisGeorgiadis** [comment]
@GeovaneW96, unfortunately, my solution is too "ad-hoc" to make a PR from it.

**Comment by GeovaneW96** [comment]
@PantelisGeorgiadis  Would you mind sharing your solution? 

I've been trying to print to CharruaSoft / KODAK DryView with no success.

It accepts BasicGrayscalePrintManagementMetaSOPClass and Verification. 

BasicGrayscalePrintManagementMetaSOPClass is defined by the following SOP Classes:

- Basic Film Session SOP Class
- Basic Film Box SOP Class
- Basic Grayscale Image Box
- Printer SOP Class

So, by using BasicGrayscalePrintManagementMetaSOPClass Presentation Context, no error about "No accepted presentation context found..." should show up.

I tried setting the PresentationContext of the N-CREATE requests to BasicGrayscalePrintManagementMetaSOPClass without success, because I get the following error:

![image](https://user-images.githubusercontent.com/19267390/44994303-662b9700-af74-11e8-9f0c-46f85c031db5.png)

**Comment by GeovaneW96** [comment]
@PantelisGeorgiadis Would you mind sharing your solution?

**Comment by PantelisGeorgiadis** [comment]
@GeovaneW96 the solution was already shared! It is a mix of my and @FKupsch's comments. More specifically:
1.	Comment out DicomClient’s behavior to propose a new context for each unique SOP class UID: https://github.com/fo-dicom/fo-dicom/blob/0c07cb0cb520a29004bfc77cbd9996f8e0b38e86/DICOM/Network/DicomClient.cs#L294
2.	After receiving an association accept, channel all requests through the first accepted presentation context. You can add the following: 
`foreach (var request in _client._requests)
                    request.PresentationContext = association.PresentationContexts.FirstOrDefault();`
after: https://github.com/fo-dicom/fo-dicom/blob/0c07cb0cb520a29004bfc77cbd9996f8e0b38e86/DICOM/Network/DicomClient.cs#L377
3.	Create an instance of your modified client and add BasicGrayscalePrintManagementMetaSOPClass as an additional presentation context:
`var pc = new DicomPresentationContext(0, DicomUID.BasicGrayscalePrintManagementMetaSOPClass);
            pc.AddTransferSyntax(DicomTransferSyntax.ExplicitVRLittleEndian);
            pc.AddTransferSyntax(DicomTransferSyntax.ImplicitVRLittleEndian);
printClient.AdditionalPresentationContexts.Add(pc);`
4.	Adapt the rest of the code from the sample Print SCU application to make your requests.

I used v2.0.2 to implement, so you have to port it to newer versions, if interested.
I guess now you understand what I meant with the “ad-hoc” term!

**Comment by ltxdyl** [comment]
@FKupsch I hava the same problem，that Link can't open？

**Comment by ltxdyl** [comment]
Good ! v4.0.0 can use!  @PantelisGeorgiadis

**Comment by Ashhhhhhhh** [comment]
> Good ! v4.0.0 can use! @PantelisGeorgiadis

can you give me solution of v4.0.0.0,this would be a great help to me and thank you very much

**Comment by Ashhhhhhhh** [comment]
> Good ! v4.0.0 can use! @PantelisGeorgiadis

can you give me solution of v4.0.0.0,this would be a great help to me.My email is ashhjay@foxmail.com
thank you very very much

**Comment by gofal** [comment]
Please give the code in this pull request a try. Now printing should work as proposed in fo-dicom-samples, without workarounds as described above.
