### ISSUE TITLE
When I use fo-dicom to update a DICOM tag the C# form changes size

### ISSUE THREAD

**Issue by policchio** [fo-dicom/fo-dicom#669]
When I use fo-dicom to update a DICOM tag, my form changes size and everything gets smaller, all the windows seem to be scaled.
The problem was presented when I use **dataset.Add**.
I explain my problem in detail, with an example, here:
https://stackoverflow.com/questions/49688458/when-i-use-fo-dicom-to-update-a-dicom-tag-the-c-sharp-form-changes-size
How can I avoid this behavior?

Thank you so much for your help and excellent work,
Davide

**Comment by malfonso0** [comment]
Hi i have the same problem.
its about DPI awareness of the form.. probably you are using 125/150 % on your screen to get "bigger" fonts.

Add a manifest to your proyect
rigth click in proyect, add, new item, search for manifest file.
it should already have commented  something about dpi.. just uncommet... if not.. add 
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">false</dpiAware>
    </windowsSettings>
  </application>


it should work.. try true for awarenes ( check your forms should have AutoScaleMode Font or DPI ) or false to do nothing about dpi awareness

hope it helps
MA

**Comment by atifc** [comment]
This does not seem to be directly related to fo-dicom, but rather a general windows desktop development question. 

Further:
Linked SO question has broken links to screenshots.
Linked SO question has broken link for sample code.

@amoerie given the age of the issue and the above, I'm thinking that the issue can be closed.

**Comment by amoerie** [comment]
^ What he said 😁
