### ISSUE TITLE
Json serialization of private tags missbehaves badly

### ISSUE THREAD

**Issue by JoakimRaySearch** [fo-dicom/fo-dicom#672]
### Expected behavior
I can serialize and deserialize private tags.

### Actual behavior
Private tags don't always get masked and the deserialization goes horribly wrong mixing values.

### Steps to reproduce the behavior
See the following LINQPad script, if you don't use LINQPad then simply view the script in your favorite text editor.
[fo-dicom - test.zip](https://github.com/fo-dicom/fo-dicom/files/1889138/fo-dicom.-.test.zip)

![image](https://user-images.githubusercontent.com/33281055/38489072-97961e3a-3be5-11e8-914f-6e49609b8cf1.png)

NB: See how both the tags "Test1" and "Test2" suddenly has "test2" as value.

### fo-dicom version and OS/platform
3.0.2, Windows 10

**Comment by anders9ustafsson** [comment]
The handling of private creator masks and tag ordering has been (hopefully sufficiently) corrected in a recent pull request (just can't remember the PR number right now). Please download and build *fo-dicom* from the latest source code to check if the problem described here is still present.

**Comment by buckstephenh** [comment]
The last build on Nuget was 5/2/2017.  Is this valid to use?

**Comment by anders9ustafsson** [comment]
I am fairly certain the PR I am referring to was not present in the 3.1.0-alpha release, so if you want to check whether serialization works correctly I recommend that you build a local *fo-dicom* binary from the latest source code.

**Comment by JoakimRaySearch** [comment]
Using the 48383f5fd77dab0b4043834ab0b2e828752f0e55 commit.
With the same code as above I now get the following when trying to create my dataset.

![image](https://user-images.githubusercontent.com/33281055/38935344-6bb8ce9e-431e-11e8-9c53-56b0f7ab56dd.png)

**Comment by gofal** [comment]
I converted your LINQPad-script into an unit test:
        [Fact]
        public static void TestPrivateTagsDeserialization()
        {
            var privateCreator = DicomDictionary.Default.GetPrivateCreator("Testing");
            var privTag1 = new DicomTag(4013, 0x008, privateCreator);
            var privTag2 = new DicomTag(4013, 0x009, privateCreator);

            var ds = new DicomDataset
            {
                { DicomTag.Modality, "CT" },
                new DicomCodeString(privTag1, "test1"),
                { privTag2, "test2" },
            };

            var json = JsonConvert.SerializeObject(ds, new JsonDicomConverter());
            var ds2 = JsonConvert.DeserializeObject<DicomDataset>(json, new JsonDicomConverter());

            Assert.Equal(ds.Get<string>(privTag1), ds2.Get<string>(privTag1));
            Assert.Equal(ds.Get<string>(privTag2), ds2.Get<string>(privTag2));
        }
This test works fine with the current development branch

**Comment by gofal** [comment]
@JoakimRaySearch To find the reason for your NullReferenceException: how did you build the solution and to which dll did you link? Does this LINQPad run as classical desktop application or as UWP? in 32 or 64bit?

**Comment by gofal** [comment]
One more thing that came into my mind today. I've seen this somewhere already: #551.
There is an issue if you target framework 4.5.1 or earlier. I assume you do not have any control of which framework LINQPad is based on?

**Comment by JoakimRaySearch** [comment]
It's run as a calssical desktop application, 32-bit.

I was when I linked it to the dll:s in the "fo-dicom\Serialization\Json\bin\Debug" folder that I got the null exception.

I just tried it with 4a415e4ee6ae9375d0fe5f8f9d7d8452b9808266 and the dll:s from "fo-dicom\Tests\Desktop\bin\Debug", then it worked perfectly.

So I guess it works on development, it's just not obvious which dll:s to use when building the project. Do you have any time frame for a new released version?

**Comment by gofal** [comment]
Yes. just wrote yesterday with anders gustavson. I'd like to include pull request #683 and then it is time to publish a 4.0 release candidate.

So this issue is not a bug any more?
