### ISSUE TITLE
Performance expectations of dicomClient

### ISSUE THREAD

**Issue by buckstephenh** [fo-dicom/fo-dicom#686]
### Expected behavior

dicomClient would send cStore requests immediately.

### Actual behavior

A dicomClient with 3000 requests takes anywhere from 2m 15s to 3m to begin sending it's payload, regardless whether using sync or async call.  There is no apparent CPU or I/O associated with this time period. 

### Steps to reproduce the behavior

Add 3000 DicomCStoreRequest to dicomclient and send or sendasync. 

### fo-dicom version and OS/platform

3.1.0-alpha MacOS High Sierra 10.13.5 Beta (17F59b)

**Comment by mia-san** [comment]
sorry for digging into rather old issue.
is this still reproducible with 4.0.0?

sending multiple files is very common task, so I decided to see if I can find anything.
I've been trying to reproduce the symptom by following simple program, but no luck so far.

I observed so far that
- adding 3,000 requests for same DICOM file takes about 10 seconds.
- Send() almost immediately open connection and start association after AddRequest loop.
- DICOM file size does not matter, it seems.
- cannot reproduce with both 3.1.0-alpha and 4.0.0.

I use fo-dicom desktop(3.1.0-alpha, 4.0.0), Windows 10, .NET Framework 4.5.2, Console application.
DICOM file is placed on HDD.

do you have any idea ?
perhaps platform matters?

```
var c = new DicomClient();

for (int i = 0; i < 3000; ++i)
{
    c.AddRequest(
        new DicomCStoreRequest(
            "dicom.dcm"
        )
    );
}

c.Send("10.0.0.130", 10400, false, "ANY-SCU", "ANY-SCP");
```

I know this is assigned to @gofal , but if I could be of any help...

**Comment by gofal** [comment]
great, removed myself as assignee.
I planned to fix this because it was a area close to an other issue I was working on, but then after releasing version 4 the number of issues raised very fast, so I worked on the bugs prior to enhancements.

I too assue a platform issue. I not not own a mac so I cannot reproduce on iOS.  Maye it is more reproducible if there are requests of 3000 different files. this causes fo-dicom to read the header of all these 3000 files and avoids file io caching when accessing the same file 3000 times.

**Comment by buckstephenh** [comment]
I was using sendasync, and I think the shared thread pool was full.  I’ve re-written the solution and no longer have the problem.   Any idea how many threads are used to evaluate the requests during sendasync to determine the association requirements or is that done at the addrequest stage?

**Comment by mia-san** [comment]
@buckstephenh thanks, so this is not the case anymore now with 4.0 ?

I've just changed my test program to use SendAsync, exhibits same as Send.

> Any idea how many threads are used to evaluate the requests during sendasync to determine the association requirements or is that done at the addrequest stage?

perhaps you mean preparing presentation context?

it seems to me as following:
Send -> SendAsync -> DoSendAsync -> DicomServiceUser.ctor.
now DicomPresentationContextCollection.AddFromRequest is invoked on each request one by one in foreach loop.

so it takes only 1 thread if i'm not mistaken, which unlikely to stress the thread pool that much.

**Comment by buckstephenh** [comment]
I am not having any issues at present related to delays in sending 3000 files, though we severely restrict the number of requests per association for other reasons now, since it’s not easy to discover what failed in the batch and just send the rest. 

Sent from my iPhone

On Dec 5, 2018, at 4:14 PM, mia-san <notifications@github.com> wrote:

@buckstephenh thanks, so this is not the case anymore now with 4.0 ?

I've just changed my test program to use SendAsync, exhibits same as Send.

Any idea how many threads are used to evaluate the requests during sendasync to determine the association requirements or is that done at the addrequest stage?

perhaps you mean preparing presentation context?

it seems to me as following:
Send -> SendAsync -> DoSendAsync -> DicomServiceUser.ctor.
now DicomPresentationContextCollection.AddFromRequest is invoked on each request one by one in foreach loop.

so it takes only 1 thread if i'm not mistaken, which unlikely to stress the thread pool that much.
