### ISSUE TITLE
Example request - Extracting video from a dicom file

### ISSUE THREAD

**Issue by roitenen1981** [fo-dicom/fo-dicom#689]
Hi, 
could you give a small example code showing how to extract a video file out of a Dicom file and save it to the local drive using fo-dicom?
Thanks

**Comment by aerik** [comment]
var df = DicomFile.Open("myfile.dcm");
            DicomItem item = df.Dataset.Get<DicomItem>(DicomTag.PixelData);
            if (item == null) return;
            if (item is DicomOtherByteFragment)
            {
                _Buffer = ((DicomOtherByteFragment)item).Fragments[0];
                if (((DicomOtherByteFragment)item).Fragments.Count == 1)
                {
                    _Buffer = ((DicomOtherByteFragment)item).Fragments[0];
                }
                else
                {
                    _Buffer = new CompositeByteBuffer(((DicomOtherByteFragment)item).Fragments.ToArray());
                }
            }
            else if (item is DicomElement)
            {
                _Buffer = ((DicomElement)item).Buffer;
            }
            File.WriteAllBytes('myfile.ext', _Buffer.Data);

**Comment by gofal** [comment]
for completeness: this is how a dicom video file can be created:

        dataset.Add(DicomTag.PhotometricInterpretation, PhotometricInterpretation.Rgb.Value);
        dataset.Add(DicomTag.Rows, (ushort)rows);
        dataset.Add(DicomTag.Columns, (ushort)columns);
        dataset.AddOrUpdate(DicomTag.TransferSyntaxUID, DicomTransferSyntax.MP4HighProfileLevel41.UID.UID);
        DicomPixelData pixelData = DicomPixelData.Create(dataset, true);
        var finfo = new FileInfo(mp4);
        var buffer = new FileByteBuffer(new Dicom.IO.DesktopFileReference(mp4), 0, (uint)finfo.Length);
        pixelData.AddFrame(buffer);
        pixelData.NumberOfFrames = numFrames;
        DicomFile dicomfile = new DicomFile(dataset);

**Comment by yvdh** [comment]
I confirm it does not work.
There are missing tags the MP4HighProfile does not exists, and a dicom checker says the file contains 'trailing garbage'. 
I checked my file for codec info:
![image](https://user-images.githubusercontent.com/16563417/73376762-41993300-42be-11ea-8ccd-90e278648475.png)

**Comment by alanhmartins** [comment]
> DicomPixelData pixelData = DicomPixelData.Create(dataset, true);
>     var finfo = new FileInfo(mp4);
>     var buffer = new FileByteBuffer(new Dicom.IO.DesktopFileReference(mp4), 0, (uint)finfo.Length);



using this code, the video is blank in the viewer, what’s missing?

**Comment by gofal** [comment]
Which viewer are you using? Just to ensure the viewer supports displaying DICOM video.

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.

**Comment by remyGrandry** [comment]
I can confirm that this in not working with Radiant Viewer and VLC. 
The dicom can be opened in radiant, but when opening with VLC by double clicking, VLC closes immediately.

Any clues about what could have gone wrong ?

**Comment by Sindhumol-S** [comment]
Solved!!!

Please try this overloaded constructor
DicomDataset dataset = new DicomDataset(DicomTransferSyntax.MPEG4AVCH264HighProfileLevel41);

and set

dataset.AddOrUpdate(DicomTag.TransferSyntaxUID, DicomTransferSyntax.MPEG4AVCH264HighProfileLevel41.UID);
.
.
.
dicomfile.FileMetaInfo.TransferSyntax = DicomTransferSyntax.Lookup(DicomUID.MPEG4AVCH264HighProfileLevel41);
