### ISSUE TITLE
Question - should I use the fo-dicom for .Net Core or Mono for running under Linux 

### ISSUE THREAD

**Issue by roitenen1981** [fo-dicom/fo-dicom#692]
Hi, 
from fo-dicom perspective, what is recommended for running under Linux?
the fo-dicom.NetCore or the Dicom.Core assembly for Mono? 
Thanks, 
Roi

**Comment by gofal** [comment]
Take a look at the wiki: https://github.com/fo-dicom/fo-dicom/wiki/Image-rendering
there is currently no imaging in .net core but the ImageManager returns an implementation depending on which actual platform the software is running.

**Comment by gofal** [comment]
I've created an issue: https://github.com/fo-dicom/fo-dicom/issues/693
