### ISSUE TITLE
'Dicom.DicomEncoding' threw an exception.'

### ISSUE THREAD

**Issue by buckstephenh** [fo-dicom/fo-dicom#694]
### Expected behavior

File Opens

### Actual behavior

Exception has occurred: CLR/System.TypeInitializationException
Exception thrown: 'System.TypeInitializationException' in Dicom.Core.dll: 'The type initializer for 'Dicom.DicomEncoding' threw an exception.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.NullReferenceException : Object reference not set to an instance of an object.
   at Dicom.IO.IOManager.get_BaseEncoding()
   at Dicom.DicomEncoding..cctor()

### Steps to reproduce the behavior

DicomFile.Open(filename);
 
### fo-dicom version and OS/platform

4.0.0-rc1 Mac 10.13.5

**Comment by buckstephenh** [comment]
This seems to be related to fo-dicom.log4net 3.1.0-alpha and 4.0.0-rc1.  Reverting to 

<PackageReference Include="fo-dicom.log4net" Version="3.0.2" /> seems to solve my problem when using fo-dicom 3.1.0-alpha. 

Not sure what we're doing wrong with logging that works in 3.0.2 but not above.

**Comment by anders9ustafsson** [comment]
@buckstephenh Do I understand correctly, that you are using the *fo-dicom* package on a Mac?

**Comment by tiloc** [comment]
I had the exact same exception today with the same stacktracke, during the same action (DICOMFile.Open), but on a different platform. I was forcefully using fo-dicom.**Desktop** 3.0.2 on a .Net Standard 2.0 project. The exception occurred where the IOManager tried to determine the default encoding for the platform by introspecting the Assemblies (actually in Setup.cs):
https://github.com/fo-dicom/fo-dicom/blob/17331dcb0c3aa3bbaf82236b26b735a0861a7cd0/DICOM/Setup.cs#L23

**Comment by gofal** [comment]
DICOM.Log4Net nuget-package contains the dll from project DICOM.Log4Net.Desktop and references DICOM.Desktop. So there is a platform issue.
the same when using fo-dicom.Desktop in a netStandard project. In NetStandard a reference to fo-dicom.NetCore would be the right choice.

So I am affraid, this is nothing to fix.

As log4net is concerned. There is a issue #772 to update the logging projects to NetStandard versions, to make it savely available in all platforms.

**Comment by shelbypereira** [comment]
I have the same error using NLog.
