### ISSUE TITLE
JPEG2000Lossless compression using fo-dicom 4.0.0-rc1 on .Net Core x86 appears to be not working

### ISSUE THREAD

**Issue by davekiwi** [fo-dicom/fo-dicom#695]
### Expected behavior
I was expecting JPEG 2000 Lossless compression to work correctly in a .Net Core windows application using fo-dicom 4.0.0-rc1.

### Actual behaviour
On the surface it appears to work correctly - it creates a smaller file, and decompressing that file results in a pixel data size the same as the original uncompressed file. However, the pixel values, although they are different from each other, seem to bear no relationship to the original pixels.

I have just built a .Net Core 2.0 library using fo-dicom 3.1.0-alpha, and this compression works fine on a bunch of different 16-bit mammo images. So it looks like 4.0.0-rc1 has regressed.

### Steps to reproduce the behavior
I called DicomFile.Clone(TransferSyntax.JPEG2000Lossless) on an uncompressed 16-bit mammo image, inside a .Net Core 2.0 application on x86, referencing fo-dicom 4.0.0-rc1

### fo-dicom version and OS/platform
.Net Core 2.0 application, referencing fo-dicom 4.0.0-rc1, on x86/x64

**Comment by gofal** [comment]
So it did work with version 3.1.0-alpha? Because as you can see on the wiki (https://github.com/fo-dicom/fo-dicom/wiki/Supported-Transfer-Syntaxes) there is only 8-bit-support for Jpeg2000Lossless on .net core. This has not changed as far as i know.

**Comment by davekiwi** [comment]
Hi Gofal, I stand corrected: the round-trip compression/decompression yields the original result, but I checked with the .Net 4.6.1 decompressor and it is having trouble decoding the Jpeg 2000 stream, so I imagine it is indeed not working.

Thanks for the link to the wiki page: that is very helpful and RLE or plain old JPEG should serve our needs quite well.

So if 16-bit JPEG2000 is not supported in 16 bits on 'Net Core, please go ahead and close this report with no action.

Thanks again,
Dave.
