### ISSUE TITLE
adding SendingApplicationEntityTitle and ReceivingApplicationEntityTitle tags making dicom file invalid

### ISSUE THREAD

**Issue by erlaxmikantha** [fo-dicom/fo-dicom#696]
### Expected behavior
After adding tags DicomTag.SendingApplicationEntityTitle and DicomTag.ReceivingApplicationEntityTitle to any dicom file should be able to open in any dicom editor application

### Actual behavior
After adding tags DicomTag.SendingApplicationEntityTitle and DicomTag.ReceivingApplicationEntityTitle
to some dicom file not able to open in dicom editors.
[problematic.zip](https://github.com/fo-dicom/fo-dicom/files/2117931/problematic.zip)

### Steps to reproduce the behavior
1. Extract the file.
2. 
            DicomFile file = DicomFile.Open(@"D:\DataSet\temp\problematic.dcm");
            file.Dataset.AddOrUpdate(DicomVR.AE, DicomTag.SendingApplicationEntityTitle, "AETSOURCE");
            file.Dataset.AddOrUpdate(DicomVR.AE, DicomTag.ReceivingApplicationEntityTitle, "AETRECEIVE");
            file.Save(@"D:\DataSet\temp\non-problematic.dcm");
Now file non-problematic.dcm is not able open standard dicom editors like DicomEdit 7.0
However if line 2 and 3 (adding new tags) are commented, then non-problematic.dcm is able to open it.

### fo-dicom version and OS/platform
version 3.0.2

**Comment by anders9ustafsson** [comment]
*Sending/ReceivingApplicationEntityTitle* tags are part of the File Meta Information. Add the tags to `file.FileMetaInfo` instead of `file.Dataset`. 

In recent *fo-dicom*  versions (not 3.0.x) there are also dedicated properties for setting and getting `SendingApplicationEntityTitle` and `ReceivingApplicationEntityTitle` in the `DicomFileMetaInformation` class.

**Comment by anders9ustafsson** [comment]
Closing issue now. Feel free to re-open if my answer above did not solve your problem, @erlaxmikantha .
