### ISSUE TITLE
Dicom Server unable to Listen on ipv4 and ipv6 using the same port

### ISSUE THREAD

**Issue by BobSter3000** [fo-dicom/fo-dicom#699]
### Expected behavior
Two listeners established on the same port using ipv4 and ipv6

### Actual behavior
Exception thrown upon creation of the second Dicom Server

### Steps to reproduce the behavior
            DicomServer.Create<DicomCEchoProvider>(NetworkManager.IPv6Any, 5000);
            DicomServer.Create<DicomCEchoProvider>(NetworkManager.IPv4Any, 5000);

### fo-dicom version and OS/platform
Development branch, fo-dicom Desktop.  Windows 10

**Comment by gofal** [comment]
See pull request #700
