### ISSUE TITLE
Hi any one can help me. i want send more than one .dcm file how to send using cstore.

### ISSUE THREAD

**Issue by Deepak01991** [fo-dicom/fo-dicom#702]
//Transfer to PACS with FO-DICOM Library
        bool transferStatusError;
        public bool CStore(string _DicomFilePath,bool isvedio)
        {
            try
            {
                transferStatusError = true;
                DicomCStoreRequest request = new DicomCStoreRequest(_DicomFilePath);

                request.OnResponseReceived += CStoreResponse;
                var client = new DicomClient();
                client.AddRequest(request);
                
                client.ReleaseAsync(32000);
                 //client.SendAsync(ClsCommonModules.PacsHostName, ClsCommonModules.PacsPortNumber, false, ClsCommonModules.PacsClientAeTitle, ClsCommonModules.PacsAeTitle);
                if (isvedio == false)
                {
                    client.Send(ClsCommonModules.PacsHostName, ClsCommonModules.PacsPortNumber, false, ClsCommonModules.PacsClientAeTitle, ClsCommonModules.PacsAeTitle);             // Alt 1
                    
                }
                return transferStatusError;
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
                transferStatusError = true;
                return transferStatusError;
            }
        }

**Comment by Deepak01991** [comment]
I am Using the code given billow for transfer dcm file

//Transfer to PACS with FO-DICOM Library
        bool transferStatusError;
        public bool CStore(string _DicomFilePath,bool isvedio)
        {
            try
            {
                transferStatusError = true;
                DicomCStoreRequest request = new DicomCStoreRequest(_DicomFilePath);

                request.OnResponseReceived += CStoreResponse;
                var client = new DicomClient();
                client.AddRequest(request);
                
                client.ReleaseAsync(32000);
                 //client.SendAsync(ClsCommonModules.PacsHostName, ClsCommonModules.PacsPortNumber, false, ClsCommonModules.PacsClientAeTitle, ClsCommonModules.PacsAeTitle);
                if (isvedio == false)
                {
                    client.Send(ClsCommonModules.PacsHostName, ClsCommonModules.PacsPortNumber, false, ClsCommonModules.PacsClientAeTitle, ClsCommonModules.PacsAeTitle);             // Alt 1
                    
                }
                return transferStatusError;
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
                transferStatusError = true;
                return transferStatusError;
            }
        }

**Comment by Deepak01991** [comment]
//Transfer to PACS with FO-DICOM Library
        bool transferStatusError;
        public bool CStore(string _DicomFilePath,bool isvedio)
        {
            try
            {
                transferStatusError = true;
                DicomCStoreRequest request = new DicomCStoreRequest(_DicomFilePath);

                request.OnResponseReceived += CStoreResponse;
                var client = new DicomClient();
                client.AddRequest(request);
                
                client.ReleaseAsync(32000);
                 //client.SendAsync(ClsCommonModules.PacsHostName, ClsCommonModules.PacsPortNumber, false, ClsCommonModules.PacsClientAeTitle, ClsCommonModules.PacsAeTitle);
                if (isvedio == false)
                {
                    client.Send(ClsCommonModules.PacsHostName, ClsCommonModules.PacsPortNumber, false, ClsCommonModules.PacsClientAeTitle, ClsCommonModules.PacsAeTitle);             // Alt 1
                    
                }
                return transferStatusError;
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
                transferStatusError = true;
                return transferStatusError;
            }
        }

**Comment by Deepak01991** [comment]
Using this code for transfer
        bool transferStatusError;
        public bool CStore(string _DicomFilePath,bool isvedio)
        {
            try
            {
               transferStatusError = true;
                DicomCStoreRequest request = new DicomCStoreRequest(_DicomFilePath);
                request.OnResponseReceived += CStoreResponse;
                var client = new DicomClient();
                client.AddRequest(request);
                
                client.ReleaseAsync(32000);
                 //client.SendAsync(ClsCommonModules.PacsHostName, ClsCommonModules.PacsPortNumber, false, ClsCommonModules.PacsClientAeTitle, ClsCommonModules.PacsAeTitle);
                if (isvedio == false)
                {
                    client.Send(ClsCommonModules.PacsHostName, ClsCommonModules.PacsPortNumber, false, ClsCommonModules.PacsClientAeTitle, ClsCommonModules.PacsAeTitle);             // Alt 1
                    
                }
                return transferStatusError;
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
                transferStatusError = true;
                return transferStatusError;
            }
        }

**Comment by gofal** [comment]
I will close this issue, since there is an answer. If it didn't solve your problem, feel free to re-open the issue.
