### ISSUE TITLE
MPEG & PDF(report) format 

### ISSUE THREAD

**Issue by ppiyushjv** [fo-dicom/fo-dicom#704]
### Expected behavior
Is it possible to get MPEG & PDF(report) format on C-Store SCP server

### fo-dicom version and OS/platform

OS: win 
Dicom.Core : v4.0.30319

**Comment by FKupsch** [comment]
PDFs can be represented by the Encapsulated PDF Image Storage SOP class. MPEG 2 or H264 video compression is represented by different Transfer Syntaxes in DICOM, but there is not a general video SOP class. A typicial SOP class used to cover video streams is Video Photographic/ Endoscopic Image Storage. If you only want to receive corresponding SOP classes with the FO-DICOM Storage SCP, you must extend the list of Accepted Transfer Syntaxes.

**Comment by deepakaneja** [comment]
Can you Provide the code for transfer MPEG to orthnac server

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.
