### ISSUE TITLE
onResponse(DicomCFindRequest req, DicomCFindResponse res) object reference not set to an instance

### ISSUE THREAD

**Issue by mohammaddaher** [fo-dicom/fo-dicom#710]
Dear Team
i'm new to fo-dicom, every time i get null exception, i created the following code:

private void button1_Click(object sender, EventArgs e)
        {
            try
            {
                string searchName = null;
                string searchID = null;

                if (!string.IsNullOrEmpty(txtName.Text))
                {
                    searchName = "*" + txtName.Text + "*";
                }

                if (!string.IsNullOrEmpty(txtID.Text))
                {
                    searchID = txtID.Text;
                }

                var cfind = DicomCFindRequest.CreatePatientQuery(searchID, searchName);
                cfind.OnResponseReceived = onResponse;

                var client = new DicomClient();

                string DicomIpAddress = ConfigurationManager.AppSettings["DicomIpAddress"];
                int DicomPort = int.Parse(ConfigurationManager.AppSettings["DicomPort"]);
                bool UseTls = bool.Parse(ConfigurationManager.AppSettings["UseTls"]);
                string DicomCallingAE = ConfigurationManager.AppSettings["DicomCallingAE"];
                string DicomCalledAE = ConfigurationManager.AppSettings["DicomCalledAE"];

                client.AddRequest(cfind);
                client.Send(DicomIpAddress, DicomPort, UseTls, DicomCallingAE, DicomCalledAE);
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }

 public void onResponse(DicomCFindRequest req, DicomCFindResponse res)
        {
            try
            {
                DicomDataset dataset = res.Dataset;
                //dataset.Add(DicomTag.SOPClassUID, "1.2.250.1.31.4.723.19980722.113224.11597");
                //dataset.Add(DicomTag.SOPClassUID, "1.2.250.1.31.4.723.19980722.113224.11597");
                //dataset.Add(DicomTag.StudyInstanceUID, GenerateUid());
                //dataset.Add(DicomTag.SeriesInstanceUID, GenerateUid());
                //dataset.Add(DicomTag.SOPInstanceUID, GenerateUid());

                dataset.Add(DicomTag.SOPClassUID, DicomUID.SecondaryCaptureImageStorage);
                dataset.Add(DicomTag.StudyInstanceUID, GenerateUid());
                dataset.Add(DicomTag.SeriesInstanceUID, GenerateUid());
                dataset.Add(DicomTag.SOPInstanceUID, GenerateUid());

                DicomFile dicomFile = new DicomFile(dataset);
                string FolderPath = ConfigurationManager.AppSettings["DicomPhotoPath"];
                if (!System.IO.Directory.Exists(FolderPath))
                {
                    System.IO.Directory.CreateDirectory(FolderPath);
                }

                dicomFile.Save(FolderPath + res.Dataset.Get<string[]>(DicomTag.PatientID) + ".dcm");
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.ToString());
            }
        }
        private static DicomUID GenerateUid()
        {
            StringBuilder uid = new StringBuilder();
            uid.Append("1.08.1982.10121984.2.0.07").Append('.').Append(DateTime.UtcNow.Ticks);
            return new DicomUID(uid.ToString(), "SOP Instance UID", DicomUidType.SOPInstance);
        }

what i'm missing, could any one help me
thanks

**Comment by gofal** [comment]
Yes. You do a CFind - that is just a query which images are available. So the responses contain only some infos about the images, but not the images themself. So you can do a quick query about all the images of a patient and get very quickly just some kilobytes of data with the info, which study with how many images on what date have been performed. And you get all the UIDs (studyuid, seriesuid, instanceuid)
Then in a second step you can retrieve the images via CGet (the images are returned in the same tcp-connection) or via CMove (tell the server to send the images to a predefined storescp).

Just take a look at the samples: https://github.com/fo-dicom/fo-dicom-samples/tree/master/Desktop/QueryRetrieve%20SCU

**Comment by mohammaddaher** [comment]
Dear Reinhard
thanks for your reply
i have some questions:
1- what is QRServerAET, AET and what is the difference and values should be?
2- PatientName ("Tester^P*"), has special characters, is it mandatory?
3- How to search by PatientID? if you have example.
4- in CreateCMoveByStudyUID("STORESCP", studyUID), what is "STORESCP"??

I appreciate your help

**Comment by gofal** [comment]
Your questions show me, that you are very new to DICOM, because that are very basic questions.

Here on github this is a bug- and issue-tracking system for fo-dicom library and not a general DICOM learning forum.
I recommend to read the DICOM standards or search in bing/google for some dicom tutorials - there are plenty of them. One I like very much is http://dicomiseasy.blogspot.com/2011/10/introduction-to-dicom-chapter-1.html.
If you then find issues with fo-dicom, you are welcome to open issues here.

**Comment by gofal** [comment]
Please read your Stacktrace:

System.InvalidOperationException: Sequence contains no elements
at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
at QueryRetrieve_SCU.Form1.button1_Click(Object sender, EventArgs e) in C:\inetpub\wwwroot\QueryRetrieve SCU\QueryRetrieve SCU\Form1.cs:line 67

The sample code is just a sample, that shows how to use the library. So the code in the sample concentrates on the fo-dicom API. It is not a fully-working, ready-to-use application. The code tries to access a collection that is empty. So the code needs error-checking, validation, etc.

**Comment by mohammaddaher** [comment]
Dear Reinhard
I'm struggling here, if you have a full sample, how to search patient by name or id and get to the dicom file and save it to my hard drive. i will be grateful.

i have pacs server details, i tried so many times but still not working.
any help

**Comment by mohammaddaher** [comment]
Dear group
any help

**Comment by gofal** [comment]
There is a full sample here: https://github.com/fo-dicom/fo-dicom-samples/tree/master/Desktop/QueryRetrieve%20SCU. You already know this repository. 
You can add this line of code in the main() method to get full DICOM communication log into your console:

            // Initialize log manager.
            LogManager.SetImplementation(ConsoleLogManager.Instance);

Or take a look at the Wiki how to configure other logging options: https://github.com/fo-dicom/fo-dicom/wiki/Logging-configuration.

As already mentioned: this here is a bug- and issue tracking system for fo-dicom, and not a DICOM learning forum! You will get answers here if you post specific error messages or describe some reproducable malfunctions of fo-dicom.

Try our gitter-chat, that is linked on the very first line of the github-startpage. There is a more loose taking and information exchange.

**Comment by mohammaddaher** [comment]
Dear Mr. Reinhard
now the sample is working fine with no errors.
but i'm facing new issue.

the application is running fine and reading studyUID, serieUids but the  client.OnCStoreRequest its not executing and saveImage function is not called, any reason for that. 

it goes direct to cMoveRequest.OnResponseReceived and give response.Status.State=success
any advise.

**Comment by mohammaddaher** [comment]
Dear 
as i mention before its cstore is sending a request but i'm not getting any response then it goes to cmove, on cmove i got this error.
**unable to process - all CSTOREs failed**
what is that mean?

i took a photo from the server log.
![log](https://user-images.githubusercontent.com/11276670/45626205-f0f5b100-ba9f-11e8-9cb4-179e8e0f46a8.jpeg)

**Comment by gofal** [comment]
Is your system configured well on the server? The thing with c-move is, that a client can do c-move requests that are working fine, but then the server has to create a new c-store association. One DICOM Tag in the c-move request is DestinationAETitle. So the c-move request tells the AETitle where the images have to be stored. then the server accepts the move-request and tries to create a complete new connection to the node with the AETitle provided in DestinationAETitle. Often a reason why this is not working is that the destination node is not configured well on the server. 
Did you start a StoreSCP-Service beside your C-Move-Client to receive the images?

**Comment by mohammaddaher** [comment]
Dear Reinhard
in fact I'm using QueryRetrieve SCU sample and there is no storeSCP, but i have c-Store SCP as separated application, i tried to run both application on the same time but nothing happens, i checked the log file with network engineer, he saying that dicom file is trying to streaming but there is no listener on port 4444 to accept it.

if   you can tell me how to merge both application or how to call  **var server = DicomServer.Create<CStoreSCP>(port);**. inside QueryRetrieve SCU.
regards

**Comment by mohammaddaher** [comment]
Dear Reinhard
I'm getting now the dicom file, but its taking long time.

any advice
