### ISSUE TITLE
RLELossless really Supported (.NET Core)

### ISSUE THREAD

**Issue by VitoHanoi** [fo-dicom/fo-dicom#714]
Hello there,
I am Cloning a DicomFile (DicomTransferSyntax.ExplicitVRLittleEndian, which is a 16bits encoded Image) to DicomTransferSyntax.RLELossless syntax.
I am cloning this new dicomFile to the original Syntax (round trip compression/decompression). 

### Expected behavior
I expect to have the Same Pixel Data...

### Actual behavior
I have 116 different bytes for every image that I am testing. Do you have any idea why?

Always
Diff:255 Original Value: 16383 (255, 63) Res Value: 16128 (0, 63)
### Steps to reproduce the behavior

```
DicomFile myOriginalDicomFile = DicomFile.Open(myOriginalDicomFilePath);
DicomFile myNewFile = myOriginalDicomFile.Clone(DicomTransferSyntax.RLELossless);
DicomFile myResFile = myNewFile.Clone(myOriginalDicomFile.Dataset.InternalTransferSyntax);

            // Supporting 16bit encoded images
            var myBitsAllocated = myResFile.Dataset.GetSingleValue<ushort>(DicomTag.BitsAllocated);
            if (myBitsAllocated == 16)
            {
                byte[] myOriginalBytes = DicomPixelData.Create(myOriginalDicomFile.Dataset).GetFrame(0).Data;
                byte[] myResBytes = DicomPixelData.Create(myResFile.Dataset).GetFrame(0).Data;

                if (!myOriginalBytes.SequenceEqual(myResBytes))
                {
                    // Number of different bytes
                    int myDiffCount = myResBytes.Where((inT, inI) => inT != myOriginalBytes[inI]).Count();
                    Trace.WriteLine("Diff count " + myDiffCount);

                    // Run through all image
                    for (var myIndex = 0; myIndex < myOriginalBytes.Length; myIndex += 2)
                    {
                        // Get Pixel value from Original image
                        byte myOriginalByte1 = myOriginalBytes[myIndex];
                        byte myOrginalByte2 = myOriginalBytes[myIndex + 1];
                        ushort myOriginalPixelValue =
                            BitConverter.ToUInt16(new byte[] {myOriginalByte1, myOrginalByte2}, 0);

                        // Get Pixel value from RoundTrip image
                        byte myResByte1 = myResBytes[myIndex];
                        byte myResByte2 = myResBytes[myIndex + 1];
                        ushort myResPixelValue = BitConverter.ToUInt16(new byte[] {myResByte1, myResByte2}, 0);

                        // If Value are different
                        if (myOriginalPixelValue != myResPixelValue)
                        {
                            Trace.Write("Diff:" + Math.Abs(myOriginalPixelValue - myResPixelValue));
                            Trace.Write(
                                $" Original Value: {myOriginalPixelValue} ({myOriginalByte1}, {myOrginalByte2})");
                            Trace.WriteLine($" Res Value: {myResPixelValue} ({myResByte1}, {myResByte2})");
                            break;
                        }
                    }
                }
            }
```

### fo-dicom version and OS/platform
Windows 10, .NET CORE, fo-dicom 4.0.0-rc1

Thanks in advance

**Comment by gofal** [comment]
There was a fix in RLE encoding in release 4.0.0-rc1: https://github.com/fo-dicom/fo-dicom/pull/681
Was this bug introduced with this fix? Would you be so kind and test with previous version (3.1.0-alpha or 3.0.2) too?

**Comment by VitoHanoi** [comment]
Hey @gofal , 
Nope it was not introduced with this fix as I ran my test on 3.1.0-alpha or 3.0.2 version and I still have this issue

![image](https://user-images.githubusercontent.com/16385289/45788305-d739b100-bccd-11e8-936c-c69622d30362.png)

**Comment by gofal** [comment]
update on this issue: i added the code above into the unit test project, but it runs green on net framework as well as net core. So it might depend on the specific image.

**Comment by gofal** [comment]
This is the same as #681. There are 3 different implementations of RLE: one for Desktop, one for Universal and one for NetCore, I assue for performance reasons. The bug was in all three versions, but has only been fixed in Desktop-implementation. Now I also fixed the two other versions.

Can you get the code from the pull request and verify it with your files?

**Comment by VitoHanoi** [comment]
I'll try to do that. Thanks again. I will let you know about the results

**Comment by jaime-olivares** [comment]
Refer to this post: https://github.com/Efferent-Health/fo-dicom.Codecs/issues/25#issuecomment-1445630560
We are warning that we have found only a Mono implementation for RLE at fo-dicom (not fo-dicom.Codecs). Please confirm.
