### ISSUE TITLE
Creating of DicomPixelData with 32Bit not working in 4.x 

### ISSUE THREAD

**Issue by JuergenDick** [fo-dicom/fo-dicom#716]
I updated  from v3.0.2 to v4.0.0-rc1. 

### Expected behavior

Calling DicomDataPixel.Create(...) with BitsAllocated set to 32-bit not throwing an exception, works in v3.0.2
 
### Actual behavior

Now an exception is thrown when calling DicomDataPixel.Create(...):
Dicom.Imaging.DicomImagingException : Cannot represent pixel data with Bits Allocated: 32 > 16
   at Dicom.Imaging.DicomPixelData.Create(DicomDataset dataset, Boolean newPixelData) in C:\fo-dicom\DICOM\Imaging\DicomPixelData.cs:line 294

BitsAllocated, BitsStored, HighBit, SamplesPerPixel, Columns, Rows were set before calling DicomDataPixel.Create(...) by adding them to the DicomDataSet passed to Create(...) method.

### fo-dicom version and OS/platform

update from v3.0.2 to v4.0.0-rc1, Windows 10

Any suggestions?

**Comment by mia-san** [comment]
no 'update' so far, but just a quick check, it seems that previous version of fo-dicom were creating OtherBytePixelData if BitsAllocated != 16.
it is changed as it is now (throw exception) at #564.

btw, what is your transfer syntax and BitsStored ?

**Comment by JuergenDick** [comment]
Transfer syntax is 1.2.840.10008.1.2.1, BitsStored is 32Bit.

**Comment by mia-san** [comment]
you want whole 32bits to be significant? that's somewhat uncommon...

btw, 1.2.840.10008.1.2.1 is LittleEndian Explicit VR.
regarding to DICOM PS 3.5, A.2 DICOM Little Endian Transfer Syntax (Explicit VR) says following about PixelData:
> •​ where Bits Allocated (0028,0100) has a value greater than 8 shall have Value Representation OW and shall be encoded in Little Endian;
> •​ where Bits Allocated (0028,0100) has a value less than or equal to 8 shall have the Value Representation OB or OW and shall be encoded in Little Endian.
> Note
> The OL Value Representation is not used for Pixel Data, even if it has a Bits Allocated (0028,0100) of 32, since OL was added to the standard after the encoding of Pixel Data had been established

it seems that previous version of fo-dicom used to return OtherBytePixelData as following:
```
if (dataset.Get<ushort>(DicomTag.BitsAllocated) == 16) return new OtherWordPixelData(dataset, true);
else return new OtherBytePixelData(dataset, true);
```
thus previous version does not comply to DICOM.

so this should be fixed anyway.

**Comment by mia-san** [comment]
@JuergenDick would you kindly test pull-request #776?
