### ISSUE TITLE
Not a JPEG file: starts with 0x00 0x00

### ISSUE THREAD

**Issue by sdekker90** [fo-dicom/fo-dicom#717]
### Expected behavior
Open the cineloop and pass through all frames. A calculation is done for each frame. After the calculation, the cineloop's DICOM tags are copied and the multi frame pixel data is replaced with a single frame.

### Actual behavior
Error message "Not a JPEG file: starts with 0x00 0x00" is given at frame 186. When this frame is skipped, a single frame dicom image is successfully created. When opeling the created single frame dicom image, the same error occurs.

The full stack trace is here:

> "   at  Dicom.Imaging.Codec.Jpeg.IJG8.ErrorExit(jpeg_common_struct* cinfo)" & vbCrLf & "   at  jpeg8_read_header(jpeg_decompress_struct* , Int32 )" & vbCrLf & "   at  Dicom.Imaging.Codec.Jpeg.Jpeg8Codec.Decode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomJpegParams params, Int32 frame)" & vbCrLf & "   at  Dicom.Imaging.Codec.DicomJpegNativeCodec.Decode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters)" & vbCrLf & "   at  Dicom.Imaging.Codec.DicomTranscoder.Decode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters) in C:\fo-dicom\DICOM\Imaging\Codec\DicomTranscoder.cs:line 228" & vbCrLf & "   at  Dicom.Imaging.Codec.DicomTranscoder.DecodeFrame(DicomDataset dataset, Int32 frame) in C:\fo-dicom\DICOM\Imaging\Codec\DicomTranscoder.cs:line 179" & vbCrLf & "   at  Dicom.Imaging.DicomImage.Load(DicomDataset dataset, Int32 frame) in C:\fo-dicom\DICOM\Imaging\DicomImage.cs:line 287" & vbCrLf & "   at  Dicom.Imaging.DicomImage.RenderImage(Int32 frame) in C:\fo-dicom\DICOM\Imaging\DicomImage.cs:line 205" & vbCrLf & "   at  IQ.frmMain.bgwMedianImage_DoWork(Object sender, DoWorkEventArgs e) in E:\frm.vb:line 7237"

### Steps to reproduce the behavior
My code looks like this:

```
Dim dcm As New DicomImage(Dicom.DicomFile.Open("E:\1537528860249.dat.dcm").Dataset) With {
                    .WindowCenter = 128,
                    .ShowOverlays = False
                }
For i As Integer = 0 To dcm.NumberOfFrames - 1
                    Dim bmpSlice As Bitmap = dcm.RenderImage(i).AsBitmap.Clone()
'Calculations that give one bitmap: MedianBitmap
Next

Dim pixels As Byte() = GetPixels(MedianBitmap, rows, columns)
Dim buffer As New MemoryByteBuffer(pixels)

'Clone original tags
Dim dcmProcessed as DicomFile = dcm.Clone(DicomTransferSyntax.ExplicitVRLittleEndian)
 Dim pixelData As DicomPixelData = DicomPixelData.Create(dcmProcessed.DataSet, True)
        pixelData.BitsStored = 8
        pixelData.SamplesPerPixel = 3
        pixelData.HighBit = 7
        pixelData.PixelRepresentation = 0
        pixelData.PlanarConfiguration = 0
        pixelData.AddFrame(buffer)

 dcm.Save(strTargetFileName)
```

The original cineloop dicom file can be found here: [https://drive.google.com/open?id=1neiOW7OVbyRH0n7ypX_spU8hxaB0vuDp](url)
The processed single frame resulting from the cineloop can be found here: [https://drive.google.com/open?id=1Pgkr-kUY8lmDS0ZuGwPpb2_lTZIzZOZo](url)

### fo-dicom version and OS/platform
3.0.2 with WinForms .NET 4.5.2

Thank you very much for your input.

**Comment by mia-san** [comment]
it seems to me that the frame is actually broken.

frame 186 begins at file offset 0x008fc870 in the DICOM file.

the frame starts like so

> 008fc870  fe ff 00 e0 f0 02 00 00  00 00 00 00 10 ca 00 00

which interpreted in little endian as
- DICOM item (FFFE,E000)
- data length 0x000002f0 (752) bytes
- JPEG pixel data (00 00 00 00 10 ca 00 00...)

As you might know, JPEG pixel data must be begin with SOI marker (0xff, 0xd8).
The frame in question begins with 0x00, 0x00, which is invalid, causes exception.

for the reference, dcmtk also complains.
```
$ dcmj2pnm --verbose --write-jpeg --frame 187 1537528860249.dat.dcm 1537528860249-187.jpg
I: reading DICOM file: 1537528860249.dat.dcm
I: preparing pixel data
E: found invalid marker in JPEG stream while scanning for bit depth: 0x0000
E: can't decompress frame 186: Pixel representation cannot be changed
E: can't convert input pixel data, probably unsupported compression
F: Invalid DICOM image
```

hope this helps, though it might be too late.
