### ISSUE TITLE
Issues with Getting Response from C-find with Orthnac Server

### ISSUE THREAD

**Issue by deepakaneja** [fo-dicom/fo-dicom#718]
Hello All,

I am using the fo-dicom for imaging device,

when i am trying to getting response from c-find function at the time Refused: Sop class is not supported failure message are showing . can any one can help for related this issue.

`private void CFind()
        {
            try
            { 
                var cFind = DicomCFindRequest.CreateWorklistQuery();
                var client = new DicomClient();
                cFind.OnResponseReceived = (DicomCFindRequest request, DicomCFindResponse response)=>
                {
                    if (response.HasDataset)
                    {                        
                        var instance = response.Dataset.Get<string>(Dicom.DicomTag.SOPClassUID);
                    }
                };
                client.NegotiateAsyncOps();
                client.AddRequest(cFind);
                client.Send("192.168.0.66", 4242, false, "ORTHANC", "ORTHANC");

            }
            catch (Exception ex)
            {
            }
        }`
Showing this message and get dataset is null.

![screenshot_10](https://user-images.githubusercontent.com/11642849/46200159-890c5980-c32e-11e8-9609-1849066e3af6.png)

This is the .dcm file whic is used
 
![screenshot_9](https://user-images.githubusercontent.com/11642849/46199890-d50ace80-c32d-11e8-9391-57005ba5822a.png)

**Comment by gofal** [comment]
I am not sure, what exactly you want to do. In the code you seem to create a worklist query. that means that you query the server (the RIS or HIS) for a list of patients who have a examination planned. For those there are typically no images.
but when you show the dicomfile, it makes me assume, that you want to query a PACS to get images. then you need to create a DicomCFindRequest.CreatePatientQuery or .CreateStudyQuery or .CreateSeriesQuery.
Querying for images or for worklist are differen SOP class UIDs.

**Comment by gofal** [comment]
I hope my answer was helpfull to you. If not then feel free to reopen this issue and provide more infos about you problem.
