### ISSUE TITLE
Question: How to render a dicom file on .NET Core?

### ISSUE THREAD

**Issue by MaherJendoubi** [fo-dicom/fo-dicom#719]
Hi,

How to render the following dicom file on .NET Core?

DicomImage image = new DicomImage(@"test.dcm");

Thanks,
Maher

**Comment by gofal** [comment]
I will copy the posts from gitter.im regarding this topic here, in case someone has a similar question and searches here:

Anders Gustafsson @anders9ustafsson Okt. 01 08:58
@MaherJendoubi You need to include the fo-dicom.Drawing NuGet package, and then you explicitly need to select the WinForms rendering implementation, which uses the System.Drawing.Bitmap renderer. To select implementation, enter the following statement in the beginning of your application: ImageManager.SetImplementation(WinFormsImageManager.Instance). For more info, see the wiki here.

Maher Jendoubi @MaherJendoubi Okt. 01 09:22
@anders9ustafsson Thank you so much Sir. It works on Blazor!

Maher Jendoubi @MaherJendoubi Okt. 01 09:29
@page "/counter"

@using Dicom.Imaging

<h1>Counter</h1>

<p>Current count: @currentCount</p>

<button class="btn btn-primary" onclick="@IncrementCount">Click me</button>

@functions {
    int currentCount = 0;

    void IncrementCount()
    {
        currentCount++;
        ImageManager.SetImplementation(WinFormsImageManager.Instance);
        var image = new DicomImage(@"test1.dcm");
        image.RenderImage().AsBitmap().Save(@"test1.jpg");
    }
}
The method AsBitmap() seems to be deprecated.

Anders Gustafsson @anders9ustafsson Okt. 01 09:53
@MaherJendoubi I have not been too much involved in the deprecation of AsBitmap, but please see the message associated with the obsoleteness warning for further instructions on how to proceed. The change is at least relevant for .NET Framework/Windows Forms, I am not sure how critical it is for .NET Core as it is realistically less tested on this platform.

Anders Gustafsson @anders9ustafsson Okt. 01 22:40
The Obsolete declaration is as follows in the WinFormsImage class: [Obsolete("use AsClonedBitmap or AsSharedBitmap instead.")]
