### ISSUE TITLE
Dicom.Native for Linux

### ISSUE THREAD

**Issue by jaime-olivares** [fo-dicom/fo-dicom#725]
Hi, we are reopening this topic. After working for several months, we have a fully functional set of Native codecs for Linux (tested on Ubuntu) for  fo-dicom 4.0.
All codecs that work on the original Native for Windows will work on Linux.
We have eliminated the need of the intermediate MC++ layer by moving it to either C# or C++ sides. Also, the codecs can be compiled for Windows/NetCore with the same benefit (no managed C++ anymore), as we have separated C++ image libraries for Windows and Linux.

You can preview our code here:
https://github.com/Efferent-Health/fo-dicom/commits/development

We will start providing nuget libraries and perform a pull-request after somebody can use it.

**Comment by jaime-olivares** [comment]
Already published nuget packages for trials:
Dicom.Core:  https://www.nuget.org/packages/fo-dicom.NetCoreHP/4.0.7-efferent
Dicom.Drawing:  https://www.nuget.org/packages/fo-dicom.DrawingHP/4.0.7-efferent

**Be aware of the following**: The native files (`Dicom.Native64.dll` for Windows and `Dicom.Native64.so` for Ubuntu) are stored inside the paths `/runtimes/win-x64/native` and `/runtimes/ubuntu.16.04-x64/native` respectively.

You may need to copy those files to the same folder as `Dicom.Core.dll`

**Comment by mia-san** [comment]
I've just tested the nuget package on .NET Core lightly and seems to be working very nicely.
At least, all the DICOM files in my "backyard" are successfully processed and produces bitmap.
really great !! :+1: 
(actually I also have been trying to use native library in rather native-oriented way privately...)

btw, linux-x64 and win64 are enough for our needs, is it possible to add arm or arm64 support etc?
thank you !

**Comment by jaime-olivares** [comment]
@anders9ustafsson are you interested in integrating this development into fo-dicom?

**Comment by jaime-olivares** [comment]
We are already have this version in production with Ubuntu Linux. No problems reported so far regarding Transfer Syntax conversion

**Comment by mia-san** [comment]
hi, @jaime-olivares.

I've just updated my project to use 4.0.9-efferent, following simple program doesn't work anymore.
it works with 4.0.8-efferent.

I have fo-dicom.NetCoreHP and fo-dicom.DrawingHP installed,
tested Windows10 x64 and Linux x64, same results.
I've also copied Dicom.Native* file into several places, no luck.

any idea?

```
private static void Main(string[] args)
{
    ImageManager.SetImplementation(WinFormsImageManager.Instance);

    var image = new DicomImage("jpeg-lossless.dcm");

    try
    {
        using (var iimage = image.RenderImage())
        {
            iimage.AsSharedBitmap();
            Console.WriteLine("OK");
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine(ex.ToString());
    }

    Console.ReadLine();
}
```
causes 
```
Dicom.Imaging.Codec.DicomCodecException: Decoding dataset with transfer syntax: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression is not supported.
   at Dicom.Imaging.Codec.DicomTranscoder.Decode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)
   at Dicom.Imaging.Codec.DicomTranscoder.DecodePixelData(DicomDataset dataset, Int32 frame)
   at Dicom.Imaging.GrayscaleRenderOptions.FromMinMax(DicomDataset dataset)
   at Dicom.Imaging.GrayscaleRenderOptions.FromDataset(DicomDataset dataset)
   at Dicom.Imaging.DicomImage.CreatePipelineData(DicomDataset dataset, DicomPixelData pixelData)
   at Dicom.Imaging.DicomImage.EstablishPipeline()
   at Dicom.Imaging.DicomImage.GetFrameIndex(Int32 frame)
   at Dicom.Imaging.DicomImage.RenderImage(Int32 frame)
   at ConsoleApp2.Program.Main(String[] args)
```

**Comment by mocsharp** [comment]
Any plans to have this pulled in?

**Comment by jaime-olivares** [comment]
Please refer to issue https://github.com/Efferent-Health/fo-dicom/issues/1
which is located in our fork
Unfortunately we haven't had response from the owner of this repository so we have to keep going by our selves

**Comment by anders9ustafsson** [comment]
@jaime-olivares I am sorry for the late response. I am currently not very active in this development and have not had opportunity to look closer into your efforts, but I plan to do this during the holidays. I will get back to you with more comments as soon as I have looked into your implementation in closer detail.

**Comment by anders9ustafsson** [comment]
@jaime-olivares After quickly browsing through the code, I am wondering about the rationale for having three separate sets of libijg, CharLS and OpenJPEG C/C++ source code. From a maintainability point-of-view this is very unfortunate. Why haven't you based your Windows64 and Linux64 builds on the C/C++ codec source code that was already available in the *fo-dicom* project?

Also, I notice that there are *Dicom.Native64.dll/so* binaries added to the repository. What is the purpose of having these binaries included in version control?

**Comment by jaime-olivares** [comment]
Hi Anders, thanks for reviewing. the binaries are there for easy evaluation, not everybody is able to deal with C++ code with easy. Of course that would be removed whenever everything is tested.

**Comment by jaime-olivares** [comment]
Soled this issue with a different approach. Now using an alternative transcoder rather than forking the entire fo-dicom project: https://github.com/Efferent-Health/Dicom-native
