### ISSUE TITLE
Rethrow as TypeInitializationException: The type initializer for 'Dicom.DicomEncoding' threw an exception.

### ISSUE THREAD

**Issue by wjr992** [fo-dicom/fo-dicom#728]
I am aware of issue #694 but I believe that this is different enough to warrant its own issue as it takes place on a different OS and fo dicom version, and I don't believe the same solution will apply.

### Expected behavior
DicomFile obj = DicomFile.Open(file.FullName);

### Actual behavior
NullReferenceException: Object reference not set to an instance of an object.
10-12 16:29:21.387 10554 10569 E Unity   :   at Dicom.IO.IOManager.get_BaseEncoding () [0x00000] in <00000000000000000000000000000000>:0
10-12 16:29:21.387 10554 10569 E Unity   :   at Dicom.DicomEncoding..cctor () [0x00000] in <00000000000000000000000000000000>:0
10-12 16:29:21.387 10554 10569 E Unity   :   at FileBrowserCUI+<LoadFilesCoroutine>c__Iterator3.MoveNext () [0x00000] in <00000000000000000000000000000000>:0
10-12 16:29:21.387 10554 10569 E Unity   :   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0
10-12 16:29:21.387 10554 10569 E Unity   : Rethrow as TypeInitializationException: The type initializer for 'Dicom.DicomEncoding' threw an exception.
10-12 16:29:21.387 10554 10569 E Unity   :   at FileBrowserCUI+<LoadFilesCoroutine>c__Iterator3.MoveNext () [0x00000] in <00000000000000000000000000000000>:0
10-12 16:29:21.387 10554 10569 E Unity   :   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00000] in <00000000000000000000000000000000>:0

### Steps to reproduce the behavior
Build into an APK with Unity using il2cpp attempt to open a dicom file

### fo-dicom version and OS/platform
newest version of fo-dicom for Unity, Android 8.1 (Oreo)

**Comment by Michael2157** [comment]
hi,i have the same issue with you ,do you solve it?

**Comment by wjr992** [comment]
I actually fixed it by building using mono instead of il2cpp, no idea why il2cpp didnt work

**Comment by frugalspark** [comment]
See also https://github.com/fo-dicom/fo-dicom/issues/885

**Comment by gofal** [comment]
duplicate to #885
