### ISSUE TITLE
CI settings to the public

### ISSUE THREAD

**Issue by idubnori** [fo-dicom/fo-dicom#729]
Hi @gofal, @anders9ustafsson 

Could you export AppVeyor CI settings to yaml file and share it with us?
I would set up CI setting in my forked repository side to analysis an issue.

Also, we could use this yaml for CI setting, if contain it into the repository root.

![export_appveyor](https://user-images.githubusercontent.com/22805312/47056079-a332ac80-d1f5-11e8-9884-446543f79e0c.png)

**Comment by gofal** [comment]
Here you are. Please try it out. If it works, I will add it to the repository:

[appveyor.yml.txt](https://github.com/fo-dicom/fo-dicom/files/2485910/appveyor.yml.txt)

**Comment by idubnori** [comment]
@gofal Thank you for the sharing. Worked well in my forked side. Please have a look at the PR #733.

**Comment by idubnori** [comment]
@gofal oops... AppVeyor might not allow the PR includes appveyor.yml adding, due to auth. Could you merge this by your local side?
