### ISSUE TITLE
JsonDicomConverter deserializtion fails, if VR is not in first position of json property. 

### ISSUE THREAD

**Issue by idubnori** [fo-dicom/fo-dicom#730]
### Expected behavior
Can deserialize, even if vr property is not first position.

### Actual behavior
Deserialize failed.
```
Newtonsoft.Json.JsonReaderException : Malformed DICOM json
```

### Steps to reproduce the behavior
the part of an issue json
```
"00080005": {
  "Value":["ISO 2022 IR 13¥ISO 2022 IR 87"],
  "vr":"CS"
}
```
e.g. `Orthanc` returns this json.
This seems to conform DICOM aggrement.

### fo-dicom version and OS/platform
dotnet, x64, win10

**Comment by idubnori** [comment]
Added the repro test, please have a look at [`VrIsNotFirstPosition`](https://github.com/fo-dicom/fo-dicom/pull/731/files) test result in [this](https://ci.appveyor.com/project/gofal/fo-dicom/builds/19566234/tests)

**Comment by gofal** [comment]
Yes, it is a bug. In https://github.com/fo-dicom/fo-dicom/blob/development/Serialization/Json/JsonDicomConverter.cs#L481 first the ValueRepresentation is read and then in a big switch-statement depending on the ValueRepresentation the value is read and parsed as the corresponding type.

Will you please add a fix to the pull request with the unit test?

**Comment by gofal** [comment]
You fixed this issue in your fork. Does it work?
Would you mind to update the pull request?
Thanks

**Comment by idubnori** [comment]
Sorry for misleading to my commit references the above. I have not found out to essential the fix solution yet.
