### ISSUE TITLE
Sneding DICOM over TLS hangs when other side is not TLS enabled

### ISSUE THREAD

**Issue by Telexy** [fo-dicom/fo-dicom#732]
### Expected behavior

When you send DICOM using TLS and accidentally point to destination which listens, but not TLS enabled - I would expect timeout.

### Actual behavior

It hangs in  DesktopNetworkStream constructor (sssl.AuthenticateAsClient to be precise)

### Steps to reproduce the behavior

Just send DICOM when Client is TLS enabled to server which is not TLS enabled.

### fo-dicom version and OS/platform

All versions for how long I remember.  Proposed way to fix: add this 2 lines into the constructor:

                ssl.ReadTimeout  = 180000;
                ssl.WriteTimeout = 180000;

Like this:

        /// <summary>
        /// Initializes a client instance of <see cref="DesktopNetworkStream"/>.
        /// </summary>
        /// <param name="host">Network host.</param>
        /// <param name="port">Network port.</param>
        /// <param name="useTls">Use TLS layer?</param>
        /// <param name="noDelay">No delay?</param>
        /// <param name="ignoreSslPolicyErrors">Ignore SSL policy errors?</param>
        internal DesktopNetworkStream(string host, int port, bool useTls, bool noDelay, bool ignoreSslPolicyErrors)
        {
            this.RemoteHost = host;
            this.RemotePort = port;

#if NETSTANDARD
            this.tcpClient = new TcpClient { NoDelay = noDelay };
            this.tcpClient.ConnectAsync(host, port).Wait();
#else
            this.tcpClient = new TcpClient(host, port) { NoDelay = noDelay };
#endif

            Stream stream = this.tcpClient.GetStream();
            if (useTls)
            {
                var ssl = new SslStream(
                    stream,
                    false,
                    (sender, certificate, chain, errors) => errors == SslPolicyErrors.None || ignoreSslPolicyErrors);

!!!! PROPOSED FIX              
                // or AuthenticateAsClient will hang if no TLS on other side...
                ssl.ReadTimeout  = 180000;
                ssl.WriteTimeout = 180000;
!!!! END OF PROPOSED FIX              

#if NETSTANDARD
                ssl.AuthenticateAsClientAsync(host).Wait();
#else
                ssl.AuthenticateAsClient(host);
#endif
                stream = ssl;
            }

            this.LocalHost = ((IPEndPoint)tcpClient.Client.LocalEndPoint).Address.ToString();
            this.LocalPort = ((IPEndPoint)tcpClient.Client.LocalEndPoint).Port;

            this.networkStream = stream;
        }

**Comment by gofal** [comment]
Thanks for the fix shipping with the issue. Would you mind to create a pull request?

**Comment by Telexy** [comment]
Totally agree. Parameter is always better. 5000 is not enough for my specific case, but If I can change it - who cares. I think I put hardcoded maximum values in that place because there was no access to that parameter in that particular place and I wanted to keep my modifications minimal. 

Thanks.

**Comment by gofal** [comment]
Ok, I see. 3 minutes timeout just for creating a network connection without even sending a single data seems too much for me as default. So if you don't mind I keep the 5 seconds.
When calling DicomClient.Send then you can use the timeout parameter and set it to 180000.
