### ISSUE TITLE
JPEG 2000 Image Compression (Lossless Only) decompress cause -32768 shift in signed 16bit data.

### ISSUE THREAD

**Issue by terarecon-keiji** [fo-dicom/fo-dicom#738]
### Expected behavior

Pixel value needs to be extracted by correct value in signed 16bit JPEG2000 compressed data.

### Actual behavior

Pixel value are shifted to -32768.

### Steps to reproduce the behavior
original test.dcm is Explicit little endian 16bit signed (PixelRepresentation 1) grayscale image data.
Then Encode to 1.2.840.10008.1.2.4.90. This result seems OK. 
Then Decode this result to 1.2.840.1008.1.2 Explicit little endian again. the result is shifted to -32768.

```
    class Program
    {
        private static string Filename = @"test.dcm";

        static void Main(string[] args)
        {
            if (args.Length != 0)
                Filename = args[0];

            var newFileName = Encode(Filename, "1.2.840.10008.1.2.4.90");
            Encode(newFileName, "1.2.840.10008.1.2");
        }

        private static string Encode(string fileName, string transferSyntax)
        {
            var dst = Path.GetFileNameWithoutExtension(fileName);
            var ext = ".dcm";
            var i = 0;
            var dstName = $"{dst}{ext}";
            while (File.Exists(dstName))
            {
                i++;
                dstName = $"{dst}-{i}{ext}";
            }

            try
            {
                using (var inStream = File.OpenRead(fileName))
                {
                    var f = DicomFile.OpenAsync(inStream).Result;
                    var ts = DicomTransferSyntax.Parse(transferSyntax);
                    using (var outStream = File.OpenWrite(dstName))
                        Dicom.Imaging.Codec.DicomCodecExtensions.Clone(f, ts).Save(outStream);
                }
            }
            catch (Exception e)
            {
                Console.WriteLine(fileName + "   " + e.Message);
                return null;
            }

            return dstName;
        }
    }
```

### fo-dicom version and OS/platform
fo-dicom 4.0.0. Windows 10.0.17134 Pro x64
.NET Core app.

I think the reason is from
fo-dicom\DICOM\Imaging\Codec\DicomJpeg2000CodecImpl.cs line# 248 in Decode() in if (bytesAllocated == 2) and if (newPixelData.PixelRepresentation == PixelRepresentation.Signed).

`int i = (i = comp[p] - sign) < 0 ? (i & mask) | sign : i & mask;`

Encode() function similar section doesn't have it. I think the code may not be required.

**Comment by gofal** [comment]
If you take a look at the wiki page, you will see that Jpeg2k is only supported for 8 bit on .Net Core:
https://github.com/fo-dicom/fo-dicom/wiki/Supported-Transfer-Syntaxes

But if you found a reason and could fix it to make Jpeg2k available for 16bit on .Net Core it would be very great if you could give it a try and create a pull request.

**Comment by gofal** [comment]
Would you please try to reproduce this bug when using Efferent's implementation of the codec?

https://github.com/Efferent-Health/fo-dicom.Codecs

Fo-dicom will use their codec as default in future.

**Comment by gofal** [comment]
I will close this issue due to inactivitiy. If there is still an issue with the latest version of fo-dicom, then please feel free to reopen this issue and provide actual informations.
