### ISSUE TITLE
UID: Unknown [1.2.752.24.3.7.7] is not a transfer syntax type.

### ISSUE THREAD

**Issue by buckstephenh** [fo-dicom/fo-dicom#739]
### Expected behavior

1.2.752.24.3.7.7 Sectra private syntax should be supported in fo-dicom out of the box OR we should be able to create transfer syntaxes/translations on the fly or using a properties file used to construct the static classes.
   
https://sectramedical.blob.core.windows.net/uploads/2017/09/pacs-dicom-conformance-statement-14.2.pdf

### Actual behavior

Dicom.DicomTransferSyntax, DicomUID, DicomUIDPrivate, etc contains static constructions and is not data driven.  There appears to be no hooks to modify or provide transfer syntax translation without recompilation.   

Exception processing PDU: {@error}Dicom.DicomDataException: UID: Unknown [1.2.752.24.3.7.7] is not a transfer syntax type.
  at Dicom.DicomTransferSyntax.Lookup(DicomUID uid)
  at Dicom.Network.AAssociateRQ.Read(RawPDU raw)
  at Dicom.Network.DicomService.ListenAndProcessPDUAsync()

There is a GE private syntax, but I think the point here should be to allow the user of fo-dicom who creates the DICOMService to have the hooks to accept/translate an association.

This problem does not seem to appear in 3.1.0-alpha
 
### Steps to reproduce the behavior

Association accept:
{association}TR_SEND|Calling AE Title:       TR_SEND
Called AE Title:        SMH
Remote host:            10.191.1.47
Remote port:            59775
Implementation Class:   Implementation Class UID [1.2.752.24.3.3.25.7]
Implementation Version: SISTOSCU_20_1
Maximum PDU Length:     28672
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
 Presentation Context:  1 [Accept]
      Abstract Syntax:  Grayscale Softcopy Presentation State Storage
      Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM

### fo-dicom version and OS/platform

    <PackageReference Include="fo-dicom" Version="4.0.0-rc1" /> 
    macOS 10.14.1 Beta (18B57c)

**Comment by gofal** [comment]
is this duplicate to #703 ?

**Comment by gofal** [comment]
fixed with #753
