### ISSUE TITLE
RenderImage - Missing Windows / Contrast

### ISSUE THREAD

**Issue by panleya** [fo-dicom/fo-dicom#741]
### Expected behavior
Calling RenderImage to a Bitmap will include the window levels and contracts seen in the Dicom Viewer.

### Actual behavior
Windows and contrast levels are missing.

### fo-dicom version and OS/platform
4.0.0 release, windows 2012 server.  .net 4.5

**Comment by gofal** [comment]
After you have created a DicomImage instance, before you call the RenderImage, you can set all the desired properties (https://fo-dicom.github.io/html/e184072d-8652-91db-eb20-566cf52d42cb.htm).
Use DicomImage.WindowWidth and DicomImage.WindowCenter for windowing.

**Comment by panleya** [comment]
The windows are already setup in the file.  I just want to render the image as was setup by the radiologist.

**Comment by panleya** [comment]
Here is one of the files...


[IM-0001-0001-0001.dcm.zip](https://github.com/fo-dicom/fo-dicom/files/2531244/IM-0001-0001-0001.dcm.zip)

**Comment by gofal** [comment]
I removed you image, because it was not anonymized.

I cannot reproduce the issue with the frame 0. In current development code as well as in a new project with fo-dicom 4.0.0 downloaded via nuget, I can execute the following code without problem:

     static void Main(string[] args)
      {
         var file = DicomFile.Open(@"IM-0001-0001-0001.dcm");
         var img = new DicomImage(file.Dataset);

         var bmp = img.RenderImage(0).AsClonedBitmap();
         bmp.Save(@"rendered1.bmp");

         img.WindowWidth = file.Dataset.GetValue<double>(DicomTag.WindowWidth, 0);
         img.WindowCenter = file.Dataset.GetValue<double>(DicomTag.WindowCenter, 0);

         bmp = img.RenderImage(0).AsClonedBitmap();
         bmp.Save(@"rendered2.bmp");
      }

But I see that there is actually no windowing applied. I assume because this sample image does not contain 1 windowing setup, but an array of windowing setups (2 elements, both of them have the same values...). 
This is to be fixed.

**Comment by gofal** [comment]
This issue is based on a bug that was introduced in version 4.0 with the new GetValue-methods in DicomDataset. I wonder if the bug is also in version 3?
What problem do you exactly face with version 3?

**Comment by XMAN274** [comment]
In print scp., the printed image not the same as the monitor, i have to change the window width and window level to make the image more darker, and the final printed image it like pixeld image, i don't know if it resolution  or what, but please resolve the issue of the window first

**Comment by gofal** [comment]
are you implementing the print scu client, who has to prepare the printed image, or are you the print scp who receives the dataset and prints it?

**Comment by khaledyasser95** [comment]
> 
> 
> In print scp., the printed image not the same as the monitor, i have to change the window width and window level to make the image more darker, and the final printed image it like pixeld image, i don't know if it resolution or what, but please resolve the issue of the window first

I have this exact problem
