### ISSUE TITLE
int/uint stream position overflow

### ISSUE THREAD

**Issue by Telexy** [fo-dicom/fo-dicom#743]
Hi,

I got couple big DICOM clips (2500 frames - 800+G and 4000 frames - 1.5G) and I found that DicomImage.RenderImage() does not extract proper frames after 750th. It keeps returning same frame until 1500 and then returns corrupted image at all. 

Quick research revealed uint (and even int) variables used to hold position or offset in that DICOM stream. So they just not big enough to hold proper value and have to be replaced with long.

The place to start from - the following 2 lines in DicomPixelData.cs:

                var offset = UncompressedFrameSize * frame;
                return new RangeByteBuffer(_element.Buffer, (uint)offset, (uint)UncompressedFrameSize);

They actually happen 2 times there: in OtherBytePixelData and OtherWordPixelData. That offset is integer, so that code should be replaced with the following:

                long offset = (long)UncompressedFrameSize * frame;
                return new RangeByteBuffer(_element.Buffer, offset, (uint)UncompressedFrameSize);

That will force you to do appropriate modifications in RangeByteBuffer and related stuff. Basically you will need to modify IFileReference and IByteBuffer interfaces in the following way:

Replace 
byte[] GetByteRange(**int** offset, int count); with
byte[] GetByteRange(**long** offset, int count);

Plus all the implementation of those interfaces...

Thanks.

**Comment by gofal** [comment]
this "offset" is only internally use? So did you se some traps or drawbacks when changing fron int to long?

**Comment by gofal** [comment]
Did you already try to do this? I easily managed to change the Offset - and then of course also the Length - from int/uint to long, but then I soon came to functions where the buffer or part of the buffer has to be copied and all common fast array-copy methods are only available wich indexes of type int. type long is only available for Desktop, but not for NetCore (the second most used fo-dicom platform after desktop) so this requires quite lot of platform dependent code - so this makes some effort.
Or did I miss something?

**Comment by gofal** [comment]
I think I got every spot to cast down from long to int or uint. The unittests and my local tests work fine, so I didn't break something. But I do not have such large DICOM files. Could you try to get the code from the branch GH-743 and try if you can open the large file without problem?
Thanks.

**Comment by Telexy** [comment]
Sure, I will. Next week.

Thanks a lot,
Dmytro

**Comment by mia-san** [comment]
may GH-743 fixes #402 ?

**Comment by gofal** [comment]
Yes, I am pretty sure it will fix #402 too. Thanks for linking these issues.

**Comment by Telexy** [comment]
Finally tested. Works good with my 2 large files. However one spot is still missing (wasn't called in my case, but still...). Please refer to my first note regarding 2 places in DicomPixelData.cs. You fixed first one (in OtherBytePixelData::GetFrame), but left second place the same (OtherWordPixelData::GetFrame). Other then that - I don't see any issues. Thanks.
