### ISSUE TITLE
Default Transfer Syntax for Lossless JPEG Image Compression is not supported.

### ISSUE THREAD

**Issue by panleya** [fo-dicom/fo-dicom#744]
### Expected behavior
Default Transfer Syntax for Lossless JPEG Image Compression IS supported.

### Actual behavior
Default Transfer Syntax for Lossless JPEG Image Compression is not supported. error when RenderImage is executed.

### Steps to reproduce the behavior
Unknown cause

### fo-dicom version and OS/platform
4.0.0 Windows 2012 with c++ libraries from 2017 installed.

**Comment by gofal** [comment]
please provide more infos: wich framework and which version are you using (https://github.com/fo-dicom/fo-dicom/wiki/Supported-Transfer-Syntaxes). For .net core it is not supported. Otherwise it should work.
provide an exact error message and a callstack of the exception. Can you provide a anonymized sample image? Did you buid in x86, x64 or anycpu?

**Comment by mia-san** [comment]
regarding RenderImage and JpegLossless, may #725 may help?

**Comment by kdma** [comment]
I have the same problem
fo-dicom desktop targeting .NET 4.7.2
 steps to reproduce :
```
var dicomFileRepresentative =  DicomFile.Open("anon2140");
DicomImage dcmImage = new DicomImage(dicomFileRepresentative.Dataset);
Bitmap unsafeBitmap = dcmImage.RenderImage().AsClonedBitmap();
```

[Example dcm file](https://github.com/fo-dicom/fo-dicom/files/2553882/anon_dcm.zip)

**Comment by mia-san** [comment]
Any chance you are building your program in "Any CPU" ?
Try building x64 or x86.

If you really need to build your program in "Any CPU", copy Dicom.Native.dll and Dicom.Native64.dll from packages\fo-dicom.Desktop.4.0.0\build\net45\ into target directory(bin\Debug or bin\Release or such, where your executable lives).

btw, have you noticed following message during build ?
`  fo-dicom native libraries require the target platform to be explicitly specified.
  Change 'ConsoleApplication1' Platform Target Build Project Property from 'AnyCPU' to either x86 or x64 to remove this message.`

(de)compression may handled by Dicom.Native*.dll, but the DLLs are not copied into target directory in "Any CPU" build.

**Comment by kdma** [comment]
> Any chance you are building your program in "Any CPU" ?
> Try building x64 or x86.
> 
> If you really need to build your program in "Any CPU", copy Dicom.Native.dll and Dicom.Native64.dll from packages\fo-dicom.Desktop.4.0.0\build\net45\ into target directory(bin\Debug or bin\Release or such, where your executable lives).
> 
> btw, have you noticed following message during build ?
> ` fo-dicom native libraries require the target platform to be explicitly specified. Change 'ConsoleApplication1' Platform Target Build Project Property from 'AnyCPU' to either x86 or x64 to remove this message.`
> 
> (de)compression may handled by Dicom.Native*.dll, but the DLLs are not copied into target directory in "Any CPU" build.

And that was the problem I was targeting AnyCpu, I didnt check the build output at all (lazy me)
Thank you for the help.

**Comment by mia-san** [comment]
@panleya are you still getting the error ?

**Comment by panleya** [comment]
I target x64 explicitly, always have, and still have this issue.

**Comment by gofal** [comment]
duplicate to #781? This may also be solved as here:
https://github.com/fo-dicom/fo-dicom/issues/886#issuecomment-522423070
