### ISSUE TITLE
Broken image upon RetainLongFullDates

### ISSUE THREAD

**Issue by martinweihrauch** [fo-dicom/fo-dicom#751]
I used this:

var _anonymizer = new DicomAnonymizer(DicomAnonymizer.SecurityProfile.LoadProfile(null, DicomAnonymizer.SecurityProfileOptions.RetainLongFullDates));

to create a new image with anonymized data. When I do the default (just new DiconAnonymizer()), everything works OK. If I use the profil "DicomAnonymizer.SecurityProfileOptions.RetainLongFullDates", the whole image is corrupted, which means that actually the last quarter of the image is shown on the left.

Plus with "RetainLongFullDates", the patient name is still present.

**Comment by mia-san** [comment]
Regarding PatientName, SecurityProfileOptions seems to mean 'basic profile + some other options.'
Does following work?
```
var anonymizer = new DicomAnonymizer(
    DicomAnonymizer.SecurityProfile.LoadProfile(
        null,
        DicomAnonymizer.SecurityProfileOptions.BasicProfile |
        DicomAnonymizer.SecurityProfileOptions.RetainLongFullDates
    )
);
```

I could not reproduce 'corrupted image' symptom.
May DicomAnonymizer.SecurityProfileOptions.RetainSafePrivate help?

**Comment by martinweihrauch** [comment]
OK, when I do this:

                var _anonymizer = new DicomAnonymizer(DicomAnonymizer.SecurityProfile.LoadProfile(
                    null,
                    DicomAnonymizer.SecurityProfileOptions.BasicProfile |
                    DicomAnonymizer.SecurityProfileOptions.RetainSafePrivate
                    )
                );

Then I get an image that is "broken":

![grafik](https://user-images.githubusercontent.com/2306324/48947130-6ebaba80-ef30-11e8-8f67-d840b3389d9d.png)

**Comment by martinweihrauch** [comment]
When I do what was suggested by you:
var anonymizer = new DicomAnonymizer(
    DicomAnonymizer.SecurityProfile.LoadProfile(
        null,
        DicomAnonymizer.SecurityProfileOptions.BasicProfile |
        DicomAnonymizer.SecurityProfileOptions.RetainLongFullDates
    )
);

Then the image is still OK

**Comment by martinweihrauch** [comment]
BTW: what I would like to keep  is 
- the patient's age (not DOB) on the date of the examination and 
- male/female
- plus date of exam (as you already showed me). 
Then, the patient would still be anonymous, but you can better use the case for teaching / case presentations? I. e. "57yo male patient with a history of colon cancer had a CT scan on 11/28/2018 and one on 09/25/2017"
Is there a simple way to do that?

**Comment by mia-san** [comment]
> BTW: what I would like to keep is
> 
>     * the patient's age (not DOB) on the date of the examination and
> 
>     * male/female
> 
>     * plus date of exam (as you already showed me).
>       Then, the patient would still be anonymous, but you can better use the case for teaching / case presentations? I. e. "57yo male patient with a history of colon cancer had a CT scan on 11/28/2018 and one on 09/25/2017"
>       Is there a simple way to do that?

Regarding to DICOM/DicomAnonymizer.cs, it is supposed to comply to PS3.15 Security and System
Management Profiles, E Attribute Confidentiality Profiles.
Table E.1-1. Application Level Confidentiality Profile Attributes seems to require that most of patient attributes to be removed or erased.

so if you want to retain several attributes, you may have to save and restore those like so
```
var file = DicomFile.Open("origin.dcm");

var patient_age = file.Dataset.GetSingleValueOrDefault(DicomTag.PatientAge, "");
var patient_sex = file.Dataset.GetSingleValueOrDefault(DicomTag.PatientSex, "");
var study_date = file.Dataset.GetSingleValueOrDefault(DicomTag.StudyDate, "");

var anonymizer = new DicomAnonymizer();
var anonymized = anonymizer.Anonymize(file);

anonymized.Dataset.AddOrUpdate(DicomTag.PatientAge, patient_age);
anonymized.Dataset.AddOrUpdate(DicomTag.PatientSex, patient_sex);
anonymized.Dataset.AddOrUpdate(DicomTag.StudyDate, study_date);

anonymized.Save("anonymized.dcm");
```

**Comment by mia-san** [comment]
> OK, when I do this:
> 
> ```
>             var _anonymizer = new DicomAnonymizer(DicomAnonymizer.SecurityProfile.LoadProfile(
>                 null,
>                 DicomAnonymizer.SecurityProfileOptions.BasicProfile |
>                 DicomAnonymizer.SecurityProfileOptions.RetainSafePrivate
>                 )
>             );
> ```
> 
> Then I get an image that is "broken":

so far
*  no options given(should equivalent to BasicProfile only) - OK
*  BasicProfile | RetainLongFullDates only - OK
*  RetainLongFullDates only - bad
*  BasicProfile | RetainSafePrivate only - bad
?

looks strange.

could you share anonymized 'broken' DICOM file ?

**Comment by martinweihrauch** [comment]
Again, thanks for your help! I attached the zipped anonymized "broken" file.
As I noticed, how much DICOM libraries usually cost, (Leadtools, Vintasoft), it's sad there is not more development going on. Are you finananced at all? Is there some company involved here to support your efforts?

Martin

[anonfile.zip](https://github.com/fo-dicom/fo-dicom/files/2612547/anonfile.zip)

**Comment by mia-san** [comment]
thanks for sharing.
but the 'broken' image not seems to be broken.

I've just tested the file against dcmtk and a few DICOM viewers as following.
as you see, the image seems to be rendered properly.
perhaps your DICOM viewer got confused for some reason ?

$ dcmj2pnm --write-jpeg --use-window 1 anonfile anonfile-dcmj2pnm.jpg
![anonfile-dcmj2pnm](https://user-images.githubusercontent.com/8837998/48973154-37f1bb00-f07c-11e8-817f-b89ce5873641.jpg)

aeskulap
![anonfile-aeskulap](https://user-images.githubusercontent.com/8837998/48973163-55268980-f07c-11e8-9dcb-65c7b8f77de0.png)

dicomscope
![anonfile-dicomscope](https://user-images.githubusercontent.com/8837998/48973164-5ce62e00-f07c-11e8-8219-d7f59f77b023.png)

**Comment by mia-san** [comment]
as to finantial things, you can donate to this project via paypal.
see project top page.

**Comment by martinweihrauch** [comment]
Damn. You're right. I was using Radiant alongside programming in Visual Studio and reloaded the slide. Probably, there is some glitch when reloading the "same" file again after changed with Visual Studio. Sorry about that, my bad!

What are you doing with the donations?

Best

Martin

**Comment by martinweihrauch** [comment]
Plus, how can I anonymize the DICOMDIR file? As far as I understand, it may also contain patient info.

**Comment by mia-san** [comment]
Do you really want to anonymize existing DICOMDIR file?

UIDs in DICOM file are replaced with new values in anonymization unless you specify RetainUIDs.
so it'd be better to create new DICOMDIR file from anonymized DICOM files.
otherwise, you may have to walk the DICOMDIR and anonymize appropriately.

Also, regarding to DicomAnonymizer options, what you want might be
```
var anonymizer = new DicomAnonymizer(
  DicomAnonymizer.SecurityProfile.LoadProfile(
    null,
    DicomAnonymizer.SecurityProfileOptions.BasicProfile |
    DicomAnonymizer.SecurityProfileOptions.RetainPatientChars |
    DicomAnonymizer.SecurityProfileOptions.RetainLongFullDates
  )
);
```
This should be easier than save/restore DICOM attributes.
RetailLongFullDates could be RetainLongModifDates, depending on requirement.

Anyway, see PS3.15 Security and System Management Profiles, E Attribute Confidentiality Profiles,
Table E.1-1. Application Level Confidentiality Profile Attributes.
It should help.

**Comment by gofal** [comment]
As I understand the original issue was solved. Will close this issue. If there is still a problem, feel free to reopen this issue.
