### ISSUE TITLE
White image when pixel data is rendered as image

### ISSUE THREAD

**Issue by frugalspark** [fo-dicom/fo-dicom#752]
With certain dicom files, the image rendered appears white instead of the expected grayscale.
This occurs in both foDicom v4.0 (running Dump.exe) and the Unity plugin (v3.5.0) using:

```
DicomImage( dicomFile.Dataset, frameIndex ).RenderImage( frameIndex )?.AsTexture2D()
```

This is observed on Windows 10 and Mac OS (10.13.6) platforms.
To reproduce open the attached example test file (160.dcm) in Dump.exe and 'View' the image.

[160.dcm.zip](https://github.com/fo-dicom/fo-dicom/files/2610489/160.dcm.zip)

The intensities in this file are all above 12k - so possibly a ‘default’ scaling issue?

Note, if I bypass RenderImage, and normalise the pixel data manually using the min & max values and then multiply the normalised value against the target image pixel value e.g. in Unity Texture2D this is 255, the grayscale image is restored (see attached).

![expectedimage](https://user-images.githubusercontent.com/20279764/48940572-14116680-ef10-11e8-8f14-8bb84e7d121d.png)

**Comment by mia-san** [comment]
yes, shared DICOM file actually produces 'white' image.

But WindowCenter and WindowWidth seem to be the cause.
image is 16 bits per pixel(BitsAllocated = 16, BitsStored = 16), WindowCenter = 3174 and WindowWidth = 2426 is extremely unusual to me.

Actually, removing WindowCenter and WindoWidth seems to produce intended image.
```
var file = DicomFile.Open("image.dcm");
file.Dataset.Remove(DicomTag.WindowCenter, DicomTag.WindowWidth);

var image = new DicomImage(file.Dataset);

using (var iimage = image.RenderImage())
{
    iimage.AsSharedBitmap().Save("image.jpg", ImageFormat.Jpeg);
}
```

Also, for reference, dcmtk produces following image.
```
$ dcmj2pnm --verbose --write-jpeg 160.dcm 160-window-none.jpg 
I: reading DICOM file: 160.dcm
I: preparing pixel data
I: disabling VOI window computation
I: writing frame 1 to 160-window-none.jpg
I: cleaning up memory
```
![160-window-none](https://user-images.githubusercontent.com/8837998/48960935-2e9d1b80-efb4-11e8-9948-7b837252bc8f.jpg)

but produces 'white' image if window was specified.

```
$ dcmj2pnm --verbose --write-jpeg --use-window 1 160.dcm 160-window-1.jpg 
I: reading DICOM file: 160.dcm
I: preparing pixel data
I: activating VOI window 1
I: writing frame 1 to 160-window-1.jpg
I: cleaning up memory
```
![160-window-1](https://user-images.githubusercontent.com/8837998/48960977-820f6980-efb4-11e8-841b-8f50f9034b0e.jpg)

**Comment by gofal** [comment]
fo-dicom behaves correct. If there are dicom tags WindowWith and WindowCenter availabe, then the values shall be used. This seems to be an issue with the aquisitioning modality.
Thanks to mia-san, who showed a workaround to fix the modalities issue. If there are no windowwith and windowcenter then fo-dicom iterates the whole pixel array and tries to find the minimum and maximum and then calculates a windowwitdh and windowcenter. This is little bit more time consuming. So if your application is time critical I would recommend not just to delete the windowing tag but to try to contact the source of the images so that they fix the values.

**Comment by frugalspark** [comment]
Thanks @mia-san & @gofal for looking into this and for the workaround. 
As the affected dicom files are from a number of different health trusts, it's probably not appropriate for us to suggest to them how they should be using their equipment. We will have to use a workaround for now.

In general, what's the impact if the window width and window center are ignored when rendering an image?
And is there an override or parameter to set RenderImage() to ignore the window attributes without removing the attributes?

**Comment by mia-san** [comment]
> In general, what's the impact if the window width and window center are ignored when rendering an image?

from top of my head,
window settings are referred on rendering image, as described in
  PS 3.3 Information Object Definitions
  C.11.2.1.2 Window Center and Window Width.

1. as @gofal  mentioned, program may have to scan all the pixels in image to guess window setting, which might be slow.

2. guessed window settings might not exactly same as intended by modality on acquisition.
  for example, dcmtk also renders different image from same DICOM file.
(sorry, dcmtk is handy for this kind of work ;)

no window specified:
![dcmj2pnm](https://user-images.githubusercontent.com/8837998/49021429-efe6ab80-f1d5-11e8-97fa-8e5b9e7781bc.jpg)

window guessed:
![dcmj2pnm min-max-window](https://user-images.githubusercontent.com/8837998/49021456-0260e500-f1d6-11e8-8191-0c93b2182266.jpg)

using window setting:
![dcmj2pnm use-window-1](https://user-images.githubusercontent.com/8837998/49021474-0c82e380-f1d6-11e8-9ed5-1176086c1c58.jpg)

3. some modalities may have multiple window settings, e.g. one for bone, one for soft tissue etc.
  if window settings are missing or invalid, how we could we render bone or soft tissue properly ?
  actually, one of my sample image has following window setting.
  WindowCenter: 2635\2653\2593
  WindowWidth: 750\600\900
  WindowCenterWidthExplanation: NORMAL\HARDER\SOFTER


> And is there an override or parameter to set RenderImage() to ignore the window attributes without removing the attributes?

DicomImage class has WindowCenter and WindowWidth property.
so something like following should work.
through removing window setting might be better if window setting is *invalid* like your image.
```
var image = new DicomImage("dicom.dcm");

image.WindowCenter = WindowCenter1;
image.WindowWidth = WindowWidth1;
using (var iimage = image.RenderImage())
{
    iimage.AsSharedBitmap().Save("image1.jpg", ImageFormat.Jpeg);
}

image.WindowCenter = WindowCenter2;
image.WindowWidth = WindowWidth2;
using (var iimage = image.RenderImage())
{
    iimage.AsSharedBitmap().Save("image2.jpg", ImageFormat.Jpeg);
}
```

**Comment by frugalspark** [comment]
That's awesome @mia-san ! Thank you.
As we need to automate the image rendering, I guess we will need to traverse through the pixel data to check if they are within the window width range before deciding to remove them...unless there's a quicker way to determine if the window center/width values are valid?

**Comment by mia-san** [comment]
I'm not 100% sure about recovering window setting, but it seems to be a tricky business to me.

my understanding is that, you can get minimum/maximum pixel value, but 'proper' window setting may differ, as I said before.
resulting image may not be what intended(too black, too white, blur, etc etc).
it could also be possible that seemingly-erroneous window setting is actually correct.

in other words, that's something like decoding byte array into string without knowing character set  and encoding.
it could be UTF-8, it could be ISO 8859-1, it could be some random character set used in some region, or total garbage.
resulting string can be either right or wrong.

so one could say DICOM image data with invalid window setting is 'broken'.

sorry to be vague.

**Comment by gofal** [comment]
@mia-san I totally agree. I was involved in a lot of installations of medical modalities and one of the long lasting tasks of the technican who sets up the modality is to find window settings for the modality that the diagnosting medical doctor is fine with. There is no automatic guessing except the min-max-value range, but this default is seldom satisfying for diagnostic purposes.

Thats why I wrote the solution would be to raise an issue at the vendor where the images come from. 

Another idea that came into my mind. Are there additional files contained in the study? I am thinking of presentation states. That are kind of structured reports that contain information, how the referenced image has to be displayed (zooming, panning, windowing, rotation, flipping, overlays, annotations, ..) Could it be possible that the vendor sends the windowing-information in presentation states files?
