### ISSUE TITLE
Enhanced US Volume storage not identified as image

### ISSUE THREAD

**Issue by PimPhilipse** [fo-dicom/fo-dicom#755]
### Expected behavior
DicomUID.EnhancedUSVolumeStorage.IsImageStorage returns true

### Actual behavior
DicomUID.EnhancedUSVolumeStorage.IsImageStorage returns false

### Steps to reproduce the behavior
Assert.True(DicomUID.EnhancedUSVolumeStorage.IsImageStorage)

### fo-dicom version and OS/platform
3.02 Windows 7 .NET 4.5.2

The issue is caused by the fact that the StorageCategory property uses the following line to determine whether a particular SOP Class is an image: 

                if (Name.Contains("Image Storage")) return DicomStorageCategory.Image;

And because "Enhanced US Volume Storage" fails this test, it is denied the image status.
However, PS3.3 Table A.59-1 shows that it has among others a Pixel Module, so it is definitely image-like.

**Comment by mia-san** [comment]
Is it better to add something like DicomStorageCategory.VolumeStorage and DicomUID.IsVolumeStorage ?
otherwise
`if (Name.Contains("Image Storage") || Name.Contains("Volume Storage")) return DicomStorageCategory.Image;`
is enough?

also, search for 'VolumeStorage' reveals
```
DICOM\DicomUIDGenerated.cs(167):            _uids.Add(DicomUID.EnhancedUSVolumeStorage.UID, DicomUID.EnhancedUSVolumeStorage);
DICOM\DicomUIDPrivate.cs(61):            _uids.Add(DicomUID.PrivatePhilipsVolumeStorage.UID, DicomUID.PrivatePhilipsVolumeStorage);
DICOM\DicomUIDPrivate.cs(62):            _uids.Add(DicomUID.PrivatePhilipsVolumeStorageRetired.UID, DicomUID.PrivatePhilipsVolumeStorageRetired);
DicomUIDPrivate.cs(67):            _uids.Add(DicomUID.PrivateSiemensCTMRVolumeStorage.UID, DicomUID.PrivateSiemensCTMRVolumeStorage);
```

what about these private volume storage sop classes ?

**Comment by gofal** [comment]
I'd also prefer a new category ".IsVolumeStorage"
