### ISSUE TITLE
How to store 16 bit ushort buffer in DicomPixelData structure

### ISSUE THREAD

**Issue by FiifiB** [fo-dicom/fo-dicom#760]
### Expected behavior
 
public void SetPixelData(Array newPixelDataArray)
        {
            if (isCompressed())
                Decompress();

            DicomPixelData newPixelData = DicomPixelData.Create(DataSet, true);

            if (BitsAllocated == 8)
            {
                for (int i = 0; i < PixelDimensions[2]; i++)
                {
                    byte[] frame = new byte[PixelData.Width * PixelData.Height * PixelData.SamplesPerPixel];
                    Array.Copy(newPixelDataArray, PixelData.Width * PixelData.Height * PixelSize * i, frame, 0, PixelData.UncompressedFrameSize);
                    MemoryByteBuffer memoryByteBuffer = new MemoryByteBuffer(frame);
                    newPixelData.AddFrame(memoryByteBuffer);
                }
            }
            else if (BitsAllocated == 16)
            {
                for (int i = 0; i < PixelDimensions[2]; i++)
                {
                    ushort[] frame = new ushort[PixelData.Width * PixelData.Height * PixelData.SamplesPerPixel];
                    Array.Copy(newPixelDataArray, PixelData.Width * PixelData.Height * PixelSize * i, frame, 0, PixelData.UncompressedFrameSize);
                    MemoryShortBuffer memoryByteBuffer = new MemoryShortBuffer(frame);
                    newPixelData.AddFrame(memoryByteBuffer);
                }
                throw new NotImplementedException("ERROR: 16bit images are not currently supported by MaskIT.");
            }

            PixelData = newPixelData;
        }

### Actual behavior
MemoryShortBuffer doesn't exist - is there a way to convert 16-bit representation to 8-bit (to output a 16-bit DICOM)?

### Steps to reproduce the behavior
Successfully read in a 16-bit DICOM, but unable to output it again as 16-bit

### fo-dicom version and OS/platform
Version 4.0.0

**Comment by mia-san** [comment]
for time being, you have to 'flatten' the ushort[] into byte[], create MemoryByteBuffer and possibly wraps it by EndianByteBuffer.Create, I'm afraid.

it might be better to have something like MemoryByteBuffer.Create(ushort[]) ?

**Comment by gofal** [comment]
mia-san wrote:
> I came across Dicom.IO.ByteConverter.ToByteBuffer(T[]).
> should I update this PR so that convenient function uses ToByteBuffer?
> if ToByteBuffer is enough, this PR could be rejected...

So using ByeConverter.ToByteBuffer solves the issue.

**Comment by mia-san** [comment]
here it is.

```
private static void Main(string[] args)
{
    ushort[] words = { 0xfedc, 0xba98, 0x7654, 0x3210 };
    var buffer = ByteConverter.ToByteBuffer(words);
    byte[] bytes = buffer.Data;
    Console.WriteLine(string.Join(' ', bytes.Select(b => b.ToString("x2"))));

    Console.ReadLine();
}
```
this will produce
`dc fe 98 ba 54 76 10 32`

still, trampoline function in MemoryByteBuffer might be convenient.
//

**Comment by FiifiB** [comment]
Thank you @mia-san. Will try that out
