### ISSUE TITLE
All currently implemented UID Generate methods cannot guarantee to generate valid DICOM UIDs

### ISSUE THREAD

**Issue by vbaderks** [fo-dicom/fo-dicom#762]
All currently implemented DicomUID.Generate methods cannot guarantee that a valid DICOM unique UID is generated. 

A DICOM UID generator should:
1) generate process wide unique IDs
2) generate system wide unique IDs (more strict then rule 1)
3) generate universal wide unique IDs (more strict then rule 2)
4) Follow the format specifications of the DICOM standard. 

Examples (based on source code of v4.0.0):

```
public static DicomUID Generate(string name) // class DicomUID
{
    if (string.IsNullOrEmpty(RootUID))
    {
        RootUID = "1.2.826.0.1.3680043.2.1343.1";
    }

    var uid = $"{RootUID}.{DateTime.UtcNow}.{DateTime.UtcNow.Ticks}";

    return new DicomUID(uid, name, DicomUidType.SOPInstance);
}
``` 
This method fails for rule 1. The resolution of Ticks is not small enough to guarantee that 2 calls quickly after each other to this method won't generate the same UID.

```
public static DicomUID Generate() // class DicomUID
{
    var generator = new DicomUIDGenerator();
    return DicomUIDGenerator.GenerateNew();
}
```
This method uses DicomUIDGenerator.GeneratorNew() and passes rule 1 but fails for rule 2 (see below)

```
public static DicomUID GenerateNew() // DicomUIDGenerator
{
    lock (_lock)
    {
        var ticks = DateTime.UtcNow.Subtract(Y2K).Ticks;
        if (ticks <= _lastTicks) ticks = _lastTicks + 1;
        _lastTicks = ticks;

        var str = ticks.ToString();
        if (str.EndsWith("0000")) str = str.Substring(0, str.Length - 4);

        var uid = new StringBuilder();
        uid.Append(InstanceRootUID.UID).Append('.').Append(str);

        return new DicomUID(uid.ToString(), "SOP Instance UID", DicomUidType.SOPInstance);
    }
}
```
This method passes rule 1, but fails rule 2. Running 2 DICOM applications that need to generate UIDs on the same system or on different computers have a high change of generating them at the same time, causing the generation of duplicate UIDs.
Note: most computers have their time synced, so UTC time is almost the same on many systems.

```
public static DicomUID GenerateDerivedFromUUID()  // DicomUIDGenerator
{            
    var guid = Guid.NewGuid().ToByteArray();
    var bigint = new System.Numerics.BigInteger(guid);
    if (bigint < 0) bigint = -bigint;
    var uid = "2.25." + bigint;

    return new DicomUID(uid, "Local UID", DicomUidType.Unknown);
}
```
This method passes 1, 2 but fails 4 and probably fails 3. DICOM requires a decimal representation
of a Universally Unique Identifier (UUID) (see PS 3.5, B.2). ToByteArray() returns the bytes of the Guid in a special order (see .NET docs and wikipedia), which needs to be transformed before it can be passed into the constructor of BigInteger (which expects the array in little endian order).
The order of the bytes is essential to keep the transformed UUID unique. Swapping them may cause conflicts with conforming UID generators.

**Recommendation:**
The GenerateDerivedFromUUID() method (when fixed) can supports almost all use cases for UID generation. The exceptional use cases (private SOP class, transfer syntax, etc) are mostly generated in a manual way. An easy solution is to only use this method in the fo-dicom library and remove all the other generator functions.

Note: an identical issue (#546) about this topic was opened in the past, but only solved a problem with rule 1.

**Comment by gofal** [comment]
Very good point. And thanks for also providing a fix with the issue description.
Would you mind to fix the method and create a pull request?

**Comment by vbaderks** [comment]
Sure, can create fix and pull request. Already cloned the repro.

**Comment by vbaderks** [comment]
I will then just update only the forwarding of DicomUID.Generate() to GenerateDerivedFromUUID and mark the other 2 "create" functions obsolete.

Do you want a new pull request or shall I extend the current one?

off topic: 
DicomUIDGenerator.RegenerateAll is a strange function. There are no unit tests for it, so its use case is unclear to me. I can understand the use case of updating the StudyUid, SeriesUid and InstanceUid for an instance, but not all "unknown" uids. As a member of DicomUIDGenerator it is also hard for end-users to discover, and it creates a dependency from DicomUIDGenerator on the class DicomDataSet. Maybe this method would be a better member of the DicomDatasetExtensions class.

**Comment by gofal** [comment]
please extend the current pull request. Thanks a lot!

**Comment by vbaderks** [comment]
done

**Comment by hkoestin** [comment]
why is there this "2.25" prefix all the time? Where is the root-UID gone?

see some parts in #862

**Comment by vbaderks** [comment]
Prefix "2.25" is required by the DICOM standard when the algorithm to generate UIDs as described in DICOM Part 5, appendix B.2 (page 107) is used.
