### ISSUE TITLE
"Unexpected tag" exception when calling DicomFile.Open

### ISSUE THREAD

**Issue by sms-ocram** [fo-dicom/fo-dicom#763]
### Expected behavior
DicomFile.Open() should return a valid DicomFile instance.

### Actual behavior
DicomFile.Open() throws a DicomFileException. The exception message is the following:

> "Unexpected tag in DICOM fragment sequence: (0000,0000)\r\n   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseFragmentSequenceTag(IByteSource source) in C:\\fo-dicom\\DICOM\\IO\\Reader\\DicomReader.cs:line 1045\r\n   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseFragmentSequence(IByteSource source) in C:\\fo-dicom\\DICOM\\IO\\Reader\\DicomReader.cs:line 1008\r\n   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseValue(IByteSource source) in C:\\fo-dicom\\DICOM\\IO\\Reader\\DicomReader.cs:line 630\r\n   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseDataset(IByteSource source) in C:\\fo-dicom\\DICOM\\IO\\Reader\\DicomReader.cs:line 225\r\n   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseItemSequenceValue(IByteSource source) in C:\\fo-dicom\\DICOM\\IO\\Reader\\DicomReader.cs:line 918\r\n   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseItemSequence(IByteSource source) in C:\\fo-dicom\\DICOM\\IO\\Reader\\DicomReader.cs:line 816\r\n   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseValue(IByteSource source) in C:\\fo-dicom\\DICOM\\IO\\Reader\\DicomReader.cs:line 610\r\n   at Dicom.IO.Reader.DicomReader.DicomReaderWorker.ParseDataset(IByteSource source) in C:\\fo-dicom\\DICOM\\IO\\Reader\\DicomReader.cs:line 225\r\n   at Dicom.IO.Reader.DicomReader.Read(IByteSource source, IDicomReaderObserver observer, Func`2 stop) in C:\\fo-dicom\\DICOM\\IO\\Reader\\DicomReader.cs:line 72\r\n   at Dicom.IO.Reader.DicomFileReader.DoParse(IByteSource source, IDicomReaderObserver fileMetasetInfoObserver, IDicomReaderObserver datasetObserver, Func`2 stop, DicomTransferSyntax& syntax, DicomFileFormat& fileFormat) in C:\\fo-dicom\\DICOM\\IO\\Reader\\DicomFileReader.cs:line 348\r\n   at Dicom.IO.Reader.DicomFileReader.Parse(IByteSource source, IDicomReaderObserver fileMetasetInfoObserver, IDicomReaderObserver datasetObserver, Func`2 stop) in C:\\fo-dicom\\DICOM\\IO\\Reader\\DicomFileReader.cs:line 168\r\n   at Dicom.IO.Reader.DicomFileReader.Read(IByteSource source, IDicomReaderObserver fileMetaInfo, IDicomReaderObserver dataset, Func`2 stop) in C:\\fo-dicom\\DICOM\\IO\\Reader\\DicomFileReader.cs:line 117\r\n   at Dicom.DicomFile.Open(String fileName, Encoding fallbackEncoding, Func`2 stop) in C:\\fo-dicom\\DICOM\\DicomFile.cs:line 212"

### Steps to reproduce the behavior

The issue happens with this file:
[1.3.12.2.1107.5.99.3.30000013012810594581200000025_us_114218.296000_1696490266.zip](https://github.com/fo-dicom/fo-dicom/files/2677538/1.3.12.2.1107.5.99.3.30000013012810594581200000025_us_114218.296000_1696490266.zip)

Unzip this file and try to open it with DicomFile.Open().

### fo-dicom version and OS/platform
fo-dicom Desktop v3.0.2
Windows 7

**Comment by mia-san** [comment]
as far as I see, the DICOM file is actually corrupted.
dcmtk also complains as following:
```
$ dcm2xml 1.3.12.2.1107.5.99.3.30000013012810594581200000025_us_114218.296000_1696490266
E: DcmSequenceOfItems: Parse error in sequence (7fe0,0010), found (0000,0000) instead of sequence delimiter (fffe,e0dd)
E: dcm2xml: error (Sequence Delimitation Item missing) reading file: 1.3.12.2.1107.5.99.3.30000013012810594581200000025_us_114218.296000_1696490266
```

**Comment by sms-ocram** [comment]
@mia-san thanks for the quick response. I'm using an internal software of my company that is able to open this file. Probably we are working around this issue somehow. I'll investigate. I believe you can close this item if you want since it seems to be not something you need to fix. Thank you again!

**Comment by mia-san** [comment]
as far as I see, the DICOM file in question has
- SOPClassUID 1.2.840.10008.5.1.4.1.1.6.1, Ultrasound Image Storage
- TransferSyntaxUID 1.2.840.10008.1.2.4.70, JPEG Lossless, Nonhierarchical, First- Order Prediction
- (0088,0200) IconImageSequence with explicit length 0x13be, containing PixelData.
- the PixelData starts at offset 0x0d74 as following
e0 7f 10 00  4f 57 00 00 ff ff ff ff
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
...
00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
interpreted as VR=OW and Undefined Length.

as you see, the PixelData is not properly encoded; no starting (FFFE,E000), no ending (FFFE,E0DD).
I've manually changed PixelData's length to 0x1000 and things seem to work fine.

one idea is to drop the sequence altogether if something went wrong in parsing the sequence; e.g. past end of sequence, improperly encoded tags, etc.
this way, the dataset might be parsed anyway in this case, but this would not work if the sequence itself has Undefined Length.
also, the 'dropped' sequence may cause trouble on rendering image etc.

**Comment by gofal** [comment]
Of course it makes only sense to be resistent to errors, if the error can be corrected clearly. For example the very first issue I solved in fo-dicom was with sequences of undefined length. the vendor did not write the last ItemDeliminationItem (FFFE,E00D) before the SequenceDeliminationItem (FFFE,E0DD). This is not dicom standard, but it is correctable, since if there are several items separated by a ItemDeliminationItem and then there is the SequenceDeliminationItem, then it is obvious that the last Item should have been ended.

Droping data, or making fo-dicom guess some data and add this data is dangerous, specially if fo-dicom reads the data without any exception or error message and so the user thinks that everything is fine. You already pointed out the follow-up-errors that might happen then.

So your detailed description (thanks!) showed, that this issue is not a correctable syntactical failure, but there is really semantically something missing. 

Well then I will close this issue.
