### ISSUE TITLE
No mono support for release 4.0.0

### ISSUE THREAD

**Issue by rkm** [fo-dicom/fo-dicom#775]
Hi all,

I'd like to use the official fo-dicom.Mono package here: https://www.nuget.org/packages/fo-dicom.Mono/ however this has not been updated to the 4.0.0 release. I can manually compile a DLL for Mono using the DICOM.Mono.sln file, however I'd prefer to use a properly supported Nuget package for easier maintainability.

I believe this was discussed in the Gitter chat some months ago, and I remember attempting to build the Nuget package myself without any result.

Thanks,
Ruairidh

**Comment by gofal** [comment]
Will close this issue, because from version 5 on fo-dicom will no longer build platform dependent assemblies, but only one netstandard2.0 assembly. mono should support netstandard2.0. If there is any issue with that, please open an new issue addressing that.
