### ISSUE TITLE
JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14) Codec

### ISSUE THREAD

**Issue by panleya** [fo-dicom/fo-dicom#781]
### Expected behavior
DICOM using this codec works

### Actual behavior
Exception processing DICOM to JPEG

### Steps to reproduce the behavior
If there is a place to download this codec, please advise.  My Google attempts have all failed.  Everything is properly compiling under x64 and other codecs work fine.

### fo-dicom version and OS/platform
v4.0.0 and 2017 c++ redistributable installed

**Comment by mia-san** [comment]
you seem to have opened #744 before for same issue.
have you checked that?

regarding to the symptom, common cause is missing Dicom.Native.dll or Dicom.Native64.dll.
if you're building your project in Any CPU, the DLLs are not copied into your 'bin' directory.
choose x86 or x64, or copy those DLLs manually(by project setting's build event)
you'll find the DLLs in your solution's packages\fo-dicom.Desktop.{version}\build\{platform}

also, nuget package's native codec seems to compiled against VC2015 runtime.

**Comment by panleya** [comment]
I build against x64, and all other dicoms process fine.  The only one that fails is the JPEG Lossless.  The DICOM.Native64.dll is there.  I'm explicitly telling it to compile as "core" (I don't even know how I would do that).  The project is a Console Application.  I do use the Nuget packages... should I not use those?  And if so, how would I switch?

**Comment by mia-san** [comment]
all the JPEG Lossless image fails?
is your project is for .netcore or .net framework?
would you mind to share minimum project that reproduce the issue?

**Comment by mia-san** [comment]
if you're building .netcore project, #725 help?
subject refers Linux, but it seems to support windows x64.

**Comment by PalminX** [comment]
I have a similar request: We are using fo-dicom in a .NET Core project, and I am wondering how to get support for JPEG Lossless into the project.

I have to admit I don't really understand #725, would it be possible to provide more information?

Ideally, a solution that would work out-of-the-box (and even more so, a nuget package) would be appreciated.

**Comment by gofal** [comment]
Efferent did a great job by making the native codecs that have been only available on windows also available on linux. So if you build .net core, the application may potentially run on windows or linux.
Read here https://github.com/fo-dicom/fo-dicom/issues/886#issuecomment-522423070 to see how simple it is to use their codec for fo-dicom.

**Comment by gofal** [comment]
I close this issue due to inactivity.
If there are any updates, or if the issue is still happening with latest version of fo-dicom and with Efferents codec, then please reopen this issue.
