### ISSUE TITLE
Get uncompressed raw image byte array from a DicomImage

### ISSUE THREAD

**Issue by sezaru** [fo-dicom/fo-dicom#782]
Hello, I need to get a raw (not compressed) byte array image from a dicom file.

To do that I was trying to use this function:
```
DicomImage image;
...
byte[] dataBytes = image.PixelData.GetFrame(n).Data;
````

That doesn't work 100% of the time since it can return compressed images (jpeg for example), and what I want is the raw data.

A workaround I did for version 3.0.2 was that:
```
        private static byte[] GetBinaryData(DicomDataset dataset, int n)
        {
            var image = new DicomImage(dataset, n);

            var pixelData = (Dicom.Imaging.Render.IPixelData)image
                .GetType()
                .GetField("_pixelData", BindingFlags.Instance | BindingFlags.NonPublic)
                .GetValue(image);

            var buffer = pixelData.GetType().GetProperty("Data").GetValue(pixelData);
            if (IsArrayOf<int>(buffer.GetType()))
            {
                return ToByteArray((int[])buffer);
            }
            else if (IsArrayOf<uint>(buffer.GetType()))
            {
                return ToByteArray((uint[])buffer);
            }
            else if (IsArrayOf<short>(buffer.GetType()))
            {
                return ToByteArray((short[])buffer);
            }
            else if (IsArrayOf<ushort>(buffer.GetType()))
            {
                return ToByteArray((ushort[])buffer);
            }
            else if (IsArrayOf<sbyte>(buffer.GetType()))
            {
                return ToByteArray((sbyte[])buffer);
            }
            else
            {
                return (byte[])buffer;
            }
        }
```

This seems to work fine, it always returns the correct raw image, but as you can see, it uses reflection to get non-public properties from fo-dicom types.

Since now we have version 4.0.0, is there a better way to achieve the same goal? If not, is there a possibility to add a new function like `RawData` so I can write something like that instead:
```
byte[] dataBytes = image.PixelData.GetFrame(n).Data;
```

**Comment by mia-san** [comment]
you mean you want 'uncompressed' pixel data, regardless the transfer syntax implies compressed or not ?

**Comment by sezaru** [comment]
Yeah, exactly, I just want the pixel data without any LUT or other transformations, and uncompressed.

Let me give some background on what I'm trying to do so it becomes more clear.

In our company we already have our own DICOM renderer and loader, but we want to remove our loader and replace it with fo-dicom.
So, in our case, we load the file with fo-dicom, get all the tags, LUTs, etc, and send it to our renderer to do the rest of the work. This means that our renderer expects a raw pixel image so it can apply all the transformation and generate the final image.

**Comment by mia-san** [comment]
hmm, what about something like this?
```
using Dicom;
using Dicom.Imaging;
using Dicom.Imaging.Codec;
using System;

namespace ConsoleApp1
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            var compressed = DicomFile.Open("jpeg-lossless.dcm");

            var uncompressed = compressed.Clone(DicomTransferSyntax.ExplicitVRLittleEndian);

            var pixel_data = DicomPixelData.Create(uncompressed.Dataset);

            var frame = pixel_data.GetFrame(0);

            var bytes = frame.Data;

            Console.ReadLine();
        }
    }
}
```

this should work on 3.0.2, too.

**Comment by sezaru** [comment]
This seems to work great. Thanks @mia-san
