### ISSUE TITLE
Remove Group Lengths Null Reference Exception

### ISSUE THREAD

**Issue by apricea4** [fo-dicom/fo-dicom#789]
This is a very intermittent problem unfortunately and cannot guarantee the steps to reproduce will reproduce it unless one uses a file that is known to cause the issue.  I am writing dicom files from image tiles.  I have successfully saved dicom files for a few months now, this issue has just recently cropped up. 
### Expected behavior
Executing Dicom.save() successfully saves a dicom file and is viewable in MicroDicom(or some other Dicom viewer)  

### Actual behavior
Exception on saving the file: `
System.NullReferenceException: Object reference not set to an instance of an object.
   at Dicom.IO.Writer.DicomDatasetExtensions.RemoveGroupLengths(DicomDataset dataset, Boolean firstLevelOnly)
`

### Steps to reproduce the behavior
Scan glass slide with Motic Scanner
Get image tiles through Motic's dll's
Create all the appropriate pieces to correctly save dicom files( dicomdataset, fill with needed tags etc)
Add tiles to dicom file as frames
Dicom.save()

### fo-dicom version and OS/platform
fo-dicom 4.0.0 Dot 
fo-dicom desktop 4.0
Net Standard 2.0 Windows 10 
Re-scanning the glass will sometimes fix the problem and running the same raw assets from the scanned glass that originally failed will always fail with the null reference exception.

**Comment by apricea4** [comment]
I apologize, I had the version wrong this is 4.0 that we are using.  I updated the original issue to reflect that and have now had it happen 3 times in a row with new scans.  Yes, since it is happening in group lengths and that is a deprecated tag we tried removing the call to RemoveGroupLengths and we tried always adding a group length tag, but it still fails somewhere down the line.
Just to make sure I understand you, are you saying try and write my own RemoveGroupLengths, call it against my failing Dataset and see what happens?
Thank you for your reply.

**Comment by mia-san** [comment]
thank you for update.

> Just to make sure I understand you, are you saying try and write my own RemoveGroupLengths, call it against my failing Dataset and see what happens?

yes.
copy the function, or inline the function into appropriate place.
the function is about 5 statements, as you see.
and run the program in question under debugger(Visual Studio or such), we'll see direct cause of the exception.
it might be useful to investigate root cause.

**Comment by apricea4** [comment]
Ok, give me a little time but I will do that.  I have already done that a week or two ago by adding the fo-dicom code directly to my project and stepping through it but can't remember exactly what we found.  I will get you back with the results in a bit.

**Comment by apricea4** [comment]
So I added the function to my code and called it against my failing Dataset.  This particular Dataset fails on the 7th dicom file.  The function does not fail when it is in my code, and if I call Dicom.save() immediately after calling my own version of RemoveGroupLengths everything works fine until it hits that 7th dicom file.  When it hits the 7th dicom file, my own RemoveGroupLengths works without a problem, but when I call save on the 7th dicom file, it fails as it always has.  
When I put in my own version of  RemoveGroupLengths I do not use it as an extension method so I do not call it with item.RemoveGroupLengths(false) instead I pass the Dataset with it.  I obviously removed the static keyword and the this keyword in the params.
Every Dataset passed in has two members {[(0020,9111), (0020,9111) SQ Frame Content Sequence]} and {[(0048,021a), (0048,021a) SQ Plane Position (Slide) Sequence]} 
with nothing null inside.
To me this makes it seem that when it is being called as an extension method I.E. item.RemoveGroupLengths() the "item" refernence is null for whatever reason on the same Dataset.  

I will add fo-dicom 4.0 code directly to my project and step through it like that.  I will come back with results from that soonish.

**Comment by apricea4** [comment]
Ok I have added the source code directly to my project and found the issue.  I was making the array of datasets too large.  I incremented the size in the wrong place and was counting null frames I was getting from an api call as valid frames.  I had the increment call one curly brace too low.  Thank you for your quick replies, help and dicom library.
