### ISSUE TITLE
Applying Color Palette LUT on 16- and 32-bit images

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#79]
*Originally posted in [Google Groups](https://groups.google.com/forum/#!topic/fo-dicom/yzgAzhpj1X8) by Mukul Lanke on September 2, 2015:*

I am trying to apply Color Palette using LUT (Lookup Tables) in my software. I also have a sample Lookup-Table file (packed inside the zip file I have    attached with this mail). This file applies the "GreenFireBlue" type of ColorPalette to the DicomImage currently being viewed. This lookup-table file has been generated by another viewer. Now, when I apply it to my DicomViewer program, it does generate an image; but when compared with the image generated from the another viewer, it shows difference. Mainly, the Blue color does not get applied at all in my program.

Below is the code which I have written to achieve the same functionality:

    string strDICOMFile =  @"D:\DicomImage.dcm";
    string strLUTFile = @"D:\GreenFireBlue.lut";

    DicomImage di = new DicomImage(strDICOMFile);
    Color32[] colorTable = ColorTable.LoadLUT(strLUTFile);
           
    OutputLUT oLUT = new OutputLUT(colorTable);
    IPixelData pixelData = PixelDataFactory.Create(di.PixelData, 0);
    ImageGraphic ig = new ImageGraphic(pixelData);
    Image image = ig.RenderImage(oLUT);
    image.Save(@"D:\GreenFireBlue2.jpg");

I want to know where I am going wrong or what I am missing.

I have also attached a zip file [here](https://groups.google.com/group/fo-dicom/attach/283e60098c1cf4/FilesForLUT.zip?part=0.1&authuser=0) with containing:
 1. LookupTable file (filename: GreenFireBlue.lut)
 2. The image which gets generated from another viewer after LUT application (filename: expected.jpg)
 3. The image which gets generated from my software using the above listed code (filename: actual.jpg).
 4. The original Dicom file to which the LUT is applied in my program and in the other viewer (filename: DicomImage.dcm)  

*Expected*
![expected](https://cloud.githubusercontent.com/assets/6515030/9677461/895e1a3a-52da-11e5-9959-1bd93b1b3000.jpg)

*Actual*
![actual](https://cloud.githubusercontent.com/assets/6515030/9677465/93cfeffc-52da-11e5-84f8-3ea1242c0d6f.jpg)

**Comment by anders9ustafsson** [comment]
The DICOM image that Mukul Lanke provided results in the `pixelData` variable being set to a `GrayscalePixelDataU16` object.

Investigation has revealed that even so, the `OutputLUT` is only applied to 8-bit values, 0-255. The return LUT value for pixel data values of 256 and above will effectively be set to LUT 255.

The correct application of the LUT table should be that it accounts for the actual range in the provided pixel data.

**Comment by anders9ustafsson** [comment]
OK, by identifying the minimum and maximum values of the pixel data (0 and 606 in this particular image), rescaling the pixel data values to be within the range 0-255 and then apply the LUT, I mage to obtain this image:

![greenfireblue2](https://cloud.githubusercontent.com/assets/6515030/9686043/24cf8f16-5322-11e5-9c3c-befcb1d85554.jpg)

The question is now, is this the (only) right way to go? For example, if you apply the min-max range LUT approach to two images with different pixel data value spans, the comparison could be misleading. At least when comparing images, it would be more relevant to use a common LUT conversion range for both images.

I would like to have your opinions here, please discuss!

**Comment by anders9ustafsson** [comment]
One more finding: in the DICOM image concerned here, window center and width are 294 and 511, respectively. When those parameters are available, it is of course natural that the LUT is applied within the ranges that the center and width dictates. If so, the same rule should be applied to 8-bit images as well for consistency, or? Please discuss!

**Comment by anders9ustafsson** [comment]
I have now investigated the issue in even more detail. The problem starts when trying to apply the "raw" color table LUT onto the image, without accounting for rescale intercept and slope, window center and width, LUT shape and inversion properties.

All this information can be obtained from the image data by calling the `GrayscaleRenderOptions.FromDataset` static method. By default, this information is transferred into a `GenericGrayscalePipeline` object which composes a `CompositeLUT` object that is used when rendering the image via `DicomImage.RenderImage`.

However, this approach is limited *Monochrome 1* and *Monochrome 2* color tables; if you want to apply a different color table, say the "green-fire-blue" table you will need to compose the composite LUT manually.

Here is a method that lets you do exactly this. It contains all the steps taken to generate a look-up table in `GenericGrayscalePipeline`, except that it applies a specified color table instead of the standard monochrome color tables when initializing the `OutputLUT` component:

    public static ILUT CreateFromDataset(DicomDataset dataset, Color32[] colorTable)
    {
      var options = GrayscaleRenderOptions.FromDataset(dataset);

      var composite = new CompositeLUT();
      OutputLUT output;

      if (options.RescaleIntercept != 0.0 || options.RescaleSlope != 1.0)
      {
        composite.Add(new ModalityLUT(options));
      }

      composite.Add(VOILUT.Create(options));
      composite.Add(
        output =
        new OutputLUT(colorTable ?? (options.Monochrome1 ? ColorTable.Monochrome1 : ColorTable.Monochrome2)));

      if (options.Invert)
      {
        composite.Add(new InvertLUT(output.MinimumOutputValue, output.MaximumOutputValue));
      }

      return new PrecalculatedLUT(composite, options.BitDepth.MinimumValue, options.BitDepth.MaximumValue);
    }

Now in the example above, instead of initializing the LUT via the `OutputLUT` constructor:

~~`OutputLUT oLUT = new OutputLUT(colorTable);`~~

call the `CreateFromDataset` method:

    var oLUT = CreateFromDataset(di.Dataset, colorTable);

and Tadaa!

![greenfireblue2](https://cloud.githubusercontent.com/assets/6515030/9714016/7e9a4ae2-5555-11e5-9b46-7fcf75c315c1.jpg)

---

I admit that *fo-dicom* is non-intuitive in this respect, and there is a definite need to make the LUT application more easily dealt with. 

This issue will be kept open, and we will consider whether to incorporate the presented helper method or something similar to facilitate a more flexible LUT application.

Everyone interested, please share your thoughts and ideas regarding this issue! Leave your comment here.

**Comment by mukullanke** [comment]
Great Anders !! Fantastic, Just Fantastic !! :+1: 

Well, I hadn't gone up-to this depth of analysis of Fellow-Oak Dicom Library and the effects of parameters - WC, WW, RescaleSlope, RescaleIntercept while applying LUT. So, right now, I think that the solution that you have provided is the best. 

I will incorporate the method that you have given above in the latest source-code of Fellow-Oak that I have (ver 1.1.0). And I will just cross-verify that whether the images produced using the above method for other LUT files (like Fire, MagentaHot, etc) match with those produced from the other Viewer. I will reply again after I verify at my end.

**Comment by mukullanke** [comment]
Hooray !! I found that all the LUT files for which I was previously getting different colors than expected - are now getting applied correctly! In fact, if we compare the images minutely, then they are showing even better detailing (or sharpness) than the expected ones!

I have inserted the images produced from other viewer and from Fellow-Oak.

Thanks a lot Anders !! :+1: 

[Expected]
![cyanhot1](https://cloud.githubusercontent.com/assets/5909083/9716920/0182c502-558c-11e5-97bc-fd619cf238b0.jpg)

[Actual]
![cyanhot2](https://cloud.githubusercontent.com/assets/5909083/9716922/0186bd42-558c-11e5-903a-6b7d17b2fd20.jpg)

[Expected]
![fire1](https://cloud.githubusercontent.com/assets/5909083/9716921/0185e700-558c-11e5-83e0-2cda4cc47b0a.jpg)

[Actual]
![fire2](https://cloud.githubusercontent.com/assets/5909083/9716923/0188da46-558c-11e5-8270-0f4c11600779.jpg)

[Expected]
![greenfireblue1](https://cloud.githubusercontent.com/assets/5909083/9716924/018b2030-558c-11e5-8713-a20a2b5f4b86.jpg)

[Actual]
![greenfireblue2](https://cloud.githubusercontent.com/assets/5909083/9716925/01a721f4-558c-11e5-91c4-d00a7884fe9c.jpg)

[Expected]
![magentahot1](https://cloud.githubusercontent.com/assets/5909083/9716926/01ac00b6-558c-11e5-86da-75298c72cbaf.jpg)

[Actual]
![magentahot2](https://cloud.githubusercontent.com/assets/5909083/9716929/01b01dfe-558c-11e5-9f58-93a5d8f812a9.jpg)

[Expected]
![redhot1](https://cloud.githubusercontent.com/assets/5909083/9716927/01ad584e-558c-11e5-9d8e-1e85cc202c93.jpg)

[Actual]
![redhot2](https://cloud.githubusercontent.com/assets/5909083/9716928/01aed980-558c-11e5-8719-db8cc1808935.jpg)

[Expected]
![spectrum1](https://cloud.githubusercontent.com/assets/5909083/9716930/01b48d12-558c-11e5-958e-6533ef3b0805.jpg)

[Actual]
![spectrum2](https://cloud.githubusercontent.com/assets/5909083/9716932/01b86dd8-558c-11e5-9754-f32b44f67904.jpg)

[Expected]
![yellow1](https://cloud.githubusercontent.com/assets/5909083/9716933/01ba3000-558c-11e5-91bc-0ef3939bf74e.jpg)

[Actual]
![yellow2](https://cloud.githubusercontent.com/assets/5909083/9716931/01b7bc30-558c-11e5-89d4-7ae4c3b4e337.jpg)

**Comment by anders9ustafsson** [comment]
That's great, Mukul, glad this solution could be of help to you!

Regards,
Anders

**Comment by IanYates** [comment]
Great job @anders9ustafsson.  Including some form of this in the library would be neat.  In the meantime I guess this is a great candidate for the wiki

**Comment by anders9ustafsson** [comment]
Thanks, @IanYates . I already have some ideas on how to incorporate this in the library, but in the meantime an addition to the wiki sounds reasonable.

**Comment by anders9ustafsson** [comment]
Wiki page added!

**Comment by sarveshJjoshi** [comment]
> Hooray !! I found that all the LUT files for which I was previously getting different colors than expected - are now getting applied correctly! In fact, if we compare the images minutely, then they are showing even better detailing (or sharpness) than the expected ones!
> 
> I have inserted the images produced from other viewer and from Fellow-Oak.
> 
> Thanks a lot Anders !! 👍
> 
> [Expected] ![cyanhot1](https://cloud.githubusercontent.com/assets/5909083/9716920/0182c502-558c-11e5-97bc-fd619cf238b0.jpg)
> 
> [Actual] ![cyanhot2](https://cloud.githubusercontent.com/assets/5909083/9716922/0186bd42-558c-11e5-903a-6b7d17b2fd20.jpg)
> 
> [Expected] ![fire1](https://cloud.githubusercontent.com/assets/5909083/9716921/0185e700-558c-11e5-83e0-2cda4cc47b0a.jpg)
> 
> [Actual] ![fire2](https://cloud.githubusercontent.com/assets/5909083/9716923/0188da46-558c-11e5-8270-0f4c11600779.jpg)
> 
> [Expected] ![greenfireblue1](https://cloud.githubusercontent.com/assets/5909083/9716924/018b2030-558c-11e5-8713-a20a2b5f4b86.jpg)
> 
> [Actual] ![greenfireblue2](https://cloud.githubusercontent.com/assets/5909083/9716925/01a721f4-558c-11e5-91c4-d00a7884fe9c.jpg)
> 
> [Expected] ![magentahot1](https://cloud.githubusercontent.com/assets/5909083/9716926/01ac00b6-558c-11e5-86da-75298c72cbaf.jpg)
> 
> [Actual] ![magentahot2](https://cloud.githubusercontent.com/assets/5909083/9716929/01b01dfe-558c-11e5-9f58-93a5d8f812a9.jpg)
> 
> [Expected] ![redhot1](https://cloud.githubusercontent.com/assets/5909083/9716927/01ad584e-558c-11e5-9d8e-1e85cc202c93.jpg)
> 
> [Actual] ![redhot2](https://cloud.githubusercontent.com/assets/5909083/9716928/01aed980-558c-11e5-8719-db8cc1808935.jpg)
> 
> [Expected] ![spectrum1](https://cloud.githubusercontent.com/assets/5909083/9716930/01b48d12-558c-11e5-958e-6533ef3b0805.jpg)
> 
> [Actual] ![spectrum2](https://cloud.githubusercontent.com/assets/5909083/9716932/01b86dd8-558c-11e5-9754-f32b44f67904.jpg)
> 
> [Expected] ![yellow1](https://cloud.githubusercontent.com/assets/5909083/9716933/01ba3000-558c-11e5-91bc-0ef3939bf74e.jpg)
> 
> [Actual] ![yellow2](https://cloud.githubusercontent.com/assets/5909083/9716931/01b7bc30-558c-11e5-89d4-7ae4c3b4e337.jpg)

Hi Mukul, 
can you provide me a source to get all those different LUT files that you used here?
I'm new to this domain and still learning basics. It would be helpful if you provide it.
