### ISSUE TITLE
PrintSCU  no working

### ISSUE THREAD

**Issue by xiongw1987** [fo-dicom/fo-dicom#790]
i use sample print scu to workerstation printer  but it can`t  

![e4pml3 chu 251xupa5q3bn](https://user-images.githubusercontent.com/20449819/51734280-08cce980-20bf-11e9-87ef-38b3b85accae.jpg)

**Comment by mia-san** [comment]
seems like SCP dislikes all the presentation context except last one and eventually aborting association.
does other print SCU works with same configuration?
what the print SCP says?

**Comment by PantelisGeorgiadis** [comment]
Please check this thread: https://github.com/fo-dicom/fo-dicom/issues/667

**Comment by ddbxyrj** [comment]
I am workingo this 2 day already. This is base on dicom greyscale sop class include 4 sop classes which fo dicom scu send 3 of them. Some print reject 4 sop classes in asscison stage, but will accpet n-creat etc on 4 sop classes. 
I wonder which is most elegent way use one acception of sop class to trige next sop classes.
I found if you add rq to dicomclient then when asscison will auto add, and when the asscisno accpeted, the n-creat... will be sent in stream. The order of associations will decide the process, Am I right?


> Please check this thread: #667

this answer will slove problem in 2.0 I thought

**Comment by gofal** [comment]
I created a pull request #907 from branch GH-667. Please give this code a try.

**Comment by gofal** [comment]
Did you have a chance to check with latest version of fo-dicom with the pull request merged?
Any other updates on this issue with latest version?
