### ISSUE TITLE
JsonDicomConverter does not correctly handle BulkDataURI

### ISSUE THREAD

**Issue by edespong** [fo-dicom/fo-dicom#796]
From [WADO-RS - RetrieveMetadata](http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_6.5.6.html
)

> The study, series, or instance metadata includes all attributes; however, a RESTful Service is permitted to replace the Value Field of an attribute with a BulkDataURI for attributes with Value Representations (VR) of DS, FL, FD, IS, LT, OB, OD, OF, OL, OW, SL, SS, ST, UC, UL, UN, US, and UT.

### Expected behavior
Using a JSON:
```
{
  "00181065": {
    "vr": "DS",
    "BulkDataURI": "http://edespong/wado/bulkdata/TlNiQw14Qm58CUNyUER3EcO"
  }
}
```

`var header = JsonConvert.DeserializeObject<DicomDataset>(json, new JsonDicomConverter());`

Should work?

### Actual behavior
Exception:
```
System.InvalidCastException: 'Unable to cast object of type 'Dicom.IO.Buffer.BulkDataUriByteBuffer' to type 'System.String[]'.'
```

### fo-dicom version and OS/platform
Dicom.Json 4.0.0
Dicom.Core 4.0.0

**Comment by mia-san** [comment]
JsonDicomConverter considers element of VR=DS to be string-type element.
BulkDataURI is recognized and BulkDataUriByteBuffer is created properly for string-type element.
however, JsonDicomConverter tries to cast the buffer to string[] blindly, just like in case of Value property, which causes InvalidCastException as reported.

also, BulkDataURI is NOT recognized for numeric-type element, end up to JsonReaderException.
