### ISSUE TITLE
How to change FileMetaInfo while DicomFile Save

### ISSUE THREAD

**Issue by chunhuxiao** [fo-dicom/fo-dicom#798]
### Expected behavior
I hope to update ImplementationVersionName and SourceApplicationEntityTitle. 

### Actual behavior
**But the FileMateInfo kept the same as below:**
0002,0012,Implementation Class UID=1.3.6.1.4.1.30071.8.
0002,0013,Implementation Version Name=fo-dicom 4.0.0
0002,0016,Source App Entity Title=My hostname

### Steps to reproduce the behavior
ndcmFile.FileMetaInfo.AddOrUpdate(Dicom.DicomTag.ImplementationVersionName, "TEST");
ndcmFile.FileMetaInfo.AddOrUpdate(Dicom.DicomTag.SourceApplicationEntityTitle, "TEST");

### fo-dicom version and OS/platform
fo-dicom 4.0.0
Win7 Pro

**Comment by mia-san** [comment]
if you're creating DicomFile from DicomDataset on the fly, DicomFile will always create new DicomFileMetaInformation from DicomDataset at beginning of Save() by calling PreprocessFileMetaInformation().
that's rather unfortunate that good old AddOrUpdate does not work in this case.

you may want to derive new class from DicomFile and override OnSave() to modify FileMetaInfo's contents.
OnSave is supposed to be 'Method to call before performing the actual saving', as its comment states.
please see https://gist.github.com/mia-san/130dabe809cb775b8cc1c7d00cfb7347

probably, it would be nice that DicomFile overrides some crucial informations only from dataset (e.g. MediaStorageSOPClassUID, MediaStorageSOPInstanceUID) with keeping other attributes in FileMetaInfo as is.

**Comment by chunhuxiao** [comment]
Thanks a lot for your support.
I will try the solution about OnSave your suggested.
But i can't reach to the link https://gist.github.com/mia-san/130dabe809cb775b8cc1c7d00cfb7347
Could you kindly paste the example or the information from the link here?
Thanks again!

**Comment by mia-san** [comment]
> But i can't reach to the link https://gist.github.com/mia-san/130dabe809cb775b8cc1c7d00cfb7347

hmm, I should have created a public gist.
anyway here we go.

```
using Dicom;
using System;

namespace ConsoleApp1
{
    internal class Program
    {
        public class MyDicomFile : DicomFile
        {
            public MyDicomFile(DicomDataset dataset) : base(dataset)
            {
            }

            protected override void OnSave()
            {
                base.OnSave();

                this.FileMetaInfo.AddOrUpdate(DicomTag.ImplementationVersionName, "TEST");
                this.FileMetaInfo.AddOrUpdate(DicomTag.SourceApplicationEntityTitle, "TEST");
            }
        };

        public static void Main(string[] args)
        {
            var dataset = new DicomDataset(
                new DicomUniqueIdentifier(DicomTag.StudyInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID()),
                new DicomUniqueIdentifier(DicomTag.SeriesInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID()),
                new DicomUniqueIdentifier(DicomTag.SOPClassUID, DicomUID.SecondaryCaptureImageStorage),
                new DicomUniqueIdentifier(DicomTag.SOPInstanceUID, DicomUIDGenerator.GenerateDerivedFromUUID())
            );

            var file = new MyDicomFile(dataset);

            file.Save("dicomfile.dcm");

            Console.ReadLine();
        }
    }
}
```

**Comment by chunhuxiao** [comment]
Thanks a lot~
Unfortunately, your solution works but the result is not right.
![image](https://user-images.githubusercontent.com/9360234/53088869-f4f19780-3545-11e9-9a89-3411d85cf451.png)
 The value should be 'TEST', but it's '1414743380' now.

On the other hand, i hope to send the dicom file to SCP, and how to update the values of ImplementationVersionName and SourceApplicationEntityTitle, just like doing save?

Thanks and have a nice day~

**Comment by mia-san** [comment]
> Unfortunately, your solution works but the result is not right.
> ![image](https://user-images.githubusercontent.com/9360234/53089055-71847600-3546-11e9-9ac5-32f0a24b2ee1.png)
> The value should be 'TEST', but it's '1414743380' now.

that's strange.
what viewer are you using?
the program should produce attached file as result, which should have 'TEST' in those elements.
[dicomfile.zip](https://github.com/fo-dicom/fo-dicom/files/2884518/dicomfile.zip)

dcmdump(from dcmtk) also agrees as following:
```
$ dcmdump dicomfile.dcm 

# Dicom-File-Format

# Dicom-Meta-Information-Header
# Used TransferSyntax: Little Endian Explicit
(0002,0000) UL 180                                      #   4, 1 FileMetaInformationGroupLength
(0002,0001) OB 00\01                                    #   2, 1 FileMetaInformationVersion
(0002,0002) UI =SecondaryCaptureImageStorage            #  26, 1 MediaStorageSOPClassUID
(0002,0003) UI [2.25.122264780640022234784569372598179874218] #  44, 1 MediaStorageSOPInstanceUID
(0002,0010) UI =LittleEndianExplicit                    #  20, 1 TransferSyntaxUID
(0002,0012) UI [1.3.6.1.4.1.30071.8]                    #  20, 1 ImplementationClassUID
(0002,0013) SH [TEST]                                   #   4, 1 ImplementationVersionName
(0002,0016) AE [TEST]                                   #   4, 1 SourceApplicationEntityTitle

# Dicom-Data-Set
# Used TransferSyntax: Little Endian Explicit
(0008,0016) UI =SecondaryCaptureImageStorage            #  26, 1 SOPClassUID
(0008,0018) UI [2.25.122264780640022234784569372598179874218] #  44, 1 SOPInstanceUID
(0020,000d) UI [2.25.47777752671308800898879342679473650560] #  44, 1 StudyInstanceUID
(0020,000e) UI [2.25.168226204347427951342094815497069488058] #  44, 1 SeriesInstanceUID
```

> On the other hand, i hope to send the dicom file to SCP, and how to update the values of ImplementationVersionName and SourceApplicationEntityTitle, just like doing save?

FileMetaHeader should not be transmitted via C-STORE.
C-STORE should send *dataset* only.
FileMetaHeader will be written by C-STORE SCP on saving received dataset onto disk or such.
see DICOM PS 3.7 9.1.1.1.8 Data Set

**Comment by mia-san** [comment]
> Unfortunately, your solution works but the result is not right.

I think I know where 1414743380 comes from.

it is 0x54534554 in hex, which can be read as 'TSET' in ASCII.
it's 'TEST' in little endian I suppose ;)
//

**Comment by chunhuxiao** [comment]
Hi mia-san,
Many thanks for your prompt support.

I read the dicom file in ezdicom, and the value is '1414743380' in this tool. Yes , the 'TEST' is in little endian. :+1: 

The additional question still about CStore SCU, if i implemented CStore SCP based on fo-dicom, File meta info is created in SCP for DicomFile, so i also have to override 'OnSave' if i hope to update the ImplementationVersionName in SCP, is it right?

**Comment by mia-san** [comment]
> I read the dicom file in ezdicom, and the value is '1414743380' in this tool.

you mean https://sourceforge.net/projects/ezdicom/ ?
I've tried the program and I found it DOES show 'TEST' as 1414743380 regardless the VR, as you say.
probably it has no idea how those tags should be displayed, as the program seems to be unmaintained for long time.

> The additional question still about CStore SCU, if i implemented CStore SCP based on fo-dicom, File meta info is created in SCP for DicomFile, so i also have to override 'OnSave' if i hope to update the ImplementationVersionName in SCP, is it right?

yes, you need 'custom' DicomFile class on SCP side in that case.

**Comment by chunhuxiao** [comment]
Thank you for your strong support and clarification, I really appreciate it.
No further questions about the topic. :+1: :100:
