### ISSUE TITLE
Move logging implementation into separate assembly

### ISSUE THREAD

**Issue by IanYates** [fo-dicom/fo-dicom#8]
The Logger abstract used throughout the codebase is great.  However it would be nice to move the NLog implementation of Logger into its own assembly.  Personally I've switched over to Serilog and fo-DICOM is the only reason I still have NLog referenced in my projects.

So... 

I propose we leave the console logger in place as-is.

Then a new assembly is created that has its dependency on NLog.  It can register an extension method on the LogManager along the lines of `.UseNLog()`.

We'd also create other assemblies (Serilog, common logging? Log4Net?) that provide concrete LogManager implementations.

Happy to hear the thoughts of others on this

**Comment by anders9ustafsson** [comment]
This sounds like a very good idea, it would be great if the *DICOM* assembly could get rid of the *NLog* dependency.

In my view the *NLog* dependent assembly should **only** contain the `NLogManager` class and potentially an extension method for easy logger registration. Is this what you are suggesting too, @IanYates ?

**Comment by IanYates** [comment]
Yes.  You've just said it much more concisely than I :)

I'd be happy to get a start on this in a few days.  Since we're not stressing too much about NuGet at the moment we can worry about the NuGet dependencies later (I'll have to read up on how to make the NuGet packages)

**Comment by jaime-olivares** [comment]
Regarding NLog, that's a heinous dependency, specially if you already have your own logging mechanism. In best case you can build a "connector for NLog" derived from your own ILog interface, so it can be decoupled or replaced with ease.

**Comment by IanYates** [comment]
@jaime-olivares - that's the plan.

Most projects, to be friendly for devs, tend to have a logging abstraction and then ready-made connectors for NLog, Serilog, Log4Net, Common Logging, etc.  Everyone using fo-DICOM already has exposure to NLog so I'll make that connector but, like you, I already have a separate logging mechanism (Serilog) so I'll make that adapter too.  I'm hoping to raise a PR over the weekend.

**Comment by hdesouky** [comment]
I like the concept of EntLib logger where logging source and logging listeners are separated.
I suggested to implement a logging abstraction interfaces (for both logger source and listener).
Log Manager will enable devs to add/remove listeners where logging output will be directed.

Initially fo-dicom can provide an example and default log listener through the Console or the default Trace.

Through this, each dev will have the freedom to implement the log listener interface to wire it to his own logging library.

What do you think?

**Comment by anders9ustafsson** [comment]
@hdesouky If I am not mistaken, the abstraction is already in place, and the `Console` default logger as well. We just need to move the `NLogManager` out of the *DICOM* assembly, I think.

**Comment by IanYates** [comment]
Yep, the abstraction is already there.  This is my little weekend project :)
@hdesouky - are you more thinking along the lines of being able to attach different loggers (probably with different logging levels/outputs) to different outputs of fo-DICOM?  I'm sure that could be accommodated if it was desired in the next PR.

**Comment by anders9ustafsson** [comment]
Resolved via PR #19.

**Comment by anders9ustafsson** [comment]
I'll re-open this issue to allow for further minor fixes, as discussed in #19 and #29.
