### ISSUE TITLE
Investigate GitLink

### ISSUE THREAD

**Issue by IanYates** [fo-dicom/fo-dicom#80]
I came across this today: https://github.com/GitTools/GitLink  - it allows end users of the library to step through the fo-dicom source when debugging without the need for us to upload symbols anywhere.

It seems fairly straightforward to integrate although I haven't had a good play with it yet.

Opinions, thoughts, etc - express them here :)

**Comment by anders9ustafsson** [comment]
Interesting! @IanYates If you have the opportunity, do you think you could try this out on your fork to be able to give a more detailed review?

**Comment by IanYates** [comment]
For my reference when I work on this in a week or so: https://oren.codes/2015/09/23/enabling-source-code-debugging-for-your-nuget-packages-with-gitlink/

**Comment by anders9ustafsson** [comment]
@IanYates Do you have any more input on this tool?

**Comment by IanYates** [comment]
I was just reading through the gitlink stuff again the other day and began looking at what xunit did to make it work.  I don't have any more input at the moment.  I'll close until I get a proper chance to implement it to keep the issue tracker tidy.
