### ISSUE TITLE
Redesign DicomImage to Work with Multi-threading

### ISSUE THREAD

**Issue by CDarbonne** [fo-dicom/fo-dicom#806]
> The idea of DicomImage is to keep the raw pixels in memory and render just what you need as Bitmap/Bitmapsource. As a radiologist you do 2 kind of things:
> * scrolling: you change the current index and draw one frame after the other
> * windowzing/zooming/... then you see a interesting image and then you do windowing, zooming, panning etc. And there you have to render the same frame again and again with different parameters. This second case is what the _pixel is for. Here you can save lot of time if you don't have to extract the frame from the raw pixels again and again.
> 
> Of course this approach is not fine in terms of multithreading. If redesigning DicomImage then maybe we should create a DicomFrame class that holds the _pixels and some other parameters like PatientPosition or similar and the DicomImage holds a list of DicomFrames. They could be lazy loaded meaning instaniated on first access and then cached in the list? This could be done threadsafe easily, but this also means that you need double memory.

_Originally posted by @gofal in https://github.com/fo-dicom/fo-dicom/issues/805#issuecomment-471039485_

It would be a very useful enhancement to redesign DicomImage according to the specs gofal suggested in the above issue. Tasks such as windowing and scrolling require quick and continuous rendering and on some machines, the sequential rendering requirement can cause slow or choppy visuals.

**Comment by hashtafak** [comment]
Is there any example for render multi-frame dicom with multi thread support? I'm new in c#

**Comment by gofal** [comment]
There is a proposal, where the whole rendering was redesigned. Now the DicomImage does not hold private variables any more, only some cached data (pixeldata, renderingpipeline) in threadsafe dictionaries.
So the Render-method is now threadsafe.
