### ISSUE TITLE
Affected SOP Class in C-FIND requests is limited to subset of SOPClasses

### ISSUE THREAD

**Issue by MikaelBertze** [fo-dicom/fo-dicom#808]
### Expected behavior
When a C-FIND request is created the AffectedSOPClass should be possible to set to any SOP Class UID.

### Actual behavior
The constructor validates that the SOP class is set to any of:
 - DicomUID.ModalityWorklistInformationModelFIND
 - DicomUID.UnifiedProcedureStepPullSOPClass
 - DicomUID.UnifiedProcedureStepWatchSOPClass

Any other SOP class will throw a DicomNetworkException.

The allowed SOP Classes does not include e.g. UPS Pull Trial (RETIRED), which is commonly used in the original, deprecated, version of IHE-RO TDW. Also, this makes private SOP Classes impossible to use as Affected SOP Class in C-FIND queries (e.g. queries not related to any series or study.)

### fo-dicom version and OS/platform
fo-dicom: 4.0.0
OS: Windows 10 x64

**Comment by mia-san** [comment]
if this is the case, another constructor should also be consistent checking SOPClassUID.
specifically
https://github.com/fo-dicom/fo-dicom/blob/36926568a88cadb73af3e9ad083d553cdd137a7a/DICOM/Network/DicomCFindRequest.cs#L60

**Comment by MikaelBertze** [comment]
Yes, I think that constructor should be changed too. The constructor that you refer to does not exist in the development branch though. I made the change on the development branch.
