### ISSUE TITLE
The Printed Image Not Align

### ISSUE THREAD

**Issue by yeqilve** [fo-dicom/fo-dicom#815]
### Actual behavior
![dicom issue](https://user-images.githubusercontent.com/27669096/54729316-d8d12c80-4bbd-11e9-918a-b0f8e46d2045.png)

### Steps to reproduce the behavior
the FilmSize is 14INX17IN  and i use resolution 300 to resize the Image (4200x5100),  the Pixel data is added by AddOrUpdatePixelData Method as following 
            var dataset = new DicomDataset();
            dataset.Add<ushort>(DicomTag.Columns, (ushort)bitmap.Width)
                .Add<ushort>(DicomTag.Rows, (ushort)bitmap.Height)
                .Add<ushort>(DicomTag.BitsAllocated, 8)
                .Add<ushort>(DicomTag.BitsStored, 8)
                .Add<ushort>(DicomTag.HighBit, 7)
                .Add(DicomTag.PixelRepresentation, (ushort)PixelRepresentation.Unsigned)
                .Add(DicomTag.PixelAspectRatio, "1\\1")
                // .Add(DicomTag.PlanarConfiguration, (ushort)PlanarConfiguration.Interleaved)
                .Add<ushort>(DicomTag.SamplesPerPixel, 1)
                //.Add(DicomTag.RequestedDecimateCropBehavior, "DECIMATE")
                //.Add(DicomTag.Polarity, "NORMAL")
                .Add(DicomTag.PhotometricInterpretation, PhotometricInterpretation.Monochrome2.Value);

            var pixels = GetGreyBytes(bitmap);
            var buffer = new Dicom.IO.Buffer.MemoryByteBuffer(pixels.Data);
            dataset.AddOrUpdatePixelData(DicomVR.OW, buffer);

### fo-dicom version and OS/platform
fo- dicom 3.1 windows server2012

**Comment by yeqilve** [comment]
it works normal in FUJI printer, and the issue comes from KONICA

**Comment by yeqilve** [comment]
![image](https://user-images.githubusercontent.com/27669096/54863697-cce49680-4d86-11e9-83ff-2a8b582e44a9.png)
there was a 00 byte data in NSet request fragment which should not exist.. How Can  I FIX IT
![image](https://user-images.githubusercontent.com/27669096/54863724-0ddcab00-4d87-11e9-8b96-8b11ca7c877f.png)

**Comment by gofal** [comment]
Which dicom tag contains this extry 0 byte data? Is it within the pixel data (I assume because of the may equal bytes), so how does your method ```GetGreyBytes(..)``` look like, that create this pixel data?

**Comment by yeqilve** [comment]
> Which dicom tag contains this extry 0 byte data? Is it within the pixel data (I assume because of the may equal bytes), so how does your method `GetGreyBytes(..)` look like, that create this pixel data?

it was caused by return association max pdu length is  65535 and the  PDV  size was Resized 
![image](https://user-images.githubusercontent.com/27669096/54998998-59eb5200-500a-11e9-8ebc-8c6884472bb0.png)

**Comment by gofal** [comment]
See here: http://dicom.nema.org/medical/dicom/current/output/chtml/part08/chapter_E.html
This pice of code was introduced with commit https://github.com/fo-dicom/fo-dicom/commit/2100cbe0243c20706596808229e155dd050aa65d because sending a odd length violates DICOM standard.
So you should ask someone managing the printer to change the pax pdu length to a even length.

**Comment by yeqilve** [comment]
shall I change the received pdu length to an even value to improve the compatibility and consist with this pice of code
