### ISSUE TITLE
DicomImage.RenderImage producing black images from monochrome pixeldata

### ISSUE THREAD

**Issue by cjcaldwell** [fo-dicom/fo-dicom#816]
### Expected behavior
`new DicomImage(dataset).RenderImage().AsSharedBitmap.Save(filename)` on a dataset should provide an image file that looks the same as when the dataset is opened in any normal viewer.

### Actual behavior
Created image file has correct dimensions but is completely black if the received image is 8-bit greyscale. Similar images with more colour channels images are saving normally.

### Steps to reproduce the behavior
Minimal demo project including a sample file is included in [monoSample.zip](https://github.com/fo-dicom/fo-dicom/files/2990727/monoSample.zip)

The build process will copy sample.dcm to the output directory. Running the application will create output_0.bmp (or more output_*.bmp files if it's multi-frame) in the same location. View that image in any image viewer.

### fo-dicom version and OS/platform
Attached example project is using fo-dicom 4.0.1 on .NET Framework 4.72 on Windows, but the main project I'm seeing this in is fo-dicom 4.0.0 on .NET Core 2.2 in Docker/Linux.

**Comment by cjcaldwell** [comment]
When I step through in the debugger and look at the pixeldata's byte array, I see the expected set of black (zero and near-zero) and white (255, or at least >250) values. The RenderImage() result's Pixels.Data, however, has 0xFF000000 at every position. How SHOULD single-byte greyscale pixel values be converted to int32 (presumably RGBA) values? Is there something weird in my sample dataset that's causing every brightness value to be mapped to black?

**Comment by mia-san** [comment]
thank you for sharing sample program and data.
confirmed that the program produces 'black' image, where as other viewers renders 'proper' image.

btw, the sample image's (0028,1051) WindowWidth is 1.
changing the value to 255 seems to render the image properly.

probably fo-dicom does not handles case of WindowWidth == 1 correctly.

something to do with
> When Window Width (0028,1051) is equal to 1, they specify a threshold below which input values will be displayed as the minimum output value.

in PS 3.3 C.11.2.1.2.1 Default LINEAR Function ?

**Comment by cjcaldwell** [comment]
When I step through in the debugger and look at the pixeldata's byte array, I see the expected set of black (zero and near-zero) and white (255, or at least >250) values. The RenderImage() result's Pixels.Data, however, has 0xFF000000 at every position. How _should_ single-byte greyscale pixel values be converted to int32 (presumably RGBA) values?

**Comment by cjcaldwell** [comment]
Looking at VOILUT.cs, I see that VOILinearLut's [](int) operator returns `(int)Math.Round((((value - WindowCenterMin05) / WindowWidthMin1) + 0.5) * 255.0);`, but the value of `WindowWidthMin1` is WindowWidth-1, which means it performs a division by 0 when the WindowWidth tag is equal to 1. While a /0 results in the "inf" magic value for a double, int has no way to represent infinity so it seems to just give 0. This will mean every greyscale luma value ends up as whatever's in Colors[0].

For now my client code can work around this with
```
if (dicomImage.WindowWidth<2){
   dicomImage.WindowWidth=2;
}
//render here
```

And I guess a PR with some special handling for WindowWidth=1 should probably be created in the near-ish future.

**Comment by PalminX** [comment]
My guess is that this is a bug, not an enhancement:

The standard says in [C.11.2 VOI LUT Module](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.11.2.html#sect_C.11.2.1.2.1)

>These Attributes are applied according to the following pseudo-code, where x is the input value, y is an output value with a range from ymin to ymax, c is Window Center (0028,1050) and w is Window Width (0028,1051):
>    ```
>    if (x <= c - 0.5 - (w-1) /2), then y = ymin
>    else if (x > c - 0.5 + (w-1) /2), then y = ymax
>    else y = ((x - (c - 0.5)) / (w-1) + 0.5) * (ymax- ymin) + ymin

The code in VOILUT.cs is this: 
https://github.com/fo-dicom/fo-dicom/blob/a77e07552f840aafbb74ac3bf4c4c7370ea7778d/DICOM/Imaging/LUT/VOILUT.cs#L206

which handles only the last case. Lines 200 - 203 contain some commented-out code which is supposed to handle the first two cases.

Changing the code to the following (untested) would fix issue #816 and be make it conform to the standard:
```
if (value <= WindowCenterMin05 - WindowWidthMin1 / 2)
{
  return 0;
}
else if (value > WindowCenterMin05 + WindowWidthMin1 / 2)
{
  return 255.0
}
else
{
  return (int)Math.Round((((value - WindowCenterMin05) / WindowWidthMin1) + 0.5) * 255.0);
}
```

**Comment by PalminX** [comment]
I don't see why negative WindowWidth values should be allowed, the standard clearly says
> Window Width (0028,1051) shall always be greater than or equal to 1.

**Comment by gofal** [comment]
Totally agree: when saving a dicomimage as DicomDataset the WindowWidth must always be greater or equal than 1 and inverting can be done by setting  (0028,0004) PhotometricInterpretation to either Monochrome1 or Monochrome2.
But a negative width is very common to be used while a medical is interactively windowing. 
The fix in the commit above, by commenting the code, was really bad coding.
The code that you have provided will fix this bug AND it will still allow the userinterface to do inverting by setting windowwith to a negative number, so it will be the perfect solution.

**Comment by gofal** [comment]
No, wait:

Just opened the code and took a look at it. I then thought that the caluculation of `WindowCenterMin05 +- WindowWidthMin1 / 2` has not to be done everytime and therefore should be cached, etc and finally I came to the exact same solution as it was before the checks were commented out.

So the solution is to remove the comments again. And windowing with negative width will not work, as I thought. But Standard is prior to nice enhancement, so I will revert the commit above and remove the comments. Then it will be fixed.

**Comment by PalminX** [comment]
Ah, I didn't realize that WindowStart and WindowEnd  is exactly what needs to be used in the checks ;-)

**Comment by PalminX** [comment]
One thing that is still not consistent is that the first two checks use `MinimumOutputValue`/`MaximumOutputValue`, whereas the calculation (implicitely) uses `0` and `255.0` directly

Right now, this doesn't make a difference, but is not nice anyway.

So to be consistent, the line really should be 
` return (int)Math.Round((((value - WindowCenterMin05) / WindowWidthMin1) + 0.5) * (MaximumOutputValue - MinimumOutputValue) + MinimumOutputValue);`
