### ISSUE TITLE
WADO return http error 403.14 

### ISSUE THREAD

**Issue by orionkubilay** [fo-dicom/fo-dicom#820]
I am testing Wado. I ve get http error 403.14 when brows "http://localhost/WADO/?requestType=WADO&studyUID=a&seriesUID=b&objectUID=c&contentType=image/jpeg"Any idea?

I ve tested WADO as is. I ve only update some nuget modules version numbers.

**Comment by gofal** [comment]
Which code are you using? fo-dicom does not contain a wado-server. Http error is standardized. 403.14 means Directory listing denied. This seems like the webserver has to access to file system. So some webserver configuration issue rather than software issue in fo-dicom.

**Comment by orionkubilay** [comment]
I

> Which code are you using? fo-dicom does not contain a wado-server. Http error is standardized. 403.14 means Directory listing denied. This seems like the webserver has to access to file system. So some webserver configuration issue rather than software issue in fo-dicom.

I ve use https://github.com/fo-dicom/fo-dicom-samples

**Comment by gofal** [comment]
I see. That is only a sample, a "how to start". The sample application always returns the same file: 
https://github.com/fo-dicom/fo-dicom-samples/blob/01cdc96b1bdb3dd5468a8379e4b3228b26173c8e/Desktop/Wado/Models/TestDicomImageFinderService.cs#L9

So you surely have implemented your own DicomImageFinderService to search a database or a file system.

As already mentioned in my previous comment, the http messages shows some access rights problem. Be sure that your application has the rights to access the desired directory or that the directory exists.

**Comment by orionkubilay** [comment]
> I see. That is only a sample, a "how to start". The sample application always returns the same file:
> https://github.com/fo-dicom/fo-dicom-samples/blob/01cdc96b1bdb3dd5468a8379e4b3228b26173c8e/Desktop/Wado/Models/TestDicomImageFinderService.cs#L9
> So you surely have implemented your own DicomImageFinderService to search a database or a file system.
> As already mentioned in my previous comment, the http messages shows some access rights problem. Be sure that your application has the rights to access the desired directory or that the directory exists.

Organizing Test<dicomImageFinderervice.cs is easy… But that sample say if you did not write Finder method it comes with test image.
I cant get test image.

**Comment by gofal** [comment]
This sample is a web application WebApi, you have to build it in visual studio and deploy to a IIS on windows. 
It has no views, so you dont have a default page. This is because WADO defines a interface for web services, not for html pages. You can build your own html view around any WADO-service.

**Comment by orionkubilay** [comment]
Image proccesing at wado is differen job. I am not asking that. But if you have a wado server support JPEG image and if you browse looklike "http://localhost/WADO/?requestType=WADO&studyUID=a&seriesUID=b&objectUID=c&contentType=image/jpeg" page, it return JPEG image.

**Comment by orionkubilay** [comment]
I ve surely build and deploy it IIS. :)

**Comment by gofal** [comment]
I would recommend to add error handling in server code. e.g. add try-catch and Logging within Controllers/Wado.cs
Since the sample works fine on my machine, the issue mut be something machine specific.

**Comment by gofal** [comment]
have you managed meanwhile to add logging to your application to get more information where the error is happening?

**Comment by gofal** [comment]
close this due to inactivity.

There is a supported WADO-application, that uses fo-dicom behind the scenes. Take a look at
https://github.com/DICOMcloud/DICOMcloud
