### ISSUE TITLE
DicomFileReader.ReadAsync returns incorrect representation of Dataset

### ISSUE THREAD

**Issue by PalminX** [fo-dicom/fo-dicom#823]
We are reading DICOM data from a WADO-RS server and parse the multipart stream using ```DicomFileReader.ReadAsync()```

We have the issue that DICOM files with (0002,0010) TransferSyntaxUID == ```RLE Lossless``` in the meta-header return a DicomFile.Dataset with InternalTransferSyntax set to ```Explicit VR Little Endian``` instead of ```RLE Lossless```

### Expected behavior
After reading a DICOM file with a (0002,0010) TransferSyntaxUID == ```RLE Lossless``` from a stream using
```
            var result = await reader.ReadAsync(new StreamByteSource(dicomStream),
                new DicomDatasetReaderObserver(df.FileMetaInfo),
                new DicomDatasetReaderObserver(df.Dataset)
```
the returned ```df.Dataset``` should have the correct InternalTransferSyntax, so that it can later be used to render the image correctly.

### Actual behavior
```df.Dataset``` has the InternalTransferSyntax still set to ```Explicit VR Little Endian```

### Steps to reproduce the behavior
See above.

I noticed that DicomFile.OpenAsync does some additional processing after reading with ReadAsync:
https://github.com/fo-dicom/fo-dicom/blob/b23d326467a0f849402f260e3cddf70cdc671a64/DICOM/DicomFile.cs#L442

I have confirmed that this correctly processes the file so that it can be rendered later. 

### fo-dicom version and OS/platform
4.0.1 / Windows 10 .NET Core

**Comment by mia-san** [comment]
just curious, are you using DicomFileReader directly?
DicomFile.OpenAsync doesn't work?
https://github.com/fo-dicom/fo-dicom/blob/b23d326467a0f849402f260e3cddf70cdc671a64/DICOM/DicomFile.cs#L397

**Comment by PalminX** [comment]
When writing this, I realized that this might be the way to go...

Yes, right now, we are using DicomFileReader directly. 

Still, I somehow think that DicomFileReader.readAsync() is returning in incorrect representation of the Dataset, don't you think?

**Comment by mia-san** [comment]
it looks to me that DicomFileReader is supposed to be helper class for DicomFile regarding its namespace, not for application use.
just guessing, I might be wrong though.

**Comment by PalminX** [comment]
I can confirm that using DicomFile.OpenAsync works as expected...

Even if DicomFileReader is only supposed to be a helper class, it returns a Dataset object which is inconsistent, I think this should be handled.

**Comment by gofal** [comment]
Yes, I agree. DicomFile.OpenAsync uses DicomFileReader and then does some internal corrections. I suppose DicomFilereader should not be public, but internal.

**Comment by PalminX** [comment]
That sounds like a possible approach, having it public in this way can lead to the problems that we have encountered.

**Comment by PalminX** [comment]
I have updated the title of the issue, since I still think that it is a bug that DicomFileReader.ReadAsync returns a Dataset which is invalid in itself. DicomFile.OpenAsync works around this bug by doing "some internal correction" as @gofal has pointed out, but this should not be necessary.

Alternatively (but not preferred), it should be made clear that DicomFileReader should not be used publicly.
