### ISSUE TITLE
About Unsupported JPEG data precision 12

### ISSUE THREAD

**Issue by ykwmz** [fo-dicom/fo-dicom#826]
Got "Unsupported JPEG data precision 12" Exception from BitMiracle.LibJpeg library when call RenderImage. After checked BitMiracle.LibJpeg's source code, that seems still do NOT support that yet. But for Medical Image, it has many this kind of DICOM files, do you have any plan or idea to supports that ?

**Comment by gofal** [comment]
fo-dicom will in future use the great codec of Efferent by default:
https://github.com/Efferent-Health/fo-dicom.Codecs
They are actively enhancing codec support. Please check with their codec and open issues there.
