### ISSUE TITLE
Trouble rendering single image from dataset

### ISSUE THREAD

**Issue by ELPona** [fo-dicom/fo-dicom#837]
### Expected behavior
```
var imageFile = await DicomFile.OpenAsync(singleDicomImageFile);
var a = new DicomImage(imageFile.Dataset);
a.RenderImage(); //provides a working IImage
```

### Actual behavior
I get an AggregateException, with its inner being "Index was outside the bounds of the array".

StackTrace:
en System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
en System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
en System.Threading.Tasks.Task.Wait()
en System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
en System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
en Dicom.Imaging.Render.ColorPixelData24.Render(ILUT lut, Int32[] output) en C:\\fo-dicom\\DICOM\\Imaging\\Render\\PixelData.cs:line 1240
en Dicom.Imaging.Render.ImageGraphic.RenderImage(ILUT lut) en C:\\fo-dicom\\DICOM\\Imaging\\Render\\ImageGraphic.cs:línea 235
en Dicom.Imaging.DicomImage.RenderImage(Int32 frame) en C:\\fo-dicom\\DICOM\\Imaging\\DicomImage.cs:line 256"

### Steps to reproduce the behavior
(I uploaded the dicomdir and the images files, so steps 1 and 2 shouldn't be necessary. I haven't uploaded the series files, I don't think they are needed, but will upload if requested)
1. Create a DICOM image via a similar method as described in [](https://gist.github.com/mdubey82/4030263).
2. Save the image to a File and have the DICOMDIR reference it.
3. Follow this code:
```
var dicomDirectory = await DicomDirectory.OpenAsync(dicomdirPath);
foreach (var patientRecord in dicomDirectory.RootDirectoryRecordCollection)
{
  foreach (var studyRecord in patientRecord.LowerLevelDirectoryRecordCollection)
  {
    foreach (var seriesRecord in studyRecord.LowerLevelDirectoryRecordCollection)
    {
      foreach (var imageRecord in seriesRecord.LowerLevelDirectoryRecordCollection)
      {
        var referencedSOPClass = imageRecord.GetValue<string>(DicomTag.ReferencedSOPClassUIDInFile, 0);
        if (referencedSOPClass != DicomUID.SecondaryCaptureImageStorage.UID)
        { //imageRecord is a series of images
          var dicomDataset = imageRecord.GetSequence(DicomTag.IconImageSequence).Items.First();
          var dicomMiniature = new DicomImage(dicomDataset);
          var miniatureImage = dicomMiniature.RenderImage().AsWriteableBitmap(); //works fine with series of images
        }
        else
        { //imageRecord is a single image
          var pathImage = string.Join(@"\", imageRecord.GetValues<string>(DicomTag.ReferencedFileID));
          var imageFile = await DicomFile.OpenAsync(pathImage);
          var dicomMiniature = new DicomImage(imageFile.Dataset);
          Debug.Print($"{dicomMiniature.NumberOfFrames} frames"); //result: "1 frames"
          var miniatureImage = dicomMiniature.RenderImage().AsWriteableBitmap(); //RenderImage() throws the above exception
          //tried .RenderImage(0) and .RenderImage(1), but the result was the same
        }
      }
    }
}
}
```

### fo-dicom version and OS/platform
fo-dicom 4.0.0.0, Windows 10

**Comment by ELPona** [comment]
[dicom_files.zip](https://github.com/fo-dicom/fo-dicom/files/3041527/dicom_files.zip)

**Comment by mia-san** [comment]
thank you for reporting and sharing sample data.
but it seems to me that the DICOM dataset is invalid.

the dataset says
  (0028,0004) PhotometricInterpretation is RGB
  (0028,0002) SamplesPerPixel is 1

this causes
- ColorPixelData24 is used for rendering as PhotometricInterpretation is RGB.
- ColorPixelData24 assumes 3 bytes per pixel.
- PixelData is read only 512 * 512 * 1 bytes, which is less than ColorPixelData24 expects.
- ColorPixelData24 accesses out of bounds.

as PixelData has size 786432 bytes, which exactly matches to 512 * 512 * 3, suggesting SamplesPerPixel should be 3.
actually, RenderImage works by changing SamplesPerPixel to 3.

dcmtk also warns as following
```
$ dcmj2pnm --write-jpeg --verbose 'Image01' 'Image01.jpg' 
I: reading DICOM file: Image01
I: preparing pixel data
W: invalid value for 'SamplesPerPixel' (1) ... assuming 3
I: writing frame 1 to Image01.jpg
I: cleaning up memory
```

btw, should fo-dicom 'correct' SamplesPerPixel like this case, as dcmtk does?

**Comment by ELPona** [comment]
@mia-san thanks a lot for the detailed response! I'm fairly new to both the DICOM standard and fo-dicom, so I guess your answer is most likely right. I'll try modifying the dataset to see if it works, as soon as I can (which will be in about 10 hours).
As a sidenote, I tried uploading the image file to [http://dicomviewer.booogle.net/](url) and it displays the image correctly, but I don't know if that site corrects the SamplesPerPixel internally.

Regarding if fo-dicom should correct the SamplesPerPixel, my guess would be that it shouldn't, but given dcmtk does, maybe it should. I'll leave that for the developers to decide.

Thanks again

**Comment by ELPona** [comment]
> actually, RenderImage works by changing SamplesPerPixel to 3.

This did the trick, SamplesPerPixel was 1 and had to be 3. It's funny because I was getting the value from a working Dataset of a series (the application creates a "Photo" from one of the images of a series being displayed on screen), but changing it to 3 made it work.

Perhaps a validation could be made, so that the exception is more relevant (I thought "Index out of bounds" was stating that I was trying to render a frame whose index surpassed the NumberOfFrames), but otherwise fo-dicom is working properly, and the error was in my code.

**Comment by mia-san** [comment]
> This did the trick, SamplesPerPixel was 1 and had to be 3.

good to hear that :)


> It's funny because I was getting the value from a working Dataset of a series (the application creates a "Photo" from one of the images of a series being displayed on screen), but changing it to 3 made it work.

just guessing, (0028,0004) PhotometricInterpretation is MONOCHROME1 or MONOCHROME2 in the original Dataset ?
SamplesPerPixel can be 1 for such images.

**Comment by ELPona** [comment]
So sorry for the delay. Yes, in the original Dataset, (0028,0004) PhotometricInterpretation is Monochrome2, and SamplesPerPixel is 1.

**Comment by mia-san** [comment]
> So sorry for the delay.

no problem :)

> Yes, in the original Dataset, (0028,0004) PhotometricInterpretation is Monochrome2, and SamplesPerPixel is 1.

ah, I think that explains.

regarding PhotometricInterpretation, DICOM standard says
- MONOCHROME2
  This value may be used only when Samples per Pixel (0028,0002) has a value of 1.
- RGB
  This value may be used only when Samples per Pixel (0028,0002) has a value of 3. 

see DICOM PS 3.3
C.7.6.3.1.2 Photometric Interpretation
https://www.dabsoft.ch/dicom/3/C.7.6.3.1.2/

in other words, you have to be careful, as just copying original dataset's attribute does not guarantee result dataset's consistency.

**Comment by gofal** [comment]
Will close the issue now, since the problem seems to be found and solved. Feel free to reopen this issue if there i still something left to do.
