### ISSUE TITLE
DicomClient.Abort / AbortAsync never returns when not connected

### ISSUE THREAD

**Issue by devsko** [fo-dicom/fo-dicom#841]
```c#
new DicomClient().Abort();
await new DicomClient().AbortAsync();
```
### Expected behavior
If a client was never used, calling Abort() should be a noop.

### Actual behavior
Abort() never returns / the AbortAsync() task never completes.

### fo-dicom version and OS/platform
4.0.1 / current branch, Windows 18362

**Comment by gofal** [comment]
this bug will be solved by the pull request #840 by @amoerie.
This unittest should demonstrate the bug you found, but runs green in the branch of the pull request:

   [Fact]
        public async Task DicomClient_AbortWhenNeverConnected()
        {
            var tic = DateTime.Now;
            new DicomClient().Abort();
            await new DicomClient().AbortAsync();
            var toc = DateTime.Now;

            Assert.True((toc - tic).TotalSeconds < 1);
        }

**Comment by devsko** [comment]
Ah, missed that. Thanks

**Comment by amoerie** [comment]
A bit sick atm, but I'll get back to it ASAP! 🙂

**Comment by hkoestin** [comment]
Is there a milestone set for this fix?

I recently tried to upgrade to 4.0.1 and cannot proceed, as that bug is blocking me.
