### ISSUE TITLE
Request datasets should not be validated (at least opt-out)

### ISSUE THREAD

**Issue by devsko** [fo-dicom/fo-dicom#842]
I try to create a request for an invalid StudyInstanceUID (it contains 0 parts). There is no easy way to turn off validation.
``` c#
var request = DicomCFindRequest.CreateSeriesQuery(studyId);
```
### Expected behavior
There should be a way to request even invalid but existing uid's.

### Actual behavior
The method throws an DicomValidationException.

### fo-dicom version and OS/platform
current development branch, Windows 18362

**Comment by gofal** [comment]
I see. So the validation should be turned off for UID tags when thy are referencing other uids, like tag ReferencedSopInstanceUID in DicomDirs or the Stuidy-, Series- and InstanceUIDs in CFind- CGet- or CMove-Requests.

Currently validation can be turned off only for the whole DicomDataset, but that would be too much to totally turn validation off for Requests, I think.

**Comment by devsko** [comment]
I personally would be fine when validation is completely off for requests. The invalid UID was just the first validation error occurred related to requests. I think requests are not the real target for dataset validation, which is otherwise a great feature.
