### ISSUE TITLE
Add Patient Info to Images

### ISSUE THREAD

**Issue by dattranvan22** [fo-dicom/fo-dicom#845]
### Expected behavior
I want to RenderImage from DICOM file. But On my contry, in IMAGES X-Ray must contain patient info as Attachments
![Dicom](https://user-images.githubusercontent.com/5811857/56336005-e67fcf00-61c8-11e9-9183-e1da7e2000b1.png)

### Steps to reproduce the behavior
var image = new DicomImage(file);
String patientname = image.Dataset.Get<string>(DicomTag.PatientName);
 Bitmap bm = image.RenderImage().AsBitmap();

### fo-dicom version and OS/platform
Nuget 4.0.1/ Windows 10

**Comment by gofal** [comment]
Yes, it is vey common to have user information as overlay over the images. But I am not sure if this should be part of `DicomImage.RenderImage()`. 

Various different contexts (printing, viewing for diagnostic purposes, reviewing, web display for patients, image analysis) require different text annotations or require no text annotation. So to have it built in DicomImage requires a lot of configuration, which tag in which font size in which corner in which color. Then some conditionals, for CT you may have different text than for MR or CR or US....

So until now I saw this kind of text annotation as part of the application that uses fo-dicom. You can do it easily by creating a System.Drawing.Graphics.DrawString.


But maybe you provide some more ideas how to enhance fo-dicom to make it easier for you and others to annotate images as required. Which kind of API do you expect?
