### ISSUE TITLE
JPEG 2000 decodes wrong colors in .NET Core

### ISSUE THREAD

**Issue by PalminX** [fo-dicom/fo-dicom#850]
Images with JPEG 2000 encoding get decoded with wrong colors in fo-dicom 4.0.1, .NET Core

### Expected behavior
Image looks like this:
![grafik](https://user-images.githubusercontent.com/28887826/56368919-ab958f80-61f8-11e9-8a8c-ac9ba83536d7.png)

### Actual behavior
Image looks like this:
![grafik](https://user-images.githubusercontent.com/28887826/56368954-b9e3ab80-61f8-11e9-87d2-a027e5c96b13.png)

### Steps to reproduce the behavior
Try to decode/render any of the PM5644-960x540_JPEG2000*.dcm files in the attached archive.

### fo-dicom version and OS/platform
4.0.1, .Net Core (Windows/Linux)

**Comment by PalminX** [comment]
Here is an update to the test pattern image archive I uploaded earlier, this now includes JPEG 2000 as well as RLE-encoded images.
In addition, the color values are now true RGB, i.e. Red is FF0000 etc.

# Color Test Pattern DICOM images

This archive contains DICOM SecondaryCaptureImageStorage color test pattern images (PM5644), the original file is available at [PM5644-1920x1080](https://commons.wikimedia.org/wiki/File:PM5644-1920x1080.gif).

The test pattern has been converted to DICOM RGB using [MeVisLab](https://www.mevislab.de/).
Subsequently, the RGB image was converted to
* 8 bit and 16 bit PALETTE COLOR images using [dcmquant](https://support.dcmtk.org/docs/dcmquant.html)
  * ```dcmquant.exe PM5644-960x540_RGB.dcm PM5644-960x540_Palette_8.dcm```
  * ```dcmquant.exe +pe PM5644-960x540_RGB.dcm PM5644-960x540_Palette_16.dcm```
* JPEG-Lossless and JPEG-Baseline images using [dcmcjpeg](https://support.dcmtk.org/docs/dcmcjpeg.html)
  * ```dcmcjpeg.exe PM5644-960x540_RGB.dcm PM5644-960x540_JPEG-Lossless_RGB.dcm```
  * ```dcmcjpeg.exe +eb PM5644-960x540_RGB.dcm PM5644-960x540_JPEG-Baseline_YBR422.dcm```
  * ```dcmcjpeg.exe +eb +s4 PM5644-960x540_RGB.dcm PM5644-960x540_JPEG-Baseline_YBRFull.dcm```
* JPEG-LS images using [dcmcjpls](https://support.dcmtk.org/docs/dcmcjpls.html)
  * ```dcmcjpls.exe PM5644-960x540_RGB.dcm PM5644-960x540_JPEG-LS_Lossless.dcm```
  * ```dcmcjpls.exe +en PM5644-960x540_RGB.dcm PM5644-960x540_JPEG-LS_NearLossless.dcm```
* JPEG 2000 and RLE encoded images using [gdcmconv](http://gdcm.sourceforge.net/html/gdcmconv.html)
  * ```gdcmconv.exe -K  PM5644-960x540_RGB.dcm PM5644-960x540_JPEG2000-Lossless.dcm```
  * ```gdcmconv.exe -K -Y  PM5644-960x540_RGB.dcm PM5644-960x540_JPEG2000-Lossy.dcm```
  * ```gdcmconv.exe -K -Y -r 50 PM5644-960x540_RGB.dcm PM5644-960x540_JPEG2000-Lossy50.dcm```
  * ```gdcmconv.exe -K -Y -r 50 PM5644-960x540_RGB.dcm PM5644-960x540_RLE-Lossless.dcm```

| File                                     	|  Instance Number (0020,0013) 	|  Transfer Syntax UID  (0002,0010)                	|  Photometric Interpretation   (0028,0004) 	|  RedPaletteColorLookupTableDescriptor   (0028,1101) 	|
|------------------------------------------	|------------------------------	|--------------------------------------------------	|-------------------------------------------	|-----------------------------------------------------	|
| PM5644-960x540_RGB.dcm                   	| 1                            	| LittleEndianExplicit                             	| RGB                                       	| N.A.                                                	|
| PM5644-960x540_Palette_8.dcm             	| 2                            	| LittleEndianExplicit                             	| PALETTE COLOR                             	| 256\0\8                                             	|
| PM5644-960x540_Palette_16.dcm            	| 3                            	| LittleEndianExplicit                             	| PALETTE COLOR                             	| 256\0\16                                            	|
| PM5644-960x540_JPEG-Lossless_RGB.dcm     	| 4                            	| JPEGLossless:Non-hierarchical-1stOrderPrediction 	| RGB                                       	| N.A.                                                	|
| PM5644-960x540_JPEG-Baseline_YBR422.dcm  	| 5                            	| JPEGBaseline                                     	| YBR_FULL                                  	| N.A.                                                	|
| PM5644-960x540_JPEG-Baseline_YBRFull.dcm 	| 6                            	| JPEGBaseline                                     	| YBR_FULL_422                              	| N.A.                                                	|
| PM5644-960x540_JPEG-LS_Lossless.dcm      	| 7                            	| JPEGLSLossless                                   	| RGB                                       	| N.A.                                                	|
| PM5644-960x540_JPEG-LS_NearLossless.dcm  	| 8                            	| JPEGLSLossy                                      	| RGB                                       	| N.A.                                                	|
| PM5644-960x540_JPEG2000-Lossless.dcm     	| 9                            	| JPEG2000LosslessOnly                             	| RGB                                       	| N.A.                                                	|
| PM5644-960x540_JPEG2000-Lossy.dcm        	| 10                           	| JPEG2000                                         	| RGB                                       	| N.A.                                                	|
| PM5644-960x540_JPEG2000-Lossy50.dcm      	| 11                           	| JPEG2000 (50% Compression Ratio)                 	| RGB                                       	| N.A.                                                	|
| PM5644-960x540_RLE-Lossless.dcm          	| 12                           	| RLELossless                                      	| RGB                                       	| N.A.                                                	|

These DICOM images can be used under a [Creative Commons Attribution 3.0 Unported License.](https://creativecommons.org/licenses/by/3.0/)

Bernd Kuemmerlen (bkuemmer@gmx.net)

Version: 3.0, 2019-04-18

[TestPattern_Samples_V3.zip](https://github.com/fo-dicom/fo-dicom/files/3094900/TestPattern_Samples_V3.zip)

**Comment by PalminX** [comment]
It seems that just the red and blue channels are swapped while decoding

**Comment by PalminX** [comment]
Does anyone have a chance looking into this? I tried debugging, but got lost in the codecs...

**Comment by PalminX** [comment]
I don't know how the two issues are related, I just wanted to point out that I did some more analysis in https://github.com/Efferent-Health/Dicom-native/issues/1#issuecomment-498318129, and I am wondering if the code at https://github.com/fo-dicom/fo-dicom/blob/146d9cb2b7b200c9ec8ce8c178873fec0c71c95d/DICOM/Imaging/DicomImage.cs#L355 is doing the correct thing for YBR_* photometric interpretations. 

If this is really completely unrelated, I could open a new issue to clarify this question...

**Comment by gofal** [comment]
line 355 in DicomImage is not relevant. the issue is with Jpeg2000 compression and the condition in line above is for JpegProcess1 and JpegProcess2_4, so not for jpeg 2000.

**Comment by gofal** [comment]
its definitively some mixed up color space problem. Dicom has RGB, but when rendering Bitmaps internally use BGR color space. Somewhere this conversion is missing. I am comparing with other encodings where the image is rendered correctly, but nowhere I found a explicit conversion. Still doing research.

**Comment by gofal** [comment]
fixed the RGB BGR colorspace problem in netcore jpeg2k compression. Now all sample images in all compresssions render correctly in .netcore and desktop. 

Please veryfy and give feedback.

**Comment by PalminX** [comment]
Thanks, I can confirm that all my Testpattern sample images are now rendered correctly! Thanks a lot!
Closing
