### ISSUE TITLE
what's the best practices of DicomServer?

### ISSUE THREAD

**Issue by cocosip** [fo-dicom/fo-dicom#851]
> when create a dicom server :
```c#
var server = new DicomServer<xxxProvider>(12345);
```
> If i wan't xxxProviderto handle multiple type of request ,like c-move,c-store,c-get ...... in one port ,
Should xxxProvider implements the interface `IDicomCGetProvider`,`IDicomCMoveProvider`,`IDicomCFindProvider` ... ?  What's the best practices ?

**Comment by mia-san** [comment]
I suppose that's why they're defined as interface.

actually, one of my projects has something like this:
```
Public Class MyServiceProvider
    Inherits DicomService
    Implements IDicomCEchoProvider
    Implements IDicomCFindProvider
    Implements IDicomCStoreProvider
    Implements IDicomServiceProvider
```

**Comment by gofal** [comment]
right. The reason for interfaces is, because inheriting from multiple classes is not supported in c#.

furthermore it is best practice to call

         DicomServer.Createy<T>(....)

instead of directly instanciating a new DicomServer. This static factory-method does some checks to make sure the port is available for listening.
