### ISSUE TITLE
When 4.0.2 release is planned?

### ISSUE THREAD

**Issue by Telexy** [fo-dicom/fo-dicom#855]
Waiting for some 4.0.1 critical bug fix which is already fixed in "development" branch... Do you have any expectation regarding to 4.0.2 release date?

Thanks.

**Comment by hkoestin** [comment]
Would be interested in the same ;-)

**Comment by anders9ustafsson** [comment]
Will look into this and prepare a release relatively soon.

**Comment by PalminX** [comment]
I also would appreciate a release of 4.0.2 soon

**Comment by PalminX** [comment]
With the fixes for #850 and #817 having landed now, I really would appreciate a new official release soon.

Thanks for your consideration.

**Comment by amoerie** [comment]
We're also interested in an official 4.0.2 release 👍

**Comment by anders9ustafsson** [comment]
Sorry about the delay. I had issues building the solution automatically, will try again shortly.

**Comment by gofal** [comment]
release is available via nuget
