### ISSUE TITLE
Using DicomClient to send several C-STORE requests over same connection/association

### ISSUE THREAD

**Issue by hkoestin** [fo-dicom/fo-dicom#857]
Hello

I am trying to achieve the following: my software serves as a proxy between a PACS and some other (destination) DICOM nodes (AEs).
A PACS can push data to such a destination node through the proxy.
The proxy would then accept the incoming C-STORE requests and forward them on the fly to the destination node as requested.

As the destination nodes have restrictions in terms of connections and also concurrent associations, I need to do that in a single association with a single DicomClient.

My C-STORE provider will just take the request and "forward" its dataset to the destination by simply adding the request to that client. The client then sends data using the `SendAsync` method to not block the next incoming C-STORE from the PACS to my provider.

BTW: according to #707 (and this is quite clear), I did add all the presentation contexts in the beginning as additional PCs to the client. No luck with that though.

### Expected behavior
By using the linger period of the DicomClient, I would like to add new requests on the fly and the client then should send them over to the destination using the SAME association and connection.

### Actual behavior
The DicomClient just disconnects at a certain point in time by releasing the association and sending an association release request to the destination.
Then, a few requests fail, and after the connection + assoc is re-established, sending succeeds again.
However, I lost a few instances then.
This usually happens when I try to push series with more than 20 instances. For single instances or just small series, this does not happen.

Why does the client decide to give up on the existing association, although the request queue is still not empty?

What I did try so far:
* using 4.0.0: no luck
* using Send(): no luck
* using SendAsync(): no luck
* using INetworkStream I created on my own to keep open: no luck

### Steps to reproduce the behavior
Things to reproduce are mentioned in here #745 and #707 already. #356 is similar as well, but NegotiateAsyncOps does not help as well.

Just create one client, add PCs to it, and start sending requests to a remote.
Then in a loop keep adding requests. Eventually, you will see the disconnect happening.

This here is an extract from my logs:
```
// my store provider already received a few C-STOREs and added them to the client
// then, because it is run async, the association to the destination AE is created
2019-05-08 15:45:22.5000 [Dicom.Network] IF88ORTHANC -> Association request:
// ... 
// which gets accepted right after
2019-05-08 15:45:22.5059 [Dicom.Network] IF88ORTHANC <- Association accept:

// then it starts sending requests
2019-05-08 15:45:22.5229 [Dicom.Network] IF88ORTHANC -> C-Store request [1] 
2019-05-08 15:45:22.5743 [Dicom.Network] IF88ORTHANC <- C-Store response [1]: Success 
2019-05-08 15:45:22.5743 [Dicom.Network] IF88ORTHANC -> C-Store request [2] 
2019-05-08 15:45:22.6142 [Dicom.Network] IF88ORTHANC <- C-Store response [2]: Success 

// after some time, the DicomClient releases the association, which causes errors
2019-05-08 15:45:24.9897 [Dicom.Network] IF88ORTHANC -> C-Store request [64] 

// WHY????
2019-05-08 15:45:25.0036 [Dicom.Network] IF88ORTHANC -> Association release request 

2019-05-08 15:45:25.0036 [Dicom.Network] Socket error while writing PDU: ConnectionReset [10054] 
2019-05-08 15:45:25.0036 [Dicom.Network] Connection closed 
2019-05-08 15:45:25.0366 [Dicom.Network] Exception creating PDV: System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host

// but eventually reconnects afterwards again and continues sending.
2019-05-08 15:45:26.2722 [Dicom.Network] IF88ORTHANC -> Association request:
2019-05-08 15:45:26.2722 [Dicom.Network] IF88ORTHANC <- Association accept:
2019-05-08 15:45:26.2722 [Dicom.Network] IF88ORTHANC -> C-Store request [65] 
2019-05-08 15:45:26.2852 [Dicom.Network] IF88ORTHANC <- C-Store response [65]: Success
```

For the logs above, C-Store request [64] was lost and the proxy could get through C-Store request [65] already again. Some times, there are more failing, than just one.
So when I try to push a full study or series, it could be the case, that there are a few instances missing.

### fo-dicom version and OS/platform
4.0.1 with Win10 x64

What am I doing wrong?
Or is this simply a bug in the framework?

This functionality (sending several requests) using the same assoc/connection to the destination would be crucial for me. I simply cannot recreate a new DicomClient for every incoming C-STORE from the PACS.

Thank you very much for your help!

Kind regards,
Harald

EDIT:
Somehow I have the feeling, that the new version of the https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Network/DicomClient.cs class would solve some issues already, as there is special handling for not releasing an association, when there are requests available and/or lingering period has not exceeded.

When will there a new release of that?
Can I somehow get a pre-release of the current master?

**Comment by hkoestin** [comment]
Somehow I have the feeling, that the new version of the https://github.com/fo-dicom/fo-dicom/blob/development/DICOM/Network/DicomClient.cs class would solve some issues already, as there is special handling for not releasing an association, when there are requests available and/or lingering period has not exceeded.

When will there a new release of that?
Can I somehow get a pre-release of the current master?

**Comment by gofal** [comment]
You are doing nothing wrong. And it's not a bug of fo-dicom. Because nowhere in DICOM standard is defined that an association should be kept open as long as the client likes. It's just how its implemented.

The DicomClient does some very handy interface for you. Just add the list of Requests you like to send and then call `Send` or `SendAsync`. And fo-dicom does then find out all the abstract syntaxes you like to send and then opens the association for you, does the sending, and closes it as it should. So it is a very handy API. 
What you desire is that you want to take more control. You want to open the association yourself and you decide in advance which different abstractsyntaxes will be sent. and you want to take responsibility to close the association manually after some time. That is a complete different approach.

Yes, the new implementation of DicomClient will make this possible. 
You can fetch the sourcecode from the branch whenever you want. Will merge the pull request within the next days, then you just need to get the latest code from development branch.  If you need a ready built nuget package, then you will have to wait until Anders Gustaffson does a new release.

**Comment by hkoestin** [comment]
> And it's not a bug of fo-dicom.

To be fairly honest with you, in my opinion, this **is a bug** of fo-dicom.
I use the linger period property to set a linger period of 2000ms and would expect this to behave as I expected.

In the documentation it clearly says:
```c#
/// <summary>
/// Gets or sets time in milliseconds to keep connection alive for additional requests.
/// </summary>
public int Linger { get; set; }
```

When the client then releases the association within that time-frame, then to me, this is a bug.
The time-frame should be calculated from the point of the last enqueued request. If there are no requests enqueued within the "linger-period-in-ms", then the client is free to cancel/abort/release the connection.
However, if the client obviously sees, that there are remaining requests in the queue, it **must not** release the association. Or is this now a misunderstanding on my side?

I will try to port over the new `DicomClient` implementation to my code-base and use that one as a template.

**Comment by hkoestin** [comment]
@amoerie thank you very much for your feedback. 

I see, that the client is a tough work to do, as of all the async tasks involved there. Thank you for your work so far and the effort.

I just did a local build and will give that a try now.

**Comment by amoerie** [comment]
@hkoestin @gofal I've added missing unit tests for the linger behavior for both the old and the new DicomClient. This actually surfaced another small bug in the old DicomClient, see this commit: https://github.com/fo-dicom/fo-dicom/pull/854

The linger tests for the old DicomClient can be seen here:
https://github.com/amoerie/fo-dicom/blob/development/Tests/Desktop/Network/DicomClientTest.cs#L704

The linger tests for the new DicomClient can be seen here:
https://github.com/amoerie/fo-dicom/blob/development/Tests/Desktop/Network/Client/DicomClientTest.cs#L820

**Comment by buckstephenh** [comment]
The only way using linger to maintain a connection beyond the current known set of items to send prior to connection establishment  is to have code that verified the incoming items post-association were already negotiated successfully, then the linger counter would begin after the last acknowledgment. 

If a dicom item comes in that is not part of the current negotiation then the connection would need to terminate and a new association created.   


Sent from my iPhone

On May 9, 2019, at 1:59 AM, Harald Koestinger <notifications@github.com> wrote:

And it's not a bug of fo-dicom.

To be fairly honest with you, in my opinion, this is a bug of fo-dicom.
I use the linger period property to set a linger period of 2000ms and would expect this to behave as I expected.

In the documentation it clearly says:

/// <summary>
/// Gets or sets time in milliseconds to keep connection alive for additional requests.
/// </summary>
public int Linger { get; set; }
When the client then releases the association within that time-frame, then to me, this is a bug.
The time-frame should be calculated from the point of the last enqueued request. If there are no requests enqueued within the "linger-period-in-ms", then the client is free to cancel/abort/release the connection.
However, if the client obviously sees, that there are remaining requests in the queue, it must not release the association. Or is this now a misunderstanding on my side?

I will try to port over the new DicomClient implementation to my code-base and use that one as a template.

**Comment by hkoestin** [comment]
@amoerie I gave your new implementation a try and it seems to work quite nicely. I did transfer a whole patient with 800 instances, and a few smaller studies and series, all without any issue so far.

Also from the logs, you can easily see, that there is work done :-)

```
[Dicom.Network] [SENDING REQUESTS] DICOM client send queue is empty, going to linger association now... 
[Dicom.Network] [SENDING REQUESTS] --> [LINGERING ASSOCIATION] 
[Dicom.Network] [LINGERING ASSOCIATION] Linger timed out after 2000ms, releasing association 
[Dicom.Network] [LINGERING ASSOCIATION] --> [RELEASING ASSOCIATION] 
[Dicom.Network] IF88ORTHANC -> Association release request 
[Dicom.Network] IF88ORTHANC <- Association release response 
[Dicom.Network] [RELEASING ASSOCIATION] No more requests to be sent, disconnecting... 
[Dicom.Network] Connection closed 
[Dicom.Network] [RELEASING ASSOCIATION] --> [COMPLETED] 
[Dicom.Network] [COMPLETED] DICOM client completed without errors 
[Dicom.Network] [COMPLETED] We still have an active connection, cleaning that up now 
[Dicom.Network] [COMPLETED] --> [IDLE] 
[Dicom.Network] [IDLE] No requests to send, staying idle 
```

**Comment by amoerie** [comment]
That's amazing to hear. Looks like the unit tests are quite reliable! 

Thank you very much for taking it for a spin. I'm trying to add decent 'Abort' behavior to it right now (immediately send an ABORT to the DICOM server and shut down the connection) which should give it 99% feature parity with the old DicomClient, save for the special C-Store request handling, which is still a bit under discussion.

**Comment by amoerie** [comment]
> The only way using linger to maintain a connection beyond the current known set of items to send prior to connection establishment is to have code that verified the incoming items post-association were already negotiated successfully, then the linger counter would begin after the last acknowledgment. If a dicom item comes in that is not part of the current negotiation then the connection would need to terminate and a new association created.
> […](#)
> Sent from my iPhone On May 9, 2019, at 1:59 AM, Harald Koestinger <notifications@github.com> wrote: And it's not a bug of fo-dicom. To be fairly honest with you, in my opinion, this is a bug of fo-dicom. I use the linger period property to set a linger period of 2000ms and would expect this to behave as I expected. In the documentation it clearly says: /// <summary> /// Gets or sets time in milliseconds to keep connection alive for additional requests. /// </summary> public int Linger { get; set; } When the client then releases the association within that time-frame, then to me, this is a bug. The time-frame should be calculated from the point of the last enqueued request. If there are no requests enqueued within the "linger-period-in-ms", then the client is free to cancel/abort/release the connection. However, if the client obviously sees, that there are remaining requests in the queue, it must not release the association. Or is this now a misunderstanding on my side? I will try to port over the new DicomClient implementation to my code-base and use that one as a template. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

It's tricky though. If you enqueue many requests, some of which are compatible and some aren't, what do you do? Send those that can be sent over the existing association? What if you keep enqueuing requests that are compatible, so that the non-compatible ones are never sent?

For now, the responsibility lies with the user, who has to ensure that associations are properly created by either enqueueing the requests up front or by using the additional presentation contexts that can be configured on DicomClient. 

Trying to do too much magic usually results in complex, hard to maintain code, so I try to avoid being a wizard at all times. :-)

**Comment by amoerie** [comment]
@hkoestin I added some finishing touches to the new DicomClient, and am now quite confident in its abilities. If you get compilation errors, I refactored AddRequest to AddRequestAsync. For full details why I did this, see my comment here: https://github.com/fo-dicom/fo-dicom/pull/854#issuecomment-493752467

There's also AddRequestsAsync now, if you have many requests that are known in advance.

CC @gofal

**Comment by amoerie** [comment]
@gofal This can probably be closed now?

**Comment by mocsharp** [comment]
Will this be in 4.0.2 release?

In the mean time, is it better to create a single client and do multiple `client.AddRequest(..)` or is it better to send each request with `client.Send(...)`?

Thanks!

**Comment by amoerie** [comment]
General advice: make a separate DicomClient for every DICOM server you'll be talking to. If you have many requests, it's best to reuse a DicomClient, as it'll reuse the existing connection and association to send them. It's best though to first call "AddRequest" for each request and then call Send at the end, because then it'll automatically set up the correct presentation contexts on the association.

If you plan to add more requests while it's already sending, you must either prepare the DicomClient with all the presentation contexts you're going to need using DicomClient.AdditionalPresentationContexts, or you can use multiple DicomClients. The question is always: is this request compatible with the current open association?

**Comment by gofal** [comment]
this is implemented with the new DicomClient

**Comment by priyam1507** [comment]
Hello Guys, 
I found this thread that discussed similar issues that I am having currently.  
I am facing this issue quite often while trying to migrate large amount of DICOM /Jpeg Lossless studies from One PACS to other ,the latter is hosted on AWS EC2 instance. DICOM association fails or be broken after 30-40 studies are successfully transferred out of total 400+ studies that  I am attempting to transfer in single DICOM association between these two Pacs. What could be the issue and how can I use the fo-dicom toolkit on Windows 10 platform to potentially achieve a feasible solution?Can anyone help me how to download and install this toolkit and deploy this client between these two PACS. 
Thanks in advance for your expert advice.!!
Best 
Priyam

**Comment by buckstephenh** [comment]
> @buckstephenh
> 
> > The only way using linger to maintain a connection beyond the current known set of items to send prior to connection establishment is to have code that verified the incoming items post-association were already negotiated successfully, then the linger counter would begin after the last acknowledgment. If a dicom item comes in that is not part of the current negotiation then the connection would need to terminate and a new association created.
> 
> It's tricky though. If you enqueue many requests, some of which are compatible and some aren't, what do you do? Send those that can be sent over the existing association? What if you keep enqueuing requests that are compatible, so that the non-compatible ones are never sent?
> 
> For now, the responsibility lies with the user, who has to ensure that associations are properly created by either enqueueing the requests up front or by using the additional presentation contexts that can be configured on DicomClient.
> 
> Trying to do too much magic usually results in complex, hard to maintain code, so I try to avoid being a wizard at all times. :-)

Unfortunately I replaced fo-dicom with dcmtk to get the performance and reliability I needed, partly because of this issue.  I have moved on from the project but the solution I wrote is in over 500 hospitals and counting.   We were unable to "rely on the user" for presentation contexts.  We simply got what we are handed and had to transmit everything.  There was no room for error in the library deciding to hang in the batch and not know which item was the problem.  Hope it gets fixed.  I had to drop to batch size 1 to get any reliability which killed performance.  Also the event hooks made it extra slow as well.   Best success!  The fo-dicom connector is still in the solution if progress is made.

**Comment by priyam1507** [comment]
Thanks Stephen for your response , Could you please point me to the right dcmtk tool/client that best fits my need. I am gonna need it not only for my current work but largely for many clinical trial data migration projects from one PACS server to another. Also, It would be great if you can provide link for any documentation that describes as to how I can deploy the tool between those two modalities/PACS server so it works seamlessly and servers the purpose . Thank you in advance for your timely advice! Much appreciated!!

**Comment by zhan2016** [comment]
@priyam1507 Did you figure out question? Can you give some documentation? 

> Thanks Stephen for your response , Could you please point me to the right dcmtk tool/client that best fits my need. I am gonna need it not only for my current work but largely for many clinical trial data migration projects from one PACS server to another. Also, It would be great if you can provide link for any documentation that describes as to how I can deploy the tool between those two modalities/PACS server so it works seamlessly and servers the purpose . Thank you in advance for your timely advice! Much appreciated!!
