### ISSUE TITLE
DicomValidation for VR UI and VM > 1

### ISSUE THREAD

**Issue by hkoestin** [fo-dicom/fo-dicom#860]
Hello

For creating C-FIND requests, which carry several study-instace-uids, I need to do a list of UID matching, right?
See also: http://dicom.nema.org/medical/dicom/current/output/chtml/part04/sect_C.2.2.2.2.html

I need to do that in order to support the DICOMweb standard QIDO parts:
http://dicom.nema.org/medical/dicom/current/output/chtml/part18/sect_10.6.html

```
/studies?StudyInstanceUID=1.2.392.200036.9116.2.2.2.2162893313.1029997326.94587,1.2.392.200036.9116.2.2.2.2162893313.1029997326.94583
```

My previous code I had for that, to include several UIDs in the c-find command set was just doing this.
I just replaced the "," on the web request with the "\"
```
var ds = new DicomDataset().Add(DicomTag.StudyInstanceUID, "1.2.3\\3.4.5");
```

### Expected behavior
I need to get in several UIDs for list matching.

### Actual behavior
This however is throwing now:
```
Content "(0020,000d) UI Study Instance UID" does not validate VR UI: Number of items 2 does not match ValueMultiplicity 1
```

### Steps to reproduce the behavior
```c#
var ds = new DicomDataset().Add(DicomTag.StudyInstanceUID, "1.2.3\\3.4.5");

// or
var ds = new DicomDataset().Add(DicomTag.StudyInstanceUID, "1.2.3", "2.3.4");

// or
var ds = new DicomDataset().Add(new DicomUniqueIdentifier(DicomTag.StudyInstanceUID, "1.2.3", "3.4.5"));
```

### fo-dicom version and OS/platform
Development branch, but I guess already in 4.0.1 existing.

How can I achieve my goal?

Currently, I cannot use my software, as all the unit tests and integration tests I have are failing.

**Comment by hkoestin** [comment]
This is realted to #627 and #756 I guess

**Comment by gofal** [comment]
This is a tricky bug. Validation is done by ValueRepresentation as well as - if defined in DICOM standard - by Value Multiplicity. And StudyInstanceUid 0020,000D seemed to be defined with VM 1. But there seem to be a exception in case of CFinds, where the VM is 1...n.
But anyway: in pull request #861 the auto validation for CFind requests was turned off, so this validation for VM is now disabled too.
You can write any text you like into dicomTag 0020,000D, you will receive an empty resultset if the text was invalid ;-)

Will add unit tests for this issue here to the pull request.

**Comment by hkoestin** [comment]
Thank you very much for the fast fixes concerning these issues.

I will forward-merge the PR into my private repo and give it a try on my testing instances.
Can provide you with more feedback afterwards.

**Comment by hkoestin** [comment]
In general, this seems to work now. The root level dataset for the C-FIND request now is not validated anymore, which is fine for "most" of the cases.

However, there are other cases as well, were you need to add "sub-datasets" to the find request itself, e.g. when you have sequences with values.

For example, the code shows one of my integration tests for query building: the URL on a Dicom QIDO service can contain the query `"?OtherPatientIDsSequence.00100020=1234,5678,1.2,3.4"`

```c#

// INPUT to unit test
new Dictionary<string, string>
{
   // Matching parameter / Query parameter
    {"OtherPatientIDsSequence.00100020", "1234,5678,1.2,3.4"}
},

// EXPECTED output
(Action<DicomDataset>) (ds =>
{
   // the expected outcome of the c-find query dataset should look like "ds" in the end.

    var seq = new DicomDataset {AutoValidate = false};
    seq.Add(DicomTag.PatientID, "1234", "5678", "1.2", "3.4");
    ds.Add(new DicomSequence(DicomTag.OtherPatientIDsSequence, seq));
})
```

When my code now detects such a sequence matching parameter, I do add it to the root-level dataset using the following code: 

```c#
var dicomSequence = new DicomSequence(entry.Tag);
var dataset = new DicomDataset();

// find the tag using the Dictionary ...
// check and parse value, replace ',' by '/' etc.

// THIS code now fails !!!
dataset.AddOrUpdate(tag, value);

// add the dataset to the sequence 
dicomSequence.Items.Add(dataset);

// set the sequence to the c-find request
dicomRequest.AddOrUpdate(dicomSequence);
```

I know, I can easily fix it by making all Datasets there "non-validating", but this seems to be ugly.

Any idea on having that?
Maybe some nice extension method for the `DicomCFindRequest` class?

I like explicit and speaking code. some nice explicit method would be nice.

```c#
    public static class DicomCFindRequestExtensions
    {
        /// <summary>
        /// Creates a new <see cref="DicomDataset"/> and sets its
        /// <see cref="DicomDataset.AutoValidate"/> property according to the
        /// request's query dataset property value for the auto validate field.
        /// <para>
        /// Said differently: when the C-FIND request has a dataset which is not validated,
        /// the created dataset won't be validated either.
        /// </para>
        /// </summary>
        /// <param name="request">Not null. The request object.</param>
        public static DicomDataset CreateChildDataset(this DicomCFindRequest request)
        {
            return new DicomDataset {AutoValidate = request.Dataset.AutoValidate};
        }
    }
```

In addition, I would favor a "fluent" version of the setting of the validation flag, as now, you cannot create and add values to a dataset in a construction call, as method chaining is not possible.

```c#
var x = new DicomDataset { AutoValidate = false };
x.Add().Add().Add()...;
```

Maybe a "native" method on the dataset would help to do that, e.g `NotValidated()`, which returns the modified instance and allows for method chaining.

```c#
// extension
public static DicomDataset NotValidated(this DicomDataset dataset)
{
    dataset.AutoValidate = false;
    return dataset;
}

// usage

var x = new DicomDataset().NotValidated()
   .Add()
  .Add();
```

What do you think about that?
