### ISSUE TITLE
Question about UID parsing

### ISSUE THREAD

**Issue by hkoestin** [fo-dicom/fo-dicom#864]
I noticed some of my integration tests failing because of this code change:

https://github.com/fo-dicom/fo-dicom/blob/a87f5105c48c26f303b54aad0d97a801cdc33e21/DICOM/DicomUID.cs#L171

Was this made on purpose or did it just happen?
The line is simply commented.

I had tests which checked for some valid/invalid transfer-syntax elements. Now, I always get Unknown instead of failures, when the passed UID is obviously not valid.

Maybe there is a stronger set of regression tests needed here?

**Comment by gofal** [comment]
This line was commented out in 2012: https://github.com/fo-dicom/fo-dicom/commit/82784a889b6114ff28c672849e51f407cf3a7d6b So actially it has been always there in fo-dicom
