### ISSUE TITLE
How to read the tags of multiple Dicom files as fast as possible?

### ISSUE THREAD

**Issue by nah0y** [fo-dicom/fo-dicom#865]
Hello!

I have a lot of DICOM files to read at once, to be able to sort each of them in groups (depending on the series they're from).
Is there a way to very quickly read tags from Dicom files without opening them?

For 700+ elements, it takes more than 13 seconds to open all of them.

Same thing with getting thumbnails of Dicom files. Is there a way to very quickly get a thumbnail of a lot of Dicom files? Or I absolutely have to open them one by one?

Thanks!

**Comment by gofal** [comment]
There is an option in `DicomFile.Open` how to deal with larte Tags (namely the pixel data): https://github.com/fo-dicom/fo-dicom/blob/9c14ae6afca96d3b41a59797565840a947714cd7/DICOM/DicomFile.cs#L205
With Option `SkipLargeTags' fo-dicom only reads a few kilobytes instead the megabytes of pixel data. 
Of yourse you also can try to read the files in parallel, but you have to test it on your machine.

With thumbnails: if you have to calculat the tumbnails yourself, then there is no other option than to read the whole file and do rendering. If the creator of the dicom files already inserts a thumbnail (icon Image Sequence 0088,0200 - GE does this sometimes) then this thumbnail is available with the option described above.

If you have a chance of pre-processing (eg you receive the images via your Store-SCP service and then you need to read the files later when displaying the data, then there is time between for pre-processing), you could read the files and create a DICOMDIR file that contains the dicom tags you require for sorting and grouping. You may also add Icon Image Sequences to the DICOMDIR file.

**Comment by nah0y** [comment]
Thanks for the answer!
Unfortunately I'm using the Unity version of the project (available in the Unity Asset Store), but it's been a while since it's been updated. So I don't have the latest commits with this option for Open.
Do you know if there's any plan to upgrade it?

Thanks a lot for the other tips as well :)

**Comment by gofal** [comment]
The unity project just imports the code from shared project. So it should be just a release action, no coding required. @anders9ustafsson

**Comment by nah0y** [comment]
Well there is some issues with building the code myself.
First there is a lot of errors that I don't really know how to fix.
Plus the code to convert DICOM to Texture2D is not included in the source code, it's only in the DLL sold on the Asset Store.
So even if I'm able to build it myself, I won't be able to use it because it will miss the convert to Texture2D...

**Comment by anders9ustafsson** [comment]
I will add the full-blown Texture2D implementation for everyone's convenience. Hold on a short while longer.

**Comment by gofal** [comment]
closed due to inactivity. If there are any updates or if the problem is still alive, please reopen the issue.
