### ISSUE TITLE
The .NET Core unit tests are not run in CI?

### ISSUE THREAD

**Issue by amoerie** [fo-dicom/fo-dicom#867]
See title. Can this be added to Appveyor?

**Comment by gofal** [comment]
See #804 I am not very happy with Appveyor. 
I would prefer to use Travis CI to build and run tests on .netcore on linux and OsX, and use Azure for .net framework on windows. Any experiences or other recommendations from someone?

**Comment by amoerie** [comment]
I actually run my own mini project and am very content with running my builds with a Docker file.
See https://github.com/amoerie/teamcity-theatre, more specifically https://github.com/amoerie/teamcity-theatre/blob/master/Dockerfile for the docker file itself. 

It makes the setup pretty much CI platform agnostic, so for example my Travis file looks like this: https://github.com/amoerie/teamcity-theatre/blob/master/.travis.yml

Of course, for .NET Desktop builds you'd need Windows Containers, but these are available on Azure Devops!

**Comment by amoerie** [comment]
I played around with Dockerizing fo-dicom builds, but the fact that we need to build a portable class library, which is not included in Visual Studio Build Tools, is a serious obstacle right now. I've created an issue here #870 that would make this a whole lot easier.

**Comment by amoerie** [comment]
Closing this issue for now. Can come up again once the transition to .NET Standard 2.0 is made
