### ISSUE TITLE
Access violation while trying to export image, causing crashes

### ISSUE THREAD

**Issue by srikrishnag** [fo-dicom/fo-dicom#869]
I see that fo-dicom is throwing "access violation, attempted to read or write protected memory" at GdipSaveImageToFile intermittentley , while trying to save image using image.RenderImage().... We are using system.drawing lib in our project

### Expected behavior
Able to export image

### Actual behavior
Crashes program

### Steps to reproduce the behavior
This happens intermittently 

### fo-dicom version and OS/platform
fo-dciom 4.0.1,windows server 2019

**Comment by gofal** [comment]
Could you provide more code, that you use when the exception is thrown? I dont know where to start searching in code based on this minimal information.
On thing that comes into my mind immediatelly: are you using `.AsBitmap()`, `.AsClonedBitmap()` or `.AsSharedBitmap()` on IImage after calling `.RenderImage()`?

**Comment by srikrishnag** [comment]
found issue with my code., i was not handling the unmanaged code. With proper GC i was able to handle it
