### ISSUE TITLE
Secure DICOM - still works on TLS 1.0

### ISSUE THREAD

**Issue by Telexy** [fo-dicom/fo-dicom#872]
### Expected behavior
DICOM server should support TLS 1.1 and TLS 1.2. Especially TLS 1.2 as previous versions are not considered as secure any more.

### Actual behavior
Only TLS 1.0 supported.

### Steps to reproduce the behavior
Try to establish secure connection from a client with TLS 1.2. It will fall down to TLS 1.0. Or will not connect at all if TLS 1.0 is disabled on the server computer.

### fo-dicom version and OS/platform
Windows. fo-dicom 4.0 and current development branch.

**Comment by gofal** [comment]
Currently fo-dicom is designed to compile as portable (PCL). And there is no support for TLS 1.1 and TLS 1.2..
As described here #870 the plan is, soon to migrato to netstandard where this then will be possible.

**Comment by Telexy** [comment]
Actually I was talking about replacing single line in DesktopNetworkStream.cs which does not have any PCL reference. It is about replacing this:
                ssl.AuthenticateAsServer(certificate, false, SslProtocols.Tls, false);
with this:
                ssl.AuthenticateAsServer(certificate, false, SslProtocols.Tls | SslProtocols.Tls11 | SslProtocols.Tls12, false);

Otherwise this library simply doesn't work on Windows 2019. I mean server part with secure DICOM enabled. Didn't know that this is more complicated then that...

**Comment by gofal** [comment]
ah, I see. I will take a look at this. If it really is just this line and there are no dependencies, then of course I will add it as soon as possible. I had a talk to my coworker about this topic some time ago and I got the impression this would be something to implement with netstandard.

**Comment by Telexy** [comment]
That probably make sense if you want to change it for other platforms as well - I don't know. But for Windows (Desktop platform) - that's it. Already tested - works fine. Just make sure to leave that SslProtocols.Tls (TLS 1.0) as well for compatibility with older clients. 
Thanks for considering.

**Comment by gofal** [comment]
actually changing these two lines of code buids on all platforms well.

**Comment by Marigoldp1** [comment]
Hello All,
Can you share me the link or C# project , Which explain How to use TLS protocol security with Dicom PACS server.
