### ISSUE TITLE
Unbelievable warning "No Dicom codecs were found after searching"

### ISSUE THREAD

**Issue by viodo** [fo-dicom/fo-dicom#874]
### Expected behavior
JPEGLSLossless image compression

### Actual behavior
In Windows 7 and Windows 10 are all possible, but under Windows Server 2008 R2 platform will throw No Dicom codecs were found after searching "C:\JFAPP\RIS\tmp\Debug\Dicom.Native*.dll", but Dicom.Native.dll is there
### fo-dicom version and OS/platform
fo-dicom v4.0.1 
windows server 2008 R2(VMware)
.net framework v4.5.2

**Comment by mia-san** [comment]
any chance you're building your project in Any CPU?
Dicom.Native*.dll would not copied into your bin directory.
may https://github.com/fo-dicom/fo-dicom/issues/744#issuecomment-436322408 help ?
//

**Comment by chenxxcc** [comment]
> do you have VC2015 runtime installed?
> those DLLs are build against VC2015, if I'm not mistaken.
> //

I installed VC2015 runtime, but it still doesn't work
`[13:17:05.181] [Warning] No Dicom codecs were found after searching C:\JFAPP\PACSNiub\Release\Dicom.Native*.dll
`

**Comment by mia-san** [comment]
do you have Dicom.Native.dll only, or Dicom.Native64.dll too, in your executable directory ?
are you building your program in Any CPU, x86 or x64 ?
//

**Comment by chenxxcc** [comment]
> do you have Dicom.Native.dll only, or Dicom.Native64.dll too, in your executable directory ?
> are you building your program in Any CPU, x86 or x64 ?
> //
I'm sure Dicom. Native64. DLL and Dicom. Native. DLL exist.
I built any CPU on vs2015.
Strangely, only Winserver 2008 R2 does not work under VMware, and everything else is normal.

**Comment by BobSter3000** [comment]
I had a similar issue before when I forgot to change my build to Release instead of Debug.

**Comment by chenxxcc** [comment]
I tested several win Server 2008 R2 or prompted "No Dicom codecs were found after searching"

**Comment by gofal** [comment]
> I built any CPU on vs2015.
you have to build explicitly 32bit or 64bit.
See https://github.com/fo-dicom/fo-dicom/wiki/Native-codecs-on-.NET

**Comment by amoerie** [comment]
Closing this issue as it is properly documented, and there is not a lot more we can do to help consumers of this library.
