### ISSUE TITLE
Cannot render a DICOM file to System.Drawing.Bitmap under .NET Core

### ISSUE THREAD

**Issue by iberisoft** [fo-dicom/fo-dicom#877]
### Expected behavior

The following snippet should work:
```
        public byte[] GetData()
        {
            var image = new DicomImage(m_File.Dataset);
            using (var image2 = image.RenderImage())
            {
                using (var bitmap = image2.AsSharedBitmap())
                {
                    var stream = new MemoryStream();
                    bitmap.Save(stream, ImageFormat.Jpeg);
                    return stream.ToArray();
                }
            }
        }
```

I believe so because the AsSharedBitmap method of class Dicom.Imaging.WinFormsImageExtensions returns a System.Drawing.Bitmap object (System.Drawing.Common.dll). So this is fo-dicom team's decision to return bitmaps of this particular type.

### Actual behavior

However there is an exception when calling AsSharedBitmap.

**Dicom.Imaging.DicomImagingException: 'Cannot cast to 'Bitmap'; type must be assignable from 'Byte[]''**

### Steps to reproduce the behavior

Create a DicomFile object under .NET Core than call **.RenderImage().AsSharedBitmap()**.

### fo-dicom version and OS/platform

Version: 4.0.1.0
Platform: .NET Core on Windows 10

**Comment by iberisoft** [comment]
Let me share a sample console app reproducing the issue: https://gist.github.com/iberisoft/b09554654ed803de29b1d9402c271e48

Please run Program.cs under .NET Core to get the exception.

**Comment by iberisoft** [comment]
Resolved by calling the following code on top:

`ImageManager.SetImplementation(new WinFormsImageManager());`

The issue leads from the fact that Setup.GetDefaultPlatformInstance<ImageManager>() returns a RawImageManager object. It occurs because image managers do not search in Dicom.Drawing.dll, only in Dicom.Core.dll. Even searching in both assemblies, a RawImageManager object will still return because RawImageManager.IsDefault returns true, WinFormsImageManager.IsDefault returns false under .NET Core.

**Comment by gofal** [comment]
Yes, this intended behaviour. dependency to System.Drawing, linked in Dicom.Drawing, should be avoided by default, because on linux it only works if you have libc6-dev and libgdiplus installed. So the dependency should be set explicitly. You could also integrate other drawing libraries as ImageSharp or similar.

**Comment by iberisoft** [comment]
`Because on linux it only works if you have libc6-dev and libgdiplus installed`

Hello @gofal , I have found that `RenderImage` does fire an exception under Docker `Unable to load shared library 'libgdiplus' or one of its dependencies`. Do you have a manual on how to install the fo-dicom rendering requirements on Linux?

**Comment by gofal** [comment]
I personally do not use System.Drawing for rendering on services and in our application running on docker. Only in desktop WPF applications. In docker application the project references the nuget package fo-dicom.imaging.imagesharp. Then on Startup I am initializing with

new DicomSetupBuilder()
    .RegisterServices(s => s.AddFellowOakDicom().AddImageManager<ImageSharpImageManager>())
.Build();

And finally rendering is done by

var sharpimage = image.RenderImage().AsSharpImage();

further actions on the rendered image (croping, resizing, storing as jpeg,...) is very well documented here https://github.com/SixLabors/ImageSharp

**Comment by iberisoft** [comment]
Thank you @gofal, it works!
