### ISSUE TITLE
Patient ID

### ISSUE THREAD

**Issue by phelys** [fo-dicom/fo-dicom#881]
Sorry, but after try during 2 days, I give up. I need help here, please... to get the patient ID to use in print directory name. I'm using the Print SCP example. How I can do it? During assoaction, or when create film dicom files??... thanks....

**Comment by gofal** [comment]
Please explain in more detail what you need. But one thing to disappoint you in advance: PrintSCP never gets some patient context.
The print protocol is defined in that way that the print client sends the rendered pixeldata to the print server without patient-, study-, series- or image-information. So the printscp usually never gets data like patientname, patientids, studyinstanceuids etc.

Unless you use your own print client with your own print server and you add some private meta information with patientids to the communication, you cannot expect from a print client to send you the IDs.

**Comment by phelys** [comment]
Unfortunately the dicom viewer is from other company, I can't change de dicom tag files in the viewer or in film generator, however I will try do a crazy thing, maybe read the patient name and id in the image, but is very dangerous. I need do it, because I want creat a patient directory in server with patient name and, inside this, I wish save the images that physician sent to print for that patient.
