### ISSUE TITLE
compress a dcm file

### ISSUE THREAD

**Issue by unosbaghaie** [fo-dicom/fo-dicom#886]
How can I compress a dcm file in .net core (c# )?

**Comment by gofal** [comment]
See here for the list of supported TransferSyntaxes (=compressions):
https://github.com/fo-dicom/fo-dicom/wiki/Supported-Transfer-Syntaxes

Then you open a file, clone it with different transfersyntax, that is supported, and then save it again:

    var file = DicomFile.Open(@"test.dcm");
    var newFile = file.Clone(DicomTransferSyntax.JPEGProcess14SV1);
    newFile.Save(@"output.dcm");

**Comment by unosbaghaie** [comment]
ok thank you . Can I save it into memory not to file?

**Comment by unosbaghaie** [comment]
and when I compress the dcm file with `JPEG2000Lossless`, the rendered dcm file would be like this (white images)

![pacs1](https://user-images.githubusercontent.com/14114058/62190587-f641ae80-b386-11e9-8eed-2ad83e2ececc.png)

**Comment by gofal** [comment]
You can save it into memory. The DicomFile.Save method has an overload to accept a Stream as first parameter instead of a filename. There you can pass a MemoryStream for example

**Comment by gofal** [comment]
Hm, shouldn't be a white image. You did not get any exception when compressing the file? Can you tell more about the file. In NetCore only 8bit is supported for Jpeg2000Lossless. Is it a color or a grayscale image? what happes, if you window the white image, does it then change?

**Comment by unosbaghaie** [comment]
when I open the compressed file with a viewer, i get this error `index was outside the bounds of the array`


And my dicom files are like this 

![pacs2](https://user-images.githubusercontent.com/14114058/62264832-da95e100-b436-11e9-87cd-248f66ca055c.png)

**Comment by unosbaghaie** [comment]
When I save into MemoryStream 

```
 using (MemoryStream ms = new MemoryStream())
                    {
                        Dicom.Imaging.Codec.DicomCodecExtensions.Clone(f, ts).Save(ms);
                    }
```
I get this errror :
```
Activated	Event	Time	Duration	Thread
	Exception thrown: 'System.ArgumentOutOfRangeException' in CSJ2K.dll ("Specified argument was out of the range of valid values.") Exception thrown: 'System.ArgumentOutOfRangeException' in CSJ2K.dll ("Specified argument was out of the range of valid values.") Hyperlink: Activate Historical Debugging	3.29s		[10008] Main Thread 
```

**Comment by gofal** [comment]
hm, I have no idea at the moment. Maybe you could tell more, like which version of fo-dicom are you using, what is your build configuration. Does this happen with all images you are trying or only with some specific images. you have a net core project, so is your application running in windows or linux. have you also tried various compressions like Rle or jpegbaseline and does it always happen or only with specific compressions. etc etc

**Comment by unosbaghaie** [comment]
I am using fo-dicom.NetCore and fo-dicom.Drawing 4.0.2 
I publish my code for linux and then test it on Linux  OS Opensuse distribution. 
It happens with all dcm files for any patients.
I have tested it with JPEG2000Lossless, JPEG2000Lossy which it doesn't work and all images are white. 
But with RLELossless it works. and it compresses the Dcm files correctly. 

Why the case is this with JPEG2000Lossless, JPEG2000Lossy ?

**Comment by gofal** [comment]
Compression and portable project are a big issue. There is (sadly) no pure managed jpeg2k compression out there which supports everything that is required for DICOM. See here: https://github.com/fo-dicom/fo-dicom/wiki/Supported-Transfer-Syntaxes. fo-dicom uses native c++ builds, that only work on windows operation systems. Efferent is trying to make it work on linux and mac: https://github.com/Efferent-Health/Dicom-native. but mac is still work in progress.
There is a managed j2k implementation included in fo-dicom, but it only supports 8 Bit! Your sceenshot seems to be a default 12bit ct scan, isn't it?

**Comment by unosbaghaie** [comment]
Thanks for your answer. Yes it's a 12bit.

**Comment by gofal** [comment]
Then please give the implementation of Efferent-Health a try.

**Comment by unosbaghaie** [comment]
Sure, I let you know the result

**Comment by unosbaghaie** [comment]
I added this line to my startup.cs file 

```
Dicom.Imaging.Codec.TranscoderManager.SetImplementation(new Efferent.Native.Codec.NativeTranscoderManager());
```

And then tested with these four Transfers  "RLELossless"  "JPEG2000Lossless"   "JPEG2000Lossy"  "JPEGProcess1" . All of them work and the speed is really fast. 


With [Efferent.Native ](https://www.nuget.org/packages/Efferent.Native) is 5x  faster . My test was about compressing 461 dcm files. With Efferent.Native  it was less than 10 seconds but with fa-dicom 
 was more than 50 seconds. 

Thank you

**Comment by foroughi9300** [comment]
> when I open the compressed file with a viewer, i get this error `index was outside the bounds of the array`
> 
> And my dicom files are like this
> 
> ![pacs2](https://user-images.githubusercontent.com/14114058/62264832-da95e100-b436-11e9-87cd-248f66ca055c.png)

Hi,
Is it possible to tell me which DICOM viewer you are using ?
