### ISSUE TITLE
Issues with DicomTranscoder and JPEG encoding

### ISSUE THREAD

**Issue by Corvin666** [fo-dicom/fo-dicom#889]
Hey, folks. 

So I am experimenting with conversion of DICOM files between transfer syntaxes and I am seeing some weird behavior when it comes to transcoding JPEGs which looks like a bug to me. Hope someone can help me figure this out. 

### Expected behavior
When transcoding is made between JPEG Process 1 (1.2.840.10008.1.2.4.50) and Explicit VR Little Endian (1.2.840.10008.1.2.1) image comes out similar to original
![JPEGProcess1](https://user-images.githubusercontent.com/2642048/62335306-20c36280-b480-11e9-8e0f-d8639f96ab35.png)

### Actual behavior
Photometric Interpretation is not correctly set and image comes out corrupted:
![JPEGProcess1-ExplicitVRLittleEndian](https://user-images.githubusercontent.com/2642048/62335307-20c36280-b480-11e9-8ca4-ae6c7b022028.png)

### Steps to reproduce the behavior
1. I have the following code to generate an image:
```
public static DicomFile GenerateDicomFile(string studyInstanceUID, string seriesInstanceUID, string sopInstanceUID, string sopClassUID, string transferSyntax)
        {
            var rows = 512;
            var cols = 512;

            var dicomFile = new DicomFile(
                new DicomDataset(DicomTransferSyntax.ExplicitVRLittleEndian)
                {
                    { DicomTag.StudyInstanceUID, studyInstanceUID },
                    { DicomTag.SeriesInstanceUID, seriesInstanceUID },
                    { DicomTag.SOPInstanceUID, sopInstanceUID },
                    { DicomTag.SOPClassUID, sopClassUID },
                    { DicomTag.Rows, (ushort)rows },
                    { DicomTag.Columns, (ushort)cols },
                    { DicomTag.PhotometricInterpretation, PhotometricInterpretation.Monochrome2.Value },
                    { DicomTag.BitsAllocated, (ushort)8 },
                });

            var pixelData = DicomPixelData.Create(dicomFile.Dataset, true);
            pixelData.SamplesPerPixel = 1;
            pixelData.BitsStored = 8;
            pixelData.HighBit = 7;
            pixelData.PixelRepresentation = PixelRepresentation.Unsigned;

            var buffer = new MemoryByteBuffer(GetBytes(rows, cols));
            pixelData.AddFrame(buffer);

            if (transferSyntax != DicomTransferSyntax.ExplicitVRLittleEndian.UID.UID)
            {
                var transcoder =
                    new DicomTranscoder(dicomFile.Dataset.InternalTransferSyntax, DicomTransferSyntax.Parse(transferSyntax));
                dicomFile = transcoder.Transcode(dicomFile);
            }

            return dicomFile;
        }
```

Here, GetBytes just generates a pattern ensuring that entire color range is used.

I call this method like `var dicomFile = Generator.GenerateDicomFile(DicomTransferSyntax.JPEGProcess1.UID.UID)` and save the file.

I validate that InternalTransferSyntax is correctly set.

2. I open the saved file, transcode and save like so:

```
dicomFile = DicomFile.Open(filename);

var transcoder = new DicomTranscoder(
                dicomFile.Dataset.InternalTransferSyntax,
                DicomTransferSyntax.ExplicitVRLittleEndian);

dicomFile = transcoder.Transcode(dicomFile);
await dicomFile.SaveAsync("transcodes\\JPEGProcess1-ExplicitVRLittleEndian.dcm");
```

When I open the saved file in MicroDicom the following comes out:
![JPEGProcess1-ExplicitVRLittleEndian](https://user-images.githubusercontent.com/2642048/62335307-20c36280-b480-11e9-8ca4-ae6c7b022028.png)

It seems that PhotometricInterpretation is being incorrectly set to RGB which leads to corrupted rendering. 

I have tried all combinations of the supported transfer syntaxes (as per [this page](https://github.com/fo-dicom/fo-dicom/wiki/Supported-Transfer-Syntaxes)) and most of them come out properly using this process except for 
a) conversions from Process 1 and Process 2&4 all of which exhibit the issue described above
b) conversions from Process 1  and Process 2&4 to Process1, Process 2&4, JPEG2000 Lossless and JPEG 2000Lossy which throw exceptions "Cannot use component transformation on a image with less than three components" and "bogus input colorspace". This is probably related to issue above

I found more weird stuff with 16bit images, but let's start here :)

Thanks!

### fo-dicom version and OS/platform
fo-dicom 4.0.1
.NET Core 2.2

**Comment by gofal** [comment]
Could you please repeat your test with fo-dicom 4.0.2. I did not dig deeper into your description, but issue #836 came into my mind immeditelly, which was fixed with 4.0.2.

**Comment by Corvin666** [comment]
Hmm, in 4.0.2 

exact same code throws 
```
System.InvalidOperationException: Unable to JPEG encode image ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Dicom.Imaging.Codec.DicomJpegCodecImpl.Encode(DicomPixelData oldPixelData, DicomPixelData newPixelData, 
...
```
at
```
var transcoder =
                    new DicomTranscoder(dicomFile.Dataset.InternalTransferSyntax, DicomTransferSyntax.Parse(transferSyntax));
                dicomFile = transcoder.Transcode(dicomFile);
```

**Comment by mocsharp** [comment]
Having the same issue here with 4.0.2 using `{JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression}`.  It throws at `dicomFile.Clone`
```
Exception has occurred: CLR/System.InvalidOperationException
An exception of type 'System.InvalidOperationException' occurred in Dicom.Core.dll but was not handled in user code: 'Unable to JPEG encode image' & `{JPEG Extended (Process 2 & 4): Default Transfer Syntax for Lossy JPEG 12 Bit Image Compression (Process 4 only)}`

 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 System.NullReferenceException : Object reference not set to an instance of an object.
   at Dicom.Imaging.Codec.DicomJpegCodecImpl.Encode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomJpegParams parameters)
```

**Comment by Corvin666** [comment]
> Workaround for me, since I'm using this to generate test files, I remove PixeLdata from dataset, clone it with the new transfer syntax and then set the pixel data.

If I understand it correctly, this won't help you in real world - you will have to encode pixeldata per the transfer syntax which would invoke same codec as Clone invokes. The way you are doing it - it won't throw the exception, but the actual pixel data in your resulting file will not be parseable by any viewer.

**Comment by mocsharp** [comment]
DicomJpegCodeImpl.cs:169
```
 newPixelData.PhotometricInterpretation =
                           parameters.SampleFactor == DicomJpegSampleFactor.SF422
                           ? PhotometricInterpretation.YbrFull422 : PhotometricInterpretation.YbrFull;
```

`parameters` is null by default, the line above shall check for nullness.

**Comment by EdwardMarcus** [comment]
Recently after the TS conversion to JPEG, I had to manually alter the photometric interpretation. This  might have been fixed in the latest build.

**Comment by paulchitsonultromics** [comment]
Worth noting the the viewer being used is MicroDICOM.  This mis-reports the photometric interpretation as RGB.  I would check the DICOM tags using a tool like the DCMTK dcmdump utility, as this will show you the true contents of the PhotometricInterpretation tag.

**Comment by EdwardMarcus** [comment]
Hi Paul,

I appreciate your response.

Yes I have noticed – that with transfer syntax changes, that the Photometric interpretation of a new syntax needs to be explicitly set.

Best Regards,

Ed

**Comment by gofal** [comment]
so is this still an open issue in version 5.0.3?

**Comment by gofal** [comment]
Encoding and Decoding has been moved to Efferent.
in current state of developement branch, in PR #1591 a bug was fixed, when the wrong PhotometricInterpretation was applied when rendering a encoded image. 
This bug should be fixed now.

But if there is still an issue with the latest version of fo-dicom, then please feel free to reopen this issue and provide actual informations.

**Comment by EdwardMarcus** [comment]
Hello Reinhard,

Thank you for this simplifying update to the photometric interpretation feature.

My best,
________________________________
