### ISSUE TITLE
Imaging Excpetion

### ISSUE THREAD

**Issue by EdwardMarcus** [fo-dicom/fo-dicom#890]
I am not sure if this is a programming or toolkit issue:

I was wondering if there is a simple way to generally suppress the DicomImagingExceptions  from displaying as a dialog box messages, and to instead implement a programmatic handling of  the exceptions ?

Thank you

**Comment by gofal** [comment]
fo-dicom has so user interface and does never show any message boxes.
If your application calls some code which throws an exception and you do not catch this exception (within a try-catch-block) then your application has an Unhandled exception and shows this messagebox.
You can either put your code into try-catch-blocks and then handle the exceptions appropriately, Or you can attach globally on AppDomain.CurrentDomain.UnhandledException event and handle all the exceptions (not only the DicomExceptions) there.

**Comment by EdwardMarcus** [comment]
Thank you for this valuable information.

I will look into your suggestions.


Edward Marcus MSc

Principal Research Software Application Engineer
Children’s Hospital Boston

9 Hope St. Waltham, MA. 02453
(781) 216-2532
Ed.Marcus@cardio.chboston.org

**Comment by gofal** [comment]
Close this due to inactivity. If there is still some problem or any update on the issue, please reopen this issue again.
