### ISSUE TITLE
Update DICOM dictionary

### ISSUE THREAD

**Issue by anders9ustafsson** [fo-dicom/fo-dicom#9]
The dictionaries of DICOM tags, UID:s etc. are outdated. The current *DICOM Dictionary.xml* file relates to *DICOM Standard 2011*.

Dictionaries should be updated to reflect the most recent DICOM standard.

**Comment by hdesouky** [comment]
I i remember correctly there is a Dictionary generator in the library that parse the tags from the standards to create new dictionary.

I am not sure how this process can be done

**Comment by anders9ustafsson** [comment]
I remember the tool being mentioned at one time, but I don't think it ever got included in the repo. Now Colby promised on Gitter to provide us with the latest dictionary, so that would really simplify things for now.

But eventually, I think we should consider a solution where we have persistent control. @rickardraysearch has developed a tool for extracting the dictionary from the official DICOM Standard XML documents. He has kindly provided me with pull requests so that I have been able to include it in my portable *cureos* fork, see [here](https://github.com/cureos/fo-dicom/tree/portable/Tools/DictionaryGenerators). Rickard's solution even generates C# code to include in the class library instead of reading the gzipped XML file, which I also think is a good enhancement.

I don't want to rush in Rickard's solution right now since it is quite a substantial change. I think it would be better to create a new stable release with Colby's updated XML file, and only after that start looking at Rickard's (or potentially other) solutions for a more flexible dictionary generation in the future.

Comments?

**Comment by IanYates** [comment]
@anders9ustafsson :+1: 
Let's get the new XML off Colby and in the meantime perhaps get a PR or a branch underway which uses the newer approach.  It's nice that it uses the standard XML files directly.

**Comment by hdesouky** [comment]
Any updates from colby ?
