### ISSUE TITLE
TryGetSingleValue/TryGetValue does not find DicomPersonName in dataset

### ISSUE THREAD

**Issue by ddebrecenijr** [fo-dicom/fo-dicom#902]
### Expected behavior
TryGetSingleValue<DicomPersonName>(DicomTag.PatientName, out var personName) returns true with personName being of type DicomPersonName

### Actual behavior
Returns false and personName is null

Obsolete use of Get<DicomPersonName>(DicomTag.PatientName) works as expected.

### Steps to reproduce the behavior
Create dataset with DicomTag.PatientName.
Try to retrieve value with TryGetValue/TryGetSingleValue

### fo-dicom version and OS/platform
fo-dicom v4.0.2
OS: Windows 10 Pro 1903

**Comment by davidsybren** [comment]
Hi @ddebrecenijr, I'm not sure if i am correct but I think that TryGetSingleValue (and TryGetValue) is intended to return value types only. Try to use `GetDicomItem<DicomPersonName>(DicomTag.PatientName)` instead.
