### ISSUE TITLE
Certificate used for DICOM over TLS should be more precisely configurable

### ISSUE THREAD

**Issue by SrividyaTR** [fo-dicom/fo-dicom#903]
### Expected behavior
It should be possible to precisely specify which Certificate is to be used for DICOM over TLS.
It might be better to use certificate Thumbprint which is guaranteed to be unique (rather than the certificate subjectName).
This is needed especially when there are multiple certificates that have the same subjectName (for eg: multiple certificates "IssuedTo" the 'HostName' of the machine by different "Issuers")

### Actual behavior
Currently, the certificate subjectName can be passed as input and the first certificate that matches that subjectName from LocalSystem->Personal store is used for DICOM over TLS

### Steps to reproduce the behavior
var dicomServer = DicomServer.Create<CStoreSCP>(port, "myHostName.myDomainName")

### fo-dicom version and OS/platform
4.0.2 Windows/x64

**Comment by amoerie** [comment]
Will be fixed by #1418
