### ISSUE TITLE
Choose the correct of  2 or more structured report if they exist

### ISSUE THREAD

**Issue by saschke** [fo-dicom/fo-dicom#904]
This is a general question, I hope you can help me. 

I read structured reports of ultrasound studies (echo) from a dicom server and use the data for extended reporting. 

I realized that some studies have more than one SR and took the youngest one (studyInstanceDate/seriesInstantDate/ContentDate (and time))

All works find but for some reason these younger SRs can be empty (only contain patient and main level tags) and the data I need sits only in the “older” report. 

Is there a way to found out how many measurements a SR “has” during the CFindRequest on ImageLevel (SR Level)?
Or does anyone have another idea how to know what SR to use if more that one exists?

I use the current 4.02 version of FO-Dicom. 

Thank you for any help!

#886

**Comment by gofal** [comment]
I'm affraid not. Theoretically in a cfind you can send filter for any dicom tag. The question is, if the PACS archive support the tag you are querying. You have to read the Dicom Conformance Statement of the PACS. 
I would strongly recommend to receive every SR that is available and parse all of then to get the measurements.

**Comment by saschke** [comment]
Thank you. I was affraid that is the only way. So I will have to go there ...

-Schlomo
