### ISSUE TITLE
Adding fo-dicom NuGet package to .NET Framework C# project in SDK format is always out-dated

### ISSUE THREAD

**Issue by vbaderks** [fo-dicom/fo-dicom#908]
### Expected behavior
.csproj file is up to date when project is build once:

### Actual behavior
Visual Studio is unable to cache the project status and build the project every time.

### Steps to reproduce the behavior
1) Create a .NET core console application 
2) Update the <TargetFramework> to net48 in the .csproj file
3) Add a package reference to the NuGet package fo-dicom
4) Create a Directory.Build.props file 1 directory up with the property
  <PropertyGroup>
    <OutDir>$(MSBuildThisFileDirectory)bin\$(Configuration)\$(Platform)\</OutDir>
  </PropertyGroup>

### fo-dicom version and OS/platform
fo-dicom 4.0.2
Visual Studio 16.2.3
Msbuild 16.2.37902+b5aaefc9f

Notes:
- The "classic" .csproj format works fine.
- <TargetFramework>netcoreapp2.2<TargetFramework> works also fine
- Removing <OutDir> seems to also solve the problem

It is unclear to me if this is a problem in the fo-dicom NuGet package or a generic VS\MSbuild problem.

**Comment by vbaderks** [comment]
A workaround for the problem is to modify the Directory.Build.props file:

Replace <OutDir> with a static path, select with a condition:

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <OutDir>$(MSBuildThisFileDirectory)bin\Release\x86\</OutDir>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <OutDir>$(MSBuildThisFileDirectory)bin\Debug\x86\</OutDir>
  </PropertyGroup>

and add:

<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>

This will ensure that Visual Studio can cache the build status and doesn't trigger msbuild to build the project. Still unclear if this is fo-dicom NuGet package problem or a general VS/msbuild problem.

**Comment by gofal** [comment]
I assume, that is fine now. Close this due to inactivity. Please feel free to reopen this issue, if there is still an issue.
