### ISSUE TITLE
Adding multiple child sequences of the same type to a parent sequence 

### ISSUE THREAD

**Issue by LeeTurl** [fo-dicom/fo-dicom#918]
How is it possible to add multiple sequences of the same type to a parent sequence.

For example I need to add mulltiple ReferencedInstanceSequence's to a ReferencedSeriesSequence

Any help much appreciated.

Using 4.0.2

**Comment by gofal** [comment]
What have you tried so far?
You can create a DicomSequence with several items directly via constructor, or you can iterate and call .Items.Add(..) several times. And it does not matter if the items you add to a DicomSequence are "simple" items or if they are nested DicomSequences.

**Comment by gofal** [comment]
here some pseudo-code for iterating:

            var seqReferencedSeres = new DicomSequence(DicomTag.ReferencedSeriesSequence);
            foreach (var serie in lstSeries)
            {
                var seqReferencedInstances = new DicomSequence(DicomTag.ReferencedInstanceSequence);
                // fill content into seqReferencInstances...

                seqReferencedSeres.Items.Add(new DicomDataset(seqReferencedInstances));
            }

**Comment by gofal** [comment]
Close this issue due to inactivity.
If my suggestions did not help or there are any other problems, please reopen this issue again.
