### ISSUE TITLE
Image Processing

### ISSUE THREAD

**Issue by khaledyasser95** [fo-dicom/fo-dicom#919]
So after testing fo-dicom my dad says Charruasoft-Printscp in printing quality is better as he can Process the image (Gamma,Contrast,sharpness,smooth....)

So Can we implement something like this in the printscp?
Where in the code and the method?

![image](https://user-images.githubusercontent.com/26413162/64481642-8d005700-d1e0-11e9-9cf3-7f36cb53e81f.png)

**Comment by gofal** [comment]
The domain of fo-dicom is to implement DICOM standard. If you take a look at the fo-dicom-samples repository you will find the Print SCP project. There the DICOM communication is implemented. The class `PrintJob.cs` holds most of the information.

But if you want to do some post-processing like gamma, contrast, saturation etc. Or if you want to get the most out of windows-printing, then I recomment do use imageprocessing-libraries like aforgenet.com.

**Comment by XMAN274** [comment]
> 
> 
> The domain of fo-dicom is to implement DICOM standard. If you take a look at the fo-dicom-samples repository you will find the Print SCP project. There the DICOM communication is implemented. The class `PrintJob.cs` holds most of the information.
> 
> But if you want to do some post-processing like gamma, contrast, saturation etc. Or if you want to get the most out of windows-printing, then I recomment do use imageprocessing-libraries like aforgenet.com.

yeah i used the Aforge Library , but the problem in the gamma correction , it give error when i use it 
but the contrast and brightness working fine
the problem in the gamma correction , i think it about the filter accepts 8 bpp grayscale and 24 bpp color images for processing
any help ??

**Comment by khaledyasser95** [comment]
> 
> 
> > The domain of fo-dicom is to implement DICOM standard. If you take a look at the fo-dicom-samples repository you will find the Print SCP project. There the DICOM communication is implemented. The class `PrintJob.cs` holds most of the information.
> > But if you want to do some post-processing like gamma, contrast, saturation etc. Or if you want to get the most out of windows-printing, then I recomment do use imageprocessing-libraries like aforgenet.com.
> 
> yeah i used the Aforge Library , but the problem in the gamma correction , it give error when i use it
> but the contrast and brightness working fine
> the problem in the gamma correction , i think it about the filter accepts 8 bpp grayscale and 24 bpp color images for processing
> any help ??

Sorry Sir I have a question

Where should I implement the function to change the contrast for example in the PrintJob class?
Do I need to convert the Filmbox to a picture then use Aforge to reedit the image then reconvert it again to filmbox?

Thanks

**Comment by gofal** [comment]
No, you dont need to convert it back to a filmbox.
fo-dicom processes all the N-Set and N-Create messages and build up the list of FilmBoxes which all of them contain a list of ImageBoxes and additional properties. 
Then it is up to you what you want to do with it. The sample in fo-dicom-samples repository just prints to xps page. The method `_currentFilmBox.Print` takes a `Graphics` object as parameter and draws there. This Graphis is provided by windows while printing.

You could do for example the following. In PrintJob.DoPrint() you could iterate all the FilmBoxes and manipulate all the raw pixel data.

Or you could change PrintJob.OnPrintPage and instead of directly rendering on e.Graphics you could create a new Bitmap, create a Graphics object from this new bitmap, then render the _currentFilmBox on this new graphics object. This rendered image can then be manipulated via Aforge etc. And then draw this manipulated bitmap on the e.Graphics  to the printer.

**Comment by gofal** [comment]
I close this issue due to inactivity.
If my suggestion did not help, or if you are still facing any problems, please feel free to reopen this issue again.

**Comment by andersoncav** [comment]
sorry to bother you, I've been trying to solve this problem for several days;
Please explain with an example code?
I'm using the following code in C #

 Bitmap im = new Bitmap(200,100);
 Graphics flagGraphics = Graphics.FromImage(im);
 var image = new DicomImage(_currentFilmBox);
 im = image.RenderImage().As<Bitmap>();

 Bitmap adjustedImage = this.ajustabrilhocontrasteegamabmp(im, 1.0f, 2.0f, 1.0f);

adjustedImage.Dispose();
currentFilmBox.Print(adjustedImage, e.MarginBounds, 100);

**Comment by andersoncav** [comment]
private void OnPrintPage(object sender, PrintPageEventArgs e)
      {
                
            Bitmap im = new Bitmap(200,100);
            Graphics flagGraphics = Graphics.FromImage(im);
            var image = new DicomImage(_currentFilmBox);
            
            im = image.RenderImage().As<Bitmap>();


            Bitmap adjustedImage = this.ajustabrilhocontrasteegamabmp(im, 1.0f, 2.0f, 1.0f);

              adjustedImage.Dispose();

             _currentFilmBox.Print(adjustedImage, e.MarginBounds, 100);

            _currentFilmBox = null;
         _currentPage++;

         e.HasMorePages = _currentPage < FilmBoxFolderList.Count;
      }

**Comment by gofal** [comment]
I do not know what exactly your problem is. You create an adjustedImage, then call `Dispose()` to this adjusted image, which clears all its content, and then you want to print this disposed adjustedImage?

**Comment by andersoncav** [comment]
Good afternoon,
I need to control the brightness and contrast of the image before printing

**Comment by gofal** [comment]
fo-dicom gives you the rendered image in the line `im = image.RenderImage().As<Bitmap>();`. Thats the spot where fo-dicom is done. Now the question is how to bring the Bitmap on the printer. This you can read in MSDN or other GDI related forums. If you have issues about the enhancement of the Bitmap using Aforge, then please ask in AForge forum.

**Comment by andersoncav** [comment]
public Bitmap ajustabrilhocontrasteegama2(Graphics imagem2, float brightness, float contrast, float gamma)
        {


            Bitmap originalImage;
            Bitmap adjustedImage;

            Bitmap imagem = new Bitmap(100, 100, imagem2);

            originalImage = imagem;
            adjustedImage = imagem;

            float adjustedBrightness = brightness - 1.0f;
            // create matrix that will brighten and contrast the image
            float[][] ptsArray ={
        new float[] {contrast, 0, 0, 0, 0}, // scale red
        new float[] {0, contrast, 0, 0, 0}, // scale green
        new float[] {0, 0, contrast, 0, 0}, // scale blue
        new float[] {0, 0, 0, 1.0f, 0}, // don't scale alpha
        new float[] {adjustedBrightness, adjustedBrightness, adjustedBrightness, 0, 1}};

            ImageAttributes imageAttributes = new ImageAttributes();
            imageAttributes.ClearColorMatrix();
            imageAttributes.SetColorMatrix(new ColorMatrix(ptsArray), ColorMatrixFlag.Default, ColorAdjustType.Bitmap);
            imageAttributes.SetGamma(gamma, ColorAdjustType.Bitmap);
            Graphics g = Graphics.FromImage(adjustedImage);
            g.DrawImage(originalImage, new Rectangle(0, 0, adjustedImage.Width, adjustedImage.Height)
                , 0, 0, originalImage.Width, originalImage.Height,
                GraphicsUnit.Pixel, imageAttributes);

            return adjustedImage;

        }

**Comment by andersoncav** [comment]
where do I put this code
im = image.RenderImage().As<Bitmap>();

**Comment by gofal** [comment]
I took this line from your code sample above.

I do not know what your code looks like. But If you started using the Print SCP project from fo-dicom-samples repository, then there is the `PrintJob` class. This class also implements printing on a windows printer using GDI. There is the private method `OnPrintPage(object sender, PrintPageEventArgs e)` which is called by windows printer driver for every page to print. The sample application uses the `e.Graphics` object to render the image there. 

      private void OnPrintPage(object sender, PrintPageEventArgs e)
      {
         _currentFilmBox.Print(e.Graphics, e.MarginBounds, 100);

         _currentFilmBox = null;
         _currentPage++;

         e.HasMorePages = _currentPage < FilmBoxFolderList.Count;
      }

instead now you create a Graphics-object from an Bitmap, render the filmbox on this Bitmap, and then you can do your adjustations and finally write the Bitmap to e.Graphics.

      private void OnPrintPage(object sender, PrintPageEventArgs e)
      {
         var bmp = new Bitmap(e.PageBounds.Width, e.PageBounds.Height);
         using (var bmpGraphics = Graphics.FromImage(bmp))
         {
            _currentFilmBox.Print(bmpGraphics, e.MarginBounds, 100);
         }

         // then here you do your manipulations on bmp

         // now draw your adjusted bitmap on the printer
         e.Graphics.DrawImage(bmp, 0, 0);

         _currentFilmBox = null;
         _currentPage++;

         e.HasMorePages = _currentPage < FilmBoxFolderList.Count;
      }

I have of course not tested it now. It might be that you have to do some changes, like you should not draw the bmp to point 0/0 but to e.MarginBound.X/e.MarginBound.Y etc. But you will see this when the image is not centered on the page. etc...

**Comment by andersoncav** [comment]
Thank you very much, God enlighten you ... thank you ....

**Comment by andersoncav** [comment]
Sorry to bother you again ...
I used what you explained above
but the image quality has decreased.
is there a function that maintains the image quality?

**Comment by andersoncav** [comment]
in this part the image reduces the resolution
using (var bmpGraphics = Graphics.FromImage(bmp))

**Comment by megarockss** [comment]
Please @gofal need help with this error.

Starting print SCP server with AET: PRINTSCP on port 8000
Press any key to stop the service
[INFO] WEASIS_AE <- Association request:
Calling AE Title:       WEASIS_AE
Called AE Title:        PRINTSCP
Remote host:            192.168.88.169
Remote port:            55104
Implementation Class:   Implementation Class UID [1.2.40.0.13.1.3]
Implementation Version: dcm4che-5.24.2
Maximum PDU Length:     16378
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] Received association request from AE: WEASIS_AE with IP: 192.168.88.169
[INFO] Accepted association request from WEASIS_AE
[INFO] WEASIS_AE -> Association accept:
Calling AE Title:       WEASIS_AE
Called AE Title:        PRINTSCP
Remote host:            192.168.88.169
Remote port:            55104
Implementation Class:   Implementation Class UID [1.2.40.0.13.1.3]
Implementation Version: dcm4che-5.24.2
Maximum PDU Length:     16378
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Basic Grayscale Print Management Meta SOP Class
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] WEASIS_AE <- N-Create request [1]
[INFO] Create new film session 2.25.43369002965375377547447458353885123418
[INFO] WEASIS_AE -> N-Create response [1]: Success
[INFO] WEASIS_AE <- N-Create request [2]
[INFO] Applying display format STANDARD\1,1 for film box Unknown [2.25.193497880471278022723684129141826792891]
[INFO] Created new film box 2.25.193497880471278022723684129141826792891
[INFO] WEASIS_AE -> N-Create response [2]: Success
[INFO] WEASIS_AE <- N-Set request [3]
[INFO] Set image box 2.25.193497880471278022723684129141826792891.1
[INFO] WEASIS_AE -> N-Set response [3]: Success
[INFO] WEASIS_AE <- N-Action request [4]
                Action Type:    0001
[INFO] Creating new print job for film box 2.25.193497880471278022723684129141826792891
[INFO] Print Job 147962443662677333917205416075102238014 Status Pending: QUEUED
[INFO] WEASIS_AE -> N-Action response [4]: Success
                Action Type:    0001
[INFO] Print Job 147962443662677333917205416075102238014 Status Printing: QUEUED
[INFO] WEASIS_AE <- N-Delete request [5]
[INFO] WEASIS_AE -> N-Delete response [5]: Success
[INFO] WEASIS_AE <- N-Delete request [6]
[INFO] WEASIS_AE -> N-Delete response [6]: Success
[INFO] WEASIS_AE <- Association release request
[INFO] WEASIS_AE -> Association release response
[INFO] Connection closed
[INFO] Print Job 147962443662677333917205416075102238014 Status Printing: NORMAL
Error:FellowOakDicom.Imaging.DicomImagingException: Cannot cast to 'Image'; type must be assignable from 'Byte[]'
   em FellowOakDicom.Imaging.ImageBase`1.As[T]()
   em FellowOakDicom.Printing.ImageBoxExtensions.Print(ImageBox imageBox, Graphics graphics, RectF box, Int32 imageResolution)
   em FellowOakDicom.Printing.FilmBoxExtensions.Print(FilmBox filmBox, Graphics graphics, Rectangle marginBounds, Int32 imageResolution)
   em FellowOakDicom.Samples.Printing.PrintJob.OnPrintPage(Object sender, PrintPageEventArgs e) na D:\Leandro\fo-dicom-samples-master\Desktop\Print SCP\PrintJob.cs:linha 315
   em System.Drawing.Printing.PrintDocument.OnPrintPage(PrintPageEventArgs e)
   em System.Drawing.Printing.PrintDocument._OnPrintPage(PrintPageEventArgs e)
   em System.Drawing.Printing.PrintController.PrintLoop(PrintDocument document)
   em System.Drawing.Printing.PrintController.Print(PrintDocument document)
   em System.Drawing.Printing.PrintDocument.Print()
   em FellowOakDicom.Samples.Printing.PrintJob.DoPrint() na D:\Leandro\fo-dicom-samples-master\Desktop\Print SCP\PrintJob.cs:linha 280
[ERROR] Print Job 147962443662677333917205416075102238014 Status Failure: UNKNOWN

**Comment by megarockss** [comment]
I tried to change it to bmp but the error persists, I must be changing the wrong place in the code.

`
// Copyright (c) 2012-2022 fo-dicom contributors.
// Licensed under the Microsoft Public License (MS-PL).

using FellowOakDicom.Log;
using FellowOakDicom.Printing;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Printing;
using System.IO;
using System.Linq;
using System.Threading;

namespace FellowOakDicom.Samples.Printing
{
    public class StatusUpdateEventArgs : EventArgs
    {
        public ushort EventTypeId { get; private set; }
        public string ExecutionStatusInfo { get; private set; }
        public string FilmSessionLabel { get; private set; }
        public string PrinterName { get; private set; }

        public StatusUpdateEventArgs(
            ushort eventTypeId,
            string executionStatusInfo,
            string filmSessionLabel,
            string printerName)
        {
            EventTypeId = eventTypeId;
            ExecutionStatusInfo = executionStatusInfo;
            FilmSessionLabel = filmSessionLabel;
            PrinterName = printerName;
        }
    }

    public enum PrintJobStatus : ushort
    {
        Pending = 1,

        Printing = 2,

        Done = 3,

        Failure = 4
    }


    public class PrintJob : DicomDataset
    {
        #region Properties and Attributes

        public bool SendNEventReport { get; set; }

        public Guid PrintJobGuid { get; private set; }

        public IList<string> FilmBoxFolderList { get; private set; }

        public Printer Printer { get; private set; }

        public PrintJobStatus Status { get; private set; }

        public string PrintJobFolder { get; private set; }

        public string FullPrintJobFolder { get; private set; }

        public Exception Error { get; private set; }

        public string FilmSessionLabel { get; private set; }

        private int _currentPage;

        private FilmBox _currentFilmBox;

        /// <summary>
        /// Print job SOP class UID
        /// </summary>
        public readonly DicomUID SOPClassUID = DicomUID.PrintJob;

        /// <summary>
        /// Print job SOP instance UID
        /// </summary>
        public DicomUID SOPInstanceUID { get; private set; }

        /// <summary>
        /// Execution status of print job.
        /// </summary>
        /// <remarks>
        /// Enumerated Values:
        /// <list type="bullet">
        /// <item><description>PENDING</description></item>
        /// <item><description>PRINTING</description></item>
        /// <item><description>DONE</description></item>
        /// <item><description>FAILURE</description></item>
        /// </list>
        /// </remarks> 
        public string ExecutionStatus
        {
            get => GetSingleValueOrDefault(DicomTag.ExecutionStatus, string.Empty);
            set => AddOrUpdate(DicomTag.ExecutionStatus, value.ToUpperInvariant());
        }

        /// <summary>
        /// Additional information about Execution Status (2100,0020).
        /// </summary>
        public string ExecutionStatusInfo
        {
            get => GetSingleValueOrDefault(DicomTag.ExecutionStatusInfo, string.Empty);
            set => AddOrUpdate(DicomTag.ExecutionStatusInfo, value.ToUpperInvariant());
        }

        /// <summary>
        /// Specifies the priority of the print job.
        /// </summary>
        /// <remarks>
        /// Enumerated values:
        /// <list type="bullet">
        ///     <item><description>HIGH</description></item>
        ///     <item><description>MED</description></item>
        ///     <item><description>LOW</description></item>
        /// </list>
        /// </remarks>
        public string PrintPriority
        {
            get => GetSingleValueOrDefault(DicomTag.PrintPriority, "MED");
            set => AddOrUpdate(DicomTag.PrintPriority, value);
        }

        /// <summary>
        /// Date/Time of print job creation.
        /// </summary>
        public DateTime CreationDateTime
        {
            get => this.GetDateTime(DicomTag.CreationDate, DicomTag.CreationTime);
            set
            {
                AddOrUpdate(DicomTag.CreationDate, value);
                AddOrUpdate(DicomTag.CreationTime, value);
            }
        }

        /// <summary>
        /// User defined name identifying the printer.
        /// </summary>
        public string PrinterName
        {
            get => GetSingleValueOrDefault(DicomTag.PrinterName, string.Empty);
            set => AddOrUpdate(DicomTag.PrinterName, value);
        }

        /// <summary>
        /// DICOM Application Entity Title that issued the print operation.
        /// </summary>
        public string Originator
        {
            get => GetSingleValueOrDefault(DicomTag.Originator, string.Empty);
            set => AddOrUpdate(DicomTag.Originator, value);
        }

        public ILogger Log { get; private set; }


        public event EventHandler<StatusUpdateEventArgs> StatusUpdate;

        #endregion

        #region Constructors

        /// <summary>
        /// Construct new print job using specified SOP instance UID. If passed SOP instance UID is missing, new UID will
        /// be generated
        /// </summary>
        /// <param name="sopInstance">New print job SOP instance uID</param>
        public PrintJob(DicomUID sopInstance, Printer printer, string originator, ILogger log)
            : base()
        {
            Log = log;

            SOPInstanceUID = string.IsNullOrEmpty(sopInstance?.UID) ? DicomUID.Generate() : sopInstance;

            Add(DicomTag.SOPClassUID, SOPClassUID);
            Add(DicomTag.SOPInstanceUID, SOPInstanceUID);

            Printer = printer ?? throw new ArgumentNullException(nameof(printer));

            Status = PrintJobStatus.Pending;

            PrinterName = Printer.PrinterAet;

            Originator = originator;

            if (CreationDateTime == DateTime.MinValue)
            {
                CreationDateTime = DateTime.Now;
            }

            PrintJobFolder = SOPInstanceUID.UID;

            var receivingFolder = Path.Combine(Environment.CurrentDirectory, "PrintJobs");

            FullPrintJobFolder = Path.Combine(receivingFolder, PrintJobFolder);

            FilmBoxFolderList = new List<string>();
        }

        #endregion

        #region Printing Methods

        public void Print(IList<FilmBox> filmBoxList)
        {
            try
            {
                Status = PrintJobStatus.Pending;

                OnStatusUpdate("QUEUED");

                var printJobDir = new DirectoryInfo(FullPrintJobFolder);
                if (!printJobDir.Exists)
                {
                    printJobDir.Create();
                }

                DicomFile file;
                int filmsCount = FilmBoxFolderList.Count;
                for (int i = 0; i < filmBoxList.Count; i++)
                {
                    var filmBox = filmBoxList[i];
                    var filmBoxDir = printJobDir.CreateSubdirectory(string.Format("F{0:000000}", i + 1 + filmsCount));

                    file = new DicomFile(filmBox.FilmSession);
                    file.Save(Path.Combine(filmBoxDir.FullName, "FilmSession.dcm"));

                    FilmBoxFolderList.Add(filmBoxDir.Name);
                    filmBox.Save(filmBoxDir.FullName);
                }

                FilmSessionLabel = filmBoxList.First().FilmSession.FilmSessionLabel;

                var thread = new Thread(new ThreadStart(DoPrint))
                {
                    Name = $"PrintJob {SOPInstanceUID.UID}",
                    IsBackground = true
                };
                thread.Start();
            }
            catch (Exception ex)
            {
                Error = ex;
                Status = PrintJobStatus.Failure;
                OnStatusUpdate("UNKNOWN"); // The exception may be analyzed and a more proper code as defined in "Table C.13.9.1-1. Defined Terms for Printer and Execution Status Info" may be used
                DeletePrintFolder();
            }
        }

        private void DoPrint()
        {
            PrintDocument printDocument = null;
            try
            {
                Status = PrintJobStatus.Printing;
                OnStatusUpdate("QUEUED");

                var printerSettings = new PrinterSettings
                {
                    PrinterName = "HP2734C8",
                    //PrintToFile = true,
                    //PrintFileName = Path.Combine(FullPrintJobFolder, SOPInstanceUID.UID + ".xps")
                };

                printDocument = new PrintDocument
                {
                    PrinterSettings = printerSettings,
                    DocumentName = Thread.CurrentThread.Name,
                    PrintController = new StandardPrintController()
                };

                printDocument.QueryPageSettings += OnQueryPageSettings;
                printDocument.PrintPage += OnPrintPage;

                printDocument.Print();

                Status = PrintJobStatus.Done;

                OnStatusUpdate("NORMAL");
            }
            catch (Exception e)
            {
                Console.WriteLine("Error:"+e );
                Status = PrintJobStatus.Failure;
                OnStatusUpdate("UNKNOWN"); // The exception may be analyzed and a more proper code as defined in "Table C.13.9.1-1. Defined Terms for Printer and Execution Status Info" may be used
            }
            finally
            {
                if (printDocument != null)
                {
                    //dispose the print document and unregister events handlers to avoid memory leaks
                    printDocument.QueryPageSettings -= OnQueryPageSettings;
                    printDocument.PrintPage -= OnPrintPage;
                    printDocument.Dispose();
                }
            }
        }

        private void OnPrintPage(object sender, PrintPageEventArgs e)
        {
            /* _currentFilmBox.Print(e.Graphics, e.MarginBounds, 100);

             _currentFilmBox = null;
             _currentPage++;

             e.HasMorePages = _currentPage < FilmBoxFolderList.Count;*/
            var bmp = new Bitmap(e.PageBounds.Width, e.PageBounds.Height);
            using (var bmpGraphics = Graphics.FromImage(bmp))
            {
                _currentFilmBox.Print(bmpGraphics, e.MarginBounds, 100);
                Console.WriteLine("teste");
            }

            // then here you do your manipulations on bmp

            // now draw your adjusted bitmap on the printer
            e.Graphics.DrawImage(bmp, 0, 0);

            _currentFilmBox = null;
            _currentPage++;

            e.HasMorePages = _currentPage < FilmBoxFolderList.Count;
        }

        private void OnQueryPageSettings(object sender, QueryPageSettingsEventArgs e)
        {
            OnStatusUpdate($"NORMAL");
            var filmBoxFolder = Path.Combine(FullPrintJobFolder, FilmBoxFolderList[_currentPage]);
            var filmSession = FilmSession.Load(Path.Combine(filmBoxFolder, "FilmSession.dcm"));
            _currentFilmBox = FilmBox.Load(filmSession, filmBoxFolder);

            e.PageSettings.Margins.Left = 25;
            e.PageSettings.Margins.Right = 25;
            e.PageSettings.Margins.Top = 25;
            e.PageSettings.Margins.Bottom = 25;

            e.PageSettings.Landscape = _currentFilmBox.FilmOrientation == "LANDSCAPE";
        }

        private void DeletePrintFolder()
        {
            var folderInfo = new DirectoryInfo(FullPrintJobFolder);
            if (folderInfo.Exists)
            {
                folderInfo.Delete(true);
            }
        }

        #endregion

        #region Notification Methods

        protected virtual void OnStatusUpdate(string info)
        {
            ExecutionStatus = Status.ToString();
            ExecutionStatusInfo = info;

            if (Status != PrintJobStatus.Failure)
            {
                Log.Info("Print Job {0} Status {1}: {2}", SOPInstanceUID.UID.Split('.').Last(), Status, info);
            }
            else
            {
                Log.Error("Print Job {0} Status {1}: {2}", SOPInstanceUID.UID.Split('.').Last(), Status, info);
            }
            StatusUpdate?.Invoke(this, new StatusUpdateEventArgs((ushort)Status, info, FilmSessionLabel, PrinterName));
        }

        #endregion

    }
}

`

**Comment by megarockss** [comment]
I need to print the document on a laser printer as soon as the service listens for the dicom print

**Comment by mrbean-bremen** [comment]
@megarockss - please create a separate issue for your problem.

**Comment by megarockss** [comment]
Sorry Brow
