### ISSUE TITLE
DICOM images are broken when they are transcoded automatically

### ISSUE THREAD

**Issue by amoerie** [fo-dicom/fo-dicom#921]
### Expected behavior
Sending a little endian explicit DCM file over the wire with a C-STORE request, during which the file is converted to JPEG Lossless P14 S1, is jumbled up and unusable.

The reason is that the photometric interpretation is overwritten to YBRFull instead of MONOCHROME2, while the pixels themselves are not converted to the RGB color space.

### Actual behavior
The output is unchanged pixel data with a new photometric interpretation, causing the file to be unreadable.

### Steps to reproduce the behavior

```
                var input = DicomFile.Open("..."); // A file with little endian explicit transfer syntax
                var output = input.Clone(DicomTransferSyntax.JPEGProcess14SV1);
```

### fo-dicom version and OS/platform
Latest development branch
Windows 10 latest stable update

### Sample 

![Sample input](https://i.imgur.com/jFvdj48.png)

becomes

![Sample output](https://i.imgur.com/ZDY863v.png)

**Comment by amoerie** [comment]
I've traced down the reason for this bug to this commit:

https://github.com/fo-dicom/fo-dicom/pull/880/commits/8812a46480da373399ce08ab86e1c1f3508dc3d6

In the past, the original photometric interpretation (being MONOCHROME2) would not have been updated, causing things to keep working.

**Comment by gofal** [comment]
The bugfix was because when encoding to transfersyntax JpegBaseline then the resultung photometric interpretation has to be YBRFull. I did not thing that this codepath is also used when converting to other Jpeg compressions that preserve the photometric interpretation.
So the old condition

    if (oldPixelData->PhotometricInterpretation == PhotometricInterpretation::Rgb && cinfo.jpeg_color_space == JCS_YCbCr)

should not have been deleted but rather replaced by if the new transfersyntax is jpegbaseline

**Comment by gofal** [comment]
This is a very critical bug. Please verify, I will plan a release 4.0.3 very soon then.

**Comment by amoerie** [comment]
Agreed that this is very critical. It essentially blocks our update to 4.0.2. 

We don't have a fix for this issue yet, I intend to take a look tomorrow what the best course of action is. Unless the solution is obvious to you? I'm still not entirely clear on what the original fix actually solved.

**Comment by gofal** [comment]
The original issue was: when you have some grayscale image and convert it to JpegBaseline, then in background it is converted into a "classical windows jpeg", so the monochrome image becomes a color image. There the photometric interpretation had to be updated. It was not critical because most of the viewers seemed to ignore the photometric interpretation when opening a file with TransferSyntax JpegBaseline, but actually the file was invalid and some viewers complained about it. 

My mistake, when doing the fix, was that I thought this code path was only used for JpegBaseline encoding. The fix of the fix is obvious to me and I already commited it into the development branch: I had to add a condition that the photometric interpretation is only changed if the encoding is in Mode Baseline.

**Comment by amoerie** [comment]
Perfect, thanks for the swift responses! I’ll try it out later today. 

Perhaps it would be a good idea to have some tests that exercise the transcoders and verify correct pixel data output? I found it a bit scary that no test could have prevented this problem.

**Comment by amoerie** [comment]
@gofal Is it possible you forgot Dicom.Imaging.Codec.DicomJpegCodecImpl.cs#169?

I see very similar logic there.

**Comment by gofal** [comment]
No, this class is included in Dicom.NetCore. This class handles only jpeg process 1 encoding/decoding, which is baseline. other processes like process 14 (jpeglossless) are not supported in NetCore by fo-dicom.

**Comment by gofal** [comment]
.. but I forgot it for windows universal platform

**Comment by amoerie** [comment]
Our tests are green now. Commencing manual tests now.

**Comment by amoerie** [comment]
Bad news:

Transcoding from JPEG2000Lossy to JPEGProcess2_4 suffers from the same problem, because the JPEG mode is then set to "Sequential", which also triggers the overwriting of the photometric interpretation, while the value should remain MONOCHROME2. 😢

**Comment by amoerie** [comment]
The following snippet is showing promising results so far:
```cplusplus

        if (cinfo.jpeg_color_space == JCS_YCbCr)
        {
            if (params->SampleFactor == DicomJpegSampleFactor::SF422)
                newPixelData->PhotometricInterpretation = PhotometricInterpretation::YbrFull422;
            else
                newPixelData->PhotometricInterpretation = PhotometricInterpretation::YbrFull;
        }
        else if (cinfo.jpeg_color_space == JCS_RGB)
        {
            newPixelData->PhotometricInterpretation = PhotometricInterpretation::Rgb;
        }
```

**Comment by gofal** [comment]
No, this does not work for me. Using the file contained in Dicom.Tests.Desktop project "GH064.dcm". it has Photometricinterpretation `MONOCHROME2`. When converting to JpegBaseline with your code snippet then the PhotometricInterpretation still stays MONOCHROME2 but should be changed to YBR_FULL_422.

**Comment by gofal** [comment]
But you say it does not work for Sequential Mode. So I would remove the Sequential from the condition.

    if (Mode == JpegMode::Baseline)
    {
        ....

Could you try that?

**Comment by amoerie** [comment]
The only place - that I can find - where a codec is initialized JpegMode::Baseline is here:

https://github.com/fo-dicom/fo-dicom/blob/5fddcf7a36919e612587515ec74fb7eb81b48134/Native/Desktop/Dicom.Imaging.Codec.Jpeg.h#L106-L113

Whenever you have 12 bit or 16 bit images (i.e. where BitsStored > 8, or where BitsAllocated = 16) it uses JpegMode::Sequential.

We don't want to convert our grayscale images to the RGB color space, and hence we don't want to update our photometric interpretations to RGB or YBR.

**Comment by gofal** [comment]
see my comment on gitter: 

> This bug is really bad and I rather would like to create JpegBaseline encoded with wrong PhotometricInterpretation, which most of the viewers out there seem to ignore in case of JpegBaseline transfer syntax, than creating corrupt jpegLossless images where the Photometricinterpretation is cruical. So I'd commit your snippet and plan a release and create an issue to make this clear in a next release. Is that fine for everyone?

**Comment by amoerie** [comment]
I agree with this strategy

**Comment by gofal** [comment]
By having reverted the change, I see this issue as closed. Feel free to reopen it if there is still something going wrong.
