### ISSUE TITLE
Film print group

### ISSUE THREAD

**Issue by phelys** [fo-dicom/fo-dicom#924]
I need some help, how is possible to group films generated using Print SCP, when I sent from my workstation, the print sample save images film by film, but i need group this images, is possible?

**Comment by gofal** [comment]
I am not sure what you want to get. As I understand currently you get 1 image per film (= page), but you would like to print several images on one page?

In samples you see this code:

                printJob.StartFilmBox("STANDARD\\1,1", "PORTRAIT", "A4");
                printJob.FilmSession.IsColor = true; //set to true to print in color
                printJob.AddImage(bitmap, 0);
                printJob.EndFilmBox();

It creates a page in portrait and size A4 with standard 1x1 images. so you can add only one image with index 1.
If you alter it to

                printJob.StartFilmBox("STANDARD\\2,1", "PORTRAIT", "A4");
                printJob.FilmSession.IsColor = false; //set to true to print in color
                printJob.AddImage(bitmap1, 0);
                printJob.AddImage(bitmap2, 1);
                printJob.EndFilmBox();

you create a portrait A4 page with 2 columns and 1 row. so you have 2 images side by side. Therefore you add 2 images with index 0 and 1 to the filmbox.

Its the clients responsibility how to layout the images within a film.

Does that help you?

**Comment by phelys** [comment]
> I am not sure what you want to get. As I understand currently you get 1 image per film (= page), but you would like to print several images on one page?
> 
> In samples you see this code:
> 
> ```
>             printJob.StartFilmBox("STANDARD\\1,1", "PORTRAIT", "A4");
>             printJob.FilmSession.IsColor = true; //set to true to print in color
>             printJob.AddImage(bitmap, 0);
>             printJob.EndFilmBox();
> ```
> 
> It creates a page in portrait and size A4 with standard 1x1 images. so you can add only one image with index 1.
> If you alter it to
> 
> ```
>             printJob.StartFilmBox("STANDARD\\2,1", "PORTRAIT", "A4");
>             printJob.FilmSession.IsColor = false; //set to true to print in color
>             printJob.AddImage(bitmap1, 0);
>             printJob.AddImage(bitmap2, 1);
>             printJob.EndFilmBox();
> ```
> 
> you create a portrait A4 page with 2 columns and 1 row. so you have 2 images side by side. Therefore you add 2 images with index 0 and 1 to the filmbox.
> 
> Its the clients responsibility how to layout the images within a film.
> 
> Does that help you?

First of all, sorry about my english... the current script avaliable to donwload on fo-dicom git repository , have like example a fo-dicom print scp, when I send one film with two or more page of my workstation to print, the program save one directory with just one xps image for each page o film, and I need save all xps files in the same directory... that is, for each print command, I want to created a directory with all images sented by user that time

**Comment by gofal** [comment]
Ah, I see. So this is not in scope of fo-dicom, because this is not about DICOM communication. But waht you are asking for is how to store the xps files in different directories.
Well, the printscp-sample wants to demonstrate how to receive the images and organize then in filmboxes etc. Just for demonstration purposes the printscp then creates a directory for each connection from a client and then saves a xps there. it also could save jpegs there to show how the page would look like. In class `PrintJob` within the constructor the directory, where the xps will be stored, is calculated. it is the property `FullPrintJobFolder`. There you can set the property to a constant directory instead of calculating a unique directory for every connection.

**Comment by phelys** [comment]
> Ah, I see. So this is not in scope of fo-dicom, because this is not about DICOM communication. But waht you are asking for is how to store the xps files in different directories.
> Well, the printscp-sample wants to demonstrate how to receive the images and organize then in filmboxes etc. Just for demonstration purposes the printscp then creates a directory for each connection from a client and then saves a xps there. it also could save jpegs there to show how the page would look like. In class `PrintJob` within the constructor the directory, where the xps will be stored, is calculated. it is the property `FullPrintJobFolder`. There you can set the property to a constant directory instead of calculating a unique directory for every connection.

great, I'll check it, thanks a lot, best regards

**Comment by gofal** [comment]
I close this issue due to inactivity.
If you are still facing some problems or have any updates, please reopen this issue again.
