### ISSUE TITLE
fo-dicom.Desktop: Lossy JPEG 8 Bit Image cannot be decoded

### ISSUE THREAD

**Issue by a21862** [fo-dicom/fo-dicom#928]
### Expected behavior
JPEG Baseline (Process 1) is expected  to be supported

### Actual behavior
however, exception happens： “Decoding dataset with transfer syntax: JPEG Baseline (Process 1): Default Transfer Syntax for Lossy JPEG 8 Bit Image Compression is not supported.”

### Steps to reproduce the behavior

img = new DicomImage(dcmfilePath);
var image = img.RenderImage(0);

### fo-dicom version and OS/platform
v4.0.3
Windows 10, Visual Studio 2015,

**Comment by gofal** [comment]
have you compiled with AnyCpu? To have codec support you need to compile explicit as x86 or x64

**Comment by amoerie** [comment]
Possible duplicate of #911

**Comment by a21862** [comment]
@gofal 
Thanks. It works after I complie the code explicitly as x64 !!! Appreciate your help

**Comment by a21862** [comment]
specifying x64 resolves this issue.
