### ISSUE TITLE
TryGetString(DicomTag, out string) throws "ArgumentOutOfRange" Exception on PregnancyStatus

### ISSUE THREAD

**Issue by apang2013** [fo-dicom/fo-dicom#932]
### Expected behavior
`DicomDataset dataset;`
`dataset.TryGetString(DicomTag.PregnancyStatus, out string s);`
Function should only throw an ArgumentOutOfRangeException if the DicomTag has VM>1, or VR=SQ
### Actual behavior
Exception is thrown if the value does not exist, as if the VR of Pregnancy status is a `DicomSequence`, or its VM is >1?
But if the value exists, it functions as expected (ushort parsed to string).
### Steps to reproduce the behavior
![image](https://user-images.githubusercontent.com/18233589/65743355-c1ec3380-e126-11e9-8f8a-d68ed41d1bc4.png)

### fo-dicom version and OS/platform
4.0.0; Windows 10

**Comment by gofal** [comment]
See #746. With version 4.0.1 a fix has been made when using TryGet* methods. Please try with version 4.0.1 or higher. If the issue still exists then please comment.

**Comment by apang2013** [comment]
@gofal Thanks for the pointer, I also realized using TryGetString to get the value of some VR=US tag is inappropriate, and should've only used the appropriate try get for the corresponding VR. 

Nevertheless, I tried it with NuGet Package 4.0.3, and TryGetString({Some DicomTag VR=US}) would still throw Argument Out Of Range Exception. So if you have the free time, test all the types of VR with each type of tryget.

```csharp
// Do a C-Find request to retrieve MWL of some old Dicom Ris servers, e.g. jdicom.
DicomDataset dataSet = new DicomDataset();

 // jdicom would return DicomDatasets including PregnancyStatus, but with an empty string, despite not having a valid value entered in the ris server
dataSet.Add(DicomTag.PregnancyStatus, "");

foreach (var item in dataSet)
{
    try
    {
        dataSet.TryGetString(item.Tag, out string s);
        Debug.WriteLine($"{item.ToString()} {s}");
    }
    catch(Exception ex)
    {
        Debug.WriteLine($"{item.Tag} {ex.Message}");
    }
}

/* Debug output
Exception thrown: 'System.ArgumentOutOfRangeException' in Dicom.Core.dll
(0010,21c0) US Pregnancy Status Index is outside the range of available value items
Parameter name: item
*/
```
