### ISSUE TITLE
DicomCStoreRequest CreatePresentationContext not set the specific transfer syntaxs

### ISSUE THREAD

**Issue by Ealfaro41** [fo-dicom/fo-dicom#934]
### Expected behavior

CreatePresentationContext  set and use the list of supported transfers transfers syntax.

### Actual behavior

As much as I call CreatePresentationContext with my list of supported syntax transfers, at the time of sending the images the current transferSyntax of the image + ImplicitVRLittleEndian is always negotiated. Is there any way to propose ONLY one transfer syntax from the SCU?

### Steps to reproduce the behavior

DicomClient Client = new DicomClient();
Client.NegotiateAsyncOps();

foreach (string file in matchingFiles){

	DicomCStoreRequest storeRequest = new DicomCStoreRequest(file, DicomPriority.Medium);

	DicomTransferSyntax[] AcceptedImageTransferSyntaxes = new DicomTransferSyntax[] {          
               DicomTransferSyntax.ExplicitVRLittleEndian };

	storeRequest.CreatePresentationContext(AcceptedImageTransferSyntaxes);
}

Client.SendAsync("127.0.0.1", "11113", false, "SCU", "SCP", 5000);

[If the image is in transfer syntax JPEGProcess14, Always negotiate JPEGProcess14 and ImplicitVRLittleEndian, ignoring my preference.]

### fo-dicom version and OS/platform

Fo-Dicom 4.01, Wnidows 10 64b

**Comment by gofal** [comment]
The method `CreatePresentationContext` is defined in the base class `DicomRequest` and is used in all types of requests except of CStoreRequest. This is because DICOM standard says that transfersyntax ImplicitVRLittleEndian always has to be offered by a store SCU. Therefore the `DicomCStoreRequest`-class has the property `AdditionalTransferSyntaxes` that is used here.

We could override the method `CreatePresentationContext` to set `AdditionalTransferSyntaxes` in `DicomCStoreRequest`, but the transfersyntax ImplicitLittleEndian will always be offered due to DICOM standard.

**Comment by Ealfaro41** [comment]
Thanks for the reply Gofal. I understand the point, but the problem is that not only Implicit Little Endian is offered, but also, the current image transfer is always offered to. Not having control over the list of transfer syntaxs offered and the order I think is a mistake and takes away a lot of flexibility. We have many clients and hundreds of equipment where images are sent. Each manufacturer is a world with its own compatibility and operating problems. I believe that if an explicitly offered syntax transfer list is not  assigned, it is correct that fo-dicom offers by default, but there should be some method to negotiate our own list in the order that is required.

As an example, many devices support Implicit little endian but then do not receive the images or break them upon receiving them. In these cases we could say, ok, it is outside the dicom protocol, or it is a problem of the equipment, but still we need to provide a solution that is often not possible with the device technician. I think it should be possible to decide which transfers to negotiate explicitly. It's just an opinion that I think has easy implementation and that would improve product compatibility. Regards.

**Comment by gofal** [comment]
I understand. But you need an other solution. dicom standard requires to offer ImplicitLittleEndian, there is no way around this. And you can already add additional transfersyntaxes. 
The server then answers for every single transfersyntax if it is supported or not. The order does not matter here. 

But then I see your actual request: the client now has received a list of accepted transfersyntaxes. Currently the first of the accepted is choosen, that is the transfersyntax that the file is currently saved (this avoids transcoding). But you want to explicitly choose which transfersyntax to prefer over the others. 
This could be solved with a property like `PreferedTransferSyntax` if it is only one transfersyntax you want to prefer over others. Or we could implement an event that is raised just before actually sending where the input parameter is the list of accepted transfersyntaxes and the eventhandler has to return the actual transfersyntax to choose. This is harder to implement for the user but gives more flexibility.

Would that solve your problem?

**Comment by Ealfaro41** [comment]
As you indicate, the order of a syntax transfer in the list offered is irrelevant, since the server will simply choose one from the list (for each context) depending on its own priority list. Therefore I do not see much sense in the use of "PreferedTransferSyntax". The only important thing is that transfer syntax are offered to the recipient. I have a specific problem with some tomosynthesis studies in which each image weighs 1GB. The images are found in Explicit VR Little Endian, so Explicit VR Little Endian and Implicit VR Little Endian are always traded. Since the server has the Transfer Syntax Implicit in its priority list before the Transfer Syntax Explicit, Implicit is always negotiated making transcoding necessary. If ONLY Explicit VR Little Endian could be negotiated, the server would be forced to receive it, since there is only one possible syntax transfer for negotiation.

The transcoding is taking too long, and sometimes the images do not reach the server. This is just one example (of many others) that are presented if cannot fully manage the Transfer list to Offer. 

Thank you for your answers

**Comment by fcomarcio** [comment]
I have a similar problem.

I have an SCP using dicom-desktop 4.0.3.
I have images stored with:

lossless, non-hierarchical JPEG syntax (Process 14) - 1.2.840.10008.1.2.4.57 and
Lossless, non-hierarchical, first-order JPEG forecast (Case 14 [SV1]) - 1.2.840.10008.1.2.4.70

If the image is in transfer syntax JPEGProcess14, Always negotiate JPEGProcess14 and ImplicitVRLittleEndian,
but save on client ImplicitVRLittleEndian.

When the image is in 1.2.840.10008.1.2.4.70, my OnCMoveRequest method works fine.
The image is saved on the client with the same syntax.

I'd like keep the original transfersyntax.

The client (AquariusNET) supports both syntaxes.

**Comment by gofal** [comment]
@fcomarcio I understand that you want to avoid transcoding. But the DICOM Standard is very clear here:
* ImplicitVRLitteEndian must be offered in every CStoreRequest. 
* And it is up to the Store SCP to decide about the TransferSyntax which to accept and which to reject.

So if you offer the image as JpegProecess14, but the AquariusNet client decides to receive the image as ImpicitVRLitteEndian, than thats how DICOM works.
In the list of presentation contexts, fo-dicom always sends the actual transfersyntax of the image as first entry, then it sends the AdditionalTransfersyntaxes that you may set for the DicomCStoreRequest, and finally as last entry it sends ImplicitVRLittleEndian. So if the client would just take the first syntax that it supports, then it would choose JpegProcess14. This means that ImplicitLittleEndian is choosen intentionally by the client.
I am affraid to have to contact someone from AquariusNet to prefer JpegProcess14 over uncompressed transfersyntax.

**Comment by fcomarcio** [comment]
@gofal Thanks for your answers!
