### ISSUE TITLE
Problem finding patient names with foreign characters (umlaut)

### ISSUE THREAD

**Issue by saschke** [fo-dicom/fo-dicom#938]
I know this has been an issue before but whatever I read didn't help me so I hope someone can help me.

In my project I can search on all levels but when I search a patient with a name containing an umlaut (by example. Müller) nothing is found. I receive the umlauts correctly when I search by id or anything else.

By default (in the examples) is set to "ISO_IR 100"

       var request = new DicomCFindRequest(DicomQueryRetrieveLevel.Study);
        request.Dataset.AddOrUpdate(new DicomTag(0x8, 0x5), "ISO_IR 100");
        request.Dataset.AddOrUpdate(new DicomTag(0x8, 0x5), DiCoConstants.Encoding);
        request.Dataset.AddOrUpdate(DicomTag.PatientName, "");
        request.Dataset.AddOrUpdate(DicomTag.PatientName, "Müller");
this way the search doesn't work but the received names are correct
changing it to "ISO_IR 192" didn't help and the names show a "?" instead of the "ü"

I have a Dicom viewer that has no trouble finding studies by patient-name with umlauts so the problem is on my side.

Can you help me make this work? Thanks a lot!

-Schlomo

### fo-dicom version and OS/platform
Fo-dicom V4.03 on Windows 10

**Comment by saschke** [comment]
Please ignore the line
request.Dataset.AddOrUpdate(new DicomTag(0x8, 0x5), DiCoConstants.Encoding);
DiCoConstants.Encoding = "ISO_IR 100"

**Comment by gofal** [comment]
I know the string-encoding-thing is not very intuitive in fo-dicom currently. I have plans to redesign. 

When you add an item to a dataset, then it is encoded into dicom bytes immediatelly: Datetimes are converted to strings in format yyyymmdd and converted back if you get a value from the dataset. strings are encoded immediatelly, not evaluating if there is a dicomtag 0008,0005. 
In my imagination all types are stored as managed types and only encoded when writing the dataset into a stream (file or network). 

But anyway. At the moment you have to set the encoding as parameter in every `AddOrUpdate`. The default encoding is ASCII. So call `request.Dataset.AddorUpdate(DicomTag.PatientName, System.Text.Encoding.UTF8, "Müller");`.

**Comment by saschke** [comment]
It ryed it and in the debugger I can see that the 'ü' is now not a '?' naymore but the request returns empty if a name includes an umlaut. Is there anything else I need to do?

**Comment by gofal** [comment]
Hm. don't have an idea. Maybe you could try other encoding than utf8? Utf7, Unicode,.. And do not forget to set the dicomtag 0008,0005 corresponding.

**Comment by saschke** [comment]
_ = request.Dataset.AddOrUpdate(DicomTag.PatientName, **Encoding.Default**, "Müller"); 
did the Job.
Thank you!
