### ISSUE TITLE
TryGetString(DicomTag, out string) throws Unexpected VR found for DICOM fragment sequence: UN“”

### ISSUE THREAD

**Issue by leconehu** [fo-dicom/fo-dicom#947]
### Expected behavior

TryGetString(DicomTag, out string) throws Unexpected VR found for DICOM fragment sequence: UN

**Comment by gofal** [comment]
Is it possible to give more information? A anonymized sample file would be great. Or at least a stacktrace of the exception to locate the source of the exception?
