### ISSUE TITLE
Unity: Read DicomDirectory with Open(string)

### ISSUE THREAD

**Issue by MusoAga** [fo-dicom/fo-dicom#950]
### Expected behavior
I want to read all Dicom Files in a Directory and return it as DicomDirectory. 

`string PathToDicomTestFile = Path.Combine(System.IO.Directory.GetCurrentDirectory(), "DICOM", "brain");`

`DicomDirectory dicomDirectory = DicomDirectory.Open(PathToDicomTestFile);`

The directory contains only valid dicom files.

### Actual behavior
I get this error:

![image](https://user-images.githubusercontent.com/12189192/68123544-99b5d880-ff0d-11e9-8cb2-75e050e6791d.png)

I can read a single dicom file without problems and do not getting any errors.

`var file = DicomFile.Open(PathToDicomTestFile);`

### Steps to reproduce the behavior

Empty scene in Unity. Attached empty MonoBehaviour script to gameobject and call on Start()

`string PathToDicomTestFile = Path.Combine(System.IO.Directory.GetCurrentDirectory(), "DICOM", "brain");`

`DicomDirectory dicomDirectory = DicomDirectory.Open(PathToDicomTestFile);`

### fo-dicom version and OS/platform

fo-dicom for Unity 3.5.0 |   Windows 10 with Visual Studio 2019 and Unity 2019.2.10f1

**Comment by Darkroll76** [comment]
Hi, I have the same issue. We need to create the DICOMDIR of the folder first and then read this file to open all the DICOM Files.

**Comment by MusoAga** [comment]
Thanks for reply @Darkroll76 . What exactly do you mean by **create the DICOMDIR of the folder**? So I have to read all single files and add them to a DICOMDIR?

**Comment by Darkroll76** [comment]
When they write "DICOMDIR" at `var dicomDirPath = Path.Combine(path, "DICOMDIR");` 
I first understand that I had to replace it by the name of my directory like you are trying to do with "brain". But after some research DICOMDIR is a [file format](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_F.2.2.2.html)

I first found this [project](https://github.com/UoA-eResearch/DICOM_viewer/blob/master/Assets/Scripts/LoadDICOM.cs) which is a Unity Project for Hololens using this library. See line 318.  

What I'm trying to do now is "if" there is no DICOMDIR in the folder, I'm creating one. But I'm still stuck on this. I'm getting this error `NullReferenceException: Object reference not set to an instance of an object Dicom.Network.NetworkManager.TryGetNetworkIdentifier (Dicom.DicomUID& identifier) (at <95b156382bfa4140a7707521d71f6cc6>:0)`

**Comment by Darkroll76** [comment]
Another link about DICOMDIR : http://dicomiseasy.blogspot.com/2013/03/dicomdir-and-media-interchange.html

**Comment by MusoAga** [comment]
Oh thank you very much! It would have taken me a long time to find this out. Now I think it works, at least I have no errors. Maybe the error of your code, is related to your dicom file. I could upload the brain dicom files for testing, they were anyway free to download somewhere.

**Comment by Darkroll76** [comment]
@MusoAga You're welcome! You have already a DICOMDIR file in your directory? Because I still have a network error (Don't know why)

**Comment by MusoAga** [comment]
I just created manually a DICOMDIR folder, then add it the .dcm files. I work locally, so maybe the error is network related. 

I am using the fo-dicom for unity from the assets store. Just downloaded and added them to project. The hololens project should use the same, but it is maybe another version?

**Comment by Darkroll76** [comment]
Yeah maybe. I will try to delete them and install it again using Assets Store
