### ISSUE TITLE
Cannot parse DicomTime if decimal point >6

### ISSUE THREAD

**Issue by jbjumbojb** [fo-dicom/fo-dicom#951]
### Expected behavior
parse DicomTime to DateTime correctly

### Actual behavior
Cannot parse in case decimal point > 6

### Steps to reproduce the behavior
new DicomDataset(new DicomTime(DicomTag.CreationTime, "155431.1234567"));

### fo-dicom version and OS/platform
fo-dicomv 4.0.3 
Windows 10 build 17763.805

**Comment by gofal** [comment]
Yes of cource, since it is not a valid DateTime format as defined in DICOM standard.
http://dicom.nema.org/dicom/2013/output/chtml/part05/sect_6.2.html

here the definition of Value Representation DT (Date Time). I made the part with the maximum of 6 digits bold.

> A concatenated date-time character string in the format:
>
>YYYYMMDDHHMMSS.FFFFFF&ZZXX
>
> The components of this string, from left to right, are YYYY = Year, MM = Month, DD = Day, HH = Hour (range "00" - "23"), MM = Minute (range "00" - "59"), SS = Second (range "00" - "60").
> 
> FFFFFF = Fractional Second contains a fractional part of a second **as small as 1 millionth of a second** (range "000000" - "999999").
> 
> &ZZXX is an optional suffix for offset from Coordinated Universal Time (UTC), where & = "+" or "-", and ZZ = Hours and XX = Minutes of offset.

**Comment by gofal** [comment]
some sentences later is is desribed in more detail:

> The Fractional Second component, if present, shall contain 1 to 6 digits. If Fractional Second is unspecified the preceding "." shall not be included.

**Comment by jbjumbojb** [comment]
Thank you
