### ISSUE TITLE
Use DI with DicomService

### ISSUE THREAD

**Issue by chen-wu** [fo-dicom/fo-dicom#952]
### Expected behavior
Hi,
I would like to inject another service to my custom CStore SCP service. e.g. to send DICOM Dataset to other place instead of saving them to file. But the DicomService is totally sealed within DicomServer.
Do I need to implement my own IDicomServer to override this? I tried to wrote my own DicomServer<T> however the DicomServer static class will start the server as soon as it is created.

### Actual behavior
No way to input anything to the server

**Comment by gofal** [comment]
the new netstandard-implementation of fo-dicom will have a DI container included. You can take a look at the code in branch "netstandard".
But in current implementation you have an UserState object to pass from DicomServer to the DicomService instances. 
If you start an DicomServer, you can pass an argument like

    DicomServer.Create<MyStoreScpService>(NetworkManager.IPv6Any, port, userState: anyObject);

so you can pass any object `anyObject` to the DicomServer. this may be some configuration file or some class holding databaseconnections or whatever.

Then within your `MyStoreScpService`, which inherits from class `DicomService`, you have the property `UserState` available, that contains the content you passed through.

**Comment by chen-wu** [comment]
Thanks for your support! @gofal This helps a lot!
I will try the netstandard version. But for now, I will follow your instruction.
