### ISSUE TITLE
Could you give me an example of how to convert a dicom video to mp4?

### ISSUE THREAD

**Issue by alanhmartins** [fo-dicom/fo-dicom#953]
Could you give me an example of how to convert a dicom video to mp4?

**Comment by gofal** [comment]
Sure. See here: #689

**Comment by alanhmartins** [comment]
@gofal 
It doesn't work, it even saves the file in avi or mp4 format, but doesn't play the video when trying to watch it

**Comment by aerik** [comment]
@alanhmartins Are you sure your video *is* an mp4?

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.

**Comment by msciborski** [comment]
Hello, @gofal 
Which approach is correct for 4.0.7?
