### ISSUE TITLE
DicomFile.Open(outFile, FileReadOption.ReadAll) returns null

### ISSUE THREAD

**Issue by wesdean** [fo-dicom/fo-dicom#957]
`DicomFile.Open(outFile, FileReadOption.ReadAll)`

Reading from a file on disk works as expected. If I put that same file into a MemoryStream then DicomFile.Open returns null.

I suspect it has something to do with `if (!source.Require(132U))` on line `DicomFileReader.cs : 102`

Stack Trace:
I get this stack trace when attempting to get the DicomFile.Dataset on the last line of my Steps to Reproduce.
`
{
  "error": "13 INTERNAL: Object reference not set to an instance of an object.
   at DicoogleGRPCServer.Services.DicoogleStorageImpl.RetrieveImage(String authToken, String guid, String mimeType) in /app/DicoogleGRPCServer/Services/DicoogleStorageImpl.cs:line 663"
}
`

### Expected behavior
To return a DicomFile instance

### Actual behavior
Returns null

### Steps to reproduce the behavior
```
ImageManager.SetImplementation(new RawImageManager());
using var inFile = new FileStream("/app/0002.DCM", FileMode.Open, FileAccess.Read);
var inBytes = new byte[inFile.Length];
var numBytesToRead = (int)inFile.Length;
var numBytesRead = 0;
while (numBytesToRead > 0)
{
  var n = inFile.Read(inBytes, numBytesRead, numBytesToRead);
  if (n == 0) break;
  numBytesRead += n;
  numBytesToRead -= n;
}
inFile.Close();

numBytesToRead = inBytes.Length;
using var outFile = new MemoryStream();
outFile.Write(inBytes, 0, numBytesToRead);
                        
var dicomDataset = DicomFile.Open(outFile, FileReadOption.ReadAll).Dataset;
```

### fo-dicom version and OS/platform
fo-dicom.NetCore 4.0.3
Alpine Linux 3.9
OS Docker image: mcr.microsoft.com/dotnet/core/aspnet:3.0.0-alpine3.9

**Comment by rcd** [comment]
I believe this is because the stream position is still at the end of the stream once you finish writing all the bytes and that will be the position that `DicomFile.Open` will start reading from when called. What happens if you reset the position of the `MemoryStream` before you call `DicomFile.Open`?

```csharp
...
outFile.Write(inBytes, 0, numBytesToRead);
outFile.Seek(0, SeekOrigin.Begin); // move position back to beginning of stream
                        
var dicomDataset = DicomFile.Open(outFile, FileReadOption.ReadAll).Dataset;
```

**Comment by wesdean** [comment]
That worked, thank you.
