### ISSUE TITLE
Socket error while reading PDU: ConnectionReset [10054]

### ISSUE THREAD

**Issue by kevinlo** [fo-dicom/fo-dicom#960]
Occasionally, we get the "Socket error while reading PDU: ConnectionReset [10054]" error in the log and it loses a few instances.

My question is if the DicomClient or DicomServices handle transient error and do the retry?

If it really has transient network issue that cause the ConnectionReset, do I need to handle it myself?

I have read #857 which has the problem fixed in the latest DicomClient.  But I am using version 4.0.3 already.

Currently, I can't tell if my problem is network issue or linger issue or something else.

My second question if there is any good practice in using the DicomClient.   Should it be created a new one for each request or it should be reused with existing connection and association?  

I am newbie to dicom.  Thanks in advance for any suggestion.

**Comment by kingyzf** [comment]
I have the same error and question

**Comment by amoerie** [comment]
Copying from the referenced thread, which already included some advice:

General advice: make a separate DicomClient for every DICOM server you'll be talking to. If you have many requests, it's best to reuse a DicomClient, as it'll reuse the existing connection and association to send them. It's best though to first call "AddRequest" for each request and then call Send at the end, because then it'll automatically set up the correct presentation contexts on the association.

As for lost connections, you can catch any exceptions thrown by SendAsync (if you await it properly) and handle them as needed. There is no automatic reconnection logic provided.

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.

**Comment by jdbogdan** [comment]
[INFO] DVTK_MW_SCU <- Association request:
Calling AE Title:       DVTK_MW_SCU
Called AE Title:        Zhy
Remote host:            10.8.109.38
Remote port:            64748
Implementation Class:   Implementation Class UID [1.2.276.0.7230010.3.0.3.6.4]
Implementation Version: OFFIS_DCMTK_364
Maximum PDU Length:     16384
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Proposed]
       Abstract Syntax:  Modality Worklist Information Model - FIND
       Transfer Syntax:  Explicit VR Little Endian
       Transfer Syntax:  Explicit VR Big Endian (Retired)
       Transfer Syntax:  Implicit VR Little Endian: Default Transfer Syntax for DICOM
[INFO] Received association request from AE: DVTK_MW_SCU with IP: 10.8.109.38
[INFO] Accepted association request from DVTK_MW_SCU
[INFO] DVTK_MW_SCU -> Association accept:
Calling AE Title:       DVTK_MW_SCU
Called AE Title:        Zhy
Remote host:            10.8.109.38
Remote port:            64748
Implementation Class:   Implementation Class UID [1.2.276.0.7230010.3.0.3.6.4]
Implementation Version: OFFIS_DCMTK_364
Maximum PDU Length:     16384
Async Ops Invoked:      1
Async Ops Performed:    1
Presentation Contexts:  1
  Presentation Context:  1 [Accept]
       Abstract Syntax:  Modality Worklist Information Model - FIND
       Transfer Syntax:  Explicit VR Little Endian
[INFO] Socket error while writing PDU: ConnectionAborted [10053]
[INFO] Connection closed
[INFO] Socket error while reading PDU: ConnectionAborted [10053]

IOException in FellowOakDicom.Network.DicomService 

Is this a client-side problem or a server-side problem

**Comment by bakhtvar** [comment]
I also faced the Socket error while reading PDU: ConnectionReset [10054] error recently.
My findings:
- While sending compressed format it may face this problem.
- The error is consistent "fortunately", I mean for some specific files the send operation stops and raises the mentioned errors.
- When you change the transfer syntax to Uncompressed, the issues is solved and you can send the file.
- You revert from Uncompressed to original compressed format. again the file cant be send.
- The same file (I mean the original compressed file) can DO send from some other machines! I mean you copy the file to some other machine and will be send to the same destination with no problem.
- The problematic find can NOT be send either of ways, I mean from point A to B or B to A, it can NOT be send.
- Both directions works when you Uncompressed the file.

I face the issue just recently, I mean almost for 1 week, and I am hearing about from different points and customers.
I am using the very latest version of 4.0.7.
I am using Win10 / WinServer2019 for either of two sides. both systems are having latest updates from Microsoft.

I debug to deepest levels, and currently I think there is no problem with fo-dicom. may be windows has released some updates and caused the issue, as some of points/customers I am hearing the problem from. are using the system for years and this problem arose just for 1 week now and is spreading.

Looking forward of ideas.

**Comment by bakhtvar** [comment]
Just to add that there are two types of errors which happens.
- Socket error while reading PDU: TimedOut [10060]     
- Socket error while reading PDU: ConnectionReset [10054]

**Comment by vovundel** [comment]
hi people, ich have the same problem. Client from DCM4CHEE try to send C-Store to fo-dicom server:

`Socket error while reading PDU: ConnectionReset [10054]`
