### ISSUE TITLE
ChangeTransferSyntax does not compress pixel data when DicomSequence is used

### ISSUE THREAD

**Issue by KarlAbson** [fo-dicom/fo-dicom#961]
From what I have read the following line should encode the Dicom file.

_file = file.Clone(DicomTransferSyntax.JPEG2000Lossless);_

However the file size of the resultant Dicom file remains the same in my case. Also upon loading the file using the following line gives the exception "Error in JPEG 2000 code stream!":

_WriteableBitmap writeableBitmap = dicomImage.RenderImage().AsWriteableBitmap();_

A similar message is given for all except "ImplicitVRLittleEndian". Could it be that the image data is still uncompressed and something is being missed?

Many thanks,
Karl

**Comment by KarlAbson** [comment]
After some testing it seems to be that DicomDataset nodes and the images insides them are missed when placed inside a DicomSequence. These are not compressed and as such the file size remains high. I wanted to add multiple image sequences to a single file and this was the only way I could figure to do this.

This illustrates the node layout I have:
DicomFile > Main DicomDataSet > DicomSequence > Multiple DicomDatasets with sets of frames.

Unless there is a fix the only other solution I can think of is to use a individual files for each sequence of images. If the images are placed inside a dataset directly on the file node the images are compressed as expected.

**Comment by gofal** [comment]
Which tags are you talking about? As far as I know, the TransfeSyntax only has affect on PixelData (7FE0,0010). 
Do you mean you have a sequence and within this sequece the datasets do have values for 7fe0,0010? then these sub-datasets should also have transfersyntaxes, maybe...

**Comment by KarlAbson** [comment]
Many thanks for the reply.

Yes I created a sequence and within this I created datasets with PixelData in them. The TransferSyntax did not effect these for me. 

I will try this again in the next few days and see if I get a different outcome. I did not have a problem though when creating a dataset directly at the file level i.e. without a sequence.

**Comment by gofal** [comment]
I am curious. Is this something described in DICOM standard, or is it something you invented yourself? Because I know PixelData only as top-level DicomTag, not included in Sequences. Thats why changing the Transfersyntax only compresses the pixel data available in top-level hierachy and does not search recursively throught the whole dataset. But that what you do is described in standard and pixel data may be contained in sequences, then this is a bug that has to be fixed. 
Otherwise you should compress each sub-dataset independently by changing transfersyntax (you can do it in memory and do not need to write it to file, that saves IO time) and then add it to the sequence.

**Comment by KarlAbson** [comment]
I was trying to find away of storing more than one image sequences in a dicom file and I came across the following:

https://stackoverflow.com/questions/46929334/creating-dicom-sequences-with-fo-dicom

I'm not sure if this is something that is standard or advisable or not. It just seemed like a useful way of organising unrelated image sequences. Perhaps its better though to use separate files.

**Comment by gofal** [comment]
ok, I see. if you are using it ONLY internally, it is up to you to save them as sequence into a single file. But you then should not be surprised if some things do not work as you except it :-)

All you need to do, is to compress the images in memory by calling `var subimage = image.clone(Transfersyntax.xxxx)` BEFORE adding this subimage to the sequence. Calling `Clone(Transfersyntax...)` on the final file will not change the subimages any more.

Of if you need to compress the file later, you first have to load the file into memory, load each subimage, calling the clone method for each of them and then replacing the old images by the new  ones.

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.
