### ISSUE TITLE
Add ReceivingApplicationEntityTitle to FileMetaInfo in DicomService

### ISSUE THREAD

**Issue by molox** [fo-dicom/fo-dicom#962]
Adding ReceivingApplicationEntityTitle to the FileMetaInfo from the association would be very helpful when processing CStore for multiple AE's. This could easily be done in DicomService.cs like this (line 628 in DicomService.cs).

```
var file = new DicomFile();
file.FileMetaInfo.MediaStorageSOPClassUID = pc.AbstractSyntax;
file.FileMetaInfo.MediaStorageSOPInstanceUID = _dimse.Command.GetSingleValue<DicomUID>(DicomTag.AffectedSOPInstanceUID);
file.FileMetaInfo.TransferSyntax = pc.AcceptedTransferSyntax;
file.FileMetaInfo.ImplementationClassUID = Association.RemoteImplementationClassUID;
file.FileMetaInfo.ImplementationVersionName = Association.RemoteImplementationVersion;
file.FileMetaInfo.SourceApplicationEntityTitle = Association.CallingAE;
// Add this
file.FileMetaInfo.ReceivingApplicationEntityTitle = Association.CalledAE;
```
It's an optional attribute but would be very helpful when processing multiple associations from the same client to different AE's without creating a new server on a different port.

Optionally the active association could be referenced in the DicomCStoreRequest.

**Comment by gofal** [comment]
The active association is available within your `OnCStoreRequest` method. The class `DicomService` has the public property `Association`. And since your store scp class has to inherit from DicomService, you can access this property within any method.

**Comment by molox** [comment]
Oh I didn't realize it was that easy, tested and working. Thanks.
