### ISSUE TITLE
Missing ReferencedFilmSessionSequence attribute in FilmBox

### ISSUE THREAD

**Issue by tbin987** [fo-dicom/fo-dicom#967]
### Expected behavior
I'm writing an print SCU with fo-dicom to print the DICOM images to an DICOM printer. During the development, I used the sample "Print SCP" of fo-dicom-samples and DVTk to test the functionality, and there is no error. However, when I used with a real DICOM printer, the printing behavior was stopped with an error.

### Actual behavior
When sending the N-CREATE request of Basic Film Box, the printer replied "N-Create response [2]: Missing attribute".
![20200112131139](https://user-images.githubusercontent.com/33738559/72214492-416b0a80-353e-11ea-92a6-e6ae1a74caa3.png)

By looking the DICOM standard, it seems the "Referenced Film Session Sequence" is missing in the N-CREATE request of FilmBox.
![20200112132127](https://user-images.githubusercontent.com/33738559/72214500-78412080-353e-11ea-8a53-bda5c542ab30.png)

After manually adding the "Referenced Film Session Sequence", there is no error when printing to the real DICOM printer.

### Steps to reproduce the behavior
Use the "Print SCU" project of Samples.Desktop in fo-dicom-samples to print the DICOM images, the result on DVTk was captured:
![20200112131600](https://user-images.githubusercontent.com/33738559/72214498-52b41700-353e-11ea-84cb-0c904f475296.png)
[DVTk Results.zip](https://github.com/fo-dicom/fo-dicom/files/4050239/DVTk.Results.zip)

### fo-dicom version and OS/platform
- fo-dicom.Desktop 4.0.3
- Windows 10 x64
- .Net Framework 4.6

**Comment by gofal** [comment]
I added the ReferencedFilmSessionSequence. my own services work fine (but they also worked before this change...). Can you give the current sourcecode a try on your side?

**Comment by tbin987** [comment]
I've updated fo-dicom to 4.0.4 and tested. It works fine now.

![20200121150420](https://user-images.githubusercontent.com/33738559/72782687-555ded00-3c5f-11ea-9e46-5dff3312957b.png)


Thank you for the fix!
