### ISSUE TITLE
Question about OnCFindRequest and DicomAssociation

### ISSUE THREAD

**Issue by aa82at** [fo-dicom/fo-dicom#968]
Hi,

i have a question about cfindprovider. It is possible that I am not using it properly...

Is there a reason why OnCFindRequest does not provide a DicomAssociation as an argument? I would like to access the callingae from the machine's config...

thanks for the clarification
Andreas

**Comment by gofal** [comment]
the method `OnCFindRequest` is implemented within a class, that has to inherit from `DicomService`. This base class DicomService has some usefull properties. On of these is `Assocation`. So within your method implementation of OnCFindRequest you can access this Association-property anytime.

**Comment by aa82at** [comment]
> the method `OnCFindRequest` is implemented within a class, that has to inherit from `DicomService`. This base class DicomService has some usefull properties. On of these is `Assocation`. So within your method implementation of OnCFindRequest you can access this Association-property anytime.

you're right, of course. thank you.
since the other functions were mapped to the signature i didn't think it was a method of the class :-(
