### ISSUE TITLE
How to get numeric value for Fetal Measurements - Biparietal Diameter - 11820-8?

### ISSUE THREAD

**Issue by atifc** [fo-dicom/fo-dicom#970]
What would be the correct way to get Biparietal Diameter (numeric value) from a Structured Report (Comprehensive SR IOD, Class UID: 1.2.840.10008.5.1.4.1.1.88.33)?

I was not able to find a standard tag for this. Standard lists it under code value [11820-8](http://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_12005.html).

This is what it looks like in dicompyler:
![Biparietal Diameter](https://user-images.githubusercontent.com/26510982/72795566-2e42f380-3c3e-11ea-8a12-8132fd745bdc.png)

An example would be much appreciated. Thank you.

### fo-dicom version and OS/platform
4.0.3 / Windows

**Comment by gofal** [comment]
For structured reports there are some helper-classes in namespace `Dicom.StructuredReport'

The class `DicomContentItem` is the central class and represents such a Content-Node as you can see in the tree. It has properties `Code`, that gives you the ConceptNameCodeSequence, `Type` that gives you the ValueType as an enum and you can retrieve the typed value via the method `Get<T>`.
The following sample code returns you the value 40.8:

        private void hurzToolStripMenuItem_Click(object sender, EventArgs e)
        {
            var ds = DicomFile.Open(@"D:\dicom\yourDicomFilename.dcm").Dataset;
            var SR = new DicomStructuredReport(ds);

            var val = FindValue(SR, "11820-8");
            if (val != null)
            {
                MessageBox.Show($"Found value: {val.Value}");
            }
        }

        private double? FindValue(DicomContentItem item, string CodeValue)
        {
            if (item.Type == DicomValueType.Numeric && item.Code.Value == CodeValue)
            {
                return item.Get<double>();
            }
            if (item.Type == DicomValueType.Container)
            {
                foreach(var subitem in item.Children())
                {
                    var foundValue = FindValue(subitem, CodeValue);
                    if (foundValue != null)
                    {
                        return foundValue;
                    }
                }
            }
            return null;
        }

**Comment by atifc** [comment]
Thank you, this is perfect and does exactly what I needed. Thank you very much! Feel free to close this issue.

**Comment by alanhmartins** [comment]
How to find the resistivity index for each item, example the right resistivity index of the uterine artery, the resistivity index of the left uterine artery

**Comment by alanhmartins** [comment]
![image](https://user-images.githubusercontent.com/18291580/81219185-cb3f5780-8fb5-11ea-9cf4-1b80569b1335.png)
![image](https://user-images.githubusercontent.com/18291580/81219209-d7c3b000-8fb5-11ea-8669-83083d7f2dfb.png)


Put this image there, I know if I look for code 12023-8 I find the value of the resistivity index, but I need to take that this resistivity index is from the middle cerebral artery, because the resistivity index of the other arteries also has code 12023-8. any tips?
