### ISSUE TITLE
Save DicomFile as .TIFF or other formats

### ISSUE THREAD

**Issue by MusoAga** [fo-dicom/fo-dicom#971]
Is it possible to save DicomFiles as .TIFF, .RAW or other file formats?

I found the DicomFileWriter which takes a IByteTarget as parameter. But no class implements that interface. Would the IByteTarget be my file format, which I need to implement by myself? 

I am using fo-dicom for Unity from the asset strore.

Thanks.

**Comment by gofal** [comment]
the DicomFileWriter is used to write the Dicom-Tags.
You seem to want to write the rendered Image as other formats. So first you have to call RenderImage to get the final rendered Image. Then this Bitmap can be saved in any other format you like by using some other image manipulation libraries out there.
