### ISSUE TITLE
image.RenderImage(image.CurrentFrame).As<Bitmap>() error

### ISSUE THREAD

**Issue by leconehu** [fo-dicom/fo-dicom#973]
Stream streamContent = null;
            DicomFile dicomFile = DicomFile.Open(path);
            DicomImage image = new DicomImage(dicomFile.Dataset);
            Bitmap bmp = image.RenderImage(image.CurrentFrame).As<Bitmap>(); 
            streamContent = new MemoryStream(); 
            bmp.Save(streamContent, ImageFormat.Jpeg);
            streamContent.Seek(0, SeekOrigin.Begin);

when run 
Bitmap bmp = image.RenderImage(image.CurrentFrame).As<Bitmap>();  
or
Bitmap bmp = image.RenderImage(0).As<Bitmap>();  
Dicom.Imaging.DicomImagingException:“Cannot cast to 'Bitmap'; type must be assignable from 'Byte[]'”

version 4.0.4

**Comment by gofal** [comment]
So fo-dicom internally uses the RawImageManager and renders into an byte-array.
have you read the wiki https://github.com/fo-dicom/fo-dicom/wiki/Image-rendering ?
Maybe you have to set the ImageManager manually to WinFormsImageManager if you want to get a System.Drawing.Bitmap.

Which platform are you using, on which operation system are you running, ...?

**Comment by leconehu** [comment]
.net standard 2.0, win10

**Comment by gofal** [comment]
.net standard is not a platform. So you are building your library in netstandard, but this library must then be used by some project, which is either NetFramework, NetCore, Unity, Blazor, ...

And have you tried to set the ImageManager manually explicit?

**Comment by leconehu** [comment]
NetCore 2.3；Dicom.Core, Version=4.0.4.0
set the ImageManager  
ImageManager.SetImplementation(WinFormsImageManager.Instance);  
no WinFormsImageManager in NetCore

IImage.AsBitmap();
IImage.AsWriteableBitmap();

Iimage does not contain the AsBitmap， AsWriteableBitmap definition，

can you help me to get  png from dicom?
a demo?

**Comment by gofal** [comment]
Bitmap is a class that is only supported in Windows. NetCore is intended to be platform independent. So if you want to use the GDI-based Windows-Bitmap within a NetCore project, you have to import some nuget-packages:
You need the nugetpackage _System.Drawing.Common_ to have the classes Bitmap etc available.
And you need to add the nuget package _Dicom.Drawing_ to have WinformsImageManager, which is by default only included in Dicom.Desktop for NetFramework, also available in NetCore.

**Comment by gofal** [comment]
if you want to be really platform independent, then include the nugetpackage fo-dicom.ImageSharp and use ImageSharp instead of Bitmap (https://github.com/SixLabors/ImageSharp).

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.

**Comment by iwtu** [comment]
> if you want to be really platform independent, then include the nugetpackage fo-dicom.ImageSharp and use ImageSharp instead of Bitmap (https://github.com/SixLabors/ImageSharp).

Hello.
The following code throws System.NullReferenceException at iimage.AsSharpImage() line. 

```
var image = new DicomImage(dicomFile);            
var iimage = image.RenderImage();
var sharpImage = iimage.AsSharpImage();
sharpImage.Save(jpegfile);
```

Am I using it wrong?

Anyway, I would strongly prefer the platform independent solution, so I guess maybe it can be added to the Examples:

**Comment by kira-96** [comment]
> 
> 
> @gofal
> 
> > if you want to be really platform independent, then include the nugetpackage fo-dicom.ImageSharp and use ImageSharp instead of Bitmap (https://github.com/SixLabors/ImageSharp).
> 
> Hello.
> The following code throws System.NullReferenceException at iimage.AsSharpImage() line.
> 
> ```
> var image = new DicomImage(dicomFile);            
> var iimage = image.RenderImage();
> var sharpImage = iimage.AsSharpImage();
> sharpImage.Save(jpegfile);
> ```
> 
> Am I using it wrong?
> 
> Anyway, I would strongly prefer the platform independent solution, so I guess maybe it can be added to the Examples

Maybe you forgot add this line of code to your program.

``` csharp
// on application startup
ImageManager.SetImplementation(ImageSharpImageManager.Instance);
```
Here is my complete example
``` csharp
ImageManager.SetImplementation(ImageSharpImageManager.Instance);

string dicomFile = @"test.dcm";
var image = new DicomImage(dicomFile);

using (var iimage = image.RenderImage())
{
    var sharpImage = iimage.AsSharpImage();
    sharpImage.Save("test.png");
}
```

**Comment by iwtu** [comment]
@kira-96 thanks, it works.
