### ISSUE TITLE
Can I decompress DICOM images?

### ISSUE THREAD

**Issue by cslee99** [fo-dicom/fo-dicom#987]
### Steps to reproduce the behavior
I'm using fo-diom 4.0.4.
Can I decompress an image compressed in JPEG Lossless(1.2.840.10008.1.2.4.70)?
The source below does not work with version 4.0.4.

////////////////////////////////////////////////////////////////////////
var file = DicomFile.Open(@"test.dcm");             // Alt 1
var file = await DicomFile.OpenAsync(@"test.dcm");  // Alt 2

var patientid = file.Dataset.Get<string>(DicomTag.PatientID);

file.Dataset.AddOrUpdate(DicomTag.PatientName, "DOE^JOHN");

// creates a new instance of DicomFile
var newFile = file.Clone(DicomTransferSyntax.JPEGProcess14SV1);

file.Save(@"output.dcm");             // Alt 1
await file.SaveAsync(@"output.dcm");  // Alt 2

////////////////////////////////////////////////////////////////////////

### fo-dicom version and OS/platform
Windows 10

**Comment by gofal** [comment]
Could you please exlain in more detail what exactly is not working?
By the way, this sample code does not decompress, but recompresses to JpegLossles Process 14. So if your original image is already compressed, this method will not change anything.
You would have to call `file.Clone(DicomTransferSyntax.ImplicitLittleEndian);` for example, which is an uncompressed transfer syntax.

**Comment by cslee99** [comment]
I'm sorry.
This is not sample code for the question.

Is the below code "Decompress" possible?
///////////////////////////////////////////////////////
## Original (1.2.840.10008.1.2.4.70) ==> Decompress ==> DICOM(1.2.840.10008.1.2.1)

var file = DicomFile.Open(item.FullName.ToString());
var newFile = file.Clone(DicomTransferSyntax.ExplicitVRLittleEndian, null);
newFile.Save(strDestFolder + "//output.dcm");  
///////////////////////////////////////////////////////

But an exception is thrown.
///////////////////////////////////////////////////////
{"Decoding dataset with transfer syntax: JPEG Lossless, Non-Hierarchical, First-Order Prediction (Process 14 [Selection Value 1]): Default Transfer Syntax for Lossless JPEG Image Compression is not supported. See here to get help resolving the reason: https://github.com/fo-dicom/fo-dicom/wiki/Native-codecs-on-.NET"}
///////////////////////////////////////////////////////

Do I need to register a codec?
If so, please let me know its source.

**Comment by gofal** [comment]
Did you actually read the page, that we link within the exception text?

https://github.com/fo-dicom/fo-dicom/wiki/Native-codecs-on-.NET

**Comment by cslee99** [comment]
It's working fine right now.
Decompress succeeded with the below source.
Thank you.

var file = DicomFile.Open(item.FullName.ToString());
var transcoder = new DicomTranscoder(file.Dataset.InternalTransferSyntax, DicomTransferSyntax.ExplicitVRLittleEndian);
file = transcoder.Transcode(file);
file.Save(saveFilePath);
