### ISSUE TITLE
fo-dicom Operating Environment Questions

### ISSUE THREAD

**Issue by cslee99** [fo-dicom/fo-dicom#988]
Decompress works fine on windows 10.
However, Decompress does not work on Windows Server. Everything is thrown as an exception.
The exception log is unknown because the log is not written.
Does it work on Windows Server?

**Comment by cslee99** [comment]
I solved it.
Redistribution package required for deployment.

https://github.com/fo-dicom/fo-dicom/wiki/Prerequisites

**Comment by gofal** [comment]
👍
