### ISSUE TITLE
How can I get the files which moved during a DicomCMoveRequest ?

### ISSUE THREAD

**Issue by janadel** [fo-dicom/fo-dicom#991]
Hi,
I have created a DicomServer using the C-Store SCP example. I am then sending a CMoveRequest in order to move  a study from ORTHANC to my Server. The images arrive where I expect without any problem. However, I am not able in my code to know which files have been transferred. Is there any way to do it ?
By putting a breakpoint at OnCStoreRequest in the CStoreSCP class, I can see that this information is available at that time,however it is lost when the  request.OnResponseReceived runs.As  request.OnResponseReceived fires with DicomStatus.Pending for every file I guess that there should be a way to get the file information there.

Thank you very much for your support.

**Comment by gofal** [comment]
I am not sure if I get your question.
C-move means, that you have two different independent associations:

- the c-move client sends a c-move request to a pacs (Association 1)
- the pacs then creates a new c-store request to the MoveDestination (Association 2)
- then the pacs sends the file to the store (Association 2) and also sends some messages to the c-move-scu (Association 1) with very little information like Status ("pending") and number of instances sent.
- when all files have been sent, the pacs closes the store-connection (Association 2). Then it sends a status messages ("ready") to the c-move-scu and closes this connection (Association 1).

So you see, the OnCStoreRequest within your StoreSCP works on Association 2 and has all the file-information
The request.OnResponseReceived witin your c-move-scu works on Association 1 and will never have more information other than the status and the progress (number of instances sent).

**Comment by janadel** [comment]
Thanks for your answer.
My intention is to automatically perform processing on the images which arrive to my C-store which acts as the move destination. As I am not the client which initiates the c-move I don't care about the information of Association 1. I need to know outside the StoreSCP class when an association opens,when it closes and what files arrived during this specific association. The only solution I have found until now is to use a static class and from within the StoreSCP class call respective methods of my static class. The problem is that I haven't found a way to distinguish between different associations which may run at the same time.

Thank you for your help.

**Comment by gofal** [comment]
Ok, now its clearer to me.

When you start the DicomServer, you called `dicomServer.Create<YourStoreSCPClass>(port,...)`.
This `YourStoreSCPClass` inherits from `DicomService` and is the answer to your problem.

The DicomServer listens on the specified port. And whenever an association arrives, a new instance of YourStoreSCPClass is created and this instance stays alive and handles all the communication done via this connection.
-> There is exactly one instance per association.

This means, you can create some private fields in `YourStoreSCPClass` like an unique int or an Guid or whatever. Then within all methods you can use this class field to identify the association. If you create an integer field named `counter`, that you initialize with 0 in constructor and which you increment in every `OnCStoreRequest`, then this gives you the number of files within the association...
And of course you get the events AssociationOpen and AssociationClose within the methods, that implement the interface `IDicomServiceProvider`.

The problem of notifying someone outside the storescp is out of scope of fo-dicom. You can use static classes, Messaging-mechanisms like MSMQ, creating database-entries which are then peridically checked by an other process outside storescp, .....

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.
