### ISSUE TITLE
работа с fo-dicom

### ISSUE THREAD

**Issue by alarihwertbars** [fo-dicom/fo-dicom#995]
Добрый день. Подскажите, поможет ли эта библиотека для выполнения следующей задачи:
имеется сайт на котором есть карточка пациента, к ней привязана папка с с несколькими сериями снимков (примерно 1000 файлов каждая серия). Сейчас я вынужден загружать на сервер файлы в формате .jpg, а хотелось бы сразу .dcm, но стандартный html не открывает такую строку: `<img id="0" name="imgScrin" src="/Images/1/2020-02-14/IMG-0001-00031.dcm" style="width:100%">` так тег img поддерживает только картинки.

**Comment by gofal** [comment]
google translated this text to:

> Good afternoon. Tell me if this library will help to perform the following task:
There is a site on which there is a patient card, a folder with several series of pictures is attached to it (approximately 1000 files each series). Now I have to upload .jpg files to the server, but I would like to immediately .dcm, but the standard html does not open such a line: <img id = "0" name = "imgScrin" src = "/ Images / 1 / 2020-02 -14 / IMG-0001-00031.dcm "style =" width: 100% "> so the img tag only supports pictures.

**Comment by gofal** [comment]
So you have a lot of dcm-files, want to generate jpeg from these DICOM files, and then upload to a server with html.
fo-dicom can help you to convert the dcm files to jpeg:

Render Image to JPEG
        
        var image = new DicomImage(@"test.dcm");
        image.RenderImage().AsBitmap().Save(@"test.jpg");                     // Windows Forms

**Comment by alarihwertbars** [comment]
> Таким образом, у вас есть много dcm-файлов, которые вы хотите создать jpeg из этих файлов DICOM, а затем загрузить на сервер с помощью html.
> fo-dicom может помочь вам конвертировать файлы dcm в jpeg:
> 
> Отрисовка изображения в формате JPEG
> 
> ```
>     var image = new DicomImage(@"test.dcm");
>     image.RenderImage().AsBitmap().Save(@"test.jpg");                     // Windows Forms
> ```

нет, я не хочу их конвертировать, я хочу что бы они сразу закачивались на сервер и потом от туду читались на html форме. У меня проект на asp.net core mvc

**Comment by gofal** [comment]
Well, html and the Webbrowsers supporting html have a limited numer of formats that they support. For images this are bmp, jpeg, gif, png, svg, etc. But DICOM is definitly not part of it. Thats why such libraries like fo-dicom are needed. You cannot display a dicomimage in html without converting.

if you want to read and convert the dicomfile on the clientside within the browser, then you need a javascript based dicom-viewer. (https://github.com/epam/med3web, https://github.com/cornerstonejs/cornerstone, ... )

**Comment by gofal** [comment]
Close this due to inactivity. Please feel free to reopen this issue if you still face problems.
