### ISSUE TITLE
3D calculations

### ISSUE THREAD

**Issue by gofal** [fo-dicom/fo-dicom#997]
This is not an bug or enhancement issue, but rather a discussion thread for calcualtions in 3d.

from Gitter:

> Does anyone have any idea on how to implement the 3D cursor functionality?
> Examples:
> https://www.youtube.com/watch?v=TaJG-B_Aw_o
> https://www.youtube.com/watch?v=Z8hhnMFP7H4

**Comment by gofal** [comment]
If you have a stack of images, then you need the tags:
- DicomTag.ImagepositionPatient: a 3D-Point of the top left corner
- DicomTag.ImageOrientationPatient: two 3d-vectors normalized to length 1. the first pointing in x-direction, the second in y-direction
- DicomTag.PixelSpacing: two values for pixel size in x- and y-direction

You should be familar, with how to calculate the Patient-coordinate from image (x,y) coordinates. You need it for measuring etc all the time:

    Patient_xyz = ImagePositionPatient + x * PixelSpacing_x * ImageOrientationRow + y * PixelSpacing_y * ImageOrientationColumn;

If you then have a stack of images, you can calculate the vector from the ImagePositionPatient of the first image to the ImagePositionPatient of the second image. This vector should be the same between all neighbour images, otherwise this method will not work.

Now you can build up a 4D-matrix of the form:
- the first column is the ImageOrientationRow multiplied with PixelSpacing_x, and 0 as fourth value
- the second column is the ImageOrientationColumn multiplied with PixelSpacing_y, and 0 as fourth value
- the third column is the vector between two neighbour ImagepositionPatients, and 0 as fourth value
- the fourth colum is the ImagePatientPosition of the first image in your stack, and 1 as fourth value.

with this Matrix (I call it *ImageToPatientSpace*) you can calculate the coordinates if you have the three values: ImageNumber (0-based), x and y within this number by:

    PointInPatientSpace = ImageToPatientSpace-Matrix * (x, y, imagenumber, 1)

So the trick is now: you calculate such a Matrix for all your stacks, and you invert this matrix. This inverted matrix you then call *PatientToImageSpace*-Matrix.

If you click on a image within a stack, you use this stacks ImageToPatientSpace-matrix and calculate the Patient-Coordinates. Then you take the inverted PatientToImageSpace matrices of the other stakcs, multiply it with your Patient-Coordinates, and then you get the (x, y, imagenumber) values for in the other stacks, where you have to put your marker.

**Comment by gofal** [comment]
As said, this method only works, if your stack is really straight and all the vectors between the ImagePositionPatients are the same.

If this is not the case, then you have no other chance, than to use 3D-vectors for every image (similar as in class FrameGeometry.cs) with the Row-Direction, the Column-Direction and the Normal-Vector as columns. 

if you click into a image, you then can calculate the Patient-Coordinates of the (x,y) point in the image.
in the other stacks, you then have to multiply this Patient-Coordinate with the inverted matrix to a image, you will get 3 values: the x and y as coordinates within the image, and the third value is the distance to the image. So you have to do this calculation to all of your images in the stack and display that image, where the third value is the lowest value.
Of course you should do it smarter and not calculate for every image. Because if your stack is ordered you can do some approximations.

**Comment by hashitha** [comment]
Thanks @gofal for creating this thread. I don't really understand what you mean by the stack needs to be really straight. Do you mean we have to check if all the images in the stack have the same ImagePositionPatients? or are there any other tags we need to check as well?

**Comment by gofal** [comment]
Since the images are all within the same series means, that they have to be parallel and need to have the same pixel spacing etc. otherwise the stack would not be a valid DICOM. So I would check this only if you really find some invalid data.
What I mean is, that the Difference in ImagePositionPatients between two neighboring images have to be the same. There are some MR head series, where the axial images close to the eyes have 2 mm distance to each other and the distance grows, so that the images on the top of the head have 5 mm distance. For such series the first approach would not work.

**Comment by hashitha** [comment]
Thanks for the explanation, I didn't know that about the MR series. If we were to have support for both CT and MR, would you recommend going with just the second approach? or use the 1st approach if everything is straight and then the second approach if there is a mismatch?

**Comment by gofal** [comment]
10 years ago, when I implemented this, I used the strategy design pattern. When loading the stack I checked if the stack is straight and then created an instance that implemented the first approach, which is way faster, otherwise I created an instance of the second approach.

But of course I would not say that this is the only or the best solution. its just one way how it could be implemented in a reliable way.

**Comment by LavanyaGovindan** [comment]
Thanks @gofal. I really don't understand how it is possible to perform matrix multiplication between PatientToImageSpace and PatientCoordinate. Because the dimensionality of the PatientToImageSpace matrix is 4x4 and the dimensionality of PatientCoordinate is 1x3. Could you please clarify this?

**Comment by gofal** [comment]
This is because of the mathematics behind it. If you have a point in 3D and you apply a 3x3 Matrix, then the point is multiplied (y = a*x). This is a linear transformation. Meanin, that if you have double input, then you get the douple output etc. With this calculation, you can rotate a point or you can scale it, but you cannot translate a point. In order to be able to translate a point, you need a affine transformation (y = a*x +b). To achive this "+b" you can do a trick, by upscaling to 4th dimension. The top left 3x3 fields of this 4x4 Matrix are the rotation, and the 4th column is the translation vector.
To apply a point to this 4x4 matrix, you have to add an additional 4th value.
And now it become more interesting. A 1x3 Vector can have 2 different interpretations: it can be a fixed point in space, or it can be a direction in space. 
When you want to transform a point, then you should be able to rotate, scale and translate it, but if you have some direction (e.g. some length-measurement) then you only want to rotate and scale it but you do not want to applly translation on it.
That said: if you want to apply a Point-Vector to the transformation, then you have to add a 1 as the 4th number so that you get the 1x4 matrix [x y z 1], which you then apply to the 4x4 matrix and you just ignore the 4th number of the result.
If you want to apply a Direction-Vector to the transformation, then you have to add a 0 as the 4th number so that you get the 1x4 matrix [x y z 0], which you then apply to the 4x4 matrix and you jist ignore the 4th number of the result.

Does this explanation make it more clear?

**Comment by LavanyaGovindan** [comment]
Thank you, @gofal for clear explanation. Can I have the link for the second approach for the cases where the ImagePositionPatient vector is not equal?

**Comment by gofal** [comment]
There is no link. I develloped it for a Company and it is closed Sourcecode. But u did my best to describe the approach how you would implement it.
