### ISSUE TITLE
Parse VR string to DicomItem?

### ISSUE THREAD

**Issue by gasupidupi** [fo-dicom/fo-dicom#998]
### fo-dicom version and OS/platform
fo-dicom: 4.0.4
OS: windows
TargetFramework: netcoreapp3.1

I have to insert DicomItems into a DicomDataset. The reason I'm creating DicomItems first and not using the normal DicomDataset.Add<T>(DicomTag tag, params T[] values) method is because the given VR can differ from the official DicomTags VR.

What I have is a string with the VR e.g. "AE" or "DA", the DicomTag and the value as an object. The way I'm doing it now is writing a switch case for every single VR to create the specific DicomItem:
`case "AE":`
`dicomItem = new DicomApplicationEntity(dicomTag, insertionValue);`
`break;`
`case "AS":`
`dicomItem = new DicomAgeString(dicomTag, insertionValue);`
`break;`

One solution would be to overwrite the official VR by creating a custom Tag as described here which seems to have changed slightly so I couldn't manage to change the VR of a new tag:
https://stackoverflow.com/questions/28959966/how-to-change-vr-tag-of-dicom-file-with-clearcanvas

What I would prefer is something that gives me the right kind of DicomItem using the VR string. For example like this:
`DicomItem.Parse(string VRstring, Object value)`

Is there something like that or any more efficient workaround than what I'm currently doing already in place and how does the constructor for DicomTag work? Do I use the DicomPrivateCreator parameter to change the VR and how does such a creator look like?

**Comment by gofal** [comment]
First of all: 

> because the given VR can differ from the official DicomTags VR

This is a very bad design. The official DicomTags are defined in DICOM standard and every other application will ignore whatever you are inserting there but will expect the VR as defined in standard.
So when you write other values into this tag, then only your own application will be able to interpret it correctly later. For such use cases, where you want to insert information that noone else needs to able to read, DICOM defined the private Tags. These are the tags with odd group number. you can insert there any information you want with any VR you need.

Why don't you use private tags?

**Comment by gofal** [comment]
... just for the sake of completeness:
the parser is based in the IByteBuffer. This can either be a wrapper around a memorystream, a filestream, a bytearray or whatever.
so every DicomElement (DicomAgeString, DicomApplicationEntity, DicomDecimalString, ..) has a constructor with the DicomTag as first parameter and the IByteBuffer as second parameter.
This IByteBuffer can be asscessed via the public property `Buffer` of the dicomElement.

So if you do have a DicomElement of any type and you want to explicitly parse it into an other value, you can do something similar like that:

    DicomElement element = .... // from any source
    var elementAsShortString = new DicomShortString(element.Tag, element.Buffer);

**Comment by gofal** [comment]
and one more, just for documentation. If the private element is a sequence, then this code helps:

    private static bool IsUnknownTagPrivateSequence(DicomItem dicomItem, DicomDataset dataset, out DicomSequence sequence)
    {
        sequence = null;
        if (dicomItem is DicomOtherByte otherByte && dicomItem.Tag.Element == DicomTag.Parse("3283,1002").Element)
        {
            var memoryStream = new MemoryStream(otherByte.Buffer.Data);
            var dataSet = new DicomDataset();
            var result = new DicomReader().Read(new StreamByteSource(memoryStream), new DicomDatasetReaderObserver(dataSet));
            if (result != DicomReaderResult.Success)
            {
                return false;
            }
            sequence = dataSet.GetSequence(DicomTag.Item);

            return true;
        }
        return false;
    }
