### ISSUE TITLE
fo-dicom.json for .net standard?

### ISSUE THREAD

**Issue by jackliums** [fo-dicom/fo-dicom#999]
Is there any reason fo-dicom.JSON NuGet package does not include support for .NET standard? Right now, it's only targeting net45, netcore45 (which is for windows store app), and wpa81. It would be nice to be able to use the package for .Net Core applications.

**Comment by gofal** [comment]
fo-dicom 4 and prior are built in PCL (portable). You can use fo-dicom.json on every current platform without problem.

PCL is deprecated and netstandard should be used instead.

fo-dicom 5.0 completely built in netstandard 2.0 is on the road. There of course all depending projects as fo-dicom.json, fo-dicom.nlog, ... will be netstandard 2.0

**Comment by jackliums** [comment]
Adding fo-dicom.json NuGet package to .NET Core application results in the following errors:

Installing fo-dicom.Json 4.0.4.
NU1701: Package 'fo-dicom.Json 4.0.4' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.

I will try manually edit the project and include NoWarn="NU1701" to see if that would work.

**Comment by jackliums** [comment]
By using `<PackageReference Include="fo-dicom.Json" Version="4.0.5" NoWarn="NU1701" />`, I was able to ignore the warning and add the NuGet package reference. However, it would be nice to not have to do that. 

I just saw #1024 so maybe it will be done as part of that work?

**Comment by gofal** [comment]
The package fo-dicom.json references newtonsoft. issue #1024 includes the json converter directly into fo-dicom without additional reference. So this should be better :-)

**Comment by amoerie** [comment]
Closing as this is covered by #1024, give a shout if you think that is unfair.
